<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Lección 6 Contrastes de bondad de ajuste | AprendeR: Parte II</title>
  <meta name="description" content="Apuntes AprendeR bookdown::gitbook." />
  <meta name="generator" content="bookdown 0.20 and GitBook 2.6.7" />

  <meta property="og:title" content="Lección 6 Contrastes de bondad de ajuste | AprendeR: Parte II" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Apuntes AprendeR bookdown::gitbook." />
  <meta name="github-repo" content="AprendeR-UIB/AprendeR2" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Lección 6 Contrastes de bondad de ajuste | AprendeR: Parte II" />
  
  <meta name="twitter:description" content="Apuntes AprendeR bookdown::gitbook." />
  

<meta name="author" content="The UIB-AprendeR team" />


<meta name="date" content="2021-03-05" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="chap-contrastes.html"/>
<link rel="next" href="chap-indep.html"/>
<script src="libs/header-attrs-2.6/header-attrs.js"></script>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />











<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">AprendeR: Parte II</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Presentación</a></li>
<li class="part"><span><b>Parte II: Estadística inferencial</b></span></li>
<li class="chapter" data-level="1" data-path="chap-distr.html"><a href="chap-distr.html"><i class="fa fa-check"></i><b>1</b> Distribuciones de probabilidad</a>
<ul>
<li class="chapter" data-level="1.1" data-path="chap-distr.html"><a href="chap-distr.html#ejercicios"><i class="fa fa-check"></i><b>1.1</b> Ejercicios</a>
<ul>
<li class="chapter" data-level="" data-path="chap-distr.html"><a href="chap-distr.html#test"><i class="fa fa-check"></i>Test</a></li>
<li class="chapter" data-level="" data-path="chap-distr.html"><a href="chap-distr.html#problemas"><i class="fa fa-check"></i>Problemas</a></li>
<li class="chapter" data-level="" data-path="chap-distr.html"><a href="chap-distr.html#respuestas-al-test"><i class="fa fa-check"></i>Respuestas al test</a></li>
<li class="chapter" data-level="" data-path="chap-distr.html"><a href="chap-distr.html#soluciones-sucintas-de-los-problemas"><i class="fa fa-check"></i>Soluciones sucintas de los problemas</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="chap-muestreo.html"><a href="chap-muestreo.html"><i class="fa fa-check"></i><b>2</b> Conceptos básicos de muestreo</a>
<ul>
<li class="chapter" data-level="2.1" data-path="chap-muestreo.html"><a href="chap-muestreo.html#sec:muestreo"><i class="fa fa-check"></i><b>2.1</b> Tipos de muestreo</a></li>
<li class="chapter" data-level="2.2" data-path="chap-muestreo.html"><a href="chap-muestreo.html#muestreo-aleatorio-con-r"><i class="fa fa-check"></i><b>2.2</b> Muestreo aleatorio con R</a></li>
<li class="chapter" data-level="2.3" data-path="chap-muestreo.html"><a href="chap-muestreo.html#guía-rápida"><i class="fa fa-check"></i><b>2.3</b> Guía rápida</a></li>
<li class="chapter" data-level="2.4" data-path="chap-distr.html"><a href="chap-distr.html#ejercicios"><i class="fa fa-check"></i><b>2.4</b> Ejercicios</a>
<ul>
<li class="chapter" data-level="" data-path="chap-distr.html"><a href="chap-distr.html#test"><i class="fa fa-check"></i>Test</a></li>
<li class="chapter" data-level="" data-path="chap-distr.html"><a href="chap-distr.html#problemas"><i class="fa fa-check"></i>Problemas</a></li>
<li class="chapter" data-level="" data-path="chap-distr.html"><a href="chap-distr.html#respuestas-al-test"><i class="fa fa-check"></i>Respuestas al test</a></li>
<li class="chapter" data-level="" data-path="chap-distr.html"><a href="chap-distr.html#soluciones-sucintas-de-los-problemas"><i class="fa fa-check"></i>Soluciones sucintas de los problemas</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="chap-estimacion.html"><a href="chap-estimacion.html"><i class="fa fa-check"></i><b>3</b> Estimación puntual</a>
<ul>
<li class="chapter" data-level="3.1" data-path="chap-estimacion.html"><a href="chap-estimacion.html#estimación-máximo-verosímil"><i class="fa fa-check"></i><b>3.1</b> Estimación máximo verosímil</a></li>
<li class="chapter" data-level="3.2" data-path="chap-muestreo.html"><a href="chap-muestreo.html#guía-rápida"><i class="fa fa-check"></i><b>3.2</b> Guía rápida</a></li>
<li class="chapter" data-level="3.3" data-path="chap-distr.html"><a href="chap-distr.html#ejercicios"><i class="fa fa-check"></i><b>3.3</b> Ejercicios</a>
<ul>
<li class="chapter" data-level="" data-path="chap-distr.html"><a href="chap-distr.html#test"><i class="fa fa-check"></i>Test</a></li>
<li class="chapter" data-level="" data-path="chap-distr.html"><a href="chap-distr.html#problemas"><i class="fa fa-check"></i>Problemas</a></li>
<li class="chapter" data-level="" data-path="chap-distr.html"><a href="chap-distr.html#respuestas-al-test"><i class="fa fa-check"></i>Respuestas al test</a></li>
<li class="chapter" data-level="" data-path="chap-distr.html"><a href="chap-distr.html#soluciones-sucintas-de-los-problemas"><i class="fa fa-check"></i>Soluciones sucintas de los problemas</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="chap-IC.html"><a href="chap-IC.html"><i class="fa fa-check"></i><b>4</b> Intervalos de confianza</a>
<ul>
<li class="chapter" data-level="4.1" data-path="chap-IC.html"><a href="chap-IC.html#sec:ICT"><i class="fa fa-check"></i><b>4.1</b> Intervalo de confianza para la media basado en la t de Student</a></li>
<li class="chapter" data-level="4.2" data-path="chap-IC.html"><a href="chap-IC.html#intervalos-de-confianza-para-la-proporción-poblacional"><i class="fa fa-check"></i><b>4.2</b> Intervalos de confianza para la proporción poblacional</a></li>
<li class="chapter" data-level="4.3" data-path="chap-IC.html"><a href="chap-IC.html#sec:ICvar"><i class="fa fa-check"></i><b>4.3</b> Intervalo de confianza para la varianza de una población normal</a></li>
<li class="chapter" data-level="4.4" data-path="chap-IC.html"><a href="chap-IC.html#bootstrap"><i class="fa fa-check"></i><b>4.4</b> Bootstrap</a></li>
<li class="chapter" data-level="4.5" data-path="chap-muestreo.html"><a href="chap-muestreo.html#guía-rápida"><i class="fa fa-check"></i><b>4.5</b> Guía rápida</a></li>
<li class="chapter" data-level="4.6" data-path="chap-distr.html"><a href="chap-distr.html#ejercicios"><i class="fa fa-check"></i><b>4.6</b> Ejercicios</a>
<ul>
<li class="chapter" data-level="" data-path="chap-distr.html"><a href="chap-distr.html#test"><i class="fa fa-check"></i>Test</a></li>
<li class="chapter" data-level="" data-path="chap-distr.html"><a href="chap-distr.html#problemas"><i class="fa fa-check"></i>Problemas</a></li>
<li class="chapter" data-level="" data-path="chap-distr.html"><a href="chap-distr.html#respuestas-al-test"><i class="fa fa-check"></i>Respuestas al test</a></li>
<li class="chapter" data-level="" data-path="chap-distr.html"><a href="chap-distr.html#soluciones-sucintas-de-los-problemas"><i class="fa fa-check"></i>Soluciones sucintas de los problemas</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="chap-contrastes.html"><a href="chap-contrastes.html"><i class="fa fa-check"></i><b>5</b> Contrastes de hipótesis</a>
<ul>
<li class="chapter" data-level="5.1" data-path="chap-contrastes.html"><a href="chap-contrastes.html#contrastes-para-medias"><i class="fa fa-check"></i><b>5.1</b> Contrastes para medias</a>
<ul>
<li class="chapter" data-level="" data-path="chap-contrastes.html"><a href="chap-contrastes.html#el-test-t"><i class="fa fa-check"></i>El test t</a></li>
<li class="chapter" data-level="" data-path="chap-contrastes.html"><a href="chap-contrastes.html#tests-no-paramétricos"><i class="fa fa-check"></i>Tests no paramétricos</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="chap-contrastes.html"><a href="chap-contrastes.html#contrastes-para-varianzas"><i class="fa fa-check"></i><b>5.2</b> Contrastes para varianzas</a></li>
<li class="chapter" data-level="5.3" data-path="chap-contrastes.html"><a href="chap-contrastes.html#contrastes-para-proporciones"><i class="fa fa-check"></i><b>5.3</b> Contrastes para proporciones</a></li>
<li class="chapter" data-level="5.4" data-path="chap-contrastes.html"><a href="chap-contrastes.html#cálculo-de-la-potencia-de-un-contraste"><i class="fa fa-check"></i><b>5.4</b> Cálculo de la potencia de un contraste</a></li>
<li class="chapter" data-level="5.5" data-path="chap-muestreo.html"><a href="chap-muestreo.html#guía-rápida"><i class="fa fa-check"></i><b>5.5</b> Guía rápida</a></li>
<li class="chapter" data-level="5.6" data-path="chap-distr.html"><a href="chap-distr.html#ejercicios"><i class="fa fa-check"></i><b>5.6</b> Ejercicios</a>
<ul>
<li class="chapter" data-level="" data-path="chap-contrastes.html"><a href="chap-contrastes.html#modelo-de-test"><i class="fa fa-check"></i>Modelo de test</a></li>
<li class="chapter" data-level="" data-path="chap-contrastes.html"><a href="chap-contrastes.html#ejercicios-1"><i class="fa fa-check"></i>Ejercicios</a></li>
<li class="chapter" data-level="" data-path="chap-distr.html"><a href="chap-distr.html#respuestas-al-test"><i class="fa fa-check"></i>Respuestas al test</a></li>
<li class="chapter" data-level="" data-path="chap-contrastes.html"><a href="chap-contrastes.html#respuestas-sucintas-a-los-ejercicios"><i class="fa fa-check"></i>Respuestas sucintas a los ejercicios</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="chap-bondad.html"><a href="chap-bondad.html"><i class="fa fa-check"></i><b>6</b> Contrastes de bondad de ajuste</a>
<ul>
<li class="chapter" data-level="6.1" data-path="chap-bondad.html"><a href="chap-bondad.html#pruebas-gráficas-q-q-plots"><i class="fa fa-check"></i><b>6.1</b> Pruebas gráficas: Q-Q-plots</a></li>
<li class="chapter" data-level="6.2" data-path="chap-bondad.html"><a href="chap-bondad.html#el-test-chi2-de-pearson"><i class="fa fa-check"></i><b>6.2</b> El test <span class="math inline">\(\chi^2\)</span> de Pearson</a></li>
<li class="chapter" data-level="6.3" data-path="chap-bondad.html"><a href="chap-bondad.html#el-test-chi2-para-distribuciones-continuas"><i class="fa fa-check"></i><b>6.3</b> El test <span class="math inline">\(\chi^2\)</span> para distribuciones continuas</a></li>
<li class="chapter" data-level="6.4" data-path="chap-bondad.html"><a href="chap-bondad.html#el-test-de-kolgomorov-smirnov"><i class="fa fa-check"></i><b>6.4</b> El test de Kolgomorov-Smirnov</a></li>
<li class="chapter" data-level="6.5" data-path="chap-bondad.html"><a href="chap-bondad.html#tests-de-normalidad"><i class="fa fa-check"></i><b>6.5</b> Tests de normalidad</a></li>
<li class="chapter" data-level="6.6" data-path="chap-muestreo.html"><a href="chap-muestreo.html#guía-rápida"><i class="fa fa-check"></i><b>6.6</b> Guía rápida</a></li>
<li class="chapter" data-level="6.7" data-path="chap-distr.html"><a href="chap-distr.html#ejercicios"><i class="fa fa-check"></i><b>6.7</b> Ejercicios</a>
<ul>
<li class="chapter" data-level="" data-path="chap-contrastes.html"><a href="chap-contrastes.html#modelo-de-test"><i class="fa fa-check"></i>Modelo de test</a></li>
<li class="chapter" data-level="" data-path="chap-distr.html"><a href="chap-distr.html#problemas"><i class="fa fa-check"></i>Problemas</a></li>
<li class="chapter" data-level="" data-path="chap-distr.html"><a href="chap-distr.html#respuestas-al-test"><i class="fa fa-check"></i>Respuestas al test</a></li>
<li class="chapter" data-level="" data-path="chap-distr.html"><a href="chap-distr.html#soluciones-sucintas-de-los-problemas"><i class="fa fa-check"></i>Soluciones sucintas de los problemas</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="chap-indep.html"><a href="chap-indep.html"><i class="fa fa-check"></i><b>7</b> Contrastes de independencia y homogeneidad</a>
<ul>
<li class="chapter" data-level="7.1" data-path="chap-indep.html"><a href="chap-indep.html#tablas-de-contingencia"><i class="fa fa-check"></i><b>7.1</b> Tablas de contingencia</a></li>
<li class="chapter" data-level="7.2" data-path="chap-indep.html"><a href="chap-indep.html#contraste-de-independencia"><i class="fa fa-check"></i><b>7.2</b> Contraste de independencia</a></li>
<li class="chapter" data-level="7.3" data-path="chap-indep.html"><a href="chap-indep.html#sec:hom"><i class="fa fa-check"></i><b>7.3</b> Contraste de homogeneidad</a></li>
<li class="chapter" data-level="7.4" data-path="chap-indep.html"><a href="chap-indep.html#potencia-de-un-contraste-chi2"><i class="fa fa-check"></i><b>7.4</b> Potencia de un contraste <span class="math inline">\(\chi^2\)</span></a></li>
<li class="chapter" data-level="7.5" data-path="chap-muestreo.html"><a href="chap-muestreo.html#guía-rápida"><i class="fa fa-check"></i><b>7.5</b> Guía rápida</a></li>
<li class="chapter" data-level="7.6" data-path="chap-distr.html"><a href="chap-distr.html#ejercicios"><i class="fa fa-check"></i><b>7.6</b> Ejercicios</a>
<ul>
<li class="chapter" data-level="" data-path="chap-contrastes.html"><a href="chap-contrastes.html#modelo-de-test"><i class="fa fa-check"></i>Modelo de test</a></li>
<li class="chapter" data-level="" data-path="chap-contrastes.html"><a href="chap-contrastes.html#ejercicios-1"><i class="fa fa-check"></i>Ejercicios</a></li>
<li class="chapter" data-level="" data-path="chap-distr.html"><a href="chap-distr.html#respuestas-al-test"><i class="fa fa-check"></i>Respuestas al test</a></li>
<li class="chapter" data-level="" data-path="chap-distr.html"><a href="chap-distr.html#soluciones-sucintas-de-los-problemas"><i class="fa fa-check"></i>Soluciones sucintas de los problemas</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="chap-estmult.html"><a href="chap-estmult.html"><i class="fa fa-check"></i><b>8</b> Introducción a la estadística descriptiva multidimensional</a>
<ul>
<li class="chapter" data-level="8.1" data-path="chap-estmult.html"><a href="chap-estmult.html#matrices-de-datos-cuantitativos"><i class="fa fa-check"></i><b>8.1</b> Matrices de datos cuantitativos</a></li>
<li class="chapter" data-level="8.2" data-path="chap-estmult.html"><a href="chap-estmult.html#transformaciones-lineales"><i class="fa fa-check"></i><b>8.2</b> Transformaciones lineales</a></li>
<li class="chapter" data-level="8.3" data-path="chap-estmult.html"><a href="chap-estmult.html#covarianzas-y-correlaciones"><i class="fa fa-check"></i><b>8.3</b> Covarianzas y correlaciones</a></li>
<li class="chapter" data-level="8.4" data-path="chap-estmult.html"><a href="chap-estmult.html#correlación-de-spearman"><i class="fa fa-check"></i><b>8.4</b> Correlación de Spearman</a></li>
<li class="chapter" data-level="8.5" data-path="chap-estmult.html"><a href="chap-estmult.html#contrastes-de-correlación"><i class="fa fa-check"></i><b>8.5</b> Contrastes de correlación</a></li>
<li class="chapter" data-level="8.6" data-path="chap-estmult.html"><a href="chap-estmult.html#un-ejemplo"><i class="fa fa-check"></i><b>8.6</b> Un ejemplo</a></li>
<li class="chapter" data-level="8.7" data-path="chap-estmult.html"><a href="chap-estmult.html#representación-gráfica-de-datos-multidimensionales"><i class="fa fa-check"></i><b>8.7</b> Representación gráfica de datos multidimensionales</a></li>
<li class="chapter" data-level="8.8" data-path="chap-muestreo.html"><a href="chap-muestreo.html#guía-rápida"><i class="fa fa-check"></i><b>8.8</b> Guía rápida</a></li>
<li class="chapter" data-level="8.9" data-path="chap-distr.html"><a href="chap-distr.html#ejercicios"><i class="fa fa-check"></i><b>8.9</b> Ejercicios</a>
<ul>
<li class="chapter" data-level="" data-path="chap-contrastes.html"><a href="chap-contrastes.html#modelo-de-test"><i class="fa fa-check"></i>Modelo de test</a></li>
<li class="chapter" data-level="" data-path="chap-distr.html"><a href="chap-distr.html#problemas"><i class="fa fa-check"></i>Problemas</a></li>
<li class="chapter" data-level="" data-path="chap-distr.html"><a href="chap-distr.html#respuestas-al-test"><i class="fa fa-check"></i>Respuestas al test</a></li>
<li class="chapter" data-level="" data-path="chap-distr.html"><a href="chap-distr.html#soluciones-sucintas-de-los-problemas"><i class="fa fa-check"></i>Soluciones sucintas de los problemas</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="chap-ANOVA.html"><a href="chap-ANOVA.html"><i class="fa fa-check"></i><b>9</b> ANOVA básico</a>
<ul>
<li class="chapter" data-level="9.1" data-path="chap-ANOVA.html"><a href="chap-ANOVA.html#sec:modelos"><i class="fa fa-check"></i><b>9.1</b> Los modelos del ANOVA en R</a></li>
<li class="chapter" data-level="9.2" data-path="chap-ANOVA.html"><a href="chap-ANOVA.html#sec:ANOVA-1"><i class="fa fa-check"></i><b>9.2</b> ANOVA de un factor</a></li>
<li class="chapter" data-level="9.3" data-path="chap-ANOVA.html"><a href="chap-ANOVA.html#anova-de-bloques-completos-aleatorios"><i class="fa fa-check"></i><b>9.3</b> ANOVA de bloques completos aleatorios</a></li>
<li class="chapter" data-level="9.4" data-path="chap-ANOVA.html"><a href="chap-ANOVA.html#sec:ANOVA2"><i class="fa fa-check"></i><b>9.4</b> ANOVA de dos vías</a></li>
<li class="chapter" data-level="9.5" data-path="chap-ANOVA.html"><a href="chap-ANOVA.html#condiciones-del-anova"><i class="fa fa-check"></i><b>9.5</b> Condiciones del ANOVA</a></li>
<li class="chapter" data-level="9.6" data-path="chap-ANOVA.html"><a href="chap-ANOVA.html#sec:pares"><i class="fa fa-check"></i><b>9.6</b> Comparaciones de pares de medias</a>
<ul>
<li class="chapter" data-level="9.6.1" data-path="chap-ANOVA.html"><a href="chap-ANOVA.html#tests-t-por-parejas"><i class="fa fa-check"></i><b>9.6.1</b> Tests t por parejas</a></li>
<li class="chapter" data-level="9.6.2" data-path="chap-ANOVA.html"><a href="chap-ANOVA.html#test-de-duncan"><i class="fa fa-check"></i><b>9.6.2</b> Test de Duncan</a></li>
<li class="chapter" data-level="9.6.3" data-path="chap-ANOVA.html"><a href="chap-ANOVA.html#método-de-tukey"><i class="fa fa-check"></i><b>9.6.3</b> Método de Tukey</a></li>
</ul></li>
<li class="chapter" data-level="9.7" data-path="chap-ANOVA.html"><a href="chap-ANOVA.html#métodos-no-paramétricos"><i class="fa fa-check"></i><b>9.7</b> Métodos no paramétricos</a></li>
<li class="chapter" data-level="9.8" data-path="chap-muestreo.html"><a href="chap-muestreo.html#guía-rápida"><i class="fa fa-check"></i><b>9.8</b> Guía rápida</a></li>
<li class="chapter" data-level="9.9" data-path="chap-distr.html"><a href="chap-distr.html#ejercicios"><i class="fa fa-check"></i><b>9.9</b> Ejercicios</a>
<ul>
<li class="chapter" data-level="" data-path="chap-distr.html"><a href="chap-distr.html#test"><i class="fa fa-check"></i>Test</a></li>
<li class="chapter" data-level="9.9.1" data-path="chap-ANOVA.html"><a href="chap-ANOVA.html#ejercicio"><i class="fa fa-check"></i><b>9.9.1</b> Ejercicio</a></li>
<li class="chapter" data-level="" data-path="chap-distr.html"><a href="chap-distr.html#respuestas-al-test"><i class="fa fa-check"></i>Respuestas al test</a></li>
<li class="chapter" data-level="9.9.2" data-path="chap-ANOVA.html"><a href="chap-ANOVA.html#soluciones-sucintas-del-ejercicio"><i class="fa fa-check"></i><b>9.9.2</b> Soluciones sucintas del ejercicio</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="10" data-path="chap-regresion.html"><a href="chap-regresion.html"><i class="fa fa-check"></i><b>10</b> Regresión lineal</a>
<ul>
<li class="chapter" data-level="10.1" data-path="chap-regresion.html"><a href="chap-regresion.html#sec:1"><i class="fa fa-check"></i><b>10.1</b> El modelo de regresión lineal en R</a></li>
<li class="chapter" data-level="10.2" data-path="chap-regresion.html"><a href="chap-regresion.html#intervalos-de-confianza-en-el-modelo-de-regresión-lineal"><i class="fa fa-check"></i><b>10.2</b> Intervalos de confianza en el modelo de regresión lineal</a></li>
<li class="chapter" data-level="10.3" data-path="chap-regresion.html"><a href="chap-regresion.html#sec:seleccion"><i class="fa fa-check"></i><b>10.3</b> Selección del modelo en base al ajuste de los datos</a></li>
<li class="chapter" data-level="10.4" data-path="chap-regresion.html"><a href="chap-regresion.html#sec:diagn"><i class="fa fa-check"></i><b>10.4</b> Diagnósticos de regresión</a></li>
<li class="chapter" data-level="10.5" data-path="chap-muestreo.html"><a href="chap-muestreo.html#guía-rápida"><i class="fa fa-check"></i><b>10.5</b> Guía rápida</a></li>
<li class="chapter" data-level="10.6" data-path="chap-distr.html"><a href="chap-distr.html#ejercicios"><i class="fa fa-check"></i><b>10.6</b> Ejercicios</a>
<ul>
<li class="chapter" data-level="" data-path="chap-distr.html"><a href="chap-distr.html#test"><i class="fa fa-check"></i>Test</a></li>
<li class="chapter" data-level="" data-path="chap-distr.html"><a href="chap-distr.html#respuestas-al-test"><i class="fa fa-check"></i>Respuestas al test</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="11" data-path="chap-clustering.html"><a href="chap-clustering.html"><i class="fa fa-check"></i><b>11</b> <em>Clustering</em> básico</a>
<ul>
<li class="chapter" data-level="11.1" data-path="chap-clustering.html"><a href="chap-clustering.html#método-de-k-medias-o-k-means"><i class="fa fa-check"></i><b>11.1</b> Método de k-medias o <em>k-means</em></a></li>
<li class="chapter" data-level="11.2" data-path="chap-clustering.html"><a href="chap-clustering.html#elección-del-número-de-clusters"><i class="fa fa-check"></i><b>11.2</b> Elección del número de <em>clusters</em></a></li>
<li class="chapter" data-level="11.3" data-path="chap-clustering.html"><a href="chap-clustering.html#métodos-jerárquicos-aglomerativos"><i class="fa fa-check"></i><b>11.3</b> Métodos jerárquicos aglomerativos</a></li>
<li class="chapter" data-level="11.4" data-path="chap-muestreo.html"><a href="chap-muestreo.html#guía-rápida"><i class="fa fa-check"></i><b>11.4</b> Guía rápida</a></li>
<li class="chapter" data-level="11.5" data-path="chap-distr.html"><a href="chap-distr.html#ejercicios"><i class="fa fa-check"></i><b>11.5</b> Ejercicios</a>
<ul>
<li class="chapter" data-level="" data-path="chap-distr.html"><a href="chap-distr.html#test"><i class="fa fa-check"></i>Test</a></li>
<li class="chapter" data-level="" data-path="chap-distr.html"><a href="chap-distr.html#respuestas-al-test"><i class="fa fa-check"></i>Respuestas al test</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="12" data-path="extras-de-r-markdown.html"><a href="extras-de-r-markdown.html"><i class="fa fa-check"></i><b>12</b> Extras de <em>R Markdown</em></a>
<ul>
<li class="chapter" data-level="12.1" data-path="extras-de-r-markdown.html"><a href="extras-de-r-markdown.html#parámetros-de-los-chunks-de-r"><i class="fa fa-check"></i><b>12.1</b> Parámetros de los <em>chunks</em> de R</a></li>
<li class="chapter" data-level="12.2" data-path="extras-de-r-markdown.html"><a href="extras-de-r-markdown.html#los-chunks-en-modo-línea"><i class="fa fa-check"></i><b>12.2</b> Los <em>chunks</em> en modo línea</a></li>
<li class="chapter" data-level="12.3" data-path="extras-de-r-markdown.html"><a href="extras-de-r-markdown.html#figuras"><i class="fa fa-check"></i><b>12.3</b> Figuras</a></li>
<li class="chapter" data-level="12.4" data-path="extras-de-r-markdown.html"><a href="extras-de-r-markdown.html#tablas"><i class="fa fa-check"></i><b>12.4</b> Tablas</a></li>
<li class="chapter" data-level="12.5" data-path="extras-de-r-markdown.html"><a href="extras-de-r-markdown.html#fórmulas-matemáticas"><i class="fa fa-check"></i><b>12.5</b> Fórmulas matemáticas</a></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">AprendeR: Parte II</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="chap:bondad" class="section level1" number="6">
<h1><span class="header-section-number">Lección 6</span> Contrastes de bondad de ajuste</h1>
<p>Una de las condiciones habituales que requerimos sobre una muestra, por ejemplo, al razonar sobre la distribución de sus estadísticos o al realizar contrastes de hipótesis, es que la población de la que la hemos extraído siga una determinada distribución. En la Lección <a href="#chap:agrup"><strong>??</strong></a> de la primera parte del curso comprobábamos gráficamente el ajuste de una muestra a una distribución normal mediante histogramas y dibujando las curvas de densidad muestral y de densidad de la normal. En esta lección presentamos algunas instrucciones que implementan contrastes de <strong>bondad de ajuste</strong> (<em>goodness of fit</em>), técnicas cuantitativas que permiten decidir si los datos de una muestra “se ajustan” a una determinada distribución de probabilidad, es decir, si la variable aleatoria que los ha generado sigue o no esta distribución de probabilidad.</p>
<p>Los contrastes de bondad de ajuste tienen el mismo significado que los explicados en la Lección <a href="chap-contrastes.html#chap:contrastes">5</a>. Se contrasta una hipótesis nula</p>
<ul>
<li><span class="math inline">\(H_0\)</span>: La variable aleatoria poblacional tiene distribución <span class="math inline">\(X\)</span></li>
</ul>
<p>contra la hipótesis alternativa</p>
<ul>
<li><span class="math inline">\(H_1\)</span>: La variable aleatoria poblacional <em>no</em> tiene distribución <span class="math inline">\(X\)</span></li>
</ul>
<p>Como siempre, para llevar a cabo el contraste tomamos una muestra aleatoria de la población. Entonces, obtenemos evidencia significativa de que la población no tiene distribución <span class="math inline">\(X\)</span> cuando es muy raro obtener nuestra muestra si la población tiene esta distribución. En este caso, rechazamos la hipótesis nula en favor de la alternativa. Si, en cambio, no es del todo inverosímil que la muestra se haya generado con la distribución <span class="math inline">\(X\)</span>, aceptamos la hipótesis nula “por defecto” y concluimos que la población sí que tiene esta distribución. Pero que aceptemos la hipótesis nula no nos da evidencia de que la población tenga distribución <span class="math inline">\(X\)</span>: simplemente nos dice que no encontramos motivos para rechazarlo. Naturalmente, a efectos prácticos, si aceptamos la hipótesis nula de que la población tiene la distribución <span class="math inline">\(X\)</span>, actuaremos como si creyéramos que efectivamente esta hipótesis es verdadera, por ejemplo a la hora de decidir que fórmulas usar para calcular un intervalo de confianza o para efectuar un contraste de hipótesis. Pero no estaremos seguros de que podamos emplear estas fórmulas sobre nuestra muestra, simplemente no tendremos motivos para dudarlo.</p>
<p>Los pasos habituales para contrastar la bondad del ajuste de una muestra a una distribución son los siguientes:</p>
<ol style="list-style-type: decimal">
<li><p>Fijar la familia de distribuciones teóricas a la que queremos ajustar los
datos. Esta familia estará parametrizada por uno o varios parámetros. Recordemos los ejemplos más comunes:</p>
<ul>
<li><p>Si la familia es la Bernoulli, el parámetro es <span class="math inline">\(p\)</span>: la probabilidad poblacional de éxito.</p></li>
<li><p>Si la familia es la Poisson, el parámetro es <span class="math inline">\(\lambda\)</span>: la esperanza.</p></li>
<li><p>Si la familia es la binomial, los parámetros son <span class="math inline">\(n\)</span> y <span class="math inline">\(p\)</span>: el tamaño de las muestras y la probabilidad de éxito, respectivamente.</p></li>
<li><p>Si la familia es la normal, los parámetros son <span class="math inline">\(\mu\)</span> y <span class="math inline">\(\sigma\)</span>: la esperanza y la desviación típica, respectivamente.</p></li>
<li><p>Si la familia es la <span class="math inline">\(\chi^2\)</span>, el parámetro es el número de grados de libertad.</p></li>
<li><p>Si la familia es la t de Student, el parámetro es de nuevo el número de grados de libertad.</p></li>
<li><p>Otras familias de distribuciones tienen parámetros de <strong>localización</strong> (<em>location</em>), <strong>escala</strong> (<em>scale</em>) o <strong>forma</strong> (<em>shape</em>), por lo que no nos ha de extrañar si R nos pide que asignemos parámetros con estos nombres.</p></li>
</ul></li>
<li><p>Si el diseño del experimento no fija sus valores, tendremos que estimar a partir de la muestra los valores de los parámetros que mejor se ajusten a nuestros datos. Ya hemos tratado la estimación de parámetros en la Lección <a href="chap-estimacion.html#chap:estimacion">3</a>.</p></li>
<li><p>Determinar qué tipo de contraste vamos a utilizar. En esta lección veremos dos tipos básicos de contrastes generales:</p>
<ul>
<li><p>El <strong>test <span class="math inline">\(\chi^2\)</span> de Pearson</strong>. Este test es válido tanto para variables discretas como para continuas, pero solo se puede aplicar a conjuntos grandes de datos (por fijar una cota concreta, de 30 o más elementos). Además, si el <strong>espacio muestral</strong>, es decir, el conjunto de resultados posibles, es infinito, es necesario agrupar estos resultados en un número finito de clases.</p></li>
<li><p>El <strong>test de Kolgomorov-Smirnov</strong>. Este test solo es válido para variables continuas, y compara la función de distribución acumulada muestral con la teórica. No requiere que la muestra sea grande, pero en cambio, en principio, no admite que los datos de la muestra se puedan repetir.<a href="#fn4" class="footnote-ref" id="fnref4"><sup>4</sup></a> Por desgracia, las repeticiones suelen ser habituales si la muestra es grande y la precisión de los datos es baja o la variabilidad de la población muestreada es pequeña.</p></li>
<li><p>Aparte, determinados tipos de distribuciones tienen sus contrastes de bondad de ajustes específicos. Este es el caso especialmente de la normal, para la que explicaremos algunos tests que permiten contrastar si una muestra proviene de <em>alguna</em> distribución normal.</p></li>
</ul></li>
<li><p>Realizar el contraste y redactar las conclusiones. Es conveniente apoyar los
resultados del contraste con gráficos. En esta lección explicaremos los <strong>gráficos cuantil-cuantil</strong>, o <strong>Q-Q-plots</strong>, que sirven para visualizar el ajuste de unos datos a una distribución conocida y son una buena alternativa a los histogramas con curvas de densidad.</p></li>
</ol>
<div id="pruebas-gráficas-q-q-plots" class="section level2" number="6.1">
<h2><span class="header-section-number">6.1</span> Pruebas gráficas: Q-Q-plots</h2>
<p>Para comparar la distribución de una muestra con una distribución poblacional teórica se pueden realizar diversas pruebas gráficas. En la Lección <a href="#chap:agrup"><strong>??</strong></a> de la primera parte del curso usábamos para ello histogramas con densidades estimadas y teóricas. En esta sección explicamos otro tipo de gráficos que pueden usarse con el mismo fin, los <strong>gráficos cuantil-cuantil</strong>, o, para abreviar, <strong>Q-Q-plots</strong>. Estos gráficos comparan los cuantiles observados de la muestra con los cuantiles teóricos de la distribución teórica.</p>
<div class="figure" style="text-align: center"><span id="fig:qqp1"></span>
<img src="AprendeR-Parte-II_files/figure-html/qqp1-1.png" alt="Q-Q-plot básico de la muestra del Ejemplo \@ref(exm:qqp-1) contra una t de Student con 4 grados de libertad." width="480" />
<p class="caption">
Figura 6.1: Q-Q-plot básico de la muestra del Ejemplo <a href="chap-bondad.html#exm:qqp-1">6.1</a> contra una t de Student con 4 grados de libertad.
</p>
</div>
<p>La Figura <a href="chap-bondad.html#fig:qqp1">6.1</a> muestra un Q-Q-plot. Cada punto corresponde a un cuantil: <em>grosso modo</em>, hay un punto para cada <span class="math inline">\(k/n\)</span>-cuantil, siendo <span class="math inline">\(n\)</span> la longitud de la muestra y <span class="math inline">\(k=1,\ldots,n\)</span>. Para cada uno de estos cuantiles, el punto correspondiente tiene abscisa el cuantil de la distribución teórica (en este caso, una t de Student con 4 grados de libertad) y ordenada el cuantil de la muestra. Por lo tanto, si el ajuste es bueno, para cada <span class="math inline">\(k/n\)</span>, el cuantil muestral y el cuantil teórico han de ser parecidos, de manera que los puntos del gráfico (les llamaremos <strong>Q-Q-puntos</strong>, para abreviar) han de estar cerca de la diagonal <span class="math inline">\(y=x\)</span>, que hemos añadido al gráfico. En general, se considera que un Q-Q-plot muestra un buen ajuste cuando no se observa una tendencia marcada de desviación respecto de la diagonal. Sin embargo, a menudo los Q-Q-plots son difíciles de interpretar, y es conveniente combinarlos con algún contraste de bondad de ajuste.</p>
<p>Hay varias maneras de producir Q-Q-plots con R. Aquí solo explicaremos una: la función <code>qqPlot</code> del paquete <strong>car</strong>. Su sintaxis básica es</p>
<div class="sourceCode" id="cb461"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb461-1"><a href="chap-bondad.html#cb461-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qqPlot</span>(x, <span class="at">distribution=</span>...,  parámetros, <span class="at">id=</span><span class="cn">FALSE</span>, ...)</span></code></pre></div>
<p>donde:</p>
<ul>
<li><p><code>x</code> es el vector con la muestra.</p></li>
<li><p>El parámetro <code>distribution</code> se ha de igualar al nombre de la familia de distribuciones entre comillas, y puede tomar como valor cualquier familia de distribuciones de la que R sepa calcular la densidad y los cuantiles: esto incluye las distribuciones que hemos estudiado hasta el momento: <code>"norm"</code>, <code>"binom"</code>, <code>"poisson"</code>, <code>"t"</code>, etc.</p></li>
<li><p>A continuación, se tienen que entrar los parámetros de la distribución, igualando su nombre habitual (<code>mean</code> para la media, <code>sd</code> para la desviación típica, <code>df</code> para los grados de libertad, etc.) a su valor. En algunos casos, si no se especifican los parámetros, <code>qqPlot</code> toma sus valores por defecto: por ejemplo, si queremos realizar un Q-Q-plot contra una normal y no especificamos los valores de la media y la desviación típica de la distribución teórica, <code>qqPlot</code> los toma iguales a 0 y 1, respectivamente.</p></li>
<li><p>Por defecto, el gráfico obtenido con la función <code>qqPlot</code> identifica los dos Q-Q-puntos con ordenadas más extremas. Para omitirlos, usad el parámetro <code>id=FALSE</code>.</p></li>
</ul>
<p>Otros parámetros a tener en cuenta:</p>
<ul>
<li><p><code>qqPlot</code> añade por defecto una rejilla al gráfico, que podéis eliminar con <code>grid=FALSE</code>.</p></li>
<li><p><code>qqPlot</code> añade por defecto una línea recta que une los Q-Q-puntos correspondientes al primer y tercer cuartil: se la llama <strong>recta cuartil-cuartil</strong>. Un buen ajuste de los Q-Q-puntos a esta recta significa que la muestra se ajusta a la distribución teórica, pero posiblemente con parámetros diferentes a los especificados. Os recomendamos mantenerla, pero si queréis eliminarla por ejemplo para substituirla por la diagonal <span class="math inline">\(y=x\)</span>, podéis usar el parámetro <code>line="none"</code>.</p></li>
<li><p><code>qqPlot</code> también añade dos curvas discontinuas que abrazan una “región de confianza del 95%” para el Q-Q-plot. Sin entrar en detalles, esta región contendría todos los Q-Q-puntos en un 95% de las ocasiones que tomáramos una muestra de la distribución teórica del mismo tamaño que la nuestra. Por lo tanto, si todos los Q-Q-puntos caen dentro de esta franja, no hay evidencia para rechazar que la muestra provenga de la distribución teórica. Esta franja de confianza es muy útil para interpretar el Q-Q-plot, pero la podéis eliminar con <code>envelope=FALSE</code>.</p></li>
<li><p>Se pueden usar los parámetros usuales de <code>plot</code> para poner nombres a los ejes, título, modificar el estilo de los puntos, etc., y otros parámetros específicos para modificar el aspecto del gráfico. Por ejemplo, <code>col.lines</code> sirve para especificar el color de las líneas que añade. Consultad la Ayuda de la función.</p></li>
</ul>

<div class="example">
<p><span id="exm:qqp-1" class="example"><strong>Ejemplo 6.1  </strong></span>Consideremos la siguiente muestra:</p>
</div>
<div class="sourceCode" id="cb462"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb462-1"><a href="chap-bondad.html#cb462-1" aria-hidden="true" tabindex="-1"></a>muestra<span class="ot">=</span><span class="fu">c</span>(<span class="fl">0.27</span>,<span class="fl">0.81</span>,<span class="sc">-</span><span class="fl">0.73</span>,<span class="sc">-</span><span class="fl">0.96</span>,<span class="fl">1.33</span>,<span class="fl">0.91</span>,<span class="sc">-</span><span class="fl">1.70</span>,<span class="fl">0.24</span>,<span class="sc">-</span><span class="fl">0.19</span>,<span class="fl">0.29</span>,<span class="fl">1.41</span>,<span class="fl">0.13</span>,<span class="sc">-</span><span class="fl">0.06</span>,</span>
<span id="cb462-2"><a href="chap-bondad.html#cb462-2" aria-hidden="true" tabindex="-1"></a>  <span class="sc">-</span><span class="fl">0.85</span>,<span class="sc">-</span><span class="fl">0.59</span>,<span class="sc">-</span><span class="fl">3.62</span>,<span class="sc">-</span><span class="fl">1.02</span>,<span class="fl">2.36</span>,<span class="fl">0.34</span>,<span class="sc">-</span><span class="fl">0.31</span>,<span class="fl">0.81</span>,<span class="sc">-</span><span class="fl">0.88</span>,<span class="fl">0.27</span>,<span class="fl">0.52</span>,<span class="fl">1.05</span>,<span class="fl">0.20</span>,<span class="fl">0.76</span>,<span class="fl">0.25</span>,</span>
<span id="cb462-3"><a href="chap-bondad.html#cb462-3" aria-hidden="true" tabindex="-1"></a>  <span class="sc">-</span><span class="fl">1.43</span>,<span class="fl">3.71</span>,<span class="sc">-</span><span class="fl">0.78</span>,<span class="fl">0.39</span>,<span class="sc">-</span><span class="fl">1.01</span>,<span class="fl">1.53</span>,<span class="sc">-</span><span class="fl">0.72</span>,<span class="fl">1.22</span>,<span class="fl">0.56</span>,<span class="sc">-</span><span class="fl">1.17</span>,<span class="sc">-</span><span class="fl">0.65</span>,<span class="sc">-</span><span class="fl">0.33</span>,<span class="sc">-</span><span class="fl">0.07</span>,<span class="fl">0.31</span>,</span>
<span id="cb462-4"><a href="chap-bondad.html#cb462-4" aria-hidden="true" tabindex="-1"></a>  <span class="sc">-</span><span class="fl">0.74</span>,<span class="fl">0.36</span>,<span class="sc">-</span><span class="fl">1.72</span>,<span class="sc">-</span><span class="fl">1.21</span>,<span class="sc">-</span><span class="fl">0.05</span>,<span class="sc">-</span><span class="fl">1.17</span>,<span class="fl">0.28</span>,<span class="fl">1.30</span>,<span class="fl">0.89</span>,<span class="fl">1.45</span>,<span class="fl">0.13</span>,<span class="sc">-</span><span class="fl">1.12</span>,<span class="fl">3.13</span>,<span class="sc">-</span><span class="fl">1.21</span>,</span>
<span id="cb462-5"><a href="chap-bondad.html#cb462-5" aria-hidden="true" tabindex="-1"></a>  <span class="sc">-</span><span class="fl">0.90</span>,<span class="sc">-</span><span class="fl">0.31</span>,<span class="sc">-</span><span class="fl">1.05</span>,<span class="fl">0.89</span>,<span class="sc">-</span><span class="fl">1.06</span>,<span class="fl">0.21</span>,<span class="sc">-</span><span class="fl">0.50</span>,<span class="sc">-</span><span class="fl">0.36</span>,<span class="sc">-</span><span class="fl">0.29</span>,<span class="sc">-</span><span class="fl">0.19</span>,<span class="sc">-</span><span class="fl">1.71</span>,<span class="fl">0.09</span>,<span class="fl">0.21</span>,<span class="fl">0.55</span>,</span>
<span id="cb462-6"><a href="chap-bondad.html#cb462-6" aria-hidden="true" tabindex="-1"></a>  <span class="sc">-</span><span class="fl">1.42</span>,<span class="fl">0.19</span>,<span class="sc">-</span><span class="fl">0.62</span>,<span class="fl">2.46</span>,<span class="sc">-</span><span class="fl">0.17</span>,<span class="sc">-</span><span class="fl">0.63</span>,<span class="fl">0.77</span>,<span class="fl">0.94</span>,<span class="fl">0.55</span>,<span class="fl">0.35</span>,<span class="sc">-</span><span class="fl">4.47</span>,<span class="fl">1.71</span>,<span class="fl">0.07</span>,<span class="sc">-</span><span class="fl">0.57</span>,</span>
<span id="cb462-7"><a href="chap-bondad.html#cb462-7" aria-hidden="true" tabindex="-1"></a>  <span class="sc">-</span><span class="fl">1.43</span>,<span class="sc">-</span><span class="fl">0.85</span>,<span class="fl">1.06</span>,<span class="fl">0.82</span>,<span class="fl">0.19</span>,<span class="sc">-</span><span class="fl">1.08</span>,<span class="fl">0.30</span>,<span class="sc">-</span><span class="fl">0.87</span>,<span class="fl">0.77</span>,<span class="fl">1.23</span>,<span class="sc">-</span><span class="fl">0.04</span>,<span class="fl">0.66</span>,<span class="sc">-</span><span class="fl">0.87</span>,<span class="sc">-</span><span class="fl">0.86</span>,</span>
<span id="cb462-8"><a href="chap-bondad.html#cb462-8" aria-hidden="true" tabindex="-1"></a>  <span class="sc">-</span><span class="fl">1.06</span>,<span class="fl">0.10</span>)</span></code></pre></div>
<p>Queremos comprobar gráficamente si sigue una distribución t de Student de 4 grados de libertad. Vamos a usar la función <code>qqPlot</code> con sus parámetros por defecto:</p>
<div class="sourceCode" id="cb463"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb463-1"><a href="chap-bondad.html#cb463-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span>
<span id="cb463-2"><a href="chap-bondad.html#cb463-2" aria-hidden="true" tabindex="-1"></a><span class="fu">qqPlot</span>(muestra, <span class="at">distribution=</span><span class="st">&quot;t&quot;</span>, <span class="at">df=</span><span class="dv">4</span>, <span class="at">id=</span><span class="cn">FALSE</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-247"></span>
<img src="AprendeR-Parte-II_files/figure-html/unnamed-chunk-247-1.png" alt="Q-Q-plot de la muestra del Ejemplo \@ref(exm:qqp-1) contra una t de Student con 4 grados de libertad producido por defecto con qqPlot." width="480" />
<p class="caption">
Figura 6.2: Q-Q-plot de la muestra del Ejemplo <a href="chap-bondad.html#exm:qqp-1">6.1</a> contra una t de Student con 4 grados de libertad producido por defecto con qqPlot.
</p>
</div>
<p>Como todos los Q-Q-puntos están dentro de la región de confianza del 95%, podemos aceptar que la muestra proviene de una t de Student.</p>
<p>El Q-Q-plot básico de la Figura <a href="chap-bondad.html#fig:qqp1">6.1</a> se ha obtenido con el código siguiente:</p>
<div class="sourceCode" id="cb464"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb464-1"><a href="chap-bondad.html#cb464-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qqPlot</span>(muestra, <span class="at">distribution=</span><span class="st">&quot;t&quot;</span>, <span class="at">df=</span><span class="dv">4</span>, <span class="at">envelope=</span><span class="cn">FALSE</span>, <span class="at">xlab=</span><span class="st">&quot;Cuantiles de t&quot;</span>,</span>
<span id="cb464-2"><a href="chap-bondad.html#cb464-2" aria-hidden="true" tabindex="-1"></a>   <span class="at">ylab=</span><span class="st">&quot;Cuantiles de la muestra&quot;</span>, <span class="at">line=</span><span class="st">&quot;none&quot;</span>, <span class="at">pch=</span><span class="dv">20</span>, <span class="at">grid=</span><span class="cn">FALSE</span>, <span class="at">id=</span><span class="cn">FALSE</span>)</span>
<span id="cb464-3"><a href="chap-bondad.html#cb464-3" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="dv">0</span>,<span class="dv">1</span>, <span class="at">col=</span><span class="st">&quot;red&quot;</span>, <span class="at">lwd=</span><span class="fl">1.5</span>)</span></code></pre></div>
<p>Veamos otro ejemplo.</p>

<div class="example">
<p><span id="exm:irisqq" class="example"><strong>Ejemplo 6.2  </strong></span>Consideremos el <em>data frame</em> <code>iris</code> que contiene información sobre medidas relacionadas con las flores de una muestra de iris de tres especies. Vamos a producir un Q-Q-plot que ilustre si las longitudes de los sépalos de las plantas iris recogidas en esta tabla de datos siguen una distribución normal. A un Q-Q-plot que compara una muestra con una distribución normal se le suele llamar, para abreviar, un <strong>normal-plot</strong>.</p>
</div>
<p>En primer lugar, estimamos los parámetros máximo verosímiles de la distribución normal que podría haber generado nuestra muestra:</p>
<div class="sourceCode" id="cb465"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb465-1"><a href="chap-bondad.html#cb465-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(MASS)</span>
<span id="cb465-2"><a href="chap-bondad.html#cb465-2" aria-hidden="true" tabindex="-1"></a>iris.sl<span class="ot">=</span>iris<span class="sc">$</span>Sepal.Length</span>
<span id="cb465-3"><a href="chap-bondad.html#cb465-3" aria-hidden="true" tabindex="-1"></a>mu<span class="ot">=</span><span class="fu">fitdistr</span>(iris.sl,<span class="st">&quot;normal&quot;</span>)<span class="sc">$</span>estimate[<span class="dv">1</span>]</span>
<span id="cb465-4"><a href="chap-bondad.html#cb465-4" aria-hidden="true" tabindex="-1"></a>sigma<span class="ot">=</span><span class="fu">fitdistr</span>(iris.sl,<span class="st">&quot;normal&quot;</span>)<span class="sc">$</span>estimate[<span class="dv">2</span>]</span>
<span id="cb465-5"><a href="chap-bondad.html#cb465-5" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">c</span>(mu,sigma),<span class="dv">3</span>)</span></code></pre></div>
<pre><code>##  mean    sd 
## 5.843 0.825</code></pre>
<p>y ahora generamos el Q-Q-plot usando estos parámetros</p>
<div class="sourceCode" id="cb467"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb467-1"><a href="chap-bondad.html#cb467-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qqPlot</span>(iris.sl, <span class="at">distribution=</span><span class="st">&quot;norm&quot;</span>, <span class="at">mean=</span>mu, <span class="at">sd=</span>sigma, <span class="at">xlab=</span><span class="st">&quot;Cuantiles de la normal&quot;</span>,</span>
<span id="cb467-2"><a href="chap-bondad.html#cb467-2" aria-hidden="true" tabindex="-1"></a>   <span class="at">ylab=</span><span class="st">&quot;Cuantiles de la muestra&quot;</span>, <span class="at">main=</span><span class="st">&quot;&quot;</span>, <span class="at">pch=</span><span class="dv">20</span>, <span class="at">cex=</span><span class="fl">0.7</span>, <span class="at">id=</span><span class="cn">FALSE</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:qqplotiris"></span>
<img src="AprendeR-Parte-II_files/figure-html/qqplotiris-1.png" alt="Normal-plot de longitudes de sépalos de flores iris." width="480" />
<p class="caption">
Figura 6.3: Normal-plot de longitudes de sépalos de flores iris.
</p>
</div>
<p>Vemos cómo los primeros puntos salen de la región de confianza del 95% por encima. Esto significa que los valores más pequeños de la muestra son mayores de lo que sería de esperar si la muestra viniera de la variable normal. Interpretamos este Q-Q-plot como evidencia de que estas longitudes no siguen una distribución normal. Más adelante usaremos tests de normalidad específicos para contrastar la normalidad de estos datos.</p>
</div>
<div id="el-test-chi2-de-pearson" class="section level2" number="6.2">
<h2><span class="header-section-number">6.2</span> El test <span class="math inline">\(\chi^2\)</span> de Pearson</h2>
<p>El test <span class="math inline">\(\chi^2\)</span> de Pearson contrasta si una muestra ha sido generada o no con una cierta distribución, cuantificando si sus valores aparecen con una frecuencia cercana a la que sería de esperar si la muestra siguiera esa distribución. Esto se lleva a cabo por medio del estadístico de contraste</p>
<p><span class="math display">\[
X^2=\sum_{i=1}^k\frac{(\mbox{frec. observada}_i-\mbox{frec. esperada}_i)^2}{\mbox{frec. esperada}_i}
\]</span>
donde <em>k</em> es el número de clases e <em>i</em> es el índice de las clases, de manera que “frec. observada<sub><em>i</em></sub>” y “frec. esperada<sub><em>i</em></sub>” denotan, respectivamente, la frecuencia observada de la clase <em>i</em>-ésima y su frecuencia esperada bajo la distribución que contrastamos. Si se satisfacen una serie de condiciones, este estadístico sigue aproximadamente una ley <span class="math inline">\(\chi^2\)</span> con un número de grados de libertad igual al número de clases menos uno y menos el número de parámetros de la distribución teórica que hayamos estimado. Las condiciones que se han de satisfacer son:</p>
<ul>
<li><p>La muestra ha de ser grande, digamos que de tamaño como mínimo 30;</p></li>
<li><p>Si los posibles valores son infinitos, hay que agruparlos en un número finito <em>k</em> de clases que cubran todos los posibles valores (recordad que en la Lección <a href="#chap:agrup"><strong>??</strong></a> de la primera parte del curso ya explicamos cómo agrupar variables aleatorias continuas con la función <code>cut</code>);</p></li>
<li><p>Las frecuencias esperadas de las clases en las que hemos agrupado el espacio muestral han de ser todas, o al menos una gran mayoría, mayores o iguales que 5.</p></li>
</ul>
<p>La instrucción básica en R para realizar un test <span class="math inline">\(\chi^2\)</span> es <code>chisq.test</code>. Su sintaxis básica es</p>
<div class="sourceCode" id="cb468"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb468-1"><a href="chap-bondad.html#cb468-1" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(x, <span class="at">p=</span>..., <span class="at">rescale.p=</span>..., <span class="at">simulate.p.value=</span>...)</span></code></pre></div>
<p>donde:</p>
<ul>
<li><p><code>x</code> es el vector (o la tabla, calculada con <code>table</code>) de frecuencias absolutas observadas de las clases en la muestra.</p></li>
<li><p><code>p</code> es el vector de probabilidades teóricas de las clases para la distribución que queremos contrastar. Si no lo especificamos, se entiende que la probabilidad es la misma para todas las clases. Obviamente, estas probabilidades se tienen que especificar en el mismo orden que las frecuencias de <code>x</code> y, como son las probabilidades de todos los resultados posibles, en principio tienen que sumar 1; esta condición se puede relajar con el siguiente parámetro.</p></li>
<li><p><code>rescale.p</code> es un parámetro lógico que, si se iguala a <code>TRUE</code>, indica que los valores de <code>p</code> no son probabilidades, sino solo proporcionales a las probabilidades; esto hace que R tome como probabilidades teóricas los valores de <code>p</code> partidos por su suma, para que sumen 1. Por defecto vale <code>FALSE</code>, es decir, se supone que el vector que se entra como <code>p</code> son probabilidades y por lo tanto debe sumar 1, y si esto no pasa se genera un mensaje de error indicándolo. Igualarlo a <code>TRUE</code> puede ser útil, porque nos permite especificar las probabilidades mediante las frecuencias esperadas o mediante porcentajes. Pero también es peligroso, porque si nos hemos equivocado y hemos entrado un vector en <code>p</code> que no corresponda a una probabilidad, R no nos avisará.</p></li>
<li><p><code>simulate.p.value</code> es un parámetro lógico que indica a la función si debe
optar por una simulación para estimar el p-valor del contraste. Por
defecto vale <code>FALSE</code>, en cuyo caso este p-valor no se estima sino que se calcula mediante la distribución <span class="math inline">\(\chi^2\)</span> correspondiente. Si se especifica como <code>TRUE</code>, R realiza una serie de replicaciones aleatorias de la situación teórica: por defecto, 2000, pero su número se puede especificar mediante el parámetro <code>B</code>. Es decir, genera un conjunto de vectores aleatorios de frecuencias con la distribución que queremos contrastar, cada uno de suma total la de <code>x</code>. A continuación, calcula la proporción de estas repeticiones en las que el estadístico de contraste es mayor o igual que el obtenido para <code>x</code>, y éste es el p-valor que da. Cuando no se satisfacen las condiciones para que <span class="math inline">\(X^2\)</span> siga aproximadamente una distribución <span class="math inline">\(\chi^2\)</span>, estimar el p-valor mediante simulaciones es una buena alternativa.</p></li>
</ul>
<p>Veamos un primer ejemplo sencillo.</p>

<div class="example">
<p><span id="exm:dado" class="example"><strong>Ejemplo 6.3  </strong></span>Tenemos un dado, y queremos contrastar si está equilibrado o trucado. Lo hemos lanzado 40 veces y hemos obtenido los resultados siguientes:</p>
</div>
<table>
<thead>
<tr class="header">
<th align="right">Resultados</th>
<th align="right">Frecuencias</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">1</td>
<td align="right">8</td>
</tr>
<tr class="even">
<td align="right">2</td>
<td align="right">4</td>
</tr>
<tr class="odd">
<td align="right">3</td>
<td align="right">6</td>
</tr>
<tr class="even">
<td align="right">4</td>
<td align="right">3</td>
</tr>
<tr class="odd">
<td align="right">5</td>
<td align="right">7</td>
</tr>
<tr class="even">
<td align="right">6</td>
<td align="right">12</td>
</tr>
</tbody>
</table>
<p>Si el dado está equilibrado, la probabilidad de cada resultado es 1/6 y por lo tanto la frecuencia esperada de cada resultado es 40/6=6.667. Como la muestra tiene más de 30 elementos y las frecuencias esperadas son todas mayores que 5, podemos realizar de manera segura un test <span class="math inline">\(\chi^2\)</span>. Por lo tanto, entraremos estas frecuencias en un vector y le aplicaremos la función <code>chisq.test</code>. Como contrastamos si todas las clases tienen la misma probabilidad, no hace falta especificar el valor del parámetro <code>p</code>.</p>
<div class="sourceCode" id="cb469"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb469-1"><a href="chap-bondad.html#cb469-1" aria-hidden="true" tabindex="-1"></a>freqs<span class="ot">=</span><span class="fu">c</span>(<span class="dv">8</span>,<span class="dv">4</span>,<span class="dv">6</span>,<span class="dv">3</span>,<span class="dv">7</span>,<span class="dv">12</span>)</span>
<span id="cb469-2"><a href="chap-bondad.html#cb469-2" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(freqs)</span></code></pre></div>
<pre><code>## 
## 	Chi-squared test for given probabilities
## 
## data:  freqs
## X-squared = 7.7, df = 5, p-value = 0.174</code></pre>
<p>Observemos la estructura del resultado de un <code>chisq.test</code>. Nos da el valor del estadístico <span class="math inline">\(X^2\)</span> (<code>X-squared</code>), el p-valor del contraste (<code>p-value</code>), y los grados de libertad de la distribución <span class="math inline">\(\chi^2\)</span> que ha usado para calcularlo (<code>df</code>). En este caso, el p-valor es 0.174, y por lo tanto no podemos rechazar que el dado esté equilibrado: en más de 1 de cada 6 secuencias de 40 lanzamientos de un dado equilibrado obtenemos un valor de <span class="math inline">\(X^2\)</span> tan grande como el de esta secuencia, o mayor.</p>
<p>Queremos remarcar que, como R no sabe si hemos estimado o no parámetros, el número de grados de libertad que usa <code>chisq.test</code> es simplemente el número de clases menos 1. Si no hemos estimado parámetros para calcular las probabilidades teóricas, ya va bien, pero si lo hemos hecho y por lo tanto el número de grados de libertad no es el adecuado, tendremos que calcular el p-valor correcto a partir del valor del estadístico. Veremos varios ejemplos más adelante.</p>
<p>El resultado de un <code>chisq.test</code> es una <code>list</code>, de la que podemos extraer directamente la información que deseemos con los sufijos adecuados. En concreto, podemos obtener el valor del estadístico <span class="math inline">\(X^2\)</span> con el sufijo <code>$statistic</code>, los grados de libertad con el sufijo <code>$parameter</code> y el p-valor con el sufijo <code>$p.value</code>.</p>
<div class="sourceCode" id="cb471"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb471-1"><a href="chap-bondad.html#cb471-1" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(freqs)<span class="sc">$</span>statistic</span></code></pre></div>
<pre><code>## X-squared 
##       7.7</code></pre>
<div class="sourceCode" id="cb473"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb473-1"><a href="chap-bondad.html#cb473-1" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(freqs)<span class="sc">$</span>parameter</span></code></pre></div>
<pre><code>## df 
##  5</code></pre>
<div class="sourceCode" id="cb475"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb475-1"><a href="chap-bondad.html#cb475-1" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(freqs)<span class="sc">$</span>p.value</span></code></pre></div>
<pre><code>## [1] 0.173563</code></pre>
<p>Imaginemos ahora que, en vez de lanzar el dado 40 veces, lo lanzamos 20 veces, y obtenemos los resultados siguientes:</p>
<table>
<thead>
<tr class="header">
<th align="right">Resultados</th>
<th align="right">Frecuencias</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">1</td>
<td align="right">4</td>
</tr>
<tr class="even">
<td align="right">2</td>
<td align="right">2</td>
</tr>
<tr class="odd">
<td align="right">3</td>
<td align="right">3</td>
</tr>
<tr class="even">
<td align="right">4</td>
<td align="right">2</td>
</tr>
<tr class="odd">
<td align="right">5</td>
<td align="right">3</td>
</tr>
<tr class="even">
<td align="right">6</td>
<td align="right">6</td>
</tr>
</tbody>
</table>
<p>¿Hay evidencia de que el dado esté trucado? Ahora la muestra no es grande y las frecuencias esperadas son todas 20/6=3.333, menores que 5. Por tanto, el p-valor del test <span class="math inline">\(\chi^2\)</span> que se obtiene usando una distribución <span class="math inline">\(\chi^2_5\)</span> no tiene por qué tener ningún significado. En una situación como ésta es cuando conviene usar el parámetro <code>simulate.p.value</code>. Vamos a pedir a R que simule 5000 veces el experimento de lanzar 20 veces un dado equilibrado, y que calcule como p-valor la proporción de simulaciones en las que el estadístico <span class="math inline">\(X^2\)</span> haya dado un valor mayor o igual que el que se obtiene con nuestra muestra.</p>
<div class="sourceCode" id="cb477"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb477-1"><a href="chap-bondad.html#cb477-1" aria-hidden="true" tabindex="-1"></a>freqs2<span class="ot">=</span><span class="fu">c</span>(<span class="dv">4</span>,<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">6</span>)</span>
<span id="cb477-2"><a href="chap-bondad.html#cb477-2" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(freqs2, <span class="at">simulate.p.value=</span><span class="cn">TRUE</span>, <span class="at">B=</span><span class="dv">5000</span>)</span></code></pre></div>
<pre><code>## 
## 	Chi-squared test for given probabilities with simulated p-value
## 	(based on 5000 replicates)
## 
## data:  freqs2
## X-squared = 3.4, df = NA, p-value = 0.7</code></pre>
<p>Resulta que en un 70% de las simulaciones el valor de <span class="math inline">\(X^2\)</span> ha sido mayor o igual que el de nuestra muestra, 3.4. Por lo tanto, nuestra muestra entra dentro de lo normal para un dado equilibrado, por lo que no hay evidencia de que el dado esté trucado.</p>
<p>Como este p-valor se basa en simulaciones, en cada aplicación del test el p-valor puede dar resultados diferentes, pero en general la conclusión es robusta si se toma un número suficiente de simulaciones.</p>
<div class="sourceCode" id="cb479"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb479-1"><a href="chap-bondad.html#cb479-1" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(freqs2,<span class="at">simulate.p.value=</span><span class="cn">TRUE</span>,<span class="at">B=</span><span class="dv">5000</span>)<span class="sc">$</span>p.value</span></code></pre></div>
<pre><code>## [1] 0.70126</code></pre>
<div class="sourceCode" id="cb481"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb481-1"><a href="chap-bondad.html#cb481-1" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(freqs2,<span class="at">simulate.p.value=</span><span class="cn">TRUE</span>,<span class="at">B=</span><span class="dv">5000</span>)<span class="sc">$</span>p.value</span></code></pre></div>
<pre><code>## [1] 0.717656</code></pre>
<div class="sourceCode" id="cb483"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb483-1"><a href="chap-bondad.html#cb483-1" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(freqs2,<span class="at">simulate.p.value=</span><span class="cn">TRUE</span>,<span class="at">B=</span><span class="dv">5000</span>)<span class="sc">$</span>p.value</span></code></pre></div>
<pre><code>## [1] 0.708858</code></pre>
<p>Como vemos, los p-valores son todos similares.</p>
<p>Por curiosidad, ¿qué p-valor da el test <span class="math inline">\(\chi^2\)</span> usando la distribución de <span class="math inline">\(\chi^2_5\)</span>?</p>
<div class="sourceCode" id="cb485"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb485-1"><a href="chap-bondad.html#cb485-1" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(freqs2)<span class="sc">$</span>p.value</span></code></pre></div>
<pre><code>## Warning in chisq.test(freqs2): Chi-squared approximation may be incorrect</code></pre>
<pre><code>## [1] 0.63857</code></pre>
<p>El p-valor no es muy diferente y la conclusión en este caso sería la misma, pero fijaos en el mensaje de advertencia: para la muestra dada, la aproximación de la distribución de <span class="math inline">\(X^2\)</span> mediante una <span class="math inline">\(\chi^2\)</span> no tiene por qué ser correcta.</p>

<div class="example">
<p><span id="exm:unnamed-chunk-259" class="example"><strong>Ejemplo 6.4  </strong></span>Vamos a estudiar las frecuencias de los nucleótidos en una cadena de ADN, y contrastar si aparecen los cuatro con la misma probabilidad o no. En este caso, el espacio muestral son los cuatro nucleótidos: adenina (A), citosina (C), guanina (G) y timina (T). Identificaremos una cadena de ADN con un vector de letras <code>a</code>, <code>c</code>, <code>g</code> y <code>t</code>. Si llamamos <span class="math inline">\(p_a\)</span>, <span class="math inline">\(p_c\)</span>, <span class="math inline">\(p_g\)</span> y <span class="math inline">\(p_t\)</span> a las probabilidades de aparición de estas letras, el contraste que queremos realizar es</p>
</div>
<p><span class="math display">\[
\left\{\begin{array}{l} 
H_0 : p_a=p_c=p_g=p_t=0.25\\
H_1: \mbox{Algunos nucleótidos son más probables que otros}
\end{array}
\right.
\]</span>
Vamos a analizar una cadena de ADN “de verdad”, extraída de la base de datos
<em><a href="\url%7Bhttp://www.ncbi.nlm.nih.gov/genbank/%7D">GenBank</a></em>. Para ello,
utilizaremos el paquete <strong>ape</strong>, que incorpora una función <code>read.GenBank</code> que permite leer secuencias de genes incluidas en esta base de datos y convertirlas en vectores de letras <code>a</code>, <code>c</code>, <code>g</code> y <code>t</code>. En concreto, si la aplicamos al número de acceso (<em>accession number</em>) de una secuencia (entrado entre comillas, ya que es una palabra) y usamos el parámetro <code>as.character=TRUE</code>, nos devuelve dicha secuencia como un vector de letras junto con otra información sobre la secuencia.</p>
<p>En este ejemplo, nos vamos a interesar por el gen que codifica la mioglobina humana, que es una proteína relativamente pequeña constituida por una sola cadena polipeptídica de 153 aminoácidos. Su número de acceso es AH002877.2. El código siguiente lee este gen y lo guarda en un objeto.</p>
<div class="sourceCode" id="cb488"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb488-1"><a href="chap-bondad.html#cb488-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ape)</span>
<span id="cb488-2"><a href="chap-bondad.html#cb488-2" aria-hidden="true" tabindex="-1"></a>myoglobin<span class="ot">=</span><span class="fu">read.GenBank</span>(<span class="st">&quot;AH002877.2&quot;</span>, <span class="at">as.character=</span><span class="cn">TRUE</span>)</span></code></pre></div>
<p>Consultemos cómo es el objeto donde hemos guardado esta secuencia:</p>
<div class="sourceCode" id="cb489"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb489-1"><a href="chap-bondad.html#cb489-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(myoglobin)</span></code></pre></div>
<pre><code>## List of 1
##  $ AH002877.2: chr [1:6889] &quot;g&quot; &quot;t&quot; &quot;a&quot; &quot;c&quot; ...
##  - attr(*, &quot;species&quot;)= chr &quot;Homo_sapiens&quot;</code></pre>
<p>Vemos que se trata una <code>list</code> formada por una sola componente, el vector de bases, y un atributo. Vamos a extraer el vector, para poder trabajar con él. La manera más sencilla es añadiendo a la <code>list</code> el sufijo <code>[[1]]</code>:</p>
<div class="sourceCode" id="cb491"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb491-1"><a href="chap-bondad.html#cb491-1" aria-hidden="true" tabindex="-1"></a>myoglobin<span class="ot">=</span>myoglobin[[<span class="dv">1</span>]]</span>
<span id="cb491-2"><a href="chap-bondad.html#cb491-2" aria-hidden="true" tabindex="-1"></a>myoglobin[<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>]</span></code></pre></div>
<pre><code>##  [1] &quot;g&quot; &quot;t&quot; &quot;a&quot; &quot;c&quot; &quot;t&quot; &quot;g&quot; &quot;t&quot; &quot;a&quot; &quot;t&quot; &quot;t&quot;</code></pre>
<p>Nos preguntamos si podemos aceptar que en esta secuencia las cuatro bases aparecen de manera equiprobable. Para responder esta pregunta, calculamos las frecuencias de las letras con la función <code>table</code> y aplicamos el test <span class="math inline">\(\chi^2\)</span> a los resultados.</p>
<div class="sourceCode" id="cb493"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb493-1"><a href="chap-bondad.html#cb493-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(myoglobin)</span></code></pre></div>
<pre><code>## myoglobin
##    a    c    g    n    t 
## 1718 1453 2019  200 1499</code></pre>
<p>Aparecen valores <code>n</code>, que corresponden a bases no resueltas. Vamos borrarlas de la secuencia:</p>
<div class="sourceCode" id="cb495"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb495-1"><a href="chap-bondad.html#cb495-1" aria-hidden="true" tabindex="-1"></a>myoglobin<span class="ot">=</span>myoglobin[myoglobin<span class="sc">!=</span><span class="st">&quot;n&quot;</span>]</span>
<span id="cb495-2"><a href="chap-bondad.html#cb495-2" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(myoglobin)</span></code></pre></div>
<pre><code>## myoglobin
##    a    c    g    t 
## 1718 1453 2019 1499</code></pre>
<p>Ahora ya estamos en condiciones de llevar a cabo el contraste deseado con la función <code>chisq.test</code>. Puesto que miramos si todos los resultados aparecen con la misma probabilidad, no hace falta especificar el vector <code>p</code> de probabilidades.</p>
<div class="sourceCode" id="cb497"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb497-1"><a href="chap-bondad.html#cb497-1" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(<span class="fu">table</span>(myoglobin))</span></code></pre></div>
<pre><code>## 
## 	Chi-squared test for given probabilities
## 
## data:  table(myoglobin)
## X-squared = 119.8, df = 3, p-value &lt;2e-16</code></pre>
<p>El p-valor es prácticamente 0, podemos rechazar que las cuatro bases aparezcan con la misma probabilidad: las diferencias entre las frecuencias de los cuatro aminoácidos son lo suficientemente grandes como para hacer inverosímil que se hayan generado con la misma probabilidad.</p>

<div class="example">
<p><span id="exm:unnamed-chunk-266" class="example"><strong>Ejemplo 6.5  </strong></span>Siguiendo con el ejemplo anterior, vamos a contrastar ahora si las bases siguen una distribución en la que A y G aparecen un 25% de veces más que C y T. Usaremos <code>p=c(1.25,1,1.25,1)</code> para especificar estas proporciones.</p>
</div>
<div class="sourceCode" id="cb499"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb499-1"><a href="chap-bondad.html#cb499-1" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(<span class="fu">table</span>(myoglobin),<span class="at">p=</span><span class="fu">c</span>(<span class="fl">1.25</span>,<span class="dv">1</span>,<span class="fl">1.25</span>,<span class="dv">1</span>))</span></code></pre></div>
<pre><code>## Error in chisq.test(table(myoglobin), p = c(1.25, 1, 1.25, 1)): probabilities must sum to 1.</code></pre>
<p>¡Vaya! Nos habíamos olvidado de especificar <code>rescale.p=TRUE</code>, para poder entrar como <code>p</code> un vector proporcional a las probabilidades.</p>
<div class="sourceCode" id="cb501"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb501-1"><a href="chap-bondad.html#cb501-1" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(<span class="fu">table</span>(myoglobin),<span class="at">p=</span><span class="fu">c</span>(<span class="fl">1.25</span>,<span class="dv">1</span>,<span class="fl">1.25</span>,<span class="dv">1</span>),<span class="at">rescale.p=</span><span class="cn">TRUE</span>)<span class="sc">$</span>p.value</span></code></pre></div>
<pre><code>## [1] 1.30045e-05</code></pre>
<p>De nuevo, tenemos que rechazar la hipótesis nula.</p>

<div class="example">
<p><span id="exm:unnamed-chunk-269" class="example"><strong>Ejemplo 6.6  </strong></span>Vamos a realizar otro experimento con la cadena del gen de la mioglobina. Este gen consta de tres exones. El primero corresponde al número de acceso M10090.1. Vamos a comparar si la frecuencia de bases en este exón es similar a la de la cadena total, que hará de distribución teórica.</p>
</div>
<p>Para ello, leemos el exón y lo guardamos en una cadena</p>
<div class="sourceCode" id="cb503"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb503-1"><a href="chap-bondad.html#cb503-1" aria-hidden="true" tabindex="-1"></a>exon1<span class="ot">=</span><span class="fu">read.GenBank</span>(<span class="st">&quot;M10090.1&quot;</span>, <span class="at">as.character=</span><span class="cn">TRUE</span>)[[<span class="dv">1</span>]]</span></code></pre></div>
<p>Calculemos la tabla de frecuencias relativas de las bases en la cadena completa</p>
<div class="sourceCode" id="cb504"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb504-1"><a href="chap-bondad.html#cb504-1" aria-hidden="true" tabindex="-1"></a>probs.tot<span class="ot">=</span><span class="fu">prop.table</span>(<span class="fu">table</span>(myoglobin))</span>
<span id="cb504-2"><a href="chap-bondad.html#cb504-2" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(probs.tot,<span class="dv">3</span>)</span></code></pre></div>
<pre><code>## myoglobin
##     a     c     g     t 
## 0.257 0.217 0.302 0.224</code></pre>
<p>Vamos a usar esta tabla como parámetro <code>p</code> de la función <code>chisq.test</code>:</p>
<div class="sourceCode" id="cb506"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb506-1"><a href="chap-bondad.html#cb506-1" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(<span class="fu">table</span>(exon1),<span class="at">p=</span>probs.tot)<span class="sc">$</span>p.value</span></code></pre></div>
<pre><code>## [1] 9.78458e-06</code></pre>
<p>El p-valor es muy pequeño, y por lo tanto podemos rechazar que en este exón las bases aparezcan con la misma probabilidad que en la cadena total.</p>

<div class="example">
<p><span id="exm:unnamed-chunk-273" class="example"><strong>Ejemplo 6.7  </strong></span>Ahora vamos a llevar a cabo el experimento siguiente. Queremos contrastar si la aparición de pares “cg” en la mioglobina humana es aleatoria, en el sentido de que se debe simplemente a las apariciones al azar de sus dos bases, o si por el contrario hay algún otro mecanismo que los produce.</p>
</div>
<p>Para ello, tomaremos la secuencia completa de la mioglobina humana, que tenemos almacenada en <code>myoglobin</code>, y repetiremos 100 veces el proceso siguiente: extraemos una muestra aleatoria simple de 20 posiciones de la secuencia y contamos cuántas de ellas contienen el par de bases “cg”. Luego contrastaremos si la muestra así obtenida proviene de una distribución binomial con la probabilidad de aparición de “cg” como si las dos bases fueran independientes.</p>
<p>Fijamos la semilla de aleatoriedad para que se pueda reproducir el experimento.<a href="#fn5" class="footnote-ref" id="fnref5"><sup>5</sup></a> El código, que luego explicamos, y el resultado son los siguientes:</p>
<div class="sourceCode" id="cb508"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb508-1"><a href="chap-bondad.html#cb508-1" aria-hidden="true" tabindex="-1"></a>cg.in.sample<span class="ot">=</span><span class="cf">function</span>(x,S){<span class="co">#x un vector, S vector de índices</span></span>
<span id="cb508-2"><a href="chap-bondad.html#cb508-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">length</span>(<span class="fu">which</span>(x[S]<span class="sc">==</span><span class="st">&quot;c&quot;</span> <span class="sc">&amp;</span> x[S<span class="sc">+</span><span class="dv">1</span>]<span class="sc">==</span><span class="st">&quot;g&quot;</span>))</span>
<span id="cb508-3"><a href="chap-bondad.html#cb508-3" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb508-4"><a href="chap-bondad.html#cb508-4" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1700</span>)  </span>
<span id="cb508-5"><a href="chap-bondad.html#cb508-5" aria-hidden="true" tabindex="-1"></a>muestra<span class="ot">=</span><span class="fu">replicate</span>(<span class="dv">100</span>, <span class="fu">cg.in.sample</span>(myoglobin, </span>
<span id="cb508-6"><a href="chap-bondad.html#cb508-6" aria-hidden="true" tabindex="-1"></a>            <span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span>(<span class="fu">length</span>(myoglobin)<span class="sc">-</span><span class="dv">1</span>), <span class="dv">20</span>,<span class="at">replace=</span><span class="cn">TRUE</span>)))</span>
<span id="cb508-7"><a href="chap-bondad.html#cb508-7" aria-hidden="true" tabindex="-1"></a>muestra</span></code></pre></div>
<pre><code>##   [1] 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 1 0 0 0 1 0 0
##  [38] 0 0 0 0 0 0 0 1 1 0 0 2 0 2 0 0 0 1 0 1 0 1 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0
##  [75] 0 0 2 0 1 2 0 0 0 0 0 0 0 0 0 1 1 0 0 1 1 0 0 1 1 1</code></pre>
<p>La función <code>cg.in.sample</code> que hemos definido toma un vector <code>x</code> y un vector de índices <code>S</code> y cuenta el número de índices <code>s</code> de <code>S</code> en los que <code>x[s]</code> es <code>c</code> y <code>x[s+1]</code> es <code>g</code>. Entonces, con el <code>replicate</code>, hemos repetido 100 veces el proceso de extraer una muestra aleatoria simple de 20 índices de <code>myoglobin</code> (excluyendo el último, para que sean posiciones donde empieza un par de letras) y aplicar la función <code>cg.in.sample</code> a <code>myoglobin</code> y a este vector de índices.</p>
<p>Queremos determinar si esta muestra sigue una distribución binomial. En concreto, vamos a plantear tres casos de esta pregunta:</p>
<ul>
<li><p>Con probabilidad de aparición de la pareja “cg” 0.25·0.25=0.0625, que correspondería al hecho de que las dos bases aparecieran de manera equiprobable e independiente.</p></li>
<li><p>Con probabilidad de aparición de la pareja “cg” el producto de las frecuencias relativas de las bases en la secuencia global, que correspondería al hecho de que las dos bases aparecieran de manera independiente, pero no equiprobable sino con sus probabilidades dentro de la secuencia de la mioglobina.</p></li>
<li><p>Estimando el valor “real” de <span class="math inline">\(p\)</span>, lo que correspondería al hecho de que su probabilidad de aparición no tuviera nada que ver con las probabilidades individuales de sus dos bases.</p></li>
</ul>
<p>Empezamos con el primer caso. Calculemos las frecuencias con las que aparecen los diferentes resultados en la muestra:</p>
<div class="sourceCode" id="cb510"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb510-1"><a href="chap-bondad.html#cb510-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(muestra)</span></code></pre></div>
<pre><code>## muestra
##  0  1  2 
## 76 19  5</code></pre>
<p>Y las frecuencias esperadas con las que deberían aparecer si siguieran una distribución B(20,0.0625):</p>
<div class="sourceCode" id="cb512"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb512-1"><a href="chap-bondad.html#cb512-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">dbinom</span>(<span class="dv">0</span><span class="sc">:</span><span class="dv">20</span>,<span class="dv">20</span>,<span class="fl">0.0625</span>)<span class="sc">*</span><span class="dv">100</span>,<span class="dv">2</span>)</span></code></pre></div>
<pre><code>##  [1] 27.51 36.67 23.23  9.29  2.63  0.56  0.09  0.01  0.00  0.00  0.00
## [12]  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00</code></pre>
<p>Las frecuencias esperadas a partir de 4 son inferiores a 5 (recordad que la primera frecuencia corresponde al 0), y además su suma no llega a 5. Por lo tanto, vamos a agrupar en una sola clase los resultados mayores o iguales que 3. La nueva tabla de frecuencias esperadas es:</p>
<div class="sourceCode" id="cb514"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb514-1"><a href="chap-bondad.html#cb514-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">c</span>(<span class="fu">dbinom</span>(<span class="dv">0</span><span class="sc">:</span><span class="dv">2</span>,<span class="dv">20</span>,<span class="fl">0.0625</span>),<span class="dv">1</span><span class="sc">-</span><span class="fu">pbinom</span>(<span class="dv">2</span>,<span class="dv">20</span>,<span class="fl">0.0625</span>))<span class="sc">*</span><span class="dv">100</span>,<span class="dv">2</span>)</span></code></pre></div>
<pre><code>## [1] 27.51 36.67 23.23 12.59</code></pre>
<p>Ahora tenemos dos opciones: o bien tomamos como resultados posibles “0”, “1”, “2” y “3 o más”, en cuyo caso contaríamos que hemos observado 0 veces este último resultado en nuestra muestra, o bien tomamos como resultados posibles “0”, “1”, y “2 o más”, que se corresponde con los valores observados. Como norma general, es recomendable usar el mayor número de clases posible. Por consiguiente, vamos a optar por la primera estrategia: 4 clases y no 3. Por lo tanto, hay que añadir a la tabla de frecuencias de la muestra un 0 en la columna correspondiente a 3 o más observaciones.</p>
<div class="sourceCode" id="cb516"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb516-1"><a href="chap-bondad.html#cb516-1" aria-hidden="true" tabindex="-1"></a>freq.obs<span class="ot">=</span><span class="fu">c</span>(<span class="fu">table</span>(muestra),<span class="dv">0</span>)</span>
<span id="cb516-2"><a href="chap-bondad.html#cb516-2" aria-hidden="true" tabindex="-1"></a>prob.teor<span class="ot">=</span><span class="fu">c</span>(<span class="fu">dbinom</span>(<span class="dv">0</span><span class="sc">:</span><span class="dv">2</span>,<span class="dv">20</span>,<span class="fl">0.0625</span>),<span class="dv">1</span><span class="sc">-</span><span class="fu">pbinom</span>(<span class="dv">2</span>,<span class="dv">20</span>,<span class="fl">0.0625</span>))</span>
<span id="cb516-3"><a href="chap-bondad.html#cb516-3" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(freq.obs,<span class="at">p=</span>prob.teor)<span class="sc">$</span>p.value</span></code></pre></div>
<pre><code>## [1] 4.91134e-26</code></pre>
<p>El p-valor es prácticamente 0, por lo que podemos concluir que la muestra no sigue una distribución B(20,0.0625): las apariciones de los pares “cg” no se explican por la aparición de sus dos bases de manera independiente y equiprobable.</p>
<p>¿Hubiera variado la conclusión si hubiéramos optado por solo considerar tres clases?</p>
<div class="sourceCode" id="cb518"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb518-1"><a href="chap-bondad.html#cb518-1" aria-hidden="true" tabindex="-1"></a>freq.obs<span class="ot">=</span><span class="fu">table</span>(muestra)</span>
<span id="cb518-2"><a href="chap-bondad.html#cb518-2" aria-hidden="true" tabindex="-1"></a>prob.teor<span class="ot">=</span><span class="fu">c</span>(<span class="fu">dbinom</span>(<span class="dv">0</span><span class="sc">:</span><span class="dv">1</span>,<span class="dv">20</span>,<span class="fl">0.0625</span>),<span class="dv">1</span><span class="sc">-</span><span class="fu">pbinom</span>(<span class="dv">1</span>,<span class="dv">20</span>,<span class="fl">0.0625</span>))</span>
<span id="cb518-3"><a href="chap-bondad.html#cb518-3" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(freq.obs,<span class="at">p=</span>prob.teor)<span class="sc">$</span>p.value</span></code></pre></div>
<pre><code>## [1] 6.70877e-27</code></pre>
<p>El p-valor es prácticamente el mismo, la conclusión es la misma.</p>
<p>Pasemos al segundo caso de nuestro problema. Vamos a calcular la frecuencia relativa de “c” y “g” en la secuencia completa de la mioglobina humana y tomaremos como probabilidad <span class="math inline">\(p\)</span> el producto de ambas frecuencias relativas.</p>
<div class="sourceCode" id="cb520"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb520-1"><a href="chap-bondad.html#cb520-1" aria-hidden="true" tabindex="-1"></a><span class="fu">prop.table</span>(<span class="fu">table</span>(myoglobin))</span></code></pre></div>
<pre><code>## myoglobin
##        a        c        g        t 
## 0.256840 0.217222 0.301839 0.224099</code></pre>
<div class="sourceCode" id="cb522"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb522-1"><a href="chap-bondad.html#cb522-1" aria-hidden="true" tabindex="-1"></a>p<span class="ot">=</span><span class="fu">prod</span>(<span class="fu">prop.table</span>(<span class="fu">table</span>(myoglobin))[<span class="dv">2</span><span class="sc">:</span><span class="dv">3</span>])</span>
<span id="cb522-2"><a href="chap-bondad.html#cb522-2" aria-hidden="true" tabindex="-1"></a>p</span></code></pre></div>
<pre><code>## [1] 0.0655661</code></pre>
<p>Calculemos ahora las frecuencias esperadas tomando esta <span class="math inline">\(p\)</span>:</p>
<div class="sourceCode" id="cb524"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb524-1"><a href="chap-bondad.html#cb524-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">dbinom</span>(<span class="dv">0</span><span class="sc">:</span><span class="dv">20</span>,<span class="dv">20</span>,p)<span class="sc">*</span><span class="dv">100</span>,<span class="dv">2</span>)</span></code></pre></div>
<pre><code>##  [1] 25.76 36.15 24.10 10.15  3.03  0.68  0.12  0.02  0.00  0.00  0.00
## [12]  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00</code></pre>
<p>Vamos a tener que agrupar de nuevo en una sola clase los resultados mayores o iguales que 3.</p>
<div class="sourceCode" id="cb526"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb526-1"><a href="chap-bondad.html#cb526-1" aria-hidden="true" tabindex="-1"></a>freq.obs<span class="ot">=</span><span class="fu">c</span>(<span class="fu">table</span>(muestra),<span class="dv">0</span>)</span>
<span id="cb526-2"><a href="chap-bondad.html#cb526-2" aria-hidden="true" tabindex="-1"></a>prob.teor<span class="ot">=</span><span class="fu">c</span>(<span class="fu">dbinom</span>(<span class="dv">0</span><span class="sc">:</span><span class="dv">2</span>,<span class="dv">20</span>,p),<span class="dv">1</span><span class="sc">-</span><span class="fu">pbinom</span>(<span class="dv">2</span>,<span class="dv">20</span>,p))</span>
<span id="cb526-3"><a href="chap-bondad.html#cb526-3" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(freq.obs,<span class="at">p=</span>prob.teor)<span class="sc">$</span>p.value</span></code></pre></div>
<pre><code>## [1] 4.02804e-29</code></pre>
<p>Obtenemos de nuevo un valor prácticamente 0: las apariciones de los pares “cg” no se explican por la aparición de sus dos bases de manera independiente.</p>
<p>Finalmente, vamos a estimar el parámetro <span class="math inline">\(p\)</span>. La binomial es otra de las distribuciones no cubiertas por <code>fitdistr</code>, por lo que tendremos que apelar a lo que sabemos de teoría para hacerlo.
Como el valor esperado de una variable aleatoria <span class="math inline">\(X\sim B(n,p)\)</span> es <span class="math inline">\(np\)</span>, estimaremos <span class="math inline">\(p\)</span> mediante <span class="math inline">\(\overline{X}/n\)</span>. De hecho, éste es el estimador máximo verosímil de <span class="math inline">\(p\)</span> cuando <span class="math inline">\(n\)</span> es conocida.</p>
<div class="sourceCode" id="cb528"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb528-1"><a href="chap-bondad.html#cb528-1" aria-hidden="true" tabindex="-1"></a>p.estim<span class="ot">=</span><span class="fu">mean</span>(muestra)<span class="sc">/</span><span class="dv">20</span></span>
<span id="cb528-2"><a href="chap-bondad.html#cb528-2" aria-hidden="true" tabindex="-1"></a>p.estim</span></code></pre></div>
<pre><code>## [1] 0.0145</code></pre>
<p>Repetimos el proceso: calculemos las frecuencias teóricas</p>
<div class="sourceCode" id="cb530"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb530-1"><a href="chap-bondad.html#cb530-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">dbinom</span>(<span class="dv">0</span><span class="sc">:</span><span class="dv">20</span>,<span class="dv">20</span>,p.estim)<span class="sc">*</span><span class="dv">100</span>,<span class="dv">2</span>)</span></code></pre></div>
<pre><code>##  [1] 74.67 21.97  3.07  0.27  0.02  0.00  0.00  0.00  0.00  0.00  0.00
## [12]  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00</code></pre>
<p>En este caso, hemos de agrupar los resultados en “0”, “1” y “2 o más”, para que las frecuencias teóricas sean mayores que 5.
Coincide con los diferentes valores observados en la muestra.</p>
<div class="sourceCode" id="cb532"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb532-1"><a href="chap-bondad.html#cb532-1" aria-hidden="true" tabindex="-1"></a>freq.obs<span class="ot">=</span><span class="fu">table</span>(muestra)</span>
<span id="cb532-2"><a href="chap-bondad.html#cb532-2" aria-hidden="true" tabindex="-1"></a>prob.teor<span class="ot">=</span><span class="fu">c</span>(<span class="fu">dbinom</span>(<span class="dv">0</span><span class="sc">:</span><span class="dv">1</span>,<span class="dv">20</span>,p.estim),<span class="dv">1</span><span class="sc">-</span><span class="fu">pbinom</span>(<span class="dv">1</span>,<span class="dv">20</span>,p.estim))</span>
<span id="cb532-3"><a href="chap-bondad.html#cb532-3" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(freq.obs,<span class="at">p=</span>prob.teor)</span></code></pre></div>
<pre><code>## 
## 	Chi-squared test for given probabilities
## 
## data:  freq.obs
## X-squared = 1.226, df = 2, p-value = 0.542</code></pre>
<p>¡Cuidado! Este p-valor no es el correcto. Hemos estimado un parámetro, pero R no lo sabe. Por lo tanto tenemos que bajar en 1 los grados de libertad y calcular el p-valor a mano, mediante
<span class="math display">\[
  P(\chi_1^2\geq  X^2)=1-P(\chi_1^2\leq  1.226)
\]</span></p>
<div class="sourceCode" id="cb534"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb534-1"><a href="chap-bondad.html#cb534-1" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span><span class="sc">-</span><span class="fu">pchisq</span>(<span class="fu">chisq.test</span>(freq.obs,<span class="at">p=</span>prob.teor)<span class="sc">$</span>statistic,<span class="dv">1</span>)</span></code></pre></div>
<pre><code>## X-squared 
##  0.268154</code></pre>
<p>El p-valor es grande. Por lo tanto, no podemos rechazar la hipótesis nula de que
las apariciones de “cg” en muestras aleatorias de 20 posiciones sigan una ley binomial de parámetro <span class="math inline">\(p=0.0145\)</span>. Que es, por otro lado, lo que debería pasar si las “cg” estuvieran repartidas de manera aleatoria en la secuencia original, por lo que no podemos rechazar esto último.</p>
<p>La conclusión es, por lo tanto, que aceptamos que las “cg” aparecen distribuidas de manera aleatoria en la secuencia de la mioglobina humana, pero tenemos evidencia estadísticamente significativa de que las “c” y las “g” que las forman no aparecen de manera independiente.</p>
</div>
<div id="el-test-chi2-para-distribuciones-continuas" class="section level2" number="6.3">
<h2><span class="header-section-number">6.3</span> El test <span class="math inline">\(\chi^2\)</span> para distribuciones continuas</h2>
<p>El procedimiento de contraste de bondad de ajuste mediante el test <span class="math inline">\(\chi^2\)</span> para variables continuas tiene la particularidad de que es necesario un paso preliminar que consiste en definir los intervalos de clase para los que realizaremos el conteo de las frecuencias observadas. El proceso es similar al que estudiamos en la Lección <a href="#chap:agrup"><strong>??</strong></a> de la primera parte del curso para dibujar histogramas. Por lo tanto, necesitaremos definir unos intervalos de clase para el conteo de frecuencias absolutas observadas, y con las funciones <code>cut</code> y <code>table</code> obtendremos las frecuencias observadas de estas clases en la muestra de la variable continua.</p>
<p>Para obtener los intervalos podemos seguir dos estrategias razonables: reutilizar los generados por la función <code>hist</code>, o dividir el rango de la variable en un número prefijado <span class="math inline">\(k\)</span> de intervalos de amplitud fija. Vamos a ver en detalle un ejemplo de cada tipo.</p>

<div class="example">
<p><span id="exm:testnormiris1" class="example"><strong>Ejemplo 6.8  </strong></span>Vamos a contrastar si las longitudes de los sépalos de las plantas iris recogidas en la tabla de datos <code>iris</code> siguen una distribución normal. Recordaréis que el Q-Q-plot de estas longitudes que mostrábamos en la Figura <a href="chap-bondad.html#fig:qqplotiris">6.3</a> mostraba evidencia de que no la siguen.</p>
</div>
<p>Primero vamos a estimar de nuevo la media y la desviación típica de la distribución de estas longitudes.</p>
<div class="sourceCode" id="cb536"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb536-1"><a href="chap-bondad.html#cb536-1" aria-hidden="true" tabindex="-1"></a>iris.sl<span class="ot">=</span>iris<span class="sc">$</span>Sepal.Length</span>
<span id="cb536-2"><a href="chap-bondad.html#cb536-2" aria-hidden="true" tabindex="-1"></a>mu<span class="ot">=</span><span class="fu">fitdistr</span>(iris.sl,<span class="st">&quot;normal&quot;</span>)<span class="sc">$</span>estimate[<span class="dv">1</span>]</span>
<span id="cb536-3"><a href="chap-bondad.html#cb536-3" aria-hidden="true" tabindex="-1"></a>sigma<span class="ot">=</span><span class="fu">fitdistr</span>(iris.sl,<span class="st">&quot;normal&quot;</span>)<span class="sc">$</span>estimate[<span class="dv">2</span>]</span>
<span id="cb536-4"><a href="chap-bondad.html#cb536-4" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">c</span>(mu,sigma),<span class="dv">3</span>)</span></code></pre></div>
<pre><code>##  mean    sd 
## 5.843 0.825</code></pre>
<p>En este ejemplo, usaremos los intervalos en los que la función <code>hist</code> agrupa por defecto estos datos.</p>
<div class="sourceCode" id="cb538"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb538-1"><a href="chap-bondad.html#cb538-1" aria-hidden="true" tabindex="-1"></a>h<span class="ot">=</span><span class="fu">hist</span>(iris.sl, <span class="at">plot=</span><span class="cn">FALSE</span>)</span>
<span id="cb538-2"><a href="chap-bondad.html#cb538-2" aria-hidden="true" tabindex="-1"></a>h<span class="sc">$</span>breaks</span></code></pre></div>
<pre><code>## [1] 4.0 4.5 5.0 5.5 6.0 6.5 7.0 7.5 8.0</code></pre>
<p>Ahora se nos presenta el problema de que los intervalos que definen estos puntos de corte (<em>breaks</em>) no cubren toda la recta real, que es el espacio muestral de una variable aleatoria normal. Así que tenemos que reemplazar los extremos de este vector de <code>breaks</code> por los límites del espacio muestral de la variable, que en este caso son <span class="math inline">\(-\infty\)</span> e <span class="math inline">\(\infty\)</span>.</p>
<div class="sourceCode" id="cb540"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb540-1"><a href="chap-bondad.html#cb540-1" aria-hidden="true" tabindex="-1"></a>breaks2<span class="ot">=</span>h<span class="sc">$</span>breaks</span>
<span id="cb540-2"><a href="chap-bondad.html#cb540-2" aria-hidden="true" tabindex="-1"></a>breaks2[<span class="dv">1</span>]<span class="ot">=</span><span class="sc">-</span><span class="cn">Inf</span>    <span class="co">#Cambiamos el primer elemento por -Infinito</span></span>
<span id="cb540-3"><a href="chap-bondad.html#cb540-3" aria-hidden="true" tabindex="-1"></a>breaks2[<span class="fu">length</span>(breaks2)]<span class="ot">=</span><span class="cn">Inf</span>   <span class="co">#Cambiamos el último elemento por Infinito</span></span>
<span id="cb540-4"><a href="chap-bondad.html#cb540-4" aria-hidden="true" tabindex="-1"></a>breaks2</span></code></pre></div>
<pre><code>## [1] -Inf  4.5  5.0  5.5  6.0  6.5  7.0  7.5  Inf</code></pre>
<p>Ahora podemos calcular las frecuencias de la muestra en los intervalos definidos por estos puntos de corte:</p>
<div class="sourceCode" id="cb542"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb542-1"><a href="chap-bondad.html#cb542-1" aria-hidden="true" tabindex="-1"></a>freq.obs<span class="ot">=</span><span class="fu">table</span>(<span class="fu">cut</span>(iris.sl,<span class="at">breaks=</span>breaks2))</span>
<span id="cb542-2"><a href="chap-bondad.html#cb542-2" aria-hidden="true" tabindex="-1"></a>freq.obs</span></code></pre></div>
<pre><code>## 
## (-Inf,4.5]    (4.5,5]    (5,5.5]    (5.5,6]    (6,6.5]    (6.5,7] 
##          5         27         27         30         31         18 
##    (7,7.5] (7.5, Inf] 
##          6          6</code></pre>
<p>Ahora calcularemos las probabilidades teóricas. Para cada intervalo <span class="math inline">\((x,y]\)</span> en los que hemos cortado la recta real, tenemos que calcular <span class="math inline">\(P(x &lt; X\leq y)= P(X\leq y)-P( X\leq x)\)</span>, para lo que usaremos expresiones de la forma <code>pnorm(y,mu,sigma)-pnorm(x,mu,sigma)</code>.</p>
<p>Definimos dos vectores que nos den los extremos izquierdo y derecho de cada intervalo.</p>
<div class="sourceCode" id="cb544"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb544-1"><a href="chap-bondad.html#cb544-1" aria-hidden="true" tabindex="-1"></a>extremo.izq<span class="ot">=</span>breaks2[<span class="sc">-</span><span class="fu">length</span>(breaks2)]</span>
<span id="cb544-2"><a href="chap-bondad.html#cb544-2" aria-hidden="true" tabindex="-1"></a>extremo.der<span class="ot">=</span>breaks2[<span class="sc">-</span><span class="dv">1</span>]</span>
<span id="cb544-3"><a href="chap-bondad.html#cb544-3" aria-hidden="true" tabindex="-1"></a>extremo.izq</span></code></pre></div>
<pre><code>## [1] -Inf  4.5  5.0  5.5  6.0  6.5  7.0  7.5</code></pre>
<div class="sourceCode" id="cb546"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb546-1"><a href="chap-bondad.html#cb546-1" aria-hidden="true" tabindex="-1"></a>extremo.der</span></code></pre></div>
<pre><code>## [1] 4.5 5.0 5.5 6.0 6.5 7.0 7.5 Inf</code></pre>
<p>Ahora podemos calcular las probabilidades teóricas y las frecuencias esperadas de todos los intervalos de golpe. La probabilidades teóricas son:</p>
<div class="sourceCode" id="cb548"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb548-1"><a href="chap-bondad.html#cb548-1" aria-hidden="true" tabindex="-1"></a>probs.teor<span class="ot">=</span><span class="fu">pnorm</span>(extremo.der,mu,sigma)<span class="sc">-</span><span class="fu">pnorm</span>(extremo.izq,mu,sigma) </span>
<span id="cb548-2"><a href="chap-bondad.html#cb548-2" aria-hidden="true" tabindex="-1"></a>probs.teor</span></code></pre></div>
<pre><code>## [1] 0.0517955 0.1016307 0.1852753 0.2365772 0.2116091 0.1325812 0.0581747
## [8] 0.0223563</code></pre>
<p>Las frecuencias esperadas son:</p>
<div class="sourceCode" id="cb550"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb550-1"><a href="chap-bondad.html#cb550-1" aria-hidden="true" tabindex="-1"></a>freq.esp<span class="ot">=</span>probs.teor<span class="sc">*</span><span class="fu">length</span>(iris.sl)</span>
<span id="cb550-2"><a href="chap-bondad.html#cb550-2" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(freq.esp,<span class="dv">3</span>)</span></code></pre></div>
<pre><code>## [1]  7.769 15.245 27.791 35.487 31.741 19.887  8.726  3.353</code></pre>
<p>La frecuencia esperada de la última clase es inferior a 5, así que vamos a fundirla con la penúltima y así la clase resultante tendrá una frecuencia esperada superior a 5.</p>
<div class="sourceCode" id="cb552"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb552-1"><a href="chap-bondad.html#cb552-1" aria-hidden="true" tabindex="-1"></a>k<span class="ot">=</span><span class="fu">length</span>(probs.teor)</span>
<span id="cb552-2"><a href="chap-bondad.html#cb552-2" aria-hidden="true" tabindex="-1"></a><span class="co">#Nuevas probabilidades teóricas:</span></span>
<span id="cb552-3"><a href="chap-bondad.html#cb552-3" aria-hidden="true" tabindex="-1"></a>probs.teor2<span class="ot">=</span><span class="fu">c</span>(probs.teor[<span class="dv">1</span><span class="sc">:</span>(k<span class="dv">-2</span>)],<span class="fu">sum</span>(probs.teor[(k<span class="dv">-1</span>)<span class="sc">:</span>k])) </span>
<span id="cb552-4"><a href="chap-bondad.html#cb552-4" aria-hidden="true" tabindex="-1"></a><span class="co">#Nuevas frecuencias observadas:</span></span>
<span id="cb552-5"><a href="chap-bondad.html#cb552-5" aria-hidden="true" tabindex="-1"></a>freq.obs2<span class="ot">=</span><span class="fu">c</span>(freq.obs[<span class="dv">1</span><span class="sc">:</span>(k<span class="dv">-2</span>)],<span class="fu">sum</span>(freq.obs[(k<span class="dv">-1</span>)<span class="sc">:</span>k])) </span>
<span id="cb552-6"><a href="chap-bondad.html#cb552-6" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(freq.obs2,<span class="at">p=</span>probs.teor2)</span></code></pre></div>
<pre><code>## 
## 	Chi-squared test for given probabilities
## 
## data:  freq.obs2
## X-squared = 11.12, df = 6, p-value = 0.08475</code></pre>
<p>Recordemos que el p-valor obtenido no es el correcto: como hemos estimado dos parámetros, lo tenemos que calcular con una <span class="math inline">\(\chi^2\)</span> con 4 grados de libertad (dos menos de los que ha usado <code>chisq.test</code>):</p>
<div class="sourceCode" id="cb554"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb554-1"><a href="chap-bondad.html#cb554-1" aria-hidden="true" tabindex="-1"></a>test.iris<span class="ot">=</span><span class="fu">chisq.test</span>(freq.obs2,<span class="at">p=</span>probs.teor2)</span>
<span id="cb554-2"><a href="chap-bondad.html#cb554-2" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span><span class="sc">-</span><span class="fu">pchisq</span>(test.iris<span class="sc">$</span>statistic,test.iris<span class="sc">$</span>parameter<span class="dv">-2</span>)</span></code></pre></div>
<pre><code>## X-squared 
## 0.0252518</code></pre>
<p>El p-valor es inferior a 0.05, por tanto obtenemos evidencia de que la muestra no proviene de una población normal, es decir, de que las longitudes de los sépalos de las flores iris no siguen una ley normal.</p>

<div class="example">
<p><span id="exm:unnamed-chunk-296" class="example"><strong>Ejemplo 6.9  </strong></span>Vamos a repetir el estudio del ejemplo anterior, pero ahora calculando a mano los intervalos.
En general, el número de intervalos debe ser suficiente para cubrir toda la forma de la
distribución, pero tampoco conviene que haya muchos para evitar frecuencias esperadas pequeñas que obliguen a agrupar intervalos. Para una distribución normal se recomienda tomar entre 5 y 15 intervalos. Otra posibilidad es decidir el número de intervalos con alguna de las reglas explicadas en la Lección <a href="#chap:agrup"><strong>??</strong></a> de la primera parte del curso.</p>
</div>
<p>En nuestro ejemplo, vamos a usar 10 intervalos. Para calcularlos, tomamos el máximo y el mínimo de las observaciones, los restamos y dividimos por el número de intervalos (y, si fuera necesario, redondearíamos adecuadamente).</p>
<div class="sourceCode" id="cb556"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb556-1"><a href="chap-bondad.html#cb556-1" aria-hidden="true" tabindex="-1"></a>Ampl<span class="ot">=</span>(<span class="fu">max</span>(iris.sl)<span class="sc">-</span><span class="fu">min</span>(iris.sl))<span class="sc">/</span><span class="dv">10</span></span>
<span id="cb556-2"><a href="chap-bondad.html#cb556-2" aria-hidden="true" tabindex="-1"></a>Ampl</span></code></pre></div>
<pre><code>## [1] 0.36</code></pre>
<p>Los extremos de los intervalos en los que dividimos la muestra forman la secuencia que empieza en el mínimo y va sumando la amplitud hasta definir los <span class="math inline">\(k=10\)</span> intervalos. Luego hay que adecuar los dos extremos para que cubran el dominio de la densidad de la distribución teórica, en nuestro caso toda la recta real.</p>
<div class="sourceCode" id="cb558"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb558-1"><a href="chap-bondad.html#cb558-1" aria-hidden="true" tabindex="-1"></a>breaks<span class="ot">=</span><span class="fu">min</span>(iris.sl)<span class="sc">+</span>Ampl<span class="sc">*</span>(<span class="dv">0</span><span class="sc">:</span><span class="dv">10</span>)</span>
<span id="cb558-2"><a href="chap-bondad.html#cb558-2" aria-hidden="true" tabindex="-1"></a>breaks</span></code></pre></div>
<pre><code>##  [1] 4.30 4.66 5.02 5.38 5.74 6.10 6.46 6.82 7.18 7.54 7.90</code></pre>
<div class="sourceCode" id="cb560"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb560-1"><a href="chap-bondad.html#cb560-1" aria-hidden="true" tabindex="-1"></a>breaks2<span class="ot">=</span>breaks</span>
<span id="cb560-2"><a href="chap-bondad.html#cb560-2" aria-hidden="true" tabindex="-1"></a>breaks2[<span class="dv">1</span>]<span class="ot">=</span><span class="sc">-</span><span class="cn">Inf</span></span>
<span id="cb560-3"><a href="chap-bondad.html#cb560-3" aria-hidden="true" tabindex="-1"></a>breaks2[<span class="fu">length</span>(breaks2)]<span class="ot">=</span><span class="cn">Inf</span></span>
<span id="cb560-4"><a href="chap-bondad.html#cb560-4" aria-hidden="true" tabindex="-1"></a>breaks2</span></code></pre></div>
<pre><code>##  [1] -Inf 4.66 5.02 5.38 5.74 6.10 6.46 6.82 7.18 7.54  Inf</code></pre>
<p>Calculemos, como en el ejemplo anterior, las frecuencias observadas, las probabilidades teóricas y las frecuencias esperadas.</p>
<div class="sourceCode" id="cb562"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb562-1"><a href="chap-bondad.html#cb562-1" aria-hidden="true" tabindex="-1"></a>frec.obs<span class="ot">=</span><span class="fu">table</span>(<span class="fu">cut</span>(iris.sl,<span class="at">breaks=</span>breaks2))</span>
<span id="cb562-2"><a href="chap-bondad.html#cb562-2" aria-hidden="true" tabindex="-1"></a>frec.obs</span></code></pre></div>
<pre><code>## 
## (-Inf,4.66] (4.66,5.02] (5.02,5.38] (5.38,5.74]  (5.74,6.1]  (6.1,6.46] 
##           9          23          14          27          22          20 
## (6.46,6.82] (6.82,7.18] (7.18,7.54] (7.54, Inf] 
##          18           6           5           6</code></pre>
<div class="sourceCode" id="cb564"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb564-1"><a href="chap-bondad.html#cb564-1" aria-hidden="true" tabindex="-1"></a>extremo.izq<span class="ot">=</span>breaks2[<span class="sc">-</span><span class="fu">length</span>(breaks2)]</span>
<span id="cb564-2"><a href="chap-bondad.html#cb564-2" aria-hidden="true" tabindex="-1"></a>extremo.der<span class="ot">=</span>breaks2[<span class="sc">-</span><span class="dv">1</span>]</span>
<span id="cb564-3"><a href="chap-bondad.html#cb564-3" aria-hidden="true" tabindex="-1"></a>prob.teor<span class="ot">=</span><span class="fu">pnorm</span>(extremo.der,mu,sigma)<span class="sc">-</span><span class="fu">pnorm</span>(extremo.izq,mu,sigma)</span>
<span id="cb564-4"><a href="chap-bondad.html#cb564-4" aria-hidden="true" tabindex="-1"></a>frec.esp<span class="ot">=</span><span class="fu">round</span>(prob.teor<span class="sc">*</span><span class="fu">length</span>(iris.sl),<span class="dv">2</span>)</span>
<span id="cb564-5"><a href="chap-bondad.html#cb564-5" aria-hidden="true" tabindex="-1"></a>frec.esp</span></code></pre></div>
<pre><code>##  [1] 11.37 12.51 19.20 24.44 25.79 22.56 16.37  9.85  4.91  2.99</code></pre>
<p>Agruparemos las frecuencias de los dos últimos intervalos y aplicaremos el test <span class="math inline">\(\chi^2\)</span> con el número adecuado de grados de libertad:</p>
<div class="sourceCode" id="cb566"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb566-1"><a href="chap-bondad.html#cb566-1" aria-hidden="true" tabindex="-1"></a>frec.obs2<span class="ot">=</span><span class="fu">c</span>(frec.obs[<span class="dv">1</span><span class="sc">:</span><span class="dv">8</span>], <span class="fu">sum</span>(frec.obs[<span class="dv">9</span><span class="sc">:</span><span class="dv">10</span>]))</span>
<span id="cb566-2"><a href="chap-bondad.html#cb566-2" aria-hidden="true" tabindex="-1"></a>prob.teor2<span class="ot">=</span><span class="fu">c</span>(prob.teor[<span class="dv">1</span><span class="sc">:</span><span class="dv">8</span>], <span class="fu">sum</span>(prob.teor[<span class="dv">9</span><span class="sc">:</span><span class="dv">10</span>]))</span>
<span id="cb566-3"><a href="chap-bondad.html#cb566-3" aria-hidden="true" tabindex="-1"></a>test.iris<span class="fl">.2</span><span class="ot">=</span><span class="fu">chisq.test</span>(frec.obs2,<span class="at">p=</span>prob.teor2)</span>
<span id="cb566-4"><a href="chap-bondad.html#cb566-4" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span><span class="sc">-</span><span class="fu">pchisq</span>(test.iris<span class="fl">.2</span><span class="sc">$</span>statistic, test.iris<span class="fl">.2</span><span class="sc">$</span>parameter<span class="dv">-2</span>)</span></code></pre></div>
<pre><code>## X-squared 
## 0.0227734</code></pre>
<p>El p-valor es de nuevo inferior a 0.05: volvemos a obtener evidencia significativa de que la muestra no proviene de una población normal.</p>
</div>
<div id="el-test-de-kolgomorov-smirnov" class="section level2" number="6.4">
<h2><span class="header-section-number">6.4</span> El test de Kolgomorov-Smirnov</h2>
<p>El <strong>test de Kolgomorov-Smirnov</strong> (<strong>K-S</strong>) es un test genérico para contrastar la bondad de ajuste a distribuciones continuas. Se puede usar con muestras pequeñas (se suele recomendar 5 elementos como el tamaño mínimo para que el resultado sea significativo), pero la muestra no puede contener valores repetidos: si los contiene, la distribución del estadístico de contraste bajo la hipótesis nula no es la que predice la teoría sino que solo se aproxima a ella, y por lo tanto los p-valores que se obtienen son aproximados.</p>
<p>Hay que tener en cuenta que el test K-S realiza un contraste en el que la hipótesis nula es que la muestra proviene de una distribución continua completamente especificada. Es decir, no sirve para contrastar si la muestra proviene, pongamos, de “alguna” distribución normal, sino solo para contrastar si proviene de una distribución normal con una media y una desviación típica concretas. Así pues, si queremos contrastar que la muestra proviene de alguna distribución de una familia concreta y estimamos sus parámetros a partir de la muestra, el test K-S solo nos permite rechazar o no la hipótesis de que la muestra proviene de la distribución de esa familia con exactamente esos parámetros. Por lo tanto, si el resultado es rechazar la hipótesis nula, esto no excluye que la muestra provenga de una distribución de la misma familia con otros parámetros. En la próxima sección veremos algunos tests que permiten contrastar, en general, si una muestra proviene de alguna distribución normal.</p>
<p>La función básica para realizar el test K-S es <code>ks.test</code>. Su sintaxis
básica para una muestra es</p>
<div class="sourceCode" id="cb568"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb568-1"><a href="chap-bondad.html#cb568-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ks.test</span>(x, y, parámetros)</span></code></pre></div>
<p>donde:</p>
<ul>
<li><p><code>x</code> es la muestra de una variable continua.</p></li>
<li><p><code>y</code> puede ser un segundo vector, y entonces se contrasta si ambos vectores han sido generados por la misma distribución continua, o el nombre de la función de distribución (empezando con <code>p</code>) que queremos contrastar, entre comillas; por ejemplo <code>"pnorm"</code> para
la distribución normal.</p></li>
<li><p>Los <code>parámetros</code> de la función de distribución si se ha especificado una; por
ejemplo <code>mean=0, sd=1</code> para una distribución normal estándar.</p></li>
</ul>

<div class="example">
<p><span id="exm:unnamed-chunk-302" class="example"><strong>Ejemplo 6.10  </strong></span>Efectuemos el test de Kolmogorov-Smirnov para contrastar si las longitudes de sépalos de flores iris siguen una distribución normal de media y desviación típica sus estimaciones máximo verosímiles a partir la muestra <code>iris.sl</code>. Recordemos que tenemos guardados de los dos últimos ejemplos los valores de estas estimaciones en las variables <code>mu</code> y <code>sigma</code>:</p>
</div>
<div class="sourceCode" id="cb569"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb569-1"><a href="chap-bondad.html#cb569-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">c</span>(mu,sigma),<span class="dv">3</span>)</span></code></pre></div>
<pre><code>##  mean    sd 
## 5.843 0.825</code></pre>
<div class="sourceCode" id="cb571"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb571-1"><a href="chap-bondad.html#cb571-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ks.test</span>(iris.sl, <span class="st">&quot;pnorm&quot;</span>, <span class="at">mean=</span>mu, <span class="at">sd=</span>sigma)</span></code></pre></div>
<pre><code>## Warning in ks.test(iris.sl, &quot;pnorm&quot;, mean = mu, sd = sigma): ties should
## not be present for the Kolmogorov-Smirnov test</code></pre>
<pre><code>## 
## 	One-sample Kolmogorov-Smirnov test
## 
## data:  iris.sl
## D = 0.08945, p-value = 0.181
## alternative hypothesis: two-sided</code></pre>
<p>Obtenemos un p-valor de 0.181, que no nos permite rechazar la hipótesis de que siguen una ley N(5.843, 0.825). Pero R nos avisa de que hay empates. ¿Hay muchos? Vamos a calcular su frecuencia.</p>
<p>La función <code>unique</code> aplicada a un vector nos da el vector de sus elementos sin repeticiones. De esta manera podemos saber cuántos elementos diferentes hay en un vector, y por consiguiente también cuántas repeticiones.</p>
<div class="sourceCode" id="cb574"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb574-1"><a href="chap-bondad.html#cb574-1" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(<span class="fu">unique</span>(iris.sl))</span></code></pre></div>
<pre><code>## [1] 35</code></pre>
<div class="sourceCode" id="cb576"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb576-1"><a href="chap-bondad.html#cb576-1" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span><span class="sc">-</span><span class="fu">length</span>(<span class="fu">unique</span>(iris.sl))<span class="sc">/</span><span class="fu">length</span>(iris.sl)</span></code></pre></div>
<pre><code>## [1] 0.766667</code></pre>
<p>Por tanto, el vector (de 150 entradas) de longitudes de sépalos solo tiene 35 valores diferentes. El resto, un 76.67%, son valores repetidos. Hay muchos empates, y el resultado de este test en este caso es poco fiable</p>
<p>Como hemos comentado, el test K-S también se puede usar para contrastar si dos muestras se han obtenido de poblaciones con la misma distribución continua. Para hacerlo, se ha de aplicar la función <code>ks.test</code> a las dos muestras.</p>

<div class="example">
<p><span id="exm:unnamed-chunk-305" class="example"><strong>Ejemplo 6.11  </strong></span>La tabla de datos <code>Salaries</code> del paquete <strong>car</strong> contiene información sobre los sueldos de 397 profesores de una universidad norteamericana en el curso 2008-09. Démosle un vistazo.</p>
</div>
<div class="sourceCode" id="cb578"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb578-1"><a href="chap-bondad.html#cb578-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span>
<span id="cb578-2"><a href="chap-bondad.html#cb578-2" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(Salaries)</span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:	397 obs. of  6 variables:
##  $ rank         : Factor w/ 3 levels &quot;AsstProf&quot;,&quot;AssocProf&quot;,..: 3 3 1 3 3 2 3 3 3 3 ...
##  $ discipline   : Factor w/ 2 levels &quot;A&quot;,&quot;B&quot;: 2 2 2 2 2 2 2 2 2 2 ...
##  $ yrs.since.phd: int  19 20 4 45 40 6 30 45 21 18 ...
##  $ yrs.service  : int  18 16 3 39 41 6 23 45 20 18 ...
##  $ sex          : Factor w/ 2 levels &quot;Female&quot;,&quot;Male&quot;: 2 2 2 2 2 2 2 2 2 1 ...
##  $ salary       : int  139750 173200 79750 115000 141500 97000 175000 147765 119250 129000 ...</code></pre>
<p>La variable <code>sex</code> nos da el sexo del profesor y la variable <code>salary</code> su sueldo anual en dólares. Queremos contrastar si los sueldos de hombres y mujeres siguen la misma distribución. Para ello, vamos a suponer que provienen de distribuciones continuas y usaremos el test K-S. Primero miraremos si hay muchos empates.</p>
<div class="sourceCode" id="cb580"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb580-1"><a href="chap-bondad.html#cb580-1" aria-hidden="true" tabindex="-1"></a>sal.female<span class="ot">=</span>Salaries[Salaries<span class="sc">$</span>sex<span class="sc">==</span><span class="st">&quot;Female&quot;</span>,]<span class="sc">$</span>salary  <span class="co">#Salarios de mujeres</span></span>
<span id="cb580-2"><a href="chap-bondad.html#cb580-2" aria-hidden="true" tabindex="-1"></a>sal.male<span class="ot">=</span>Salaries[Salaries<span class="sc">$</span>sex<span class="sc">==</span><span class="st">&quot;Male&quot;</span>,]<span class="sc">$</span>salary  <span class="co">#Salarios de hombres</span></span>
<span id="cb580-3"><a href="chap-bondad.html#cb580-3" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span><span class="sc">-</span><span class="fu">length</span>(<span class="fu">unique</span>(sal.female))<span class="sc">/</span><span class="fu">length</span>(sal.female) <span class="co">#Proporción de salarios de mujeres repetidos</span></span></code></pre></div>
<pre><code>## [1] 0.05128205</code></pre>
<div class="sourceCode" id="cb582"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb582-1"><a href="chap-bondad.html#cb582-1" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span><span class="sc">-</span><span class="fu">length</span>(<span class="fu">unique</span>(sal.male))<span class="sc">/</span><span class="fu">length</span>(sal.male)  <span class="co">#Proporción de salarios de hombres repetidos</span></span></code></pre></div>
<pre><code>## [1] 0.05027933</code></pre>
<div class="sourceCode" id="cb584"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb584-1"><a href="chap-bondad.html#cb584-1" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span><span class="sc">-</span><span class="fu">length</span>(<span class="fu">unique</span>(Salaries<span class="sc">$</span>salary))<span class="sc">/</span><span class="fu">length</span>(Salaries<span class="sc">$</span>salary)  <span class="co">#Proporción global de salarios repetidos</span></span></code></pre></div>
<pre><code>## [1] 0.06549118</code></pre>
<p>Las repeticiones en cada lista significan alrededor del 5% de los datos, y en total un 6.5%. No son muchas, así que vamos a arriesgarnos con el test K-S.</p>
<div class="sourceCode" id="cb586"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb586-1"><a href="chap-bondad.html#cb586-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ks.test</span>(sal.male,sal.female)</span></code></pre></div>
<pre><code>## 
## 	Two-sample Kolmogorov-Smirnov test
## 
## data:  sal.male and sal.female
## D = 0.2472, p-value = 0.0271
## alternative hypothesis: two-sided</code></pre>
<p>El p-valor pequeño nos permite rechazar que los salarios de hombres y mujeres sigan la misma distribución. Pero no nos paremos aquí.</p>
<p>Si dibujamos un boxplot (véase la Figura <a href="chap-bondad.html#fig:duros">6.4</a>) de los salarios según el sexo, observaremos que los sueldos de los hombres tienen mayor mediana y variabilidad que los de las mujeres, incluyendo algunos valores atípicos grandes (¿el rector y otros altos cargos académicos?).</p>
<div class="sourceCode" id="cb588"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb588-1"><a href="chap-bondad.html#cb588-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(salary<span class="sc">~</span>sex, <span class="at">data=</span>Salaries, <span class="at">main=</span><span class="st">&quot;&quot;</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:duros"></span>
<img src="AprendeR-Parte-II_files/figure-html/duros-1.png" alt="Boxplot de sueldos según el sexo en la tabla de datos *Salaries*" width="480" />
<p class="caption">
Figura 6.4: Boxplot de sueldos según el sexo en la tabla de datos <em>Salaries</em>
</p>
</div>
<p>Si cancelamos este efecto, estandarizando las muestras, ¿siguen saliendo distribuciones diferentes? Para estandarizar las muestras usaremos la función <code>scale</code>, que explicaremos con más detalle en la Lección <a href="chap-estmult.html#chap:estmult">8</a>. Esta función, aplicada tal cual a un vector, le resta su media y divide el resultado por su desviación típica muestral.</p>
<div class="sourceCode" id="cb589"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb589-1"><a href="chap-bondad.html#cb589-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ks.test</span>(<span class="fu">scale</span>(sal.male),<span class="fu">scale</span>(sal.female))</span></code></pre></div>
<pre><code>## Warning in ks.test(scale(sal.male), scale(sal.female)): p-value will be
## approximate in the presence of ties</code></pre>
<pre><code>## 
## 	Two-sample Kolmogorov-Smirnov test
## 
## data:  scale(sal.male) and scale(sal.female)
## D = 0.139, p-value = 0.505
## alternative hypothesis: two-sided</code></pre>
<p>Al estandarizar, ya no tenemos evidencia de que provengan de distribuciones diferentes. Es decir, podemos aceptar que sus valores tipificados siguen la misma distribución.</p>
</div>
<div id="tests-de-normalidad" class="section level2" number="6.5">
<h2><span class="header-section-number">6.5</span> Tests de normalidad</h2>
<p>Existen algunos tests específicos de normalidad que permiten contrastar si una muestra proviene de alguna distribución normal. El más conocido es el <strong>test de normalidad de Kolmogorov-Smirnov-Lilliefors</strong> (<strong>K-S-L</strong>). Se trata de una variante del test K-S, y se puede realizar aplicando a la muestra la función <code>lillie.test</code> del paquete <strong>nortest</strong>.</p>
<p>Vamos a usar el test K-S-L para contrastar si las longitudes de los sépalos de las iris siguen una ley normal.</p>
<div class="sourceCode" id="cb592"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb592-1"><a href="chap-bondad.html#cb592-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(nortest)</span>
<span id="cb592-2"><a href="chap-bondad.html#cb592-2" aria-hidden="true" tabindex="-1"></a>iris.sl<span class="ot">=</span>iris<span class="sc">$</span>Sepal.Length</span>
<span id="cb592-3"><a href="chap-bondad.html#cb592-3" aria-hidden="true" tabindex="-1"></a><span class="fu">lillie.test</span>(iris.sl)</span></code></pre></div>
<pre><code>## 
## 	Lilliefors (Kolmogorov-Smirnov) normality test
## 
## data:  iris.sl
## D = 0.08865, p-value = 0.00579</code></pre>
<p>El p-valor es muy pequeño, y nos permite rechazar que la muestra provenga de una población normal.</p>
<p>La ventaja del test K-S-L es que es muy conocido, ya que es una variante del K-S (incluso usa el mismo estadístico), pero tiene un inconveniente: aunque es muy sensible a las diferencias entre la muestra y la distribución teórica alrededor de sus valores medios, le cuesta detectar diferencias prominentes en un extremo u otro de la distribución. Esto afecta su potencia. Por ejemplo, sabemos que una t de Student se parece bastante a una normal estándar, pero su densidad es algo más aplanada y hace que en los dos extremos esté por encima de la de la normal.
Al test K-S-L le cuesta detectar esta discrepancia, como podemos ver en el siguiente ejemplo:</p>
<div class="sourceCode" id="cb594"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb594-1"><a href="chap-bondad.html#cb594-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">100</span>)</span>
<span id="cb594-2"><a href="chap-bondad.html#cb594-2" aria-hidden="true" tabindex="-1"></a>x<span class="ot">=</span><span class="fu">rt</span>(<span class="dv">50</span>,<span class="dv">3</span>)   <span class="co">#Una muestra de una t de Student con 3 g.l.</span></span>
<span id="cb594-3"><a href="chap-bondad.html#cb594-3" aria-hidden="true" tabindex="-1"></a><span class="fu">lillie.test</span>(x)</span></code></pre></div>
<pre><code>## 
## 	Lilliefors (Kolmogorov-Smirnov) normality test
## 
## data:  x
## D = 0.1033, p-value = 0.201</code></pre>
<p>Este inconveniente del test K-S-L lo resuelve el <strong>test de normalidad de Anderson-Darling</strong> (<strong>A-D</strong>). Para realizarlo podemos usar la función <code>ad.test</code> del paquete <strong>nortest</strong>. Encontraréis los detalles del estadístico que usa en la Ayuda de la función.</p>
<div class="sourceCode" id="cb596"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb596-1"><a href="chap-bondad.html#cb596-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ad.test</span>(iris.sl)</span></code></pre></div>
<pre><code>## 
## 	Anderson-Darling normality test
## 
## data:  iris.sl
## A = 0.8892, p-value = 0.0225</code></pre>
<p>De nuevo obtenemos un p-valor muy pequeño. Veamos ahora que este test sí que detecta que la muestra anterior de una t de Student con 3 grados de libertad no proviene de una normal:</p>
<div class="sourceCode" id="cb598"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb598-1"><a href="chap-bondad.html#cb598-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">100</span>)</span>
<span id="cb598-2"><a href="chap-bondad.html#cb598-2" aria-hidden="true" tabindex="-1"></a>x<span class="ot">=</span><span class="fu">rt</span>(<span class="dv">50</span>,<span class="dv">3</span>)</span>
<span id="cb598-3"><a href="chap-bondad.html#cb598-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ad.test</span>(x)</span></code></pre></div>
<pre><code>## 
## 	Anderson-Darling normality test
## 
## data:  x
## A = 1.166, p-value = 0.00433</code></pre>
<p>Un inconveniente común a los tests K-S-L y A-D es que, si bien pueden usarse con muestras pequeñas (pongamos de más de 5 elementos), se comportan mal con muestras grandes, de varios miles de elementos. En muestras de este tamaño, cualquier pequeña divergencia de la normalidad se magnifica y en estos dos tests aumenta la probabilidad de errores de tipo I. Un test que resuelve este problema es el de <strong>Shapiro-Wilk</strong> (<strong>S-W</strong>), implementado en la función <code>shapiro.test</code> de la instalación básica de R.
Este test es importante, porque un experimento reciente ha mostrado evidencia significativa de que su potencia es mayor que la de los tests anteriores.<a href="#fn6" class="footnote-ref" id="fnref6"><sup>6</sup></a>
De nuevo, los detalles del estadístico que usa los encontraréis en la Ayuda de la función.</p>
<div class="sourceCode" id="cb600"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb600-1"><a href="chap-bondad.html#cb600-1" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(iris.sl)</span></code></pre></div>
<pre><code>## 
## 	Shapiro-Wilk normality test
## 
## data:  iris.sl
## W = 0.9761, p-value = 0.0102</code></pre>
<div class="sourceCode" id="cb602"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb602-1"><a href="chap-bondad.html#cb602-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">100</span>)</span>
<span id="cb602-2"><a href="chap-bondad.html#cb602-2" aria-hidden="true" tabindex="-1"></a>x<span class="ot">=</span><span class="fu">rt</span>(<span class="dv">50</span>,<span class="dv">3</span>)</span>
<span id="cb602-3"><a href="chap-bondad.html#cb602-3" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(x)</span></code></pre></div>
<pre><code>## 
## 	Shapiro-Wilk normality test
## 
## data:  x
## W = 0.8949, p-value = 0.000329</code></pre>
<p>Un último inconveniente que afecta a todos los tests explicados hasta ahora es el de los empates. Sus estadísticos tienen las distribuciones que se usan para calcular los p-valores cuando la muestra no tiene datos repetidos, y por lo tanto, si hay muchos, el p-valor puede no tener ningún significado. De los tres, el menos sensible a repeticiones es el S-W, pero si hay muchas es conveniente usar un test que no sea sensible a ellas, como por ejemplo el <strong>test omnibus de D’Agostino-Pearson</strong>. Este test se encuentra implementado en la función <code>dagoTest</code> del paquete <strong>fBasics</strong>, y lo que hace es cuantificar lo diferentes que son la asimetría y la curtosis de la muestra (dos parámetros estadísticos relacionados con la forma de la gráfica de la función de densidad muestral) respecto de los esperados en una distribución normal, y resume esta discrepancia en un p-valor con el significado usual.</p>
<div class="sourceCode" id="cb604"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb604-1"><a href="chap-bondad.html#cb604-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(fBasics)</span>
<span id="cb604-2"><a href="chap-bondad.html#cb604-2" aria-hidden="true" tabindex="-1"></a><span class="fu">dagoTest</span>(iris.sl)</span></code></pre></div>
<pre><code>## 
## Title:
##  D&#39;Agostino Normality Test
## 
## Test Results:
##   STATISTIC:
##     Chi2 | Omnibus: 5.7356
##     Z3  | Skewness: 1.5963
##     Z4  | Kurtosis: -1.7853
##   P VALUE:
##     Omnibus  Test: 0.05682 
##     Skewness Test: 0.1104 
##     Kurtosis Test: 0.07421 
## 
## Description:
##  Wed Mar 18 09:28:34 2020 by user:</code></pre>
<p>El p-valor relevante es el del <em>“Omnibus test”</em>, en este caso 0.0568 cae en la zona de penumbra.</p>
<p>Queremos hacer una última advertencia en esta sección. Aunque los tests que hemos explicado se pueden aplicar a muestras pequeñas, es muy difícil rechazar la normalidad de una muestra muy pequeña. Por ejemplo, una muestra de 10 valores escogidos con distribución uniforme entre 0 y 5 pasa holgadamente todos los tests de normalidad (salvo el de D’Agostino-Pearson, que requiere una muestra de al menos 20 elementos):</p>
<div class="sourceCode" id="cb606"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb606-1"><a href="chap-bondad.html#cb606-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">100</span>)</span>
<span id="cb606-2"><a href="chap-bondad.html#cb606-2" aria-hidden="true" tabindex="-1"></a>x<span class="ot">=</span><span class="fu">runif</span>(<span class="dv">10</span>,<span class="dv">0</span>,<span class="dv">5</span>)</span>
<span id="cb606-3"><a href="chap-bondad.html#cb606-3" aria-hidden="true" tabindex="-1"></a><span class="fu">lillie.test</span>(x)</span></code></pre></div>
<pre><code>## 
## 	Lilliefors (Kolmogorov-Smirnov) normality test
## 
## data:  x
## D = 0.1459, p-value = 0.79</code></pre>
<div class="sourceCode" id="cb608"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb608-1"><a href="chap-bondad.html#cb608-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ad.test</span>(x)</span></code></pre></div>
<pre><code>## 
## 	Anderson-Darling normality test
## 
## data:  x
## A = 0.1663, p-value = 0.912</code></pre>
<div class="sourceCode" id="cb610"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb610-1"><a href="chap-bondad.html#cb610-1" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(x)</span></code></pre></div>
<pre><code>## 
## 	Shapiro-Wilk normality test
## 
## data:  x
## W = 0.9803, p-value = 0.967</code></pre>
<div class="sourceCode" id="cb612"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb612-1"><a href="chap-bondad.html#cb612-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dagoTest</span>(x)</span></code></pre></div>
<pre><code>## Error in .omnibus.test(x): sample size must be at least 20</code></pre>
</div>
<div id="guía-rápida" class="section level2" number="6.6">
<h2><span class="header-section-number">6.6</span> Guía rápida</h2>
<ul>
<li><p><code>qqPlot</code>, del paquete <strong>car</strong>, sirve para dibujar un Q-Q-plot de una muestra contra una distribución teórica. Sus parámetros principales son:</p>
<ul>
<li><code>distribution</code>: el nombre de la familia de distribuciones, entre comillas.</li>
<li>Los parámetros de la distribución: <code>mean</code> para la media, <code>sd</code> para la desviación típica, <code>df</code> para los grados de libertad, etc.</li>
<li>Los parámetros usuales de <code>plot</code>.</li>
</ul></li>
<li><p><code>chisq.test</code> sirve para realizar tests <span class="math inline">\(\chi^2\)</span> de bondad de ajuste. Sus parámetros principales son:</p>
<ul>
<li><code>p</code>: el vector de probabilidades teóricas.</li>
<li><code>rescale.p</code>: igualado a <code>TRUE</code>, indica que los valores de <code>p</code> no son probabilidades, sino sólo proporcionales a las probabilidades.</li>
<li><code>simulate.p.value</code>: igualado a <code>TRUE</code>, R calcula el p-valor mediante simulaciones.</li>
<li><code>B</code>: en este último caso, permite especificar el número de simulaciones.</li>
</ul></li>
<li><p><code>ks.test</code> realiza el test de Kolmogorov-Smirnov. Tiene dos tipos de uso:</p>
<ul>
<li><code>ks.test(x,y)</code>: contrasta si los vectores <code>x</code> e <code>y</code> han sido generados por la misma distribución continua.</li>
<li><code>ks.test(x, "distribución", parámetros)</code>: contrasta si el vector <code>x</code> ha sido generado por la distribución especificada, que se ha de indicar con el nombre de la función de distribución de R (la que empieza con p).</li>
</ul></li>
<li><p><code>lillie.test</code>, del paquete <strong>nortest</strong>, realiza el test de normalidad de Kolmogorov-Smirnov-Lilliefors.</p></li>
<li><p><code>ad.test</code>, del paquete <strong>nortest</strong>, realiza el test de normalidad de Anderson-Darling.</p></li>
<li><p><code>shapiro.test</code> realiza el test de normalidad de Shapiro-Wilk.</p></li>
<li><p><code>dagoTest</code>, del paquete <strong>fBasics</strong>, realiza el test ómnibus de D’Agostino-Pearson.</p></li>
</ul>
</div>
<div id="ejercicios" class="section level2" number="6.7">
<h2><span class="header-section-number">6.7</span> Ejercicios</h2>
<div id="modelo-de-test" class="section level3 unnumbered">
<h3>Modelo de test</h3>
<p><em>(1)</em> Un determinado experimento tiene cinco resultados posibles: A, B, C, D, E. Lo repetimos un cierto número de veces y obtenemos 65 veces el resultado A, 95 veces el resultado B, 87 veces el resultado C, 70 veces el resultado D y 193 veces el resultado E. Realizad un test <span class="math inline">\(\chi^2\)</span> para contrastar si los resultados A, B, C y D tienen la misma probabilidad y E tiene el doble de probabilidad que cada uno de los otros resultados. Dad el p-valor del contraste (redondeado a 3 cifras decimales, sin ceros innecesarios a la derecha) y decid (contestando SI, en mayúsculas y sin acento, o NO) si tendríamos que rechazar la hipótesis nula con un nivel de significación <span class="math inline">\(\alpha=0.05\)</span>. Tenéis que dar las respuestas en este orden y separadas por un único espacio en blanco.</p>
<p><em>(2)</em> Queremos contrastar si una determinada variable sigue una distribución de Poisson. Hemos efectuado algunas observaciones y hemos obtenido 10 veces el resultado 0, 32 veces el resultado 1, 18 veces el resultado 2, 19 veces el resultado 3 y 6 veces el resultado 4. Tenéis que calcular el estimador máximo verosímil del parámetro <span class="math inline">\(\lambda\)</span> de una variable de Poisson que haya generado estas observaciones (redondeado a 3 cifras decimales, y sin ceros innecesarios a la derecha), calcular el p-valor (redondeado a 3 cifras decimales, sin ceros innecesarios a la derecha) del test <span class="math inline">\(\chi^2\)</span> para determinar si la muestra sigue <em>alguna</em> distribución de Poisson habiendo estimado como su parámetro <span class="math inline">\(\lambda\)</span> este valor redondeado, y decir (contestando SI o NO) si, con un nivel de significación <span class="math inline">\(\alpha=0.1\)</span>, tendríamos que rechazar la hipótesis nula de que esta muestra proviene de una variable aleatoria de Poisson. Dad las tres respuestas en este orden y separadas por un único espacio en blanco.</p>
<p><em>(3)</em> Queremos contrastar si una cierta variable sigue una distribución normal. Hemos efectuado 150 observaciones y hemos obtenido 9 veces un valor dentro de ]0,3], 27 veces un valor dentro de ]3,6], 51 veces un valor dentro de ]6,9], 46 veces un valor dentro de ]9,12] y 17 veces un valor dentro de ]12,15]. Tenéis que: calcular los estimadores máximo verosímiles del parámetro <span class="math inline">\(\mu\)</span> y del parámetro <span class="math inline">\(\sigma\)</span> de una variable normal que haya generado estas observaciones (ambos redondeados a 2 cifras decimales y sin ceros innecesarios a la derecha): calcular el p-valor (redondeado a 3 cifras decimales, sin ceros innecesarios a la derecha) del test <span class="math inline">\(\chi^2\)</span> para contrastar si la muestra sigue <em>alguna</em> distribución normal, empleando estos valores estimados redondeados de los parámetros que habéis dado para especificar la distribución teórica; y decir (contestando SI o NO) si, con un nivel de significación <span class="math inline">\(\alpha=0.05\)</span>, tendríamos que rechazar la hipótesis nula de que esta muestra proviene de una variable aleatoria normal. Dad las cuatro respuestas en este orden y separadas por un único espacio en blanco.</p>
<p><em>(4)</em> Generad una muestra aleatoria <em>x</em> de 25 valores de una distribución <span class="math inline">\(\chi^2\)</span> con 10 grados de libertad, fijando antes <code>set.seed(2014)</code>, y aplicad el test de Kolmogorov-Smirnov para contrastar si <em>x</em> proviene de una distribución N(10,3.16). Dad el p-valor del test (redondeado a 3 cifras decimales, sin ceros innecesarios a la derecha) y decid (contestando SI o NO) si, con un nivel de significación <span class="math inline">\(\alpha=0.05\)</span>, tendríamos que rechazar la hipótesis nula de que esta muestra proviene de esta distribución. Tenéis que dar las dos respuestas en este orden y separadas por un único espacio en blanco.</p>
<p><em>(5)</em> Queremos contrastar si la muestra siguiente sigue una distribución normal: 4.6, 0.97, 0.3, 1.11, 2.16, 15.52, 1.13, 0.17, 0.64, 2.00. Dad el p-valor (redondeado a 3 cifras decimales y sin ceros innecesarios a la derecha) del test de Kolmogorov-Smirnov-Lilliefors para esta muestra y decid (contestando SI o NO) si, con un nivel de significación <span class="math inline">\(\alpha=0.05\)</span>, tendríamos que rechazar la hipótesis nula de que esta muestra sigue una distribución normal. Tenéis que dar las dos respuestas en este orden y separadas por un único espacio en blanco.</p>
<p><em>(6)</em> Generad una muestra aleatoria <em>x</em> de 15 valores de una distribución normal con <span class="math inline">\(\mu=2\)</span> y <span class="math inline">\(\sigma=0.8\)</span> fijando antes <code>set.seed(2014)</code>, y una muestra aleatoria <em>y</em> de 25 valores de una distribución exponencial de parámetro <span class="math inline">\(1/\lambda=0.5\)</span> fijando antes <code>set.seed(1007)</code>. Aplicad el test de Kolmogorov-Smirnov para contrastar si <em>x</em> e <em>y</em> provienen de una misma distribución continua. Tenéis que dar el p-valor del test (redondeado a 3 cifras decimales, sin ceros innecesarios a la derecha) y decir (contestando SI o NO) si, con un nivel de significación <span class="math inline">\(\alpha=0.05\)</span>, tendríamos que rechazar la hipótesis nula de que estas dos muestras provienen de la misma distribución continua. Dad las dos respuestas en este orden y separadas por un único espacio en blanco.</p>
</div>
<div id="problemas" class="section level3 unnumbered">
<h3>Problemas</h3>
<p><strong>(1)</strong> La tabla siguiente da, por cada Comunidad Autónoma, su población según el censo de 2013 y el número de defunciones durante el primer semestre de 2014:</p>
<table>
<thead>
<tr class="header">
<th align="left">Comunidad</th>
<th align="right">Población</th>
<th align="right">Defunciones</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Andalucía</td>
<td align="right">8440300</td>
<td align="right">34810</td>
</tr>
<tr class="even">
<td align="left">Aragón</td>
<td align="right">1347150</td>
<td align="right">7196</td>
</tr>
<tr class="odd">
<td align="left">Asturias (Principado de)</td>
<td align="right">1068165</td>
<td align="right">6623</td>
</tr>
<tr class="even">
<td align="left">Balears (Illes)</td>
<td align="right">1111674</td>
<td align="right">4088</td>
</tr>
<tr class="odd">
<td align="left">Canarias</td>
<td align="right">2118679</td>
<td align="right">7593</td>
</tr>
<tr class="even">
<td align="left">Cantabria</td>
<td align="right">591888</td>
<td align="right">3031</td>
</tr>
<tr class="odd">
<td align="left">Castilla-La Mancha</td>
<td align="right">2100998</td>
<td align="right">14532</td>
</tr>
<tr class="even">
<td align="left">Castilla y León</td>
<td align="right">2519875</td>
<td align="right">9765</td>
</tr>
<tr class="odd">
<td align="left">Cataluña</td>
<td align="right">7553650</td>
<td align="right">32383</td>
</tr>
<tr class="even">
<td align="left">Comunitat Valenciana</td>
<td align="right">5113815</td>
<td align="right">21614</td>
</tr>
<tr class="odd">
<td align="left">Extremadura</td>
<td align="right">1104004</td>
<td align="right">5751</td>
</tr>
<tr class="even">
<td align="left">Galicia</td>
<td align="right">2765940</td>
<td align="right">15888</td>
</tr>
<tr class="odd">
<td align="left">Madrid (Comunidad de)</td>
<td align="right">6495551</td>
<td align="right">22446</td>
</tr>
<tr class="even">
<td align="left">Murcia (Región de)</td>
<td align="right">1472049</td>
<td align="right">5330</td>
</tr>
<tr class="odd">
<td align="left">Navarra (Comunidad Foral de)</td>
<td align="right">644477</td>
<td align="right">2846</td>
</tr>
<tr class="even">
<td align="left">País Vasco</td>
<td align="right">2191682</td>
<td align="right">10639</td>
</tr>
<tr class="odd">
<td align="left">Rioja (La)</td>
<td align="right">322027</td>
<td align="right">1489</td>
</tr>
<tr class="even">
<td align="left">Ceuta</td>
<td align="right">84180</td>
<td align="right">252</td>
</tr>
<tr class="odd">
<td align="left">Melilla</td>
<td align="right">83679</td>
<td align="right">234</td>
</tr>
</tbody>
</table>
<p>Tenéis esta tabla de datos en el url <a href="https://raw.githubusercontent.com/AprendeR-UIB/AprendeR2privat/master/INE.txt" class="uri">https://raw.githubusercontent.com/AprendeR-UIB/AprendeR2privat/master/INE.txt</a>.</p>
<p>Efectuad un test <span class="math inline">\(\chi^2\)</span> para contrastar si la población por comunidades autónomas y el número de defunciones por comunidad autónoma tienen la misma distribución.</p>
<p><strong>(2)</strong> En los cursos introductorios de estadística se suele dar como ejemplo de variable aleatoria de Poisson los números de goles marcados en partidos de fútbol. Vamos a contrastarlo en un ejemplo concreto. La tabla siguiente da los números de partidos en los que se marcaron los diferentes números de goles en el Mundial de Sudáfrica del 2010:</p>
<table>
<thead>
<tr class="header">
<th align="right">Goles</th>
<th align="right">Partidos</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">0</td>
<td align="right">7</td>
</tr>
<tr class="even">
<td align="right">1</td>
<td align="right">17</td>
</tr>
<tr class="odd">
<td align="right">2</td>
<td align="right">13</td>
</tr>
<tr class="even">
<td align="right">3</td>
<td align="right">14</td>
</tr>
<tr class="odd">
<td align="right">4</td>
<td align="right">8</td>
</tr>
<tr class="even">
<td align="right">5</td>
<td align="right">3</td>
</tr>
<tr class="odd">
<td align="right">7</td>
<td align="right">1</td>
</tr>
</tbody>
</table>
<p>Usad un test <span class="math inline">\(\chi^2\)</span> para contrastar si podemos aceptar que estos números de goles siguen una ley de Poisson.</p>
<p><strong>(3)</strong> Considerad la tabla de datos que encontraréis en el url <a href="https://www.dropbox.com/s/qcok2f7u51teqr6/pacientes.txt?raw=1" class="uri">https://www.dropbox.com/s/qcok2f7u51teqr6/pacientes.txt?raw=1</a> y que ya usamos en un ejercicio de la Lección <a href="chap-IC.html#chap:IC">4</a>.</p>
<p><em>(a)</em> Usad el test de Shapiro-Wilk para contrastar si los pesos de los hombres de esta tabla siguen una distribución normal</p>
<p><em>(b)</em> Llevad a cabo el mismo contraste usando un test <span class="math inline">\(\chi^2\)</span>.</p>
</div>
<div id="respuestas-al-test" class="section level3 unnumbered">
<h3>Respuestas al test</h3>
<p><em>(1)</em> 0.02 SI</p>
<p>Nosotros lo hemos calculado con</p>
<div class="sourceCode" id="cb614"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb614-1"><a href="chap-bondad.html#cb614-1" aria-hidden="true" tabindex="-1"></a>x<span class="ot">=</span><span class="fu">c</span>(<span class="dv">65</span>,<span class="dv">95</span>,<span class="dv">87</span>,<span class="dv">70</span>,<span class="dv">193</span>)</span>
<span id="cb614-2"><a href="chap-bondad.html#cb614-2" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">chisq.test</span>(x,<span class="at">p=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">2</span>),<span class="at">rescale.p=</span>T)<span class="sc">$</span>p.value,<span class="dv">3</span>)</span></code></pre></div>
<pre><code>## [1] 0.02</code></pre>
<p><em>(2)</em> 1.753 0.064 SI</p>
<p>Nosotros lo hemos calculado con</p>
<div class="sourceCode" id="cb616"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb616-1"><a href="chap-bondad.html#cb616-1" aria-hidden="true" tabindex="-1"></a>x<span class="ot">=</span><span class="fu">c</span>(<span class="dv">10</span>,<span class="dv">32</span>,<span class="dv">18</span>,<span class="dv">19</span>,<span class="dv">6</span>)</span>
<span id="cb616-2"><a href="chap-bondad.html#cb616-2" aria-hidden="true" tabindex="-1"></a>lambda<span class="ot">=</span><span class="fu">round</span>(<span class="fu">fitdistr</span>(<span class="fu">rep</span>(<span class="dv">0</span><span class="sc">:</span><span class="dv">4</span>,x),<span class="st">&quot;poisson&quot;</span>)<span class="sc">$</span>estimate,<span class="dv">3</span>)  <span class="co">#Estimamos la lambda</span></span>
<span id="cb616-3"><a href="chap-bondad.html#cb616-3" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="fu">dpois</span>(<span class="dv">0</span><span class="sc">:</span><span class="dv">3</span>,lambda),<span class="dv">1</span><span class="sc">-</span><span class="fu">ppois</span>(<span class="dv">3</span>,lambda))<span class="sc">*</span><span class="dv">85</span>  <span class="co">#Frecuencias esperadas</span></span></code></pre></div>
<pre><code>## [1] 14.726539 25.815623 22.627394 13.221940  8.608503</code></pre>
<div class="sourceCode" id="cb618"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb618-1"><a href="chap-bondad.html#cb618-1" aria-hidden="true" tabindex="-1"></a>ChiT2<span class="ot">=</span><span class="fu">chisq.test</span>(x,<span class="at">p=</span><span class="fu">c</span>(<span class="fu">dpois</span>(<span class="dv">0</span><span class="sc">:</span><span class="dv">3</span>,lambda),<span class="dv">1</span><span class="sc">-</span><span class="fu">ppois</span>(<span class="dv">3</span>,lambda)))  <span class="co">#Test</span></span>
<span id="cb618-2"><a href="chap-bondad.html#cb618-2" aria-hidden="true" tabindex="-1"></a>p.valor2<span class="ot">=</span><span class="dv">1</span><span class="sc">-</span><span class="fu">pchisq</span>(ChiT2<span class="sc">$</span>statistic,<span class="dv">3</span>)  <span class="co">#p-valor correcto</span></span>
<span id="cb618-3"><a href="chap-bondad.html#cb618-3" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(lambda,<span class="fu">round</span>(p.valor2,<span class="dv">3</span>))</span></code></pre></div>
<pre><code>##    lambda X-squared 
##     1.753     0.064</code></pre>
<p><em>(3)</em> 8.2 3.18 0.692 NO</p>
<p>Nosotros lo hemos calculado con</p>
<div class="sourceCode" id="cb620"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb620-1"><a href="chap-bondad.html#cb620-1" aria-hidden="true" tabindex="-1"></a>x<span class="ot">=</span><span class="fu">c</span>(<span class="dv">9</span>,<span class="dv">27</span>,<span class="dv">51</span>,<span class="dv">46</span>,<span class="dv">17</span>)</span>
<span id="cb620-2"><a href="chap-bondad.html#cb620-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(x)</span></code></pre></div>
<pre><code>## [1] 150</code></pre>
<div class="sourceCode" id="cb622"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb622-1"><a href="chap-bondad.html#cb622-1" aria-hidden="true" tabindex="-1"></a>muestra<span class="ot">=</span><span class="fu">rep</span>(<span class="fu">c</span>(<span class="fl">1.5</span>,<span class="fl">4.5</span>,<span class="fl">7.5</span>,<span class="fl">10.5</span>,<span class="fl">13.5</span>),x)</span>
<span id="cb622-2"><a href="chap-bondad.html#cb622-2" aria-hidden="true" tabindex="-1"></a><span class="fu">fitdistr</span>(muestra,<span class="st">&quot;normal&quot;</span>)</span></code></pre></div>
<pre><code>##      mean         sd    
##   8.2000000   3.1827661 
##  (0.2598718) (0.1837571)</code></pre>
<div class="sourceCode" id="cb624"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb624-1"><a href="chap-bondad.html#cb624-1" aria-hidden="true" tabindex="-1"></a>mu<span class="ot">=</span><span class="fu">round</span>(<span class="fu">fitdistr</span>(muestra,<span class="st">&quot;normal&quot;</span>)<span class="sc">$</span>estimate[<span class="dv">1</span>],<span class="dv">2</span>)</span>
<span id="cb624-2"><a href="chap-bondad.html#cb624-2" aria-hidden="true" tabindex="-1"></a>sigma<span class="ot">=</span><span class="fu">round</span>(<span class="fu">fitdistr</span>(muestra,<span class="st">&quot;normal&quot;</span>)<span class="sc">$</span>estimate[<span class="dv">2</span>],<span class="dv">2</span>)</span>
<span id="cb624-3"><a href="chap-bondad.html#cb624-3" aria-hidden="true" tabindex="-1"></a>left<span class="ot">=</span><span class="fu">c</span>(<span class="sc">-</span><span class="cn">Inf</span>,<span class="dv">3</span>,<span class="dv">6</span>,<span class="dv">9</span>,<span class="dv">12</span>)</span>
<span id="cb624-4"><a href="chap-bondad.html#cb624-4" aria-hidden="true" tabindex="-1"></a>right<span class="ot">=</span><span class="fu">c</span>(<span class="dv">3</span>,<span class="dv">6</span>,<span class="dv">9</span>,<span class="dv">12</span>,<span class="cn">Inf</span>)</span>
<span id="cb624-5"><a href="chap-bondad.html#cb624-5" aria-hidden="true" tabindex="-1"></a>probs<span class="ot">=</span><span class="fu">pnorm</span>(right,mu,sigma)<span class="sc">-</span><span class="fu">pnorm</span>(left,mu, sigma)</span>
<span id="cb624-6"><a href="chap-bondad.html#cb624-6" aria-hidden="true" tabindex="-1"></a>ChiT3<span class="ot">=</span><span class="fu">chisq.test</span>(x,<span class="at">p=</span>probs)</span>
<span id="cb624-7"><a href="chap-bondad.html#cb624-7" aria-hidden="true" tabindex="-1"></a>p.valor3<span class="ot">=</span><span class="dv">1</span><span class="sc">-</span><span class="fu">pchisq</span>(ChiT3<span class="sc">$</span>statistic,<span class="dv">2</span>)</span>
<span id="cb624-8"><a href="chap-bondad.html#cb624-8" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(mu,sigma,<span class="fu">round</span>(p.valor3,<span class="dv">3</span>))</span></code></pre></div>
<pre><code>##      mean        sd X-squared 
##     8.200     3.180     0.692</code></pre>
<p><em>(4)</em> 0.313 NO</p>
<p>Nosotros lo hemos calculado con</p>
<div class="sourceCode" id="cb626"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb626-1"><a href="chap-bondad.html#cb626-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">2014</span>)</span>
<span id="cb626-2"><a href="chap-bondad.html#cb626-2" aria-hidden="true" tabindex="-1"></a>x<span class="ot">=</span><span class="fu">rchisq</span>(<span class="dv">25</span>,<span class="dv">10</span>)</span>
<span id="cb626-3"><a href="chap-bondad.html#cb626-3" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">ks.test</span>(x,<span class="st">&quot;pnorm&quot;</span>,<span class="at">mean=</span><span class="dv">10</span>,<span class="at">sd=</span><span class="fl">3.16</span>)<span class="sc">$</span>p.value,<span class="dv">3</span>)</span></code></pre></div>
<pre><code>## [1] 0.313</code></pre>
<p><em>(5)</em> 0.001 SI</p>
<p>Nosotros lo hemos calculado con</p>
<div class="sourceCode" id="cb628"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb628-1"><a href="chap-bondad.html#cb628-1" aria-hidden="true" tabindex="-1"></a>x<span class="ot">=</span><span class="fu">c</span>(<span class="fl">4.6</span>, <span class="fl">0.97</span>,  <span class="fl">0.3</span>,  <span class="fl">1.11</span>,  <span class="fl">2.16</span>, <span class="fl">15.52</span>,  <span class="fl">1.13</span>,  <span class="fl">0.17</span>,  <span class="fl">0.64</span>,  <span class="fl">2.00</span>)</span>
<span id="cb628-2"><a href="chap-bondad.html#cb628-2" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">lillie.test</span>(x)<span class="sc">$</span>p.value,<span class="dv">3</span>)</span></code></pre></div>
<pre><code>## [1] 0.001</code></pre>
<p><em>(6)</em> 0.117 NO</p>
<p>Nosotros lo hemos calculado con</p>
<div class="sourceCode" id="cb630"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb630-1"><a href="chap-bondad.html#cb630-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">2014</span>)</span>
<span id="cb630-2"><a href="chap-bondad.html#cb630-2" aria-hidden="true" tabindex="-1"></a>x<span class="ot">=</span><span class="fu">rnorm</span>(<span class="dv">15</span>,<span class="dv">2</span>,<span class="fl">0.8</span>)</span>
<span id="cb630-3"><a href="chap-bondad.html#cb630-3" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1007</span>)</span>
<span id="cb630-4"><a href="chap-bondad.html#cb630-4" aria-hidden="true" tabindex="-1"></a>y<span class="ot">=</span><span class="fu">rexp</span>(<span class="dv">25</span>,<span class="fl">0.5</span>)</span>
<span id="cb630-5"><a href="chap-bondad.html#cb630-5" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">ks.test</span>(x,y)<span class="sc">$</span>p.value,<span class="dv">3</span>)</span></code></pre></div>
<pre><code>## [1] 0.117</code></pre>
</div>
<div id="soluciones-sucintas-de-los-problemas" class="section level3 unnumbered">
<h3>Soluciones sucintas de los problemas</h3>
<p><strong>(1)</strong> Para realizar el test <span class="math inline">\(\chi^2\)</span> “exacto”:</p>
<div class="sourceCode" id="cb632"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb632-1"><a href="chap-bondad.html#cb632-1" aria-hidden="true" tabindex="-1"></a>INE<span class="ot">=</span><span class="fu">read.table</span>(<span class="st">&quot;https://raw.githubusercontent.com/AprendeR-UIB/AprendeR2privat/master/INE.txt&quot;</span>,</span>
<span id="cb632-2"><a href="chap-bondad.html#cb632-2" aria-hidden="true" tabindex="-1"></a>               <span class="at">header=</span><span class="cn">TRUE</span>)</span>
<span id="cb632-3"><a href="chap-bondad.html#cb632-3" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(INE)</span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:	19 obs. of  3 variables:
##  $ Comunidad  : chr  &quot;Andalucía&quot; &quot;Aragón&quot; &quot;Asturias (Principado de)&quot; &quot;Balears (Illes)&quot; ...
##  $ Población  : int  8440300 1347150 1068165 1111674 2118679 591888 2100998 2519875 7553650 5113815 ...
##  $ Defunciones: int  34810 7196 6623 4088 7593 3031 14532 9765 32383 21614 ...</code></pre>
<div class="sourceCode" id="cb634"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb634-1"><a href="chap-bondad.html#cb634-1" aria-hidden="true" tabindex="-1"></a>Freq.Obs.INE<span class="ot">=</span>INE<span class="sc">$</span>Defunciones  <span class="co">#Frecuencias observadas</span></span>
<span id="cb634-2"><a href="chap-bondad.html#cb634-2" aria-hidden="true" tabindex="-1"></a>Prob.Esp.INE<span class="ot">=</span>INE<span class="sc">$</span>Población<span class="sc">/</span><span class="fu">sum</span>(INE<span class="sc">$</span>Población)  <span class="co">#Probabilitades esperadas</span></span>
<span id="cb634-3"><a href="chap-bondad.html#cb634-3" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(Freq.Obs.INE, <span class="at">p=</span>Prob.Esp.INE)</span></code></pre></div>
<pre><code>## 
## 	Chi-squared test for given probabilities
## 
## data:  Freq.Obs.INE
## X-squared = 8008.6, df = 18, p-value &lt; 2.2e-16</code></pre>
<p>Como la muestra no es muy grande, es más conveniente efectuar un test <span class="math inline">\(\chi^2\)</span> de Montecarlo</p>
<div class="sourceCode" id="cb636"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb636-1"><a href="chap-bondad.html#cb636-1" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(Freq.Obs.INE, <span class="at">p=</span>Prob.Esp.INE, <span class="at">simulate.p.value=</span><span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## 
## 	Chi-squared test for given probabilities with simulated p-value
## 	(based on 2000 replicates)
## 
## data:  Freq.Obs.INE
## X-squared = 8008.6, df = NA, p-value = 0.0004998</code></pre>
<p>La conclusión es la misma.</p>
<p><strong>(2)</strong></p>
<div class="sourceCode" id="cb638"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb638-1"><a href="chap-bondad.html#cb638-1" aria-hidden="true" tabindex="-1"></a>Goles<span class="ot">=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">4</span>,<span class="dv">5</span>,<span class="dv">7</span>)</span>
<span id="cb638-2"><a href="chap-bondad.html#cb638-2" aria-hidden="true" tabindex="-1"></a>Partidos<span class="ot">=</span><span class="fu">c</span>(<span class="dv">7</span>,<span class="dv">17</span>,<span class="dv">13</span>,<span class="dv">14</span>,<span class="dv">8</span>,<span class="dv">3</span>,<span class="dv">1</span>)</span>
<span id="cb638-3"><a href="chap-bondad.html#cb638-3" aria-hidden="true" tabindex="-1"></a>N<span class="ot">=</span><span class="fu">sum</span>(Partidos)</span>
<span id="cb638-4"><a href="chap-bondad.html#cb638-4" aria-hidden="true" tabindex="-1"></a>lambda<span class="ot">=</span><span class="fu">sum</span>(Goles<span class="sc">*</span>Partidos)<span class="sc">/</span>N</span>
<span id="cb638-5"><a href="chap-bondad.html#cb638-5" aria-hidden="true" tabindex="-1"></a>probs<span class="ot">=</span><span class="fu">c</span>(<span class="fu">dpois</span>(<span class="dv">0</span><span class="sc">:</span><span class="dv">5</span>,lambda),<span class="dv">1</span><span class="sc">-</span><span class="fu">ppois</span>(<span class="dv">5</span>,lambda))  <span class="co">#Probabilidades teóricas</span></span>
<span id="cb638-6"><a href="chap-bondad.html#cb638-6" aria-hidden="true" tabindex="-1"></a>probs<span class="sc">*</span>N  <span class="co">#Frecuencias esperadas</span></span></code></pre></div>
<pre><code>## [1]  6.936418 15.304161 16.883161 12.416717  6.848903  3.022214  1.588426</code></pre>
<p>Habrá que agrupar las tres últimas clases:</p>
<div class="sourceCode" id="cb640"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb640-1"><a href="chap-bondad.html#cb640-1" aria-hidden="true" tabindex="-1"></a>probs<span class="ot">=</span><span class="fu">c</span>(<span class="fu">dpois</span>(<span class="dv">0</span><span class="sc">:</span><span class="dv">3</span>,lambda),<span class="dv">1</span><span class="sc">-</span><span class="fu">ppois</span>(<span class="dv">3</span>,lambda))</span>
<span id="cb640-2"><a href="chap-bondad.html#cb640-2" aria-hidden="true" tabindex="-1"></a>Partidos<span class="ot">=</span><span class="fu">c</span>(Partidos[<span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>],<span class="fu">sum</span>(Partidos[<span class="dv">5</span><span class="sc">:</span><span class="dv">7</span>]))</span>
<span id="cb640-3"><a href="chap-bondad.html#cb640-3" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(Partidos,<span class="at">p=</span>probs)</span></code></pre></div>
<pre><code>## 
## 	Chi-squared test for given probabilities
## 
## data:  Partidos
## X-squared = 1.309, df = 4, p-value = 0.8598</code></pre>
<p><strong>(3)</strong></p>
<div class="sourceCode" id="cb642"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb642-1"><a href="chap-bondad.html#cb642-1" aria-hidden="true" tabindex="-1"></a>Datos<span class="ot">=</span><span class="fu">read.table</span>(<span class="st">&quot;https://www.dropbox.com/s/qcok2f7u51teqr6/pacientes.txt?raw=1&quot;</span>,</span>
<span id="cb642-2"><a href="chap-bondad.html#cb642-2" aria-hidden="true" tabindex="-1"></a>                <span class="at">header=</span><span class="cn">TRUE</span>)</span>
<span id="cb642-3"><a href="chap-bondad.html#cb642-3" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(Datos)</span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:	81 obs. of  7 variables:
##  $ SEXO    : Factor w/ 2 levels &quot;Hombre&quot;,&quot;Mujer&quot;: 1 1 2 1 1 2 1 1 1 1 ...
##  $ EDAD    : int  47 51 54 50 52 53 49 52 50 48 ...
##  $ ALTURA  : int  170 170 148 170 165 151 170 168 170 166 ...
##  $ PESO    : int  80 73 46 74 67 51 73 72 73 73 ...
##  $ HIPERT  : Factor w/ 2 levels &quot;Hipertenso&quot;,&quot;Normotenso&quot;: 2 1 1 1 2 1 1 2 2 2 ...
##  $ IMC     : num  27.7 25.3 21 25.6 24.6 ...
##  $ CARDIOPA: Factor w/ 2 levels &quot;Con cardiopatia&quot;,..: 2 1 2 2 2 2 2 2 1 1 ...</code></pre>
<div class="sourceCode" id="cb644"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb644-1"><a href="chap-bondad.html#cb644-1" aria-hidden="true" tabindex="-1"></a>X<span class="ot">=</span>Datos<span class="sc">$</span>PESO[Datos<span class="sc">$</span>SEXO<span class="sc">==</span><span class="st">&quot;Hombre&quot;</span>]</span></code></pre></div>
<p><em>(a)</em></p>
<div class="sourceCode" id="cb645"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb645-1"><a href="chap-bondad.html#cb645-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(nortest)</span>
<span id="cb645-2"><a href="chap-bondad.html#cb645-2" aria-hidden="true" tabindex="-1"></a><span class="fu">lillie.test</span>(X)</span></code></pre></div>
<pre><code>## 
## 	Lilliefors (Kolmogorov-Smirnov) normality test
## 
## data:  X
## D = 0.15413, p-value = 0.009027</code></pre>
<p><em>(b)</em> Veamos cuántos datos tenemos</p>
<div class="sourceCode" id="cb647"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb647-1"><a href="chap-bondad.html#cb647-1" aria-hidden="true" tabindex="-1"></a>n<span class="ot">=</span><span class="fu">length</span>(X)</span>
<span id="cb647-2"><a href="chap-bondad.html#cb647-2" aria-hidden="true" tabindex="-1"></a>n</span></code></pre></div>
<pre><code>## [1] 45</code></pre>
<p>Como queremos que todas las clases tengan frecuencias esperadas al menos 5, no podemos usar muchas. Vamos a empezar con 7.</p>
<div class="sourceCode" id="cb649"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb649-1"><a href="chap-bondad.html#cb649-1" aria-hidden="true" tabindex="-1"></a>paso<span class="ot">=</span><span class="fu">round</span>((<span class="fu">max</span>(X)<span class="sc">-</span><span class="fu">min</span>(X))<span class="sc">/</span><span class="dv">7</span>,<span class="dv">1</span>)</span>
<span id="cb649-2"><a href="chap-bondad.html#cb649-2" aria-hidden="true" tabindex="-1"></a>Límites<span class="ot">=</span><span class="fu">min</span>(X)<span class="sc">+</span>paso<span class="sc">*</span>(<span class="dv">0</span><span class="sc">:</span><span class="dv">7</span>)</span>
<span id="cb649-3"><a href="chap-bondad.html#cb649-3" aria-hidden="true" tabindex="-1"></a>Límites[<span class="dv">1</span>]<span class="ot">=</span><span class="sc">-</span><span class="cn">Inf</span></span>
<span id="cb649-4"><a href="chap-bondad.html#cb649-4" aria-hidden="true" tabindex="-1"></a>Límites[<span class="dv">8</span>]<span class="ot">=</span><span class="cn">Inf</span></span>
<span id="cb649-5"><a href="chap-bondad.html#cb649-5" aria-hidden="true" tabindex="-1"></a>Límites</span></code></pre></div>
<pre><code>## [1] -Inf 69.1 71.2 73.3 75.4 77.5 79.6  Inf</code></pre>
<div class="sourceCode" id="cb651"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb651-1"><a href="chap-bondad.html#cb651-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(<span class="fu">cut</span>(X,<span class="at">breaks=</span>Límites))</span></code></pre></div>
<table style="width:100%;">
<colgroup>
<col width="14%" />
<col width="14%" />
<col width="14%" />
<col width="14%" />
<col width="14%" />
<col width="14%" />
<col width="14%" />
</colgroup>
<thead>
<tr class="header">
<th align="right">(-Inf,69.1]</th>
<th align="right">(69.1,71.2]</th>
<th align="right">(71.2,73.3]</th>
<th align="right">(73.3,75.4]</th>
<th align="right">(75.4,77.5]</th>
<th align="right">(77.5,79.6]</th>
<th align="right">(79.6, Inf]</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">2</td>
<td align="right">2</td>
<td align="right">18</td>
<td align="right">9</td>
<td align="right">8</td>
<td align="right">2</td>
<td align="right">4</td>
</tr>
</tbody>
</table>
<div class="sourceCode" id="cb652"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb652-1"><a href="chap-bondad.html#cb652-1" aria-hidden="true" tabindex="-1"></a>mu<span class="ot">=</span><span class="fu">mean</span>(X)</span>
<span id="cb652-2"><a href="chap-bondad.html#cb652-2" aria-hidden="true" tabindex="-1"></a>dt<span class="ot">=</span><span class="fu">sd</span>(X)</span>
<span id="cb652-3"><a href="chap-bondad.html#cb652-3" aria-hidden="true" tabindex="-1"></a>Límites.Izq<span class="ot">=</span>Límites[<span class="sc">-</span><span class="dv">8</span>]</span>
<span id="cb652-4"><a href="chap-bondad.html#cb652-4" aria-hidden="true" tabindex="-1"></a>Límites.Der<span class="ot">=</span>Límites[<span class="sc">-</span><span class="dv">1</span>]</span>
<span id="cb652-5"><a href="chap-bondad.html#cb652-5" aria-hidden="true" tabindex="-1"></a>probs<span class="ot">=</span><span class="fu">pnorm</span>(Límites.Der,mu,dt)<span class="sc">-</span><span class="fu">pnorm</span>(Límites.Izq,mu,dt)</span>
<span id="cb652-6"><a href="chap-bondad.html#cb652-6" aria-hidden="true" tabindex="-1"></a>Frecs.Esp<span class="ot">=</span><span class="fu">round</span>(probs<span class="sc">*</span>n,<span class="dv">2</span>)</span>
<span id="cb652-7"><a href="chap-bondad.html#cb652-7" aria-hidden="true" tabindex="-1"></a>Frecs.Esp</span></code></pre></div>
<pre><code>## [1]  1.93  4.96  9.83 12.23  9.57  4.70  1.77</code></pre>
<p>Habrá que agrupar las dos primeras clases y las dos últimas</p>
<div class="sourceCode" id="cb654"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb654-1"><a href="chap-bondad.html#cb654-1" aria-hidden="true" tabindex="-1"></a>Límites<span class="ot">=</span>Límites[<span class="sc">-</span><span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">7</span>)]</span>
<span id="cb654-2"><a href="chap-bondad.html#cb654-2" aria-hidden="true" tabindex="-1"></a>Límites</span></code></pre></div>
<pre><code>## [1] -Inf 71.2 73.3 75.4 77.5  Inf</code></pre>
<div class="sourceCode" id="cb656"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb656-1"><a href="chap-bondad.html#cb656-1" aria-hidden="true" tabindex="-1"></a>Frecs.Obs<span class="ot">=</span><span class="fu">table</span>(<span class="fu">cut</span>(X,<span class="at">breaks=</span>Límites))</span>
<span id="cb656-2"><a href="chap-bondad.html#cb656-2" aria-hidden="true" tabindex="-1"></a>Límites.Izq<span class="ot">=</span>Límites[<span class="sc">-</span><span class="dv">6</span>]</span>
<span id="cb656-3"><a href="chap-bondad.html#cb656-3" aria-hidden="true" tabindex="-1"></a>Límites.Der<span class="ot">=</span>Límites[<span class="sc">-</span><span class="dv">1</span>]</span>
<span id="cb656-4"><a href="chap-bondad.html#cb656-4" aria-hidden="true" tabindex="-1"></a>probs<span class="ot">=</span><span class="fu">pnorm</span>(Límites.Der,mu,dt)<span class="sc">-</span><span class="fu">pnorm</span>(Límites.Izq,mu,dt)</span>
<span id="cb656-5"><a href="chap-bondad.html#cb656-5" aria-hidden="true" tabindex="-1"></a>Frecs.Esp<span class="ot">=</span><span class="fu">round</span>(probs<span class="sc">*</span>n,<span class="dv">2</span>)</span>
<span id="cb656-6"><a href="chap-bondad.html#cb656-6" aria-hidden="true" tabindex="-1"></a>Frecs.Esp</span></code></pre></div>
<pre><code>## [1]  6.89  9.83 12.23  9.57  6.47</code></pre>
<div class="sourceCode" id="cb658"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb658-1"><a href="chap-bondad.html#cb658-1" aria-hidden="true" tabindex="-1"></a>test<span class="ot">=</span><span class="fu">chisq.test</span>(Frecs.Obs,<span class="at">p=</span>probs)</span>
<span id="cb658-2"><a href="chap-bondad.html#cb658-2" aria-hidden="true" tabindex="-1"></a>test</span></code></pre></div>
<pre><code>## 
## 	Chi-squared test for given probabilities
## 
## data:  Frecs.Obs
## X-squared = 9.1484, df = 4, p-value = 0.05749</code></pre>
<div class="sourceCode" id="cb660"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb660-1"><a href="chap-bondad.html#cb660-1" aria-hidden="true" tabindex="-1"></a>p.valor<span class="ot">=</span><span class="dv">1</span><span class="sc">-</span><span class="fu">pchisq</span>(test<span class="sc">$</span>statistic,test<span class="sc">$</span>parameter<span class="dv">-2</span>)</span>
<span id="cb660-2"><a href="chap-bondad.html#cb660-2" aria-hidden="true" tabindex="-1"></a>p.valor</span></code></pre></div>
<pre><code>##  X-squared 
## 0.01031437</code></pre>
<p>La conclusión usando el test S-W y el test <span class="math inline">\(\chi^2\)</span> es la misma.</p>

</div>
</div>
</div>
<div class="footnotes">
<hr />
<ol start="4">
<li id="fn4"><p>A las repeticiones se las suele llamar empates, <em>ties</em> en inglés, porque la función de distribución acumulada muestral ordena los datos y las repeticiones producen empates en las posiciones de valores sucesivos.<a href="chap-bondad.html#fnref4" class="footnote-back">↩︎</a></p></li>
<li id="fn5"><p>Lo confesamos, hemos elegido la semilla de aleatoriedad no porque seamos fans de <a href="https://es.wikipedia.org/wiki/Daniel_Bernoulli">Daniel Bernoulli</a> sino para que la muestra obtenida solo contenga ceros, unos y doses, lo que, como veréis, motivará una pequeña discusión sobre qué clases tomar.<a href="chap-bondad.html#fnref5" class="footnote-back">↩︎</a></p></li>
<li id="fn6"><p>Véase N. M. Razali, Y. B. Wah,
“Power comparisons of Shapiro-Wilk, Kolmogorov-Smirnov, Lilliefors and Anderson-Darling tests.” <em>S. Stat. Model. Anal.</em> 2 (2011), pp. 21–33.<a href="chap-bondad.html#fnref6" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="chap-contrastes.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="chap-indep.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "subsection",
"download": ["pdf", "epub"]
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
