<!DOCTYPE html>
<html >

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Lección 5 Contrastes de hipótesis | AprendeR: Parte II</title>
  <meta name="description" content="Apuntes AprendeR bookdown::gitbook.">
  <meta name="generator" content="bookdown  and GitBook 2.6.7">

  <meta property="og:title" content="Lección 5 Contrastes de hipótesis | AprendeR: Parte II" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Apuntes AprendeR bookdown::gitbook." />
  <meta name="github-repo" content="cescrossello/AprendeR-II" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Lección 5 Contrastes de hipótesis | AprendeR: Parte II" />
  
  <meta name="twitter:description" content="Apuntes AprendeR bookdown::gitbook." />
  

<meta name="author" content="The AprendeR team">


<meta name="date" content="2019-03-25">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  
  
<link rel="prev" href="chap-IC.html">
<link rel="next" href="chap-bondad.html">
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />









<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #007020; font-weight: bold; } /* Keyword */
code > span.dt { color: #902000; } /* DataType */
code > span.dv { color: #40a070; } /* DecVal */
code > span.bn { color: #40a070; } /* BaseN */
code > span.fl { color: #40a070; } /* Float */
code > span.ch { color: #4070a0; } /* Char */
code > span.st { color: #4070a0; } /* String */
code > span.co { color: #60a0b0; font-style: italic; } /* Comment */
code > span.ot { color: #007020; } /* Other */
code > span.al { color: #ff0000; font-weight: bold; } /* Alert */
code > span.fu { color: #06287e; } /* Function */
code > span.er { color: #ff0000; font-weight: bold; } /* Error */
code > span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #880000; } /* Constant */
code > span.sc { color: #4070a0; } /* SpecialChar */
code > span.vs { color: #4070a0; } /* VerbatimString */
code > span.ss { color: #bb6688; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #19177c; } /* Variable */
code > span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code > span.op { color: #666666; } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { color: #bc7a00; } /* Preprocessor */
code > span.at { color: #7d9029; } /* Attribute */
code > span.do { color: #ba2121; font-style: italic; } /* Documentation */
code > span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">AprendeR: Parte II</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Presentación</a></li>
<li class="part"><span><b>Parte II: Estadística inferencial</b></span></li>
<li class="chapter" data-level="1" data-path="chap-distr.html"><a href="chap-distr.html"><i class="fa fa-check"></i><b>1</b> Distribuciones de probabilidad</a><ul>
<li class="chapter" data-level="1.1" data-path="chap-distr.html"><a href="chap-distr.html#ejercicios"><i class="fa fa-check"></i><b>1.1</b> Ejercicios</a><ul>
<li class="chapter" data-level="" data-path="chap-distr.html"><a href="chap-distr.html#test"><i class="fa fa-check"></i>Test</a></li>
<li class="chapter" data-level="" data-path="chap-distr.html"><a href="chap-distr.html#respuestas-al-test"><i class="fa fa-check"></i>Respuestas al test</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="chap-muestreo.html"><a href="chap-muestreo.html"><i class="fa fa-check"></i><b>2</b> Conceptos básicos de muestreo</a><ul>
<li class="chapter" data-level="2.1" data-path="chap-muestreo.html"><a href="chap-muestreo.html#sec:muestreo"><i class="fa fa-check"></i><b>2.1</b> Tipos de muestreo</a></li>
<li class="chapter" data-level="2.2" data-path="chap-muestreo.html"><a href="chap-muestreo.html#muestreo-aleatorio-con-r"><i class="fa fa-check"></i><b>2.2</b> Muestreo aleatorio con R</a></li>
<li class="chapter" data-level="2.3" data-path="chap-muestreo.html"><a href="chap-muestreo.html#guia-rapida"><i class="fa fa-check"></i><b>2.3</b> Guía rápida</a></li>
<li class="chapter" data-level="2.4" data-path="chap-muestreo.html"><a href="chap-muestreo.html#ejercicios-1"><i class="fa fa-check"></i><b>2.4</b> Ejercicios</a><ul>
<li class="chapter" data-level="" data-path="chap-muestreo.html"><a href="chap-muestreo.html#test-1"><i class="fa fa-check"></i>Test</a></li>
<li class="chapter" data-level="" data-path="chap-muestreo.html"><a href="chap-muestreo.html#respuestas-al-test-1"><i class="fa fa-check"></i>Respuestas al test</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="chap-estimacion.html"><a href="chap-estimacion.html"><i class="fa fa-check"></i><b>3</b> Estimación puntual</a><ul>
<li class="chapter" data-level="3.1" data-path="chap-estimacion.html"><a href="chap-estimacion.html#estimacion-maximo-verosimil"><i class="fa fa-check"></i><b>3.1</b> Estimación máximo verosímil</a></li>
<li class="chapter" data-level="3.2" data-path="chap-estimacion.html"><a href="chap-estimacion.html#guia-rapida-1"><i class="fa fa-check"></i><b>3.2</b> Guía rápida</a></li>
<li class="chapter" data-level="3.3" data-path="chap-estimacion.html"><a href="chap-estimacion.html#ejercicios-2"><i class="fa fa-check"></i><b>3.3</b> Ejercicios</a><ul>
<li class="chapter" data-level="" data-path="chap-estimacion.html"><a href="chap-estimacion.html#test-2"><i class="fa fa-check"></i>Test</a></li>
<li class="chapter" data-level="" data-path="chap-estimacion.html"><a href="chap-estimacion.html#respuestas-al-test-2"><i class="fa fa-check"></i>Respuestas al test</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="chap-IC.html"><a href="chap-IC.html"><i class="fa fa-check"></i><b>4</b> Intervalos de confianza</a><ul>
<li class="chapter" data-level="4.1" data-path="chap-IC.html"><a href="chap-IC.html#sec:ICT"><i class="fa fa-check"></i><b>4.1</b> Intervalo de confianza para la media basado en la t de Student</a></li>
<li class="chapter" data-level="4.2" data-path="chap-IC.html"><a href="chap-IC.html#intervalos-de-confianza-para-la-proporcion-poblacional"><i class="fa fa-check"></i><b>4.2</b> Intervalos de confianza para la proporción poblacional</a></li>
<li class="chapter" data-level="4.3" data-path="chap-IC.html"><a href="chap-IC.html#sec:ICvar"><i class="fa fa-check"></i><b>4.3</b> Intervalo de confianza para la varianza de una población normal</a></li>
<li class="chapter" data-level="4.4" data-path="chap-IC.html"><a href="chap-IC.html#bootstrap"><i class="fa fa-check"></i><b>4.4</b> Bootstrap</a></li>
<li class="chapter" data-level="4.5" data-path="chap-IC.html"><a href="chap-IC.html#guia-rapida-2"><i class="fa fa-check"></i><b>4.5</b> Guía rápida</a></li>
<li class="chapter" data-level="4.6" data-path="chap-IC.html"><a href="chap-IC.html#ejercicios-3"><i class="fa fa-check"></i><b>4.6</b> Ejercicios</a><ul>
<li class="chapter" data-level="" data-path="chap-IC.html"><a href="chap-IC.html#modelo-de-test"><i class="fa fa-check"></i>Modelo de test</a></li>
<li class="chapter" data-level="" data-path="chap-IC.html"><a href="chap-IC.html#respuestas-al-test-3"><i class="fa fa-check"></i>Respuestas al test</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="chap-contrastes.html"><a href="chap-contrastes.html"><i class="fa fa-check"></i><b>5</b> Contrastes de hipótesis</a><ul>
<li class="chapter" data-level="5.1" data-path="chap-contrastes.html"><a href="chap-contrastes.html#contrastes-para-medias"><i class="fa fa-check"></i><b>5.1</b> Contrastes para medias</a><ul>
<li class="chapter" data-level="" data-path="chap-contrastes.html"><a href="chap-contrastes.html#el-test-t"><i class="fa fa-check"></i>El test t</a></li>
<li class="chapter" data-level="" data-path="chap-contrastes.html"><a href="chap-contrastes.html#tests-no-parametricos"><i class="fa fa-check"></i>Tests no paramétricos</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="chap-contrastes.html"><a href="chap-contrastes.html#contrastes-para-varianzas"><i class="fa fa-check"></i><b>5.2</b> Contrastes para varianzas</a></li>
<li class="chapter" data-level="5.3" data-path="chap-contrastes.html"><a href="chap-contrastes.html#contrastes-para-proporciones"><i class="fa fa-check"></i><b>5.3</b> Contrastes para proporciones</a></li>
<li class="chapter" data-level="5.4" data-path="chap-contrastes.html"><a href="chap-contrastes.html#calculo-de-la-potencia-de-un-contraste"><i class="fa fa-check"></i><b>5.4</b> Cálculo de la potencia de un contraste</a></li>
<li class="chapter" data-level="5.5" data-path="chap-contrastes.html"><a href="chap-contrastes.html#guia-rapida-3"><i class="fa fa-check"></i><b>5.5</b> Guía rápida</a></li>
<li class="chapter" data-level="5.6" data-path="chap-contrastes.html"><a href="chap-contrastes.html#ejercicios-4"><i class="fa fa-check"></i><b>5.6</b> Ejercicios</a><ul>
<li class="chapter" data-level="" data-path="chap-contrastes.html"><a href="chap-contrastes.html#modelo-de-test-1"><i class="fa fa-check"></i>Modelo de test</a></li>
<li class="chapter" data-level="" data-path="chap-contrastes.html"><a href="chap-contrastes.html#respuestas-al-test-4"><i class="fa fa-check"></i>Respuestas al test</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="chap-bondad.html"><a href="chap-bondad.html"><i class="fa fa-check"></i><b>6</b> Contrastes de bondad de ajuste</a><ul>
<li class="chapter" data-level="6.1" data-path="chap-bondad.html"><a href="chap-bondad.html#pruebas-graficas-q-q-plots"><i class="fa fa-check"></i><b>6.1</b> Pruebas gráficas: Q-Q-plots</a></li>
<li class="chapter" data-level="6.2" data-path="chap-bondad.html"><a href="chap-bondad.html#el-test-chi2-de-pearson"><i class="fa fa-check"></i><b>6.2</b> El test <span class="math inline">\(\chi^2\)</span> de Pearson</a></li>
<li class="chapter" data-level="6.3" data-path="chap-bondad.html"><a href="chap-bondad.html#el-test-chi2-para-distribuciones-continuas"><i class="fa fa-check"></i><b>6.3</b> El test <span class="math inline">\(\chi^2\)</span> para distribuciones continuas</a></li>
<li class="chapter" data-level="6.4" data-path="chap-bondad.html"><a href="chap-bondad.html#el-test-de-kolgomorov-smirnov"><i class="fa fa-check"></i><b>6.4</b> El test de Kolgomorov-Smirnov</a></li>
<li class="chapter" data-level="6.5" data-path="chap-bondad.html"><a href="chap-bondad.html#tests-de-normalidad"><i class="fa fa-check"></i><b>6.5</b> Tests de normalidad</a></li>
<li class="chapter" data-level="6.6" data-path="chap-bondad.html"><a href="chap-bondad.html#guia-rapida-4"><i class="fa fa-check"></i><b>6.6</b> Guía rápida</a></li>
<li class="chapter" data-level="6.7" data-path="chap-bondad.html"><a href="chap-bondad.html#ejercicios-5"><i class="fa fa-check"></i><b>6.7</b> Ejercicios</a><ul>
<li class="chapter" data-level="" data-path="chap-bondad.html"><a href="chap-bondad.html#modelo-de-test-2"><i class="fa fa-check"></i>Modelo de test</a></li>
<li class="chapter" data-level="" data-path="chap-bondad.html"><a href="chap-bondad.html#respuestas-al-test-5"><i class="fa fa-check"></i>Respuestas al test</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="chap-indep.html"><a href="chap-indep.html"><i class="fa fa-check"></i><b>7</b> Contrastes de independencia y homogeneidad</a><ul>
<li class="chapter" data-level="7.1" data-path="chap-indep.html"><a href="chap-indep.html#tablas-de-contingencia"><i class="fa fa-check"></i><b>7.1</b> Tablas de contingencia</a></li>
<li class="chapter" data-level="7.2" data-path="chap-indep.html"><a href="chap-indep.html#contraste-de-independencia"><i class="fa fa-check"></i><b>7.2</b> Contraste de independencia</a></li>
<li class="chapter" data-level="7.3" data-path="chap-indep.html"><a href="chap-indep.html#sec:hom"><i class="fa fa-check"></i><b>7.3</b> Contraste de homogeneidad</a></li>
<li class="chapter" data-level="7.4" data-path="chap-indep.html"><a href="chap-indep.html#potencia-de-un-contraste-chi2"><i class="fa fa-check"></i><b>7.4</b> Potencia de un contraste <span class="math inline">\(\chi^2\)</span></a></li>
<li class="chapter" data-level="7.5" data-path="chap-indep.html"><a href="chap-indep.html#guia-rapida-5"><i class="fa fa-check"></i><b>7.5</b> Guía rápida</a></li>
<li class="chapter" data-level="7.6" data-path="chap-indep.html"><a href="chap-indep.html#ejercicios-6"><i class="fa fa-check"></i><b>7.6</b> Ejercicios</a><ul>
<li class="chapter" data-level="" data-path="chap-indep.html"><a href="chap-indep.html#modelo-de-test-3"><i class="fa fa-check"></i>Modelo de test</a></li>
<li class="chapter" data-level="" data-path="chap-indep.html"><a href="chap-indep.html#respuestas-al-test-6"><i class="fa fa-check"></i>Respuestas al test</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="introduccion-a-la-estadistica-descriptiva-multidimensional.html"><a href="introduccion-a-la-estadistica-descriptiva-multidimensional.html"><i class="fa fa-check"></i><b>8</b> Introducción a la estadística descriptiva multidimensional</a><ul>
<li class="chapter" data-level="8.1" data-path="introduccion-a-la-estadistica-descriptiva-multidimensional.html"><a href="introduccion-a-la-estadistica-descriptiva-multidimensional.html#matrices-de-datos-cuantitativos"><i class="fa fa-check"></i><b>8.1</b> Matrices de datos cuantitativos</a></li>
<li class="chapter" data-level="8.2" data-path="introduccion-a-la-estadistica-descriptiva-multidimensional.html"><a href="introduccion-a-la-estadistica-descriptiva-multidimensional.html#transformaciones-lineales"><i class="fa fa-check"></i><b>8.2</b> Transformaciones lineales</a></li>
<li class="chapter" data-level="8.3" data-path="introduccion-a-la-estadistica-descriptiva-multidimensional.html"><a href="introduccion-a-la-estadistica-descriptiva-multidimensional.html#covarianzas-y-correlaciones"><i class="fa fa-check"></i><b>8.3</b> Covarianzas y correlaciones</a></li>
<li class="chapter" data-level="8.4" data-path="introduccion-a-la-estadistica-descriptiva-multidimensional.html"><a href="introduccion-a-la-estadistica-descriptiva-multidimensional.html#correlacion-de-spearman"><i class="fa fa-check"></i><b>8.4</b> Correlación de Spearman</a></li>
<li class="chapter" data-level="8.5" data-path="introduccion-a-la-estadistica-descriptiva-multidimensional.html"><a href="introduccion-a-la-estadistica-descriptiva-multidimensional.html#contrastes-de-correlacion"><i class="fa fa-check"></i><b>8.5</b> Contrastes de correlación</a></li>
<li class="chapter" data-level="8.6" data-path="introduccion-a-la-estadistica-descriptiva-multidimensional.html"><a href="introduccion-a-la-estadistica-descriptiva-multidimensional.html#un-ejemplo"><i class="fa fa-check"></i><b>8.6</b> Un ejemplo</a></li>
<li class="chapter" data-level="8.7" data-path="introduccion-a-la-estadistica-descriptiva-multidimensional.html"><a href="introduccion-a-la-estadistica-descriptiva-multidimensional.html#representacion-grafica-de-datos-multidimensionales"><i class="fa fa-check"></i><b>8.7</b> Representación gráfica de datos multidimensionales</a></li>
<li class="chapter" data-level="8.8" data-path="introduccion-a-la-estadistica-descriptiva-multidimensional.html"><a href="introduccion-a-la-estadistica-descriptiva-multidimensional.html#guia-rapida-6"><i class="fa fa-check"></i><b>8.8</b> Guía rápida</a></li>
<li class="chapter" data-level="8.9" data-path="introduccion-a-la-estadistica-descriptiva-multidimensional.html"><a href="introduccion-a-la-estadistica-descriptiva-multidimensional.html#ejercicios-7"><i class="fa fa-check"></i><b>8.9</b> Ejercicios</a><ul>
<li class="chapter" data-level="" data-path="introduccion-a-la-estadistica-descriptiva-multidimensional.html"><a href="introduccion-a-la-estadistica-descriptiva-multidimensional.html#modelo-de-test-4"><i class="fa fa-check"></i>Modelo de test</a></li>
<li class="chapter" data-level="" data-path="introduccion-a-la-estadistica-descriptiva-multidimensional.html"><a href="introduccion-a-la-estadistica-descriptiva-multidimensional.html#ejercicio"><i class="fa fa-check"></i>Ejercicio</a></li>
<li class="chapter" data-level="" data-path="introduccion-a-la-estadistica-descriptiva-multidimensional.html"><a href="introduccion-a-la-estadistica-descriptiva-multidimensional.html#respuestas-al-test-7"><i class="fa fa-check"></i>Respuestas al test</a></li>
</ul></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/cescrossello/AprendeR-II" target="blank">Publicado con  bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">AprendeR: Parte II</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="chap:contrastes" class="section level1">
<h1><span class="header-section-number">Lección 5</span> Contrastes de hipótesis</h1>
<p>En esta lección explicamos algunas instrucciones de R que permiten llevar a cabo contrastes de hipótesis sobre parámetros poblacionales. Antes de empezar, repasemos el vocabulario básico relacionado con los contrastes de hipótesis:</p>
<ul>
<li><p><strong>Hipótesis alternativa</strong>, <span class="math inline">\(H_1\)</span>: Aquella de la que buscamos evidencia en nuestro estudio.</p></li>
<li><p><strong>Hipótesis nula</strong>, <span class="math inline">\(H_0\)</span>: La hipótesis que estamos dispuestos a aceptar si no encontramos evidencia suficiente de la hipótesis alternativa. Suele plantearse en términos de “no hay diferencia”.</p></li>
<li><p><strong>Contraste bilateral</strong>: Contraste en el que la hipótesis alternativa viene definida por un <span class="math inline">\(\neq\)</span>: que un parámetro sea <em>diferente</em> de un valor dado, que un parámetro sobre una población sea <em>diferente</em> del mismo parámetro sobre otra población, …</p></li>
<li><p><strong>Contraste unilateral</strong>: Contraste en el que la hipótesis alternativa viene definida por un <span class="math inline">\(&gt;\)</span> o un <span class="math inline">\(&lt;\)</span>: que un parámetro sea <em>mayor</em> que un valor dado, que un parámetro sobre una población sea <em>menor</em> que el mismo parámetro sobre otra población, …</p></li>
<li><p><strong>Error de tipo I</strong>, o <strong>Falso positivo</strong>: Concluir que la hipótesis alternativa es verdadera cuando en realidad es falsa.</p></li>
<li><p><strong>Nivel de significación</strong>, <span class="math inline">\(\alpha\)</span>: La probabilidad de cometer un error de tipo I.</p></li>
<li><p><strong>Nivel de confianza</strong>, <span class="math inline">\(1-\alpha\)</span>: La probabilidad de <em>no</em> cometer un error de tipo I.</p></li>
<li><p><strong>Error de tipo II</strong>, o <strong>Falso negativo</strong>: Concluir que la hipótesis alternativa es falsa cuando en realidad es verdadera.</p></li>
<li><p><strong>Potencia</strong>, <span class="math inline">\(1-\beta\)</span>: La probabilidad de <em>no</em> cometer un error de tipo II.</p></li>
<li><p><strong>Estadístico de contraste</strong>: El valor que se calcula a partir de la muestra obtenida en el estudio y que se usará para tomar la decisión en el contraste planteado.</p></li>
<li><p><strong>p-valor</strong>: La probabilidad de que, si la hipótesis nula es verdadera, el estadístico de contraste tome un valor tan o más extremo <em>en el sentido de la hipótesis alternativa</em> que el obtenido en el estudio</p></li>
<li><p><strong>Intervalo de confianza</strong> al nivel de confianza <span class="math inline">\(1-\alpha\)</span>: Un intervalo en el que el parámetro poblacional que contrastamos tiene probabilidad <span class="math inline">\(1-\alpha\)</span> de pertenecer en el sentido de los intervalos de confianza de la Lección <a href="chap-IC.html#chap:IC">4</a>: es decir, porque se ha obtenido con un procedimiento que produce intervalos que, en el <span class="math inline">\((1-\alpha)\times 100\%\)</span> de las ocasiones que lo aplicamos a muestras aleatorias simples, contiene el parámetro poblacional. Está formado por los valores del parámetro poblacional que, si fueran los que contrastáramos en nuestro contraste, producirían un p-valor como mínimo <span class="math inline">\(\alpha\)</span>. Los intervalos de confianza de los contrastes bilaterales coinciden con los definidos en la Lección <a href="chap-IC.html#chap:IC">4</a>.</p></li>
<li><p><strong>Regla de rechazo</strong>: Rechazamos la hipótesis nula en favor de la alternativa con un nivel de significación <span class="math inline">\(\alpha\)</span> dado cuando se da alguna de las dos condiciones siguientes (que son equivalentes, es decir, se dan las dos o ninguna):</p>
<ul>
<li>El p-valor és menor que el nivel de significación.</li>
<li>El valor contrastado del parámetro poblacional no pertenece al intervalo de confianza del nivel <span class="math inline">\(1-\alpha\)</span>.</li>
</ul></li>
</ul>

<div class="example">
<p><span id="exm:monedabase" class="example"><strong>Ejemplo 5.1  </strong></span>Tenemos una moneda y creemos que está trucada a favor de Cara, es decir, que al lanzarla al aire produce más caras que cruces. Para intentar decidir si esto es cierto o no, lanzamos la moneda al aire 20 veces y obtenemos 15 caras.</p>
</div>

<p>Llamemos <span class="math inline">\(p\)</span> a la probabilidad de obtener cara al lanzar al aire esta moneda. Entonces:</p>
<ul>
<li><p>La hipótesis alternativa, de la que buscamos evidencia, es que la moneda está trucada a favor de cara: <span class="math inline">\(H_1: p&gt;0.5\)</span>.</p></li>
<li><p>La hipótesis nula, que aceptaremos por defecto si no encontramos evidencia de que la alternativa sea verdadera, es que la moneda no está trucada: <span class="math inline">\(H_0: p=0.5\)</span>.</p></li>
<li><p>Cometeríamos un error de tipo I si la moneda fuera honrada y nosotros concluyéramos que está trucada.</p></li>
<li><p>Cometeríamos un error de tipo II si la moneda estuviera trucada y nosotros concluyéramos que no lo está.</p></li>
<li><p>El estadístico de contraste en este experimento es simplemente el número de caras en un serie de lanzamientos de la moneda.</p></li>
<li><p>El p-valor es la probabilidad de obtener 15 o más caras al lanzar al aire 20 veces la moneda si fuera verdad que <span class="math inline">\(p=0.5\)</span>. Como en este caso el número de caras seguiría una distribución binomial <span class="math inline">\(B(20,0.5)\)</span>, podemos calcular fácilmente esta probabilidad:</p></li>
</ul>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="dv">1</span><span class="op">-</span><span class="kw">pbinom</span>(<span class="dv">14</span>,<span class="dv">20</span>,<span class="fl">0.5</span>)</code></pre></div>
<pre><code>## [1] 0.0206947</code></pre>
<div style="white-space: pre-line;">       Por lo tanto, el p-valor es 0.021.</div>
<ul>
<li>El intervalo de confianza del 95% de este contraste está formado por los valores de <span class="math inline">\(p\)</span> para los que la probabilidad de obtener 15 o más caras al lanzar al aire 20 veces la moneda es mayor o igual que el 5%, y es [0.5444, 1].</li>
</ul>
<p>Y bueno, tras todo este vocabulario, ¿cuál sería la conclusión? El p-valor obtenido significa que si la moneda no estuviera trucada, la probabilidad de obtener el número de caras que hemos obtenido o más es muy pequeña, lo que hace difícil de creer que la moneda no esté trucada. En particular, si trabajamos con un nivel de significación del 5%, como el p-valor es más pequeño que 0.05, rechazamos la hipótesis nula. Equivalentemente, como el intervalo de confianza del 95% para la <span class="math inline">\(p\)</span> está completamente a la derecha del valor que contrastamos, 0.5, con este nivel de confianza hemos de concluir que <span class="math inline">\(p&gt;0.5\)</span>.</p>
<p>En resumen, aceptando una probabilidad de error de tipo I (de concluir que una moneda honrada está trucada) del 5%, rechazamos la hipótesis nula e inferimos que la moneda está trucada a favor de cara.</p>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-119"></span>
<img src="http://imgs.xkcd.com/comics/null_hypothesis.png" alt="&quot;Hipótesis Nula&quot; (http://imgs.xkcd.com/comics/null_hypothesis.png (CC-BY-NC 2.5))"  />
<p class="caption">
Figura 5.1: “Hipótesis Nula” (<a href="http://imgs.xkcd.com/comics/null_hypothesis.png" class="uri">http://imgs.xkcd.com/comics/null_hypothesis.png</a> (CC-BY-NC 2.5))
</p>
</div>
<div id="contrastes-para-medias" class="section level2">
<h2><span class="header-section-number">5.1</span> Contrastes para medias</h2>
<div id="el-test-t" class="section level3 unnumbered">
<h3>El test t</h3>
<p>El <strong>test t</strong> para contrastar una o dos medias basado en la t de Student está implementado en la función <code>t.test</code>. Este test usa diferentes estadísticos según que el contraste sea de una media o de dos; en este último caso, según se usen muestras emparejadas o independientes; y en este último caso, según las poblaciones tengan varianzas iguales o diferentes. Aunque este test solo es exacto (en el sentido de que da la conclusión con el nivel de significación requerido) cuando las poblaciones involucradas siguen distribuciones normales, el Teorema Central del Límite garantiza que también da resultados aproximadamente correctos cuando las muestras son grandes, aunque las poblaciones no sean normales, por lo que en esta situación también se recomienda su uso. Así pues, aunque en la práctica el test t se use como test “de talla única” para contrastar una o dos medias en cualquier situación, hay que tener claro que su resultado es fiable tan solo:</p>
<ul>
<li><p>cuando las variables poblacionales involucradas son (aproximadamente) normales, o</p></li>
<li><p>cuando todas las muestras usadas son grandes.</p></li>
</ul>
<p>Al final de esta sección explicamos las funciones asociadas a algunos contrastes no paramétricos que pueden usarse cuando estas condiciones no se cumplen.</p>
<p>La sintaxis básica de la función <code>t.test</code> es</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">t.test</span>(x, y, <span class="dt">mu=</span>..., <span class="dt">alternative=</span>..., <span class="dt">conf.level=</span>..., <span class="dt">paired=</span>..., <span class="dt">var.equal=</span>...)</code></pre></div>
<p>donde:</p>
<ul>
<li><p><code>x</code> es el vector de datos que forma la muestra que analizamos.</p></li>
<li><p><code>y</code> es un vector opcional; si lo entramos, R entiende que estamos realizando un contraste de dos medias, con hipótesis nula la igualdad de estas medias.</p></li>
<li><p>Podemos sustituir los vectores <code>x</code> e <code>y</code> por una fórmula <code>variable1~variable2</code> que indique que separamos la variable numérica <code>variable1</code> en dos vectores definidos por los niveles de un factor <code>variable2</code> de dos niveles (o de otra variable asimilable a un factor de dos niveles, como por ejemplo una variable numérica que solo tome dos valores diferentes). Con esta construcción, R tomará estos vectores en el orden natural de los niveles de <code>variable2</code>: <code>x</code> será el vector correspondiente al primer nivel e <code>y</code> el correspondiente al segundo. Hay que tener esto en cuenta a la hora de especificar la hipótesis alternativa si es unilateral. Si las dos variables de la fórmula son columnas de un <em>dataframe</em>, se puede usar el parámetro <code>data=...</code> para indicarlo.</p></li>
<li><p>Solamente tenemos que especificar el parámetro <code>mu</code> si hemos entrado una sola muestra, y en este caso lo hemos de igualar al valor <span class="math inline">\(\mu_0\)</span> que queremos contrastar, de manera que la hipótesis nula será <span class="math inline">\(H_0: \mu=\mu_0\)</span>.</p></li>
<li><p>El parámetro <code>alternative</code> puede tomar tres valores: <code>&quot;two.sided&quot;</code>, para contrastes bilaterales, y <code>&quot;less&quot;</code> y <code>&quot;greater&quot;</code>, para contrastes unilaterales. En esta función, y en todas las que explicamos en esta lección, su valor por defecto, que no hace falta especificar, es <code>&quot;two.sided&quot;</code>. El significado de estos valores depende del tipo de test que efectuemos:</p>
<ul>
<li><p>Si el test es de una sola muestra, <code>&quot;two.sided&quot;</code> representa la hipótesis alternativa <span class="math inline">\(H_1: \mu\neq \mu_0\)</span>, <code>&quot;less&quot;</code> corresponde a <span class="math inline">\(H_1: \mu&lt; \mu_0\)</span>, y <code>&quot;greater&quot;</code> corresponde a <span class="math inline">\(H_1: \mu&gt; \mu_0\)</span>.</p></li>
<li><p>Si hemos entrado dos muestras y llamamos <span class="math inline">\(\mu_x\)</span> y <span class="math inline">\(\mu_y\)</span> a las medias de las poblaciones de las que hemos extraído las muestras <span class="math inline">\(x\)</span> e <span class="math inline">\(y\)</span>, respectivamente, entonces <code>&quot;two.sided&quot;</code> representa la hipótesis alternativa <span class="math inline">\(H_1: \mu_x \neq \mu_y\)</span>; <code>&quot;less&quot;</code> indica que la hipótesis alternativa es <span class="math inline">\(H_1: \mu_x&lt; \mu_y\)</span>; y <code>&quot;greater&quot;</code>, que la hipótesis alternativa es <span class="math inline">\(H_1: \mu_x&gt; \mu_y\)</span>.</p></li>
</ul></li>
<li><p>El valor del parámetro <code>conf.level</code> es el nivel de confianza <span class="math inline">\(1-\alpha\)</span>. En esta función, y en todas las que explicamos en esta lección, su valor por defecto, que no es necesario especificar, es 0.95, que corresponde a un nivel de confianza del 95%, es decir, a un nivel de significación <span class="math inline">\(\alpha=0.05\)</span>.</p></li>
<li><p>El parámetro <code>paired</code> solo lo tenemos que especificar si llevamos a cabo un contraste de dos medias. En este caso, con <code>paired=TRUE</code> indicamos que las muestras son emparejadas, y con <code>paired=FALSE</code> (que es su valor por defecto) que son independientes. Si se trata de muestras emparejadas, los vectores <code>x</code> e <code>y</code> tienen que tener la misma longitud, naturalmente.</p></li>
<li><p>El parámetro <code>var.equal</code> solo lo tenemos que especificar si llevamos a cabo un contraste de dos medias usando muestras independientes, y en este caso sirve para indicar si queremos considerar las dos varianzas poblacionales iguales (igualándolo a TRUE) o diferentes (igualándolo a FALSE, que es su valor por defecto).</p></li>
</ul>
<p>La función <code>t.test</code> tiene otro parámetro que queremos destacar, que es común a la mayoría de las funciones de estadística inferencial y análisis de datos. Se trata del parámetro <code>na.action</code>, que sirve para especificar qué queremos hacer con los valores NA. Su valor por defecto es <code>na.omit</code>, que elimina las entradas NA de los vectores (o los pares que contengan algún NA, en el caso de muestras emparejadas). Por ahora, esta opción por defecto es la adecuada, por lo que no hace falta usar este parámetro, pero conviene saber que hay alternativas. Las más útiles son: <code>na.fail</code>, que hace que la ejecución pare si hay algún NA en los vectores, y <code>na.pass</code>, que no hace nada con los NA y permite que las operaciones internas de la función sigan su curso y los manejen como les corresponda.</p>
<p>Veamos varios ejemplos de uso de esta función.</p>

<div class="example">
<span id="exm:norm1bis" class="example"><strong>Ejemplo 5.2  </strong></span>Consideremos el siguiente vector de longitud 25:
</div>

<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x=<span class="kw">c</span>(<span class="fl">2.2</span>,<span class="fl">2.66</span>,<span class="fl">2.74</span>,<span class="fl">3.41</span>,<span class="fl">2.46</span>,<span class="fl">2.96</span>,<span class="fl">3.34</span>,<span class="fl">2.16</span>,<span class="fl">2.46</span>,<span class="fl">2.71</span>,<span class="fl">2.04</span>,<span class="fl">3.74</span>,<span class="fl">3.24</span>,<span class="fl">3.92</span>,<span class="fl">2.38</span>,<span class="fl">2.82</span>,<span class="fl">2.2</span>,
    <span class="fl">2.42</span>,<span class="fl">2.82</span>,<span class="fl">2.84</span>,<span class="fl">4.22</span>,<span class="fl">3.64</span>,<span class="fl">1.77</span>,<span class="fl">3.44</span>,<span class="fl">1.53</span>)</code></pre></div>
<p>Supongamos que esta muestra ha sido extraída de una población normal. Postulamos que el valor medio <span class="math inline">\(\mu\)</span> de la población no es 2. Para confirmarlo, vamos realizar el contraste <span class="math display">\[
\left\{\begin{array}{l}
H_{0}:\mu=2\\
H_{1}:\mu\neq 2
\end{array}\right.
\]</span> con nivel de significación <span class="math inline">\(\alpha=0.05\)</span>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">t.test</span>(x, <span class="dt">mu=</span><span class="dv">2</span>, <span class="dt">alternative=</span><span class="st">&quot;two.sided&quot;</span>, <span class="dt">conf.level=</span><span class="fl">0.95</span>)</code></pre></div>
<pre><code>## 
##  One Sample t-test
## 
## data:  x
## t = 5.912, df = 24, p-value = 4.23e-06
## alternative hypothesis: true mean is not equal to 2
## 95 percent confidence interval:
##  2.52384 3.08576
## sample estimates:
## mean of x 
##    2.8048</code></pre>
<p>(Como los parámetros <code>alternative=&quot;two.sided&quot;</code> y <code>conf.level=0.95</code> eran los que toma R por defecto, en realidad no hacía falta especificarlos.) Observad la información que obtenemos con esta instrucción:</p>
<ul>
<li><p>Información sobre la muestra <span class="math inline">\(x\)</span>: su media muestral (<code>mean of x</code>) <span class="math inline">\(\overline{x}\)</span>, que vale 2.8048.</p></li>
<li><p>La hipótesis alternativa (<code>alternative hypothesis</code>), en este caso <code>true mean is not equal to 2</code>: la media verdadera, o poblacional, <span class="math inline">\(\mu\)</span> es diferente de 2.</p></li>
<li><p>El valor <code>t</code> que toma el estadístico de contraste, <span class="math inline">\(T=\frac{\overline{X}-\mu_0}{\widetilde{S}_X/\sqrt{n}}\)</span>, sobre la muestra, en este caso 5.912, y los grados de libertad <code>df</code> (<em>degrees of freedom</em>) de su distribución t de Student cuando la hipótesis nula es verdadera, <code>df =24</code>.</p></li>
<li><p>El p-valor (<code>p-value</code>) de nuestro test, en este caso <code>p-value = 4.232e-06</code>, es decir, <span class="math inline">\(4.232\times 10^{-6}\)</span>.</p></li>
<li><p>Un intervalo de confianza del <span class="math inline">\((1-\alpha)\times 100\%\)</span> (en nuestro caso, <code>95 percent confidence interval</code>) para la <span class="math inline">\(\mu\)</span>: en este ejemplo, [2.523844, 3.085756].</p></li>
</ul>
<p>Lo único que no nos dice directamente es si tenemos que rechazar o no la hipótesis nula, pero esto lo deducimos del p-valor: como es más pequeño que el nivel de significación (de hecho, es <em>muy</em> pequeño), podemos rechazar la hipótesis nula, <span class="math inline">\(\mu=2\)</span>, en favor de la alternativa, <span class="math inline">\(\mu \neq 2\)</span>. Es decir, hay evidencia estadísticamente significativa de que <span class="math inline">\(\mu \neq 2\)</span>. Otra manera de decidir si rechazamos o no la hipótesis nula es mirar si el valor que contrastamos pertenece al intervalo de confianza del contraste. Puesto que <span class="math inline">\(2 \notin [2.523844, 3.085756]\)</span>, podemos rechazar la hipótesis nula en favor de la alternativa y concluir que <span class="math inline">\(\mu\neq 2\)</span>.</p>
<p>Hagamos ahora el test cambiando la hipótesis alternativa por <span class="math inline">\(H_{1}:\mu&lt; 3\)</span>, es decir,</p>
<p><span class="math display">\[
\left\{\begin{array}{l}
H_{0}:\mu=3\\
H_{1}:\mu&lt; 3
\end{array}\right.
\]</span> y tomando como nivel de significación <span class="math inline">\(\alpha=0.1\)</span>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">t.test</span>(x, <span class="dt">mu=</span><span class="dv">3</span>, <span class="dt">alternative=</span><span class="st">&quot;less&quot;</span>, <span class="dt">conf.level=</span><span class="fl">0.9</span>)</code></pre></div>
<pre><code>## 
##  One Sample t-test
## 
## data:  x
## t = -1.434, df = 24, p-value = 0.0822
## alternative hypothesis: true mean is less than 3
## 90 percent confidence interval:
##    -Inf 2.9842
## sample estimates:
## mean of x 
##    2.8048</code></pre>
<p>En este caso, el p-valor es 0.082, por lo que podemos rechazar la hipótesis nula con un nivel de significación del 10% y concluir, con este nivel de significación (es decir, asumiendo esta probabilidad de equivocarnos), que <span class="math inline">\(\mu&lt;3\)</span>; pero fijaos en que con un nivel de significación del 5% no podríamos rechazar la hipótesis nula. El intervalo de confianza del 90% es ahora <span class="math inline">\((-\infty,2.984]\)</span> (<code>Inf</code> representa <span class="math inline">\(\infty\)</span>). Que no contenga el 3 (aunque por muy poco) también indica que podemos rechazar la hipótesis nula <span class="math inline">\(\mu=3\)</span> en favor de la alternativa <span class="math inline">\(\mu&lt; 3\)</span> con este nivel de confianza.</p>
<p>El p-valor y el intervalo de confianza se pueden obtener directamente, añadiendo a la instrucción <code>t.test</code> los sufijos <code>$p.value</code> o <code>$conf.int</code>, respectivamente. Esperamos que recordéis que en la lección anterior ya usábamos la construcción <code>t.test(...)$conf.int</code> para calcular un intervalo de confianza para la media usando la fórmula basada en la t de Student. Es lo correcto, puesto que el intervalo de confianza de un test t bilateral es el que explicamos entonces y no depende para nada de la hipótesis nula (por eso no especificábamos la <span class="math inline">\(\mu\)</span>, y dejábamos que la función tomase su valor por defecto, 0). Pero ahora podemos calcular dos intervalos de confianza más, correspondientes a los dos tipos de contrastes unilaterales. En ellos toda la “probabilidad de equivocarnos” se concentra a un lado del intervalo de confianza, en lugar de repartirse por igual a ambos lados.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">t.test</span>(x, <span class="dt">mu=</span><span class="dv">2</span>)<span class="op">$</span>p.value</code></pre></div>
<pre><code>## [1] 4.23159e-06</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">t.test</span>(x, <span class="dt">mu=</span><span class="dv">2</span>)<span class="op">$</span>conf.int</code></pre></div>
<pre><code>## [1] 2.52384 3.08576
## attr(,&quot;conf.level&quot;)
## [1] 0.95</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">t.test</span>(x, <span class="dt">mu=</span><span class="dv">2</span>)<span class="op">$</span>conf.int[<span class="dv">1</span>]</code></pre></div>
<pre><code>## [1] 2.52384</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">t.test</span>(x, <span class="dt">mu=</span><span class="dv">2</span>)<span class="op">$</span>conf.int[<span class="dv">2</span>]</code></pre></div>
<pre><code>## [1] 3.08576</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">t.test</span>(x, <span class="dt">mu=</span><span class="dv">3</span>, <span class="dt">alternative=</span><span class="st">&quot;less&quot;</span>, <span class="dt">conf.level=</span><span class="fl">0.9</span>)<span class="op">$</span>conf.int</code></pre></div>
<pre><code>## [1]   -Inf 2.9842
## attr(,&quot;conf.level&quot;)
## [1] 0.9</code></pre>
<p>Podéis consultar los sufijos necesarios para obtener las otras componentes del resultado en la Ayuda de la función.</p>

<div class="example">
<span id="exm:colesterol" class="example"><strong>Ejemplo 5.3  </strong></span>Queremos contrastar si el valor medio del nivel de colesterol en una población es de 220 mg/dl o no, a un nivel de significación del 5%. Es decir, si llamamos <span class="math inline">\(\mu\)</span> a la media de la variable aleatoria “Nivel de colesterol de un individuo de esta población, en mg/dl”, queremos realizar el contraste bilateral <span class="math display">\[
\left\{\begin{array}{l}
H_{0}:\mu=220\\
H_{1}:\mu \neq 220
\end{array}\right.
\]</span>
</div>

<p>Para ello, hemos tomado una muestra del nivel de colesterol en plasma de 9 individuos de la población. Los datos obtenidos, en mg/dl, son los siguientes:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">colesterol=<span class="kw">c</span>(<span class="dv">203</span>,<span class="dv">229</span>,<span class="dv">215</span>,<span class="dv">220</span>,<span class="dv">223</span>,<span class="dv">233</span>,<span class="dv">208</span>,<span class="dv">228</span>,<span class="dv">209</span>)</code></pre></div>
<p>Suponemos que el nivel de colesterol en plasma sigue una ley normal y que por lo tanto nos podemos fiar del resultado de un test t:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">t.test</span>(colesterol, <span class="dt">mu=</span><span class="dv">220</span>)</code></pre></div>
<pre><code>## 
##  One Sample t-test
## 
## data:  colesterol
## t = -0.3801, df = 8, p-value = 0.714
## alternative hypothesis: true mean is not equal to 220
## 95 percent confidence interval:
##  210.577 226.756
## sample estimates:
## mean of x 
##   218.667</code></pre>
<p>El p-valor es 0.714, muy grande y en particular superior a 0.05, por lo tanto no podemos rechazar la hipótesis nula de que el valor medio sea 220 mg/dl. Además, el intervalo de confianza del 95% del contraste es [210.58, 226.76], y contiene holgadamente el valor 220.</p>
<p>Más adelante en esta misma sección discutiremos qué podemos hacer si el nivel de colesterol en plasma no sigue una ley aproximadamente normal, en cuyo caso el resultado de este test t no sirve para nada.</p>

<div class="example">
<p><span id="exm:iris" class="example"><strong>Ejemplo 5.4  </strong></span>Recordad el <em>dataframe</em> <code>iris</code>, que recoge datos de las flores de 50 ejemplares de cada una de tres especies de iris.</p>
</div>

<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">str</span>(iris)</code></pre></div>
<pre><code>## &#39;data.frame&#39;:    150 obs. of  5 variables:
##  $ Sepal.Length: num  5.1 4.9 4.7 4.6 5 5.4 4.6 5 4.4 4.9 ...
##  $ Sepal.Width : num  3.5 3 3.2 3.1 3.6 3.9 3.4 3.4 2.9 3.1 ...
##  $ Petal.Length: num  1.4 1.4 1.3 1.5 1.4 1.7 1.4 1.5 1.4 1.5 ...
##  $ Petal.Width : num  0.2 0.2 0.2 0.2 0.2 0.4 0.3 0.2 0.2 0.1 ...
##  $ Species     : Factor w/ 3 levels &quot;setosa&quot;,&quot;versicolor&quot;,..: 1 1 1 1 1 1 1 1 1 1 ...</code></pre>
<p>Queremos estudiar si la longitud media <span class="math inline">\(\mu_v\)</span> de los sépalos de las <em>Iris virginica</em> es mayor que la longitud media <span class="math inline">\(\mu_s\)</span> de los sépalos de las <em>Iris setosa</em> usando las muestras contenidas en esta tabla de datos. Para ello realizamos el contraste</p>
<p><span class="math display">\[
\left\{\begin{array}{l}
H_{0}:\mu_s=\mu_v\\
H_{1}:\mu_s&lt; \mu_v
\end{array}\right.
\]</span> En este caso, se trata de un contraste de dos muestras independientes, y como las muestras son grandes, podemos usar con garantías un test t.</p>
<p>Ahora bien, recordad que el test t concreto que hay que usar depende de si las varianzas de las dos variables cuyas medias comparamos son iguales o diferentes. Como no sabemos nada de las varianzas de las longitudes de los sépalos de estas dos especies, y no nos supone apenas esfuerzo realizar los tests, llevaremos a cabo el contraste en los dos casos: varianzas iguales y varianzas diferentes.<a href="#fn1" class="footnoteRef" id="fnref1"><sup>1</sup></a> Más adelante, en el Ejemplo <a href="chap-contrastes.html#exm:variris">5.11</a>, explicamos cómo contrastar si estas dos varianzas son iguales o diferentes.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">S=iris[iris<span class="op">$</span>Species<span class="op">==</span><span class="st">&quot;setosa&quot;</span>,]<span class="op">$</span>Sepal.Length
V=iris[iris<span class="op">$</span>Species<span class="op">==</span><span class="st">&quot;virginica&quot;</span>,]<span class="op">$</span>Sepal.Length</code></pre></div>
<p>El test suponiendo que las dos varianzas son iguales:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">t.test</span>(S, V, <span class="dt">alternative=</span><span class="st">&quot;less&quot;</span>, <span class="dt">var.equal=</span><span class="ot">TRUE</span>) </code></pre></div>
<pre><code>## 
##  Two Sample t-test
## 
## data:  S and V
## t = -15.39, df = 98, p-value &lt;2e-16
## alternative hypothesis: true difference in means is less than 0
## 95 percent confidence interval:
##      -Inf -1.41126
## sample estimates:
## mean of x mean of y 
##     5.006     6.588</code></pre>
<p>El test suponiendo que las dos varianzas son diferentes:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">t.test</span>(S, V, <span class="dt">alternative=</span><span class="st">&quot;less&quot;</span>, <span class="dt">var.equal=</span><span class="ot">FALSE</span>) </code></pre></div>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  S and V
## t = -15.39, df = 76.52, p-value &lt;2e-16
## alternative hypothesis: true difference in means is less than 0
## 95 percent confidence interval:
##     -Inf -1.4108
## sample estimates:
## mean of x mean of y 
##     5.006     6.588</code></pre>
<p>En los dos casos el p-valor es prácticamente 0 y por lo tanto podemos rechazar la hipótesis nula en favor de la alternativa: tenemos evidencia estadísticamente muy significativa de que, en promedio, las flores de la especie setosa tienen sépalos más cortos que las de la especie virginica. El intervalo de confianza del 95% para la diferencia de medias <span class="math inline">\(\mu_s-\mu_v\)</span> en este contraste es en ambos casos <span class="math inline">\((-\infty, -1.41]\)</span> y no contiene el 0, que sería el valor de esta diferencia si la hipótesis nula <span class="math inline">\(\mu_s=\mu_v\)</span> fuera verdad.</p>

<div class="example">
<p><span id="exm:sueño" class="example"><strong>Ejemplo 5.5  </strong></span>En un experimento clásico de la primera década del siglo XX, Student quiso comparar el efecto somnífero de dos compuestos químicos, la hiosciamina y la hioscina. La hipótesis a contrastar era que la hioscina es más efectiva que la hiosciamina. Para ello, tomó 10 sujetos y midió su promedio de horas de sueño durante períodos de entre 3 y 9 días bajo tres tratamientos: en condiciones normales, tomando antes de acostarse 0.6 mg de hiosciamina y tomando antes de acostarse 0.6 mg de hioscina. A continuación, calculó para cada sujeto y cada compuesto la diferencia “promedio de horas de sueño tomando el compuesto menos promedio de horas de sueño en condiciones normales”. Las diferencias que obtuvo fueron las siguientes (las podéis encontrar en el <em>dataframe</em> <code>sleep</code> de la instalación básica de R, aunque no lo vamos a usar):</p>
</div>

<table>
<thead>
<tr class="header">
<th align="right">Sujeto</th>
<th align="right">Hiosciamina</th>
<th align="right">Hioscina</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">1</td>
<td align="right">0.7</td>
<td align="right">1.9</td>
</tr>
<tr class="even">
<td align="right">2</td>
<td align="right">-1.6</td>
<td align="right">0.8</td>
</tr>
<tr class="odd">
<td align="right">3</td>
<td align="right">-0.2</td>
<td align="right">1.1</td>
</tr>
<tr class="even">
<td align="right">4</td>
<td align="right">-1.2</td>
<td align="right">0.1</td>
</tr>
<tr class="odd">
<td align="right">5</td>
<td align="right">-0.1</td>
<td align="right">-0.1</td>
</tr>
<tr class="even">
<td align="right">6</td>
<td align="right">3.4</td>
<td align="right">4.4</td>
</tr>
<tr class="odd">
<td align="right">7</td>
<td align="right">3.7</td>
<td align="right">5.5</td>
</tr>
<tr class="even">
<td align="right">8</td>
<td align="right">0.8</td>
<td align="right">1.6</td>
</tr>
<tr class="odd">
<td align="right">9</td>
<td align="right">0.0</td>
<td align="right">4.6</td>
</tr>
<tr class="even">
<td align="right">10</td>
<td align="right">2.0</td>
<td align="right">3.4</td>
</tr>
</tbody>
</table>
<p>Una manera de comparar el efecto en las horas de sueño de estos compuestos es comparando las medias de estas diferencias de promedios de horas de sueño: una diferencia media mayor significa que, de media, el compuesto “ha añadido” más horas de sueño al promedio normal. Digamos <span class="math inline">\(\mu_1\)</span> a la media de las diferencias individuales del promedio de horas de sueño tomando hiosciamina menos el promedio en condiciones normales y <span class="math inline">\(\mu_2\)</span> a la media de las diferencias individuales del promedio de horas de sueño tomando hioscina menos el promedio en condiciones normales. Tomaremos como hipótesis nula <span class="math inline">\(H_0: \mu_1= \mu_2\)</span> (ambos compuestos tienen el mismo efecto medio sobre las horas de sueño de los individuos) e hipótesis alternativa <span class="math inline">\(H_1: \mu_1&lt;\mu_2\)</span> (la hioscina aumenta más las horas de sueño que la hiosciamina). Si podemos rechazar la hipótesis nula en favor de la alternativa, concluiremos que la hioscina tiene un mayor efecto somnífero que la hiosciamina.</p>
<p>Observad que se trata de un contraste de dos muestras emparejadas, porque los datos refieren a los mismos 10 pacientes. Vamos a suponer que las diferencias medias en horas de sueño en ambos casos siguen leyes normales (Student así lo hizo) y que, por lo tanto, el resultado de un test t es fiable.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">Hiosciamina=<span class="kw">c</span>(<span class="fl">0.7</span>,<span class="op">-</span><span class="fl">1.6</span>,<span class="op">-</span><span class="fl">0.2</span>,<span class="op">-</span><span class="fl">1.2</span>,<span class="op">-</span><span class="fl">0.1</span>,<span class="fl">3.4</span>,<span class="fl">3.7</span>,<span class="fl">0.8</span>,<span class="dv">0</span>,<span class="fl">2.0</span>)
Hioscina=<span class="kw">c</span>(<span class="fl">1.9</span>,<span class="fl">0.8</span>,<span class="fl">1.1</span>,<span class="fl">0.1</span>,<span class="op">-</span><span class="fl">0.1</span>,<span class="fl">4.4</span>,<span class="fl">5.5</span>,<span class="fl">1.6</span>,<span class="fl">4.6</span>,<span class="fl">3.4</span>)
<span class="kw">t.test</span>(Hiosciamina, Hioscina, <span class="dt">alternative=</span><span class="st">&quot;less&quot;</span>, <span class="dt">paired=</span><span class="ot">TRUE</span>)</code></pre></div>
<pre><code>## 
##  Paired t-test
## 
## data:  Hiosciamina and Hioscina
## t = -4.062, df = 9, p-value = 0.00142
## alternative hypothesis: true difference in means is less than 0
## 95 percent confidence interval:
##       -Inf -0.866995
## sample estimates:
## mean of the differences 
##                   -1.58</code></pre>
<p>El p-valor es 0.001, mucho menor que 0.05, y por lo tanto podemos rechazar la hipótesis nula con un nivel de significación del 5%. Observad también que el intervalo de confianza del 95% para la diferencia de medias <span class="math inline">\(\mu_1-\mu_2\)</span> es <span class="math inline">\((-\infty,-0.867]\)</span> y está totalmente a la izquierda del 0. La conclusión es, pues, que efectivamente la hioscina tiene un mayor efecto somnífero que la hiosciamina y que con un 95% de confianza podemos afirmar que añade, de media, como mínimo 52 minutos (-0.867 horas) diarios más de sueño.</p>

<div class="example">
<p><span id="exm:fumar" class="example"><strong>Ejemplo 5.6  </strong></span>Veamos un ejemplo de aplicación de <code>t.test</code> a una fórmula. Queremos contrastar si es cierto que fumar durante el embarazo está asociado a un peso menor del recién nacido. Si llamamos <span class="math inline">\(\mu_n\)</span> y <span class="math inline">\(\mu_f\)</span> al peso medio de un recién nacido de madre no fumadora y fumadora, respectivamente, el contraste que queremos realizar es <span class="math display">\[
\left\{\begin{array}{l}
H_{0}:\mu_n=\mu_f\\
H_{1}:\mu_n&gt; \mu_f
\end{array}\right.
\]</span> Vamos a usar los datos incluidos en la tabla <code>birthwt</code> incluida en el paquete <strong>MASS</strong>, que recoge información sobre una muestra de madres y sus hijos.</p>
</div>

<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(MASS)
<span class="kw">str</span>(birthwt)</code></pre></div>
<pre><code>## &#39;data.frame&#39;:    189 obs. of  10 variables:
##  $ low  : int  0 0 0 0 0 0 0 0 0 0 ...
##  $ age  : int  19 33 20 21 18 21 22 17 29 26 ...
##  $ lwt  : int  182 155 105 108 107 124 118 103 123 113 ...
##  $ race : int  2 3 1 1 1 3 1 3 1 1 ...
##  $ smoke: int  0 0 1 1 1 0 0 0 1 1 ...
##  $ ptl  : int  0 0 0 0 0 0 0 0 0 0 ...
##  $ ht   : int  0 0 0 0 0 0 0 0 0 0 ...
##  $ ui   : int  1 0 0 1 1 0 0 0 0 0 ...
##  $ ftv  : int  0 3 1 2 0 0 1 1 1 0 ...
##  $ bwt  : int  2523 2551 2557 2594 2600 2622 2637 2637 2663 2665 ...</code></pre>
<p>En la Ayuda de <code>birthwt</code> nos enteramos de que la variable <code>smoke</code> indica si la madre ha fumado durante el embarazo (1) o no (0), y que la variable <code>bwt</code> da el peso del recién nacido en gramos. Lo primero que haremos será mirar si las muestras de madres fumadoras y no fumadoras contenidas en esta tabla son lo suficientemente grandes como para que el resultado del test t sea fiable.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">table</span>(birthwt<span class="op">$</span>smoke)</code></pre></div>
<pre><code>## 
##   0   1 
## 115  74</code></pre>
<p>Vemos que sí, que ambas son suficientemente grandes.</p>
<p>Para entrar en la instrucción <code>t.test</code> los vectores de pesos de hijos de fumadoras y no fumadoras, usaremos la fórmula <code>bwt~smoke</code> especificando que <code>data=birthwt</code>. Fijaos en que los valores de <code>smoke</code> son 0 y 1, y que R los considera ordenados en este orden (basta ver el resultado de la función <code>table</code> anterior). Por consiguiente, <code>bwt~smoke</code> representa, en este orden, el vector de pesos de recién nacidos de madres no fumadoras (<code>smoke=0</code>) y el vector de pesos de recién nacidos de madres fumadoras (<code>smoke=1</code>). Como la hipótesis alternativa es <span class="math inline">\(\mu_n&gt;\mu_f\)</span>, deberemos especificar en la función <code>t.test</code> que <code>alternative=&quot;greater&quot;</code>.</p>
<p>Es un contraste de muestras independientes, y por lo tanto el procedimiento para llevarlo a cabo depende de la igualdad o no de las varianzas de los pesos de los recién nacidos en los dos grupos de madres. Como en el Ejemplo <a href="chap-contrastes.html#exm:iris">5.4</a>, vamos a llevar a cabo el test t suponiendo que estas varianzas son iguales y que son diferentes, y cruzaremos los dedos para que la conclusión sea la misma. Otra posibilidad es contrastar antes la igualdad de las varianzas.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">t.test</span>(bwt<span class="op">~</span>smoke, <span class="dt">data=</span>birthwt, <span class="dt">alternative=</span><span class="st">&quot;greater&quot;</span>, <span class="dt">paired=</span><span class="ot">FALSE</span>, <span class="dt">var.equal=</span><span class="ot">TRUE</span>)</code></pre></div>
<pre><code>## 
##  Two Sample t-test
## 
## data:  bwt by smoke
## t = 2.653, df = 187, p-value = 0.00433
## alternative hypothesis: true difference in means is greater than 0
## 95 percent confidence interval:
##  106.953     Inf
## sample estimates:
## mean in group 0 mean in group 1 
##         3055.70         2771.92</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">t.test</span>(bwt<span class="op">~</span>smoke, <span class="dt">data=</span>birthwt, <span class="dt">alternative=</span><span class="st">&quot;greater&quot;</span>, <span class="dt">paired=</span><span class="ot">FALSE</span>, <span class="dt">var.equal=</span><span class="ot">FALSE</span>)</code></pre></div>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  bwt by smoke
## t = 2.73, df = 170.1, p-value = 0.0035
## alternative hypothesis: true difference in means is greater than 0
## 95 percent confidence interval:
##  111.855     Inf
## sample estimates:
## mean in group 0 mean in group 1 
##         3055.70         2771.92</code></pre>
<p>En ambos casos hemos obtenido un p-valor un orden de magnitud inferior a 0.05, lo que nos permite concluir que, en efecto, los hijos de las madres no fumadoras pesan más al nacer que los de las fumadoras.</p>
<p>En vez de especificar los vectores de pesos con <code>bwt~smoke,data=birthwt</code>, hubiéramos podido usar <code>birthwt$bwt~birthwt$smoke</code>. Por ejemplo:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">t.test</span>(birthwt<span class="op">$</span>bwt<span class="op">~</span>birthwt<span class="op">$</span>smoke, <span class="dt">alternative=</span><span class="st">&quot;greater&quot;</span>, <span class="dt">paired=</span><span class="ot">FALSE</span>, <span class="dt">var.equal=</span><span class="ot">TRUE</span>)</code></pre></div>
<pre><code>## 
##  Two Sample t-test
## 
## data:  birthwt$bwt by birthwt$smoke
## t = 2.653, df = 187, p-value = 0.00433
## alternative hypothesis: true difference in means is greater than 0
## 95 percent confidence interval:
##  106.953     Inf
## sample estimates:
## mean in group 0 mean in group 1 
##         3055.70         2771.92</code></pre>
</div>
<div id="tests-no-parametricos" class="section level3 unnumbered">
<h3>Tests no paramétricos</h3>
<p>Cuando comparamos dos medias, o una media con un valor, usando un test t sobre muestras pequeñas, suponemos que las variables poblacionales que han producido las muestras son normales. En la Lección <a href="chap-bondad.html#chap:bondad">6</a> estudiaremos los contrastes que nos permiten aceptar o rechazar que una muestra provenga de una variable aleatoria con una distribución concreta, pero en estos momentos ya tendría que ser claro que nos podemos encontrar con conjuntos de datos para los cuales el supuesto de normalidad de la variable poblacional no esté justificado: por ejemplo, porque sean datos cuantitativos discretos o porque la variable sea claramente muy asimétrica (por citar una, la duración del embarazo, con una clara cola a la izquierda: hay un número no despreciable de partos prematuros, pero ningún embarazo dura 11 meses). En las situaciones en las que no estamos seguros de que las variables poblacionales satisfagan aproximadamente las hipótesis de los teoremas que nos garantizan la fiabilidad de las conclusiones de un contraste, por ejemplo de un test t, una salida razonable es usar un <strong>test no paramétrico</strong> alternativo.</p>
<p>En el caso de los contrastes de medias, los tests no paramétricos para comparar medias en realidad lo que comparan son las medianas. Los más populares son los siguientes:</p>
<ul>
<li><p>El <strong>test de signos</strong>, que permite contrastar si la mediana de una variable aleatoria cualquiera (incluso ordinal) es un valor dado <span class="math inline">\(M_0\)</span> estudiando la distribución de los signos de las diferencias entre este valor y los de una muestra (si la mediana fuera <span class="math inline">\(M_0\)</span>, los números de diferencias positivas y negativas en muestras aleatorias seguirían distribuciones binomiales con <span class="math inline">\(p=0.5\)</span>). En R está implementado en la función <code>SIGN.test</code> del paquete <strong>BSDA</strong>. Su sintaxis es similar a la de <code>t.test</code> para una muestra, cambiando el parámetro <code>mu</code>, que en <code>t.test</code> sirve para especificar el valor de la media que contrastamos, por <code>md</code>, que en <code>SIGN.test</code> sirve para especificar el valor de la <strong>mediana</strong> que contrastamos. Esta función también se puede aplicar a dos muestras emparejadas: en este caso, la hipótesis nula del contraste que realiza es que “la mediana de las diferencias de las dos variables es 0”.</p></li>
<li><p>El <strong>test de Wilcoxon</strong> para comparar la media de una variable continua simétrica con un valor dado o las medias de dos variables continuas cuya diferencia sea simétrica por medio de muestras emparejadas. Más en general, se puede usar para comparar la mediana de una variable continua con un valor dado o para comparar la mediana de la diferencia de dos variables continuas (medidas sobre muestras emparejadas) con 0. Observad que cuando las variables en juego son simétricas, las medianas coinciden con las medias y el contraste de medianas es también un contraste de medias. En R está implementado en la función <code>wilcox.test</code> y su sintaxis es la misma que la de <code>t.test</code> para una muestra o para dos muestras emparejadas (en este último caso, hay que especificar <code>paired=TRUE</code>).</p></li>
<li><p>El <strong>test de Mann-Whitney</strong> para comparar las medianas de dos variables aleatorias por medio de muestras independientes. En R también está implementado en la función <code>wilcox.test</code> y su sintaxis es la misma que la de <code>t.test</code> para dos muestras independientes (especificando <code>paired=FALSE</code>), salvo que aquí no hay que especificar si las varianzas son iguales o diferentes, puesto que esto no se usa en este test.</p></li>
</ul>

<div class="example">
<p><span id="exm:wilcox-colesterol" class="example"><strong>Ejemplo 5.7  </strong></span>Si los niveles de colesterol no siguen una distribución normal, el test t realizado en el Ejemplo <a href="chap-contrastes.html#exm:colesterol">5.3</a> no sirve para nada. Una posibilidad es entonces no contrastar si el nivel medio de colesterol es 220, sino si el nivel <em>mediano</em> es 220. Para ello vamos realizar un test de signos. Los parámetros <code>alternative=&quot;two.sided&quot;</code> y <code>conf.level=0.95</code> son los que usa la función <code>SIGN.test</code> por defecto, así que no haría falta especificarlos; los incluimos para que los veáis.</p>
</div>

<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(BSDA)
<span class="kw">SIGN.test</span>(colesterol, <span class="dt">md=</span><span class="dv">220</span>, <span class="dt">alternative=</span><span class="st">&quot;two.sided&quot;</span>, <span class="dt">conf.level=</span><span class="fl">0.95</span>)</code></pre></div>
<pre><code>## 
##  One-sample Sign-Test
## 
## data:  colesterol
## s = 4, p-value = 1
## alternative hypothesis: true median is not equal to 220
## 95 percent confidence interval:
##  208.078 228.922
## sample estimates:
## median of x 
##         220 
## 
## Achieved and Interpolated Confidence Intervals: 
## 
##                   Conf.Level  L.E.pt  U.E.pt
## Lower Achieved CI     0.8203 209.000 228.000
## Interpolated CI       0.9500 208.078 228.922
## Upper Achieved CI     0.9609 208.000 229.000</code></pre>
<p>Observad que la salida de la función es muy similar a la de <code>t.test</code> (salvo por los últimos intervalos de confianza, que no vamos a explicar). El p-valor ha dado directamente 1 y el intervalo de confianza al 95% para la mediana ha dado [208.1, 228.9]: por lo tanto, no podemos rechazar que la mediana del nivel de colesterol en la población de la que hemos extraído la muestra sea 220.</p>
<p>También podríamos usar el test de Wilcoxon para realizar este contraste de una mediana:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">wilcox.test</span>(colesterol, <span class="dt">mu=</span><span class="dv">220</span>, <span class="dt">alternative=</span><span class="st">&quot;two.sided&quot;</span>,<span class="dt">conf.level=</span><span class="fl">0.95</span>)</code></pre></div>
<pre><code>## Warning in wilcox.test.default(colesterol, mu = 220, alternative =
## &quot;two.sided&quot;, : cannot compute exact p-value with zeroes</code></pre>
<pre><code>## 
##  Wilcoxon signed rank test with continuity correction
## 
## data:  colesterol
## V = 15, p-value = 0.726
## alternative hypothesis: true location is not equal to 220</code></pre>
<p>El p-valor es 0.726, la conclusión es la misma. El mensaje de advertencia nos avisa de que la muestra ha contenido valores iguales al valor de la mediana contrastado, por lo que el p-valor obtenido no es exacto. Solo os tenéis que preocupar de un mensaje como este si el p-valor fuera muy cercano al nivel de significación deseado, que no es el caso.</p>

<div class="example">
<p><span id="exm:unnamed-chunk-144" class="example"><strong>Ejemplo 5.8  </strong></span>Si las diferencias en promedios de horas de sueño no siguen distribuciones normales, el test t realizado en el Ejemplo <a href="chap-contrastes.html#exm:sueño">5.5</a> no sirve para nada. En este caso, vamos a usar un test de Wilcoxon para muestras emparejadas. Este test en realidad contrastará la <em>hipótesis nula</em> de que si para cada individuo calculamos la diferencia entre el aumento promedio de horas de sueño cuando toma hiosciamina y el aumento promedio tomando hioscina, la <strong>mediana</strong> de la variable aleatoria que define estas diferencias es 0, y como hipótesis alternativa que esta mediana es menor que 0 (y que por lo tanto más de la mitad de las veces es negativa, es decir, que a más de la mitad de la población la hioscina le añade más tiempo promedio de sueño que la hiosciamina). Si las variables “aumento de horas de sueño” en juego son simétricas, estas medianas coinciden con las correspondientes medias y llevamos a cabo el contraste del Ejemplo <a href="chap-contrastes.html#exm:sueño">5.5</a>. Si no son simétricas, igualmente estamos contrastando si la hioscina es más efectiva que la hiosciamina, solo que planteándolo de otra manera.</p>
</div>

<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">wilcox.test</span>(Hiosciamina, Hioscina, <span class="dt">alternative=</span><span class="st">&quot;less&quot;</span>, <span class="dt">paired=</span><span class="ot">TRUE</span>)</code></pre></div>
<pre><code>## Warning in wilcox.test.default(Hiosciamina, Hioscina, alternative =
## &quot;less&quot;, : cannot compute exact p-value with ties</code></pre>
<pre><code>## Warning in wilcox.test.default(Hiosciamina, Hioscina, alternative =
## &quot;less&quot;, : cannot compute exact p-value with zeroes</code></pre>
<pre><code>## 
##  Wilcoxon signed rank test with continuity correction
## 
## data:  Hiosciamina and Hioscina
## V = 0, p-value = 0.00455
## alternative hypothesis: true location shift is less than 0</code></pre>
<p>En este caso R nos avisa de nuevo de que el p-valor no es exacto, pero esto no afecta a la conclusión dado que el p-valor es muy pequeño: rechazamos la hipótesis nula en favor de la alternativa y también concluimos con este test no paramétrico que la hioscina tiene un mayor efecto somnífero que la hiosciamina.</p>

<div class="example">
<p><span id="exm:unnamed-chunk-146" class="example"><strong>Ejemplo 5.9  </strong></span>Nos preguntamos si los hijos de madres de 20 años pesan lo mismo al nacer que los de madres de 30 años, o no. Querríamos responder esta pregunta planteándola como un contraste bilateral de los pesos medios de los hijos de madres de 20 y 30 años y usando la muestra recogida en la tabla de datos <code>birthwt</code> del paquete <strong>MASS</strong>, que contiene la variable <code>age</code> con la edad de las madres.</p>
</div>

<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">hijos.<span class="dv">20</span>=birthwt[birthwt<span class="op">$</span>age<span class="op">==</span><span class="dv">20</span>,<span class="st">&quot;bwt&quot;</span>]
hijos.<span class="dv">30</span>=birthwt[birthwt<span class="op">$</span>age<span class="op">==</span><span class="dv">30</span>,<span class="st">&quot;bwt&quot;</span>]
<span class="kw">c</span>(<span class="kw">length</span>(hijos.<span class="dv">20</span>),<span class="kw">length</span>(hijos.<span class="dv">30</span>))</code></pre></div>
<pre><code>## [1] 18  7</code></pre>
<p>Las muestras no son lo suficientemente grandes como para usar un test t si no estamos seguros de que las variables poblacionales sean normales. Como las muestras son independientes, vamos a usar un test de Mann-Whitney para comparar los pesos medianos. Es decir, en vez de traducir “los hijos de madres de 20 años pesan lo mismo al nacer que los de madres de 30 años” en términos de igualdad de pesos medios, lo traducimos en términos de igualdad de pesos medianos. (En realidad, la hipótesis nula de este test es que “Es igual de probable que un hijo de madre de 20 años pese más que un hijo de madre de 30 años que al revés”, pero no vamos a entrar en este nivel de precisión. Es otra manera de decir que no hay tendencia a que unos pesen más que los otros.)</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">wilcox.test</span>(hijos.<span class="dv">20</span>, hijos.<span class="dv">30</span>, <span class="dt">alternative=</span><span class="st">&quot;two.sided&quot;</span>,<span class="dt">paired=</span><span class="ot">FALSE</span>)</code></pre></div>
<pre><code>## Warning in wilcox.test.default(hijos.20, hijos.30, alternative =
## &quot;two.sided&quot;, : cannot compute exact p-value with ties</code></pre>
<pre><code>## 
##  Wilcoxon rank sum test with continuity correction
## 
## data:  hijos.20 and hijos.30
## W = 43.5, p-value = 0.25
## alternative hypothesis: true location shift is not equal to 0</code></pre>
<p>El p-valor es 0.25, por lo que no podemos rechazar que las medianas de los pesos al nacer de los hijos de madres de 20 años y de 30 sean iguales.</p>
</div>
</div>
<div id="contrastes-para-varianzas" class="section level2">
<h2><span class="header-section-number">5.2</span> Contrastes para varianzas</h2>
<p>El <strong>test <span class="math inline">\(\chi^2\)</span></strong> para comparar la varianza <span class="math inline">\(\sigma^2\)</span> (o la desviación típica <span class="math inline">\(\sigma\)</span>) de una población normal con un valor dado <span class="math inline">\(\sigma_0^2\)</span> (o <span class="math inline">\(\sigma_0\)</span>) usa el estadístico <span class="math display">\[
\frac{(n-1)\widetilde{S}_X^2}{\sigma_0^2}
\]</span> que, si la hipótesis nula <span class="math inline">\(\sigma^2=\sigma_0^2\)</span> es verdadera, sigue una distribución <span class="math inline">\(\chi^2_{n-1}\)</span>, de ahí su nombre. Dicho test está convenientemente implementado en la función <code>sigma.test</code> del paquete <strong>TeachingDemos</strong>. Su sintaxis es la misma que la de la función <code>t.test</code> para una muestra, substituyendo el parámetro <code>mu</code> de <code>t.test</code> por el parámetro <code>sigma</code> (para especificar el valor de la desviación típica que contrastamos, <span class="math inline">\(\sigma_0\)</span>) o <code>sigmasq</code> (por “sigma al cuadrado”, para especificar el valor de la varianza que contrastamos, <span class="math inline">\(\sigma_0^2\)</span>). Como siempre, los valores por defecto de <code>alternative</code> y <code>conf.level</code> son <code>&quot;two.sided&quot;</code> y 0.95, respectivamente. La salida de la función es también similar a la de <code>t.test</code>. Veamos un ejemplo.</p>

<div class="example">
<p><span id="exm:unnamed-chunk-149" class="example"><strong>Ejemplo 5.10  </strong></span>Se ha realizado un experimento para estudiar el tiempo <span class="math inline">\(X\)</span> (en minutos) que tarda un lagarto del desierto en llegar a los 45<sup>o</sup> partiendo de su temperatura normal mientras está a la sombra. Los tiempos obtenidos (en minutos) en una muestra aleatoria de lagartos fueron los siguientes:</p>
</div>

<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">TL45=<span class="kw">c</span>(<span class="fl">10.1</span>,<span class="fl">12.5</span>,<span class="fl">12.2</span>,<span class="fl">10.2</span>,<span class="fl">12.8</span>,<span class="fl">12.1</span>,<span class="fl">11.2</span>,<span class="fl">11.4</span>,<span class="fl">10.7</span>,<span class="fl">14.9</span>,<span class="fl">13.9</span>,<span class="fl">13.3</span>)</code></pre></div>
<p>Supongamos que estos tiempos siguen una ley normal. ¿Aporta este experimento evidencia de que la desviación típica <span class="math inline">\(\sigma\)</span> de <span class="math inline">\(X\)</span> es inferior a 1.5 minutos? Para responder esta pregunta, hemos de realizar el contraste <span class="math display">\[
\left\{\begin{array}{l}
H_{0}:\sigma= 1.5 \\
H_{1}:\sigma&lt; 1.5
\end{array}\right.
\]</span> Para ello, usaremos la función <code>sigma.test</code> aplicada a esta muestra y a <code>sigma=1.5</code>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(TeachingDemos)
<span class="kw">sigma.test</span>(TL45, <span class="dt">sigma=</span><span class="fl">1.5</span>, <span class="dt">alternative=</span><span class="st">&quot;less&quot;</span>)</code></pre></div>
<pre><code>## 
##  One sample Chi-squared test for variance
## 
## data:  TL45
## X-squared = 10.69, df = 11, p-value = 0.53
## alternative hypothesis: true variance is less than 2.25
## 95 percent confidence interval:
##  0.00000 5.25686
## sample estimates:
## var of TL45 
##     2.18629</code></pre>
<p>El p-valor que obtenemos es 0.53, muy grande, por lo que no tenemos evidencia que nos permita concluir que <span class="math inline">\(\sigma&lt;1.5\)</span>.</p>
<p><strong>¡Atención!</strong> El intervalo de confianza que da la función <code>sigma.test</code> es siempre para la varianza, aunque le entréis el valor de la desviación típica. Así que si queréis un intervalo de confianza para la desviación típica, tenéis que tomar la raíz cuadrada del que os da <code>sigma.test</code>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sqrt</span>(<span class="kw">sigma.test</span>(TL45, <span class="dt">sigma=</span><span class="fl">1.5</span>, <span class="dt">alternative=</span><span class="st">&quot;less&quot;</span>)<span class="op">$</span>conf.int)</code></pre></div>
<pre><code>## [1] 0.00000 2.29279
## attr(,&quot;conf.level&quot;)
## [1] 0.95</code></pre>
<p>El test <span class="math inline">\(\chi^2\)</span> no se usa mucho en la práctica. En parte, porque realmente es poco interesante ya que suele ser difícil conjeturar la desviación típica a contrastar, y en parte porque su validez depende fuertemente de la hipótesis de que la variable aleatoria poblacional sea normal. En cambio, el contraste de las desviaciones típicas de dos poblaciones sí que es muy utilizado. Por ejemplo, en un contraste de dos medias usando un test t sobre dos muestras independientes, nos puede interesar conocer <em>a priori</em> si las varianzas poblacionales son iguales o diferentes, en lugar de realizar el test bajo ambas suposiciones. Si no las conocemos, ¿cómo podemos saber cuál es el caso? Si las dos variables poblacionales son normales, podemos contrastar la igualdad de las varianzas con el <strong>test F</strong>, basado en el estadístico <span class="math display">\[
\frac{\widetilde{S}_{X_1}^2} {\widetilde{S}_{X_2}^2}
\]</span> que, si las dos poblaciones son normales y tienen la misma varianza, sigue una distribución F de Fisher-Snedecor. Por desgracia, este test es también muy sensible a la no normalidad de las poblaciones objeto de estudio: a la que una de ellas se aleja un poco de la normalidad, el test deja de dar resultados fiables.<a href="#fn2" class="footnoteRef" id="fnref2"><sup>2</sup></a></p>
<p>La función para efectuar este test es <code>var.test</code> y su sintaxis básica es la misma que la de <code>t.test</code> para dos muestras:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">var.test</span>(x, y, <span class="dt">alternative=</span>..., <span class="dt">conf.level=</span>...)</code></pre></div>
<p>donde <code>x</code> e <code>y</code> son los dos vectores de datos, que se pueden especificar mediante una fórmula como en el caso de <code>t.test</code>, y el parámetro <code>alternative</code> puede tomar los tres mismos valores que en los tests anteriores: su valor por defecto es, como siempre, <code>&quot;two.sided&quot;</code>, que es el que nos permite contrastar si las varianzas son iguales o diferentes.</p>

<div class="example">
<p><span id="exm:variris" class="example"><strong>Ejemplo 5.11  </strong></span>Suponiendo que las longitudes de los sépalos de las flores de las diferentes especies de iris siguen leyes normales, ¿hubiéramos podido considerar <em>a priori</em> iguales las varianzas de las dos muestras en el Ejemplo <a href="chap-contrastes.html#exm:iris">5.4</a>? Veamos:</p>
</div>

<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">S=iris[iris<span class="op">$</span>Species<span class="op">==</span><span class="st">&quot;setosa&quot;</span>,]<span class="op">$</span>Sepal.Length
V=iris[iris<span class="op">$</span>Species<span class="op">==</span><span class="st">&quot;virginica&quot;</span>,]<span class="op">$</span>Sepal.Length
<span class="kw">var.test</span>(S,V)</code></pre></div>
<pre><code>## 
##  F test to compare two variances
## 
## data:  S and V
## F = 0.3073, num df = 49, denom df = 49, p-value = 6.37e-05
## alternative hypothesis: true ratio of variances is not equal to 1
## 95 percent confidence interval:
##  0.174378 0.541496
## sample estimates:
## ratio of variances 
##           0.307286</code></pre>
<p>El p-valor es <span class="math inline">\(6.4\times 10^{-5}\)</span>, muy pequeño. Por lo tanto, podemos rechazar la hipótesis nula de que las dos varianzas son iguales, en favor de la hipótesis alternativa de que las dos varianzas son diferentes. Así, pues, bastaba realizar solo el <code>t.test</code> con <code>var.equal=FALSE</code>.</p>
<p>Puede ser conveniente remarcar aquí que el intervalo de confianza obtenido con <code>var.test</code> es para <em>el cociente de varianzas poblacionales</em> <span class="math inline">\(\sigma^2_x/\sigma^2_y\)</span>, no para su diferencia. Por lo tanto, para contrastar si las varianzas son iguales o diferentes, hay que mirar si el 1 pertenece o no al intervalo obtenido. En este ejemplo, el intervalo de confianza al 95% ha sido [0.174, 0.541] y no contiene el 1, lo que confirma la evidencia de que las varianzas son diferentes.</p>

<div class="example">
<p><span id="exm:unnamed-chunk-155" class="example"><strong>Ejemplo 5.12  </strong></span>Queremos contrastar si los gatos adultos macho pesan más que los gatos adultos hembra. Para ello usaremos los datos recogidos en el <em>dataframe</em> <code>cats</code> del paquete <strong>MASS</strong>, que contiene información sobre el peso de una muestra de gatos adultos, separados por su sexo.</p>
</div>

<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">str</span>(cats)</code></pre></div>
<pre><code>## &#39;data.frame&#39;:    144 obs. of  3 variables:
##  $ Sex: Factor w/ 2 levels &quot;F&quot;,&quot;M&quot;: 1 1 1 1 1 1 1 1 1 1 ...
##  $ Bwt: num  2 2 2 2.1 2.1 2.1 2.1 2.1 2.1 2.1 ...
##  $ Hwt: num  7 7.4 9.5 7.2 7.3 7.6 8.1 8.2 8.3 8.5 ...</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">table</span>(cats<span class="op">$</span>Sex)</code></pre></div>
<pre><code>## 
##  F  M 
## 47 97</code></pre>
<p>Consultando la Ayuda de <code>cats</code> nos enteramos de que la variable <code>Bwt</code> contiene el peso de cada gato en kg, y la variable <code>Sex</code> contiene el sexo de cada gato: F para hembra (<em>female</em>) y M para macho (<em>male</em>). Como vemos en la tabla de frecuencias, los números de ejemplares de cada sexo son grandes.</p>
<p>Así pues, si llamamos <span class="math inline">\(\mu_m\)</span> al peso medio de un gato macho adulto y <span class="math inline">\(\mu_h\)</span> al peso medio de un gato hembra adulto, el contraste que vamos a realizar es <span class="math display">\[
\left\{\begin{array}{l}
H_{0}:\mu_m=\mu_h\\
H_{1}:\mu_m&gt;\mu_h
\end{array}\right.
\]</span> y para ello antes vamos a contrastar si las varianzas de ambas poblaciones son iguales o diferentes, para luego poder aplicar la función <code>t.test</code> con el valor de <code>var.equal</code> adecuado. Vamos a suponer que los pesos en ambos sexos siguen leyes normales. Para que el contraste de las varianzas sea fiable es necesario que esta suposición sea cierta; para el de los pesos medios, no, ya que ambas muestras son grandes. El contraste de la igualdad de varianzas es el siguiente:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">var.test</span>(Bwt<span class="op">~</span>Sex, <span class="dt">data=</span>cats)</code></pre></div>
<pre><code>## 
##  F test to compare two variances
## 
## data:  Bwt by Sex
## F = 0.3435, num df = 46, denom df = 96, p-value = 0.000116
## alternative hypothesis: true ratio of variances is not equal to 1
## 95 percent confidence interval:
##  0.212628 0.580348
## sample estimates:
## ratio of variances 
##           0.343501</code></pre>
<p>El p-valor es <span class="math inline">\(1.2\times 10^{-4}\)</span>, y por lo tanto podemos rechazar la hipótesis nula de que las varianzas son iguales y concluir que son diferentes. Así que en el test t las consideraremos diferentes.</p>
<p>Recordemos ahora que la hipótesis alternativa que queremos contrastar es <span class="math inline">\(H_{1}:\mu_m&gt;\mu_h\)</span>. En el factor <code>cats$Sex</code>, la F (hembra) va antes que la M (macho), y, por tanto, si entramos los vectores de pesos mediante <code>Bwt~Sex,data=cats</code>, el primer vector corresponderá a las gatas y el segundo a los gatos. Así pues, la hipótesis alternativa que tenemos que especificar es que la media del primer vector es inferior a la del segundo vector: <code>alternative=&quot;less&quot;</code>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">t.test</span>(Bwt<span class="op">~</span>Sex, <span class="dt">data=</span>cats, <span class="dt">alternative=</span><span class="st">&quot;less&quot;</span>,<span class="dt">var.equal=</span><span class="ot">FALSE</span>)</code></pre></div>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  Bwt by Sex
## t = -8.709, df = 136.8, p-value = 4.42e-15
## alternative hypothesis: true difference in means is less than 0
## 95 percent confidence interval:
##       -Inf -0.437666
## sample estimates:
## mean in group F mean in group M 
##         2.35957         2.90000</code></pre>
<p>Como el p-valor es prácticamente 0, podemos concluir que, efectivamente, de media, los gatos adultos pesan más que las gatas adultas.</p>
<p>Hemos insistido en que el test F solo es válido si las dos poblaciones cuyas varianzas comparamos son normales. ¿Qué podemos hacer si dudamos de su normalidad? Usar un test no paramétrico que no presuponga esta hipótesis. Hay diversos tests no paramétricos para realizar contrastes bilaterales de dos varianzas. Aquí os recomendamos el <strong>test de Fligner-Killeen</strong>, implementado en la función <code>fligner.test</code>. Se aplica o bien a una <code>list</code> formada por las dos muestras, o bien a una fórmula que separe un vector numérico en dos muestras por medio de un factor de dos niveles.</p>

<div class="example">
<p><span id="exm:unnamed-chunk-159" class="example"><strong>Ejemplo 5.13  </strong></span>Si queremos contrastar si las varianzas de las longitudes de los sépalos de las flores iris setosa y virginica son iguales o no sin presuponer que siguen leyes normales, podemos usar el test de Fligner-Killeen de la manera siguiente:</p>
</div>

<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">fligner.test</span>(<span class="kw">list</span>(S,V))</code></pre></div>
<pre><code>## 
##  Fligner-Killeen test of homogeneity of variances
## 
## data:  list(S, V)
## Fligner-Killeen:med chi-squared = 9.984, df = 1, p-value = 0.00158</code></pre>
<p>El p-valor es 0.0016, por lo que podemos concluir que las varianzas son diferentes.</p>

<div class="example">
<p><span id="exm:unnamed-chunk-161" class="example"><strong>Ejemplo 5.14  </strong></span>Si queremos contrastar si las varianzas de los pesos de los gatos y las gatas adultos son iguales o no sin presuponer que dichos pesos tienen distribuciones normales, podemos usar el test de Fligner-Killeen de la manera siguiente:</p>
</div>

<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">fligner.test</span>(Bwt<span class="op">~</span>Sex, <span class="dt">data=</span>cats)</code></pre></div>
<pre><code>## 
##  Fligner-Killeen test of homogeneity of variances
## 
## data:  Bwt by Sex
## Fligner-Killeen:med chi-squared = 16.91, df = 1, p-value =
## 3.92e-05</code></pre>
<p>El p-valor es <span class="math inline">\(4\times 10^{-5}\)</span>, por lo que podemos concluir que las varianzas son diferentes.</p>
</div>
<div id="contrastes-para-proporciones" class="section level2">
<h2><span class="header-section-number">5.3</span> Contrastes para proporciones</h2>
<p>Cuando tenemos que efectuar un contraste sobre una probabilidad de éxito <span class="math inline">\(p\)</span> de una variable Bernoulli, podemos emplear el <strong>test binomial exacto</strong>. Este test se basa en que, si la hipótesis nula <span class="math inline">\(H_0: p=p_0\)</span> es verdadera, los números de éxitos en muestras aleatorias simples de tamaño <span class="math inline">\(n\)</span> de la variable poblacional, que será de tipo <span class="math inline">\(Be(p_0)\)</span>, siguen una ley binomial <span class="math inline">\(B(n,p_0)\)</span>. Este test está implementado en la función <code>binom.test</code>, cuya sintaxis es</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">binom.test</span>(x, n, <span class="dt">p=</span>..., <span class="dt">alternative=</span>..., <span class="dt">conf.level=</span>...)</code></pre></div>
<p>donde</p>
<ul>
<li><p><code>x</code> y <code>n</code> son números naturales: el número de éxitos y el tamaño de la muestra.</p></li>
<li><p><code>p</code> es la probabilidad de éxito que queremos contrastar.</p></li>
<li><p>El significado de <code>alternative</code> y <code>conf.level</code>, y sus posibles valores, son los usuales.</p></li>
</ul>
<p>Fijaos en particular que <code>binom.test</code> no se aplica directamente al vector de una muestra, sino a su número de éxitos y a su longitud. Si la muestra es un vector binario <code>X</code>, el número de éxitos será <code>sum(X)</code> y la longitud <code>length(X)</code>.</p>

<div class="remark">
<p> <span class="remark"><em>Nota. </em></span> El intervalo de confianza para la <span class="math inline">\(p\)</span> que da <code>binom.test</code> en un contraste bilateral es el de Clopper-Pearson.</p>
</div>


<div class="example">
<p><span id="exm:unnamed-chunk-165" class="example"><strong>Ejemplo 5.15  </strong></span>Recordemos el Ejemplo <a href="chap-contrastes.html#exm:monedabase">5.1</a>, donde, en una serie de 20 lanzamientos de una moneda, había obtenido 15 caras. ¿Podemos sospechar que la moneda está trucada a favor de cara? Como comentamos en ese ejemplo, si llamamos <span class="math inline">\(p\)</span> a la probabilidad de obtener cara con esta moneda, el contraste que queremos realizar es <span class="math display">\[
\left\{\begin{array}{l}
H_{0}:p=0.5\\
H_{1}:p&gt; 0.5
\end{array}\right.
\]</span> Usaremos la función <code>binom.test</code>:</p>
</div>

<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">binom.test</span>(<span class="dv">15</span>,<span class="dv">20</span>, <span class="dt">p=</span><span class="fl">0.5</span>, <span class="dt">alternative=</span><span class="st">&quot;greater&quot;</span>)</code></pre></div>
<pre><code>## 
##  Exact binomial test
## 
## data:  15 and 20
## number of successes = 15, number of trials = 20, p-value = 0.0207
## alternative hypothesis: true probability of success is greater than 0.5
## 95 percent confidence interval:
##  0.544418 1.000000
## sample estimates:
## probability of success 
##                   0.75</code></pre>
<p>El p-valor del test es 0.0207 y el intervalo de confianza que nos da este test para la <span class="math inline">\(p\)</span> es [0.5444, 1]. Ambos valores coinciden con los dados en el ejemplo original</p>
<p>Cuando la muestra es grande, pongamos de 40 o más sujetos, podemos usar también el <strong>test aproximado</strong>, basado en la aproximación de la distribución de la proporción muestral por medio de una normal dada por el Teorema Central del Límite. En R está implementado en la función <code>prop.test</code>, que además también sirve para contrastar dos proporciones por medio de muestras independientes grandes. Su sintaxis es</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">prop.test</span>(x, n, <span class="dt">p =</span>..., <span class="dt">alternative=</span>..., <span class="dt">conf.level=</span>...)</code></pre></div>
<p>donde:</p>
<ul>
<li><p><code>x</code> puede ser dos cosas:</p>
<ul>
<li>Un número natural: en este caso, R entiende que es el número de éxitos en una muestra.</li>
<li>Un vector de dos números naturales: en este caso, R entiende que es un contraste de dos proporciones y que estos son los números de éxitos en las muestras.</li>
</ul></li>
<li><p>Cuando trabajamos con una sola muestra, <code>n</code> es su tamaño. Cuando estamos trabajando con dos muestras, <code>n</code> es el vector de dos entradas de sus tamaños.</p></li>
<li><p>Cuando trabajamos con una sola muestra, <code>p</code> es la proporción poblacional que contrastamos. En el caso de un contraste de dos muestras, no hay que especificarlo.</p></li>
<li><p>El significado de <code>alternative</code> y <code>conf.level</code>, y sus posibles valores, son los usuales.</p></li>
</ul>
<p>Veamos algunos ejemplos más.</p>

<div class="example">
<p><span id="exm:unnamed-chunk-168" class="example"><strong>Ejemplo 5.16  </strong></span>Queremos contrastar si la proporción de estudiantes zurdos en la UIB es diferente del 10%, el porcentaje estimado de zurdos en España. Es decir, si llamamos <span class="math inline">\(p\)</span> a la proporción de estudiantes zurdos en la UIB, queremos realizar el contraste <span class="math display">\[
\left\{
\begin{array}{l}
H_0:p=0.1\\
H_1:p\neq 0.1
\end{array}
\right.
\]</span> Para ello, tomamos una muestra de 50 estudiantes de la UIB encuestados al azar y resulta que 3 son zurdos. Vamos a suponer que forman una muestra aleatoria simple. Como la muestra es grande (<span class="math inline">\(n=50\)</span>) usaremos la función <code>prop.test</code>.</p>
</div>

<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">prop.test</span>(<span class="dv">3</span>, <span class="dv">50</span>, <span class="dt">p=</span><span class="fl">0.1</span>)</code></pre></div>
<pre><code>## 
##  1-sample proportions test with continuity correction
## 
## data:  3 out of 50, null probability 0.1
## X-squared = 0.5, df = 1, p-value = 0.48
## alternative hypothesis: true p is not equal to 0.1
## 95 percent confidence interval:
##  0.0156246 0.1754187
## sample estimates:
##    p 
## 0.06</code></pre>
<p>El p-valor obtenido en el test es 0.48, muy superior a 0.05. Por lo tanto, no podemos rechazar que un 10% de los estudiantes de la UIB sean zurdos. El intervalo de confianza del 95% para <span class="math inline">\(p\)</span> que hemos obtenido es [0.016, 0.175].</p>
<p>La conclusión usando el test binomial hubiera sido la misma:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">binom.test</span>(<span class="dv">3</span>, <span class="dv">50</span>, <span class="dt">p=</span><span class="fl">0.1</span>)</code></pre></div>
<pre><code>## 
##  Exact binomial test
## 
## data:  3 and 50
## number of successes = 3, number of trials = 50, p-value = 0.48
## alternative hypothesis: true probability of success is not equal to 0.1
## 95 percent confidence interval:
##  0.0125486 0.1654819
## sample estimates:
## probability of success 
##                   0.06</code></pre>
<p>Ya que estamos, comprobemos que el intervalo de confianza del 95% obtenido con <code>binom.test</code> es efectivamente el de Clopper-Pearson:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(epitools)
<span class="kw">binom.exact</span>(<span class="dv">3</span>,<span class="dv">50</span>)</code></pre></div>
<pre><code>##   x  n proportion     lower    upper conf.level
## 1 3 50       0.06 0.0125486 0.165482       0.95</code></pre>

<div class="remark">
<p> <span class="remark"><em>Nota. </em></span> El intervalo de confianza que se obtiene con <code>prop.test</code> en un contraste bilateral es el de Wilson modificado mediante una <strong>corrección de continuidad</strong>, un ajuste que se recomienda realizar cuando una distribución discreta (en este caso, una binomial) se aproxima mediante una distribución continua. En concreto, la fórmula que utiliza <code>prop.test</code> es la que se explica en <a href="https://en.wikipedia.org/wiki/Binomial_proportion_confidence_interval#Wilson_score_interval_with_continuity_correction">esta entrada de la Wikipedia</a>. Podéis indicar que R no efectue esta corrección de continuidad con el parámetro <code>correct=FALSE</code>:</p>
</div>

<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">prop.test</span>(<span class="dv">3</span>, <span class="dv">50</span>, <span class="dt">p=</span><span class="fl">0.1</span>, <span class="dt">correct=</span><span class="ot">FALSE</span>)</code></pre></div>
<pre><code>## 
##  1-sample proportions test without continuity correction
## 
## data:  3 out of 50, null probability 0.1
## X-squared = 0.8889, df = 1, p-value = 0.346
## alternative hypothesis: true p is not equal to 0.1
## 95 percent confidence interval:
##  0.020615 0.162171
## sample estimates:
##    p 
## 0.06</code></pre>
<p>(Observad que sin el <code>correct=FALSE</code>, el encabezamiento del resultado del <code>prop.test</code> es <code>1-sample proportions test with continuity correction</code>, mientras que con <code>correct=FALSE</code> es <code>1-sample proportions test without continuity correction</code>). Comprobemos que el intervalo de confianza del 95% que hemos obtenido ahora sí que es el de Wilson:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">binom.wilson</span>(<span class="dv">3</span>, <span class="dv">50</span>)</code></pre></div>
<pre><code>##   x  n proportion    lower    upper conf.level
## 1 3 50       0.06 0.020615 0.162171       0.95</code></pre>

<div class="example">
<p><span id="exm:trampas1" class="example"><strong>Ejemplo 5.17  </strong></span>Una empresa que fabrica trampas para cucarachas ha producido una nueva versión de su trampa más popular y afirma que la nueva trampa mata más cucarachas que la vieja. Hemos llevado a cabo un experimento para comprobarlo. Hemos situado dos trampas en dos habitaciones. En cada habitación hemos soltado 60 cucarachas. La versión vieja de la trampa ha matado 40 y la nueva, 48. ¿Es suficiente evidencia de que la nueva trampa es más efectiva que la vieja?</p>
</div>

<p>Digamos <span class="math inline">\(p_v\)</span> y <span class="math inline">\(p_n\)</span> a las proporciones de cucarachas que matan la trampa vieja y la trampa nueva, respectivamente. La hipótesis nula será que las trampas de los dos tipos son igual de efectivas, <span class="math inline">\(H_0:p_v=p_n\)</span>, y la hipótesis alternativa que las trampas nuevas son más efectivas que las viejas, <span class="math inline">\(H_1:p_v&lt;p_n\)</span>. Los tamaños de las muestras nos permiten usar la función <code>prop.test</code>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">prop.test</span>(<span class="kw">c</span>(<span class="dv">40</span>,<span class="dv">48</span>),<span class="kw">c</span>(<span class="dv">60</span>,<span class="dv">60</span>),<span class="dt">alternative=</span><span class="st">&quot;less&quot;</span>)</code></pre></div>
<pre><code>## 
##  2-sample test for equality of proportions with continuity
##  correction
## 
## data:  c(40, 48) out of c(60, 60)
## X-squared = 2.088, df = 1, p-value = 0.0742
## alternative hypothesis: less
## 95 percent confidence interval:
##  -1.0000000  0.0146167
## sample estimates:
##   prop 1   prop 2 
## 0.666667 0.800000</code></pre>
<p>El p-valor es 0.074, y el intervalo de confianza que nos da el test, [-1, 0.015], es para la diferencia de proporciones <span class="math inline">\(p_v-p_n\)</span> y contiene el 0, aunque por poco. En resumen, a un nivel de significación de 0.05 no encontramos evidencia de que la trampa nueva sea mejor que la vieja, pero el resultado no es del todo concluyente y convendría llevar a cabo otro experimento con más cucarachas para aumentar la potencia (cf. Ejemplo <a href="chap-contrastes.html#exm:trampas1bis">5.23</a> en la próxima sección).</p>
<p>La función <code>prop.test</code> solo sirve para contrastar dos proporciones cuando las dos muestras son independientes y grandes. Un test que se puede usar siempre para contrastar dos proporciones usando muestras independientes es el <strong>test exacto de Fisher</strong>, que usa una distribución hipergeométrica.</p>
<p>Supongamos que evaluamos una característica dicotómica (es decir, que solo puede tomar dos valores y por tanto define distribuciones de Bernoulli) sobre dos poblaciones y tomamos dos muestras independientes, una de cada población. Resumimos los resultados en una tabla como la que sigue:</p>
<p><span class="math display">\[
\begin{array}{r|c}
 &amp; \quad\mbox{Población}\quad \\
\mbox{Característica} &amp;\quad 1 \qquad 2\quad \\\hline
 \mbox{Sí} &amp;\quad a  \qquad b\quad \\
 \mbox{No} &amp;\quad c  \qquad d\quad
\end{array}
\]</span></p>
<p>Llamemos <span class="math inline">\(p_{1}\)</span> a la proporción de individuos con la característica bajo estudio en la población 1 y <span class="math inline">\(p_{2}\)</span> a su proporción en la población 2. Queremos contrastar la hipótesis nula <span class="math inline">\(H_{0}:p_1=p_2\)</span> contra alguna hipótesis alternativa. Por ejemplo, en el experimento de las trampas para cucarachas, las poblaciones vendrían definidas por el tipo de trampa, y la característica que tendríamos en cuenta sería si la cucaracha ha muerto o no, lo que nos daría la tabla siguiente:</p>
<p><span class="math display">\[
\begin{array}{r|c}
 &amp; \qquad\mbox{Trampas}\quad \\
&amp;\quad \mbox{Viejas}\qquad \mbox{Nuevas}\\\hline
 \mbox{Muertas} &amp;\qquad 40  \qquad\qquad 48\quad \\
 \mbox{Vivas} &amp;\qquad 20  \qquad\qquad 12\quad
 \end{array}
\]</span></p>
<p>El test exacto de Fisher está implementado en la función <code>fisher.test</code>. Su sintaxis es</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">fisher.test</span>(x, <span class="dt">alternative=</span>..., <span class="dt">conf.level=</span>...)</code></pre></div>
<p>donde</p>
<ul>
<li><p><code>x</code> es la matriz <span class="math inline">\(\left(\begin{array}{cc} a &amp; b\\ c &amp; d\end{array}\right)\)</span>, en la que los números de éxitos van en la primera fila y los de fracasos en la segunda, y las poblaciones se ordenan por columnas.</p></li>
<li><p>El significado de <code>alternative</code> y <code>conf.level</code>, y sus posibles valores, son los usuales.</p></li>
</ul>
<p>Así, en el ejemplo de las trampas para cucarachas, entraríamos:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">Datos=<span class="kw">rbind</span>(<span class="kw">c</span>(<span class="dv">40</span>,<span class="dv">48</span>),<span class="kw">c</span>(<span class="dv">20</span>,<span class="dv">12</span>))
Datos</code></pre></div>
<pre><code>##      [,1] [,2]
## [1,]   40   48
## [2,]   20   12</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">fisher.test</span>(Datos, <span class="dt">alternative=</span><span class="st">&quot;less&quot;</span>)</code></pre></div>
<pre><code>## 
##  Fisher&#39;s Exact Test for Count Data
## 
## data:  Datos
## p-value = 0.0739
## alternative hypothesis: true odds ratio is less than 1
## 95 percent confidence interval:
##  0.00000 1.08414
## sample estimates:
## odds ratio 
##   0.502909</code></pre>
<p>y obtenemos de nuevo un p-valor cercano a 0.074.</p>
<p>Hay que ir con cuidado con la interpretación del intervalo de confianza que da esta función: no es ni para la diferencia de las proporciones ni para su cociente, sino para su <strong>odds ratio</strong>: el cociente <span class="math display">\[
\Big({\frac{p_v}{1-p_v}}\Big)\Big/\Big({\frac{p_n}{1-p_n}}\Big).
\]</span></p>
<p>Recordad que si la probabilidad de un suceso <span class="math inline">\(A\)</span> es <span class="math inline">\(P(A)\)</span>, sus <strong>odds</strong> son el cociente <span class="math display">\[
\mbox{Odds}(A)=\frac{P(A)}{1-P(A)}
\]</span> que mide cuántas veces es más probable <span class="math inline">\(A\)</span> que su contrario. Las <em>odds</em> son una función creciente de la probabilidad, y por lo tanto <span class="math display">\[
\mbox{Odds}(A)&lt;\mbox{Odds}(B)\Longleftrightarrow P(A)&lt;P(B).
\]</span> Esto permite comparar <em>odds</em> en vez de probabilidades, con la misma conclusión. Por ejemplo, en nuestro caso, como el intervalo de confianza para la <em>odds ratio</em> va de 0 a 1.084, en particular contiene el 1, por lo que no podemos rechazar que <span class="math display">\[
\Big({\frac{p_v}{1-p_v}}\Big)\Big/\Big({\frac{p_n}{1-p_n}}\Big)=1,
\]</span> es decir, no podemos rechazar que <span class="math display">\[
\frac{p_v}{1-p_v}=\frac{p_n}{1-p_n}
\]</span> y esto es equivalente a <span class="math inline">\(p_v=p_n\)</span>. Si, por ejemplo, el intervalo de confianza hubiera ido de 0 a 0.8, entonces la conclusión a este nivel de confianza hubiera sido que <span class="math display">\[
\Big({\frac{p_v}{1-p_v}}\Big)\Big/\Big({\frac{p_n}{1-p_n}}\Big)&lt;1
\]</span> es decir, que <span class="math display">\[
\frac{p_v}{1-p_v}&lt;\frac{p_n}{1-p_n}
\]</span> y esto es equivalente a <span class="math inline">\(p_v&lt;p_n\)</span>.</p>

<div class="example">
<span id="exm:unnamed-chunk-178" class="example"><strong>Ejemplo 5.18  </strong></span>Para determinar si el Síndrome de Muerte Súbita del Recién Nacido (<em>SIDS</em>, por sus siglas en inglés) tiene algún componente genético, se estudiaron parejas de gemelos y mellizos en las que se dio algún caso de SIDS. Sean <span class="math inline">\(p_1\)</span> la proporción de casos con exactamente una muerte por SIDS entre las parejas de gemelos con algún caso de SIDS, y <span class="math inline">\(p_2\)</span> la proporción de casos con exactamente una muerte por SIDS entre las parejas de mellizos con algún caso de SIDS. La hipótesis de trabajo es que si el SIDS tiene componente genético, será más probable que un gemelo de un muerto por SIDS también lo sufra que si solo es mellizo, y por lo tanto que en las parejas de gemelos ha de ser más raro que haya exactamente un caso de SIDS que en las parejas de mellizos. Es decir, que <span class="math inline">\(p_1&lt;p_2\)</span>. Así pues, queremos realizar el contraste <span class="math display">\[
\left\{\begin{array}{l}
H_0:p_1=p_2\\
H_1:p_1&lt; p_2
\end{array}\right.
\]</span>
</div>

<p>En un estudio se obtuvieron los datos siguientes:</p>
<p><span class="math display">\[
\begin{array}{r|c}
 &amp; \ \mbox{Tipo de gemelos}\  \\
\mbox{Casos de SIDS} &amp;\ \mbox{Gemelos}\qquad \mbox{Mellizos}\\\hline
\mbox{Uno} &amp; \quad\  23 \qquad\quad\quad\quad \ 35\quad  \\
 \mbox{Dos} &amp; \quad\  1  \quad\quad\qquad\quad \ \hphantom{3}  2 \quad
 \end{array}
\]</span></p>
<p>Vamos a realizar el contraste. Observad que damos la tabla de manera que <span class="math inline">\(p_1\)</span> es la proporción de parejas con un solo caso de SIDS entre las de la población 1 (gemelos), y <span class="math inline">\(p_{2}\)</span> es la proporción de parejas con un solo caso de SIDS entre las de la población 2 (mellizos). Por tanto hemos de aplicar <code>fisher.test</code> a esta matriz y <span class="math inline">\(p_1&lt;p_2\)</span> corresponderá a <code>alternative=&quot;less&quot;</code>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">Datos=<span class="kw">rbind</span>(<span class="kw">c</span>(<span class="dv">23</span>,<span class="dv">35</span>),<span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">2</span>))
Datos</code></pre></div>
<pre><code>##      [,1] [,2]
## [1,]   23   35
## [2,]    1    2</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">fisher.test</span>(Datos, <span class="dt">alternative=</span><span class="st">&quot;less&quot;</span>)</code></pre></div>
<pre><code>## 
##  Fisher&#39;s Exact Test for Count Data
## 
## data:  Datos
## p-value = 0.784
## alternative hypothesis: true odds ratio is less than 1
## 95 percent confidence interval:
##   0.0000 39.7395
## sample estimates:
## odds ratio 
##    1.30859</code></pre>
<p>El p-valor es 0.784, muy grande, por lo que no obtenemos evidencia de componente genético en el SIDS.</p>
<p>Supongamos ahora que queremos comparar dos proporciones usando muestras emparejadas. Por ejemplo, supongamos que evaluamos dos características dicotómicas sobre una misma muestra de <span class="math inline">\(n\)</span> sujetos. Resumimos los resultados obtenidos en la tabla siguiente:</p>
<p><span class="math display">\[
\begin{array}{r|c}
 &amp; \ \mbox{Característica 1}\  \\
\mbox{Característica 2} &amp;\ \ \, \mbox{Sí}\qquad \mbox{No}\\\hline
 \mbox{Sí} &amp; \quad\ \  a \qquad \ \ \, b\quad  \\
 \mbox{No} &amp; \quad\ \   c  \qquad \ \ \, d\quad
 \end{array}
\]</span></p>
<p>donde <span class="math inline">\(a+b+c+d=n\)</span>. Esta tabla quiere decir, naturalmente, que <span class="math inline">\(a\)</span> sujetos de la muestra tuvieron la característica 1 y la característica 2, que <span class="math inline">\(b\)</span> sujetos de la muestra tuvieron la característica 2 pero no tuvieron la característica 1, etc.</p>
<p>Vamos a llamar <span class="math inline">\(p_{1}\)</span> a la proporción poblacional de individuos con la característica 1, y <span class="math inline">\(p_{2}\)</span> a la proporción poblacional de individuos con la característica 2. Queremos contrastar la hipótesis nula <span class="math inline">\(H_{0}:p_1=p_2\)</span> contra alguna hipótesis alternativa. En este caso, no pueden usarse las funciones <code>prop.test</code> o <code>fisher.test</code>. Tenemos dos soluciones posibles.</p>
<p>La primera nos permite realizar el contraste bilateral <span class="math display">\[
\left\{\begin{array}{l}
H_{0}:p_1=p_2\\
H_{1}:p_1\neq p_2
\end{array}\right.
\]</span> cuando <span class="math inline">\(n\)</span> es grande (digamos que <span class="math inline">\(n{\geqslant}100\)</span>) y el número <span class="math inline">\(b+c\)</span> de <strong>casos discordantes</strong> (en los que una característica da Sí y la otra da No) es razonablemente grande, pongamos <span class="math inline">\({\geqslant}20\)</span>. En esta situación podemos usar el <strong>test de McNemar</strong>, que se lleva a cabo en R con la instrucción <code>mcnemar.test</code>. Su sintaxis básica es</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">mcnemar.test</span>(X)</code></pre></div>
<p>donde <code>X</code> es la matriz <span class="math inline">\(\left(\begin{array}{cc} a &amp; b\\ c&amp; d \end{array}\right)\)</span> que corresponde a la tabla anterior.</p>

<div class="example">
<p><span id="exm:asma1" class="example"><strong>Ejemplo 5.19  </strong></span>Para comparar la efectividad de dos tratamientos del asma, se escogieron 200 pacientes con asma severo, y a cada uno se le trató durante un mes con el tratamiento A o el tratamiento B, decidiéndose cada tratamiento al azar; tras esta fase de tratamiento, se les dejó sin tratamiento durante un mes, y a continuación a cada uno se le trató durante un mes con el otro tratamiento (B si antes había recibido A, A si antes había recibido B). Se anotó si durante cada periodo de tratamiento cada enfermo visitó o no el servicio de urgencias por dificultades respiratorias. Los resultados del experimento se resumen en la tabla siguiente (“Sí” significa que sí que acudió a urgencias por dificultades respiratorias):</p>
</div>

<p><span class="math display">\[
\begin{array}{r|c}
 &amp; \ \mbox{Tratamiento A}\  \\
\mbox{Trat. B} &amp;\quad \ \mbox{ Sí}\qquad\quad \mbox{No}\quad \\\hline
 \mbox{Sí} &amp; \quad \  71 \qquad\quad    48\quad  \\
 \mbox{No} &amp; \quad \   30  \qquad\quad   51\quad
 \end{array}
\]</span></p>
<p>Queremos determinar si hay diferencia en la efectividad de los dos tratamientos. Para ello, entramos la tabla anterior en una matriz y le aplicamos la función <code>mcnemar.test</code>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">Datos=<span class="kw">matrix</span>(<span class="kw">c</span>(<span class="dv">71</span>,<span class="dv">48</span>,<span class="dv">30</span>,<span class="dv">51</span>),<span class="dt">nrow=</span><span class="dv">2</span>,<span class="dt">byrow=</span><span class="ot">TRUE</span>)
Datos</code></pre></div>
<pre><code>##      [,1] [,2]
## [1,]   71   48
## [2,]   30   51</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">mcnemar.test</span>(Datos)</code></pre></div>
<pre><code>## 
##  McNemar&#39;s Chi-squared test with continuity correction
## 
## data:  Datos
## McNemar&#39;s chi-squared = 3.705, df = 1, p-value = 0.0542</code></pre>
<p>El p-valor del test es 0.054, ligeramente superior a 0.05, por lo tanto no permite concluir a un nivel de significación del 5% que haya evidencia de que la efectividad de los dos tratamientos sea diferente, pero sería conveniente llevar a cabo un estudio más amplio.</p>
<p>Otra posibilidad para realizar un contraste de dos proporciones usando muestras emparejadas, que no requiere de ninguna hipótesis sobre los tamaños de las muestras, es usar de manera adecuada la función <code>binom.test</code>. Para explicar este método, consideremos la tabla siguiente, donde ahora damos las probabilidades poblacionales de las cuatro combinaciones de resultados: <span class="math display">\[
\begin{array}{r|c}
 &amp; \ \mbox{Característica 1}\  \\
\mbox{Característica 2} &amp;\quad \ \!\mbox{Sí}\qquad\quad\, \mbox{No}\quad \\\hline
 \mbox{Sí} &amp; \quad \  p_{11}  \qquad\quad p_{01}\quad  \\
 \mbox{No} &amp; \quad \  p_{10} \qquad\quad  p_{00}\quad
 \end{array}
\]</span></p>
<p>De esta manera <span class="math inline">\(p_1=p_{11}+p_{10}\)</span> y <span class="math inline">\(p_2=p_{11}+p_{01}\)</span>. Entonces, <span class="math inline">\(p_1=p_2\)</span> es equivalente a <span class="math inline">\(p_{10}=p_{01}\)</span> y cualquier hipótesis alternativa se traduce en la misma desigualdad, pero para <span class="math inline">\(p_{10}\)</span> y <span class="math inline">\(p_{01}\)</span>: <span class="math inline">\(p_1\neq p_2\)</span> es equivalente a <span class="math inline">\(p_{10}\neq p_{01}\)</span>; <span class="math inline">\(p_1&lt; p_2\)</span> es equivalente a <span class="math inline">\(p_{10}&lt; p_{01}\)</span>; y <span class="math inline">\(p_1&gt; p_2\)</span> es equivalente a <span class="math inline">\(p_{10}&gt; p_{01}\)</span>. Por lo tanto podemos traducir el contraste sobre <span class="math inline">\(p_1\)</span> y <span class="math inline">\(p_2\)</span> al mismo contraste sobre <span class="math inline">\(p_{10}\)</span> y <span class="math inline">\(p_{01}\)</span>. La gracia ahora está en que si la hipótesis nula <span class="math inline">\(p_{10}=p_{01}\)</span> es cierta, entonces, en el total de casos discordantes, el número de sujetos en los que la característica 1 da Sí y la característica 2 da No sigue una ley binomial con <span class="math inline">\(p=0.5\)</span>. Por lo tanto, podemos efectuar el contraste usando un test binomial exacto tomando como muestra los casos discordantes de nuestra muestra, de tamaño <span class="math inline">\(b+c\)</span>, como éxitos los sujetos que han dado Sí en la característica 1 y No en la característica 2, de tamaño <span class="math inline">\(c\)</span>, con proporción a contrastar <span class="math inline">\(p=0.5\)</span> y con hipótesis alternativa la que corresponda. La ventaja de este test es que su validez no requiere de ninguna hipótesis sobre los tamaños de las muestras. El inconveniente es que el intervalo de confianza que nos dará será para <span class="math inline">\(p_{10}/(p_{10}+p_{01})\)</span>, y no permite obtener un intervalo de confianza para la diferencia o el cociente de las probabilidades <span class="math inline">\(p_1\)</span> y <span class="math inline">\(p_2\)</span> de interés.</p>

<div class="example">
<p><span id="exm:unnamed-chunk-182" class="example"><strong>Ejemplo 5.20  </strong></span>Usemos el test binomial para llevar a cabo el contraste bilateral del Ejemplo <a href="chap-contrastes.html#exm:asma1">5.19</a>. Habíamos obtenido 30+48=78 casos discordantes, de los que 48 eran casos en los que el tratamiento A había dado Sí y el tratamiento B había dado No.</p>
</div>

<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">binom.test</span>(<span class="dv">48</span>, <span class="dv">78</span>, <span class="dt">p=</span><span class="fl">0.5</span>)</code></pre></div>
<pre><code>## 
##  Exact binomial test
## 
## data:  48 and 78
## number of successes = 48, number of trials = 78, p-value = 0.0535
## alternative hypothesis: true probability of success is not equal to 0.5
## 95 percent confidence interval:
##  0.498331 0.723398
## sample estimates:
## probability of success 
##               0.615385</code></pre>
<p>Obtenemos de nuevo un p-valor en la zona de penumbra, ligeramente superior a 0.05.</p>

<div class="example">
<span id="exm:unnamed-chunk-184" class="example"><strong>Ejemplo 5.21  </strong></span>Para determinar si un test casero de VIH basado en un frotis bucal da más positivos (que seguramente serán falsos positivos) que el test de VIH de referencia, basado en una analítica de sangre que detecta la presencia del virus, se tomó una muestra aleatoria de 241 individuos en situación de riesgo, y a todos se les realizaron ambos tests. Los resultados se resumen en la tabla siguiente:
</div>

<p><span class="math display">\[
\begin{array}{r|c}
 &amp; \ \mbox{Test estándar}\  \\
\mbox{Test casero}   &amp;\quad \ \mbox{ Positivo}\qquad\quad \quad \mbox{Negativo}\quad \\\hline
 \mbox{Positivo} &amp; \quad\ \  72  \qquad\qquad\qquad\    10 \quad  \\
 \mbox{Negativo} &amp; \quad\quad   2 \qquad\qquad\quad\quad \  157  \quad
 \end{array}
\]</span></p>
<p>Si llamamos <span class="math inline">\(p_{c}\)</span> a la probabilidad de que el test casero dé positivo y <span class="math inline">\(p_{e}\)</span> a la probabilidad de que el test estándar dé positivo, queremos realizar el contraste <span class="math display">\[
\left\{\begin{array}{l}
H_{0}:p_{e}=p_{c}\\
H_{1}:p_{e}&lt; p_{c}
\end{array}\right.
\]</span></p>
<p>El número de casos discordantes es pequeño (10+2=12) y además el test es unilateral, así que usaremos el test binomial. Como queremos realizar un contraste unilateral, hay que pensar en cómo traducir la hipótesis alternativa en términos de una hipótesis sobre la probabilidad <span class="math inline">\(p=p_{10}/(p_{10}+p_{01})\)</span> de que un caso discordante tenga la característica 1 (la de las columnas). Veamos, <span class="math inline">\(p_{e}&lt; p_{c}\)</span> significa que la característica de las columnas es menos probable que la de las filas, por tanto se ha de traducir en que la probabilidad de tener la característica de las columnas y no la de las filas es más pequeña que la probabilidad de tener la característica de las filas y no la de las columnas, es decir, en que <span class="math inline">\(p&lt;0.5\)</span>: hemos de usar <code>alternative=less</code>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">binom.test</span>(<span class="dv">2</span>, <span class="dv">12</span>, <span class="dt">alternative=</span><span class="st">&quot;less&quot;</span>, <span class="dt">p=</span><span class="fl">0.5</span>)</code></pre></div>
<pre><code>## 
##  Exact binomial test
## 
## data:  2 and 12
## number of successes = 2, number of trials = 12, p-value = 0.0193
## alternative hypothesis: true probability of success is less than 0.5
## 95 percent confidence interval:
##  0.000000 0.438105
## sample estimates:
## probability of success 
##               0.166667</code></pre>
<p>Obtenemos evidencia significativa de que, efectivamente, el test casero da positivo con mayor frecuencia que el de referencia.</p>
</div>
<div id="calculo-de-la-potencia-de-un-contraste" class="section level2">
<h2><span class="header-section-number">5.4</span> Cálculo de la potencia de un contraste</h2>
<p>Recordemos que la <strong>potencia</strong> de un contraste de hipótesis es la probabilidad de no cometer un <strong>error de tipo II</strong>, es decir, la probabilidad de aceptar la hipótesis alternativa si es verdadera. Usualmente, la probabilidad de cometer un error de tipo II se denota por <span class="math inline">\(\beta\)</span>, y por lo tanto la potencia es <span class="math inline">\(1-\beta\)</span>.</p>
<p>La potencia de un contraste está relacionada con lo que se llama la <strong>magnitud del efecto</strong> (<em>effect size</em>). En un contraste, el <strong>efecto</strong> es la diferencia entre el valor estimado del parámetro a partir de la muestra usada y el valor que se da a dicho parámetro como hipótesis nula: por ejemplo, en el contraste de una media, la diferencia entre la media muestral <span class="math inline">\(\overline{x}\)</span> y el valor contrastado <span class="math inline">\(\mu_0\)</span>; o, en el contraste de dos medias, la diferencia entre las dos medias muestrales. Se rechaza entonces la hipótesis nula si el efecto observado es tan grande que es muy improbable cuando la hipótesis nula es verdadera. Pero recordad que, en realidad, no se tiene en cuenta si el efecto observado ha sido grande o no por si mismo, solo si es estadísticamente significativo, es decir, si es improbable cuando la hipótesis nula es verdadera. Entonces, sin entrar en detalle, digamos que la <strong>magnitud del efecto</strong> es una medida estadística específica del tamaño del efecto observado respecto de su valor esperado si la hipótesis nula es verdadera. La fórmula para calcular la magnitud del efecto depende del contraste y del estadístico usado.</p>
<p>Para cada tipo de test se han consensuado unos valores de la magnitud del efecto considerados como “pequeño”, “medio” y “grande”. Estos valores se obtienen con R con la función <code>cohen.ES</code> del paquete <strong>pwr</strong>. Su sintaxis básica es</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">cohen.ES</span>(<span class="dt">test=</span>..., <span class="dt">size=</span>...)</code></pre></div>
<p>donde:</p>
<ul>
<li><p>el parámetro <code>test</code> sirve para indicar el tipo de test: por ejemplo, <code>test=&quot;t&quot;</code> para un test t usando <code>t.test</code>, o <code>test=&quot;p&quot;</code> para un test aproximado de proporciones usando <code>prop.test</code>;</p></li>
<li><p>el parámetro <code>size</code> sirve para indicar la magnitud esperada: <code>&quot;small&quot;</code>, <code>&quot;medium&quot;</code> o <code>&quot;large&quot;</code>.</p></li>
</ul>
<p>A modo de ejemplo, la siguiente instrucción nos da la magnitud de efecto que se considera pequeña en un test t:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(pwr)
<span class="kw">cohen.ES</span>(<span class="dt">test=</span><span class="st">&quot;t&quot;</span>,<span class="dt">size=</span><span class="st">&quot;small&quot;</span>)</code></pre></div>
<pre><code>## 
##      Conventional effect size from Cohen (1982) 
## 
##            test = t
##            size = small
##     effect.size = 0.2</code></pre>
<p>De manera similar, para saber la magnitud de efecto que se considera media en un test aproximado de proporciones podemos usar instrucción siguiente:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">cohen.ES</span>(<span class="dt">test=</span><span class="st">&quot;p&quot;</span>,<span class="dt">size=</span><span class="st">&quot;medium&quot;</span>)</code></pre></div>
<pre><code>## 
##      Conventional effect size from Cohen (1982) 
## 
##            test = p
##            size = medium
##     effect.size = 0.5</code></pre>
<p>Si se desea solo el valor de la magnitud del efecto, para poderlo entrar en otras funciones, se obtiene con el sufijo <code>$effect.size</code>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">cohen.ES</span>(<span class="dt">test=</span><span class="st">&quot;p&quot;</span>,<span class="dt">size=</span><span class="st">&quot;medium&quot;</span>)<span class="op">$</span>effect.size</code></pre></div>
<pre><code>## [1] 0.5</code></pre>
<p>Así pues, en un contraste de hipótesis intervienen cuatro cantidades fundamentales: el <strong>tamaño</strong> de la muestra, <span class="math inline">\(n\)</span>; el <strong>nivel de significación</strong>, <span class="math inline">\(\alpha\)</span>; la <strong>potencia</strong>, <span class="math inline">\(1-\beta\)</span>; y la <strong>magnitud del efecto</strong>. El tamaño de la muestra y el nivel de significación están bajo el control del investigador; sin embargo, la potencia del contraste y la magnitud del efecto afectan al contraste de forma más indirecta y su control escapa al investigador. Por ejemplo, si incrementamos el tamaño de la muestra, la potencia aumenta, pero el aumento preciso depende de la magnitud del efecto esperada. De hecho, las cuatro cantidades anteriores no son independientes, sino que, a partir de tres cualesquiera de ellas, se puede calcular la cuarta. Las funciones del paquete <strong>pwr</strong> permiten realizar estos cálculos para los contrastes de medias y proporciones.</p>
<p>Las funciones de dicho paquete que por ahora nos interesan en este sentido son las siguientes:</p>
<ul>
<li><p><code>pwr.t.test</code>, para utilizar en tests t de una media, de dos medias usando muestras emparejadas o de dos medias usando muestras independientes del mismo tamaño.</p></li>
<li><p><code>pwr.t2n.test</code>, para utilizar en tests t de dos medias usando muestras independientes de distinto tamaño.</p></li>
<li><p><code>pwr.p.test</code>, para utilizar en contrastes aproximados de una proporción.</p></li>
<li><p><code>pwr.2p.test</code>, para utilizar en contrastes aproximados de dos proporciones usando muestras independientes del mismo tamaño.</p></li>
<li><p><code>pwr.2p2n.test</code>, para utilizar en contrastes aproximados de dos proporciones usando muestras de distinto tamaño.</p></li>
</ul>
<p>Estas funciones tienen los parámetros básicos siguientes:</p>
<ul>
<li><p><code>n</code>: el tamaño de la muestra (o de las muestras cuando son del mismo tamaño).</p></li>
<li><p><code>n1</code> y <code>n2</code>: los tamaños de las dos muestras en <code>pwr.2p2n.test</code> y <code>pwr.t2n.test</code>.</p></li>
<li><p><code>d</code> (en las dos primeras) o <code>h</code> (en las tres últimas): la magnitud del efecto.</p></li>
<li><p><code>sig.level</code>: el nivel de significación.</p></li>
<li><p><code>power</code>: la potencia.</p></li>
<li><p><code>type</code> (en la primera): el tipo de muestras usado, siendo sus posibles valores <code>&quot;one.sample&quot;</code> (para contrastes de una muestra), <code>&quot;two.sample&quot;</code> (para contrastes de dos muestras independientes), o <code>&quot;paired&quot;</code> (para contrastes de dos muestras emparejadas).</p></li>
<li><p><code>alternative</code>: el tipo de hipótesis alternativa, con sus valores usuales.</p></li>
</ul>
<p>Si, en una cualquiera de estas funciones se especifican todos los parámetros <code>n</code> (o <code>n1</code> y <code>n2</code>), <code>d</code> (o <code>h</code>), <code>sig.level</code> y <code>power</code> menos uno, la función da el valor del parámetro que falta.</p>
<p>Veamos algunos ejemplos de uso.</p>

<div class="example">
<p><span id="exm:norm1bispot" class="example"><strong>Ejemplo 5.22  </strong></span>Queremos calcular la potencia del contraste llevado a cabo en el Ejemplo <a href="chap-contrastes.html#exm:norm1bis">5.2</a>. Se trataba de un contraste bilateral de una media usando un test t, por lo que utilizaremos la función <code>pwr.t.test</code>. Los parámetros que le entraremos son:</p>
</div>

<ul>
<li><p><code>n</code>, el tamaño de la muestra; en este ejemplo, <span class="math inline">\(n=25\)</span>.</p></li>
<li><p><code>d</code>, la magnitud del efecto. Para tests t de una media e hipótesis nula <span class="math inline">\(H_0: \mu = \mu_0\)</span>, la magnitud del efecto se calcula con la fórmula <span class="math display">\[
d=\frac{|\overline{x}-\mu_0|}{\widetilde{s}_x}.
\]</span> En nuestro ejemplo, <span class="math inline">\(d=\frac{|2.8048-2|}{0.68064}= 1.1824\)</span>.</p></li>
<li><p><code>sig.level</code>, el nivel de significación; en este ejemplo, <span class="math inline">\(\alpha=0.05\)</span>.</p></li>
</ul>
<p>Además como es un contraste bliateral de una media, especificaremos <code>type=&quot;one.sample&quot;</code> y <code>alternative=&quot;two.sided&quot;</code> (esto último en realidad no hace falta: como siempre, este es su valor por defecto).</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x=<span class="kw">c</span>(<span class="fl">2.2</span>,<span class="fl">2.66</span>,<span class="fl">2.74</span>,<span class="fl">3.41</span>,<span class="fl">2.46</span>,<span class="fl">2.96</span>,<span class="fl">3.34</span>,<span class="fl">2.16</span>,<span class="fl">2.46</span>,<span class="fl">2.71</span>,<span class="fl">2.04</span>,<span class="fl">3.74</span>,<span class="fl">3.24</span>,
  <span class="fl">3.92</span>,<span class="fl">2.38</span>,<span class="fl">2.82</span>,<span class="fl">2.2</span>,<span class="fl">2.42</span>,<span class="fl">2.82</span>,<span class="fl">2.84</span>,<span class="fl">4.22</span>,<span class="fl">3.64</span>,<span class="fl">1.77</span>,<span class="fl">3.44</span>,<span class="fl">1.53</span>)
mag.ef=<span class="kw">abs</span>(<span class="kw">mean</span>(x)<span class="op">-</span><span class="dv">2</span>)<span class="op">/</span><span class="kw">sd</span>(x) <span class="co">#Magnitud del efecto</span>
<span class="kw">pwr.t.test</span>(<span class="dt">n=</span><span class="dv">25</span>, <span class="dt">d=</span>mag.ef, <span class="dt">sig.level=</span><span class="fl">0.05</span>, <span class="dt">type=</span><span class="st">&quot;one.sample&quot;</span>, <span class="dt">alternative=</span><span class="st">&quot;two.sided&quot;</span>)</code></pre></div>
<pre><code>## 
##      One-sample t test power calculation 
## 
##               n = 25
##               d = 1.18241
##       sig.level = 0.05
##           power = 0.999893
##     alternative = two.sided</code></pre>
<p>Obtenemos que la potencia del test es prácticamente 1.</p>
<p>Si estuviéramos diseñando el experimento y quisiéramos calcular el tamaño mínimo de una muestra para tener un nivel de significación del 5% y potencia del 99%, suponiendo <em>a priori</em> que la magnitud del efecto esperado va a ser grande (y que por lo tanto detectar que la hipótesis alternativa es verdadera va a ser fácil), primero calcularíamos cuánto vale una magnitud del efecto grande:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">cohen.ES</span>(<span class="dt">test=</span><span class="st">&quot;t&quot;</span>,<span class="dt">size=</span><span class="st">&quot;large&quot;</span>)<span class="op">$</span>effect.size</code></pre></div>
<pre><code>## [1] 0.8</code></pre>
<p>y a continuación la usaríamos en la función <code>pwr.t.test</code>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">pwr.t.test</span>(<span class="dt">d=</span><span class="fl">0.8</span>, <span class="dt">sig.level=</span><span class="fl">0.05</span>, <span class="dt">power=</span><span class="fl">0.99</span>, <span class="dt">type=</span><span class="st">&quot;one.sample&quot;</span>)</code></pre></div>
<pre><code>## 
##      One-sample t test power calculation 
## 
##               n = 30.7143
##               d = 0.8
##       sig.level = 0.05
##           power = 0.99
##     alternative = two.sided</code></pre>
<p>Bastarían 31 observaciones para tener la potencia deseada. Si en cambio esperáramos una magnitud del efecto pequeña:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">pwr.t.test</span>(<span class="dt">d=</span><span class="kw">cohen.ES</span>(<span class="dt">test=</span><span class="st">&quot;t&quot;</span>,<span class="dt">size=</span><span class="st">&quot;small&quot;</span>)<span class="op">$</span>effect.size,
           <span class="dt">sig.level=</span><span class="fl">0.05</span>, <span class="dt">power=</span><span class="fl">0.99</span>, <span class="dt">type=</span><span class="st">&quot;one.sample&quot;</span>)</code></pre></div>
<pre><code>## 
##      One-sample t test power calculation 
## 
##               n = 461.238
##               d = 0.2
##       sig.level = 0.05
##           power = 0.99
##     alternative = two.sided</code></pre>
<p>En este caso necesitaríamos 462 observaciones.</p>
<p>Podemos obtener solo una de las componentes del resultado de una de estas funciones añadiéndole el sufijo adecuado. Por ejemplo, la potencia se obtiene con el sufijo <code>$power</code> y el valor de <span class="math inline">\(n\)</span> con el sufijo <code>$n</code>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">pwr.t.test</span>(<span class="dt">n=</span><span class="dv">25</span>, <span class="dt">d=</span>mag.ef, <span class="dt">sig.level=</span><span class="fl">0.05</span>, <span class="dt">type=</span><span class="st">&quot;one.sample&quot;</span>, <span class="dt">alternative=</span><span class="st">&quot;two.sided&quot;</span>)<span class="op">$</span>power</code></pre></div>
<pre><code>## [1] 0.999893</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">pwr.t.test</span>(<span class="dt">d=</span><span class="fl">0.8</span>, <span class="dt">sig.level=</span><span class="fl">0.05</span>, <span class="dt">power=</span><span class="fl">0.99</span>, <span class="dt">type=</span><span class="st">&quot;one.sample&quot;</span>)<span class="op">$</span>n</code></pre></div>
<pre><code>## [1] 30.7143</code></pre>

<div class="example">
<p><span id="exm:trampas1bis" class="example"><strong>Ejemplo 5.23  </strong></span>Vamos a calcular la potencia del contraste</p>
</div>

<p><span class="math display">\[
\left\{
\begin{array}{l} 
 H_0:p_v=p_n\\
 H_1:p_v&lt;p_n
 \end{array}
 \right.
\]</span></p>
<p>del Ejemplo <a href="chap-contrastes.html#exm:trampas1">5.17</a>. En este caso, usamos la función <code>pwr.2p.test</code>, ya que usamos dos muestras del mismo tamaño, y le entramos los parámetros siguientes:</p>
<ul>
<li><p><code>n</code>, el tamaño de las muestras; en este ejemplo, <span class="math inline">\(n=60\)</span>.</p></li>
<li><p><code>h</code>, la magnitud del efecto. Para calcularla,<a href="#fn3" class="footnoteRef" id="fnref3"><sup>3</sup></a> usamos la función <code>ES.h</code> del mismo paquete <strong>pwr</strong> y que se aplica a las proporciones muestrales de éxitos: en este ejemplo, <span class="math inline">\(\widehat{p}_v=0.67\)</span> y <span class="math inline">\(\widehat{p}_n =0.8\)</span> y la magnitud del efecto vale:</p></li>
</ul>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"> <span class="kw">ES.h</span>(<span class="fl">0.67</span>,<span class="fl">0.8</span>)</code></pre></div>
<pre><code>## [1] -0.296584</code></pre>
<ul>
<li><code>sig.level</code>, el nivel de significación, 0.05.</li>
</ul>
<p>Como solo nos interesa la potencia, añadiremos al <code>pwr.2p.test</code> el sufijo <code>$power</code>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">pwr.2p.test</span>(<span class="dt">h=</span><span class="kw">ES.h</span>(<span class="fl">0.67</span>,<span class="fl">0.8</span>), <span class="dt">n=</span><span class="dv">60</span>, <span class="dt">sig.level=</span><span class="fl">0.05</span>,<span class="dt">alternative=</span><span class="st">&quot;less&quot;</span>)<span class="op">$</span>power</code></pre></div>
<pre><code>## [1] 0.491864</code></pre>
<p>Hemos obtenido una potencia de, aproximadamente, un 49%.</p>
<p>Si estuviéramos diseñando el experimento y quisiéramos calcular el tamaño de las muestras necesario para tener una potencia del 90% al nivel de significación del 5% y esperando una magnitud del efecto pequeña (porque esperamos una mejora con las nuevas trampas, pero solo pequeña), entraríamos:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">cohen.ES</span>(<span class="dt">test=</span><span class="st">&quot;p&quot;</span>,<span class="dt">size=</span><span class="st">&quot;small&quot;</span>)<span class="op">$</span>effect.size</code></pre></div>
<pre><code>## [1] 0.2</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">pwr.2p.test</span>(<span class="dt">h=</span><span class="op">-</span><span class="fl">0.2</span>, <span class="dt">sig.level=</span><span class="fl">0.05</span>, <span class="dt">power=</span><span class="fl">0.9</span>,<span class="dt">alternative=</span><span class="st">&quot;less&quot;</span>)<span class="op">$</span>n</code></pre></div>
<pre><code>## [1] 428.192</code></pre>
<p>Tendríamos que usar dos muestras de 429 cucarachas cada una. Observad que en <code>pwr.2p.test</code> hemos entrado en <code>h</code> la magnitud del efecto en negativo: esto es debido a que usamos <code>alternative=&quot;less&quot;</code> y por lo tanto esperamos que la primera proporción sea menor que la segunda.</p>

<div class="example">
<p><span id="exm:fumarbis" class="example"><strong>Ejemplo 5.24  </strong></span>En el contraste</p>
</div>
<p> <span class="math display">\[
\left\{\begin{array}{l}
H_{0}:\mu_n=\mu_f\\
H_{1}:\mu_n&gt; \mu_f
\end{array}\right.
\]</span> del Ejemplo <a href="chap-contrastes.html#exm:fumar">5.6</a>, ¿qué tamaño de la muestra de mujeres fumadoras tendríamos que tomar si usáramos una muestra de 100 no fumadoras, quisiéramos una potencia del 90% y un nivel de significación del 5% y esperáramos una magnitud del efecto media?</p>
<p>Como es un contraste de dos medias independientes y los tamaños de las muestras pueden ser diferentes, usaremos la función <code>pwr.t2n.test</code>. Entraremos como <code>n1</code> el tamaño de la muestra de fumadoras y le pediremos que nos dé solo el valor de <code>n2</code>, el tamaño de la “otra” muestra:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">pwr.t2n.test</span>(<span class="dt">n1=</span><span class="dv">100</span>, <span class="dt">d=</span><span class="kw">cohen.ES</span>(<span class="dt">test=</span><span class="st">&quot;t&quot;</span>,<span class="dt">size=</span><span class="st">&quot;medium&quot;</span>)<span class="op">$</span>effect.size,  
             <span class="dt">sig.level=</span><span class="fl">0.05</span>, <span class="dt">power=</span><span class="fl">0.9</span>, <span class="dt">alternative=</span><span class="st">&quot;greater&quot;</span>)<span class="op">$</span>n2</code></pre></div>
<pre><code>## [1] 52.8251</code></pre>
<p>Bastaría estudiar 53 madres fumadoras.</p>
</div>
<div id="guia-rapida-3" class="section level2">
<h2><span class="header-section-number">5.5</span> Guía rápida</h2>
<p>Excepto en las que decimos lo contrario, todas las funciones para realizar contrastes que damos a continuación admiten los parámetros <code>alternative</code>, que sirve para especificar el tipo de contraste (unilateral en un sentido u otro o bilateral), y <code>conf.level</code>, que sirve para indicar el nivel de confianza <span class="math inline">\(1-\alpha\)</span>. Sus valores por defecto son contraste bilateral y nivel de confianza 0.95.</p>
<ul>
<li><p><code>t.test</code> realiza tests t para contrastar una o dos medias (tanto usando muestras independientes como emparejadas). Aparte de <code>alternative</code> y <code>conf.level</code>, sus parámetros principales son:</p>
<ul>
<li><p><code>mu</code> para especificar el valor de la media que queremos contrastar en un test de una media.</p></li>
<li><p><code>paired</code> para indicar si en un contraste de dos medias usamos muestras independientes o emparejadas.</p></li>
<li><p><code>var.equal</code> para indicar en un contraste de dos medias usando muestras independientes si las varianzas poblacionales son iguales o diferentes.</p></li>
</ul></li>
<li><p><code>SIGN.test</code> del paquete <strong>BSDA</strong>, realiza un test de signos para contrastar una mediana. Dispone del parámetro <code>md</code> para entrar la mediana a contrastar.</p></li>
<li><p><code>wilcox.test</code>, para realizar tests de Wilcoxon y de Mann-Whitney para contrastar una o dos medianas (tanto usando muestras independientes como emparejadas). Sus parámetros son los mismos que los de <code>t.test</code> (salvo <code>var.equal</code>, que en estos tests no tiene sentido).</p></li>
<li><p><code>sigma.test</code>, para realizar tests <span class="math inline">\(\chi^2\)</span> para contrastar una varianza (o una desviación típica). Dispone de los parámetros <code>sigma</code> y <code>sigmasq</code> para indicar, respectivamente, la desviación típica o la varianza a contrastar.</p></li>
<li><p><code>var.test</code>, para realizar tests F para contrastar dos varianzas (o dos desviaciones típicas).</p></li>
<li><p><code>fligner.test</code>, para realizar tests no paramétricos de Fligner-Killeen para contrastar dos varianzas (o dos desviaciones típicas). No dispone de los parámetros <code>alternative</code> (solo sirve para contrastes bilaterales) ni <code>conf.level</code> (no calcula intervalos de confianza).</p></li>
<li><p><code>binom.test</code>, para realizar tests binomiales exactos para contrastar una proporción. Dispone del parámetro <code>p</code> para indicar la proporción a contrastar.</p></li>
<li><p><code>prop.test</code>, para realizar tests aproximados para contrastar una proporción o dos proporciones de poblaciones usando muestras independientes. También dispone del parámetro <code>p</code> para indicar la proporción a contrastar en un contraste de una proporción.</p></li>
<li><p><code>fisher.test</code>, para realizar tests exactos de Fisher para contrastar dos proporciones usando muestras independientes.</p></li>
<li><p><code>mcnemar.test</code>, para realizar tests bilaterales de McNemar para contrastar dos proporciones usando muestras emparejadas. No dispone de los parámetros <code>alternative</code> ni <code>conf.level</code>.</p></li>
<li><p><code>cohen.ES</code> del paquete <strong>pwr</strong>, da los valores aceptados por convenio como “pequeño”, “mediano” y “grande” para diferentes tests.</p></li>
<li><code>pwr.t.test</code> del paquete <strong>pwr</strong>, relaciona el tamaño de la(s) muestra(s), el nivel de significación, la potencia y la magnitud del efecto (en el sentido de que si se entran tres de estos valores se obtiene el cuarto) en tests t de una media, de dos medias usando muestras emparejadas o de dos medias usando muestras independientes del mismo tamaño. Sus parámetros, son
<ul>
<li><code>n</code>: el tamaño de la muestra o de las muestras.</li>
<li><code>sig.level</code>: el nivel de significación.</li>
<li><code>power</code>: la potencia.</li>
<li><code>d</code>: la magnitud del efecto</li>
<li><code>type</code>: el tipo de muestras (una muestra, dos muestras emparejadas, dos muestras independientes).</li>
<li><code>alternative</code>: el tipo de hipótesis alternativa.</li>
</ul></li>
<li><code>pwr.t2n.test</code>del paquete <strong>pwr</strong>, relaciona los tamaños de muestras, el nivel de significación, la potencia y la magnitud del efecto en tests t de dos medias usando muestras independientes de distinto tamaño. Sus parámetros son
<ul>
<li><code>n1</code> y <code>n2</code>: los tamaños de las dos muestras.</li>
<li><code>sig.level</code>, <code>power</code>, <code>d</code> y <code>alternative</code> como en <code>pwr.t.test</code>.</li>
</ul></li>
<li><code>pwr.p.test</code> del paquete <strong>pwr</strong>, relaciona los tamaños de muestras, el nivel de significación, la potencia y la magnitud del efecto en contrastes aproximados de una proporción. Sus parámetros son
<ul>
<li><code>n</code>, <code>sig.level</code>, <code>power</code> y <code>alternative</code> como en <code>pwr.t.test</code>.</li>
<li><code>h</code>: la magnitud del efecto</li>
</ul></li>
<li><p><code>pwr.2p.test</code> del paquete <strong>pwr</strong>, relaciona los tamaños de muestras, el nivel de significación, la potencia y la magnitud del efecto en contrastes aproximados de dos proporciones usando muestras independientes del mismo tamaño. Sus parámetros son los mismos que los de <code>pwr.p.test</code>.</p></li>
<li><code>pwr.2p2n.test</code>, del paquete <strong>pwr</strong>, relaciona los tamaños de muestras, el nivel de significación, la potencia y la magnitud del efecto en contrastes aproximados de dos proporciones usando muestras de distinto tamaño. Sus parámetros son
<ul>
<li><code>n1</code> y <code>n2</code>: los tamaños de las dos muestras.</li>
<li><code>sig.level</code>, <code>power</code>, <code>h</code> y <code>alternative</code> como en <code>pwr.p.test</code>.</li>
</ul></li>
</ul>
</div>
<div id="ejercicios-4" class="section level2">
<h2><span class="header-section-number">5.6</span> Ejercicios</h2>
<div id="modelo-de-test-1" class="section level3 unnumbered">
<h3>Modelo de test</h3>
<p><em>(1)</em> Tenemos una m.a.s. de una población normal <span class="math inline">\(X\sim N(\mu,\sigma)\)</span> formada por los números 2,5,3,5,6,6,7,2. Usando la función <code>t.test</code>, calculad el p-valor (redondeado a 3 cifras decimales, sin ceros innecesarios a la derecha) del contraste <span class="math inline">\(H_0: \mu=4\)</span> contra <span class="math inline">\(H_1:\mu \neq 4\)</span> y decid (contestando SI, sin acento, o NO) si podemos rechazar la hipótesis nula en favor de la alternativa a un nivel de significación de 0.05. Tenéis que dar las dos respuestas en este orden, separadas por un único espacio en blanco.</p>
<p><em>(2)</em> Tenemos dos muestras de poblaciones normales, <span class="math inline">\(X_1\sim N(\mu_1,\sigma_1)\)</span> y <span class="math inline">\(X_2\sim N(\mu_2,\sigma_2)\)</span>. Sean <span class="math inline">\(x_1=(2,5,3,5,6,6,7,2)\)</span> y <span class="math inline">\(x_2=(3,2,5,4,2,2,4,5,1,6,2)\)</span> muestras aleatorias simples de <span class="math inline">\(X_1\)</span> y <span class="math inline">\(X_2\)</span>, respectivamente. Usando la función <code>t.test</code>, calculad el p-valor (redondeado a 3 cifras decimales, sin ceros innecesarios a la derecha) del contraste <span class="math inline">\(H_0: \mu_1=\mu_2\)</span> contra <span class="math inline">\(H_1:\mu_1&gt;\mu_2\)</span> suponiendo que las varianzas son diferentes y decid (contestando SI, sin acento, o NO) si podemos rechazar la hipótesis nula en favor de la alternativa a un nivel de significación de 0.1. Tenéis que dar las dos respuestas en este orden, separadas por un único espacio en blanco.</p>
<p><em>(3)</em> Tenemos dos muestras de poblaciones normales, <span class="math inline">\(X_1\sim N(\mu_1,\sigma_1)\)</span> y <span class="math inline">\(X_2\sim N(\mu_2,\sigma_2)\)</span>. Sean <span class="math inline">\(x_1=(2,5,3,5,6,6,7,2)\)</span> y <span class="math inline">\(x_2=(3,2,10,9,2,2,4,5,1,10,2)\)</span> muestras aleatorias simples de <span class="math inline">\(X_1\)</span> y <span class="math inline">\(X_2\)</span>, respectivamente. Usando la función <code>var.test</code>, calculad los extremos inferior y superior de un intervalo de confianza del 95% para <span class="math inline">\(\sigma_1^2/\sigma_2^2\)</span> (redondeados a 3 cifras decimales, sin ceros innecesarios a la derecha) y decid (contestando SI, sin acento, o NO) si en el contraste <span class="math inline">\(H_0: \sigma_1=\sigma_2\)</span> contra <span class="math inline">\(H_1:\sigma_1 \neq \sigma_2\)</span> podemos rechazar la hipótesis nula en favor de la alternativa a un nivel de significación de 0.05. Tenéis que dar las tres respuestas en este orden, separadas por un único espacio en blanco.</p>
<p><em>(4)</em> Tenemos dos variables aleatorias de Bernoulli de proporciones poblacionales <span class="math inline">\(p_1\)</span> y <span class="math inline">\(p_2\)</span>, respectivamente. En una muestra de 100 observaciones de la primera hemos obtenido 20 éxitos, y en una muestra de 150 observaciones de la segunda, hemos obtenido 40 éxitos. Usando la función <code>prop.test</code>, calculad el p-valor (redondeado a 3 cifras decimales, sin ceros innecesarios a la derecha) del contraste <span class="math inline">\(H_0: p_1=p_2\)</span> contra <span class="math inline">\(H_1:p_1&lt;p_2\)</span> y decid (contestando SI, sin acento, o NO) si podemos rechazar la hipótesis nula en favor de la alternativa a un nivel de significación de 0.05. Tenéis que dar las dos respuestas en este orden, separadas por un único espacio en blanco.</p>
<!--
### Ejercicios {-}

**(1)** Para satisfacer las necesidades respiratorias de los peces de agua caliente, el contenido de oxígeno disuelto debe presentar un promedio de
6.5 partes por millón (ppm), con una desviación típica no mayor de 1.2 ppm.
Cuando la temperatura del agua crece, el oxígeno disuelto disminuye, y esto causa la asfixia del pez. 

Se realizó un estudio sobre los efectos del calor en verano en el contenido de oxígeno disuelto en un gran lago. Después de un período particularmente caluroso, se tomaron muestras de agua en $35$ lugares aleatoriamente seleccionados
en el lago, y se determinó el contenido de oxígeno disuelto. Los resultados (en ppm) fueron los siguientes:

```r
O2=c(9.1,6.8,7.0,7.5,8.7,3.2,5.4,8.1,4.4,5.1,6.2,6.9,6.9,4.3,
    8.0,5.3,6.2,6.4,7.8,5.8,6.9,7.7,5.2,5.8,6.3,5.9,8.5,7.5,8.9,
    5.6,6.6,5.3,5.7,6.9,6.6)
```
Suponemos que estos contenidos de oxígeno siguen una distribución normal.

*(a)*  ¿Hay evidencia de que el contenido medio de oxígeno en el lago sea inferior al nivel aceptable de $6.5$ ppm?
*(b)*  ¿Hay evidencia de que la desviación típica del contenido  de oxígeno en el lago sea superior a $1.2$ ppm?

**(2)** Los angiogramas son la técnica estándar para diagnosticar un ictus, pero tienen un ligero riesgo de mortalidad (inferior al 1%). Algunos investigadores han propuesto usar una prueba PET para diagnosticar el ictus de manera no invasiva. Sobre 64 pacientes ingresados en urgencias con síntomas de ictus se usaron ambas técnicas de diagnóstico. Los resultados obtenidos se resumen en la tabla siguiente:
$$
\begin{array}{r|c}
 & \quad\mbox{Angiograma}\quad \\
\mbox{PET} &\quad \mbox{Positivo} \qquad \mbox{Negativo}\quad \\\hline
 \mbox{Positivo} &\quad 32  \qquad\qquad\ \ 8\quad \\
 \mbox{Negativo} &\quad\quad 3   \qquad\qquad\ \   21\quad\ 
\end{array}
$$

Contrastad si ambas técnicas de diagnóstico tienen la misma probabilidad de dar positivo.
-->
</div>
<div id="respuestas-al-test-4" class="section level3 unnumbered">
<h3>Respuestas al test</h3>
<p><em>(1)</em> 0.487 NO</p>
<p>Nosotros lo hemos resuelto con</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x=<span class="kw">c</span>(<span class="dv">2</span>,<span class="dv">5</span>,<span class="dv">3</span>,<span class="dv">5</span>,<span class="dv">6</span>,<span class="dv">6</span>,<span class="dv">7</span>,<span class="dv">2</span>)
<span class="kw">round</span>(<span class="kw">t.test</span>(x,<span class="dt">mu=</span><span class="dv">4</span>)<span class="op">$</span>p.value,<span class="dv">3</span>)</code></pre></div>
<pre><code>## [1] 0.487</code></pre>
<p><em>(2)</em> 0.083 SI</p>
<p>Nosotros lo hemos resuelto con</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x1=<span class="kw">c</span>(<span class="dv">2</span>,<span class="dv">5</span>,<span class="dv">3</span>,<span class="dv">5</span>,<span class="dv">6</span>,<span class="dv">6</span>,<span class="dv">7</span>,<span class="dv">2</span>)
x2=<span class="kw">c</span>(<span class="dv">3</span>,<span class="dv">2</span>,<span class="dv">5</span>,<span class="dv">4</span>,<span class="dv">2</span>,<span class="dv">2</span>,<span class="dv">4</span>,<span class="dv">5</span>,<span class="dv">1</span>,<span class="dv">6</span>,<span class="dv">2</span>)
<span class="kw">round</span>(<span class="kw">t.test</span>(x1,x2,<span class="dt">alternative=</span><span class="st">&quot;greater&quot;</span>)<span class="op">$</span>p.value,<span class="dv">3</span>)</code></pre></div>
<pre><code>## [1] 0.083</code></pre>
<p><em>(3)</em> 0.078 1.465 NO</p>
<p>Nosotros lo hemos resuelto con</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x1=<span class="kw">c</span>(<span class="dv">2</span>,<span class="dv">5</span>,<span class="dv">3</span>,<span class="dv">5</span>,<span class="dv">6</span>,<span class="dv">6</span>,<span class="dv">7</span>,<span class="dv">2</span>)
x2=<span class="kw">c</span>(<span class="dv">3</span>,<span class="dv">2</span>,<span class="dv">10</span>,<span class="dv">9</span>,<span class="dv">2</span>,<span class="dv">2</span>,<span class="dv">4</span>,<span class="dv">5</span>,<span class="dv">1</span>,<span class="dv">10</span>,<span class="dv">2</span>)
<span class="kw">round</span>(<span class="kw">var.test</span>(x1,x2)<span class="op">$</span>conf.int,<span class="dv">3</span>)</code></pre></div>
<pre><code>## [1] 0.078 1.465
## attr(,&quot;conf.level&quot;)
## [1] 0.95</code></pre>
<p><em>(4)</em> 0.145 NO</p>
<p>Nosotros lo hemos resuelto con</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">round</span>(<span class="kw">prop.test</span>(<span class="kw">c</span>(<span class="dv">20</span>,<span class="dv">40</span>),<span class="kw">c</span>(<span class="dv">100</span>,<span class="dv">150</span>),<span class="dt">alternative=</span><span class="st">&quot;less&quot;</span>)<span class="op">$</span>p.value,<span class="dv">3</span>)</code></pre></div>
<pre><code>## [1] 0.145</code></pre>
<!--
### Respuestas sucintas a los ejercicios {-}

**(1)** *(a)* No:

```r
O2=c(9.1,6.8,7.0,7.5,8.7,3.2,5.4,8.1,4.4,5.1,6.2,6.9,6.9,4.3,
    8.0,5.3,6.2,6.4,7.8,5.8,6.9,7.7,5.2,5.8,6.3,5.9,8.5,7.5,8.9,
    5.6,6.6,5.3,5.7,6.9,6.6)
t.test(O2,mu=6.5,alternative="less")
```

```
## 
##  One Sample t-test
## 
## data:  O2
## t = 0.124, df = 34, p-value = 0.549
## alternative hypothesis: true mean is less than 6.5
## 95 percent confidence interval:
##     -Inf 6.91816
## sample estimates:
## mean of x 
##   6.52857
```

*(b)* Tampoco:

```r
library(TeachingDemos)
sigma.test(O2, sigma=1.2, alternative="greater")
```

```
## 
##  One sample Chi-squared test for variance
## 
## data:  O2
## X-squared = 43.87, df = 34, p-value = 0.12
## alternative hypothesis: true variance is greater than 1.44
## 95 percent confidence interval:
##  1.29976     Inf
## sample estimates:
## var of O2 
##   1.85798
```

**(2)** Nop:

```r
binom.test(3,11, p=0.5)
```

```
## 
##  Exact binomial test
## 
## data:  3 and 11
## number of successes = 3, number of trials = 11, p-value = 0.227
## alternative hypothesis: true probability of success is not equal to 0.5
## 95 percent confidence interval:
##  0.0602177 0.6097426
## sample estimates:
## probability of success 
##               0.272727
```
-->

</div>
</div>
</div>
<div class="footnotes">
<hr />
<ol start="1">
<li id="fn1"><p>Se sabe que si las dos muestras provienen de poblaciones normales y son del mismo tamaño, el test t tiende a dar la misma conclusión tanto si se supone que las dos varianzas son iguales como si se supone que son diferentes: véase C. A. Markowski y E. P. Markowski, “Conditions for the Effectiveness of a Preliminary Test of Variance,” <em>The American Statistician</em> 44 (1990), pp. 322-326. Pero no sabemos si estas longitudes siguen distribuciones normales o no, y que “tienda a dar” la misma conclusión no significa que en un ejemplo concreto con p-valores cercanos al nivel de significación no pueda dar conclusiones diferentes.<a href="chap-contrastes.html#fnref1">↩</a></p></li>
<li id="fn2"><p>Véanse: E. S. Pearson, “The analysis of variance in cases of non-normal variation,” <em>Biometrika</em> 23 (1931), pp. 114-133; G. E. P. Box, “Non-normality and tests on variances,” <em>Biometrika</em> 40 (1953), pp. 318-335.<a href="chap-contrastes.html#fnref2">↩</a></p></li>
<li id="fn3"><p>Por si a alguien le interesa, la fórmula para esta magnitud del efecto es <span class="math display">\[
h=2\left(\arcsin\big(\sqrt{\widehat{p}_1}\,\big)-\arcsin\big(\sqrt{\widehat{p}_2}\,\big)\right),
\]</span> siendo <span class="math inline">\(\widehat{p}_1\)</span> y <span class="math inline">\(\widehat{p}_2\)</span> las proporciones muestrales de éxitos de las dos muestras.<a href="chap-contrastes.html#fnref3">↩</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="chap-IC.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="chap-bondad.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/cescrossello/AprendeR-II/edit/master/05-ContrastesI.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"download": ["AprendeR-Parte-II.pdf", "AprendeR-Parte-II.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:" && /^https?:/.test(src))
      src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
