<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Lección 9 ANOVA básico | AprendeR: Parte II</title>
  <meta name="description" content="Apuntes AprendeR bookdown::gitbook." />
  <meta name="generator" content="bookdown 0.20 and GitBook 2.6.7" />

  <meta property="og:title" content="Lección 9 ANOVA básico | AprendeR: Parte II" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Apuntes AprendeR bookdown::gitbook." />
  <meta name="github-repo" content="AprendeR-UIB/AprendeR2" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Lección 9 ANOVA básico | AprendeR: Parte II" />
  
  <meta name="twitter:description" content="Apuntes AprendeR bookdown::gitbook." />
  

<meta name="author" content="The UIB-AprendeR team" />


<meta name="date" content="2021-03-05" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="chap-estmult.html"/>
<link rel="next" href="chap-regresion.html"/>
<script src="libs/header-attrs-2.6/header-attrs.js"></script>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />











<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">AprendeR: Parte II</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Presentación</a></li>
<li class="part"><span><b>Parte II: Estadística inferencial</b></span></li>
<li class="chapter" data-level="1" data-path="chap-distr.html"><a href="chap-distr.html"><i class="fa fa-check"></i><b>1</b> Distribuciones de probabilidad</a>
<ul>
<li class="chapter" data-level="1.1" data-path="chap-distr.html"><a href="chap-distr.html#ejercicios"><i class="fa fa-check"></i><b>1.1</b> Ejercicios</a>
<ul>
<li class="chapter" data-level="" data-path="chap-distr.html"><a href="chap-distr.html#test"><i class="fa fa-check"></i>Test</a></li>
<li class="chapter" data-level="" data-path="chap-distr.html"><a href="chap-distr.html#problemas"><i class="fa fa-check"></i>Problemas</a></li>
<li class="chapter" data-level="" data-path="chap-distr.html"><a href="chap-distr.html#respuestas-al-test"><i class="fa fa-check"></i>Respuestas al test</a></li>
<li class="chapter" data-level="" data-path="chap-distr.html"><a href="chap-distr.html#soluciones-sucintas-de-los-problemas"><i class="fa fa-check"></i>Soluciones sucintas de los problemas</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="chap-muestreo.html"><a href="chap-muestreo.html"><i class="fa fa-check"></i><b>2</b> Conceptos básicos de muestreo</a>
<ul>
<li class="chapter" data-level="2.1" data-path="chap-muestreo.html"><a href="chap-muestreo.html#sec:muestreo"><i class="fa fa-check"></i><b>2.1</b> Tipos de muestreo</a></li>
<li class="chapter" data-level="2.2" data-path="chap-muestreo.html"><a href="chap-muestreo.html#muestreo-aleatorio-con-r"><i class="fa fa-check"></i><b>2.2</b> Muestreo aleatorio con R</a></li>
<li class="chapter" data-level="2.3" data-path="chap-muestreo.html"><a href="chap-muestreo.html#guía-rápida"><i class="fa fa-check"></i><b>2.3</b> Guía rápida</a></li>
<li class="chapter" data-level="2.4" data-path="chap-distr.html"><a href="chap-distr.html#ejercicios"><i class="fa fa-check"></i><b>2.4</b> Ejercicios</a>
<ul>
<li class="chapter" data-level="" data-path="chap-distr.html"><a href="chap-distr.html#test"><i class="fa fa-check"></i>Test</a></li>
<li class="chapter" data-level="" data-path="chap-distr.html"><a href="chap-distr.html#problemas"><i class="fa fa-check"></i>Problemas</a></li>
<li class="chapter" data-level="" data-path="chap-distr.html"><a href="chap-distr.html#respuestas-al-test"><i class="fa fa-check"></i>Respuestas al test</a></li>
<li class="chapter" data-level="" data-path="chap-distr.html"><a href="chap-distr.html#soluciones-sucintas-de-los-problemas"><i class="fa fa-check"></i>Soluciones sucintas de los problemas</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="chap-estimacion.html"><a href="chap-estimacion.html"><i class="fa fa-check"></i><b>3</b> Estimación puntual</a>
<ul>
<li class="chapter" data-level="3.1" data-path="chap-estimacion.html"><a href="chap-estimacion.html#estimación-máximo-verosímil"><i class="fa fa-check"></i><b>3.1</b> Estimación máximo verosímil</a></li>
<li class="chapter" data-level="3.2" data-path="chap-muestreo.html"><a href="chap-muestreo.html#guía-rápida"><i class="fa fa-check"></i><b>3.2</b> Guía rápida</a></li>
<li class="chapter" data-level="3.3" data-path="chap-distr.html"><a href="chap-distr.html#ejercicios"><i class="fa fa-check"></i><b>3.3</b> Ejercicios</a>
<ul>
<li class="chapter" data-level="" data-path="chap-distr.html"><a href="chap-distr.html#test"><i class="fa fa-check"></i>Test</a></li>
<li class="chapter" data-level="" data-path="chap-distr.html"><a href="chap-distr.html#problemas"><i class="fa fa-check"></i>Problemas</a></li>
<li class="chapter" data-level="" data-path="chap-distr.html"><a href="chap-distr.html#respuestas-al-test"><i class="fa fa-check"></i>Respuestas al test</a></li>
<li class="chapter" data-level="" data-path="chap-distr.html"><a href="chap-distr.html#soluciones-sucintas-de-los-problemas"><i class="fa fa-check"></i>Soluciones sucintas de los problemas</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="chap-IC.html"><a href="chap-IC.html"><i class="fa fa-check"></i><b>4</b> Intervalos de confianza</a>
<ul>
<li class="chapter" data-level="4.1" data-path="chap-IC.html"><a href="chap-IC.html#sec:ICT"><i class="fa fa-check"></i><b>4.1</b> Intervalo de confianza para la media basado en la t de Student</a></li>
<li class="chapter" data-level="4.2" data-path="chap-IC.html"><a href="chap-IC.html#intervalos-de-confianza-para-la-proporción-poblacional"><i class="fa fa-check"></i><b>4.2</b> Intervalos de confianza para la proporción poblacional</a></li>
<li class="chapter" data-level="4.3" data-path="chap-IC.html"><a href="chap-IC.html#sec:ICvar"><i class="fa fa-check"></i><b>4.3</b> Intervalo de confianza para la varianza de una población normal</a></li>
<li class="chapter" data-level="4.4" data-path="chap-IC.html"><a href="chap-IC.html#bootstrap"><i class="fa fa-check"></i><b>4.4</b> Bootstrap</a></li>
<li class="chapter" data-level="4.5" data-path="chap-muestreo.html"><a href="chap-muestreo.html#guía-rápida"><i class="fa fa-check"></i><b>4.5</b> Guía rápida</a></li>
<li class="chapter" data-level="4.6" data-path="chap-distr.html"><a href="chap-distr.html#ejercicios"><i class="fa fa-check"></i><b>4.6</b> Ejercicios</a>
<ul>
<li class="chapter" data-level="" data-path="chap-distr.html"><a href="chap-distr.html#test"><i class="fa fa-check"></i>Test</a></li>
<li class="chapter" data-level="" data-path="chap-distr.html"><a href="chap-distr.html#problemas"><i class="fa fa-check"></i>Problemas</a></li>
<li class="chapter" data-level="" data-path="chap-distr.html"><a href="chap-distr.html#respuestas-al-test"><i class="fa fa-check"></i>Respuestas al test</a></li>
<li class="chapter" data-level="" data-path="chap-distr.html"><a href="chap-distr.html#soluciones-sucintas-de-los-problemas"><i class="fa fa-check"></i>Soluciones sucintas de los problemas</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="chap-contrastes.html"><a href="chap-contrastes.html"><i class="fa fa-check"></i><b>5</b> Contrastes de hipótesis</a>
<ul>
<li class="chapter" data-level="5.1" data-path="chap-contrastes.html"><a href="chap-contrastes.html#contrastes-para-medias"><i class="fa fa-check"></i><b>5.1</b> Contrastes para medias</a>
<ul>
<li class="chapter" data-level="" data-path="chap-contrastes.html"><a href="chap-contrastes.html#el-test-t"><i class="fa fa-check"></i>El test t</a></li>
<li class="chapter" data-level="" data-path="chap-contrastes.html"><a href="chap-contrastes.html#tests-no-paramétricos"><i class="fa fa-check"></i>Tests no paramétricos</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="chap-contrastes.html"><a href="chap-contrastes.html#contrastes-para-varianzas"><i class="fa fa-check"></i><b>5.2</b> Contrastes para varianzas</a></li>
<li class="chapter" data-level="5.3" data-path="chap-contrastes.html"><a href="chap-contrastes.html#contrastes-para-proporciones"><i class="fa fa-check"></i><b>5.3</b> Contrastes para proporciones</a></li>
<li class="chapter" data-level="5.4" data-path="chap-contrastes.html"><a href="chap-contrastes.html#cálculo-de-la-potencia-de-un-contraste"><i class="fa fa-check"></i><b>5.4</b> Cálculo de la potencia de un contraste</a></li>
<li class="chapter" data-level="5.5" data-path="chap-muestreo.html"><a href="chap-muestreo.html#guía-rápida"><i class="fa fa-check"></i><b>5.5</b> Guía rápida</a></li>
<li class="chapter" data-level="5.6" data-path="chap-distr.html"><a href="chap-distr.html#ejercicios"><i class="fa fa-check"></i><b>5.6</b> Ejercicios</a>
<ul>
<li class="chapter" data-level="" data-path="chap-contrastes.html"><a href="chap-contrastes.html#modelo-de-test"><i class="fa fa-check"></i>Modelo de test</a></li>
<li class="chapter" data-level="" data-path="chap-contrastes.html"><a href="chap-contrastes.html#ejercicios-1"><i class="fa fa-check"></i>Ejercicios</a></li>
<li class="chapter" data-level="" data-path="chap-distr.html"><a href="chap-distr.html#respuestas-al-test"><i class="fa fa-check"></i>Respuestas al test</a></li>
<li class="chapter" data-level="" data-path="chap-contrastes.html"><a href="chap-contrastes.html#respuestas-sucintas-a-los-ejercicios"><i class="fa fa-check"></i>Respuestas sucintas a los ejercicios</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="chap-bondad.html"><a href="chap-bondad.html"><i class="fa fa-check"></i><b>6</b> Contrastes de bondad de ajuste</a>
<ul>
<li class="chapter" data-level="6.1" data-path="chap-bondad.html"><a href="chap-bondad.html#pruebas-gráficas-q-q-plots"><i class="fa fa-check"></i><b>6.1</b> Pruebas gráficas: Q-Q-plots</a></li>
<li class="chapter" data-level="6.2" data-path="chap-bondad.html"><a href="chap-bondad.html#el-test-chi2-de-pearson"><i class="fa fa-check"></i><b>6.2</b> El test <span class="math inline">\(\chi^2\)</span> de Pearson</a></li>
<li class="chapter" data-level="6.3" data-path="chap-bondad.html"><a href="chap-bondad.html#el-test-chi2-para-distribuciones-continuas"><i class="fa fa-check"></i><b>6.3</b> El test <span class="math inline">\(\chi^2\)</span> para distribuciones continuas</a></li>
<li class="chapter" data-level="6.4" data-path="chap-bondad.html"><a href="chap-bondad.html#el-test-de-kolgomorov-smirnov"><i class="fa fa-check"></i><b>6.4</b> El test de Kolgomorov-Smirnov</a></li>
<li class="chapter" data-level="6.5" data-path="chap-bondad.html"><a href="chap-bondad.html#tests-de-normalidad"><i class="fa fa-check"></i><b>6.5</b> Tests de normalidad</a></li>
<li class="chapter" data-level="6.6" data-path="chap-muestreo.html"><a href="chap-muestreo.html#guía-rápida"><i class="fa fa-check"></i><b>6.6</b> Guía rápida</a></li>
<li class="chapter" data-level="6.7" data-path="chap-distr.html"><a href="chap-distr.html#ejercicios"><i class="fa fa-check"></i><b>6.7</b> Ejercicios</a>
<ul>
<li class="chapter" data-level="" data-path="chap-contrastes.html"><a href="chap-contrastes.html#modelo-de-test"><i class="fa fa-check"></i>Modelo de test</a></li>
<li class="chapter" data-level="" data-path="chap-distr.html"><a href="chap-distr.html#problemas"><i class="fa fa-check"></i>Problemas</a></li>
<li class="chapter" data-level="" data-path="chap-distr.html"><a href="chap-distr.html#respuestas-al-test"><i class="fa fa-check"></i>Respuestas al test</a></li>
<li class="chapter" data-level="" data-path="chap-distr.html"><a href="chap-distr.html#soluciones-sucintas-de-los-problemas"><i class="fa fa-check"></i>Soluciones sucintas de los problemas</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="chap-indep.html"><a href="chap-indep.html"><i class="fa fa-check"></i><b>7</b> Contrastes de independencia y homogeneidad</a>
<ul>
<li class="chapter" data-level="7.1" data-path="chap-indep.html"><a href="chap-indep.html#tablas-de-contingencia"><i class="fa fa-check"></i><b>7.1</b> Tablas de contingencia</a></li>
<li class="chapter" data-level="7.2" data-path="chap-indep.html"><a href="chap-indep.html#contraste-de-independencia"><i class="fa fa-check"></i><b>7.2</b> Contraste de independencia</a></li>
<li class="chapter" data-level="7.3" data-path="chap-indep.html"><a href="chap-indep.html#sec:hom"><i class="fa fa-check"></i><b>7.3</b> Contraste de homogeneidad</a></li>
<li class="chapter" data-level="7.4" data-path="chap-indep.html"><a href="chap-indep.html#potencia-de-un-contraste-chi2"><i class="fa fa-check"></i><b>7.4</b> Potencia de un contraste <span class="math inline">\(\chi^2\)</span></a></li>
<li class="chapter" data-level="7.5" data-path="chap-muestreo.html"><a href="chap-muestreo.html#guía-rápida"><i class="fa fa-check"></i><b>7.5</b> Guía rápida</a></li>
<li class="chapter" data-level="7.6" data-path="chap-distr.html"><a href="chap-distr.html#ejercicios"><i class="fa fa-check"></i><b>7.6</b> Ejercicios</a>
<ul>
<li class="chapter" data-level="" data-path="chap-contrastes.html"><a href="chap-contrastes.html#modelo-de-test"><i class="fa fa-check"></i>Modelo de test</a></li>
<li class="chapter" data-level="" data-path="chap-contrastes.html"><a href="chap-contrastes.html#ejercicios-1"><i class="fa fa-check"></i>Ejercicios</a></li>
<li class="chapter" data-level="" data-path="chap-distr.html"><a href="chap-distr.html#respuestas-al-test"><i class="fa fa-check"></i>Respuestas al test</a></li>
<li class="chapter" data-level="" data-path="chap-distr.html"><a href="chap-distr.html#soluciones-sucintas-de-los-problemas"><i class="fa fa-check"></i>Soluciones sucintas de los problemas</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="chap-estmult.html"><a href="chap-estmult.html"><i class="fa fa-check"></i><b>8</b> Introducción a la estadística descriptiva multidimensional</a>
<ul>
<li class="chapter" data-level="8.1" data-path="chap-estmult.html"><a href="chap-estmult.html#matrices-de-datos-cuantitativos"><i class="fa fa-check"></i><b>8.1</b> Matrices de datos cuantitativos</a></li>
<li class="chapter" data-level="8.2" data-path="chap-estmult.html"><a href="chap-estmult.html#transformaciones-lineales"><i class="fa fa-check"></i><b>8.2</b> Transformaciones lineales</a></li>
<li class="chapter" data-level="8.3" data-path="chap-estmult.html"><a href="chap-estmult.html#covarianzas-y-correlaciones"><i class="fa fa-check"></i><b>8.3</b> Covarianzas y correlaciones</a></li>
<li class="chapter" data-level="8.4" data-path="chap-estmult.html"><a href="chap-estmult.html#correlación-de-spearman"><i class="fa fa-check"></i><b>8.4</b> Correlación de Spearman</a></li>
<li class="chapter" data-level="8.5" data-path="chap-estmult.html"><a href="chap-estmult.html#contrastes-de-correlación"><i class="fa fa-check"></i><b>8.5</b> Contrastes de correlación</a></li>
<li class="chapter" data-level="8.6" data-path="chap-estmult.html"><a href="chap-estmult.html#un-ejemplo"><i class="fa fa-check"></i><b>8.6</b> Un ejemplo</a></li>
<li class="chapter" data-level="8.7" data-path="chap-estmult.html"><a href="chap-estmult.html#representación-gráfica-de-datos-multidimensionales"><i class="fa fa-check"></i><b>8.7</b> Representación gráfica de datos multidimensionales</a></li>
<li class="chapter" data-level="8.8" data-path="chap-muestreo.html"><a href="chap-muestreo.html#guía-rápida"><i class="fa fa-check"></i><b>8.8</b> Guía rápida</a></li>
<li class="chapter" data-level="8.9" data-path="chap-distr.html"><a href="chap-distr.html#ejercicios"><i class="fa fa-check"></i><b>8.9</b> Ejercicios</a>
<ul>
<li class="chapter" data-level="" data-path="chap-contrastes.html"><a href="chap-contrastes.html#modelo-de-test"><i class="fa fa-check"></i>Modelo de test</a></li>
<li class="chapter" data-level="" data-path="chap-distr.html"><a href="chap-distr.html#problemas"><i class="fa fa-check"></i>Problemas</a></li>
<li class="chapter" data-level="" data-path="chap-distr.html"><a href="chap-distr.html#respuestas-al-test"><i class="fa fa-check"></i>Respuestas al test</a></li>
<li class="chapter" data-level="" data-path="chap-distr.html"><a href="chap-distr.html#soluciones-sucintas-de-los-problemas"><i class="fa fa-check"></i>Soluciones sucintas de los problemas</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="chap-ANOVA.html"><a href="chap-ANOVA.html"><i class="fa fa-check"></i><b>9</b> ANOVA básico</a>
<ul>
<li class="chapter" data-level="9.1" data-path="chap-ANOVA.html"><a href="chap-ANOVA.html#sec:modelos"><i class="fa fa-check"></i><b>9.1</b> Los modelos del ANOVA en R</a></li>
<li class="chapter" data-level="9.2" data-path="chap-ANOVA.html"><a href="chap-ANOVA.html#sec:ANOVA-1"><i class="fa fa-check"></i><b>9.2</b> ANOVA de un factor</a></li>
<li class="chapter" data-level="9.3" data-path="chap-ANOVA.html"><a href="chap-ANOVA.html#anova-de-bloques-completos-aleatorios"><i class="fa fa-check"></i><b>9.3</b> ANOVA de bloques completos aleatorios</a></li>
<li class="chapter" data-level="9.4" data-path="chap-ANOVA.html"><a href="chap-ANOVA.html#sec:ANOVA2"><i class="fa fa-check"></i><b>9.4</b> ANOVA de dos vías</a></li>
<li class="chapter" data-level="9.5" data-path="chap-ANOVA.html"><a href="chap-ANOVA.html#condiciones-del-anova"><i class="fa fa-check"></i><b>9.5</b> Condiciones del ANOVA</a></li>
<li class="chapter" data-level="9.6" data-path="chap-ANOVA.html"><a href="chap-ANOVA.html#sec:pares"><i class="fa fa-check"></i><b>9.6</b> Comparaciones de pares de medias</a>
<ul>
<li class="chapter" data-level="9.6.1" data-path="chap-ANOVA.html"><a href="chap-ANOVA.html#tests-t-por-parejas"><i class="fa fa-check"></i><b>9.6.1</b> Tests t por parejas</a></li>
<li class="chapter" data-level="9.6.2" data-path="chap-ANOVA.html"><a href="chap-ANOVA.html#test-de-duncan"><i class="fa fa-check"></i><b>9.6.2</b> Test de Duncan</a></li>
<li class="chapter" data-level="9.6.3" data-path="chap-ANOVA.html"><a href="chap-ANOVA.html#método-de-tukey"><i class="fa fa-check"></i><b>9.6.3</b> Método de Tukey</a></li>
</ul></li>
<li class="chapter" data-level="9.7" data-path="chap-ANOVA.html"><a href="chap-ANOVA.html#métodos-no-paramétricos"><i class="fa fa-check"></i><b>9.7</b> Métodos no paramétricos</a></li>
<li class="chapter" data-level="9.8" data-path="chap-muestreo.html"><a href="chap-muestreo.html#guía-rápida"><i class="fa fa-check"></i><b>9.8</b> Guía rápida</a></li>
<li class="chapter" data-level="9.9" data-path="chap-distr.html"><a href="chap-distr.html#ejercicios"><i class="fa fa-check"></i><b>9.9</b> Ejercicios</a>
<ul>
<li class="chapter" data-level="" data-path="chap-distr.html"><a href="chap-distr.html#test"><i class="fa fa-check"></i>Test</a></li>
<li class="chapter" data-level="9.9.1" data-path="chap-ANOVA.html"><a href="chap-ANOVA.html#ejercicio"><i class="fa fa-check"></i><b>9.9.1</b> Ejercicio</a></li>
<li class="chapter" data-level="" data-path="chap-distr.html"><a href="chap-distr.html#respuestas-al-test"><i class="fa fa-check"></i>Respuestas al test</a></li>
<li class="chapter" data-level="9.9.2" data-path="chap-ANOVA.html"><a href="chap-ANOVA.html#soluciones-sucintas-del-ejercicio"><i class="fa fa-check"></i><b>9.9.2</b> Soluciones sucintas del ejercicio</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="10" data-path="chap-regresion.html"><a href="chap-regresion.html"><i class="fa fa-check"></i><b>10</b> Regresión lineal</a>
<ul>
<li class="chapter" data-level="10.1" data-path="chap-regresion.html"><a href="chap-regresion.html#sec:1"><i class="fa fa-check"></i><b>10.1</b> El modelo de regresión lineal en R</a></li>
<li class="chapter" data-level="10.2" data-path="chap-regresion.html"><a href="chap-regresion.html#intervalos-de-confianza-en-el-modelo-de-regresión-lineal"><i class="fa fa-check"></i><b>10.2</b> Intervalos de confianza en el modelo de regresión lineal</a></li>
<li class="chapter" data-level="10.3" data-path="chap-regresion.html"><a href="chap-regresion.html#sec:seleccion"><i class="fa fa-check"></i><b>10.3</b> Selección del modelo en base al ajuste de los datos</a></li>
<li class="chapter" data-level="10.4" data-path="chap-regresion.html"><a href="chap-regresion.html#sec:diagn"><i class="fa fa-check"></i><b>10.4</b> Diagnósticos de regresión</a></li>
<li class="chapter" data-level="10.5" data-path="chap-muestreo.html"><a href="chap-muestreo.html#guía-rápida"><i class="fa fa-check"></i><b>10.5</b> Guía rápida</a></li>
<li class="chapter" data-level="10.6" data-path="chap-distr.html"><a href="chap-distr.html#ejercicios"><i class="fa fa-check"></i><b>10.6</b> Ejercicios</a>
<ul>
<li class="chapter" data-level="" data-path="chap-distr.html"><a href="chap-distr.html#test"><i class="fa fa-check"></i>Test</a></li>
<li class="chapter" data-level="" data-path="chap-distr.html"><a href="chap-distr.html#respuestas-al-test"><i class="fa fa-check"></i>Respuestas al test</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="11" data-path="chap-clustering.html"><a href="chap-clustering.html"><i class="fa fa-check"></i><b>11</b> <em>Clustering</em> básico</a>
<ul>
<li class="chapter" data-level="11.1" data-path="chap-clustering.html"><a href="chap-clustering.html#método-de-k-medias-o-k-means"><i class="fa fa-check"></i><b>11.1</b> Método de k-medias o <em>k-means</em></a></li>
<li class="chapter" data-level="11.2" data-path="chap-clustering.html"><a href="chap-clustering.html#elección-del-número-de-clusters"><i class="fa fa-check"></i><b>11.2</b> Elección del número de <em>clusters</em></a></li>
<li class="chapter" data-level="11.3" data-path="chap-clustering.html"><a href="chap-clustering.html#métodos-jerárquicos-aglomerativos"><i class="fa fa-check"></i><b>11.3</b> Métodos jerárquicos aglomerativos</a></li>
<li class="chapter" data-level="11.4" data-path="chap-muestreo.html"><a href="chap-muestreo.html#guía-rápida"><i class="fa fa-check"></i><b>11.4</b> Guía rápida</a></li>
<li class="chapter" data-level="11.5" data-path="chap-distr.html"><a href="chap-distr.html#ejercicios"><i class="fa fa-check"></i><b>11.5</b> Ejercicios</a>
<ul>
<li class="chapter" data-level="" data-path="chap-distr.html"><a href="chap-distr.html#test"><i class="fa fa-check"></i>Test</a></li>
<li class="chapter" data-level="" data-path="chap-distr.html"><a href="chap-distr.html#respuestas-al-test"><i class="fa fa-check"></i>Respuestas al test</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="12" data-path="extras-de-r-markdown.html"><a href="extras-de-r-markdown.html"><i class="fa fa-check"></i><b>12</b> Extras de <em>R Markdown</em></a>
<ul>
<li class="chapter" data-level="12.1" data-path="extras-de-r-markdown.html"><a href="extras-de-r-markdown.html#parámetros-de-los-chunks-de-r"><i class="fa fa-check"></i><b>12.1</b> Parámetros de los <em>chunks</em> de R</a></li>
<li class="chapter" data-level="12.2" data-path="extras-de-r-markdown.html"><a href="extras-de-r-markdown.html#los-chunks-en-modo-línea"><i class="fa fa-check"></i><b>12.2</b> Los <em>chunks</em> en modo línea</a></li>
<li class="chapter" data-level="12.3" data-path="extras-de-r-markdown.html"><a href="extras-de-r-markdown.html#figuras"><i class="fa fa-check"></i><b>12.3</b> Figuras</a></li>
<li class="chapter" data-level="12.4" data-path="extras-de-r-markdown.html"><a href="extras-de-r-markdown.html#tablas"><i class="fa fa-check"></i><b>12.4</b> Tablas</a></li>
<li class="chapter" data-level="12.5" data-path="extras-de-r-markdown.html"><a href="extras-de-r-markdown.html#fórmulas-matemáticas"><i class="fa fa-check"></i><b>12.5</b> Fórmulas matemáticas</a></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">AprendeR: Parte II</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="chap:ANOVA" class="section level1" number="9">
<h1><span class="header-section-number">Lección 9</span> ANOVA básico</h1>
<p>En esta lección explicamos cómo efectuar con R los ANOVA básicos que se estudian en cursos introductorios de estadística inferencial: de uno y dos factores y de bloques completos aleatorios. El tema central de la lección son los aspectos técnicos del ANOVA con R y los tests posteriores de comparación de pares de medias. Incluimos además una sección con algunas instrucciones que permiten contrastar las condiciones necesarias sobre los datos para que un contraste ANOVA tenga sentido y una sección con algunos contrastes no paramétricos alternativos al ANOVA que se puedan usar justamente cuando no tiene sentido realizar un ANOVA.</p>
<div id="sec:modelos" class="section level2" number="9.1">
<h2><span class="header-section-number">9.1</span> Los modelos del ANOVA en R</h2>
<p>Los modelos a los que se aplica un ANOVA u otras muchas funciones, como por ejemplo la función <code>lm</code> para calcular la recta de regresión lineal, se especifican en R mediante <strong>fórmulas</strong>. El operador básico para construir una fórmula es la tilde, <code>~</code>. Las fórmulas suelen tener la forma <code>Y~modelo</code>, donde la <em>Y</em> es un vector y el <em>modelo</em> es una combinación de vectores o factores que representa el modelo con el que queremos explicar el vector <em>Y</em> (en palabras técnicas, al que queremos <strong>ajustar</strong> los datos del vector <em>Y</em>). Por ejemplo, para calcular la recta de regresión por mínimos cuadrados de un vector <em>Y</em> respecto de un vector <em>X</em>, usamos <code>lm(Y~X)</code>. Esto significa que aplicamos la función <code>lm</code> a la fórmula <code>Y~X</code> que indica que queremos explicar <em>Y</em> en función de <em>X</em>.</p>
<p>En los ANOVA que consideramos en esta lección se usan cuatro tipos de fórmulas. Concretamente, si <em>X</em> es una variable numérica y <em>F1</em> y <em>F2</em> son dos factores:</p>
<ul>
<li><p>La fórmula <code>X~F1</code> se usa para indicar el ANOVA de un factor, <em>F1</em>, de la variable <em>X</em>.</p></li>
<li><p>La fórmula <code>X~F1+F2</code> se usa para indicar el ANOVA de dos factores, <em>F1</em> y <em>F2</em>, de la variable <em>X</em>, sin tener en cuenta la interacción entre los factores; es decir, suponiendo que sus efectos se suman, sin que haya interacción entre los mismos. Es el tipo de fórmula que se usa en los ANOVA de bloques.</p></li>
<li><p>La fórmula <code>X~F1*F2</code> se usa para indicar el ANOVA de dos factores, <em>F1</em> y <em>F2</em>, de la variable <em>X</em>, teniendo en cuenta además la posible interacción entre estos factores.</p></li>
<li><p>La fórmula <code>X~F1:F2</code> se usa para indicar el ANOVA de un factor que tiene como niveles los pares ordenados de niveles de <em>F1</em> y <em>F2</em>.</p></li>
</ul>
<p>La función básica de R para realizar un ANOVA es <code>aov</code>. Su
sintaxis genérica es</p>
<div class="sourceCode" id="cb953"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb953-1"><a href="chap-ANOVA.html#cb953-1" aria-hidden="true" tabindex="-1"></a><span class="fu">aov</span>(fórmula, <span class="at">data=</span>...)</span></code></pre></div>
<p>con los argumentos siguientes:</p>
<ul>
<li><p><code>fórmula</code>: Una fórmula que especifique un modelo de ANOVA.</p></li>
<li><p><code>data</code>: Opcional, sirve para especificar, si es necesario, el <em>data frame</em> al que pertenecen las variables utilizadas en la fórmula.</p></li>
</ul>
<p>Así, por ejemplo, si tenemos un <em>data frame</em> llamado <code>DF</code>, con una variable numérica <code>X</code> y un factor <code>Fact</code>, para realizar el ANOVA de la variable <code>X</code> respecto del factor <code>Fact</code> con la función <code>aov</code> podríamos entrar</p>
<div class="sourceCode" id="cb954"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb954-1"><a href="chap-ANOVA.html#cb954-1" aria-hidden="true" tabindex="-1"></a><span class="fu">aov</span>(X<span class="sc">~</span>Fact, <span class="at">data=</span>DF) </span></code></pre></div>
<p>o</p>
<div class="sourceCode" id="cb955"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb955-1"><a href="chap-ANOVA.html#cb955-1" aria-hidden="true" tabindex="-1"></a><span class="fu">aov</span>(DF<span class="sc">$</span>X<span class="sc">~</span>DF<span class="sc">$</span>Fact)</span></code></pre></div>
<p>Otra posibilidad, que por ahora no usaremos pero sí más adelante, es aplicar la función <code>anova</code> (no la confundáis con <code>aov</code>) al resultado de <code>lm</code>. La sintaxis sería entonces</p>
<div class="sourceCode" id="cb956"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb956-1"><a href="chap-ANOVA.html#cb956-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(<span class="fu">lm</span>(fórmula, <span class="at">data=</span>...))</span></code></pre></div>
</div>
<div id="sec:ANOVA-1" class="section level2" number="9.2">
<h2><span class="header-section-number">9.2</span> ANOVA de un factor</h2>
<p>Para ilustrar el ANOVA de un factor con R utilizaremos un experimento en el que se quiso determinar si cuatro dietas concretas tenían alguna influencia en el tiempo de coagulación de la sangre en mamíferos: véase <em>Statistics for Experimenters</em> (2a edición), de G. P. Box, W. G. Hunter y J. S. Hunte (Wiley, 2005), p. 133. Para ello se escogieron 24 animales, se repartieron de manera aleatoria en 4 grupos de 6 ejemplares cada uno, y a cada grupo se le asignó de manera aleatoria una de las 4 dietas objeto de estudio, que indicaremos con A, B, C y D. Al cabo de un cierto tiempo se midió el tiempo de coagulación de la sangre en estos animales. Los resultados (redondeados a enteros) se muestran en la Tabla <a href="chap-ANOVA.html#tab:1">9.1</a>. Observad que estamos ante un diseño experimental de un solo factor: la dieta.</p>
<table>
<caption><span id="tab:1">Tabla 9.1: </span>Tiempos de coagulación bajo diferentes dietas.</caption>
<thead>
<tr class="header">
<th align="right">A</th>
<th align="right">B</th>
<th align="right">C</th>
<th align="right">D</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">62</td>
<td align="right">63</td>
<td align="right">68</td>
<td align="right">56</td>
</tr>
<tr class="even">
<td align="right">60</td>
<td align="right">67</td>
<td align="right">66</td>
<td align="right">62</td>
</tr>
<tr class="odd">
<td align="right">63</td>
<td align="right">71</td>
<td align="right">71</td>
<td align="right">60</td>
</tr>
<tr class="even">
<td align="right">59</td>
<td align="right">64</td>
<td align="right">67</td>
<td align="right">61</td>
</tr>
<tr class="odd">
<td align="right">63</td>
<td align="right">65</td>
<td align="right">68</td>
<td align="right">63</td>
</tr>
<tr class="even">
<td align="right">59</td>
<td align="right">66</td>
<td align="right">68</td>
<td align="right">64</td>
</tr>
</tbody>
</table>
<p>Para contrastar si los tiempos medios de coagulación son los mismos para las cuatro dietas o no, vamos a realizar un ANOVA de estos datos. Para ello, lo primero que tenemos que hacer es recoger los datos en un <em>data frame</em>, formado por una variable numérica con los valores de la tabla y un factor cuyos niveles sean las diferentes dietas, de manera que a cada valor en la variable numérica le corresponda la dieta con la que se obtuvo. Nosotros entraremos los datos de la tabla anterior por filas, y entonces el factor tendrá que ser</p>
<pre><code>A, B, C, D, A, B, C, D, A... </code></pre>
<p>Otra opción sería entrar los datos por columnas, y entonces entraríamos como factor</p>
<pre><code>A, A, A, A, A, A, B, B, B,... </code></pre>
<p>Entramos pues los datos de la tabla, por filas:</p>
<div class="sourceCode" id="cb959"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb959-1"><a href="chap-ANOVA.html#cb959-1" aria-hidden="true" tabindex="-1"></a>coag<span class="ot">=</span><span class="fu">c</span>(<span class="dv">62</span>,<span class="dv">63</span>,<span class="dv">68</span>,<span class="dv">56</span>,<span class="dv">60</span>,<span class="dv">67</span>,<span class="dv">66</span>,<span class="dv">62</span>,<span class="dv">63</span>,<span class="dv">71</span>,<span class="dv">71</span>,<span class="dv">60</span>,<span class="dv">59</span>,<span class="dv">64</span>,<span class="dv">67</span>,<span class="dv">61</span>,<span class="dv">63</span>,<span class="dv">65</span>,<span class="dv">68</span>,<span class="dv">63</span>,<span class="dv">59</span>,<span class="dv">66</span>,<span class="dv">68</span>,<span class="dv">64</span>)</span></code></pre></div>
<p>Definimos de manera adecuada el factor de las dietas, como 6 copias de la fila A,B,C,D:</p>
<div class="sourceCode" id="cb960"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb960-1"><a href="chap-ANOVA.html#cb960-1" aria-hidden="true" tabindex="-1"></a>diet<span class="ot">=</span><span class="fu">rep</span>(<span class="fu">c</span>(<span class="st">&quot;A&quot;</span>,<span class="st">&quot;B&quot;</span>,<span class="st">&quot;C&quot;</span>,<span class="st">&quot;D&quot;</span>), <span class="at">times=</span><span class="dv">6</span>)</span></code></pre></div>
<p>Finalmente, definimos el <em>data frame</em> y comprobamos que es correcto:</p>
<div class="sourceCode" id="cb961"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb961-1"><a href="chap-ANOVA.html#cb961-1" aria-hidden="true" tabindex="-1"></a>coagulacion<span class="ot">=</span><span class="fu">data.frame</span>(coag,diet)</span>
<span id="cb961-2"><a href="chap-ANOVA.html#cb961-2" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(coagulacion)</span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:	24 obs. of  2 variables:
##  $ coag: num  62 63 68 56 60 67 66 62 63 71 ...
##  $ diet: Factor w/ 4 levels &quot;A&quot;,&quot;B&quot;,&quot;C&quot;,&quot;D&quot;: 1 2 3 4 1 2 3 4 1 2 ...</code></pre>
<div class="sourceCode" id="cb963"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb963-1"><a href="chap-ANOVA.html#cb963-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(coagulacion)</span></code></pre></div>
<pre><code>##   coag diet
## 1   62    A
## 2   63    B
## 3   68    C
## 4   56    D
## 5   60    A
## 6   67    B</code></pre>
<p>Para analizar la igualdad de los tiempos medios de coagulación bajo las cuatro dietas, realizaremos un ANOVA de la variable <code>coag</code> separándola según (<strong>ajustándola a</strong>) el factor <code>diet</code>. Antes de empezar, es conveniente visualizar los datos para hacernos una idea de su distribución; por ejemplo, por medio de un diagrama de cajas con una caja por cada nivel:</p>
<div class="sourceCode" id="cb965"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb965-1"><a href="chap-ANOVA.html#cb965-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(coag<span class="sc">~</span>diet, <span class="at">data=</span>coagulacion)</span></code></pre></div>
<p>Observad que también hemos empleado una fórmula para indicar que queremos los diagramas de cajas de la variable <code>coag</code> separada por la variable <code>diet</code> del <em>data frame</em> <code>coagulacion</code>. Obtenemos la Figura <a href="chap-ANOVA.html#fig:241">9.1</a>, donde podemos ver que las medias muestrales para las dietas A y C son muy diferentes, y que en cambio seguramente no podríamos rechazar que las medias poblacionales de las dietas A y D sean iguales. Por lo tanto, el resultado que esperamos del ANOVA es que nos permita rechazar la hipótesis nula de que los cuatro tiempos medios de coagulación son iguales. Ahora bien, hasta que no realicemos el ANOVA no sabremos si las diferencias que observamos en este diagrama son estadísticamente significativas o no.</p>
<div class="figure" style="text-align: center"><span id="fig:241"></span>
<img src="AprendeR-Parte-II_files/figure-html/241-1.png" alt="Diagrama de cajas de los tiempos de coagulación según las diferentes dietas." width="480" />
<p class="caption">
Figura 9.1: Diagrama de cajas de los tiempos de coagulación según las diferentes dietas.
</p>
</div>
<p>Como hemos comentado, para realizar el ANOVA deseado, entramos:</p>
<div class="sourceCode" id="cb966"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb966-1"><a href="chap-ANOVA.html#cb966-1" aria-hidden="true" tabindex="-1"></a><span class="fu">aov</span>(coag<span class="sc">~</span>diet, <span class="at">data=</span>coagulacion)</span></code></pre></div>
<pre><code>## Call:
##    aov(formula = coag ~ diet, data = coagulacion)
## 
## Terms:
##                 diet Residuals
## Sum of Squares   228       112
## Deg. of Freedom    3        20
## 
## Residual standard error: 2.366432
## Estimated effects may be unbalanced</code></pre>
<p>El resultado no es la tabla del ANOVA. Para obtenerla, hay que aplicar <code>summary</code> al resultado de <code>aov</code>:</p>
<div class="sourceCode" id="cb968"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb968-1"><a href="chap-ANOVA.html#cb968-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">aov</span>(coag<span class="sc">~</span>diet, <span class="at">data=</span>coagulacion))</span></code></pre></div>
<pre><code>##             Df Sum Sq Mean Sq F value   Pr(&gt;F)    
## diet         3    228    76.0   13.57 4.66e-05 ***
## Residuals   20    112     5.6                     
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>El resultado de esta función <code>summary</code> es la tabla ANOVA usual:</p>
<ul>
<li><p>En la primera columna, dos etiquetas: el nombre del factor, en este caso <code>diet</code>, y <code>Residuals</code>, que representa los errores o residuos del ANOVA.</p></li>
<li><p>La segunda columna, etiquetada <code>Df</code>, nos da los grados de libertad correspondientes al factor (su número de niveles menos 1) y a los residuos (el número de individuos en la tabla, menos el número de niveles del factor).</p></li>
<li><p>La tercera columna, <code>Sum Sq</code>, nos muestra las sumas de los cuadrados del factor, <span class="math inline">\(SS_{Tr}\)</span>, y de los residuos, <span class="math inline">\(SS_E\)</span>.</p></li>
<li><p>La cuarta columna, <code>Mean Sq</code>, contiene las medias de los cuadrados del factor, <span class="math inline">\(MS_{Tr}\)</span>, y de los residuos, <span class="math inline">\(MS_E\)</span>.</p></li>
<li><p>La quinta columna, <code>F value</code>, nos da el valor
del estadístico de contraste.</p></li>
<li><p>En la sexta columna, <code>Pr(&gt;F)</code>, aparece el p-valor del contraste.</p></li>
<li><p>La séptima columna, sin etiqueta, indica el nivel de significación del p-valor según el código usual, explicado en la última línea del resultado. A mayor número de
asteriscos, más significativo es el p-valor y por lo tanto es más fuerte la evidencia
de que las medias comparadas no son todas iguales.</p></li>
</ul>
<p>En nuestro caso, hemos obtenido un p-valor del orden de <span class="math inline">\(4.7\times 10^{-5}\)</span>. Esto nos permite rechazar la hipótesis nula y concluir que no todos los tiempos medios de coagulación para las diferentes dietas consideradas son iguales, como intuíamos. Recordad que esto no significa que hayamos obtenido evidencia de que todos los tiempos medios de coagulación son diferentes, solo de que hay al menos un par de dietas que dan tiempos medios diferentes. Si ahora queremos determinar de qué pares de dietas se trata, tendremos que realizar algún test de comparaciones de pares de medias: véase la Sección <a href="chap-ANOVA.html#sec:pares">9.6</a>.</p>
<p>Para ahorrar espacio vertical, en lo que queda de lección vamos a eliminar los símbolos que marcan los niveles de significación de los p-valores. Para ello entramos la siguiente instrucción:</p>
<div class="sourceCode" id="cb970"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb970-1"><a href="chap-ANOVA.html#cb970-1" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">show.signif.stars=</span><span class="cn">FALSE</span>)</span></code></pre></div>
<p>A partir de ahora, y mientras no cerremos la sesión, estos símbolos no aparecerán más en las tablas ANOVA.</p>
<div class="sourceCode" id="cb971"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb971-1"><a href="chap-ANOVA.html#cb971-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">aov</span>(coag<span class="sc">~</span>diet, <span class="at">data=</span>coagulacion))</span></code></pre></div>
<pre><code>##             Df Sum Sq Mean Sq F value   Pr(&gt;F)
## diet         3    228    76.0   13.57 4.66e-05
## Residuals   20    112     5.6</code></pre>
<p>Si en algún momento de la sesión queréis volver a ver los códigos de significación, basta que entréis</p>
<div class="sourceCode" id="cb973"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb973-1"><a href="chap-ANOVA.html#cb973-1" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">show.signif.stars=</span><span class="cn">TRUE</span>)</span></code></pre></div>
<p>Como hemos comentado, una manera alternativa de realizar un ANOVA es mediante <code>anova(lm(...))</code>. Con esta construcción obtenemos directamente la tabla, sin necesidad de aplicarle <code>summary</code>.</p>
<div class="sourceCode" id="cb974"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb974-1"><a href="chap-ANOVA.html#cb974-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(<span class="fu">lm</span>(coag<span class="sc">~</span>diet, <span class="at">data=</span>coagulacion))</span></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Response: coag
##           Df Sum Sq Mean Sq F value    Pr(&gt;F)
## diet       3    228    76.0  13.571 4.658e-05
## Residuals 20    112     5.6</code></pre>
<p>Para extraer los datos de la tabla ANOVA obtenida con la función <code>summary(aov(...))</code>, y así poder operar directamente con ellos, hay que añadirle los sufijos adecuados. Consultemos su estructura.</p>
<div class="sourceCode" id="cb976"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb976-1"><a href="chap-ANOVA.html#cb976-1" aria-hidden="true" tabindex="-1"></a>tabla<span class="ot">=</span><span class="fu">summary</span>(<span class="fu">aov</span>(coag<span class="sc">~</span>diet, <span class="at">data=</span>coagulacion)) </span>
<span id="cb976-2"><a href="chap-ANOVA.html#cb976-2" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(tabla)</span></code></pre></div>
<pre><code>## List of 1
##  $ :Classes &#39;anova&#39; and &#39;data.frame&#39;:	2 obs. of  5 variables:
##   ..$ Df     : num [1:2] 3 20
##   ..$ Sum Sq : num [1:2] 228 112
##   ..$ Mean Sq: num [1:2] 76 5.6
##   ..$ F value: num [1:2] 13.6 NA
##   ..$ Pr(&gt;F) : num [1:2] 4.66e-05 NA
##  - attr(*, &quot;class&quot;)= chr [1:2] &quot;summary.aov&quot; &quot;listof&quot;</code></pre>
<p>Vemos que la tabla ANOVA obtenida con <code>summary(aov(...))</code> es una <code>list</code> formada por un solo objeto (<code>List of 1</code>), que a su vez es un <em>data frame</em> cuyas variables son las columnas numéricas de la tabla. Por lo tanto, para obtener una columna de estas, primero hemos de añadir el sufijo <code>[[1]]</code>, que extrae el <em>data frame</em> de la <code>list</code>, y a continuación el sufijo <code>$columna</code> correspondiente a la <code>columna</code> de la tabla ANOVA que nos interesa. Por ejemplo, la columna de las sumas de los cuadrados es:</p>
<div class="sourceCode" id="cb978"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb978-1"><a href="chap-ANOVA.html#cb978-1" aria-hidden="true" tabindex="-1"></a>tabla[[<span class="dv">1</span>]]<span class="sc">$</span><span class="st">&quot;Sum Sq&quot;</span></span></code></pre></div>
<pre><code>## [1] 228 112</code></pre>
<p>De manera similar, como el p-valor es el primer elemento de la columna <code>Pr(&gt;F)</code>, lo obtenemos con:</p>
<div class="sourceCode" id="cb980"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb980-1"><a href="chap-ANOVA.html#cb980-1" aria-hidden="true" tabindex="-1"></a>tabla[[<span class="dv">1</span>]]<span class="sc">$</span><span class="st">&quot;Pr(&gt;F)&quot;</span>[<span class="dv">1</span>]</span></code></pre></div>
<pre><code>## [1] 4.658471e-05</code></pre>
<p>Fijaos en que, como los nombres de estas columnas contienen espacios en blanco u otros símbolos no aceptados en los nombres de objetos de R (recordad la <a href="https://aprender-uib.github.io/AprendeR1/chap-vect.html">Lección 4 de la primera parte</a>), hay que especificarlos entre comillas.</p>
<p>El resultado de <code>anova(lm(...))</code> ya es directamente un <em>data frame</em>, por lo que para extraer los valores de la tabla ANOVA que produce podemos usar la sintaxis usual de los <em>data frames</em>.</p>
<div class="sourceCode" id="cb982"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb982-1"><a href="chap-ANOVA.html#cb982-1" aria-hidden="true" tabindex="-1"></a>tabla2<span class="ot">=</span><span class="fu">anova</span>(<span class="fu">lm</span>(coag<span class="sc">~</span>diet, <span class="at">data=</span>coagulacion))</span>
<span id="cb982-2"><a href="chap-ANOVA.html#cb982-2" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(tabla2)</span></code></pre></div>
<pre><code>## Classes &#39;anova&#39; and &#39;data.frame&#39;:	2 obs. of  5 variables:
##  $ Df     : int  3 20
##  $ Sum Sq : num  228 112
##  $ Mean Sq: num  76 5.6
##  $ F value: num  13.6 NA
##  $ Pr(&gt;F) : num  4.66e-05 NA
##  - attr(*, &quot;heading&quot;)= chr  &quot;Analysis of Variance Table\n&quot; &quot;Response: coag&quot;</code></pre>
<div class="sourceCode" id="cb984"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb984-1"><a href="chap-ANOVA.html#cb984-1" aria-hidden="true" tabindex="-1"></a>tabla2<span class="sc">$</span><span class="st">&quot;Sum Sq&quot;</span></span></code></pre></div>
<pre><code>## [1] 228 112</code></pre>
<div class="sourceCode" id="cb986"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb986-1"><a href="chap-ANOVA.html#cb986-1" aria-hidden="true" tabindex="-1"></a>tabla2<span class="sc">$</span><span class="st">&quot;Pr(&gt;F)&quot;</span>[<span class="dv">1</span>]</span></code></pre></div>
<pre><code>## [1] 4.658471e-05</code></pre>
<p>Veamos otro ejemplo de ANOVA de un factor.</p>

<div class="example">
<p><span id="exm:rabbits" class="example"><strong>Ejemplo 9.1  </strong></span>En un experimento, se estudió el efecto de seis dietas sobre el crecimiento de crías de conejo doméstico: véase <em>Experimental Design and Analysis</em>, de M. Lentner y T. Bishop (Valley Book Co. 1986), p. 428. Los datos obtenidos están recogidos en la tabla de datos <code>rabbit</code> del paquete <strong>faraway</strong>.</p>
</div>
<div class="sourceCode" id="cb988"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb988-1"><a href="chap-ANOVA.html#cb988-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(faraway)</span>
<span id="cb988-2"><a href="chap-ANOVA.html#cb988-2" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(rabbit)</span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:	30 obs. of  3 variables:
##  $ treat: Factor w/ 6 levels &quot;a&quot;,&quot;b&quot;,&quot;c&quot;,&quot;d&quot;,..: 6 2 3 3 1 2 3 6 4 1 ...
##  $ gain : num  42.2 32.6 35.2 40.9 40.1 38.1 34.6 34.3 37.5 44.9 ...
##  $ block: Factor w/ 10 levels &quot;b1&quot;,&quot;b10&quot;,&quot;b2&quot;,..: 1 1 1 3 3 3 4 4 4 5 ...</code></pre>
<p>Consultando la Ayuda de <code>rabbit</code> nos enteramos de que el factor <code>treat</code> indica la dieta, con niveles a,b,c,d,e,f, y de que la variable <code>gain</code> indica el aumento de peso; la variable <code>block</code>, que indica la camada, es irrelevante en este análisis concreto.</p>
<p>Si dibujamos el diagrama de cajas de los crecimientos para cada dieta, obtenemos la Figura <a href="chap-ANOVA.html#fig:242">9.2</a>, donde no observamos grandes diferencias en los crecimientos medios.</p>
<div class="sourceCode" id="cb990"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb990-1"><a href="chap-ANOVA.html#cb990-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(gain<span class="sc">~</span>treat, <span class="at">data=</span>rabbit)</span></code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:242"></span>
<img src="AprendeR-Parte-II_files/figure-html/242-1.png" alt="Diagrama de cajas de los crecimientos de crías de conejo  según las diferentes dietas." width="480" />
<p class="caption">
Figura 9.2: Diagrama de cajas de los crecimientos de crías de conejo según las diferentes dietas.
</p>
</div>
<p>Para determinar si hay diferencia en los aumentos medios de peso bajo las seis dietas, realizaremos un ANOVA de la variable <code>gain</code> ajustándola al factor <code>treat</code>.</p>
<div class="sourceCode" id="cb991"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb991-1"><a href="chap-ANOVA.html#cb991-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">aov</span>(gain<span class="sc">~</span>treat, <span class="at">data=</span>rabbit))</span></code></pre></div>
<pre><code>##             Df Sum Sq Mean Sq F value Pr(&gt;F)
## treat        5  293.4   58.68   1.886  0.134
## Residuals   24  746.5   31.10</code></pre>
<p>El p-valor es 0.134, lo que indica que, efectivamente, no hay evidencia de que las dietas den lugar a crecimientos medios diferentes. Si hubiéramos querido obtener solo el p-valor, podríamos haber entrado:</p>
<div class="sourceCode" id="cb993"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb993-1"><a href="chap-ANOVA.html#cb993-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">aov</span>(gain<span class="sc">~</span>treat, <span class="at">data=</span>rabbit))[[<span class="dv">1</span>]]<span class="sc">$</span><span class="st">&quot;Pr(&gt;F)&quot;</span>[<span class="dv">1</span>]</span></code></pre></div>
<pre><code>## [1] 0.1342124</code></pre>
<p>Es muy importante tener presente que, al usar las instrucciones <code>aov</code> o <code>anova(lm(...))</code> para realizar un ANOVA, se tiene que emplear un factor (o varios, en las próximas secciones) para separar la variable numérica en subpoblaciones. Veamos un ejemplo de lo que pasa si nos descuidamos en este punto.</p>

<div class="example">
<p><span id="exm:bliss" class="example"><strong>Ejemplo 9.2  </strong></span>En un experimento se estudió el efecto de la vitamina C en el crecimiento de los dientes: véase <em>The Statistics of Bioassay</em> de C. I. Bliss (Academic Press, 1952), p. 499-501. Se tomaron 60 cobayas y se trató cada uno de ellos con una combinación diferente de dosis de vitamina C (0.5, 1 o 2 mg) y método de suministro de la misma (mediante zumo de naranja o como ácido ascórbico) durante 6 semanas, y se cuantificó el crecimiento de sus dientes durante dicho período (más en concreto, se midió la longitud media de sus odontoblastos al final del mismo). El resultado es una tabla de 60 datos, que aparecen recogidos en el fichero <code>ToothGrowth</code> del paquete <strong>UsingR</strong>.</p>
</div>
<div class="sourceCode" id="cb995"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb995-1"><a href="chap-ANOVA.html#cb995-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(UsingR)</span>
<span id="cb995-2"><a href="chap-ANOVA.html#cb995-2" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(ToothGrowth)</span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:	60 obs. of  3 variables:
##  $ len : num  4.2 11.5 7.3 5.8 6.4 10 11.2 11.2 5.2 7 ...
##  $ supp: Factor w/ 2 levels &quot;OJ&quot;,&quot;VC&quot;: 2 2 2 2 2 2 2 2 2 2 ...
##  $ dose: num  0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 ...</code></pre>
<p>La Ayuda de <code>ToothGrowth</code> nos dice que la variable <code>len</code> contiene la longitud media final de los odontoblastos del animal, la variable <code>supp</code> el método de suministro (OJ indica zumo de naranja, <em>orange juice</em>, y VC indica ácido ascórbico puro, <em>vitamine C</em>), y la variable <code>dose</code> la dosis.</p>
<p>Nos vamos a olvidar por el momento de la variable <code>supp</code>, y vamos a contrastar si la dosis de vitamina C tiene influencia en el crecimiento de los dientes. Para ello realizamos un ANOVA de un factor.</p>
<div class="sourceCode" id="cb997"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb997-1"><a href="chap-ANOVA.html#cb997-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">aov</span>(len<span class="sc">~</span>dose, <span class="at">data=</span>ToothGrowth))</span></code></pre></div>
<pre><code>##             Df Sum Sq Mean Sq F value   Pr(&gt;F)
## dose         1   2224  2224.3   105.1 1.23e-14
## Residuals   58   1228    21.2</code></pre>
<p>¿Veis algo raro? Hemos comentado que se usaron tres dosis diferentes, por lo que el número de grados de libertad en la fila del factor, <code>dose</code>, tendría que ser 2, y no 1. ¿Qué ha pasado? Muy sencillo: <code>dose</code> es una variable numérica, y para usar <code>aov</code> el factor ha de ser eso, un factor. Así que lo primero que tenemos que hacer es convertir esta variable en un factor. Los haremos sobre un duplicado de la tabla <code>ToothGrowth</code> original, a la que llamaremos <code>ToothGrowth2</code>.</p>
<div class="sourceCode" id="cb999"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb999-1"><a href="chap-ANOVA.html#cb999-1" aria-hidden="true" tabindex="-1"></a>ToothGrowth2<span class="ot">=</span>ToothGrowth</span>
<span id="cb999-2"><a href="chap-ANOVA.html#cb999-2" aria-hidden="true" tabindex="-1"></a>ToothGrowth2<span class="sc">$</span>dose<span class="ot">=</span><span class="fu">as.factor</span>(ToothGrowth2<span class="sc">$</span>dose)</span>
<span id="cb999-3"><a href="chap-ANOVA.html#cb999-3" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(ToothGrowth2)</span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:	60 obs. of  3 variables:
##  $ len : num  4.2 11.5 7.3 5.8 6.4 10 11.2 11.2 5.2 7 ...
##  $ supp: Factor w/ 2 levels &quot;OJ&quot;,&quot;VC&quot;: 2 2 2 2 2 2 2 2 2 2 ...
##  $ dose: Factor w/ 3 levels &quot;0.5&quot;,&quot;1&quot;,&quot;2&quot;: 1 1 1 1 1 1 1 1 1 1 ...</code></pre>
<div class="sourceCode" id="cb1001"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1001-1"><a href="chap-ANOVA.html#cb1001-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">aov</span>(len<span class="sc">~</span>dose, <span class="at">data=</span>ToothGrowth2))</span></code></pre></div>
<pre><code>##             Df Sum Sq Mean Sq F value   Pr(&gt;F)
## dose         2   2426    1213   67.42 9.53e-16
## Residuals   57   1026      18</code></pre>
<p>Ahora está bien. El p-valor prácticamente 0 nos permite rechazar la hipótesis nula y concluir que hay dosis de vitamina C que dan lugar a diferentes crecimientos medios de los odontoblastos.</p>
</div>
<div id="anova-de-bloques-completos-aleatorios" class="section level2" number="9.3">
<h2><span class="header-section-number">9.3</span> ANOVA de bloques completos aleatorios</h2>
<p>Para ilustrar este tipo de ANOVA, analizaremos un experimento sobre producción de penicilina: vVéase <em>Practical Regression and Anova using R</em>, de J. Faraway, p. 186 (este texto se puede descargar de la página web <a href="https://cran.r-project.org/doc/contrib/Faraway-PRA.pdf" class="uri">https://cran.r-project.org/doc/contrib/Faraway-PRA.pdf</a>). En dicho experimento, se evaluaron cuatro procesos diferentes para determinar si había diferencias en su efectividad. Los cuatro procesos usaban una técnica de cultivo sumergido y empleaban agua de macerado de maíz como fuente de nitrógeno orgánico. Como la composición de este líquido puede afectar la producción final de penicilina, para evaluar los cuatro procesos se prepararon 5 mezclas diferentes de agua de macerado de maíz, de cada mezcla se tomaron 4 muestras y se asignaron de manera aleatoria a los cuatro procesos de producción. Los resultados obtenidos son los de la Tabla <a href="chap-ANOVA.html#tab:2">9.2</a>, y aparecen recogidos en la tabla de datos <code>penicillin</code> del paquete <strong>faraway</strong>.</p>
<table>
<caption><span id="tab:2">Tabla 9.2: </span>Producción de penicilina bajo diferentes procesos de producción y mezclas.</caption>
<thead>
<tr class="header">
<th align="right">Mezcla</th>
<th align="right">A</th>
<th align="right">B</th>
<th align="right">C</th>
<th align="right">D</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">1</td>
<td align="right">89</td>
<td align="right">88</td>
<td align="right">97</td>
<td align="right">94</td>
</tr>
<tr class="even">
<td align="right">2</td>
<td align="right">84</td>
<td align="right">77</td>
<td align="right">92</td>
<td align="right">79</td>
</tr>
<tr class="odd">
<td align="right">3</td>
<td align="right">81</td>
<td align="right">87</td>
<td align="right">87</td>
<td align="right">85</td>
</tr>
<tr class="even">
<td align="right">4</td>
<td align="right">87</td>
<td align="right">92</td>
<td align="right">89</td>
<td align="right">84</td>
</tr>
<tr class="odd">
<td align="right">5</td>
<td align="right">79</td>
<td align="right">81</td>
<td align="right">80</td>
<td align="right">88</td>
</tr>
</tbody>
</table>
<p>Observad que estamos ante un diseño experimental de bloques completos aleatorios. Los bloques son las mezclas de agua de macerado de maíz y los tratamientos (los procesos de producción) se han asignado de manera aleatoria a las unidades experimentales (las muestras) de cada bloque, de tal manera que cada bloque contiene exactamente una unidad experimental para cada tratamiento. Este es un ejemplo paradigmático de uso de bloques: para evitar la influencia de la variable “extraña” dada por la composición del agua de macerado de maíz, que puede influir en la producción, se escogen al azar unas mezclas y se prueban todos los procesos de manera independiente sobre cada mezcla.</p>
<p>Demos un vistazo a esta tabla de datos.</p>
<div class="sourceCode" id="cb1003"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1003-1"><a href="chap-ANOVA.html#cb1003-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(penicillin)</span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:	20 obs. of  3 variables:
##  $ treat: Factor w/ 4 levels &quot;A&quot;,&quot;B&quot;,&quot;C&quot;,&quot;D&quot;: 1 2 3 4 1 2 3 4 1 2 ...
##  $ blend: Factor w/ 5 levels &quot;Blend1&quot;,&quot;Blend2&quot;,..: 1 1 1 1 2 2 2 2 3 3 ...
##  $ yield: num  89 88 97 94 84 77 92 79 81 87 ...</code></pre>
<div class="sourceCode" id="cb1005"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1005-1"><a href="chap-ANOVA.html#cb1005-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(penicillin)</span></code></pre></div>
<pre><code>##   treat  blend yield
## 1     A Blend1    89
## 2     B Blend1    88
## 3     C Blend1    97
## 4     D Blend1    94
## 5     A Blend2    84
## 6     B Blend2    77</code></pre>
<p>Según la Ayuda de <code>penicillin</code>, la variable <code>treat</code> es el proceso de producción, con valores <code>A</code>, <code>B</code>, <code>C</code> y <code>D</code>; la variable <code>blend</code> es la mezcla usada (los bloques), con valores <code>Blend1</code> a <code>Blend5</code>; y la variable numérica <code>yield</code> es un valor que cuantifica la producción de penicilina.</p>
<p>Veamos cómo son los diagramas de cajas de la producción de penicilina separada por procesos de producción y por mezclas:</p>
<div class="sourceCode" id="cb1007"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1007-1"><a href="chap-ANOVA.html#cb1007-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(yield<span class="sc">~</span>treat, <span class="at">data=</span>penicillin)</span></code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-490"></span>
<img src="AprendeR-Parte-II_files/figure-html/unnamed-chunk-490-1.png" alt="Diagrama de cajas de la producción de penicilina bajo los diferentes procesos de producción." width="480" />
<p class="caption">
Figura 9.3: Diagrama de cajas de la producción de penicilina bajo los diferentes procesos de producción.
</p>
</div>
<div class="sourceCode" id="cb1008"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1008-1"><a href="chap-ANOVA.html#cb1008-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(yield<span class="sc">~</span>blend, <span class="at">data=</span>penicillin)</span></code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-491"></span>
<img src="AprendeR-Parte-II_files/figure-html/unnamed-chunk-491-1.png" alt="Diagrama de cajas de la producción de penicilina según las diferentes mezclas." width="480" />
<p class="caption">
Figura 9.4: Diagrama de cajas de la producción de penicilina según las diferentes mezclas.
</p>
</div>
<p>Vemos que no hay mucha diferencia entre las producciones para los diferentes procesos (sin tener en cuenta los bloques), y que sí que hay algunas diferencias en las producciones según la composición del agua de macerado de maíz; ya hemos comentado que es bien sabido que su composición influye en la producción.</p>
<p>Si realizamos un ANOVA de un factor para cada uno de estos dos factores por separado, obtenemos resultados consistentes con esta observación visual:</p>
<div class="sourceCode" id="cb1009"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1009-1"><a href="chap-ANOVA.html#cb1009-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">aov</span>(yield<span class="sc">~</span>treat, <span class="at">data=</span>penicillin))</span></code></pre></div>
<pre><code>##             Df Sum Sq Mean Sq F value Pr(&gt;F)
## treat        3     70   23.33   0.762  0.532
## Residuals   16    490   30.62</code></pre>
<div class="sourceCode" id="cb1011"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1011-1"><a href="chap-ANOVA.html#cb1011-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">aov</span>(yield<span class="sc">~</span>blend, <span class="at">data=</span>penicillin))</span></code></pre></div>
<pre><code>##             Df Sum Sq Mean Sq F value Pr(&gt;F)
## blend        4    264   66.00   3.345  0.038
## Residuals   15    296   19.73</code></pre>
<p>El p-valor del ANOVA separando por procesos de producción es 0.532, lo que indica que no podemos rechazar la hipótesis nula de que los procesos de producción tengan igual productividad media (sin tener en cuenta las mezclas), y el p-valor del ANOVA separando por mezclas es 0.038, lo que, con un nivel de significación del 5%, nos permite rechazar que todas las mezclas produzcan la misma cantidad media de penicilina. Pero precisamente, el hecho de que la mezcla influya en la producción es lo que hace que el primer ANOVA no sea fiable: a lo mejor el efecto de las mezclas enmascara las diferencias en las productividades de los procesos bajo estudio. Para determinarlo, vamos a realizar un ANOVA de bloques, es decir, de dos factores y efectos acumulados.</p>
<div class="sourceCode" id="cb1013"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1013-1"><a href="chap-ANOVA.html#cb1013-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">aov</span>(yield<span class="sc">~</span>treat<span class="sc">+</span>blend, <span class="at">data=</span>penicillin))</span></code></pre></div>
<pre><code>##             Df Sum Sq Mean Sq F value Pr(&gt;F)
## treat        3     70   23.33   1.239 0.3387
## blend        4    264   66.00   3.504 0.0407
## Residuals   12    226   18.83</code></pre>
<p>El p-valor que nos interesa en esta tabla es el de la fila <code>treat</code>: es 0.34, por lo que si tenemos en cuenta los bloques tampoco detectamos evidencia de que haya diferencias en la productividad media de los procesos estudiados.
El segundo p-valor de la tabla, 0.0407, es el del ANOVA de bloques que resulta de intercambiar los bloques y el tratamiento, tomando las mezclas como el factor a analizar y los procesos de producción como los bloques:</p>
<div class="sourceCode" id="cb1015"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1015-1"><a href="chap-ANOVA.html#cb1015-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">aov</span>(yield<span class="sc">~</span>blend<span class="sc">+</span>treat, <span class="at">data=</span>penicillin))</span></code></pre></div>
<pre><code>##             Df Sum Sq Mean Sq F value Pr(&gt;F)
## blend        4    264   66.00   3.504 0.0407
## treat        3     70   23.33   1.239 0.3387
## Residuals   12    226   18.83</code></pre>
<p>Podemos extraer los resultados de una tabla de un ANOVA de bloques generada por <code>summary(aov(...))</code> añadiendo los mismos sufijos que en el caso de un factor. Así, por ejemplo, los p-valores son:</p>
<div class="sourceCode" id="cb1017"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1017-1"><a href="chap-ANOVA.html#cb1017-1" aria-hidden="true" tabindex="-1"></a>tabla<span class="ot">=</span><span class="fu">summary</span>(<span class="fu">aov</span>(yield<span class="sc">~</span>treat<span class="sc">+</span>blend, <span class="at">data=</span>penicillin))</span>
<span id="cb1017-2"><a href="chap-ANOVA.html#cb1017-2" aria-hidden="true" tabindex="-1"></a>tabla[[<span class="dv">1</span>]]<span class="sc">$</span><span class="st">&quot;Pr(&gt;F)&quot;</span></span></code></pre></div>
<pre><code>## [1] 0.33865812 0.04074617         NA</code></pre>
<p>y si solo nos interesa el del factor <code>treat</code>:</p>
<div class="sourceCode" id="cb1019"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1019-1"><a href="chap-ANOVA.html#cb1019-1" aria-hidden="true" tabindex="-1"></a>tabla[[<span class="dv">1</span>]]<span class="sc">$</span><span class="st">&quot;Pr(&gt;F)&quot;</span>[<span class="dv">1</span>]</span></code></pre></div>
<pre><code>## [1] 0.3386581</code></pre>
<p>Veamos otro ejemplo de ANOVA de bloques completos aleatorios.</p>

<div class="example">
<p><span id="exm:notes" class="example"><strong>Ejemplo 9.3  </strong></span>Para estudiar si las diferentes actividades de evaluación llevadas a cabo en la asignatura de Matemáticas I tienen una dificultad similar (o mejor dicho, para mirar de confirmar nuestras sospechas de que no es así), escogimos una muestra aleatoria de 15 estudiantes de Biología o Bioquímica que se hubieran presentado al control 2 de dicha asignatura en el curso 2012-2013, y anotamos las notas obtenidas por estos estudiantes en los apartados de Tests, Talleres, Ejercicios de Casa, Control 1 y Control 2. Si obtenemos evidencia de que no todas las medias de las notas de las diferentes actividades fueron iguales, podremos concluir que no todas las actividades tienen la misma dificultad. Los datos obtenidos son los de la tabla <a href="chap-ANOVA.html#tab:3">9.3</a>.</p>
</div>
<table>
<caption><span id="tab:3">Tabla 9.3: </span>Notas obtenidas por 15 estudiantes en diferentes actividades de evaluación.</caption>
<thead>
<tr class="header">
<th align="right">Estudiante</th>
<th align="right">Tests</th>
<th align="right">Casa</th>
<th align="right">Talleres</th>
<th align="right">Control.1</th>
<th align="right">Control.2</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">1</td>
<td align="right">48</td>
<td align="right">42</td>
<td align="right">85</td>
<td align="right">31</td>
<td align="right">20</td>
</tr>
<tr class="even">
<td align="right">2</td>
<td align="right">94</td>
<td align="right">86</td>
<td align="right">100</td>
<td align="right">52</td>
<td align="right">48</td>
</tr>
<tr class="odd">
<td align="right">3</td>
<td align="right">98</td>
<td align="right">94</td>
<td align="right">93</td>
<td align="right">93</td>
<td align="right">90</td>
</tr>
<tr class="even">
<td align="right">4</td>
<td align="right">60</td>
<td align="right">58</td>
<td align="right">71</td>
<td align="right">66</td>
<td align="right">46</td>
</tr>
<tr class="odd">
<td align="right">5</td>
<td align="right">52</td>
<td align="right">56</td>
<td align="right">79</td>
<td align="right">64</td>
<td align="right">24</td>
</tr>
<tr class="even">
<td align="right">6</td>
<td align="right">78</td>
<td align="right">73</td>
<td align="right">84</td>
<td align="right">80</td>
<td align="right">95</td>
</tr>
<tr class="odd">
<td align="right">7</td>
<td align="right">84</td>
<td align="right">84</td>
<td align="right">94</td>
<td align="right">83</td>
<td align="right">70</td>
</tr>
<tr class="even">
<td align="right">8</td>
<td align="right">83</td>
<td align="right">76</td>
<td align="right">99</td>
<td align="right">51</td>
<td align="right">55</td>
</tr>
<tr class="odd">
<td align="right">9</td>
<td align="right">75</td>
<td align="right">55</td>
<td align="right">70</td>
<td align="right">85</td>
<td align="right">48</td>
</tr>
<tr class="even">
<td align="right">10</td>
<td align="right">24</td>
<td align="right">49</td>
<td align="right">57</td>
<td align="right">19</td>
<td align="right">55</td>
</tr>
<tr class="odd">
<td align="right">11</td>
<td align="right">47</td>
<td align="right">47</td>
<td align="right">64</td>
<td align="right">44</td>
<td align="right">35</td>
</tr>
<tr class="even">
<td align="right">12</td>
<td align="right">53</td>
<td align="right">42</td>
<td align="right">78</td>
<td align="right">50</td>
<td align="right">8</td>
</tr>
<tr class="odd">
<td align="right">13</td>
<td align="right">82</td>
<td align="right">93</td>
<td align="right">92</td>
<td align="right">66</td>
<td align="right">30</td>
</tr>
<tr class="even">
<td align="right">14</td>
<td align="right">66</td>
<td align="right">62</td>
<td align="right">74</td>
<td align="right">24</td>
<td align="right">56</td>
</tr>
<tr class="odd">
<td align="right">15</td>
<td align="right">49</td>
<td align="right">40</td>
<td align="right">74</td>
<td align="right">35</td>
<td align="right">21</td>
</tr>
</tbody>
</table>
<p>Como podemos observar, se trata de un experimento de bloques completos aleatorios: hemos escogido de manera aleatoria unos bloques (los estudiantes) y para cada estudiante hemos apuntado el valor de cada uno de los niveles del factor a estudiar (las notas en las diferentes actividades). Este diseño es el adecuado para este problema, puesto que hay una gran variabilidad en las notas obtenidas por estudiantes diferentes, desde matrículas a suspensos. Al tomar bloques, es decir, al considerar todas las notas de un conjunto aleatorio fijo de estudiantes, eliminamos el efecto de esta variabilidad.</p>
<p>Vamos a construir un <em>data frame</em> con estos datos. Este <em>data frame</em> tendrá tres variables: <code>notas</code>, con las notas obtenidas por los estudiantes; <code>acts</code>, con los tipos de actividades de evaluación realizados; y <code>bloques</code>, con el indicador de cada estudiante.
Entraremos las notas siguiendo las filas de la tabla anterior, y por lo tanto tenemos que construir estos dos factores entrando sus niveles en el orden adecuado: el factor <code>acts</code> ha de estar formado por 15 copias de la fila de actividades, y el factor <code>bloques</code> ha de estar formado por 5 copias de <code>1</code>, 5 copias de <code>2</code>, y así hasta 5 copias de <code>15</code>. Y recordad que <code>bloques</code> ha de ser un factor, puesto que queremos usarlo en un ANOVA.</p>
<div class="sourceCode" id="cb1021"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1021-1"><a href="chap-ANOVA.html#cb1021-1" aria-hidden="true" tabindex="-1"></a>notas<span class="ot">=</span><span class="fu">c</span>(<span class="dv">48</span>,<span class="dv">42</span>,<span class="dv">85</span>,<span class="dv">31</span>,<span class="dv">20</span>,<span class="dv">94</span>,<span class="dv">86</span>,<span class="dv">100</span>,<span class="dv">52</span>,<span class="dv">48</span>,<span class="dv">98</span>,<span class="dv">94</span>,<span class="dv">93</span>,<span class="dv">93</span>,<span class="dv">90</span>,<span class="dv">60</span>,<span class="dv">58</span>,</span>
<span id="cb1021-2"><a href="chap-ANOVA.html#cb1021-2" aria-hidden="true" tabindex="-1"></a>   <span class="dv">71</span>,<span class="dv">66</span>,<span class="dv">46</span>,<span class="dv">52</span>,<span class="dv">56</span>,<span class="dv">79</span>,<span class="dv">64</span>,<span class="dv">24</span>,<span class="dv">78</span>,<span class="dv">73</span>,<span class="dv">84</span>,<span class="dv">80</span>,<span class="dv">95</span>,<span class="dv">84</span>,<span class="dv">84</span>,<span class="dv">94</span>,<span class="dv">83</span>,<span class="dv">70</span>,<span class="dv">83</span>,<span class="dv">76</span>,</span>
<span id="cb1021-3"><a href="chap-ANOVA.html#cb1021-3" aria-hidden="true" tabindex="-1"></a>   <span class="dv">99</span>,<span class="dv">51</span>,<span class="dv">55</span>,<span class="dv">75</span>,<span class="dv">55</span>,<span class="dv">70</span>,<span class="dv">85</span>,<span class="dv">48</span>,<span class="dv">24</span>,<span class="dv">49</span>,<span class="dv">57</span>,<span class="dv">19</span>,<span class="dv">55</span>,<span class="dv">47</span>,<span class="dv">47</span>,<span class="dv">64</span>,<span class="dv">44</span>,<span class="dv">35</span>,<span class="dv">53</span>,<span class="dv">42</span>,</span>
<span id="cb1021-4"><a href="chap-ANOVA.html#cb1021-4" aria-hidden="true" tabindex="-1"></a>   <span class="dv">78</span>,<span class="dv">50</span>,<span class="dv">8</span>,<span class="dv">82</span>,<span class="dv">93</span>,<span class="dv">92</span>,<span class="dv">66</span>,<span class="dv">30</span>,<span class="dv">66</span>,<span class="dv">62</span>,<span class="dv">74</span>,<span class="dv">24</span>,<span class="dv">56</span>,<span class="dv">49</span>,<span class="dv">40</span>,<span class="dv">74</span>,<span class="dv">35</span>,<span class="dv">21</span>)</span>
<span id="cb1021-5"><a href="chap-ANOVA.html#cb1021-5" aria-hidden="true" tabindex="-1"></a>acts<span class="ot">=</span><span class="fu">rep</span>(<span class="fu">c</span>(<span class="st">&quot;Tests&quot;</span>,<span class="st">&quot;Casa&quot;</span>,<span class="st">&quot;Talleres&quot;</span>,<span class="st">&quot;Control 1&quot;</span>,<span class="st">&quot;Control 2&quot;</span>), <span class="at">times=</span><span class="dv">15</span>)</span>
<span id="cb1021-6"><a href="chap-ANOVA.html#cb1021-6" aria-hidden="true" tabindex="-1"></a>bloques<span class="ot">=</span><span class="fu">as.factor</span>(<span class="fu">rep</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">15</span>,<span class="at">each=</span><span class="dv">5</span>)) </span>
<span id="cb1021-7"><a href="chap-ANOVA.html#cb1021-7" aria-hidden="true" tabindex="-1"></a>notas.bloques<span class="ot">=</span><span class="fu">data.frame</span>(notas,acts,bloques)</span>
<span id="cb1021-8"><a href="chap-ANOVA.html#cb1021-8" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(notas.bloques)</span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:	75 obs. of  3 variables:
##  $ notas  : num  48 42 85 31 20 94 86 100 52 48 ...
##  $ acts   : Factor w/ 5 levels &quot;Casa&quot;,&quot;Control 1&quot;,..: 5 1 4 2 3 5 1 4 2 3 ...
##  $ bloques: Factor w/ 15 levels &quot;1&quot;,&quot;2&quot;,&quot;3&quot;,&quot;4&quot;,..: 1 1 1 1 1 2 2 2 2 2 ...</code></pre>
<div class="sourceCode" id="cb1023"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1023-1"><a href="chap-ANOVA.html#cb1023-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(notas.bloques)</span></code></pre></div>
<pre><code>##   notas      acts bloques
## 1    48     Tests       1
## 2    42      Casa       1
## 3    85  Talleres       1
## 4    31 Control 1       1
## 5    20 Control 2       1
## 6    94     Tests       2</code></pre>
<p>Vamos a dibujar los diagramas de cajas de las notas de las diferentes actividades y de los diferentes estudiantes:</p>
<div class="sourceCode" id="cb1025"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1025-1"><a href="chap-ANOVA.html#cb1025-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(notas.bloques<span class="sc">$</span>notas<span class="sc">~</span>notas.bloques<span class="sc">$</span>acts)</span></code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-498"></span>
<img src="AprendeR-Parte-II_files/figure-html/unnamed-chunk-498-1.png" alt="Diagrama de cajas de las notas en las diferentes actividades." width="480" />
<p class="caption">
Figura 9.5: Diagrama de cajas de las notas en las diferentes actividades.
</p>
</div>
<div class="sourceCode" id="cb1026"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1026-1"><a href="chap-ANOVA.html#cb1026-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(notas.bloques<span class="sc">$</span>notas<span class="sc">~</span>notas.bloques<span class="sc">$</span>bloques)</span></code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-499"></span>
<img src="AprendeR-Parte-II_files/figure-html/unnamed-chunk-499-1.png" alt="Diagrama de cajas de las notas de los estudiantes." width="480" />
<p class="caption">
Figura 9.6: Diagrama de cajas de las notas de los estudiantes.
</p>
</div>
<p>Podemos observar diferencias en las notas de algunas actividades: por ejemplo, las notas del control 2 son muy inferiores a las de los talleres. Asimismo, como nos temíamos, vemos una gran variabilidad en las notas de los estudiantes.</p>
<p>Realicemos ahora el ANOVA.</p>
<div class="sourceCode" id="cb1027"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1027-1"><a href="chap-ANOVA.html#cb1027-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">aov</span>(notas<span class="sc">~</span>acts<span class="sc">+</span>bloques, <span class="at">data=</span>notas.bloques))</span></code></pre></div>
<pre><code>##             Df Sum Sq Mean Sq F value   Pr(&gt;F)
## acts         4   9646  2411.5  13.133 1.31e-07
## bloques     14  19430  1387.9   7.558 1.47e-08
## Residuals   56  10283   183.6</code></pre>
<p>El p-valor que nos interesa es el de la primera fila, etiquetada con el factor cuyos niveles queremos comparar, en este caso <code>acts</code>. Este p-valor es muy pequeño, del orden de <span class="math inline">\(10^{-7}\)</span>, lo que es evidencia de que, como nos temíamos, no todas las notas medias de las actividades de evaluación son iguales.</p>
</div>
<div id="sec:ANOVA2" class="section level2" number="9.4">
<h2><span class="header-section-number">9.4</span> ANOVA de dos vías</h2>
<p>Para ilustrar el ANOVA de dos vías, es decir, de dos factores que pueden interacccionar, analizaremos en primer lugar los resultados de un experimento sobre el efecto de venenos y antídotos: véase “An analysis of transformations”, de G. Box y D. Cox, <em>J. Roy. Stat. Soc. Series B</em> 26 (1964), pp. 211-252; véase también <em>Practical Regression and Anova using R</em>, de J. Faraway, p. 182. En este experimento se usaron tres venenos y cuatro antídotos, y cada combinación de veneno y antídoto se administró a cuatro ratas elegidas de manera aleatoria e independiente. A continuación, se anotó el tiempo de supervivencia de cada animal, en unidades de 10 horas. Se trata, pues, de un diseño experimental de dos factores, en el que cada individuo ha sido asignado al azar a cada nivel de los dos factores. Por otro lado, no podemos descartar <em>a priori</em> que haya interacción entre venenos y antídotos, puesto que un antídoto puede ser más efectivo para un veneno que para otro.</p>
<p>El objetivo del experimento era contrastar la igualdad de los tiempos medios de supervivencia según el veneno, según el antídoto, y según la combinación veneno-antídoto. Los datos obtenidos en este experimento se han recogido en la tabla <code>rats</code> del paquete <strong>faraway</strong>.</p>
<p>Pero ahora tenemos un problema con este <em>data frame</em>. Si cargamos en una misma sesión varios paquetes que contengan objetos con el mismo nombre, R entiende en cada momento que ese nombre refiere al objeto del paquete que se haya cargado más recientemente. Como en esta lección hemos cargado el paquete <strong>UsingR</strong> después del paquete <strong>faraway</strong>, en estos momentos <code>rats</code> refiere a una tabla de datos del paquete <strong>survival</strong> que se ha cargado con <strong>UsingR</strong> y que no tiene nada que ver con los datos de este experimento. Una solución posible sería en este punto volver a cargar el paquete <strong>faraway</strong>. Otra opción más rápida es definir <code>rats</code> como el objeto <code>rats</code> de <strong>faraway</strong> por medio de la instrucción <code>rats=faraway::rats</code>. La construcción <code>paquete::objeto</code> invoca el <code>objeto</code> (una función, una tabla de datos,…) del <strong>paquete</strong> y sirve para eliminar ambigüedades como la que nos encontramos aquí. Además, tiene la ventaja de que no es necesario cargar el <strong>paquete</strong>, basta que esté instalado</p>
<p>Vamos a cargar y explorar estos datos.</p>
<div class="sourceCode" id="cb1029"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1029-1"><a href="chap-ANOVA.html#cb1029-1" aria-hidden="true" tabindex="-1"></a>rats<span class="ot">=</span>faraway<span class="sc">::</span>rats</span>
<span id="cb1029-2"><a href="chap-ANOVA.html#cb1029-2" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(rats)</span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:	48 obs. of  3 variables:
##  $ time  : num  0.31 0.82 0.43 0.45 0.45 1.1 0.45 0.71 0.46 0.88 ...
##  $ poison: Factor w/ 3 levels &quot;I&quot;,&quot;II&quot;,&quot;III&quot;: 1 1 1 1 1 1 1 1 1 1 ...
##  $ treat : Factor w/ 4 levels &quot;A&quot;,&quot;B&quot;,&quot;C&quot;,&quot;D&quot;: 1 2 3 4 1 2 3 4 1 2 ...</code></pre>
<div class="sourceCode" id="cb1031"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1031-1"><a href="chap-ANOVA.html#cb1031-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(rats)</span></code></pre></div>
<pre><code>##   time poison treat
## 1 0.31      I     A
## 2 0.82      I     B
## 3 0.43      I     C
## 4 0.45      I     D
## 5 0.45      I     A
## 6 1.10      I     B</code></pre>
<p>En la Ayuda de <code>rats</code> nos enteramos de que el factor <code>treat</code> contiene el antídoto, con niveles <code>A</code>, <code>B</code>, <code>C</code> y <code>D</code>; el factor <code>poison</code> contiene el veneno, con niveles <code>I</code>, <code>II</code> y <code>III</code>; y la variable numérica <code>time</code> contiene el tiempo de supervivencia de las ratas. Veamos cómo son los diagramas de cajas de estos tiempos, separados por venenos y por antídotos.</p>
<div class="sourceCode" id="cb1033"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1033-1"><a href="chap-ANOVA.html#cb1033-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(time<span class="sc">~</span>poison, <span class="at">data=</span>rats)</span></code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-502"></span>
<img src="AprendeR-Parte-II_files/figure-html/unnamed-chunk-502-1.png" alt="Diagrama de cajas de los tiempos de supervivencia según los venenos." width="480" />
<p class="caption">
Figura 9.7: Diagrama de cajas de los tiempos de supervivencia según los venenos.
</p>
</div>
<div class="sourceCode" id="cb1034"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1034-1"><a href="chap-ANOVA.html#cb1034-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(time<span class="sc">~</span>treat, <span class="at">data=</span>rats)</span></code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-503"></span>
<img src="AprendeR-Parte-II_files/figure-html/unnamed-chunk-503-1.png" alt="Diagrama de cajas de los tiempos de supervivencia según los antídotos" width="480" />
<p class="caption">
Figura 9.8: Diagrama de cajas de los tiempos de supervivencia según los antídotos
</p>
</div>
<p>Parece que hay diferencias en los tiempos medios de supervivencia tanto para los diferentes venenos como para los diferentes antídotos. Podemos también dibujar un diagrama de cajas de los tiempos de supervivencia separándolos por combinaciones de veneno y antídoto. La instrucción para hacerlo es la siguiente (observad la fórmula del argumento):</p>
<div class="sourceCode" id="cb1035"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1035-1"><a href="chap-ANOVA.html#cb1035-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(time<span class="sc">~</span>poison<span class="sc">:</span>treat, <span class="at">data=</span>rats)</span></code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-504"></span>
<img src="AprendeR-Parte-II_files/figure-html/unnamed-chunk-504-1.png" alt="Diagrama de cajas de los tiempos de supervivencia según las combinaciones de veneno y antídoto." width="480" />
<p class="caption">
Figura 9.9: Diagrama de cajas de los tiempos de supervivencia según las combinaciones de veneno y antídoto.
</p>
</div>
<p>El código para efectuar el ANOVA de dos vías del tiempo de supervivencia de las ratas bajo los efectos combinados de los venenos y los antídotos es el siguiente:</p>
<div class="sourceCode" id="cb1036"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1036-1"><a href="chap-ANOVA.html#cb1036-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">aov</span>(time<span class="sc">~</span>poison<span class="sc">*</span>treat, <span class="at">data=</span>rats))</span></code></pre></div>
<pre><code>##              Df Sum Sq Mean Sq F value   Pr(&gt;F)
## poison        2 1.0330  0.5165  23.222 3.33e-07
## treat         3 0.9212  0.3071  13.806 3.78e-06
## poison:treat  6 0.2501  0.0417   1.874    0.112
## Residuals    36 0.8007  0.0222</code></pre>
<p>En la última columna de la tabla que obtenemos, el primer p-valor es el del contraste de la igualdad de tiempos medios de supervivencia según el veneno (<code>poison</code>): su valor, <span class="math inline">\(3.3\times 10^{-7}\)</span>, nos permite concluir que estos tiempos medios no son todos iguales. El segundo p-valor es el del contraste de la igualdad de tiempos medios de supervivencia según el antídoto (<code>treat</code>): que valga <span class="math inline">\(3.8\times 10^{-6}\)</span> indica que estos tiempos medios tampoco son todos iguales. Finalmente, el tercer p-valor es el del contraste de interacción entre veneno y antídoto (<code>poison:treat</code>). Recordad que existe dicha <strong>interacción</strong> cuando los cambios en la variable de respuesta (en este ejemplo, el tiempo de supervivencia) originados por uno de los factores no son los mismos para diferentes niveles del otro factor: es decir, en el contexto de este experimento, si algún antídoto es más (o menos) efectivo contra algún veneno que contra otro. Como aquí este p-valor vale 0.112, no obtenemos evidencia estadísticamente significativa de dicha interacción: aceptamos que cada uno de los antídotos tiene un efecto similar sobre cada veneno (pero no todos los antídotos son igual de efectivos).</p>
<p>Observaréis que la tabla del ANOVA que produce R con esta fórmula no contiene la fila que permite contrastar si hay diferencia entre las medias de las poblaciones definidas por combinaciones de niveles, uno por cada factor: en este ejemplo, por las combinaciones de veneno y antídoto. Si se desea obtener esta fila, basta realizar un ANOVA de un factor que combine los dos factores del experimento.</p>
<div class="sourceCode" id="cb1038"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1038-1"><a href="chap-ANOVA.html#cb1038-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">aov</span>(time<span class="sc">~</span>poison<span class="sc">:</span>treat, <span class="at">data=</span>rats))</span></code></pre></div>
<pre><code>##              Df Sum Sq Mean Sq F value   Pr(&gt;F)
## poison:treat 11 2.2044 0.20040    9.01 1.99e-07
## Residuals    36 0.8007 0.02224</code></pre>
<p>Vemos que también hay diferencias estadísticamente significativas entre las combinaciones veneno–antídoto.</p>
<p>En el caso del ANOVA de dos vías, es interesante dibujar el <strong>gráfico de interacción</strong> entre factores.
En un gráfico de interacción del factor <span class="math inline">\(F_1\)</span> respecto del factor <span class="math inline">\(F_2\)</span> en el ANOVA de una variable numérica <span class="math inline">\(X\)</span> respecto de estos factores, se dibuja una línea quebrada para cada nivel de <span class="math inline">\(F_1\)</span>. Esta línea une, mediante segmentos, los valores medios que toma la variable <span class="math inline">\(X\)</span> en nuestra muestra para cada nivel de <span class="math inline">\(F_2\)</span> en el nivel de <span class="math inline">\(F_1\)</span> correspondiente. Si no hay ninguna interacción entre estos factores, las líneas resultantes serán paralelas. Cuanto más se alejen de ser paralelas, más evidencia de interacción habrá entre estos dos factores.</p>
<p>Estos gráficos de interacción se dibujan en R con la instrucción <code>interaction.plot</code> aplicada, por este orden, a los dos factores y la variable numérica. Así, pues, para obtener el gráfico de interacción de la variable antídoto respecto de la variable veneno en el ANOVA anterior, entraríamos la siguiente instrucción:</p>
<div class="sourceCode" id="cb1040"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1040-1"><a href="chap-ANOVA.html#cb1040-1" aria-hidden="true" tabindex="-1"></a><span class="fu">interaction.plot</span>(rats<span class="sc">$</span>treat, rats<span class="sc">$</span>poison, rats<span class="sc">$</span>time)</span></code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-507"></span>
<img src="AprendeR-Parte-II_files/figure-html/unnamed-chunk-507-1.png" alt="Gráfico de interacción del veneno y el antídoto." width="480" />
<p class="caption">
Figura 9.10: Gráfico de interacción del veneno y el antídoto.
</p>
</div>
<p>En el gráfico resultante observamos que los tres niveles del veneno producen líneas casi paralelas, aunque se observa una ligera interacción: la pendiente de la recta correspondiente al veneno II entre los valores medios de C y D es mucho mayor que la de las rectas correspondientes a los otros dos venenos, lo que indica que en el experimento el antídoto D ha sido menos efectivo contra el veneno II que contra los otros dos. No obstante, la diferencia no ha sido estadísticamente significativa.</p>
<p>Este diagrama no ha quedado muy bonito, ya que las variables aparecen en él con sus nombres completos, y los factores no aparecen en la leyenda ordenados alfabéticamente. Una posibilidad para mejorarlo es cambiar las etiquetas de los ejes y la leyenda (eliminándola con <code>legend=FALSE</code> y añadiéndola a nuestro gusto con la función <code>legend</code>). Ya que estamos, dibujaremos algo más gruesas las líneas. En general, la instrucción <code>interaction.plot</code> admite todos los parámetros de <code>plot</code> más algunos de específicos que podéis conocer consultando su Ayuda.</p>
<div class="sourceCode" id="cb1041"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1041-1"><a href="chap-ANOVA.html#cb1041-1" aria-hidden="true" tabindex="-1"></a><span class="fu">interaction.plot</span>(rats<span class="sc">$</span>treat, rats<span class="sc">$</span>poison, rats<span class="sc">$</span>time, <span class="at">legend=</span><span class="cn">FALSE</span>,</span>
<span id="cb1041-2"><a href="chap-ANOVA.html#cb1041-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">xlab=</span><span class="st">&quot;Antídoto&quot;</span>, <span class="at">ylab=</span><span class="st">&quot;Tiempo medio de supervivencia&quot;</span>, <span class="at">lwd=</span><span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">2</span>,<span class="dv">2</span>))</span>
<span id="cb1041-3"><a href="chap-ANOVA.html#cb1041-3" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">&quot;topright&quot;</span>, <span class="at">lty=</span><span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>, <span class="at">cex=</span><span class="fl">0.6</span>, <span class="at">title=</span><span class="st">&quot;Venenos&quot;</span>, <span class="at">legend=</span><span class="fu">c</span>(<span class="st">&quot;I&quot;</span>,<span class="st">&quot;II&quot;</span>,<span class="st">&quot;III&quot;</span>))</span></code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-508"></span>
<img src="AprendeR-Parte-II_files/figure-html/unnamed-chunk-508-1.png" alt="Gráfico de interacción del veneno y el antídoto." width="480" />
<p class="caption">
Figura 9.11: Gráfico de interacción del veneno y el antídoto.
</p>
</div>
<p>Veamos otro ejemplo de ANOVA de dos vías.</p>

<div class="example">
<p><span id="exm:tooth2" class="example"><strong>Ejemplo 9.4  </strong></span>En el Ejemplo <a href="chap-ANOVA.html#exm:bliss">9.2</a> hablábamos de un cierto experimento sobre el efecto de la vitamina C en el crecimiento de los dientes, y de la tabla de datos <code>ToothGrowth</code> del paquete <strong>UsingR</strong> que recoge los datos obtenidos en ese experimento. Ahora vamos a realizar un ANOVA de dos factores sobre esta tabla de datos para contrastar la influencia en dicho crecimiento de la dosis de vitamina C y del método de suministrarla, teniendo en cuenta que sus efectos pueden interaccionar.
Recordad de aquel ejemplo que, si queremos llevar a cabo un ANOVA sobre esta tabla que involucre la variable <code>dose</code> que contiene la dosis, primero hay que convertir esta variable en un factor. Volveremos a copiar la tabla <code>ToothGrowth</code> en una nueva tabla <code>ToothGrowth2</code> y modificaremos en esta tabla dicha variable.</p>
</div>
<div class="sourceCode" id="cb1042"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1042-1"><a href="chap-ANOVA.html#cb1042-1" aria-hidden="true" tabindex="-1"></a>ToothGrowth2<span class="ot">=</span>ToothGrowth </span>
<span id="cb1042-2"><a href="chap-ANOVA.html#cb1042-2" aria-hidden="true" tabindex="-1"></a>ToothGrowth2<span class="sc">$</span>dose<span class="ot">=</span><span class="fu">as.factor</span>(ToothGrowth2<span class="sc">$</span>dose)</span>
<span id="cb1042-3"><a href="chap-ANOVA.html#cb1042-3" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(ToothGrowth2)</span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:	60 obs. of  3 variables:
##  $ len : num  4.2 11.5 7.3 5.8 6.4 10 11.2 11.2 5.2 7 ...
##  $ supp: Factor w/ 2 levels &quot;OJ&quot;,&quot;VC&quot;: 2 2 2 2 2 2 2 2 2 2 ...
##  $ dose: Factor w/ 3 levels &quot;0.5&quot;,&quot;1&quot;,&quot;2&quot;: 1 1 1 1 1 1 1 1 1 1 ...</code></pre>
<p>Demos ahora una ojeada a los diagramas de cajas de esta tabla, separando las longitudes de los odontoblastos por dosis, por suministro y por ambos.</p>
<div class="sourceCode" id="cb1044"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1044-1"><a href="chap-ANOVA.html#cb1044-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(len<span class="sc">~</span>dose, <span class="at">data=</span>ToothGrowth2)</span></code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-510"></span>
<img src="AprendeR-Parte-II_files/figure-html/unnamed-chunk-510-1.png" alt="Diagrama de cajas de las longitudes de los odontoblastos según la dosis de vitamina C." width="480" />
<p class="caption">
Figura 9.12: Diagrama de cajas de las longitudes de los odontoblastos según la dosis de vitamina C.
</p>
</div>
<div class="sourceCode" id="cb1045"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1045-1"><a href="chap-ANOVA.html#cb1045-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(len<span class="sc">~</span>supp, <span class="at">data=</span>ToothGrowth2)</span></code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-511"></span>
<img src="AprendeR-Parte-II_files/figure-html/unnamed-chunk-511-1.png" alt="Diagrama de cajas de las longitudes de los odontoblastos según el método de suministro de vitamina C." width="480" />
<p class="caption">
Figura 9.13: Diagrama de cajas de las longitudes de los odontoblastos según el método de suministro de vitamina C.
</p>
</div>
<div class="sourceCode" id="cb1046"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1046-1"><a href="chap-ANOVA.html#cb1046-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(len<span class="sc">~</span>dose<span class="sc">:</span>supp, <span class="at">data=</span>ToothGrowth2)</span></code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-512"></span>
<img src="AprendeR-Parte-II_files/figure-html/unnamed-chunk-512-1.png" alt="Diagrama de cajas de las longitudes de los odontoblastos según la dosis y el método de suministro." width="480" />
<p class="caption">
Figura 9.14: Diagrama de cajas de las longitudes de los odontoblastos según la dosis y el método de suministro.
</p>
</div>
<p>Podemos observar diferencias tanto según la dosis como según el método de suministro. ¿Serán significativas?</p>
<div class="sourceCode" id="cb1047"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1047-1"><a href="chap-ANOVA.html#cb1047-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">aov</span>(len<span class="sc">~</span>supp<span class="sc">*</span>dose, <span class="at">data=</span>ToothGrowth2))</span></code></pre></div>
<pre><code>##             Df Sum Sq Mean Sq F value   Pr(&gt;F)
## supp         1  205.4   205.4  15.572 0.000231
## dose         2 2426.4  1213.2  92.000  &lt; 2e-16
## supp:dose    2  108.3    54.2   4.107 0.021860
## Residuals   54  712.1    13.2</code></pre>
<div class="sourceCode" id="cb1049"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1049-1"><a href="chap-ANOVA.html#cb1049-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">aov</span>(len<span class="sc">~</span>supp<span class="sc">:</span>dose, <span class="at">data=</span>ToothGrowth2))</span></code></pre></div>
<pre><code>##             Df Sum Sq Mean Sq F value Pr(&gt;F)
## supp:dose    5 2740.1   548.0   41.56 &lt;2e-16
## Residuals   54  712.1    13.2</code></pre>
<p>El resultado muestra que, efectivamente, hay diferencias significativas en el crecimiento de los dientes tanto según la dosis (p-valor prácticamente 0) como según el método de suministro (p-valor <span class="math inline">\(2\times 10^{-4}\)</span>) o la combinación de ambos (p-valor prácticamente 0), y también que hay evidencia estadística de interacción entre los dos factores (p-valor 0.022). El gráfico de interacción entre las dosis y el método de suministro que produce la instrucción siguiente refleja esta interacción: la línea correspondiente a la dosis de 2 mg no es paralela a las otras.</p>
<div class="sourceCode" id="cb1051"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1051-1"><a href="chap-ANOVA.html#cb1051-1" aria-hidden="true" tabindex="-1"></a><span class="fu">interaction.plot</span>(ToothGrowth2<span class="sc">$</span>supp, ToothGrowth2<span class="sc">$</span>dose, ToothGrowth2<span class="sc">$</span>len,  <span class="at">legend=</span><span class="cn">FALSE</span>,</span>
<span id="cb1051-2"><a href="chap-ANOVA.html#cb1051-2" aria-hidden="true" tabindex="-1"></a> <span class="at">xlab=</span><span class="st">&quot;Método de suministro&quot;</span>, <span class="at">ylab=</span><span class="st">&quot;Crecimiento medio&quot;</span>, <span class="at">lwd=</span><span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">2</span>,<span class="dv">2</span>))</span>
<span id="cb1051-3"><a href="chap-ANOVA.html#cb1051-3" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">&quot;topright&quot;</span>,<span class="at">lty=</span><span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>,<span class="at">cex=</span><span class="fl">0.6</span>,<span class="at">title=</span><span class="st">&quot;Dosis&quot;</span>,<span class="at">legend=</span><span class="fu">c</span>(<span class="st">&quot;0.5&quot;</span>,<span class="st">&quot;1&quot;</span>,<span class="st">&quot;2&quot;</span>))</span></code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-514"></span>
<img src="AprendeR-Parte-II_files/figure-html/unnamed-chunk-514-1.png" alt="Gráfico de interacción de la dosis de vitamina C y el método de suministro." width="480" />
<p class="caption">
Figura 9.15: Gráfico de interacción de la dosis de vitamina C y el método de suministro.
</p>
</div>
<p>El hecho de haber detectado interacción entre los dos factores hace que nos interese estudiar el efecto de los niveles de un factor en el otro. Esto se puede llevar a cabo mediante varios ANOVA de un factor.</p>
<p>En primer lugar, vamos estudiar, para cada método de suministro de vitamina C, si hay diferencias entre los crecimientos medios de los odontoblastos según la dosis cuando la vitamina C se suministra mediante ese método. Para ello vamos a realizar dos ANOVA de un factor, la dosis, sobre dos <em>data frames</em> extraídos de <code>ToothGrowth2</code>, uno con las filas donde <code>supp</code> toma el valor <code>OJ</code> y otro con las filas donde <code>supp</code> toma el valor <code>VC</code>. Vamos extraer estas subtablas de datos usando la instrucción <code>subset</code>. Recordad que la construcción</p>
<div class="sourceCode" id="cb1052"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1052-1"><a href="chap-ANOVA.html#cb1052-1" aria-hidden="true" tabindex="-1"></a><span class="fu">subset</span>(df, condición)</span></code></pre></div>
<p>define un <em>data frame</em> con las filas del <em>data frame</em> <code>df</code> que cumplen la <code>condición</code>.</p>
<div class="sourceCode" id="cb1053"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1053-1"><a href="chap-ANOVA.html#cb1053-1" aria-hidden="true" tabindex="-1"></a>TG.OJ<span class="ot">=</span><span class="fu">subset</span>(ToothGrowth2, supp<span class="sc">==</span><span class="st">&quot;OJ&quot;</span>)</span>
<span id="cb1053-2"><a href="chap-ANOVA.html#cb1053-2" aria-hidden="true" tabindex="-1"></a>TG.VC<span class="ot">=</span><span class="fu">subset</span>(ToothGrowth2, supp<span class="sc">==</span><span class="st">&quot;VC&quot;</span>)</span></code></pre></div>
<p>Ahora realizamos los dos ANOVA:</p>
<div class="sourceCode" id="cb1054"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1054-1"><a href="chap-ANOVA.html#cb1054-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">aov</span>(len<span class="sc">~</span>dose, <span class="at">data=</span>TG.OJ))</span></code></pre></div>
<pre><code>##             Df Sum Sq Mean Sq F value   Pr(&gt;F)
## dose         2  885.3   442.6   31.44 8.89e-08
## Residuals   27  380.1    14.1</code></pre>
<div class="sourceCode" id="cb1056"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1056-1"><a href="chap-ANOVA.html#cb1056-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">aov</span>(len<span class="sc">~</span>dose, <span class="at">data=</span>TG.VC))</span></code></pre></div>
<pre><code>##             Df Sum Sq Mean Sq F value   Pr(&gt;F)
## dose         2   1650   824.7   67.07 3.36e-11
## Residuals   27    332    12.3</code></pre>
<p>En ambos casos el p-valor es muy pequeño, lo que indica que para cada tipo de suministro de vitamina C, el crecimiento medio de los dientes varía con la dosis.</p>
<p>En este tipo de análisis, hay que tener en cuenta que si realizamos <span class="math inline">\(N\)</span> contrastes independientes en un mismo experimento, cada uno de ellos con un nivel de significación <span class="math inline">\(\alpha\)</span>, la probabilidad de rechazar en alguno de ellos la hipótesis nula si en todos es verdadera es
<span class="math display">\[
1-(1-\alpha)^N\approx N\alpha.
\]</span>
Por lo tanto, si queremos garantizar un nivel de significación global <span class="math inline">\(\alpha\)</span>, hay que realizar cada contraste con nivel de significación <span class="math inline">\(\alpha/N\)</span>. (Para ser exactos, si llamamos <span class="math inline">\(\alpha_c\)</span> al nivel de significación de cada contraste necesario para obtener un nivel de significación global <span class="math inline">\(\alpha\)</span>, se cumple que <span class="math inline">\(1-(1-\alpha_c)^N=\alpha\)</span>, de donde podemos despejar <span class="math inline">\(\alpha_c\)</span> y obtenemos <span class="math inline">\(\alpha_c=1-\sqrt[N]{1-\alpha}\)</span>, que es un poco mayor que <span class="math inline">\(\alpha/N\)</span>. Por ejemplo, para <span class="math inline">\(\alpha=0.05\)</span> y <span class="math inline">\(N=20\)</span> tenemos que <span class="math inline">\(\alpha_c=0.0341\)</span> mientras que <span class="math inline">\(\alpha/N=0.025\)</span>.) En este ejemplo concreto, si hubiéramos deseado un nivel de significación global 0.05, deberíamos haber realizado cada uno de los ANOVA con un nivel de significación 0.025, lo que no afecta a las conclusiones, ya que los p-valores han sido realmente muy pequeños.</p>
<p>También podemos estudiar, para cada dosis, si hay diferencias entre las medias de crecimiento según el método de suministro. Como solo hay dos métodos de suministro, para cada dosis tanto da realizar un ANOVA o un simple test t suponiendo que las varianzas son iguales (ya que es una de las condiciones para poder realizar el ANOVA).</p>
<div class="sourceCode" id="cb1058"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1058-1"><a href="chap-ANOVA.html#cb1058-1" aria-hidden="true" tabindex="-1"></a>TG.<span class="fl">0.5</span><span class="ot">=</span><span class="fu">subset</span>(ToothGrowth2, dose<span class="sc">==</span><span class="fl">0.5</span>)</span>
<span id="cb1058-2"><a href="chap-ANOVA.html#cb1058-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">aov</span>(len<span class="sc">~</span>supp, <span class="at">data=</span>TG.<span class="fl">0.5</span>))</span></code></pre></div>
<pre><code>##             Df Sum Sq Mean Sq F value Pr(&gt;F)
## supp         1  137.8  137.81   10.05 0.0053
## Residuals   18  246.9   13.72</code></pre>
<div class="sourceCode" id="cb1060"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1060-1"><a href="chap-ANOVA.html#cb1060-1" aria-hidden="true" tabindex="-1"></a>TG<span class="fl">.1</span><span class="ot">=</span><span class="fu">subset</span>(ToothGrowth2, dose<span class="sc">==</span><span class="dv">1</span>)</span>
<span id="cb1060-2"><a href="chap-ANOVA.html#cb1060-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">aov</span>(len<span class="sc">~</span>supp, <span class="at">data=</span>TG<span class="fl">.1</span>))</span></code></pre></div>
<pre><code>##             Df Sum Sq Mean Sq F value   Pr(&gt;F)
## supp         1  175.8  175.82   16.26 0.000781
## Residuals   18  194.6   10.81</code></pre>
<div class="sourceCode" id="cb1062"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1062-1"><a href="chap-ANOVA.html#cb1062-1" aria-hidden="true" tabindex="-1"></a>TG<span class="fl">.2</span><span class="ot">=</span><span class="fu">subset</span>(ToothGrowth2, dose<span class="sc">==</span><span class="dv">2</span>)</span>
<span id="cb1062-2"><a href="chap-ANOVA.html#cb1062-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">aov</span>(len<span class="sc">~</span>supp, <span class="at">data=</span>TG<span class="fl">.2</span>))</span></code></pre></div>
<pre><code>##             Df Sum Sq Mean Sq F value Pr(&gt;F)
## supp         1   0.03   0.032   0.002  0.964
## Residuals   18 270.61  15.034</code></pre>
<p>En este caso, para garantizar un nivel de significación global de 0.05, hay que realizar cada contraste con un nivel de significación de 0.05/3=0.017. Obtenemos evidencia de que hay diferencia en el crecimiento medio de los odontoblastos según el tipo de suministro solo para las dosis de 0.5 y 1 mg, que es donde hemos obtenido p-valores inferiores al nivel de significación.</p>
<p>Si la variable <code>dose</code> hubiera tenido, pongamos, 20 niveles en vez de 3, definir una subtabla para cada nivel y efectuar el ANOVA correspondiente hubiera sido muy largo. Para automatizar cálculos como estos, lo mejor es definir una función que calcule el p-valor del ANOVA de una variable respecto de un factor sobre la subtabla definida por un nivel variable <span class="math inline">\(x\)</span> de un segundo factor, y luego aplicar esta función al vector de los niveles de este segundo factor.
En este ejemplo concreto usaríamos el código siguiente.</p>
<div class="sourceCode" id="cb1064"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1064-1"><a href="chap-ANOVA.html#cb1064-1" aria-hidden="true" tabindex="-1"></a>Anova_dosis<span class="ot">=</span><span class="cf">function</span>(x){</span>
<span id="cb1064-2"><a href="chap-ANOVA.html#cb1064-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summary</span>(<span class="fu">aov</span>(len<span class="sc">~</span>supp, </span>
<span id="cb1064-3"><a href="chap-ANOVA.html#cb1064-3" aria-hidden="true" tabindex="-1"></a>       <span class="at">data=</span><span class="fu">subset</span>(ToothGrowth2, dose<span class="sc">==</span>x)))[[<span class="dv">1</span>]]<span class="sc">$</span><span class="st">&quot;Pr(&gt;F)&quot;</span>[<span class="dv">1</span>]</span>
<span id="cb1064-4"><a href="chap-ANOVA.html#cb1064-4" aria-hidden="true" tabindex="-1"></a>   }</span>
<span id="cb1064-5"><a href="chap-ANOVA.html#cb1064-5" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">sapply</span>(<span class="fu">levels</span>(ToothGrowth2<span class="sc">$</span>dose), <span class="at">FUN=</span>Anova_dosis),<span class="dv">4</span>)</span></code></pre></div>
<pre><code>##    0.5      1      2 
## 0.0053 0.0008 0.9637</code></pre>
</div>
<div id="condiciones-del-anova" class="section level2" number="9.5">
<h2><span class="header-section-number">9.5</span> Condiciones del ANOVA</h2>
<p>Los resultados de un ANOVA nos permiten extraer conclusiones solo si las poblaciones a las que se aplica cumplen una serie de condiciones; las dos básicas son la normalidad y la igualdad de varianzas. La condición de normalidad requiere que cada nivel de cada factor defina una distribución normal, es decir, que cada muestra aleatoria simple de un tratamiento provenga de una población normal. La condición de igualdad de varianzas requiere que todas estas distribuciones tengan la misma varianza.</p>
<p>En la Lección <a href="chap-bondad.html#chap:bondad">6</a> ya estudiamos algunos tests específicos de normalidad: los tests de Kolmogorov-Smirnov-Lillliefors,
de Anderson-Darling, de Shapiro-Wilk y de D’Agostino-Pearson. Cada uno tiene sus ventajas y sus inconvenientes: el primero es muy popular, por ser una variante del test de Kolmogorov-Smirnov; el segundo, detecta mejor las discrepancias en los extremos; el test de Shapiro-Wilk es más potente para muestras grandes y menos sensible a repeticiones que los dos anteriores; y el test de D’Agostino-Pearson permite repeticiones de datos, pero no se puede usar con muestras de tamaño inferior a 20.</p>
<p>Veamos algunos ejemplos de aplicación de tests de normalidad en el contexto de un ANOVA.</p>

<div class="example">
<p><span id="exm:SW-auto" class="example"><strong>Ejemplo 9.5  </strong></span>Queremos contrastar si los tiempos de coagulación bajo cuatro dietas dados en la Tabla <a href="chap-ANOVA.html#tab:1">9.1</a> provienen de distribuciones normales. Como hay algunas repeticiones de valores en las columnas de la tabla y no llegan a los 20 valores cada una, usaremos el test de Shapiro-Wilk que, recordemos, está implementado en la función <code>shapiro.test</code>. Teníamos los datos guardados en un <em>data frame</em> llamado coagulacion.</p>
</div>
<div class="sourceCode" id="cb1066"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1066-1"><a href="chap-ANOVA.html#cb1066-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(coagulacion)</span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:	24 obs. of  2 variables:
##  $ coag: num  62 63 68 56 60 67 66 62 63 71 ...
##  $ diet: Factor w/ 4 levels &quot;A&quot;,&quot;B&quot;,&quot;C&quot;,&quot;D&quot;: 1 2 3 4 1 2 3 4 1 2 ...</code></pre>
<p>Apliquemos la función <code>shapiro.test</code> a los tiempos de coagulación para cada dieta:</p>
<div class="sourceCode" id="cb1068"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1068-1"><a href="chap-ANOVA.html#cb1068-1" aria-hidden="true" tabindex="-1"></a>coagA<span class="ot">=</span>coagulacion[coagulacion<span class="sc">$</span>diet<span class="sc">==</span><span class="st">&quot;A&quot;</span>,]<span class="sc">$</span>coag</span>
<span id="cb1068-2"><a href="chap-ANOVA.html#cb1068-2" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(coagA)<span class="sc">$</span>p.value</span></code></pre></div>
<pre><code>## [1] 0.1130298</code></pre>
<div class="sourceCode" id="cb1070"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1070-1"><a href="chap-ANOVA.html#cb1070-1" aria-hidden="true" tabindex="-1"></a>coagB<span class="ot">=</span>coagulacion[coagulacion<span class="sc">$</span>diet<span class="sc">==</span><span class="st">&quot;B&quot;</span>,]<span class="sc">$</span>coag</span>
<span id="cb1070-2"><a href="chap-ANOVA.html#cb1070-2" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(coagB)<span class="sc">$</span>p.value</span></code></pre></div>
<pre><code>## [1] 0.5227052</code></pre>
<div class="sourceCode" id="cb1072"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1072-1"><a href="chap-ANOVA.html#cb1072-1" aria-hidden="true" tabindex="-1"></a>coagC<span class="ot">=</span>coagulacion[coagulacion<span class="sc">$</span>diet<span class="sc">==</span><span class="st">&quot;C&quot;</span>,]<span class="sc">$</span>coag</span>
<span id="cb1072-2"><a href="chap-ANOVA.html#cb1072-2" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(coagC)<span class="sc">$</span>p.value</span></code></pre></div>
<pre><code>## [1] 0.2375366</code></pre>
<div class="sourceCode" id="cb1074"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1074-1"><a href="chap-ANOVA.html#cb1074-1" aria-hidden="true" tabindex="-1"></a>coagD<span class="ot">=</span>coagulacion[coagulacion<span class="sc">$</span>diet<span class="sc">==</span><span class="st">&quot;D&quot;</span>,]<span class="sc">$</span>coag</span>
<span id="cb1074-2"><a href="chap-ANOVA.html#cb1074-2" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(coagD)<span class="sc">$</span>p.value</span></code></pre></div>
<pre><code>## [1] 0.5227052</code></pre>
<p>Los cuatro p-valores que obtenemos son grandes, mayores que 0.05, lo que quiere decir que en ninguno de los cuatro tests podemos rechazar la hipótesis nula: no hay evidencia de que los tiempos de coagulación bajo alguna de las cuatro dietas no sigan leyes normales, por lo que aceptamos que sí las siguen. Recordad además que, como hemos efectuado cuatro contrastes, para garantizar un nivel de significación global de 0.05 hemos de realizar cada uno con un nivel de significación de 0.05/4=0.0125: es decir, que con p-valores por encima de este nivel de significación no podríamos rechazar ninguna hipótesis nula.</p>
<p>¿Cómo podríamos haber automatizado el cálculo de estos p-valores, para no tener que definir “a mano” cada vector de tiempos de coagulación? Con el código siguiente, donde definimos una función <code>Test.SW</code> que calcula el p-valor del test de Shapiro-Wilk y la aplicamos con un <code>aggregate</code> a los tiempos de coagulación del <em>data frame</em> <code>coagulacion</code> separados según la dieta. De esta manera obtenemos un <em>data frame</em> cuya columna <code>coag</code> contiene, para cada nivel de <code>diet</code>, el p-valor del test de Shapiro-Wilk para los tiempos de coagulación de la dieta correspondiente.</p>
<div class="sourceCode" id="cb1076"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1076-1"><a href="chap-ANOVA.html#cb1076-1" aria-hidden="true" tabindex="-1"></a>Test.SW<span class="ot">=</span><span class="cf">function</span>(x){<span class="fu">shapiro.test</span>(x)<span class="sc">$</span>p.value}</span>
<span id="cb1076-2"><a href="chap-ANOVA.html#cb1076-2" aria-hidden="true" tabindex="-1"></a><span class="fu">aggregate</span>(coag<span class="sc">~</span>diet, <span class="at">data=</span>coagulacion,<span class="at">FUN=</span>Test.SW)</span></code></pre></div>
<pre><code>##   diet      coag
## 1    A 0.1130298
## 2    B 0.5227052
## 3    C 0.2375366
## 4    D 0.5227052</code></pre>

<div class="example">
<p><span id="exm:unnamed-chunk-523" class="example"><strong>Ejemplo 9.6  </strong></span>Vamos a contrastar si en el ANOVA de dos vías del ejemplo de venenos y antídotos explicado en la Sección <a href="chap-ANOVA.html#sec:ANOVA2">9.4</a> se satisface que cada combinación de veneno y antídoto define una población normal. Para ello, en principio deberíamos repetir 12 veces, una para cada combinación de veneno y antídoto, un par de instrucciones como las siguientes:</p>
</div>
<div class="sourceCode" id="cb1078"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1078-1"><a href="chap-ANOVA.html#cb1078-1" aria-hidden="true" tabindex="-1"></a>time.I.A<span class="ot">=</span>rats[rats<span class="sc">$</span>poison<span class="sc">==</span><span class="st">&quot;I&quot;</span> <span class="sc">&amp;</span> rats<span class="sc">$</span>treat<span class="sc">==</span><span class="st">&quot;A&quot;</span>, ]<span class="sc">$</span>time</span>
<span id="cb1078-2"><a href="chap-ANOVA.html#cb1078-2" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(time.I.A)<span class="sc">$</span>p.value</span></code></pre></div>
<pre><code>## [1] 0.07414486</code></pre>
<p>Para evitarnos trabajo, vamos a usar la estrategia explicada al final del ejemplo anterior: aplicaremos la función <code>Test.SW</code> que hemos definido en dicho ejemplo a la variable numérica <code>time</code> del <em>data frame</em> <code>rats</code> separándola por las combinaciones de veneno y antídoto.</p>
<div class="sourceCode" id="cb1080"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1080-1"><a href="chap-ANOVA.html#cb1080-1" aria-hidden="true" tabindex="-1"></a><span class="fu">aggregate</span>(time<span class="sc">~</span>poison<span class="sc">:</span>treat, <span class="at">data=</span>rats, <span class="at">FUN=</span>Test.SW)</span></code></pre></div>
<pre><code>##    poison treat       time
## 1       I     A 0.07414486
## 2      II     A 0.84756406
## 3     III     A 0.57735490
## 4       I     B 0.69983383
## 5      II     B 0.70083721
## 6     III     B 0.17057001
## 7       I     C 0.40503490
## 8      II     C 0.92091109
## 9     III     C 0.97187706
## 10      I     D 0.42739119
## 11     II     D 0.90650963
## 12    III     D 0.68893644</code></pre>
<p>Todos los p-valores que obtenemos son mayores que 0.05 (y de hecho, para garantizar un nivel de significación global de 0.05, deberíamos realizar cada test de Shapiro-Wilk con un nivel de significación 0.05/12=0.0042), por lo que no podemos rechazar que
todas las combinaciones de veneno y antídoto definan unos tiempos de supervivencia que sigan leyes normales.</p>
<p>Pasemos al contraste de igualdad de varianzas (su nombre técnico es <strong>contraste de homocedasticidad</strong>), en el que usaremos el llamado <strong>test de Bartlett</strong>. Supongamos, para fijar ideas, que tenemos <span class="math inline">\(k\)</span> vectores numéricos
<span class="math display">\[
x_i=(x_{i1},x_{i2},\ldots,x_{in_i}),\quad i=1,\ldots, k,
\]</span>
cada uno de los cuales es una muestra aleatoria simple de una variable aleatoria normal (se supone que lo hemos contrastado previamente) de varianza <span class="math inline">\(\sigma_i^2\)</span>. El contraste que queremos realizar es:
<span class="math display">\[
\left\{
\begin{array}{ll}
H_0: &amp; \sigma_1^2 = \cdots = \sigma_k^2\\
H_1: &amp; \mbox{$\sigma_i^2 \neq \sigma_j^2$ para algunos $i, j$}
\end{array}
\right.
\]</span>
Para realizar este contraste, se usa el <strong>estadístico de Bartlett</strong>:
<span class="math display">\[
K^2 = \frac{ (N-k)\ln (\widetilde{s}_p^2)-\sum_{i=1}^k (n_i -1)\ln (\widetilde{s}_i^2)}{ 1+\frac{1}{3(k-1)}\left(\sum_{i=1}^k \left(\frac{1}{n_i
-1}\right)-\frac{1}{N-k}\right)},
\]</span>
donde
<span class="math display">\[
N=\sum_{i=1}^k n_i,\quad \widetilde{s}_p^2 = \frac{\sum_{i=1}^k (n_i -1) \widetilde{s}_i^2}{N-k},\quad \widetilde{s}_i^2 =\frac{\sum_{j=1}^{n_i} (x_{ij}-\overline{x}_{i})^2}{n_i -1},\ i=1,\ldots,k.
\]</span>
Si las variables poblacionales son normales, este estadístico sigue aproximadamente una distribución <span class="math inline">\(\chi^2_{k-1}\)</span>, y si la hipótesis nula es verdadera, su valor esperado es pequeño (puesto que, en este caso, los valores esperados de <span class="math inline">\(\widetilde{s}_1^2,\ldots, \widetilde{s}_k^2\)</span> y <span class="math inline">\(\widetilde{s}_p^2\)</span> son todos iguales). El p-valor del contraste es entonces <span class="math inline">\(P(\chi^2_{k-1} &gt; K^2)\)</span>.</p>
<p>R tiene una función que efectúa este test, <code>bartlett.test</code>, y puede aplicarse a una fórmula. Por ejemplo, para contrastar si las tres dietas en el ejemplo de la coagulación de la Sección <a href="chap-ANOVA.html#sec:ANOVA-1">9.2</a> definen poblaciones con la misma varianza, podemos entrar</p>
<div class="sourceCode" id="cb1082"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1082-1"><a href="chap-ANOVA.html#cb1082-1" aria-hidden="true" tabindex="-1"></a><span class="fu">bartlett.test</span>(coag<span class="sc">~</span>diet, <span class="at">data=</span>coagulacion)</span></code></pre></div>
<pre><code>## 
## 	Bartlett test of homogeneity of variances
## 
## data:  coag by diet
## Bartlett&#39;s K-squared = 1.946, df = 3, p-value = 0.5837</code></pre>
<p>Como el p-valor es alto, concluimos que las varianzas de los tiempos de coagulación bajo las tres dietas son la misma.</p>
<p>En los ANOVA de dos vías, se ha de comprobar la igualdad de varianzas para las combinaciones de niveles de los dos factores. En la fórmula que se entra al <code>bartlett.test</code> esta combinación no se puede especificar con <code>:</code>, como hemos hecho hasta ahora, sino con <code>interaction</code>. Por ejemplo, para contrastar por medio del test de Bartlett si las 12 combinaciones veneno-dieta en el ejemplo de venenos y antídotos explicado en la Sección <a href="chap-ANOVA.html#sec:ANOVA2">9.4</a> tienen la misma varianza, tenemos que entrar:</p>
<div class="sourceCode" id="cb1084"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1084-1"><a href="chap-ANOVA.html#cb1084-1" aria-hidden="true" tabindex="-1"></a><span class="fu">bartlett.test</span>(time<span class="sc">~</span><span class="fu">interaction</span>(poison,treat), <span class="at">data=</span>rats)</span></code></pre></div>
<pre><code>## 
## 	Bartlett test of homogeneity of variances
## 
## data:  time by interaction(poison, treat)
## Bartlett&#39;s K-squared = 45.137, df = 11, p-value = 4.59e-06</code></pre>
<p>Obtenemos un p-valor de <span class="math inline">\(4.6\times 10^{-6}\)</span>, por lo tanto, hemos de rechazar la igualdad de varianzas: las conclusiones de ese ANOVA de dos vías no tienen en principio ninguna validez, puesto que hay evidencia de que no se cumple una de las condiciones para realizarlo.</p>
<p>Otros tests de igualdad de varianzas son el de Fligner-Killeen, implementado en la función
<code>fligner.test</code> (y que tiene la misma particularidad que <code>bartlett.test</code> a la hora de especificar combinaciones de factores) y el test de Levene, implementado en la función
<code>leveneTest</code> del paquete <strong>car</strong> (donde las combinaciones de factores sí que se pueden especificar con <code>:</code>). En cada caso, el test produce un p-valor con el significado usual. El test de Levene es muy popular, porque no requiere que las poblaciones sean normales, pero en el contexto del ANOVA esta propiedad no tiene ningún interés; además, cuando las poblaciones son normales, el test de Bartlett es más potente que el de Levene.</p>
</div>
<div id="sec:pares" class="section level2" number="9.6">
<h2><span class="header-section-number">9.6</span> Comparaciones de pares de medias</h2>
<p>Si en un ANOVA hemos rechazado la hipótesis nula de la igualdad de todas las medias, es posible que nos interese determinar qué medias son diferentes. Para ello podemos llevar a cabo algunos tests. En esta sección explicamos las instrucciones de R para tres de ellos.</p>
<div id="tests-t-por-parejas" class="section level3" number="9.6.1">
<h3><span class="header-section-number">9.6.1</span> Tests t por parejas</h3>
<p>En los tests t por parejas, realizamos un contraste de medias para cada par de niveles del factor, teniendo en cuenta que, para garantizar un nivel de significación global <span class="math inline">\(\alpha\)</span>, se ha de ajustar el nivel de significación de cada test. Hay diversos métodos para llevar a cabo este ajuste: los más populares son el método de Bonferroni, el de Holm, que es más potente, y el de Hochberg, que, para contrastes ANOVA que no sean de bloques, aún tiene mayor potencia.</p>
<p>La función que efectúa tests t por parejas es <code>pairwise.t.test</code>. Su sintaxis es</p>
<div class="sourceCode" id="cb1086"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1086-1"><a href="chap-ANOVA.html#cb1086-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pairwise.t.test</span>(var.numérica, factor, <span class="at">paired=</span>..., <span class="at">p.adjust.method=</span>...)</span></code></pre></div>
<p>El valor de <code>p.adjust.method</code> es el método de ajuste de p-valores que deseamos usar, y se ha de entrar entrecomillado. El valor por defecto es el de Holm, indicado por <code>"holm"</code> aunque no es necesario especificarlo. Para usar el de Bonferroni, hay que especificar <code>p.adjust.method="bonferroni"</code>, y para usar el de Hochberg, <code>p.adjust.method="hochberg"</code>. Si no queréis ningún ajuste, tenéis que usar <code>p.adjust.method="none"</code>. Para conocer qué otros métodos se pueden usar, sus ventajas e inconvenientes, consultad la Ayuda de <code>p.adjust</code>.</p>
<p>Por lo que refiere al parámetro <code>paired</code>, sirve para indicar si las muestras son independientes (igualándolo a <code>FALSE</code>, que es su valor por defecto) o emparejadas (igualándolo a <code>TRUE</code>); cuando el ANOVA es de bloques, las muestras son emparejadas, y por lo tanto
se ha de especificar <code>paired=TRUE</code>.</p>
<p>Veamos algunos ejemplos de su uso.</p>

<div class="example">
<p><span id="exm:unnamed-chunk-529" class="example"><strong>Ejemplo 9.7  </strong></span>Para determinar cuáles de las tres dietas en el ejemplo de la coagulación de la Sección <a href="chap-ANOVA.html#sec:ANOVA-1">9.2</a> dan tiempos medios de coagulación diferentes, vamos a efectuar un test t por parejas de Bonferroni.</p>
</div>
<div class="sourceCode" id="cb1087"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1087-1"><a href="chap-ANOVA.html#cb1087-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pairwise.t.test</span>(coagulacion<span class="sc">$</span>coag,coagulacion<span class="sc">$</span>diet,<span class="at">p.adjust.method=</span><span class="st">&quot;bonferroni&quot;</span>)</span></code></pre></div>
<pre><code>## 
## 	Pairwise comparisons using t tests with pooled SD 
## 
## data:  coagulacion$coag and coagulacion$diet 
## 
##   A       B       C      
## B 0.00934 -       -      
## C 0.00031 0.95266 -      
## D 1.00000 0.00934 0.00031
## 
## P value adjustment method: bonferroni</code></pre>
<p>Los p-valores del resultado ya han sido ajustados, y por lo tanto se han de comparar directamente con el nivel de significación <span class="math inline">\(\alpha\)</span> global. Por ejemplo, con un nivel de significación <span class="math inline">\(\alpha=0.05\)</span>, obtenemos evidencia de que los tiempos medios para los pares de dietas (A,B), (A,C), (B,D), (C,D) son diferentes, y en cambio no hay evidencia de que los tiempos medios para los pares (A,D) y (B,C) sean diferentes.</p>

<div class="example">
<p><span id="exm:unnamed-chunk-531" class="example"><strong>Ejemplo 9.8  </strong></span>Para determinar qué actividades de evaluación de las consideradas en el Ejemplo <a href="chap-ANOVA.html#exm:notes">9.3</a> dan notas medias diferentes, vamos a realizar un test t por parejas de Holm. Primero vamos a comprobar que dichas actividades de evaluación definen poblaciones normales, condición necesaria para que los tests t por parejas tengan sentido.</p>
</div>
<p>Contrastaremos la normalidad de las notas para cada actividad de evaluación con el test de Shapiro-Wilk, y para no trabajar más de la cuenta, usaremos la técnica explicada en el Ejemplo <a href="chap-ANOVA.html#exm:SW-auto">9.5</a>.</p>
<div class="sourceCode" id="cb1089"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1089-1"><a href="chap-ANOVA.html#cb1089-1" aria-hidden="true" tabindex="-1"></a>Test.SW<span class="ot">=</span><span class="cf">function</span>(x){<span class="fu">round</span>(<span class="fu">shapiro.test</span>(x)<span class="sc">$</span>p.value,<span class="dv">4</span>)}</span>
<span id="cb1089-2"><a href="chap-ANOVA.html#cb1089-2" aria-hidden="true" tabindex="-1"></a><span class="fu">aggregate</span>(notas<span class="sc">~</span>acts, <span class="at">data=</span>notas.bloques, <span class="at">FUN=</span>Test.SW)</span></code></pre></div>
<pre><code>##        acts  notas
## 1      Casa 0.1384
## 2 Control 1 0.7054
## 3 Control 2 0.5515
## 4  Talleres 0.7612
## 5     Tests 0.5984</code></pre>
<p>Todos los p-valores son altos, los que nos permite aceptar que las notas de cada actividad provienen de una distribución normal.</p>
<p>Así pues, podemos realizar el test t de Holm. En este caso tenemos que usar <code>paired=TRUE</code>, puesto que se trata de un ANOVA de bloques.</p>
<div class="sourceCode" id="cb1091"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1091-1"><a href="chap-ANOVA.html#cb1091-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pairwise.t.test</span>(notas.bloques<span class="sc">$</span>notas, notas.bloques<span class="sc">$</span>acts, <span class="at">paired=</span><span class="cn">TRUE</span>) </span></code></pre></div>
<pre><code>## 
## 	Pairwise comparisons using paired t tests 
## 
## data:  notas.bloques$notas and notas.bloques$acts 
## 
##           Casa   Control 1 Control 2 Talleres
## Control 1 0.4562 -         -         -       
## Control 2 0.0271 0.4562    -         -       
## Talleres  0.0012 0.0038    0.0012    -       
## Tests     0.4562 0.1640    0.0271    0.0038  
## 
## P value adjustment method: holm</code></pre>
<p>Los p-valores superiores a 0.05 son los de los pares de actividades “Ejercicios de casa”-“Control 1”,
“Control 1”-“Control 2”, “Ejercicios de casa”-“Tests” y “Control 1”-“Tests”. Por lo tanto, a un nivel de significación global de 0.05,
no podemos rechazar que las notas medias de estos pares de actividades sean iguales, mientras que en los otros tenemos evidencia de que son diferentes.</p>
</div>
<div id="test-de-duncan" class="section level3" number="9.6.2">
<h3><span class="header-section-number">9.6.2</span> Test de Duncan</h3>
<p>Otro método popular para comparar los pares de medias es el test de Duncan. Con R se puede efectuar con la instrucción <code>duncan.test</code> del paquete <strong>agricolae</strong>. Su sintaxis básica es</p>
<div class="sourceCode" id="cb1093"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1093-1"><a href="chap-ANOVA.html#cb1093-1" aria-hidden="true" tabindex="-1"></a><span class="fu">duncan.test</span>(aov, <span class="st">&quot;factor&quot;</span>, <span class="at">alpha=</span>..., <span class="at">group=</span>...)<span class="sc">$</span>sufijo</span></code></pre></div>
<p>donde</p>
<ul>
<li><p><code>aov</code> es el resultado de la función <code>aov</code> (sin <code>summary</code>) con la que hemos calculado el ANOVA de partida.</p></li>
<li><p>El <code>factor</code> es el factor del ANOVA, y se ha de entrar entrecomillado y con el mismo nombre que se ha usado en la fórmula del <code>aov</code>.</p></li>
<li><p>El parámetro <code>alpha</code> sirve para entrar el nivel de significación <span class="math inline">\(\alpha\)</span>: por defecto vale 0.05.</p></li>
<li><p><code>group</code> puede valer <code>TRUE</code> o <code>FALSE</code>, y hace que el resultado se presente de forma diferente.</p></li>
<li><p>El <code>sufijo</code> tiene que ser <code>groups</code> si <code>group=TRUE</code> y <code>comparison</code> si <code>group=FALSE</code>.</p></li>
</ul>
<p>Este test no se puede usar en el ANOVA de bloques, puesto que supone que las muestras de los tratamientos son independientes.</p>

<div class="example">
<p><span id="exm:unnamed-chunk-535" class="example"><strong>Ejemplo 9.9  </strong></span>Vamos a usar el test de Duncan para determinar qué pares de dietas en el ejemplo de la coagulación de la Sección <a href="chap-ANOVA.html#sec:ANOVA-1">9.2</a> tienen tiempos medios de coagulación diferentes, con un nivel de significación global del 5%. En primer lugar, guardamos en un objeto el ANOVA calculado con <code>aov</code>, y luego aplicamos la función <code>duncan.test</code> a este objeto. Aquí lo haremos dos veces, una para cada posible valor del parámetro <code>group</code>, para poder comparar y comentar cómo se muestran los resultados. No entraremos el parámetro <code>alpha</code>, puesto que usamos su valor por defecto.</p>
</div>
<div class="sourceCode" id="cb1094"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1094-1"><a href="chap-ANOVA.html#cb1094-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(agricolae)</span>
<span id="cb1094-2"><a href="chap-ANOVA.html#cb1094-2" aria-hidden="true" tabindex="-1"></a>anova.coag<span class="ot">=</span><span class="fu">aov</span>(coag<span class="sc">~</span>diet, <span class="at">data=</span>coagulacion)</span>
<span id="cb1094-3"><a href="chap-ANOVA.html#cb1094-3" aria-hidden="true" tabindex="-1"></a><span class="fu">duncan.test</span>(anova.coag, <span class="st">&quot;diet&quot;</span>, <span class="at">group=</span><span class="cn">FALSE</span>)<span class="sc">$</span>comparison</span></code></pre></div>
<pre><code>##       difference pvalue signif.       LCL        UCL
## A - B         -5 0.0016      ** -7.849968 -2.1500315
## A - C         -7 0.0001     *** -9.991509 -4.0084906
## A - D          0 1.0000         -2.849968  2.8499685
## B - C         -2 0.1588         -4.849968  0.8499685
## B - D          5 0.0021      **  2.008491  7.9915094
## C - D          7 0.0001     ***  3.918538 10.0814618</code></pre>
<div class="sourceCode" id="cb1096"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1096-1"><a href="chap-ANOVA.html#cb1096-1" aria-hidden="true" tabindex="-1"></a><span class="fu">duncan.test</span>(anova.coag, <span class="st">&quot;diet&quot;</span>, <span class="at">group=</span><span class="cn">TRUE</span>)<span class="sc">$</span>groups</span></code></pre></div>
<pre><code>##   coag groups
## C   68      a
## B   66      a
## A   61      b
## D   61      b</code></pre>
<p>Observemos los resultados:</p>
<ul>
<li><p>Con <code>group=FALSE</code> y sufijo <code>comparison</code>, obtenemos una tabla donde, para cada pareja de niveles del factor, se da, entre otros datos, un p-valor (la columna <code>p value</code>). Estos p-valores tienen el significado usual. En este ejemplo, de los p-valores se desprende que no podemos rechazar que las medias para los pares A-D y B-C sean iguales (los p-valores son grandes), mientras que, en cambio, hay evidencia significativa de que el resto de los pares de dietas tienen medias diferentes (los p-valores son pequeños). Las dos últimas columnas de la tabla definen intervalos de confianza (del nivel de confianza correspondiente al nivel de significación que hayamos entrado con <code>alpha</code>) para las diferencias de la medias en el orden especificado en la primera columna.</p></li>
<li><p>Con <code>group=TRUE</code> y sufijo <code>groups</code>, obtenemos una tabla donde se agrupan los niveles según la igualdad de medias. En este caso, asigna las dietas B y C al grupo <code>a</code> y las dietas A y D al grupo <code>b</code>: dietas en el mismo grupo hemos de aceptar que tienen medias iguales, dietas en grupos diferentes podemos concluir que tienen medias diferentes.</p></li>
</ul>
</div>
<div id="método-de-tukey" class="section level3" number="9.6.3">
<h3><span class="header-section-number">9.6.3</span> Método de Tukey</h3>
<p>El <strong>método HSD de Tukey</strong> (las siglas HSD refieren a <em>Honestly Significant Difference</em>) es el método más preciso de comparación de parejas de medias para contrastes ANOVA de un factor en los que cada nivel tenga el mismo número de observaciones. Es un test similar al test t, pero usa otro estadístico con una distribución diferente, no vamos a entrar en detalles. Con R se efectúa aplicando la función <code>TukeyHSD</code> al resultado de <code>aov</code>.</p>
<p>Para explicar qué información obtenemos con esta función, vamos a aplicar el método de Tukey al ANOVA del ejemplo sobre tiempos de coagulación de la Sección <a href="chap-ANOVA.html#sec:ANOVA-1">9.2</a>.</p>
<div class="sourceCode" id="cb1098"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1098-1"><a href="chap-ANOVA.html#cb1098-1" aria-hidden="true" tabindex="-1"></a>anova.coag<span class="ot">=</span><span class="fu">aov</span>(coag<span class="sc">~</span>diet, <span class="at">data=</span>coagulacion)</span>
<span id="cb1098-2"><a href="chap-ANOVA.html#cb1098-2" aria-hidden="true" tabindex="-1"></a><span class="fu">TukeyHSD</span>(anova.coag)</span></code></pre></div>
<pre><code>##   Tukey multiple comparisons of means
##     95% family-wise confidence level
## 
## Fit: aov(formula = coag ~ diet, data = coagulacion)
## 
## $diet
##              diff        lwr       upr     p adj
## B-A  5.000000e+00   1.175925  8.824075 0.0077978
## C-A  7.000000e+00   3.175925 10.824075 0.0002804
## D-A  1.421085e-14  -3.824075  3.824075 1.0000000
## C-B  2.000000e+00  -1.824075  5.824075 0.4766005
## D-B -5.000000e+00  -8.824075 -1.175925 0.0077978
## D-C -7.000000e+00 -10.824075 -3.175925 0.0002804</code></pre>
<p>De esta manera, para cada par de niveles obtenemos, entre otra información:</p>
<ul>
<li><p>La diferencia de sus medias muestrales, en la columna <code>diff</code>.</p></li>
<li><p>Los extremos inferior y superior de un intervalo de confianza del 95% para la diferencia de medias poblacionales en el orden dado en la primera columna, en las columnas <code>lwr</code> y <code>upr</code>, respectivamente. El nivel de confianza se puede ajustar con el parámetro <code>conf.level</code> dentro de la función.</p></li>
<li><p>El p-valor del contraste de igualdad de medias correspondiente, en la columna <code>p adj</code>.</p></li>
</ul>
<p>En nuestro ejemplo, los intervalos de confianza para las diferencias de medias de los pares A-B, A-C, B-D y C-D no contienen el valor 0 (y los p-valores correspondientes son pequeños), lo que indica que podemos rechazar que estas medias sean iguales. En cambio, los intervalos de confianza para las diferencias de medias de los pares A-D y B-C sí que contienen el 0 (y los p-valores correspondientes son grandes), lo que indica que podemos aceptar que estas medias son iguales. En este caso obtenemos, por lo tanto, la misma conclusión que con el test t de Bonferroni.</p>
</div>
</div>
<div id="métodos-no-paramétricos" class="section level2" number="9.7">
<h2><span class="header-section-number">9.7</span> Métodos no paramétricos</h2>
<p>Cuando no se satisfacen las condiciones para poder aplicar un ANOVA, hay que usar algún otro método que no las requiera.</p>
<p>En el caso del ANOVA de una vía, el método alternativo no paramétrico recomendado es el <strong>test de Kruskal-Wallis</strong>, que generaliza a más de dos muestras el test de Mann-Whitney-Wilcoxon para dos muestras independientes en el mismo sentido que el ANOVA generaliza el test t; en particular, un test de Kruskal-Wallis para un factor con solo dos niveles es equivalente al test de Mann-Whitney. Con R, el test de Kruskal-Wallis se lleva a cabo con la función <code>kruskal.test</code>, con la misma sintaxis que <code>aov</code>. Naturalmente, el resultado no es una tabla ANOVA, porque no estamos haciendo un ANOVA, pero da un p-valor que indica si podemos rechazar o no que las medias por niveles sean todas iguales.</p>
<p>Por ejemplo, para efectuar el test de Kruskal-Wallis sobre la tabla de tiempos de coagulación del principio de la Sección <a href="chap-ANOVA.html#sec:ANOVA-1">9.2</a>, entraríamos:</p>
<div class="sourceCode" id="cb1100"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1100-1"><a href="chap-ANOVA.html#cb1100-1" aria-hidden="true" tabindex="-1"></a><span class="fu">kruskal.test</span>(coag<span class="sc">~</span>diet, <span class="at">data=</span>coagulacion)</span></code></pre></div>
<pre><code>## 
## 	Kruskal-Wallis rank sum test
## 
## data:  coag by diet
## Kruskal-Wallis chi-squared = 17.027, df = 3, p-value = 0.0006977</code></pre>
<p>El p-valor nos da evidencia estadísticamente significativa de que no todos los tiempos medios de coagulación son iguales. Para determinar entonces qué pares de dietas dan tiempos medios diferentes, podríamos llevar a cabo un contraste por parejas. En principio no podremos usar un test t por parejas, ya que este presupone las condiciones de normalidad de las poblaciones e igualdad de las varianzas que son necesarias para el ANOVA y que suponemos que no se satisfacen (o habríamos hecho un ANOVA en vez de un test de Kruskal-Wallis). En su lugar, podemos usar un test de Mann-Whitney por parejas, con la función <code>pairwise.wilcox.test</code>. Su sintaxis es la misma que la de <code>pairwise.t.test</code>. En particular, hay que indicar con <code>p.adjust.method</code> el método de ajuste de los p-valores, siendo de nuevo <code>"holm"</code> su valor por defecto. Así, por ejemplo, para
realizar un test de Mann-Whitney por parejas con ajuste de Bonferroni, entraríamos:</p>
<div class="sourceCode" id="cb1102"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1102-1"><a href="chap-ANOVA.html#cb1102-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pairwise.wilcox.test</span>(coagulacion<span class="sc">$</span>coag,coagulacion<span class="sc">$</span>diet,<span class="at">p.adjust.method=</span><span class="st">&quot;bonferroni&quot;</span>)</span></code></pre></div>
<pre><code>## 
## 	Pairwise comparisons using Wilcoxon rank sum test 
## 
## data:  coagulacion$coag and coagulacion$diet 
## 
##   A     B     C    
## B 0.046 -     -    
## C 0.028 0.630 -    
## D 1.000 0.076 0.029
## 
## P value adjustment method: bonferroni</code></pre>
<p>Con un nivel de significación de 0.05, obtenemos evidencia de que los pares de dietas (A,B), (A,C) y (C,D) dan tiempos medios de coagulación diferentes, y no podemos rechazar que los otros pares de dietas den el mismo tiempo de coagulación. El resultado ha sido ligeramente diferente del test t por parejas, donde también obteníamos evidencia de diferencia de medias entre las dietas B y D. Recordad que, en general, los métodos no paramétricos tienen potencia menor y por lo tanto les cuesta más detectar diferencias.</p>
<p>Por lo que refiere al ANOVA de bloques completos aleatorios, el método no paramétrico alternativo más popular es el <strong>test de Friedman</strong>, que generaliza a más de dos muestras el test de Wilcoxon para muestras emparejadas. Está implementado en la función <code>friedman.test</code>, cuya sintaxis es de nuevo la misma que la de <code>aov</code> excepto que la suma de los tratamientos y los bloques no se indica en la fórmula con un signo de suma sino con una barra vertical.</p>
<p>Por ejemplo, para efectuar el test de Friedman sobre la tabla de datos de notas en actividades de evaluación del Ejemplo <a href="chap-ANOVA.html#exm:notes">9.3</a>, entraríamos:</p>
<div class="sourceCode" id="cb1104"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1104-1"><a href="chap-ANOVA.html#cb1104-1" aria-hidden="true" tabindex="-1"></a><span class="fu">friedman.test</span>(notas<span class="sc">~</span>acts<span class="sc">|</span>bloques, <span class="at">data=</span>notas.bloques)</span></code></pre></div>
<pre><code>## 
## 	Friedman rank sum test
## 
## data:  notas and acts and bloques
## Friedman chi-squared = 30.047, df = 4, p-value = 4.787e-06</code></pre>
<p>El p-valor nos indica que hay evidencia estadísticamente significativa de que algunas notas medias fueron diferentes. Para determinar cuáles, podemos llevar a cabo un test de Wilcoxon por parejas, usando la función <code>pairwise.wilcox.test</code> con <code>paired=TRUE</code>. Por ejemplo, usando de nuevo el ajuste de Bonferroni:</p>
<div class="sourceCode" id="cb1106"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1106-1"><a href="chap-ANOVA.html#cb1106-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pairwise.wilcox.test</span>(notas.bloques<span class="sc">$</span>notas, notas.bloques<span class="sc">$</span>acts, </span>
<span id="cb1106-2"><a href="chap-ANOVA.html#cb1106-2" aria-hidden="true" tabindex="-1"></a>   <span class="at">paired=</span><span class="cn">TRUE</span>, <span class="at">p.adjust.method=</span><span class="st">&quot;bonferroni&quot;</span>)</span></code></pre></div>
<pre><code>## 
## 	Pairwise comparisons using Wilcoxon signed rank test 
## 
## data:  notas.bloques$notas and notas.bloques$acts 
## 
##           Casa   Control 1 Control 2 Talleres
## Control 1 1.0000 -         -         -       
## Control 2 0.0823 1.0000    -         -       
## Talleres  0.0133 0.0285    0.0031    -       
## Tests     1.0000 0.5693    0.1816    0.0132  
## 
## P value adjustment method: bonferroni</code></pre>
<p>Encontramos evidencia de que las notas medias de los Talleres fueron diferentes de las del resto de actividades, y no podemos rechazar que las notas medias de las otras actividades fueran todas iguales.</p>
<p>Finalmente, en el caso de experimentos con dos o más factores, no hay una solución simple cuando no se satisfacen las condiciones necesarias para poder hacer un ANOVA. Una posible salida es usar un método adecuado de <em>bootstrap</em>. Sin entrar en detalles, una buena opción en un experimento de dos factores es usar la función <code>pbad2way</code> del paquete <strong>WRS2</strong>. Su sintaxis básica es</p>
<div class="sourceCode" id="cb1108"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1108-1"><a href="chap-ANOVA.html#cb1108-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pbad2way</span>(fórmula, <span class="at">est=</span><span class="st">&quot;median&quot;</span>, <span class="at">nboot=</span>...)</span></code></pre></div>
<p>En el parámetro <code>nboot</code> se ha de entrar el número de muestras que se han de tomar; tened en cuenta que cuántas más toméis, mas tardará la ejecución. El parámetro <code>est</code> indica qué parámetro se quiere comparar, la media no está entre los valores disponibles así que aquí usaremos la mediana. Consultad la Ayuda de la función (y las referencias que se citan) para saber qué otros estadísticos podéis usar.</p>
<p>Por ejemplo, para llevar a cabo por medio de un <em>bootstrap</em> el contraste del Ejemplo <a href="chap-ANOVA.html#exm:tooth2">9.4</a> sobre el efecto de la vitamina C en el crecimiento de los dientes (y recordando que la tabla <code>ToothGrowth2</code> contiene los datos con los tratamientos codificados como factores)
podríamos entrar:</p>
<div class="sourceCode" id="cb1109"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1109-1"><a href="chap-ANOVA.html#cb1109-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(WRS2)</span>
<span id="cb1109-2"><a href="chap-ANOVA.html#cb1109-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">42</span>) <span class="co">#Fijamos la semilla de aleatoriedad, para que sea reproducible</span></span>
<span id="cb1109-3"><a href="chap-ANOVA.html#cb1109-3" aria-hidden="true" tabindex="-1"></a><span class="fu">pbad2way</span>(len<span class="sc">~</span>supp<span class="sc">*</span>dose, <span class="at">data=</span>ToothGrowth2, <span class="at">est=</span><span class="st">&quot;median&quot;</span>, <span class="at">nboot=</span><span class="dv">500</span>)</span></code></pre></div>
<pre><code>## Call:
## pbad2way(formula = len ~ supp * dose, data = ToothGrowth2, est = &quot;median&quot;, 
##     nboot = 500)
## 
##           p.value
## supp        0.002
## dose        0.000
## supp:dose   0.034</code></pre>
<p><em>Grosso modo</em>, los p-valores obtenidos tienen el significado usual en un <em>bootstrap</em>: la fracción de muestras en las que obtenemos un valor de un cierto estadístico tan o más extremo que el de la muestra global. Un p-valor pequeño nos da evidencia de que podemos rechazar la hipótesis nula. Los p-valores de las filas con los nombres de los factores son los de los contrastes de los mismos y el p-valor de la última fila es el del contraste de interacción. Por lo tanto, con este contraste concluimos que hay evidencia de que tanto la dosis de vitamina C como el método de suministrarla influyen en el crecimiento de los odontoblastos (en concreto, en su <em>mediana</em>) y que hay interacción entre ambos factores.</p>
<p>Como en el ANOVA, el contraste de la combinación de factores se ha de efectuar aparte: en este caso (ya que no podemos llevar a cabo un ANOVA, o no nos estaríamos complicando tanto la vida) una buena opción es usar un test de Kruskal-Wallis tomando como factor la combinación de factores (entrada en la fórmula por medio de <code>interaction</code>).</p>
<div class="sourceCode" id="cb1111"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1111-1"><a href="chap-ANOVA.html#cb1111-1" aria-hidden="true" tabindex="-1"></a><span class="fu">kruskal.test</span>(len<span class="sc">~</span><span class="fu">interaction</span>(supp,dose),<span class="at">data=</span>ToothGrowth2)</span></code></pre></div>
<pre><code>## 
## 	Kruskal-Wallis rank sum test
## 
## data:  len by interaction(supp, dose)
## Kruskal-Wallis chi-squared = 45.806, df = 5, p-value = 9.948e-09</code></pre>
<p>Concluimos que también hay evidencia de que la combinación de la dosis de vitamina C y el método de suministrarla influye en el crecimiento de los odontoblastos.</p>
<p>Para terminar, una advertencia sobre <code>pbad2way</code>: a veces da un error numérico, como en la siguiente ejecución en el otro ejemplo de experimento de 2 vías de la Sección <a href="chap-ANOVA.html#sec:ANOVA2">9.4</a>:</p>
<div class="sourceCode" id="cb1113"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1113-1"><a href="chap-ANOVA.html#cb1113-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pbad2way</span>(time<span class="sc">~</span>poison<span class="sc">*</span>treat, <span class="at">data=</span>rats, <span class="at">est=</span><span class="st">&quot;median&quot;</span>, <span class="at">nboot=</span><span class="dv">500</span>)</span></code></pre></div>
<pre><code>## Error in solve.default(cov, ...): system is computationally singular: reciprocal condition number = 5.31267e-19</code></pre>
<p>En este caso, el inventor del método recomienda emplear el parámetro <code>pro.dis=TRUE</code>, que modifica el método de cálculo de los estadísticos que se usan en el <em>bootstrap</em> y evita el error.</p>
<div class="sourceCode" id="cb1115"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1115-1"><a href="chap-ANOVA.html#cb1115-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">42</span>)</span>
<span id="cb1115-2"><a href="chap-ANOVA.html#cb1115-2" aria-hidden="true" tabindex="-1"></a><span class="fu">pbad2way</span>(time<span class="sc">~</span>poison<span class="sc">*</span>treat, <span class="at">data=</span>rats, <span class="at">est=</span><span class="st">&quot;median&quot;</span>,<span class="at">nboot=</span><span class="dv">500</span>,<span class="at">pro.dis=</span><span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## Call:
## pbad2way(formula = time ~ poison * treat, data = rats, est = &quot;median&quot;, 
##     nboot = 500, pro.dis = TRUE)
## 
##              p.value
## poison         0.000
## treat          0.000
## poison:treat   0.174</code></pre>
</div>
<div id="guía-rápida" class="section level2" number="9.8">
<h2><span class="header-section-number">9.8</span> Guía rápida</h2>
<ul>
<li><p>Fórmulas:</p>
<ul>
<li><p><code>X~F1</code> ajusta la variable <code>X</code> al factor <code>F1</code>.</p></li>
<li><p><code>X~F1+F2</code> ajusta la variable <code>X</code> a los factores <code>F1</code> y <code>F2</code> sin tener en cuenta la interacción entre los factores.</p></li>
<li><p><code>X~F1*F2</code> ajusta la variable <code>X</code> a los factores <code>F1</code> y <code>F2</code> teniendo en cuenta además la interacción entre los factores.</p></li>
<li><p><code>X~F1:F2</code> ajusta la variable <code>X</code> a un factor que tiene como niveles los pares de niveles de <code>F1</code> y <code>F2</code>.</p></li>
</ul></li>
<li><p><code>options(show.signif.stars=...)</code> sirve para desactivar (usando <code>FALSE</code>) o activar (con <code>TRUE</code>) los códigos de significación por medio de estrellitas.</p></li>
<li><p><code>aov(fórmula)</code> efectúa el ANOVA indicado por la <code>fórmula</code>. El parámetro adicional <code>data</code> sirve para indicar el <em>data frame</em> del que se extraen los vectores y factores de la <code>fórmula</code>.</p></li>
<li><p><code>summary(aov(...))</code> muestra la tabla del ANOVA efectuado con la función <code>aov</code>. Añadiendo el sufijo <code>[[1]]$"Pr(&gt;F)"</code> nos da directamente la columna de p-valores de la tabla.</p></li>
<li><p><code>anova(lm(fórmula, data=...))</code> también produce la tabla del ANOVA indicado por la <code>fórmula</code>.
Con el sufijo <code>$"Pr(&gt;F)"</code>, nos da directamente la columna de p-valores de la tabla.</p></li>
<li><p><code>interaction.plot(factor1,factor2,vector)</code> produce el gráfico de interacción del <code>vector</code> respecto de los dos factores.</p></li>
<li><p><code>subset(dataframe,condición)</code> define un <em>data frame</em> con las filas del <code>dataframe</code> que cumplen la <code>condición</code>.</p></li>
<li><p><code>shapiro.test(x)</code> realiza el test de normalidad de Shapiro-Wilk sobre el vector numérico <code>x</code>.</p></li>
<li><p><code>aggregate</code> sirve para aplicar una función a una o varias variables de un <em>data frame</em> agrupando sus entradas por los niveles de uno o varios factores.</p></li>
<li><p><code>bartlett.test</code>, con la misma sintaxis que <code>aov</code>, efectúa el test de Bartlett de homocedasticidad.</p></li>
<li><p><code>pairwise.t.test(x,factor)</code> efectúa un test t por parejas de la variable <code>x</code> separada por los niveles del <code>factor</code>. Dos parámetros importantes:</p>
<ul>
<li><p><code>paired</code>: se ha de igualar a <code>TRUE</code> en los ANOVA de bloques.</p></li>
<li><p><code>p.adjust.method</code>: sirve para indicar el método de ajuste de los p-valores.</p></li>
</ul></li>
<li><p><code>duncan.test(aov,factor)$sufijo</code> del paquete <strong>agricolae</strong>, efectúa el test de Duncan del ANOVA <code>aov</code>. Sus dos parámetros más importantes para nosotros son <code>alpha</code>, que sirve para indicar el nivel de significación y <code>group</code>, que sirve para indicar cómo queremos que muestre el resultado. El <code>sufijo</code> ha de ser ser <code>groups</code> si <code>group=TRUE</code> y <code>comparison</code> si <code>group=FALSE</code>.</p></li>
<li><p><code>TukeyHSD(aov)</code> efectúa el test HSD de Tukey del ANOVA <code>aov</code>.</p></li>
<li><p><code>kruskal.test</code> efectúa el test de Kruskal-Wallis. Su sintaxis es la misma que la de <code>aov</code>.</p></li>
<li><p><code>pairwise.wilcox.test</code> efectúa un test de Wilcoxon (con <code>paired=TRUE</code>) o de Mann-Whitney-Wilcoxon (con <code>paired=FALSE</code>, el valor por defecto de este parámetro) por parejas. Su sintaxis es la misma que la de <code>pairwise.t.test</code>.</p></li>
<li><p><code>friedman.test</code> efectúa el test de Friedman. Su sintaxis es la misma que la de <code>aov</code>.</p></li>
<li><p><code>pbad2way(fórmula, data=..., est="median")</code> del paquete <strong>WRS2</strong> lleva a cabo un contraste <em>bootstrap</em> de medianas de los datos de un experimento factorial de 2 vías. El parámetro <code>nboot</code> sirve para indicar el número de muestras a usar.</p></li>
</ul>
</div>
<div id="ejercicios" class="section level2" number="9.9">
<h2><span class="header-section-number">9.9</span> Ejercicios</h2>
<div id="test" class="section level3 unnumbered">
<h3>Test</h3>
<p><em>(1)</em> En un experimento queremos comparar el valor medio de una cierta variable en cuatro poblaciones, A, B, C y D. Hemos tomado una muestra de 5 individuos de cada población y hemos medido en ellos la variable en cuestión. Los resultados para cada población han sido los siguientes: A=(23.1,17.2,20.1,19.5,18.8), B=(22.6,15.5,19.3,18.5,16.2), C=(21.1,26.4,24.7,21.4,20.9) y D=(20.4,24,23.4,24.9,21.5). Realizad un ANOVA de 1 vía sobre estos datos. Tenéis que dar el p-valor del contraste de la igualdad de las medias redondeado a 3 cifras decimales (sin ceros innecesarios a la derecha) y decir si podéis rechazar (con un SI) o no (con un NO), con un nivel de significación del 5%, la igualdad de todas las medias. Dad el p-valor y la conclusión en este orden, separados por un único espacio en blanco.</p>
<p><em>(2)</em> En un experimento queremos comparar la influencia de cuatro tratamientos, A, B, C y D, sobre una determinada variable fisiológica. Para ello hemos aplicado cada tratamiento a los mismos 5 individuos, pero en órdenes y momentos escogidos al azar, y hemos medido en ellos la variable en cuestión tras cada tratamiento. Los resultados para cada tratamiento (ordenados en cada uno en el mismo orden, correspondiente a los individuos) han sido los siguientes: A=(23.1,17.2,20.1,19.5,18.8), B=(22.6,15.5,19.3,18.5,16.2), C=(21.1,26.4,24.7,21.4,20.9) y D=(20.4,24,23.4,24.9,21.5). Realizad un ANOVA de bloques sobre estos datos. Tenéis que dar el p-valor del contraste de la igualdad de las medias de los tratamientos redondeado a 3 cifras decimales (sin ceros innecesarios a la derecha) y decir si podéis rechazar (con un SI) o no (con un NO), con un nivel de significación del 5%, la igualdad de todas las medias de los tratamientos. Dad el p-valor y la conclusión en este orden, separados por un único espacio en blanco.</p>
<p><em>(3)</em> En un experimento queremos comparar el valor medio de una cierta variable en cuatro poblaciones, A, B, C y D; los individuos de cada población además pueden clasificarse en dos tipos, X e Y, según una determinada característica que creemos que será relevante en nuestro estudio. Hemos tomado una muestra de 5 individuos de cada combinación población-característica y hemos medido en ellos la variable en cuestión. Los resultados para cada combinación población-característica han sido los siguientes: A-X=(29.2,30.9,31.3,30.0,30.0), B-X=(29.1,31.3,31.4,34.3,32.3), C-X=(31.3,40.7,32.6,34.8, 38.3), D-X=(32.2,36.0,31.6,31.8,32.6), A-Y=(26.3,25.9,25.6,25.3,24.9), B-Y=(30.7,29.8, 27.9,28.8,28.1), C-Y=(26.2,26.7,27.2,29.3,28.4), y D-Y=(20.5,26.2,27.9,23.3,27.8). Realizad un ANOVA de 2 vías sobre estos datos. Dad el p-valor del contraste de interacción entre el tratamiento y la característica redondeado a 3 cifras decimales (sin ceros innecesarios a la derecha) y decid si podéis concluir (con un SI) o no (con un NO), con un nivel de significación del 5%, que hay interacción entre el tratamiento y la característica. Dad el p-valor y la conclusión en este orden, separados por un único espacio en blanco.</p>
<p><em>(4)</em> En un experimento queremos comparar el valor medio de una cierta variable en cuatro poblaciones, A, B, C y D. Hemos tomado una muestra de 5 individuos de cada población y hemos medido en ellos la variable en cuestión. Los resultados para cada población han sido los siguientes: A=(23.1,17.2,20.1,19.5,18.8), B=(22.6,15.5,19.3,18.5,16.2), C=(21.1,26.4,24.7,21.4,20.9) y D=(20.4,24,23.4,24.9,21.5). Realizad un test de Bartlett de homocedasticidad sobre estos datos, para saber si las varianzas poblacionales de las cuatro poblaciones son todas iguales o no. Tenéis que dar el p-valor del contraste de la igualdad de las varianzas redondeado a 3 cifras decimales (sin ceros innecesarios a la derecha) y decir si podéis rechazar (con un SI) o no (con un NO), con un nivel de significación del 5%, la igualdad de todas las varianzas. Dad el p-valor y la conclusión en este orden, separados por un único espacio en blanco.</p>
<p><em>(5)</em> En un experimento hemos comparado el valor medio de una cierta variable en cuatro poblaciones, A, B, C y D. Hemos tomado una muestra de 5 individuos de cada población y hemos medido en ellos la variable en cuestión. Los resultados para cada población han sido los siguientes: A=(23.1,17.2,20.1,19.5,18.8), B=(22.6,15.5,19.3,18.5,16.2), C=(21.1,26.4,24.7,21.4,20.9) y D=(20.4,24,23.4,24.9,21.5).
Realizad un test t por parejas de Bonferroni sobre estos datos con un nivel de significación del 5%, para determinar qué pares de poblaciones podemos concluir que tienen medias diferentes con este nivel de significación. Tenéis que decir si podéis rechazar (con un SI) o no (con un NO), con un nivel de significación del 5%, la igualdad de las medias de las poblaciones B y C.</p>
</div>
<div id="ejercicio" class="section level3" number="9.9.1">
<h3><span class="header-section-number">9.9.1</span> Ejercicio</h3>
<p><em>(1)</em> La tabla de datos <code>butterfat</code> del paquete <strong>faraway</strong> contiene los porcentajes de contenido de grasa en la leche en muestras aleatorias de 5 razas. Para cada raza hay 20 vacas en la muestra: 10 vacas de dos años, <code>2year</code>, y 10 de más de 4 años, <code>Mature</code>. Las variables de la tabla de datos son:</p>
<ul>
<li><code>Butterfat</code>: Porcentaje de contenido de grasa en la leche.</li>
<li><code>Breed</code>: un factor que indica la raza de la vaca. Los niveles son: <code>Ayrshire</code>, <code>Canadian</code>, <code>Guernsey</code>, <code>Holstein-Fresian</code> y <code>Jersey</code>.</li>
<li><code>Age</code>: una variable factor con los valores ya comentados: <code>2year</code> y <code>Mature</code>.</li>
</ul>
<p>Queremos usar estos datos para contrastar si el porcentaje medio de contenido de grasa en la leche depende de la raza o de la edad de la vaca.</p>
<p><em>(a)</em> Dibujad sendos gráficos con los diagrama de cajas de los porcentajes de contenido de grasa en la leche de las vacas de la muestra separados por la raza de la vaca y separados por su edad, respectivamente. Comentadlos.</p>
<p><em>(b)</em> Contrastad si cada muestra de una combinación de niveles (raza,edad) proviene de una distribución normal usando el test de Shapiro-Wilks con un nivel de significación <span class="math inline">\(\alpha =0.05\)</span>.</p>
<p><em>(c)</em> Contrastad si todas las muestras de combinaciones de niveles (raza,edad) tienen la misma varianza, con un nivel de significación <span class="math inline">\(\alpha =0.05\)</span>.</p>
<p><em>(d)</em> Se satisfacen las hipótesis para poder usar un ANOVA de 2 vías para comprobar si el porcentaje medio de grasa en la leche depende de la raza o de la edad de la vaca?</p>
<p><em>(e)</em> Sea cual sea vuestra respuesta a la pregunta anterior, realizad un test ANOVA de 2 vías para contrastar con un nivel de significación <span class="math inline">\(\alpha =0.05\)</span> si el porcentaje medio de grasa en la leche depende de la raza o de la edad de la vaca (no hace falta contrastar las combinaciones (raza,edad)). Hay interacción entre la raza de la vaca y la edad de la misma?</p>
<p><em>(f)</em> Sea cual sea vuestra respuesta a la pregunta <em>(d)</em>, realizad también los contrastes de <em>(e)</em> mediante un test no paramétrico adecuado con un nivel de significación <span class="math inline">\(\alpha =0.05\)</span>. Coinciden las conclusiones?</p>
</div>
<div id="respuestas-al-test" class="section level3 unnumbered">
<h3>Respuestas al test</h3>
<p><em>(1)</em> 0.013 SI</p>
<p>Fijaos en que en el enunciado nos dan la tabla de datos siguiente por columnas:</p>
<table>
<thead>
<tr class="header">
<th align="right">A</th>
<th align="right">B</th>
<th align="right">C</th>
<th align="right">D</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">23.1</td>
<td align="right">22.6</td>
<td align="right">21.1</td>
<td align="right">20.4</td>
</tr>
<tr class="even">
<td align="right">17.2</td>
<td align="right">15.5</td>
<td align="right">26.4</td>
<td align="right">24.0</td>
</tr>
<tr class="odd">
<td align="right">20.1</td>
<td align="right">19.3</td>
<td align="right">24.7</td>
<td align="right">23.4</td>
</tr>
<tr class="even">
<td align="right">19.5</td>
<td align="right">18.5</td>
<td align="right">21.4</td>
<td align="right">24.9</td>
</tr>
<tr class="odd">
<td align="right">18.8</td>
<td align="right">16.2</td>
<td align="right">21.9</td>
<td align="right">21.5</td>
</tr>
</tbody>
</table>
<p>Por lo tanto para entrarla de manera correcta como un <em>data frame</em> copiando los datos del enunciado hay que usar:</p>
<div class="sourceCode" id="cb1117"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1117-1"><a href="chap-ANOVA.html#cb1117-1" aria-hidden="true" tabindex="-1"></a>x<span class="ot">=</span><span class="fu">c</span>(<span class="fl">23.1</span>,<span class="fl">17.2</span>,<span class="fl">20.1</span>,<span class="fl">19.5</span>,<span class="fl">18.8</span>,</span>
<span id="cb1117-2"><a href="chap-ANOVA.html#cb1117-2" aria-hidden="true" tabindex="-1"></a>    <span class="fl">22.6</span>,<span class="fl">15.5</span>,<span class="fl">19.3</span>,<span class="fl">18.5</span>,<span class="fl">16.2</span>,</span>
<span id="cb1117-3"><a href="chap-ANOVA.html#cb1117-3" aria-hidden="true" tabindex="-1"></a>    <span class="fl">21.1</span>,<span class="fl">26.4</span>,<span class="fl">24.7</span>,<span class="fl">21.4</span>,<span class="fl">21.9</span>,</span>
<span id="cb1117-4"><a href="chap-ANOVA.html#cb1117-4" aria-hidden="true" tabindex="-1"></a>    <span class="fl">20.4</span>,<span class="fl">24.0</span>,<span class="fl">23.4</span>,<span class="fl">24.9</span>,<span class="fl">21.5</span>)</span>
<span id="cb1117-5"><a href="chap-ANOVA.html#cb1117-5" aria-hidden="true" tabindex="-1"></a>pobl<span class="ot">=</span><span class="fu">rep</span>(<span class="fu">c</span>(<span class="st">&quot;A&quot;</span>,<span class="st">&quot;B&quot;</span>,<span class="st">&quot;C&quot;</span>,<span class="st">&quot;D&quot;</span>),<span class="at">each=</span><span class="dv">5</span>) </span>
<span id="cb1117-6"><a href="chap-ANOVA.html#cb1117-6" aria-hidden="true" tabindex="-1"></a>X<span class="ot">=</span><span class="fu">data.frame</span>(x,pobl)</span></code></pre></div>
<p>A partir de aquí, la respuesta la obtenemos con</p>
<div class="sourceCode" id="cb1118"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1118-1"><a href="chap-ANOVA.html#cb1118-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">aov</span>(x<span class="sc">~</span>pobl,<span class="at">data=</span>X))[[<span class="dv">1</span>]]<span class="sc">$</span><span class="st">&quot;Pr(&gt;F)&quot;</span></span></code></pre></div>
<pre><code>## [1] 0.01257876         NA</code></pre>
<p><em>(2)</em> 0.026 NO</p>
<p>Nosotros lo hemos resuelto con</p>
<div class="sourceCode" id="cb1120"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1120-1"><a href="chap-ANOVA.html#cb1120-1" aria-hidden="true" tabindex="-1"></a>x<span class="ot">=</span><span class="fu">c</span>(<span class="fl">23.1</span>,<span class="fl">17.2</span>,<span class="fl">20.1</span>,<span class="fl">19.5</span>,<span class="fl">18.8</span>,</span>
<span id="cb1120-2"><a href="chap-ANOVA.html#cb1120-2" aria-hidden="true" tabindex="-1"></a>    <span class="fl">22.6</span>,<span class="fl">15.5</span>,<span class="fl">19.3</span>,<span class="fl">18.5</span>,<span class="fl">16.2</span>,</span>
<span id="cb1120-3"><a href="chap-ANOVA.html#cb1120-3" aria-hidden="true" tabindex="-1"></a>    <span class="fl">21.1</span>,<span class="fl">26.4</span>,<span class="fl">24.7</span>,<span class="fl">21.4</span>,<span class="fl">21.9</span>,</span>
<span id="cb1120-4"><a href="chap-ANOVA.html#cb1120-4" aria-hidden="true" tabindex="-1"></a>    <span class="fl">20.4</span>,<span class="fl">24.0</span>,<span class="fl">23.4</span>,<span class="fl">24.9</span>,<span class="fl">21.5</span>)</span>
<span id="cb1120-5"><a href="chap-ANOVA.html#cb1120-5" aria-hidden="true" tabindex="-1"></a>pobl<span class="ot">=</span><span class="fu">rep</span>(<span class="fu">c</span>(<span class="st">&quot;A&quot;</span>,<span class="st">&quot;B&quot;</span>,<span class="st">&quot;C&quot;</span>,<span class="st">&quot;D&quot;</span>), <span class="at">each=</span><span class="dv">5</span>)</span>
<span id="cb1120-6"><a href="chap-ANOVA.html#cb1120-6" aria-hidden="true" tabindex="-1"></a>bloques<span class="ot">=</span><span class="fu">as.factor</span>(<span class="fu">rep</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>,<span class="dv">4</span>))</span>
<span id="cb1120-7"><a href="chap-ANOVA.html#cb1120-7" aria-hidden="true" tabindex="-1"></a>X.b<span class="ot">=</span><span class="fu">data.frame</span>(x,pobl,bloques)</span>
<span id="cb1120-8"><a href="chap-ANOVA.html#cb1120-8" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">aov</span>(x<span class="sc">~</span>pobl<span class="sc">+</span>bloques,<span class="at">data=</span>X.b))[[<span class="dv">1</span>]]<span class="sc">$</span><span class="st">&quot;Pr(&gt;F)&quot;</span>[<span class="dv">1</span>]</span></code></pre></div>
<pre><code>## [1] 0.02561791</code></pre>
<p><em>(3)</em> 0.0234 SI</p>
<p>Nosotros lo hemos resuelto con</p>
<div class="sourceCode" id="cb1122"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1122-1"><a href="chap-ANOVA.html#cb1122-1" aria-hidden="true" tabindex="-1"></a>AX<span class="ot">=</span><span class="fu">c</span>(<span class="fl">29.2</span>,<span class="fl">30.9</span>,<span class="fl">31.3</span>,<span class="fl">30.0</span>,<span class="fl">30.0</span>)</span>
<span id="cb1122-2"><a href="chap-ANOVA.html#cb1122-2" aria-hidden="true" tabindex="-1"></a>BX<span class="ot">=</span><span class="fu">c</span>(<span class="fl">29.1</span>,<span class="fl">31.3</span>,<span class="fl">31.4</span>,<span class="fl">34.3</span>,<span class="fl">32.3</span>)</span>
<span id="cb1122-3"><a href="chap-ANOVA.html#cb1122-3" aria-hidden="true" tabindex="-1"></a>CX<span class="ot">=</span><span class="fu">c</span>(<span class="fl">31.3</span>,<span class="fl">40.7</span>,<span class="fl">32.6</span>,<span class="fl">34.8</span>,<span class="fl">38.3</span>)</span>
<span id="cb1122-4"><a href="chap-ANOVA.html#cb1122-4" aria-hidden="true" tabindex="-1"></a>DX<span class="ot">=</span><span class="fu">c</span>(<span class="fl">32.2</span>,<span class="fl">36.0</span>,<span class="fl">31.6</span>,<span class="fl">31.8</span>,<span class="fl">32.6</span>)</span>
<span id="cb1122-5"><a href="chap-ANOVA.html#cb1122-5" aria-hidden="true" tabindex="-1"></a>AY<span class="ot">=</span><span class="fu">c</span>(<span class="fl">26.3</span>,<span class="fl">25.9</span>,<span class="fl">25.6</span>,<span class="fl">25.3</span>,<span class="fl">24.9</span>)</span>
<span id="cb1122-6"><a href="chap-ANOVA.html#cb1122-6" aria-hidden="true" tabindex="-1"></a>BY<span class="ot">=</span><span class="fu">c</span>(<span class="fl">30.7</span>,<span class="fl">29.8</span>,<span class="fl">27.9</span>,<span class="fl">28.8</span>,<span class="fl">28.1</span>)</span>
<span id="cb1122-7"><a href="chap-ANOVA.html#cb1122-7" aria-hidden="true" tabindex="-1"></a>CY<span class="ot">=</span><span class="fu">c</span>(<span class="fl">26.2</span>,<span class="fl">26.7</span>,<span class="fl">27.2</span>,<span class="fl">29.3</span>,<span class="fl">28.4</span>)</span>
<span id="cb1122-8"><a href="chap-ANOVA.html#cb1122-8" aria-hidden="true" tabindex="-1"></a>DY<span class="ot">=</span><span class="fu">c</span>(<span class="fl">20.5</span>,<span class="fl">26.2</span>,<span class="fl">27.9</span>,<span class="fl">23.3</span>,<span class="fl">27.8</span>)</span>
<span id="cb1122-9"><a href="chap-ANOVA.html#cb1122-9" aria-hidden="true" tabindex="-1"></a>y<span class="ot">=</span><span class="fu">c</span>(AX,BX,CX,DX,AY,BY,CY,DY)</span>
<span id="cb1122-10"><a href="chap-ANOVA.html#cb1122-10" aria-hidden="true" tabindex="-1"></a>fact.A<span class="ot">=</span><span class="fu">rep</span>(<span class="fu">rep</span>(<span class="fu">c</span>(<span class="st">&quot;A&quot;</span>,<span class="st">&quot;B&quot;</span>,<span class="st">&quot;C&quot;</span>,<span class="st">&quot;D&quot;</span>),<span class="at">each=</span><span class="dv">5</span>),<span class="dv">2</span>)</span>
<span id="cb1122-11"><a href="chap-ANOVA.html#cb1122-11" aria-hidden="true" tabindex="-1"></a>fact.X<span class="ot">=</span><span class="fu">rep</span>(<span class="fu">c</span>(<span class="st">&quot;X&quot;</span>,<span class="st">&quot;Y&quot;</span>),<span class="at">each=</span><span class="dv">20</span>)</span>
<span id="cb1122-12"><a href="chap-ANOVA.html#cb1122-12" aria-hidden="true" tabindex="-1"></a>DF<span class="ot">=</span><span class="fu">data.frame</span>(y,fact.A,fact.X)</span>
<span id="cb1122-13"><a href="chap-ANOVA.html#cb1122-13" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">aov</span>(y<span class="sc">~</span>fact.A<span class="sc">*</span>fact.X))</span></code></pre></div>
<pre><code>##               Df Sum Sq Mean Sq F value   Pr(&gt;F)
## fact.A         3   74.7    24.9   5.487  0.00371
## fact.X         1  330.1   330.1  72.700 9.62e-10
## fact.A:fact.X  3   49.3    16.4   3.619  0.02344
## Residuals     32  145.3     4.5</code></pre>
<p><em>(4)</em> 0.881 NO</p>
<p>Nosotros lo hemos resuelto con</p>
<div class="sourceCode" id="cb1124"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1124-1"><a href="chap-ANOVA.html#cb1124-1" aria-hidden="true" tabindex="-1"></a><span class="fu">bartlett.test</span>(x<span class="sc">~</span>pobl,<span class="at">data=</span>X)</span></code></pre></div>
<pre><code>## 
## 	Bartlett test of homogeneity of variances
## 
## data:  x by pobl
## Bartlett&#39;s K-squared = 0.6667, df = 3, p-value = 0.881</code></pre>
<p><em>(5)</em> SI</p>
<p>Nosotros lo hemos resuelto con</p>
<div class="sourceCode" id="cb1126"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1126-1"><a href="chap-ANOVA.html#cb1126-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pairwise.t.test</span>(X<span class="sc">$</span>x,X<span class="sc">$</span>pobl,<span class="at">p.adjust.method=</span><span class="st">&quot;holm&quot;</span>)</span></code></pre></div>
<pre><code>## 
## 	Pairwise comparisons using t tests with pooled SD 
## 
## data:  X$x and X$pobl 
## 
##   A     B     C    
## B 0.762 -     -    
## C 0.143 0.034 -    
## D 0.151 0.041 0.861
## 
## P value adjustment method: holm</code></pre>
</div>
<div id="soluciones-sucintas-del-ejercicio" class="section level3" number="9.9.2">
<h3><span class="header-section-number">9.9.2</span> Soluciones sucintas del ejercicio</h3>
<div class="sourceCode" id="cb1128"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1128-1"><a href="chap-ANOVA.html#cb1128-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(faraway)</span>
<span id="cb1128-2"><a href="chap-ANOVA.html#cb1128-2" aria-hidden="true" tabindex="-1"></a>BF<span class="ot">=</span>butterfat</span>
<span id="cb1128-3"><a href="chap-ANOVA.html#cb1128-3" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(BF)</span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:	100 obs. of  3 variables:
##  $ Butterfat: num  3.74 4.01 3.77 3.78 4.1 4.06 4.27 3.94 4.11 4.25 ...
##  $ Breed    : Factor w/ 5 levels &quot;Ayrshire&quot;,&quot;Canadian&quot;,..: 1 1 1 1 1 1 1 1 1 1 ...
##  $ Age      : Factor w/ 2 levels &quot;2year&quot;,&quot;Mature&quot;: 2 1 2 1 2 1 2 1 2 1 ...</code></pre>
<p><em>(a)</em></p>
<div class="sourceCode" id="cb1130"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1130-1"><a href="chap-ANOVA.html#cb1130-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(Butterfat<span class="sc">~</span>Breed, <span class="at">data=</span>BF)</span></code></pre></div>
<p><img src="AprendeR-Parte-II_files/figure-html/unnamed-chunk-556-1.png" width="480" style="display: block; margin: auto;" /></p>
<div class="sourceCode" id="cb1131"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1131-1"><a href="chap-ANOVA.html#cb1131-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(Butterfat<span class="sc">~</span>Age, <span class="at">data=</span>BF)</span></code></pre></div>
<p><img src="AprendeR-Parte-II_files/figure-html/unnamed-chunk-557-1.png" width="480" style="display: block; margin: auto;" /></p>
<p><em>(b)</em></p>
<div class="sourceCode" id="cb1132"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1132-1"><a href="chap-ANOVA.html#cb1132-1" aria-hidden="true" tabindex="-1"></a>Test.SW<span class="ot">=</span><span class="cf">function</span>(x){<span class="fu">shapiro.test</span>(x)<span class="sc">$</span>p.value}</span>
<span id="cb1132-2"><a href="chap-ANOVA.html#cb1132-2" aria-hidden="true" tabindex="-1"></a><span class="fu">aggregate</span>(Butterfat<span class="sc">~</span>Breed<span class="sc">:</span>Age, <span class="at">data=</span>BF,<span class="at">FUN=</span>Test.SW)</span></code></pre></div>
<pre><code>##               Breed    Age  Butterfat
## 1          Ayrshire  2year 0.99921213
## 2          Canadian  2year 0.20778457
## 3          Guernsey  2year 0.95640414
## 4  Holstein-Fresian  2year 0.16320779
## 5            Jersey  2year 0.69510564
## 6          Ayrshire Mature 0.21757333
## 7          Canadian Mature 0.73627123
## 8          Guernsey Mature 0.33518154
## 9  Holstein-Fresian Mature 0.05739251
## 10           Jersey Mature 0.10347415</code></pre>
<p>Podemos concluir con un nivel de significación del 5% que todas las muestras provienen de variables normales.</p>
<p><em>(c)</em></p>
<div class="sourceCode" id="cb1134"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1134-1"><a href="chap-ANOVA.html#cb1134-1" aria-hidden="true" tabindex="-1"></a><span class="fu">bartlett.test</span>(Butterfat<span class="sc">~</span><span class="fu">interaction</span>(Breed,Age), <span class="at">data=</span>BF)</span></code></pre></div>
<pre><code>## 
## 	Bartlett test of homogeneity of variances
## 
## data:  Butterfat by interaction(Breed, Age)
## Bartlett&#39;s K-squared = 24.356, df = 9, p-value = 0.003772</code></pre>
<p>No podemos aceptar que se dé homocedasticidad.</p>
<p><em>(d)</em> No.</p>
<p><em>(e)</em></p>
<div class="sourceCode" id="cb1136"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1136-1"><a href="chap-ANOVA.html#cb1136-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">aov</span>(Butterfat<span class="sc">~</span>Breed<span class="sc">*</span>Age,<span class="at">data=</span>BF))</span></code></pre></div>
<pre><code>##             Df Sum Sq Mean Sq F value Pr(&gt;F)    
## Breed        4  34.32   8.580  49.565 &lt;2e-16 ***
## Age          1   0.27   0.274   1.580  0.212    
## Breed:Age    4   0.51   0.128   0.742  0.566    
## Residuals   90  15.58   0.173                   
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p><em>(f)</em></p>
<div class="sourceCode" id="cb1138"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1138-1"><a href="chap-ANOVA.html#cb1138-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(WRS2)</span>
<span id="cb1138-2"><a href="chap-ANOVA.html#cb1138-2" aria-hidden="true" tabindex="-1"></a><span class="fu">pbad2way</span>(Butterfat<span class="sc">~</span>Breed<span class="sc">*</span>Age,<span class="at">data=</span>BF, <span class="at">est=</span><span class="st">&quot;median&quot;</span>, <span class="at">nboot=</span><span class="dv">500</span>)</span></code></pre></div>
<pre><code>## Error in solve.default(cov, ...): system is computationally singular: reciprocal condition number = 4.97982e-19</code></pre>
<p>¡Ups!</p>
<div class="sourceCode" id="cb1140"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1140-1"><a href="chap-ANOVA.html#cb1140-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pbad2way</span>(Butterfat<span class="sc">~</span>Breed<span class="sc">*</span>Age,<span class="at">data=</span>BF, <span class="at">est=</span><span class="st">&quot;median&quot;</span>, <span class="at">nboot=</span><span class="dv">500</span>,<span class="at">pro.dis=</span><span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## Call:
## pbad2way(formula = Butterfat ~ Breed * Age, data = BF, est = &quot;median&quot;, 
##     nboot = 500, pro.dis = TRUE)
## 
##           p.value
## Breed        0.00
## Age          0.28
## Breed:Age    0.83</code></pre>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="chap-estmult.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="chap-regresion.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "subsection",
"download": ["pdf", "epub"]
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
