<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Tema 5 Contrastos d’hipòtesis d’un i dos paràmetres | Matemàtiques II</title>
  <meta name="description" content="Apunts Matemàtiques II bookdown::gitbook." />
  <meta name="generator" content="bookdown 0.18 and GitBook 2.6.7" />

  <meta property="og:title" content="Tema 5 Contrastos d’hipòtesis d’un i dos paràmetres | Matemàtiques II" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Apunts Matemàtiques II bookdown::gitbook." />
  <meta name="github-repo" content="cescrossello/MatesII" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Tema 5 Contrastos d’hipòtesis d’un i dos paràmetres | Matemàtiques II" />
  
  <meta name="twitter:description" content="Apunts Matemàtiques II bookdown::gitbook." />
  



<meta name="date" content="2020-05-04" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="contrastos-dhipòtesis-generalitats.html"/>
<link rel="next" href="contrastos-de-bondat-dajust.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />











<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(data-line-number);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Bioestadística II</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Presentació</a></li>
<li class="part"><span><b>Part II: Estadística inferencial</b></span></li>
<li class="chapter" data-level="1" data-path="repàs-de-la-distribució-normal.html"><a href="repàs-de-la-distribució-normal.html"><i class="fa fa-check"></i><b>1</b> Repàs de la distribució normal</a><ul>
<li class="chapter" data-level="1.1" data-path="repàs-de-la-distribució-normal.html"><a href="repàs-de-la-distribució-normal.html#propietats-de-la-distribució-normal"><i class="fa fa-check"></i><b>1.1</b> Propietats de la distribució normal</a></li>
<li class="chapter" data-level="1.2" data-path="repàs-de-la-distribució-normal.html"><a href="repàs-de-la-distribució-normal.html#amb-r"><i class="fa fa-check"></i><b>1.2</b> Amb R</a></li>
<li class="chapter" data-level="1.3" data-path="repàs-de-la-distribució-normal.html"><a href="repàs-de-la-distribució-normal.html#combinacions-lineals"><i class="fa fa-check"></i><b>1.3</b> Combinacions lineals</a></li>
<li class="chapter" data-level="1.4" data-path="repàs-de-la-distribució-normal.html"><a href="repàs-de-la-distribució-normal.html#intervals-de-referència"><i class="fa fa-check"></i><b>1.4</b> Intervals de referència</a></li>
<li class="chapter" data-level="1.5" data-path="repàs-de-la-distribució-normal.html"><a href="repàs-de-la-distribució-normal.html#el-z-score"><i class="fa fa-check"></i><b>1.5</b> El z-score</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="estimació-puntual.html"><a href="estimació-puntual.html"><i class="fa fa-check"></i><b>2</b> Estimació puntual</a><ul>
<li class="chapter" data-level="2.1" data-path="estimació-puntual.html"><a href="estimació-puntual.html#definicions-bàsiques"><i class="fa fa-check"></i><b>2.1</b> Definicions bàsiques</a></li>
<li class="chapter" data-level="2.2" data-path="estimació-puntual.html"><a href="estimació-puntual.html#mitjana-mostral"><i class="fa fa-check"></i><b>2.2</b> Mitjana mostral</a></li>
<li class="chapter" data-level="2.3" data-path="estimació-puntual.html"><a href="estimació-puntual.html#proporció-mostral"><i class="fa fa-check"></i><b>2.3</b> Proporció mostral</a></li>
<li class="chapter" data-level="2.4" data-path="estimació-puntual.html"><a href="estimació-puntual.html#variància-mostral"><i class="fa fa-check"></i><b>2.4</b> Variància mostral</a></li>
<li class="chapter" data-level="2.5" data-path="estimació-puntual.html"><a href="estimació-puntual.html#la-t-de-student"><i class="fa fa-check"></i><b>2.5</b> La t de Student</a></li>
<li class="chapter" data-level="2.6" data-path="estimació-puntual.html"><a href="estimació-puntual.html#bons-estimadors"><i class="fa fa-check"></i><b>2.6</b> “Bons” estimadors</a><ul>
<li class="chapter" data-level="2.6.1" data-path="estimació-puntual.html"><a href="estimació-puntual.html#estimadors-no-esbiaixats"><i class="fa fa-check"></i><b>2.6.1</b> Estimadors no esbiaixats</a></li>
<li class="chapter" data-level="2.6.2" data-path="estimació-puntual.html"><a href="estimació-puntual.html#estimadors-eficients"><i class="fa fa-check"></i><b>2.6.2</b> Estimadors eficients</a></li>
<li class="chapter" data-level="2.6.3" data-path="estimació-puntual.html"><a href="estimació-puntual.html#estimadors-màxim-versemblants"><i class="fa fa-check"></i><b>2.6.3</b> Estimadors màxim versemblants</a></li>
</ul></li>
<li class="chapter" data-level="2.7" data-path="estimació-puntual.html"><a href="estimació-puntual.html#sec:pobl"><i class="fa fa-check"></i><b>2.7</b> Estimació de poblacions</a><ul>
<li class="chapter" data-level="2.7.1" data-path="estimació-puntual.html"><a href="estimació-puntual.html#estimació-de-poblacions-numerades"><i class="fa fa-check"></i><b>2.7.1</b> Estimació de poblacions numerades</a></li>
<li class="chapter" data-level="2.7.2" data-path="estimació-puntual.html"><a href="estimació-puntual.html#marca-recaptura"><i class="fa fa-check"></i><b>2.7.2</b> Marca-recaptura</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="intervals-de-confiança.html"><a href="intervals-de-confiança.html"><i class="fa fa-check"></i><b>3</b> Intervals de confiança</a><ul>
<li class="chapter" data-level="3.1" data-path="intervals-de-confiança.html"><a href="intervals-de-confiança.html#definicions-bàsiques-1"><i class="fa fa-check"></i><b>3.1</b> Definicions bàsiques</a></li>
<li class="chapter" data-level="3.2" data-path="intervals-de-confiança.html"><a href="intervals-de-confiança.html#exemple-interval-de-confiança-del-95-per-a-la-mitjana-duna-variable-aleatòria-normal"><i class="fa fa-check"></i><b>3.2</b> Exemple: Interval de confiança del 95% per a la mitjana d’una variable aleatòria normal</a></li>
<li class="chapter" data-level="3.3" data-path="intervals-de-confiança.html"><a href="intervals-de-confiança.html#interval-de-confiança-per-a-la-mitjana-basat-en-la-t-de-student"><i class="fa fa-check"></i><b>3.3</b> Interval de confiança per a la mitjana basat en la t de Student</a><ul>
<li class="chapter" data-level="" data-path="intervals-de-confiança.html"><a href="intervals-de-confiança.html#la-fórmula"><i class="fa fa-check"></i>La fórmula</a></li>
<li class="chapter" data-level="" data-path="intervals-de-confiança.html"><a href="intervals-de-confiança.html#algunes-consideracions"><i class="fa fa-check"></i>Algunes consideracions</a></li>
<li class="chapter" data-level="" data-path="intervals-de-confiança.html"><a href="intervals-de-confiança.html#amb-r-1"><i class="fa fa-check"></i>Amb R</a></li>
<li class="chapter" data-level="" data-path="intervals-de-confiança.html"><a href="intervals-de-confiança.html#càlcul-de-la-mida-de-la-mostra-per-fixar-lerror"><i class="fa fa-check"></i>Càlcul de la mida de la mostra per fixar l’error</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="intervals-de-confiança.html"><a href="intervals-de-confiança.html#intervals-de-confiança-per-a-proporcions"><i class="fa fa-check"></i><b>3.4</b> Intervals de confiança per a proporcions</a><ul>
<li class="chapter" data-level="" data-path="intervals-de-confiança.html"><a href="intervals-de-confiança.html#mètode-exacte-de-clopper-pearson"><i class="fa fa-check"></i>Mètode “exacte” de Clopper-Pearson</a></li>
<li class="chapter" data-level="" data-path="intervals-de-confiança.html"><a href="intervals-de-confiança.html#mètode-de-wilson"><i class="fa fa-check"></i>Mètode de Wilson</a></li>
<li class="chapter" data-level="" data-path="intervals-de-confiança.html"><a href="intervals-de-confiança.html#mètode-de-laplace"><i class="fa fa-check"></i>Mètode de Laplace</a></li>
<li class="chapter" data-level="" data-path="intervals-de-confiança.html"><a href="intervals-de-confiança.html#més-exemples"><i class="fa fa-check"></i>Més exemples</a></li>
<li class="chapter" data-level="" data-path="intervals-de-confiança.html"><a href="intervals-de-confiança.html#càlcul-de-la-mida-de-la-mostra-per-a-fixar-lerror"><i class="fa fa-check"></i>Càlcul de la mida de la mostra per a fixar l’error</a></li>
</ul></li>
<li class="chapter" data-level="3.5" data-path="intervals-de-confiança.html"><a href="intervals-de-confiança.html#intervals-de-confiança-per-a-la-variància-duna-variable-normal"><i class="fa fa-check"></i><b>3.5</b> Intervals de confiança per a la variància d’una variable normal</a></li>
<li class="chapter" data-level="3.6" data-path="intervals-de-confiança.html"><a href="intervals-de-confiança.html#poblacions-finites"><i class="fa fa-check"></i><b>3.6</b> “Poblacions finites”</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="contrastos-dhipòtesis-generalitats.html"><a href="contrastos-dhipòtesis-generalitats.html"><i class="fa fa-check"></i><b>4</b> Contrastos d’hipòtesis: Generalitats</a><ul>
<li class="chapter" data-level="4.1" data-path="contrastos-dhipòtesis-generalitats.html"><a href="contrastos-dhipòtesis-generalitats.html#hipòtesis-nulla-i-alternativa"><i class="fa fa-check"></i><b>4.1</b> Hipòtesis nul·la i alternativa</a></li>
<li class="chapter" data-level="4.2" data-path="contrastos-dhipòtesis-generalitats.html"><a href="contrastos-dhipòtesis-generalitats.html#sec:moneda"><i class="fa fa-check"></i><b>4.2</b> Un exemple</a></li>
<li class="chapter" data-level="4.3" data-path="contrastos-dhipòtesis-generalitats.html"><a href="contrastos-dhipòtesis-generalitats.html#sec:pval"><i class="fa fa-check"></i><b>4.3</b> El p-valor</a></li>
<li class="chapter" data-level="4.4" data-path="contrastos-dhipòtesis-generalitats.html"><a href="contrastos-dhipòtesis-generalitats.html#tipus-derrors"><i class="fa fa-check"></i><b>4.4</b> Tipus d’errors</a></li>
<li class="chapter" data-level="4.5" data-path="contrastos-dhipòtesis-generalitats.html"><a href="contrastos-dhipòtesis-generalitats.html#sec:exttest"><i class="fa fa-check"></i><b>4.5</b> Exemple: El test t</a></li>
<li class="chapter" data-level="4.6" data-path="contrastos-dhipòtesis-generalitats.html"><a href="contrastos-dhipòtesis-generalitats.html#recapitulació"><i class="fa fa-check"></i><b>4.6</b> Recapitulació</a><ul>
<li class="chapter" data-level="" data-path="contrastos-dhipòtesis-generalitats.html"><a href="contrastos-dhipòtesis-generalitats.html#interval-de-confiança-dun-contrast"><i class="fa fa-check"></i>Interval de confiança d’un contrast</a></li>
<li class="chapter" data-level="" data-path="contrastos-dhipòtesis-generalitats.html"><a href="contrastos-dhipòtesis-generalitats.html#la-potència"><i class="fa fa-check"></i>La potència</a></li>
<li class="chapter" data-level="" data-path="contrastos-dhipòtesis-generalitats.html"><a href="contrastos-dhipòtesis-generalitats.html#el-risc-de-positiu-fals-opcional"><i class="fa fa-check"></i>El risc de positiu fals (Opcional)</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="contrastos-dhipòtesis-dun-i-dos-paràmetres.html"><a href="contrastos-dhipòtesis-dun-i-dos-paràmetres.html"><i class="fa fa-check"></i><b>5</b> Contrastos d’hipòtesis d’un i dos paràmetres</a><ul>
<li class="chapter" data-level="5.1" data-path="contrastos-dhipòtesis-dun-i-dos-paràmetres.html"><a href="contrastos-dhipòtesis-dun-i-dos-paràmetres.html#contrastos-de-mitjanes"><i class="fa fa-check"></i><b>5.1</b> Contrastos de mitjanes</a><ul>
<li class="chapter" data-level="5.1.1" data-path="contrastos-dhipòtesis-dun-i-dos-paràmetres.html"><a href="contrastos-dhipòtesis-dun-i-dos-paràmetres.html#test-t-per-a-una-mitjana"><i class="fa fa-check"></i><b>5.1.1</b> Test t per a una mitjana</a></li>
<li class="chapter" data-level="5.1.2" data-path="contrastos-dhipòtesis-dun-i-dos-paràmetres.html"><a href="contrastos-dhipòtesis-dun-i-dos-paràmetres.html#test-t-per-a-dues-mitjanes"><i class="fa fa-check"></i><b>5.1.2</b> Test t per a dues mitjanes</a></li>
<li class="chapter" data-level="5.1.3" data-path="contrastos-dhipòtesis-dun-i-dos-paràmetres.html"><a href="contrastos-dhipòtesis-dun-i-dos-paràmetres.html#tests-t-amb-r"><i class="fa fa-check"></i><b>5.1.3</b> Tests t amb R</a></li>
<li class="chapter" data-level="5.1.4" data-path="contrastos-dhipòtesis-dun-i-dos-paràmetres.html"><a href="contrastos-dhipòtesis-dun-i-dos-paràmetres.html#exemples"><i class="fa fa-check"></i><b>5.1.4</b> Exemples</a></li>
<li class="chapter" data-level="5.1.5" data-path="contrastos-dhipòtesis-dun-i-dos-paràmetres.html"><a href="contrastos-dhipòtesis-dun-i-dos-paràmetres.html#tests-no-paramètrics"><i class="fa fa-check"></i><b>5.1.5</b> Tests no paramètrics</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="contrastos-dhipòtesis-dun-i-dos-paràmetres.html"><a href="contrastos-dhipòtesis-dun-i-dos-paràmetres.html#sec:contrvar"><i class="fa fa-check"></i><b>5.2</b> Contrastos de variàncies</a><ul>
<li class="chapter" data-level="5.2.1" data-path="contrastos-dhipòtesis-dun-i-dos-paràmetres.html"><a href="contrastos-dhipòtesis-dun-i-dos-paràmetres.html#test-chi2-duna-variància"><i class="fa fa-check"></i><b>5.2.1</b> Test <span class="math inline">\(\chi^2\)</span> d’una variància</a></li>
<li class="chapter" data-level="5.2.2" data-path="contrastos-dhipòtesis-dun-i-dos-paràmetres.html"><a href="contrastos-dhipòtesis-dun-i-dos-paràmetres.html#test-f-per-a-dues-variàncies"><i class="fa fa-check"></i><b>5.2.2</b> Test F per a dues variàncies</a></li>
<li class="chapter" data-level="5.2.3" data-path="contrastos-dhipòtesis-dun-i-dos-paràmetres.html"><a href="contrastos-dhipòtesis-dun-i-dos-paràmetres.html#tests-no-paramètrics-1"><i class="fa fa-check"></i><b>5.2.3</b> Tests no paramètrics</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="contrastos-dhipòtesis-dun-i-dos-paràmetres.html"><a href="contrastos-dhipòtesis-dun-i-dos-paràmetres.html#contrastos-per-a-proporcions"><i class="fa fa-check"></i><b>5.3</b> Contrastos per a proporcions</a><ul>
<li class="chapter" data-level="5.3.1" data-path="contrastos-dhipòtesis-dun-i-dos-paràmetres.html"><a href="contrastos-dhipòtesis-dun-i-dos-paràmetres.html#contrastos-per-a-una-proporció"><i class="fa fa-check"></i><b>5.3.1</b> Contrastos per a una proporció</a></li>
<li class="chapter" data-level="5.3.2" data-path="contrastos-dhipòtesis-dun-i-dos-paràmetres.html"><a href="contrastos-dhipòtesis-dun-i-dos-paràmetres.html#contrastos-per-a-2-proporcions-emprant-mostres-independents"><i class="fa fa-check"></i><b>5.3.2</b> Contrastos per a 2 proporcions emprant mostres independents</a></li>
<li class="chapter" data-level="5.3.3" data-path="contrastos-dhipòtesis-dun-i-dos-paràmetres.html"><a href="contrastos-dhipòtesis-dun-i-dos-paràmetres.html#contrastos-per-a-2-proporcions-emprant-mostres-aparellades"><i class="fa fa-check"></i><b>5.3.3</b> Contrastos per a 2 proporcions emprant mostres aparellades</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="contrastos-de-bondat-dajust.html"><a href="contrastos-de-bondat-dajust.html"><i class="fa fa-check"></i><b>6</b> Contrastos de bondat d’ajust</a><ul>
<li class="chapter" data-level="6.1" data-path="contrastos-de-bondat-dajust.html"><a href="contrastos-de-bondat-dajust.html#bondat-dajust"><i class="fa fa-check"></i><b>6.1</b> Bondat d’ajust</a></li>
<li class="chapter" data-level="6.2" data-path="contrastos-de-bondat-dajust.html"><a href="contrastos-de-bondat-dajust.html#test-chi2-de-pearson"><i class="fa fa-check"></i><b>6.2</b> Test <span class="math inline">\(\chi^2\)</span> de Pearson</a><ul>
<li class="chapter" data-level="6.2.1" data-path="contrastos-de-bondat-dajust.html"><a href="contrastos-de-bondat-dajust.html#el-test-bàsic"><i class="fa fa-check"></i><b>6.2.1</b> El test bàsic</a></li>
<li class="chapter" data-level="6.2.2" data-path="contrastos-de-bondat-dajust.html"><a href="contrastos-de-bondat-dajust.html#mètode-de-montecarlo"><i class="fa fa-check"></i><b>6.2.2</b> Mètode de Montecarlo</a></li>
<li class="chapter" data-level="6.2.3" data-path="contrastos-de-bondat-dajust.html"><a href="contrastos-de-bondat-dajust.html#test-chi2-amb-paràmetres-poblacionals-desconeguts"><i class="fa fa-check"></i><b>6.2.3</b> Test <span class="math inline">\(\chi^2\)</span> amb paràmetres poblacionals desconeguts</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="contrastos-de-bondat-dajust.html"><a href="contrastos-de-bondat-dajust.html#test-de-kolmogorov-smirnov"><i class="fa fa-check"></i><b>6.3</b> Test de Kolmogorov-Smirnov</a></li>
<li class="chapter" data-level="6.4" data-path="contrastos-de-bondat-dajust.html"><a href="contrastos-de-bondat-dajust.html#test-de-kolmogorov-smirnov-lilliefors"><i class="fa fa-check"></i><b>6.4</b> Test de Kolmogorov-Smirnov-Lilliefors</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="contrastos-dindependència-i-homogeneïtat.html"><a href="contrastos-dindependència-i-homogeneïtat.html"><i class="fa fa-check"></i><b>7</b> Contrastos d’independència i homogeneïtat</a><ul>
<li class="chapter" data-level="7.1" data-path="contrastos-dindependència-i-homogeneïtat.html"><a href="contrastos-dindependència-i-homogeneïtat.html#test-chi2-dindependència"><i class="fa fa-check"></i><b>7.1</b> Test <span class="math inline">\(\chi^2\)</span> d’independència</a></li>
<li class="chapter" data-level="7.2" data-path="contrastos-dindependència-i-homogeneïtat.html"><a href="contrastos-dindependència-i-homogeneïtat.html#test-chi2-dhomogeneïtat"><i class="fa fa-check"></i><b>7.2</b> Test <span class="math inline">\(\chi^2\)</span> d’homogeneïtat</a></li>
<li class="chapter" data-level="7.3" data-path="contrastos-dindependència-i-homogeneïtat.html"><a href="contrastos-dindependència-i-homogeneïtat.html#test-chi2-de-tendència-opcional"><i class="fa fa-check"></i><b>7.3</b> Test <span class="math inline">\(\chi^2\)</span> de tendència (Opcional)</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="introducció-a-lestadística-multidimensional.html"><a href="introducció-a-lestadística-multidimensional.html"><i class="fa fa-check"></i><b>8</b> Introducció a l’estadística multidimensional</a><ul>
<li class="chapter" data-level="8.1" data-path="introducció-a-lestadística-multidimensional.html"><a href="introducció-a-lestadística-multidimensional.html#poblacions-vectors-aleatoris"><i class="fa fa-check"></i><b>8.1</b> Poblacions: vectors aleatoris</a><ul>
<li class="chapter" data-level="8.1.1" data-path="introducció-a-lestadística-multidimensional.html"><a href="introducció-a-lestadística-multidimensional.html#covariància"><i class="fa fa-check"></i><b>8.1.1</b> Covariància</a></li>
<li class="chapter" data-level="8.1.2" data-path="introducció-a-lestadística-multidimensional.html"><a href="introducció-a-lestadística-multidimensional.html#correlació"><i class="fa fa-check"></i><b>8.1.2</b> Correlació</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="introducció-a-lestadística-multidimensional.html"><a href="introducció-a-lestadística-multidimensional.html#estadística-descriptiva-mostres"><i class="fa fa-check"></i><b>8.2</b> Estadística descriptiva: Mostres</a><ul>
<li class="chapter" data-level="8.2.1" data-path="introducció-a-lestadística-multidimensional.html"><a href="introducció-a-lestadística-multidimensional.html#covariàncies"><i class="fa fa-check"></i><b>8.2.1</b> Covariàncies</a></li>
<li class="chapter" data-level="8.2.2" data-path="introducció-a-lestadística-multidimensional.html"><a href="introducció-a-lestadística-multidimensional.html#correlació-de-pearson"><i class="fa fa-check"></i><b>8.2.2</b> Correlació de Pearson</a></li>
<li class="chapter" data-level="8.2.3" data-path="introducció-a-lestadística-multidimensional.html"><a href="introducció-a-lestadística-multidimensional.html#correlació-de-spearman"><i class="fa fa-check"></i><b>8.2.3</b> Correlació de Spearman</a></li>
<li class="chapter" data-level="8.2.4" data-path="introducció-a-lestadística-multidimensional.html"><a href="introducció-a-lestadística-multidimensional.html#contrastos-de-correlació"><i class="fa fa-check"></i><b>8.2.4</b> Contrastos de correlació</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="anova.html"><a href="anova.html"><i class="fa fa-check"></i><b>9</b> ANOVA</a><ul>
<li class="chapter" data-level="9.1" data-path="anova.html"><a href="anova.html#nocions-bàsiques"><i class="fa fa-check"></i><b>9.1</b> Nocions bàsiques</a></li>
<li class="chapter" data-level="9.2" data-path="anova.html"><a href="anova.html#anova-d1-via"><i class="fa fa-check"></i><b>9.2</b> ANOVA d’1 via</a><ul>
<li class="chapter" data-level="9.2.1" data-path="anova.html"><a href="anova.html#contrast-bàsic"><i class="fa fa-check"></i><b>9.2.1</b> Contrast bàsic</a></li>
<li class="chapter" data-level="9.2.2" data-path="anova.html"><a href="anova.html#amb-r-2"><i class="fa fa-check"></i><b>9.2.2</b> Amb R</a></li>
<li class="chapter" data-level="9.2.3" data-path="anova.html"><a href="anova.html#comparacions-posteriors-per-parelles"><i class="fa fa-check"></i><b>9.2.3</b> Comparacions posteriors per parelles</a></li>
<li class="chapter" data-level="9.2.4" data-path="anova.html"><a href="anova.html#verificació-de-les-condicions"><i class="fa fa-check"></i><b>9.2.4</b> Verificació de les condicions</a></li>
<li class="chapter" data-level="9.2.5" data-path="anova.html"><a href="anova.html#test-no-paramètric"><i class="fa fa-check"></i><b>9.2.5</b> Test no paramètric</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="anova.html"><a href="anova.html#anova-de-blocs"><i class="fa fa-check"></i><b>9.3</b> ANOVA de blocs</a><ul>
<li class="chapter" data-level="9.3.1" data-path="anova.html"><a href="anova.html#contrast-bàsic-1"><i class="fa fa-check"></i><b>9.3.1</b> Contrast bàsic</a></li>
<li class="chapter" data-level="9.3.2" data-path="anova.html"><a href="anova.html#amb-r-3"><i class="fa fa-check"></i><b>9.3.2</b> Amb R</a></li>
<li class="chapter" data-level="9.3.3" data-path="anova.html"><a href="anova.html#comparacions-posteriors-per-parelles-1"><i class="fa fa-check"></i><b>9.3.3</b> Comparacions posteriors per parelles</a></li>
<li class="chapter" data-level="9.3.4" data-path="anova.html"><a href="anova.html#contrast-no-paramètric"><i class="fa fa-check"></i><b>9.3.4</b> Contrast no paramètric</a></li>
</ul></li>
<li class="chapter" data-level="9.4" data-path="anova.html"><a href="anova.html#anova-de-2-vies"><i class="fa fa-check"></i><b>9.4</b> ANOVA de 2 vies</a><ul>
<li class="chapter" data-level="9.4.1" data-path="anova.html"><a href="anova.html#contrast-bàsic-2"><i class="fa fa-check"></i><b>9.4.1</b> Contrast bàsic</a></li>
<li class="chapter" data-level="9.4.2" data-path="anova.html"><a href="anova.html#amb-r-4"><i class="fa fa-check"></i><b>9.4.2</b> Amb R</a></li>
</ul></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Matemàtiques II</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="contrastos-dhipòtesis-dun-i-dos-paràmetres" class="section level1">
<h1><span class="header-section-number">Tema 5</span> Contrastos d’hipòtesis d’un i dos paràmetres</h1>

<div class="rmdimportant">
<p>Per adquirir un poc de disciplina en la realització de contrastos d’hipòtesis, procurau, almenys per ara, dividir-los en els apartats següents:</p>
<ol style="list-style-type: decimal">
<li><p>Variables aleatòries d’interès, incloent les seves unitats de mesura si en tenen, i els paràmetres poblacionals involucrats en el contrast</p></li>
<li><p>Contrast
<span class="math display">\[
\left\{\begin{array}{l}
H_{0}: ...\\
H_{1}: ... 
\end{array}
\right.
\]</span></p></li>
</ol>
<p>I a partir d’aquí, si el feu “a mà”:</p>
<ol start="3" style="list-style-type: decimal">
<li><p>Estadístic de contrast i distribució si la hipòtesi nul·la és vertadera</p></li>
<li><p>Valor de l’estadístic sobre la mostra</p></li>
<li><p>p-valor i si pot ser interval de confiança del nivell de significació demanat (0.05 per defecte)</p></li>
<li><p>Conclusió</p></li>
</ol>
<p>I si el feu amb R:</p>
<ol start="3" style="list-style-type: decimal">
<li><p>L’efectuau amb R</p></li>
<li><p>Conclusió</p></li>
</ol>
<p>Per a la conclusió, emprau la plantilla següent</p>
<blockquote>
<p>Hem obtingut evidència estadísticament significativa que passa tal cosa (test realitzat, p-valor …, IC 95% …).<br />
No hem obtingut evidència estadísticament significativa que passa tal cosa (test realitzat, p-valor …, IC 95% …).</p>
</blockquote>
</div>

<div id="contrastos-de-mitjanes" class="section level2">
<h2><span class="header-section-number">5.1</span> Contrastos de mitjanes</h2>
<div id="test-t-per-a-una-mitjana" class="section level3">
<h3><span class="header-section-number">5.1.1</span> Test t per a una mitjana</h3>
<p>Si estam en una de les dues situacions següents:</p>
<ul>
<li><p><span class="math inline">\(X\)</span> una variable aleatòria normal amb mitjana <span class="math inline">\(\mu\)</span> i en prenem una mostra aleatòria simple de mida <span class="math inline">\(n\)</span> qualsevol</p></li>
<li><p><span class="math inline">\(X\)</span> una variable aleatòria qualsevol amb mitjana <span class="math inline">\(\mu\)</span> i en prenem una mostra aleatòria simple de mida <span class="math inline">\(n\)</span> gran (diguem que de mida com a mínim 30)</p></li>
</ul>
<p>i volem realitzar un contrast
<span class="math display">\[
\left\{\begin{array}{l}
H_{0}:\mu=\mu_0\\ 
H_{1}:\mu \neq\mu_0\text{ o }\mu &gt;\mu_0\text{ o }\mu&lt;\mu_0
\end{array}
\right.
\]</span>
podem emprar el <strong>test t</strong> que ja hem explicat a la Secció <a href="contrastos-dhipòtesis-generalitats.html#sec:exttest">4.5</a>, basat en l’estadístic de contrast
<span class="math display">\[
T= \frac{\overline{X}-\mu_{0}}{{\widetilde{S}_X}/{\sqrt{n}}}
\]</span>
que, en les condicions donades i si <span class="math inline">\(\mu=\mu_0\)</span>, té una distribució (aproximadament, si <span class="math inline">\(X\)</span> no és normal però <span class="math inline">\(n\)</span> és gran) <span class="math inline">\(t_{n-1}\)</span>.</p>

<div class="example">
<p><span id="exm:ttest1" class="example"><strong>Exemple 5.1  </strong></span>Una organització ecologista afirma que el pes mitjà dels individus adults d’una espècie ha disminuït dràsticament.
Se sap per les dades històriques que el pes mitjà poblacional era de 460 g.</p>
</div>

<p>Una mostra aleatòria de 50 individus d’aquesta espècie ha donat una mitjana mostral de 428 g i una desviació típica mostral de 119 g. Amb aquestes dades, podem afirmar amb un nivell de significació del 5% que el pes mitjà és inferior a 460 g?</p>
<p><em>Variable aleatòria d’interès</em>: <span class="math inline">\(X\)</span>: “Prenem un animaló d’aquests i mesuram el seu pes, en grams”, amb mitjana <span class="math inline">\(\mu\)</span></p>
<p><em>Contrast</em>:
<span class="math display">\[
\left\{\begin{array}{l}
H_{0}:\mu=460\\
H_{1}:\mu&lt;460
\end{array}
\right.
\]</span></p>
<p>Prenem nivell de significació <span class="math inline">\(\alpha=0.05\)</span>.</p>
<p><em>Estadístic de contrast</em>: Com que <span class="math inline">\(n=50\)</span> és gran, podem usar
<span class="math display">\[
T=\frac{\overline{X}-\mu_0}{{\widetilde{S}_X}/{\sqrt{n}}}
\]</span>
que sí <span class="math inline">\(H_0\)</span> és vertadera serà (aproximadament) t de Student amb <span class="math inline">\(n-1=49\)</span> graus de llibertat</p>
<p><em>Valor de l’estadístic</em>:
<span class="math display">\[
\dfrac{428-460}{{119}/{\sqrt{50}}}=-1.9
\]</span></p>
<p><em>p-valor</em>:
<span class="math display">\[
P(T\leqslant-1.9)=\texttt{pt(-1.9,49)}=0.032
\]</span></p>
<p><em>Interval de confiança del 95%</em>:
<span class="math display">\[
\left(-\infty, \overline{X}+t_{n-1,1-\alpha}\cdot \frac{\widetilde{S}_X}{\sqrt{n}}\right]=(-\infty, 456.2]
\]</span></p>
<p><em>Conclusió</em>: Com que el p-valor és més petit que 0.05, concloem (amb <span class="math inline">\(\alpha=0.05\)</span>) que el pes mitjà actual és més petit que 460 g. De fet, amb un 95% de confiança podem afirmar que el pes mitjà actual és inferior a 456.2 g, que està per davall dels 460 g.</p>
<p>Amb la plantilla que us hem donat:</p>
<blockquote>
<p>Hem obtingut evidència estadísticament significativa que el pes mitjà actual és menor que 460 g (test t, p-valor 0.03, IC 95% de <span class="math inline">\(-\infty\)</span> a 456.2) i que per tant ha minvat en els darrers anys.</p>
</blockquote>
</div>
<div id="test-t-per-a-dues-mitjanes" class="section level3">
<h3><span class="header-section-number">5.1.2</span> Test t per a dues mitjanes</h3>
<p>Si estam en una de les situacions següents:</p>
<ul>
<li><p><span class="math inline">\(X_1,X_2\)</span> dues variables aleatòries normals de mitjanes <span class="math inline">\(\mu_1\)</span>, <span class="math inline">\(\mu_2\)</span> i en prenem mostres aleatòries simples de mides <span class="math inline">\(n_1\)</span>, <span class="math inline">\(n_2\)</span> qualssevol</p></li>
<li><p><span class="math inline">\(X_1,X_2\)</span> dues variables aleatòries qualssevol de mitjanes <span class="math inline">\(\mu_1\)</span>, <span class="math inline">\(\mu_2\)</span> i en prenem mostres aleatòries simples de mides <span class="math inline">\(n_1\)</span>, <span class="math inline">\(n_2\)</span> grans (diguem que <strong>totes dues</strong> de mida com a mínim 30)</p></li>
</ul>
<p>i volem realitzar un contrast
<span class="math display">\[
\left\{\begin{array}{l}
H_{0}:\mu_1=\mu_2\\ 
H_{1}:\mu_1 \neq\mu_2\text{ o }\mu_1 &gt;\mu_2\text{ o }\mu_1&lt;\mu_2
\end{array}
\right.
\]</span>
podem usar un <strong>test t</strong>, basat en un estadístic de contrast <span class="math inline">\(T\)</span> adequat que segueix una llei t de Student.</p>
<p>L’estadístic de contrast concret i els graus de llibertat de la seva distribució t de Student depenen:</p>
<ul>
<li><p>De si les dues mostres són <strong>independents</strong> (hem mesurat <span class="math inline">\(X_1\)</span> i <span class="math inline">\(X_2\)</span> sobre dues mostres obtingudes de manera independent una de l’altra) o <strong>aparellades</strong> (hem mesurat <span class="math inline">\(X_1\)</span> i <span class="math inline">\(X_2\)</span> sobre els subjectes d’una mateixa mostra o hi ha un aparellament natural entre els subjectes de les dues mostres)</p></li>
<li><p>Quan les mostres són independents, també depenen de si <span class="math inline">\(X_1\)</span> i <span class="math inline">\(X_2\)</span> <strong>tenen la mateixa variància o no</strong> (la qual cosa es pot decidir amb un altre contrast: vegeu la Secció <a href="contrastos-dhipòtesis-dun-i-dos-paràmetres.html#sec:contrvar">5.2</a>); per a mostres de la mateixa mida de variables normals, la conclusió sol ser la mateixa</p></li>
</ul>
<p>Quan les mostres són <strong>aparellades</strong>, podem entendre que tenim una sola mostra, formada per les parelles, sobre les quals mesuram la diferència <span class="math inline">\(X_1-X_2\)</span>. En aquest cas, traduïm
<span class="math display">\[
\left\{\begin{array}{l}
H_{0}:\mu_1=\mu_2\\ 
H_{1}:\mu_1 \neq\mu_2\text{ o }\mu_1 &gt;\mu_2\text{ o }\mu_1&lt;\mu_2
\end{array}
\right.
\]</span>
en
<span class="math display">\[
\left\{\begin{array}{l}
H_{0}:\mu_1-\mu_2=0\\ 
H_{1}:\mu_1-\mu_2 \neq0\text{ o }\mu_1-\mu_2 &gt;0\text{ o }\mu_1-\mu_2&lt;0
\end{array}
\right.
\]</span>
on <span class="math inline">\(\mu_1-\mu_2\)</span> és la mitjana de <span class="math inline">\(X_1-X_2\)</span>, i el consideram un contrast d’una sola mitjana, emprant com a mostra les diferències <span class="math inline">\(X_1-X_2\)</span> a les parelles.</p>
<p>Per tant, quan les mostres són aparellades, si diem <span class="math inline">\(D\)</span> a <span class="math inline">\(X_1-X_2\)</span>, <span class="math inline">\(\overline{D}\)</span> a la mitjana mostral de <span class="math inline">\(D\)</span> i <span class="math inline">\(\widetilde{S}_D\)</span> a la desviació típica mostral de <span class="math inline">\(D\)</span> sobre la mostra de parelles i diem <span class="math inline">\(n\)</span> a la mida de la mostra de parelles, l’estadístic de contrast és
<span class="math display">\[
T=\frac{\overline{D}}{\widetilde{S}_D/\sqrt{n}}
\]</span>
que, quan <span class="math inline">\(\mu_D=(\mu_1-\mu_2)=0\)</span>, té (aproximadament, si <span class="math inline">\(X_1,X_2\)</span> no són normals però la <span class="math inline">\(n\)</span> és gran) distribució <span class="math inline">\(t_{n-1}\)</span>.</p>
<p>Quan les mostres són <strong>independents</strong>, siguin <span class="math inline">\(\overline{X}_1\)</span> i <span class="math inline">\(\widetilde{S}^2_1\)</span> la mitjana mostral i la variància mostral de la mostra de <span class="math inline">\(X_1\)</span> i <span class="math inline">\(\overline{X}_2\)</span> i <span class="math inline">\(\widetilde{S}^2_2\)</span> la mitjana mostral i la variància mostral de la mostra de <span class="math inline">\(X_2\)</span>. Diguem, a més, <span class="math inline">\(\sigma_1^2\)</span> i <span class="math inline">\(\sigma_2^2\)</span> a les variàncies (poblacionals) de <span class="math inline">\(X_1\)</span> i <span class="math inline">\(X_2\)</span>. Aleshores:</p>
<ul>
<li><p>Si <span class="math inline">\(\sigma_1^2=\sigma_2^2\)</span>, l’estadístic de contrast és
<span class="math display">\[
T=\frac{\overline{X}_1-\overline{X}_2}{\sqrt{(\frac{1}{n_1}+\frac{1}{n_2})\cdot 
\frac{(n_1-1)\widetilde{S}_1^2+(n_2-1)\widetilde{S}_2^2}{n_1+n_2-2}}}
\]</span>
que, quan <span class="math inline">\(\mu_1=\mu_2\)</span>, té distribució (aproximadament, si <span class="math inline">\(X_1,X_2\)</span> no són normals però <span class="math inline">\(n_1\)</span> i <span class="math inline">\(n_2\)</span> són totes dues grans) <span class="math inline">\(t_{n_1+n_2-2}\)</span></p></li>
<li><p>Si <span class="math inline">\(\sigma_1^2\neq \sigma_2^2\)</span>, l’estadístic de contrast és
<span class="math display">\[
T=\frac{\overline{X}_1-\overline{X}_2}{\sqrt{\frac{\widetilde{S}_1^2}{n_1}+\frac{\widetilde{S}_2^2}{n_2}}}
\]</span>
que, quan <span class="math inline">\(\mu_1=\mu_2\)</span>, té distribució (aproximadament, si <span class="math inline">\(X_1,X_2\)</span> no són normals però <span class="math inline">\(n_1\)</span> i <span class="math inline">\(n_2\)</span> són totes dues grans) <span class="math inline">\(t_{\nu}\)</span> amb
<span class="math display">\[
\nu=\frac{\displaystyle \left( \frac{\widetilde{S}_1^2}{n_1}+\frac{\widetilde{S}_2^2}{n_2}\right)^2}
{\displaystyle \frac{1}{n_1-1}\left(\frac{\widetilde{S}_1^2}{n_1}\right)^2+\frac{1}{n_2-1}\left(\frac{\widetilde{S}_2^2}{n_2}\right)^2}
\]</span></p></li>
</ul>

<div class="rmdmercifulgod">
No cal que sapigueu aquestes fórmules per a mostres independents, només que l’estadístic de contrast i la seva distribució depenen de si les variàncies poblacionals són iguals o diferents.
</div>

<p>El nombre de graus de llibertat de la distribució t de Student usada en un contrast sobre dues mostres de mida <span class="math inline">\(n\)</span>:</p>
<ul>
<li><p>Si les mostres són aparellades, és <span class="math inline">\(n-1\)</span></p></li>
<li><p>Si les mostres són independents, és aproximadament <span class="math inline">\(2(n-1)\)</span></p></li>
</ul>
<p>Això fa que la probabilitat d’error de Tipus I del contrast amb mostres aparellades (a igualtat de la resta de valors) sigui més petita. Per exemple, suposem que volem realitzar el contrast
<span class="math display">\[
\left\{
\begin{array}{l}
H_0: \mu_1=\mu_2\\
H_1: \mu_1&gt;\mu_2
\end{array}
\right.
\]</span>
i que l’estadístic de contrast <span class="math inline">\(T\)</span> sobre dues mostres de mides <span class="math inline">\(n_1=n_2=20\)</span> dóna 1.7. Aleshores</p>
<ul>
<li><p>Si les mostres són independents,
<span class="math display">\[
\text{p-valor}=P(T&gt;1.7)\approx \texttt{1-pt(1.7,38)}=0.0487
\]</span></p></li>
<li><p>Si les mostres són aparellades,
<span class="math display">\[
\text{p-valor}=P(T&gt;1.7)=\texttt{1-pt(1.7,19)}=0.0527
\]</span></p></li>
</ul>
<p>Per tant, amb nivell de significació <span class="math inline">\(\alpha=0.05\)</span>, rebutjaríem la hipòtesi nul·la amb les mostres independents i l’acceptaríem amb les mostres aparellades.</p>
</div>
<div id="tests-t-amb-r" class="section level3">
<h3><span class="header-section-number">5.1.3</span> Tests t amb R</h3>
<p>Tots aquests tests t estan implementats en la funció de R</p>
<div class="sourceCode" id="cb185"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb185-1" data-line-number="1"><span class="kw">t.test</span>(x, y, <span class="dt">mu=</span>..., <span class="dt">alternative=</span>..., <span class="dt">paired=</span>...,</a>
<a class="sourceLine" id="cb185-2" data-line-number="2">       <span class="dt">var.equal=</span>..., <span class="dt">conf.level=</span>...)</a></code></pre></div>
<p>on:</p>
<ul>
<li><p>Entram com a <code>x</code> una mostra i a <code>mu</code> el valor amb el qual volem contrastar <span class="math inline">\(\mu\)</span>, o entram com a <code>x</code> i <code>y</code> les
mostres de <span class="math inline">\(X_1\)</span> i de <span class="math inline">\(X_2\)</span></p></li>
<li><p>A <code>alternative</code> hi hem d’indicar el tipus de contrast segons la hipòtesi alternativa:</p>
<ul>
<li><code>alternative=&quot;two.sided&quot;</code> (<span class="math inline">\(\neq\)</span>, el valor per defecte)</li>
<li><code>alternative=&quot;less&quot;</code> (<span class="math inline">\(&lt;\)</span>)</li>
<li><code>alternative=&quot;greater&quot;</code> (<span class="math inline">\(&gt;\)</span>)</li>
</ul></li>
<li><p>En el cas d’un contrast de dues mitjanes, a <code>paired</code> hi hem d’indicar si les mostres són independents, amb <code>paired=FALSE</code> (el valor per defecte), o aparellades, amb <code>paired=TRUE</code></p></li>
<li><p>En el cas d’un contrast de dues mitjanes amb mostres independents, a <code>var.equal</code> hi hem d’indicar si les variàncies són iguals, amb <code>var.equal=TRUE</code>, o diferents, amb <code>var.equal=FALSE</code> (el valor per defecte)</p></li>
<li><p>A <code>conf.level</code> hi hem d’especificar el nivell de confiança <span class="math inline">\(1-\alpha\)</span>: el seu valor per defecte és 0.95, que correspon al nivell de significació <span class="math inline">\(\alpha=0.05\)</span> usual</p></li>
</ul>
</div>
<div id="exemples" class="section level3">
<h3><span class="header-section-number">5.1.4</span> Exemples</h3>

<div class="example">
<p><span id="exm:temphomes1" class="example"><strong>Exemple 5.2  </strong></span>La temperatura mitjana del cos humà, és el valor usualment acceptat de 98.6<sup>o</sup> F (37<sup>o</sup> C)?</p>
</div>

<p>Per contrastar-ho, emprarem la taula de dades <strong>Body_Temperature.txt</strong>, construïda per P.A. Mackowiak, S. S. Wasserman i M.M. Levine en 1992 precisament per realitzar aquest contrast i que trobareu a l’Aula Digital.</p>
<p><em>Variable aleatòria d’interès</em>: <span class="math inline">\(X\)</span>: “Prenem una persona i li miram la temperatura, en graus F”, amb mitjana <span class="math inline">\(\mu\)</span></p>
<p><em>Contrast</em>:
<span class="math display">\[
\left\{\begin{array}{l}
H_{0}:\mu=98.6\\
H_{1}:\mu \neq 98.6
\end{array}
\right.
\]</span></p>
<p>Realitzarem aquest contrast amb R. Carregam la taula de temperatures, que prèviament hem guardat en el directori de treball de R, en un dataframe que anomenarem <code>BT</code>.</p>
<div class="sourceCode" id="cb186"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb186-1" data-line-number="1">BT=<span class="kw">read.table</span>(<span class="st">&quot;Body_Temperature.txt&quot;</span>)</a>
<a class="sourceLine" id="cb186-2" data-line-number="2"><span class="kw">head</span>(BT)</a></code></pre></div>
<pre><code>##   Gender HeartRate Temperature
## 1      M        69        97.0
## 2      M        72        98.8
## 3      M        68        96.2
## 4      F        75        97.8
## 5      F        68        98.8
## 6      M        79       101.3</code></pre>
<div class="sourceCode" id="cb188"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb188-1" data-line-number="1"><span class="kw">str</span>(BT)</a></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    230 obs. of  3 variables:
##  $ Gender     : chr  &quot;M&quot; &quot;M&quot; &quot;M&quot; &quot;F&quot; ...
##  $ HeartRate  : int  69 72 68 75 68 79 71 73 77 81 ...
##  $ Temperature: num  97 98.8 96.2 97.8 98.8 ...</code></pre>
<p>Veiem que la taula <code>BT</code> consta de 230 individus i 3 variables mesurades sobre cadascun d’ells: el sexe (variable <code>Gender</code>, amb nivells <code>F</code> per a dona i <code>M</code> per a home), les pulsacions per minut (variable <code>HeartRate</code>) i la temperatura en graus F (variable <code>Temperature</code>).</p>
<p>Com que la mostra és gran, <span class="math inline">\(n=230\)</span>, podem emprar un test t. Emprarem la funció <code>t.test</code>, aplicant-la al vector de temperatures i al valor que contrastam, 98.6, entrat amb el parametre <code>mu</code>. El paràmetre <code>alternative=&quot;two.sided&quot;</code> indica que el test serà bilateral.</p>
<div class="sourceCode" id="cb190"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb190-1" data-line-number="1"><span class="kw">t.test</span>(BT<span class="op">$</span>Temperature, <span class="dt">mu=</span><span class="fl">98.6</span>, <span class="dt">alternative=</span><span class="st">&quot;two.sided&quot;</span>)</a></code></pre></div>
<pre><code>## 
##  One Sample t-test
## 
## data:  BT$Temperature
## t = -5.7205, df = 229, p-value = 3.301e-08
## alternative hypothesis: true mean is not equal to 98.6
## 95 percent confidence interval:
##  98.17563 98.39307
## sample estimates:
## mean of x 
##  98.28435</code></pre>
<p>Del resultat cal destacar:</p>
<ul>
<li><p>El p-valor, <code>p-value</code>, en el nostre cas 3.301·10<sup>-8</sup> (R l’ha escrit en notació científica: 3.301e-08).</p></li>
<li><p>L’IC 95%, <code>95 percent confidence interval</code>, per al valor que contrastam (aquí, la temperatura mitjana poblacional), en el nostre cas [98.17563, 98.39307].</p></li>
<li><p>La mitjana mostral de la mostra, <code>sample of x</code>, en el nostre cas 98.28435.</p></li>
</ul>
<p>Per tant:</p>
<ul>
<li><p>El p-valor és 3·10<sup>-8</sup>, per la qual cosa amb les dades d’aquesta taula obtenim evidència estadísticament significativa que la temperatura mitjana del cos humà no és de 98.6<sup>o</sup> F (37<sup>o</sup> C)</p></li>
<li><p>A més, com que l’IC 95% per a la temperatura mitjana del cos humà que hem obtingut va de 98.2 a 98.4 (36.78 a 36.89<sup>o</sup> C), hem trobat evidència amb aquest nivell de confiança que aquesta temperatura mitjana és de fet (lleugerament) inferior 98.6<sup>o</sup> F</p></li>
</ul>
<p><em>Conclusió</em>: Hem obtingut evidència estadísticament significativa que la temperatura mitjana del cos humà no és de 98.6<sup>o</sup> F (test t, p-valor 3·10<sup>-8</sup>, IC 95% de 98.2 a 98.4).</p>

<div class="example">
<p><span id="exm:temphomesdones" class="example"><strong>Exemple 5.3  </strong></span>La temperatura dels homes, és més alta que la de les dones?</p>
</div>

<p>Per resoldre aquesta qüestió, emprarem la mateixa taula de dades que abans.</p>
<p><em>Variables aleatòries d’interès</em>:</p>
<ul>
<li><span class="math inline">\(X_d\)</span>: “Prenem una dona i li miram la temperatura, en graus F”, amb mitjana <span class="math inline">\(\mu_d\)</span></li>
<li><span class="math inline">\(X_h\)</span>: “Prenem un home i li miram la temperatura, en graus F”, amb mitjana <span class="math inline">\(\mu_h\)</span></li>
</ul>
<p><em>Contrast</em>: Plantejarem el contrast en termes de temperatures mitjanes:
<span class="math display">\[
\left\{\begin{array}{l}
H_{0}:\mu_d=\mu_h\\
H_{1}:\mu_d&lt; \mu_h
\end{array}
\right.
\]</span></p>
<p>Per poder emprar un t test, primer ens cal saber si hi ha nombres suficientment grans d’homes i dones a la nostra mostra per emprar-lo. Per això calcularem la taula de freqüències dels sexes, aplicant la funció <code>table</code> al vector <code>BT$Gender</code> dels sexes:</p>
<div class="sourceCode" id="cb192"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb192-1" data-line-number="1"><span class="kw">table</span>(BT<span class="op">$</span>Gender)</a></code></pre></div>
<pre><code>## 
##   F   M 
## 116 114</code></pre>
<p>Són prou grans.</p>
<p>Anam a crear uns vectors amb les temperatures d’homes i de dones. Recordau que hi ha diverses maneres d’extreure d’un dataframe el vector de valors d’una variable <code>V1</code> per als individus que prenen un valor concret <code>X</code> en una altra variable <code>V2</code>: per exemple <code>dataframe$V1[V2==X]</code> o <code>dataframe[V2==X,V1]</code>. Així, les temperatures dels homes (individus on la variable <code>Gender</code> és igual a <code>M</code>) són</p>
<div class="sourceCode" id="cb194"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb194-1" data-line-number="1">BT<span class="op">$</span>Temperature[BT<span class="op">$</span>Gender<span class="op">==</span><span class="st">&quot;M&quot;</span>]</a></code></pre></div>
<pre><code>##   [1]  97.0  98.8  96.2 101.3  99.2  97.5  97.3  98.6  99.0  98.0  97.0  97.6
##  [13]  99.0  97.1  98.9  98.6  98.9  97.2  98.0  99.4  98.8  98.5  99.6  97.3
##  [25]  96.5  97.8  98.3  98.1  98.8  97.7  98.3  97.7  99.1  98.8  97.4  96.9
##  [37]  98.0  98.4 100.3  97.0  99.0 100.6  98.0  98.5  97.0  97.0  98.6  97.8
##  [49]  97.3  96.3  96.7  96.9  97.0  97.1  97.1  97.1  97.2  97.3  97.4  97.4
##  [61]  97.4  97.4  97.5  97.5  97.6  97.6  97.6  97.7  97.8  97.8  97.8  97.8
##  [73]  97.9  97.9  98.0  98.0  98.0  98.0  98.0  98.0  98.1  98.1  98.2  98.2
##  [85]  98.2  98.2  98.3  98.3  98.4  98.4  98.4  98.4  98.5  98.5  98.6  98.6
##  [97]  98.6  98.6  98.6  98.6  98.7  98.7  98.8  98.8  98.8  98.9  99.0  99.0
## [109]  99.0  99.1  99.2  99.3  99.4  99.5</code></pre>
<p>Bé, cream els vectors <span class="math inline">\(X_d\)</span> (dones) i <span class="math inline">\(X_h\)</span> (homes)</p>
<div class="sourceCode" id="cb196"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb196-1" data-line-number="1">X_d=BT[BT<span class="op">$</span>Gender<span class="op">==</span><span class="st">&quot;F&quot;</span>,<span class="st">&quot;Temperature&quot;</span>]  <span class="co">#temperatures de dones</span></a>
<a class="sourceLine" id="cb196-2" data-line-number="2">X_h=BT[BT<span class="op">$</span>Gender<span class="op">==</span><span class="st">&quot;M&quot;</span>,<span class="st">&quot;Temperature&quot;</span>]  <span class="co">#temperatures d&#39;homes</span></a></code></pre></div>
<p>Per portar a terme un test t per comparar dues mitjanes, aplicam la funció <code>t.test</code> als vectors <code>X_d</code>i <code>X_h</code> amb paràmetre <code>alternative=&quot;less&quot;</code> per indicar que el test és unilateral: la hipòtesi alternativa és que la mitjana de la primera població (dones) és més petita que la de la segona (homes). En aquest exemple, a més, especificarem que les mostres són independents amb <code>paired=FALSE</code> (no caldria, ja que és el valor per defecte) i a més hem d’especificar si les variàncies poblacionals són iguals (<code>var.equal=TRUE</code>) o diferents (<code>var.equal=FALSE</code>). El que farem aquí serà provar els dos casos: amb les variàncies iguals i amb les variàncies diferents. Si les dues conclusions són la mateixa, aquesta serà la conclusió que prendrem. Si dóna diferent, haurem de realitzar un contrast previ per decidir si hem de suposar que les variàncies són iguals o diferents.</p>
<div class="sourceCode" id="cb197"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb197-1" data-line-number="1"><span class="kw">t.test</span>(X_d, X_h, <span class="dt">alternative=</span><span class="st">&quot;less&quot;</span>,<span class="dt">paired=</span><span class="ot">FALSE</span>, <span class="dt">var.equal=</span><span class="ot">TRUE</span>)</a></code></pre></div>
<pre><code>## 
##  Two Sample t-test
## 
## data:  X_d and X_h
## t = 2.5379, df = 228, p-value = 0.9941
## alternative hypothesis: true difference in means is less than 0
## 95 percent confidence interval:
##       -Inf 0.4569566
## sample estimates:
## mean of x mean of y 
##  98.42155  98.14474</code></pre>
<div class="sourceCode" id="cb199"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb199-1" data-line-number="1"><span class="kw">t.test</span>(X_d, X_h, <span class="dt">alternative=</span><span class="st">&quot;less&quot;</span>,<span class="dt">paired=</span><span class="ot">FALSE</span>, <span class="dt">var.equal=</span><span class="ot">FALSE</span>)</a></code></pre></div>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  X_d and X_h
## t = 2.5358, df = 225.32, p-value = 0.9941
## alternative hypothesis: true difference in means is less than 0
## 95 percent confidence interval:
##       -Inf 0.4571095
## sample estimates:
## mean of x mean of y 
##  98.42155  98.14474</code></pre>
<p>En tots dos casos obtenim un p-valor (<code>p-value</code>) gran. L’IC 95 % (<code>95 percent confidence interval</code>) que ens dóna és per a la diferència de les mitjanes. Com que conté el 0, no podem descartar que les dues mitjanes siguin iguals.</p>
<p><em>Conclusió</em>: No hem obtingut evidència estadísticament significativa que la temperatura mitjana de les dones sigui més baixa que la dels homes (test t, p-valor 0.99, IC 95% per a la diferència de les mitjanes de <span class="math inline">\(-\infty\)</span> a 0.46).</p>

<div class="rmdnote">
Vegem, si <span class="math inline">\(\overline{X_d}=98.42\)</span> i <span class="math inline">\(\overline{X_h}=98.14\)</span>, com volíeu que obtinguéssim evidència que <span class="math inline">\(\mu_d&lt;\mu_h\)</span>? <strong>Mirau sempre les dades primer!</strong>
</div>

<p>Si, per exemple, haguéssim dibuixat abans del contrast un diagrama de caixes de les temperatures separades per sexe, hauríem vist que era impossible obtenir evidència que les dones tenen temperatura mitjana inferior als homes, i no hauria fet falta continuar.</p>
<div class="sourceCode" id="cb201"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb201-1" data-line-number="1"><span class="kw">boxplot</span>(Temperature<span class="op">~</span>Gender,<span class="dt">data=</span>BT,<span class="dt">names=</span><span class="kw">c</span>(<span class="st">&quot;Dones&quot;</span>,<span class="st">&quot;Homes&quot;</span>),<span class="dt">xlab=</span><span class="st">&quot;&quot;</span>,<span class="dt">ylab=</span><span class="st">&quot;Temperatura&quot;</span>)</a></code></pre></div>
<p><img src="Bioestadistica-II_files/figure-html/unnamed-chunk-276-1.png" width="50%" style="display: block; margin: auto;" /></p>
<p><strong>Exercici</strong>: Emprant les mateixes dades, trobau evidència que <span class="math inline">\(\mu_h&lt;\mu_d\)</span>? I que <span class="math inline">\(\mu_h\neq \mu_d\)</span>? Spoiler:</p>
<p><img src="Bioestadistica-II_files/figure-html/tempcorp3.png" width="50%" style="display: block; margin: auto;" /></p>

<div class="example">
<p><span id="exm:oatbran" class="example"><strong>Exemple 5.4  </strong></span>Desdijunar segó de civada (<em>oat bran</em>) en lloc de flocs de blat de moro (<em>corn flakes</em>), ajuda a reduir el nivell de colesterol?</p>
</div>

<p>Per resoldre aquesta qüestió, emprarem la taula de dades <strong>oatbran.txt</strong>, que trobareu a l’Aula Digital. Aquestes dades es recolliren en un assaig creuat sobre 14 individus. A cada un d’ells se li assignà un dels dos desdijunis de manera aleatòria i el prengueren durant 15 dies. Al final d’aquest període, se’ls mesurà el nivell de colesterol en sang. Passat un mes de descans, cada participant va desdijunar durant 15 dies l’altre producte, i al final se’ls tornà a mesurar el nivell de colesterol en sang. En aquesta taula, aquests nivells de colesterol estan mesurats en milimols per litre</p>
<!-- (J. Anderson \textsl{et a el}, ``Oat-bran cereal lowers serum total and LDL cholesterol in hypercholesterolemic men.'' \textsl{The American journal of clinical nutrition} 52 (1990), 495--499)
-->
<p><em>Variables aleatòries d’interès</em>:</p>
<ul>
<li><span class="math inline">\(X_{ob}\)</span>: “Prenem una persona que desdijuna <em>oat bran</em> i li mesuram el nivell de colesterol en mmol/l”, amb mitjana <span class="math inline">\(\mu_{ob}\)</span></li>
<li><span class="math inline">\(X_{cf}\)</span>: “Prenem una persona que desdijuna <em>corn flakes</em> i li mesuram el nivell de colesterol en mmol/l”, amb mitjana <span class="math inline">\(\mu_{cf}\)</span></li>
</ul>
<p><em>Contrast</em>: El plantejarem en termes de nivells mitjans de colesterol:
<span class="math display">\[
\left\{\begin{array}{l}
H_{0}:\mu_{ob}=\mu_{cf}\\
H_{1}:\mu_{ob}&lt; \mu_{cf}
\end{array}
\right.
\]</span></p>
<p>Carregam la taula de dades, que prèviament hem guardat en el directori de treball de R, en un dataframe al que anomenam <code>OBR</code> i consultam la seva estructura:</p>
<div class="sourceCode" id="cb202"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb202-1" data-line-number="1">OBR=<span class="kw">read.table</span>(<span class="st">&quot;oatbran.txt&quot;</span>,<span class="dt">header=</span><span class="ot">TRUE</span>)</a>
<a class="sourceLine" id="cb202-2" data-line-number="2"><span class="kw">head</span>(OBR)</a></code></pre></div>
<pre><code>##   CORNFLK OATBRAN
## 1    4.61    3.94
## 2    6.42    5.57
## 3    5.40    5.85
## 4    4.54    4.80
## 5    3.98    3.68
## 6    3.82    2.96</code></pre>
<div class="sourceCode" id="cb204"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb204-1" data-line-number="1"><span class="kw">str</span>(OBR)</a></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    14 obs. of  2 variables:
##  $ CORNFLK: num  4.61 6.42 5.4 4.54 3.98 3.82 5.01 4.34 3.8 4.56 ...
##  $ OATBRAN: num  3.94 5.57 5.85 4.8 3.68 2.96 4.41 3.72 3.49 3.94 ...</code></pre>
<p>N’extraiem les dues variables en forma de vectors:</p>
<div class="sourceCode" id="cb206"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb206-1" data-line-number="1">OAT=OBR<span class="op">$</span>OATBRAN</a>
<a class="sourceLine" id="cb206-2" data-line-number="2">CFL=OBR<span class="op">$</span>CORNFLK</a></code></pre></div>
<p>Com que 14 dades són poques, si volem aplicar un test t necessitam que provinguin d’una distribució normal. Per decidir si és veritat o no, més endavant explicarem contrastos de bondat d’ajust, amb hipòtesi nul·la “Aquesta mostra prové d’una variable aleatòria amb tal distribució” i hipòtesi alternativa “No és veritat que aquesta mostra provengui d’una variable aleatòria amb tal distribució”. Per ara ens conformarem amb decidir-ho a partir d’un gràfic.</p>
<p>A Matemàtiques I us explicàvem que podeu dibuixar un histograma d’una mostra afegint-hi la densitat estimada, a partir de la mostra, de la variable poblacional i la densitat d’una distribució normal amb mitjana i desviació típica les de la mostra, i mirar si sembla que les dades segueixen aquesta distribució normal. Però amb poques dades això és mal de veure:</p>
<div class="sourceCode" id="cb207"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb207-1" data-line-number="1"><span class="kw">hist</span>(OAT,<span class="dt">freq=</span><span class="ot">FALSE</span>, <span class="dt">breaks=</span><span class="dv">4</span>,<span class="dt">col=</span><span class="st">&quot;light blue&quot;</span>,<span class="dt">xlab=</span><span class="st">&quot;Colesterol&quot;</span>,</a>
<a class="sourceLine" id="cb207-2" data-line-number="2">     <span class="dt">ylab=</span><span class="st">&quot;Densitat&quot;</span>, <span class="dt">main=</span><span class="st">&quot;Histograma de OATBRAN&quot;</span>,<span class="dt">ylim=</span><span class="kw">c</span>(<span class="dv">0</span>,<span class="kw">max</span>(<span class="kw">density</span>(OAT)<span class="op">$</span>y)))</a>
<a class="sourceLine" id="cb207-3" data-line-number="3"><span class="kw">lines</span>(<span class="kw">density</span>(OAT),<span class="dt">lty=</span><span class="dv">2</span>,<span class="dt">lwd=</span><span class="dv">2</span>)</a>
<a class="sourceLine" id="cb207-4" data-line-number="4"><span class="kw">curve</span>(<span class="kw">dnorm</span>(x,<span class="kw">mean</span>(OAT),<span class="kw">sd</span>(OAT)),<span class="dt">col=</span><span class="st">&quot;red&quot;</span>,<span class="dt">lwd=</span><span class="dv">2</span>,<span class="dt">add=</span><span class="ot">TRUE</span>)</a>
<a class="sourceLine" id="cb207-5" data-line-number="5"><span class="kw">legend</span>(<span class="st">&quot;topright&quot;</span>,<span class="dt">legend=</span><span class="kw">c</span>(<span class="st">&quot;Densitat estimada&quot;</span>,<span class="st">&quot;Normal&quot;</span>),</a>
<a class="sourceLine" id="cb207-6" data-line-number="6">       <span class="dt">col=</span><span class="kw">c</span>(<span class="st">&quot;black&quot;</span>,<span class="st">&quot;red&quot;</span>),<span class="dt">lty=</span><span class="kw">c</span>(<span class="dv">2</span>,<span class="dv">1</span>),<span class="dt">cex=</span><span class="fl">0.75</span>)</a>
<a class="sourceLine" id="cb207-7" data-line-number="7"><span class="co">#</span></a>
<a class="sourceLine" id="cb207-8" data-line-number="8"><span class="kw">hist</span>(CFL,<span class="dt">freq=</span><span class="ot">FALSE</span>, <span class="dt">breaks=</span><span class="dv">4</span>,<span class="dt">col=</span><span class="st">&quot;light blue&quot;</span>,<span class="dt">xlab=</span><span class="st">&quot;Colesterol&quot;</span>,</a>
<a class="sourceLine" id="cb207-9" data-line-number="9">     <span class="dt">ylab=</span><span class="st">&quot;Densitat&quot;</span>, <span class="dt">main=</span><span class="st">&quot;Histograma de CORNFLK&quot;</span>,,<span class="dt">ylim=</span><span class="kw">c</span>(<span class="dv">0</span>,<span class="kw">max</span>(<span class="kw">density</span>(CFL)<span class="op">$</span>y)))</a>
<a class="sourceLine" id="cb207-10" data-line-number="10"><span class="kw">curve</span>(<span class="kw">dnorm</span>(x,<span class="kw">mean</span>(CFL),<span class="kw">sd</span>(CFL)),<span class="dt">col=</span><span class="st">&quot;red&quot;</span>,<span class="dt">lwd=</span><span class="dv">2</span>,<span class="dt">add=</span><span class="ot">TRUE</span>)</a>
<a class="sourceLine" id="cb207-11" data-line-number="11"><span class="kw">lines</span>(<span class="kw">density</span>(CFL),<span class="dt">lty=</span><span class="dv">2</span>,<span class="dt">lwd=</span><span class="dv">2</span>)</a>
<a class="sourceLine" id="cb207-12" data-line-number="12"><span class="kw">legend</span>(<span class="st">&quot;topright&quot;</span>,<span class="dt">legend=</span><span class="kw">c</span>(<span class="st">&quot;Densitat estimada&quot;</span>,<span class="st">&quot;Normal&quot;</span>),</a>
<a class="sourceLine" id="cb207-13" data-line-number="13">       <span class="dt">col=</span><span class="kw">c</span>(<span class="st">&quot;black&quot;</span>,<span class="st">&quot;red&quot;</span>),<span class="dt">lty=</span><span class="kw">c</span>(<span class="dv">2</span>,<span class="dv">1</span>),<span class="dt">cex=</span><span class="fl">0.75</span>)</a></code></pre></div>
<p><img src="Bioestadistica-II_files/figure-html/unnamed-chunk-281-1.png" width="90%" style="display: block; margin: auto;" /></p>
<p>En aquest cas, una opció millor és dibuixar un <em>q-q-plot</em>. Un <strong>q-q-plot</strong> d’una mostra i una distribució teòrica és el gràfic dels <strong>q-q-punts</strong>: els punts de la forma <em>(q-quantil de la distribució, q-quantil de la mostra)</em>, per a tots els valors de q que tengui sentit donada la mida de la mostra. Quan la distribució amb la que comparam la mostra és una normal, se’n diu un <strong>normal-plot</strong>.</p>
<p>Si la mostra prové de la distribució emprada en el q-q-plot, és d’esperar que el q-quantil de la mostra sigui aproximadament igual al q-quantil de la distribució i per tant que aquests q-q-punts estiguin prop de la diagonal principal <span class="math inline">\(y=x\)</span>.</p>
<p>La funció <code>qqPlot</code> del paquet <strong>car</strong> produeix uns <em>q-q-plots</em> que contenen una regió de confiança del 95% que especifica què vol dir això que “els q-q-punts estiguin prop de la diagonal principal <span class="math inline">\(y=x\)</span>”, amb el significat usual de nivell de confiança. L’explicam amb detall a la <a href="https://aprender-uib.github.io/AprendeR2/chap-bondad.html">lliçó de R sobre Contrastos de Bondat d’Ajust</a>.</p>
<div class="sourceCode" id="cb208"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb208-1" data-line-number="1"><span class="kw">library</span>(car)</a>
<a class="sourceLine" id="cb208-2" data-line-number="2"><span class="kw">qqPlot</span>(OAT, <span class="dt">distribution=</span><span class="st">&quot;norm&quot;</span>, <span class="dt">mean=</span><span class="kw">mean</span>(OAT), <span class="dt">sd=</span><span class="kw">sd</span>(OAT),</a>
<a class="sourceLine" id="cb208-3" data-line-number="3">        <span class="dt">ylab=</span><span class="st">&quot;Quantils de OATBRAN&quot;</span>, <span class="dt">xlab=</span><span class="st">&quot;Quantils de normal&quot;</span>, <span class="dt">pch=</span><span class="dv">20</span>, <span class="dt">id=</span><span class="ot">FALSE</span>)</a>
<a class="sourceLine" id="cb208-4" data-line-number="4"><span class="kw">qqPlot</span>(CFL, <span class="dt">distribution=</span><span class="st">&quot;norm&quot;</span>, <span class="dt">mean=</span><span class="kw">mean</span>(CFL),<span class="dt">sd=</span><span class="kw">sd</span>(CFL),</a>
<a class="sourceLine" id="cb208-5" data-line-number="5">       <span class="dt">ylab=</span><span class="st">&quot;Quantils de CORNFLK&quot;</span>, <span class="dt">xlab=</span><span class="st">&quot;Quantils de normal&quot;</span>, <span class="dt">pch=</span><span class="dv">20</span>, <span class="dt">id=</span><span class="ot">FALSE</span>)</a></code></pre></div>
<p><img src="Bioestadistica-II_files/figure-html/unnamed-chunk-283-1.png" width="90%" style="display: block; margin: auto;" /></p>
<p>Aceptarem per tant que les nostres dades provenen de dues distribucions normals: podem fer servir la funció <code>t.test</code>.</p>
<p>En aquest cas, el test t és de mostres aparellades (hem mesurat les dues variable aleatòries sobre els mateixos individus), per la qual cosa hem d’especificar <code>paired=TRUE</code> i no hem d’especificar el paràmetre <code>var.equal</code>. Emprarem el paràmetre <code>alternative=&quot;less&quot;</code> per indicar que el test és unilateral: la hipòtesi alternativa és que la mitjana de la primera població és més petita que la de la segona.</p>
<div class="sourceCode" id="cb209"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb209-1" data-line-number="1"><span class="kw">t.test</span>(OAT,CFL,<span class="dt">alternative=</span><span class="st">&quot;less&quot;</span>, <span class="dt">paired=</span><span class="ot">TRUE</span>)</a></code></pre></div>
<pre><code>## 
##  Paired t-test
## 
## data:  OAT and CFL
## t = -3.3195, df = 13, p-value = 0.002768
## alternative hypothesis: true difference in means is less than 0
## 95 percent confidence interval:
##        -Inf -0.1626132
## sample estimates:
## mean of the differences 
##              -0.3485714</code></pre>
<p>Com abans, el resultat inclou el p-valor, l’IC 95% per a la mitjana de les diferències (que és igual a la diferència de les mitjanes: recordau que <span class="math inline">\(E(X-Y)=E(X)-E(Y)\)</span>) i ara, com a novetat, la mitjana de les diferències (<code>mean of the differences</code>) en comptes de les dues mitjanes.</p>
<p><em>Conclusió</em>: Hem obtingut evidència estadísticament significativa que desdijunar <em>oatbran</em> redueix el nivell mitjà de colesterol respecte de desdijunar <em>corn flakes</em> (test t, p-valor 0.003, IC 95% per a la diferència de les mitjanes de <span class="math inline">\(-\infty\)</span> a -0.163).</p>

<div class="example">
<p><span id="exm:sangumbil" class="example"><strong>Exemple 5.5  </strong></span>Volem contrastar si el nivell de triglicèrids als nadons de 2 setmanes és més alt que el del seu cordó umbilical. Per fer-ho, emprarem les dades d’una mostra de 25 nadons als quals els mesuraren els nivells de triglicèrids en plasma a la sang del seu cordó umbilical i en la seva sang al cap de 2 setmanes de néixer (les dues en ng/dl). Tenim les dades a la taula <strong>trignadons.txt</strong> que trobareu a l’Aula Digital. Les seves variables són <code>CU</code>, les mesures del cordó umbilical, <code>DS</code>, les mesures al cap de dues setmanes, i <code>Nin</code>, que identifica el nadó.</p>
</div>

<p><em>Variables aleatòries d’interès</em>:</p>
<ul>
<li><span class="math inline">\(X_{cu}\)</span>: “Prenem un recent nat i mesuram el nivell de triglicèrids en plasma a la sang del seu cordó umbilical en ng/dl”, amb mitjana <span class="math inline">\(\mu_{cu}\)</span></li>
<li><span class="math inline">\(X_{ds}\)</span>: “Prenem un nadó de 2 setmanes i mesuram el seu nivell de triglicèrids en plasmaen ng/dl”, amb mitjana <span class="math inline">\(\mu_{cf}\)</span></li>
</ul>
<p><em>Contrast</em>: Plantejarem el contrast en termes dels nivells mitjans de triglicèrids:
<span class="math display">\[
\left\{\begin{array}{l}
H_{0}:\mu_{cu}=\mu_{ds}\\
H_{1}:\mu_{cu}&lt; \mu_{ds}
\end{array}
\right.
\]</span></p>
<p>Carregam la taula de dades, que prèviament hem guardat en el directori de treball de R, en un dataframe al que anomenam <code>TGN</code> i consultam la seva estructura:</p>
<div class="sourceCode" id="cb211"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb211-1" data-line-number="1">TGN=<span class="kw">read.table</span>(<span class="st">&quot;trignadons.txt&quot;</span>,<span class="dt">header=</span><span class="ot">TRUE</span>)</a>
<a class="sourceLine" id="cb211-2" data-line-number="2"><span class="kw">head</span>(TGN)</a></code></pre></div>
<pre><code>##   Nin CU DS
## 1   1 45 80
## 2   2 30 68
## 3   3 30 83
## 4   4 30 78
## 5   5 31 79
## 6   6 27 78</code></pre>
<div class="sourceCode" id="cb213"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb213-1" data-line-number="1"><span class="kw">str</span>(TGN)</a></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    25 obs. of  3 variables:
##  $ Nin: int  1 2 3 4 5 6 7 8 9 10 ...
##  $ CU : int  45 30 30 30 31 27 27 30 33 32 ...
##  $ DS : int  80 68 83 78 79 78 89 78 72 75 ...</code></pre>
<p>Com que 25 dades són poques, miram si segueixen distribucions normals amb els seus normal-plots:</p>
<div class="sourceCode" id="cb215"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb215-1" data-line-number="1"><span class="kw">qqPlot</span>(TGN<span class="op">$</span>CU, <span class="dt">distribution=</span><span class="st">&quot;norm&quot;</span>, <span class="dt">mean=</span><span class="kw">mean</span>(TGN<span class="op">$</span>CU), <span class="dt">sd=</span><span class="kw">sd</span>(TGN<span class="op">$</span>CU),</a>
<a class="sourceLine" id="cb215-2" data-line-number="2">        <span class="dt">ylab=</span><span class="st">&quot;Quantils de la mostra&quot;</span>, <span class="dt">xlab=</span><span class="st">&quot;Quantils de normal&quot;</span>, </a>
<a class="sourceLine" id="cb215-3" data-line-number="3">       <span class="dt">pch=</span><span class="dv">20</span>, <span class="dt">id=</span><span class="ot">FALSE</span>)</a>
<a class="sourceLine" id="cb215-4" data-line-number="4"><span class="kw">qqPlot</span>(TGN<span class="op">$</span>DS,  <span class="dt">distribution=</span><span class="st">&quot;norm&quot;</span>, <span class="dt">mean=</span><span class="kw">mean</span>(TGN<span class="op">$</span>DS), <span class="dt">sd=</span><span class="kw">sd</span>(TGN<span class="op">$</span>DS),</a>
<a class="sourceLine" id="cb215-5" data-line-number="5">       <span class="dt">ylab=</span><span class="st">&quot;Quantils de la mostra&quot;</span>, <span class="dt">xlab=</span><span class="st">&quot;Quantils de normal&quot;</span>, </a>
<a class="sourceLine" id="cb215-6" data-line-number="6">       <span class="dt">pch=</span><span class="dv">20</span>,<span class="dt">id=</span><span class="ot">FALSE</span>)</a></code></pre></div>
<p><img src="Bioestadistica-II_files/figure-html/unnamed-chunk-287-1.png" width="90%" style="display: block; margin: auto;" /></p>
<p>Vaja, no sembla que segueixin una distribució normal. Vegem els seus histogrames</p>
<div class="sourceCode" id="cb216"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb216-1" data-line-number="1"><span class="kw">hist</span>(TGN<span class="op">$</span>CU, <span class="dt">freq=</span><span class="ot">FALSE</span>, <span class="dt">main=</span><span class="st">&quot;Histograma de TGN$CU&quot;</span>, </a>
<a class="sourceLine" id="cb216-2" data-line-number="2">     <span class="dt">xlab=</span><span class="st">&quot;&quot;</span>,<span class="dt">ylab=</span><span class="st">&quot;&quot;</span>,<span class="dt">col=</span><span class="st">&quot;light blue&quot;</span>)</a>
<a class="sourceLine" id="cb216-3" data-line-number="3"><span class="kw">lines</span>(<span class="kw">density</span>(TGN<span class="op">$</span>CU),<span class="dt">lty=</span><span class="dv">2</span>,<span class="dt">lwd=</span><span class="dv">2</span>)</a>
<a class="sourceLine" id="cb216-4" data-line-number="4"><span class="kw">curve</span>(<span class="kw">dnorm</span>(x,<span class="kw">mean</span>(TGN<span class="op">$</span>CU),<span class="kw">sd</span>(TGN<span class="op">$</span>CU)),<span class="dt">col=</span><span class="st">&quot;red&quot;</span>,<span class="dt">lwd=</span><span class="dv">2</span>,<span class="dt">add=</span><span class="ot">TRUE</span>)</a>
<a class="sourceLine" id="cb216-5" data-line-number="5"><span class="kw">legend</span>(<span class="st">&quot;topright&quot;</span>,<span class="dt">legend=</span><span class="kw">c</span>(<span class="st">&quot;Densitat estimada&quot;</span>,<span class="st">&quot;Normal&quot;</span>),<span class="dt">col=</span><span class="kw">c</span>(<span class="st">&quot;black&quot;</span>,<span class="st">&quot;red&quot;</span>),</a>
<a class="sourceLine" id="cb216-6" data-line-number="6">       <span class="dt">lty=</span><span class="kw">c</span>(<span class="dv">2</span>,<span class="dv">1</span>),<span class="dt">cex=</span><span class="fl">0.5</span>)</a>
<a class="sourceLine" id="cb216-7" data-line-number="7"><span class="co">#</span></a>
<a class="sourceLine" id="cb216-8" data-line-number="8"><span class="kw">hist</span>(TGN<span class="op">$</span>DS, <span class="dt">freq=</span><span class="ot">FALSE</span>, <span class="dt">main=</span><span class="st">&quot;Histograma de TGN$DS&quot;</span>, </a>
<a class="sourceLine" id="cb216-9" data-line-number="9">     <span class="dt">xlab=</span><span class="st">&quot;&quot;</span>,<span class="dt">ylab=</span><span class="st">&quot;&quot;</span>,<span class="dt">col=</span><span class="st">&quot;light blue&quot;</span>)</a>
<a class="sourceLine" id="cb216-10" data-line-number="10"><span class="kw">lines</span>(<span class="kw">density</span>(TGN<span class="op">$</span>DS),<span class="dt">lty=</span><span class="dv">2</span>,<span class="dt">lwd=</span><span class="dv">2</span>)</a>
<a class="sourceLine" id="cb216-11" data-line-number="11"><span class="kw">curve</span>(<span class="kw">dnorm</span>(x,<span class="kw">mean</span>(TGN<span class="op">$</span>DS),<span class="kw">sd</span>(TGN<span class="op">$</span>DS)),<span class="dt">col=</span><span class="st">&quot;red&quot;</span>,<span class="dt">lwd=</span><span class="dv">2</span>,<span class="dt">add=</span><span class="ot">TRUE</span>)</a>
<a class="sourceLine" id="cb216-12" data-line-number="12"><span class="kw">legend</span>(<span class="st">&quot;topright&quot;</span>,<span class="dt">legend=</span><span class="kw">c</span>(<span class="st">&quot;Densitat estimada&quot;</span>,<span class="st">&quot;Normal&quot;</span>),<span class="dt">col=</span><span class="kw">c</span>(<span class="st">&quot;black&quot;</span>,<span class="st">&quot;red&quot;</span>),</a>
<a class="sourceLine" id="cb216-13" data-line-number="13">       <span class="dt">lty=</span><span class="kw">c</span>(<span class="dv">2</span>,<span class="dv">1</span>),<span class="dt">cex=</span><span class="fl">0.5</span>)</a></code></pre></div>
<p><img src="Bioestadistica-II_files/figure-html/unnamed-chunk-289-1.png" width="90%" style="display: block; margin: auto;" /></p>
<p>Les dues mostres presenten una cua a la dreta, com podem veure als diagrames de caixa:</p>
<pre r.fig.width="5,out.width=&quot;60%&quot;"><code>par(mfrow=c(1,1))
boxplot(TGN$CU,TGN$DS,names=c(&quot;CU&quot;,&quot;DS&quot;),xlab=&quot;&quot;,ylab=&quot;Nivell triglicèrids&quot;)</code></pre>
<p>En casos així, <strong>de vegades els logaritmes seguexen aproximadament una distribució normal</strong>. Vegem si hi ha sort.</p>
<div class="sourceCode" id="cb218"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb218-1" data-line-number="1">LogCU=<span class="kw">log</span>(TGN<span class="op">$</span>CU)</a>
<a class="sourceLine" id="cb218-2" data-line-number="2"><span class="kw">qqPlot</span>(LogCU, <span class="dt">distribution=</span><span class="st">&quot;norm&quot;</span>, <span class="dt">mean=</span><span class="kw">mean</span>(LogCU), <span class="dt">sd=</span><span class="kw">sd</span>(LogCU),</a>
<a class="sourceLine" id="cb218-3" data-line-number="3">        <span class="dt">ylab=</span><span class="st">&quot;Quantils dels logaritmes&quot;</span>, <span class="dt">xlab=</span><span class="st">&quot;Quantils de normal&quot;</span>, </a>
<a class="sourceLine" id="cb218-4" data-line-number="4">       <span class="dt">pch=</span><span class="dv">20</span>, <span class="dt">id=</span><span class="ot">FALSE</span>)</a>
<a class="sourceLine" id="cb218-5" data-line-number="5"><span class="co">#</span></a>
<a class="sourceLine" id="cb218-6" data-line-number="6">LogDS=<span class="kw">log</span>(TGN<span class="op">$</span>DS)</a>
<a class="sourceLine" id="cb218-7" data-line-number="7"><span class="kw">qqPlot</span>(LogDS, <span class="dt">distribution=</span><span class="st">&quot;norm&quot;</span>, <span class="dt">mean=</span><span class="kw">mean</span>(LogDS), <span class="dt">sd=</span><span class="kw">sd</span>(LogCU),</a>
<a class="sourceLine" id="cb218-8" data-line-number="8">        <span class="dt">ylab=</span><span class="st">&quot;Quantils dels logaritmes&quot;</span>, <span class="dt">xlab=</span><span class="st">&quot;Quantils de normal&quot;</span>, </a>
<a class="sourceLine" id="cb218-9" data-line-number="9">       <span class="dt">pch=</span><span class="dv">20</span>, <span class="dt">id=</span><span class="ot">FALSE</span>)</a></code></pre></div>
<p><img src="Bioestadistica-II_files/figure-html/unnamed-chunk-291-1.png" width="90%" style="display: block; margin: auto;" /></p>
<p>Aquests logaritmes ja poden passar per normals. Per tant, el que farem serà, en lloc de comparar les mitjanes dels nivells de triglicèrids, comparar les mitjanes dels seus logaritmes.</p>

<div class="rmdrecordau">
Aquest tipus de transformació és molt usual en Bioestadística.
</div>


<div class="rmdcaution">
<p>No són contrastos equivalents, perquè el logaritme de la mitjana no és la mitjana del logaritme. Però en realitat la pregunta que originava aquesta investigació era si el <strong>nivell de triglicèrids augmenta</strong> en les dues primeres setmanes de vida dels nadons, i ho plantejàvem en termes de si és veritat que <strong>el nivell mitjà de triglicèrids augmenta</strong> en les dues primeres setmanes de vida dels nadons.</p>
Ara, demanar-nos si “el nivell de triglicèrids augmenta en les dues primeres setmanes de vida dels nadons” sí que és equivalent a demanar-nos si “el logaritme del nivell de triglicèrids augmenta en les dues primeres setmanes de vida dels nadons”. I el que fem és plantejar aquesta pregunta en termes de si és veritat que <strong>el valor mitjà del logaritme del nivell de triglicèrids augmenta</strong> en les dues primeres setmanes de vida dels nadons
</div>

<p><em>Noves variables aleatòries d’interès</em>:</p>
<ul>
<li><span class="math inline">\(\log(X_{cu})\)</span>: “Prenem un recent nat i calculam el logaritme del nivell de triglicèrids en plasma a la sang del seu cordó umbilical”, amb mitjana <span class="math inline">\(\mu_{logcu}\)</span></li>
<li><span class="math inline">\(\log(X_{ds})\)</span>: “Prenem un nadó de 2 setmanes i calculam el logaritme del seu nivell de triglicèrids en plasma”, amb mitjana <span class="math inline">\(\mu_{logds}\)</span></li>
</ul>
<p><em>Nou contrast</em>:
<span class="math display">\[
\left\{\begin{array}{l}
H_{0}:\mu_{logcu}=\mu_{logds}\\
H_{1}:\mu_{logcu}&lt; \mu_{logds}
\end{array}
\right.
\]</span></p>
<p>Prenem com a mostres de <span class="math inline">\(\log(X_{cu})\)</span> i <span class="math inline">\(\log(X_{ds})\)</span> els vectors de logaritmes <code>LogCU</code> i <code>LogDS</code> de la nostra mostra original, que podem acceptar que provenen de distribucions normals, i els aplicam la funció <code>t.test</code> amb <code>paired=TRUE</code>, perquè són mostres aparellades, i <code>alternative=&quot;less&quot;</code>.</p>
<div class="sourceCode" id="cb219"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb219-1" data-line-number="1"><span class="kw">t.test</span>(LogCU, LogDS, <span class="dt">paired=</span><span class="ot">TRUE</span>, <span class="dt">alternative=</span><span class="st">&quot;less&quot;</span>)</a></code></pre></div>
<pre><code>## 
##  Paired t-test
## 
## data:  LogCU and LogDS
## t = -26.112, df = 24, p-value &lt; 2.2e-16
## alternative hypothesis: true difference in means is less than 0
## 95 percent confidence interval:
##        -Inf -0.8353074
## sample estimates:
## mean of the differences 
##              -0.8938758</code></pre>
<p><em>Conclusió</em>: Hem obtingut evidència estadísticament significativa que el valor mitjà del logaritme del nivell de triglicèrids a la sang del cordó umbilical d’un nadó és més petit que el valor mitjà del logaritme del nivell de triglicèrids a la sang d’un nadó de 2 setmanes (test t, p-valor&lt;10<sup>-16</sup>, IC 95% per a la diferència de les mitjanes dels logaritmes de <span class="math inline">\(-\infty\)</span> a -0.84). Concloem, per tant, que tenim evidència estadísticament significativa que el nivell de triglicèrids als nadons de 2 setmanes és més alt que el del seu cordó umbilical.</p>
</div>
<div id="tests-no-paramètrics" class="section level3">
<h3><span class="header-section-number">5.1.5</span> Tests no paramètrics</h3>
<p>Si les variables aleatòries d’interès no són (aproximadament) normals i alguna mostra és petita, no podem usar un test t per comparar mitjanes. En aquest cas, una possibilitat és provar de transformar les dades com a l’Exemple <a href="contrastos-dhipòtesis-dun-i-dos-paràmetres.html#exm:sangumbil">5.5</a> per veure si la transformació esdevé normal, i si és el cas, plantejar el contrast en termes de mitjanes de les dades transformades</p>
<p>Una altra possibilitat és emprar un <strong>test no paramètric</strong>, que no necessiti que les variables aleatòries siguin normals per que la conclusió sigui vàlida.</p>
<p>La majoria de tests no paramètrics per comparar mitjanes en realitat comparen <strong>medianes</strong>, però normalment cometem l’abús de llenguatge de dir que són per contrastar mitjanes. A més, si les variables aleatòries són simètriques, les mitjanes coincideixen amb les medianes.</p>
<p>Els més populars són:</p>
<ul>
<li><p><strong>Test de Wilcoxon</strong> per a una mitjana o dues mitjanes usant mostres aparellades</p></li>
<li><p><strong>Test de Mann-Whitney</strong> per a dues mitjanes usant mostres independents</p></li>
</ul>
<p>Tots tres es calculen amb R amb la funció</p>
<div class="sourceCode" id="cb221"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb221-1" data-line-number="1"><span class="kw">wilcox.test</span>(x, y, <span class="dt">mu=</span>..., <span class="dt">alternative=</span>..., <span class="dt">paired=</span>...,</a>
<a class="sourceLine" id="cb221-2" data-line-number="2">            <span class="dt">conf.level=</span>...)</a></code></pre></div>
<p>amb sintaxi idèntica a la de <code>t.test</code> (excepte que no s’hi empra el <code>var.equal</code>).</p>

<div class="rmdimportant">
<p>Els millors tests no paramètrics solen tenir potència inferior als millors tests paramètrics. A més, els tests no paramètrics no solen produir intervals de confiança fiables. Però, per exemple, emprar un test t quan no és adequat pot portar a conclusions equivocades.</p>
<strong>Emprau tests paramètrics sempre que pogueu, però només quan pogueu.</strong>
</div>

<p>Com a exemple, vegem com funciona (una versió simplificada) del test de Wilcoxon d’una mitjana. Sigui <span class="math inline">\(X\)</span> una variable aleatòria contínua simètrica al voltant de la seva mitjana <span class="math inline">\(\mu\)</span> desconeguda. Volem realitzar un contrast
<span class="math display">\[
\left\{\begin{array}{l}
H_{0}:\mu=\mu_0\\ 
H_{1}:\mu \neq \mu_0 \text{ o }\mu &gt;\mu_0\text{ o }\mu&lt;\mu_0
\end{array}
\right.
\]</span></p>
<p>Prenem una mostra aleatòria simple <span class="math inline">\(x_1,\ldots, x_n\)</span> de <span class="math inline">\(X\)</span>. El procediment d’aquest test es basa aleshores en els següents passos, que després il·lustram a l’Exemple <a href="contrastos-dhipòtesis-dun-i-dos-paràmetres.html#exm:dietaratolins">5.6</a>:</p>
<ol style="list-style-type: decimal">
<li><p>Per a cada <span class="math inline">\(i=1,\ldots,n\)</span>, sigui <span class="math inline">\(d_i=x_i-\mu_0\)</span>; s’eliminen els valors 0</p></li>
<li><p>Enumeram els valors <span class="math inline">\(d_i\)</span> de menor a major valor absolut; en cas d’empats, a cada un dels valors empatats li assignam la mitjana de les posicions que ocuparien. A l’índex assignat d’aquesta manera a cada <span class="math inline">\(d_i\)</span> li diem el seu <strong>rang</strong>. Per exemple, a l’Exemple <a href="contrastos-dhipòtesis-dun-i-dos-paràmetres.html#exm:dietaratolins">5.6</a> hi ha quatre <span class="math inline">\(i\)</span> amb valors <span class="math inline">\(d_i=\pm 1\)</span>, i els tocarien les posicions 1, 2, 3 i 4: aleshores el rang de cada un d’aquests quatre <span class="math inline">\(d_i\)</span> és 2.5.</p></li>
<li><p>Diem <span class="math inline">\(T_+\)</span> a la suma dels rangs dels <span class="math inline">\(d_i&gt;0\)</span> i <span class="math inline">\(T_{-}\)</span> a la suma dels rangs dels <span class="math inline">\(d_i&lt;0\)</span></p></li>
<li><p>Si <span class="math inline">\(H_0\)</span> vertadera, és a dir, si <span class="math inline">\(\mu=\mu_0\)</span>, per la simetria de <span class="math inline">\(X\)</span> al voltant de <span class="math inline">\(\mu\)</span> esperam que <span class="math inline">\(T_+\approx T_-\)</span>. Per tant:</p>
<ul>
<li><p>Si <span class="math inline">\(T_+\)</span> és molt petit, és evidència que <span class="math inline">\(\mu &lt;\mu_0\)</span></p>
<p>En efecte, si <span class="math inline">\(T_+\)</span> és molt més petit que <span class="math inline">\(T_-\)</span>, bàsicament significa que hi ha més valors a l’esquerra de <span class="math inline">\(\mu_0\)</span> que a la dreta, i per tant la mediana poblacional (que és el valor que deixa la meitat de la població a l’esquerra i l’altra meitat a la dreta) ha d’estar a l’esquerra de <span class="math inline">\(\mu_0\)</span>.</p></li>
<li><p>Si <span class="math inline">\(T_+\)</span> és molt gran, és evidència que <span class="math inline">\(\mu &gt;\mu_0\)</span></p>
<p>En efecte, si <span class="math inline">\(T_+\)</span> és molt més gran que <span class="math inline">\(T_-\)</span>, bàsicament significa que hi ha més valors a la dreta de <span class="math inline">\(\mu_0\)</span> que a l’esquerra, i per tant la mediana ha d’estar a la dreta de <span class="math inline">\(\mu_0\)</span>.</p></li>
<li><p>Si <span class="math inline">\(T_+\)</span> és molt petit o gran, és evidència que <span class="math inline">\(\mu\neq \mu_0\)</span></p></li>
</ul>
<p>I resulta que, quan <span class="math inline">\(X\)</span> és simètrica i <span class="math inline">\(H_0\)</span> vertadera, la distribució de <span class="math inline">\(T_+\)</span>, per a cada <span class="math inline">\(n\)</span>, és coneguda, i es pot emprar per calcular el p-valor, que és el que fa la funció <code>wilcox.test</code>.</p></li>
</ol>

<div class="example">
<p><span id="exm:dietaratolins" class="example"><strong>Exemple 5.6  </strong></span>Alimentàrem amb una dieta especial 13 ratolins des del naixement fins a la setmana 12. Els augments de pes (en grams) varen ser els del vector següent</p>
</div>

<div class="sourceCode" id="cb222"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb222-1" data-line-number="1">pesos=<span class="kw">c</span>(<span class="dv">69</span>,<span class="dv">61</span>,<span class="dv">69</span>,<span class="dv">65</span>,<span class="dv">70</span>,<span class="dv">68</span>,<span class="dv">69</span>,<span class="dv">68</span>,<span class="dv">72</span>,<span class="dv">67</span>,<span class="dv">74</span>,<span class="dv">69</span>,<span class="dv">76</span>)</a></code></pre></div>
<p>Podem conclure que l’augment mitjà de pes en aquestes condicions és de menys de 70 g?</p>
<p><em>Variable aleatòria d’interès</em>: <span class="math inline">\(X\)</span>: “Prenem un ratolí alimentat amb aquesta dieta especial i mesuram el seu augment de pes en grams durant les seves primeres 12 setmanes de vida”, amb mitjana <span class="math inline">\(\mu\)</span>.</p>
<p><em>Contrast</em>:
<span class="math display">\[
\left\{\begin{array}{l}
H_{0}:\mu=70\\ 
H_{1}:\mu &lt;70
\end{array}
\right.
\]</span></p>
<p>Si miram la mostra, veurem que no té pinta de venir d’una distribució normal però sí simètrica:</p>
<div class="sourceCode" id="cb223"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb223-1" data-line-number="1"><span class="kw">qqPlot</span>(pesos, <span class="dt">distribution=</span><span class="st">&quot;norm&quot;</span>, <span class="dt">mean=</span><span class="kw">mean</span>(pesos), <span class="dt">sd=</span><span class="kw">sd</span>(pesos),</a>
<a class="sourceLine" id="cb223-2" data-line-number="2">        <span class="dt">ylab=</span><span class="st">&quot;Quantils de la mostra&quot;</span>, <span class="dt">xlab=</span><span class="st">&quot;Quantils de normal&quot;</span>, <span class="dt">pch=</span><span class="dv">20</span>, <span class="dt">id=</span><span class="ot">FALSE</span>)</a>
<a class="sourceLine" id="cb223-3" data-line-number="3"><span class="kw">boxplot</span>(pesos)</a></code></pre></div>
<p><img src="Bioestadistica-II_files/figure-html/unnamed-chunk-299-1.png" width="90%" style="display: block; margin: auto;" /></p>
<p>Per tant, emprarem un test de Wilcoxon. Vegem com aniria a mà.</p>
<ol style="list-style-type: decimal">
<li>Calculam els <span class="math inline">\(d_i=x_i-70\)</span></li>
</ol>
<p><span class="math display">\[
\begin{array}{l|cccccccccccccc}
\hline
x_i &amp;     69 &amp;  61 &amp;  69 &amp;  65 &amp;  70 &amp;  68 &amp;  69 &amp;  68 &amp;  72 &amp;  67 &amp;  74 &amp;  69 &amp;  76\\
d_i     &amp; -1 &amp; -9 &amp; -1  &amp;   -5  &amp;  0 &amp;  -2 &amp;  -1 &amp;  -2 &amp;  2 &amp;   -3  &amp;  4  &amp;   -1 &amp;    6\\
\hline
\end{array}
\]</span></p>
<ol start="2" style="list-style-type: decimal">
<li>Assignam índexos als <span class="math inline">\(d_i\neq 0\)</span> en ordre creixent al seu valor absolut. En cas d’empat, per ara els assignam els índexos ordenats d’esquerra a dreta.</li>
</ol>
<p><span class="math display">\[
\begin{array}{l|cccccccccccccc}
\hline
x_i &amp;                       69 &amp;  61 &amp;  69 &amp;  65 &amp;  70 &amp;  68 &amp;  69 &amp;  68 &amp;  72 &amp;  67 &amp;  74 &amp;  69 &amp;  76\\
d_i                        &amp; -1 &amp; -9 &amp; -1  &amp;   -5  &amp;  0 &amp;  -2 &amp;  -1 &amp;  -2 &amp;  2 &amp;   -3  &amp;  4 &amp; -1 &amp;    6\\
\textrm{Rang fals}        &amp;   1 &amp; 12 &amp;   2 &amp;  10  &amp;    &amp;   5 &amp;   3 &amp;   6  &amp;  7 &amp;   8    &amp;  9 &amp; 4 &amp;   11    \\
\hline
\end{array}
\]</span></p>
<ol start="3" style="list-style-type: decimal">
<li>A continuació, assignam com a <strong>rang</strong> de cada <span class="math inline">\(d_i\)</span> la mitjana de tots els “rangs falsos” dels <span class="math inline">\(d_i\)</span> amb el seu mateix valor absolut. Així, el rang de tots els <span class="math inline">\(d_i=-1\)</span> és <span class="math inline">\((1+2+3+4)/4=2.5\)</span> i el rang dels <span class="math inline">\(d_i=-2\)</span> o 2 és <span class="math inline">\((5+6+7)/3=6\)</span>.</li>
</ol>
<p><span class="math display">\[
\begin{array}{l|cccccccccccccc}
\hline
x_i &amp;                       69 &amp;  61 &amp;  69 &amp;  65 &amp;  70 &amp;  68 &amp;  69 &amp;  68 &amp;  72 &amp;  67 &amp;  74 &amp;  69 &amp;  76\\
d_i                        &amp; -1 &amp; -9 &amp; -1  &amp;   -5  &amp;  0 &amp;  -2 &amp;  -1 &amp;  -2 &amp;  2 &amp;   -3  &amp;  4 &amp; -1 &amp;    6\\
\textrm{Rang fals}        &amp;   1 &amp; 12 &amp;   2 &amp;  10  &amp;     &amp;   5 &amp;   3 &amp;   6  &amp;  7 &amp;   8 &amp;  9 &amp; 4  &amp;   11    \\
\textrm{Rang}             &amp; 2.5 &amp; 12 &amp; 2.5 &amp; 10 &amp;       &amp; 6   &amp; 2.5  &amp; 6   &amp;  6 &amp;  8  &amp;  9 &amp;  2.5 &amp; 11 \\
\hline
\end{array}
\]</span></p>
<ol start="4" style="list-style-type: decimal">
<li>Anotam quins <span class="math inline">\(d_i\)</span> són positius i quins negatius:</li>
</ol>
<p><span class="math display">\[
\begin{array}{l|cccccccccccccc}
\hline
x_i &amp;                       69 &amp;  61 &amp;  69 &amp;  65 &amp;  70 &amp;  68 &amp;  69 &amp;  68 &amp;  72 &amp;  67 &amp;  74 &amp;  69 &amp;  76\\
d_i                        &amp; -1 &amp; -9 &amp; -1  &amp;   -5  &amp;  0 &amp;  -2 &amp;  -1 &amp;  -2 &amp;  2 &amp;   -3  &amp;  4 &amp; -1 &amp;    6\\
\textrm{Rang fals}        &amp;   1 &amp; 12 &amp;   2 &amp;  10  &amp;     &amp;   5 &amp;   3 &amp;   6  &amp;  7 &amp;   8 &amp;  9 &amp; 4  &amp;   11    \\
\textrm{Rang}             &amp; 2.5 &amp; 12 &amp; 2.5 &amp; 10 &amp;       &amp; 6   &amp; 2.5  &amp; 6   &amp;  6 &amp;  8 &amp;  9 &amp;  2.5 &amp; 11 \\
\textrm{Signe} &amp;            -   &amp; - &amp;  -  &amp;  -   &amp;      &amp; - &amp;   - &amp;  -     &amp; +  &amp;  -  &amp; +   &amp; -   &amp; +\\  
\hline
\end{array}
\]</span></p>
<ol start="5" style="list-style-type: decimal">
<li><p>Sumam, d’una banda, els rangs dels <span class="math inline">\(d_i\)</span> positius i de l’altra, els dels negatius:
<span class="math display">\[
\begin{array}{l}
T_+=6+9+11=26\\
T_-=2.5+ 12 + 2.5 + 10 + 6   + 2.5  + 6   +  8 +  2.5=52
\end{array}
\]</span></p></li>
<li><p>I ara miraríem si <span class="math inline">\(T_+\)</span> és prou més petit que <span class="math inline">\(T_-\)</span> per que sigui evidència estadísticament significativa de que <span class="math inline">\(\mu &lt;\mu_0\)</span>. Això ja no ho podem fer a mà.</p></li>
</ol>
<p>Amb R, simplement entraríem</p>
<div class="sourceCode" id="cb224"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb224-1" data-line-number="1"><span class="kw">wilcox.test</span>(pesos,<span class="dt">mu=</span><span class="dv">70</span>,<span class="dt">alternative=</span><span class="st">&quot;less&quot;</span>)</a></code></pre></div>
<pre><code>## 
##  Wilcoxon signed rank test with continuity correction
## 
## data:  pesos
## V = 26, p-value = 0.1621
## alternative hypothesis: true location is less than 70</code></pre>
<p><em>Conclusió</em>: No hem obtingut evidència estadísticament significativa que l’augment mitjà de pes en aquestes condicions sigui més petit que 70 g (test de Wilcoxon, p-valor 0.16).</p>
<p>El test de Wilcoxon per a dues mitjanes emprant mostres aparellades és bàsicament el test anterior aplicat a la diferència dels valors de les dues variables a les parelles.</p>

<div class="example">
<p><span id="exm:unnamed-chunk-301" class="example"><strong>Exemple 5.7  </strong></span>Una alternativa a la transformació logarítmica portada a terme a l’Exemple <a href="contrastos-dhipòtesis-dun-i-dos-paràmetres.html#exm:sangumbil">5.5</a> hagués estat emprar el test de Wilcoxon per a mostres aparellades.</p>
</div>

<p>El contrast ara seria
<span class="math display">\[
\left\{\begin{array}{l}
H_{0}:\mu_{cu}-\mu_{ds}=0\\
H_{1}:\mu_{cu}- \mu_{ds}&lt;0
\end{array}
\right.
\]</span>
que clarament correspon al contrast original
<span class="math display">\[
\left\{\begin{array}{l}
H_{0}:\mu_{cu}=\mu_{ds}\\
H_{1}:\mu_{cu}&lt; \mu_{ds}
\end{array}
\right.
\]</span>
però hem de tenir present que la hipòtesi nul·la en realitat significa que la <strong>mediana</strong> de les diferències dels nivells de triglicèrids en el cordó umbilical menys els nivells de triglicèrids al cap de dues setmanes és 0, és a dir</p>
<blockquote>
<p>Si restam del nivell de triglicèrids en la sang del cordó umbilical d’un nadó el seu nivell de triglicèrids en sang al cap de dues setmanes, la meitat de les vegades obtenim un valor <span class="math inline">\(\geqslant 0\)</span> i l’altra meitat de les vegades un valor <span class="math inline">\(\leqslant 0\)</span>,</p>
</blockquote>
<p>o, equivalentment,</p>
<blockquote>
<p>La meitat dels nadons tenen el nivell de triglicèrids en la sang del cordó umbilical més alt o igual que el seu nivell de triglicèrids en sang al cap de dues setmanes, i l’altra meitat tenen el nivell de triglicèrids en la sang del cordó umbilical més petit o igual que el seu nivell de triglicèrids en sang al cap de dues setmanes.</p>
</blockquote>
<p>La hipòtesi alternativa que aquesta mediana és negativa. És a dir, la hipòtesi alternativa és</p>
<blockquote>
<p>Si restam el nivell de triglicèrids en la sang del cordó umbilical d’un nadó menys el nivell de triglicèrids en sang al cap de dues setmanes, més de la meitat de les vegades obtendríem un valor <span class="math inline">\(&lt;0\)</span></p>
</blockquote>
<p>o, equivalentment,</p>
<blockquote>
<p>Més de la meitat dels nadons tenen el nivell de triglicèrids en la sang del cordó umbilical més petit que el seu nivell de triglicèrids en sang al cap de dues setmanes.</p>
</blockquote>
<div class="sourceCode" id="cb226"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb226-1" data-line-number="1"><span class="kw">wilcox.test</span>(TGN<span class="op">$</span>CU,TGN<span class="op">$</span>DS,<span class="dt">alternative=</span><span class="st">&quot;less&quot;</span>,<span class="dt">paired=</span><span class="ot">TRUE</span>)</a></code></pre></div>
<pre><code>## 
##  Wilcoxon signed rank test with continuity correction
## 
## data:  TGN$CU and TGN$DS
## V = 0, p-value = 6.384e-06
## alternative hypothesis: true location shift is less than 0</code></pre>
<p>Com que el p-valor és de l’ordre de 10<sup>-6</sup>, rebutjam la hipòtesi nul·la en favor de la alternativa; abusarem del llenguatge i ho expressarem en termes de mitjanes:</p>
<p><em>Conclusió</em>: Hem obtingut evidència estadísticament significativa que el nivell mitjà de triglicèrids a la sang del cordó umbilical dels nadons és més petit que al cap de dues setmanes (test de Wilcoxon, p-valor 6.4·10<sup>-6</sup>).</p>
</div>
</div>
<div id="sec:contrvar" class="section level2">
<h2><span class="header-section-number">5.2</span> Contrastos de variàncies</h2>
<div id="test-chi2-duna-variància" class="section level3">
<h3><span class="header-section-number">5.2.1</span> Test <span class="math inline">\(\chi^2\)</span> d’una variància</h3>
<p>Siguin <span class="math inline">\(X\)</span> una variable aleatòria <span class="math inline">\(N(\mu,\sigma)\)</span> i <span class="math inline">\(X_1,\ldots,X_n\)</span> una mostra aleatòria simple de <span class="math inline">\(X\)</span> de mida <span class="math inline">\(n\)</span> qualsevol.</p>
<p>Volem realitzar un contrast
<span class="math display">\[
\left\{\begin{array}{l}
H_{0}:\sigma=\sigma_0\\ 
H_{1}:\sigma \neq\sigma_0\text{ o }\sigma &gt;\sigma_0\text{ o }\sigma&lt;\sigma_0
\end{array}
\right.
\]</span>
o equivalentment
<span class="math display">\[
\left\{\begin{array}{l}
H_{0}:\sigma^2=\sigma_0^2\\ 
H_{1}:\sigma^2 \neq\sigma_0^2\text{ o }\sigma^2 &gt;\sigma_0^2\text{ o }\sigma^2&lt;\sigma_0^2
\end{array}
\right.
\]</span></p>
<p>Si <span class="math inline">\(H_0\)</span> és vertadera, sabem que l’<em>estadístic de contrast</em>
<span class="math display">\[
\chi^2=\frac{(n-1) \widetilde{S}_X^2}{\sigma_{0}^2}
\]</span></p>
<p>té distribució <span class="math inline">\(\chi_{n-1}^2\)</span>, i aleshores ho podem emprar per calcular p-valors, regions crítiques etc. En concret, si
el valor d’aquest estadístic de contrast sobre la mostra és <span class="math inline">\(\chi_0^2\)</span>, aleshores:</p>
<ul>
<li><p>Si <span class="math inline">\(H_{1}:\sigma&gt;\sigma_{0}\)</span>, el p-valor és <span class="math inline">\(P(\chi^2\geqslant\chi_0^2)\)</span></p></li>
<li><p>Si <span class="math inline">\(H_{1}:\sigma&lt;\sigma_{0}\)</span>, el p-valor és <span class="math inline">\(P(\chi^2\leqslant\chi^2_0)\)</span></p></li>
<li><p>Si <span class="math inline">\(H_{1}:\sigma\neq \sigma_{0}\)</span>, el p-valor es pren, <strong>per conveni</strong>, igual a <span class="math inline">\(2\text{min}\big\{P(\chi^2\geqslant\chi^2_0), P(\chi^2\leqslant\chi^2_0)\big\}\)</span></p></li>
</ul>

<div class="rmdcaution">
Alerta amb els p-valors dels contrastos bilaterals que no siguin ni tests t ni binomials, ja que per motius històrics no es calculen com “la probabilitat d’obtenir un valor de l’estadístic de contrast tant o més extrem que l’obtingut”, sinó per mitjà d’una fórmula de l’estil de la que hem donat aquí dalt.
</div>


<div class="example">
<p><span id="exm:unnamed-chunk-304" class="example"><strong>Exemple 5.8  </strong></span>Suposem que tenim una mostra aleatòria simple d’una variable <span class="math inline">\(X\)</span> normal de mida 25, i ha donat
<span class="math inline">\(\widetilde{S}_X^2=1.25\)</span>. Volem realitzar alguns contrastos amb hipòtesi nul·la <span class="math inline">\(\sigma_X^2=0.8\)</span>, i per tant tendrem
<span class="math display">\[
\chi_0^2=\frac{(25-1)\cdot 1.25}{0.8}=37.5
\]</span></p>
</div>

<ul>
<li><p>Si volem realitzar el contrast
<span class="math display">\[
\left\{\begin{array}{l}
H_{0}:\sigma_X^2=0.8 \\
H_{1}:\sigma_X^2&gt; 0.8
\end{array}
\right.
\]</span>
el p-valor és
<span class="math display">\[
P(\chi^2_{24} \geqslant 37.5)=\texttt{1-pchisq(37.5,24)}=0.039
\]</span>
Amb nivell de confiança <span class="math inline">\(\alpha=0.05\)</span> rebutjam <span class="math inline">\(H_0\)</span> en favor de <span class="math inline">\(H_1\)</span></p></li>
<li><p>Si volem realitzar el contrast
<span class="math display">\[
\left\{\begin{array}{l}
H_{0}:\sigma_X^2=0.8 \\
H_{1}:\sigma_X^2\neq  0.8
\end{array}
\right.
\]</span>
El p-valor és
<span class="math display">\[
\begin{array}{l}
2\min\big\{P(\chi^2_{24}\geqslant 37.5),P(\chi^2_{24}\leqslant 37.5)\big\}\\
\qquad=2\min\{\texttt{1-pchisq(37.5,24)},\texttt{pchisq(37.5,24)}\}\\
\qquad=2\min\{0.039,0.961\}=
0.078
\end{array}
\]</span>
Amb nivell de confiança <span class="math inline">\(\alpha=0.05\)</span>, no podem rebutjar <span class="math inline">\(H_0\)</span>.</p></li>
</ul>
<p>En resum: amb la nostra mostra trobam evidència estadísticament significativa que <span class="math inline">\(\sigma&gt;\sigma_0\)</span>, però no trobam evidència estadísticament significativa que <span class="math inline">\(\sigma\neq \sigma_0\)</span>. No us ha de venir de nou, ja ens hi hem trobat en altres ocasions (recordau els Exemples <a href="contrastos-dhipòtesis-generalitats.html#exm:ttestmu20">4.13</a> i <a href="contrastos-dhipòtesis-generalitats.html#exm:ttest1bis">4.16</a>): per rebutjar la hipòtesi nul·la en un contrast bilateral cal més evidència que en un contrast unilateral, perquè al contrast bilateral tenim dues fonts d’error de tipus I i al contrast unilateral només una.</p>

<div class="example">
<p><span id="exm:unnamed-chunk-305" class="example"><strong>Exemple 5.9  </strong></span>S’ha analitzat el líquid amniòtic d’una mostra aleatòria de 15 embarassades de 3er trimestre, i s’han obtingut les mesures següents de proteïnes totals (en grams per 100 ml):</p>
</div>

<div class="sourceCode" id="cb228"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb228-1" data-line-number="1">amnio=<span class="kw">c</span>(<span class="fl">0.69</span>,<span class="fl">1.04</span>,<span class="fl">0.39</span>,<span class="fl">0.37</span>,<span class="fl">0.64</span>,<span class="fl">0.73</span>,<span class="fl">0.69</span>,<span class="fl">1.04</span>,<span class="fl">0.83</span>,<span class="fl">1.01</span>,</a>
<a class="sourceLine" id="cb228-2" data-line-number="2">        <span class="fl">0.19</span>,<span class="fl">0.61</span>,<span class="fl">0.42</span>,<span class="fl">0.25</span>,<span class="fl">0.79</span>)</a></code></pre></div>
<p>Podem concloure a partir d’aquestes dades, amb un nivell de significació del 5%, que la desviació típica poblacional (és a dir, la desviació típica de la quantitat de proteïna total en el líquid amniòtic de les embarassades de 3er trimestre expressada en grams per 100 ml) és diferent de 0.25?</p>
<p><em>Variable aleatòria d’interès</em>: <span class="math inline">\(X\)</span>: “Prenem una embarassada i li mesuram la quantitat de proteïna total en …”, amb desviació típica <span class="math inline">\(\sigma\)</span>.</p>
<p><em>Contrast</em>:
<span class="math display">\[
\left\{\begin{array}{l}
H_{0}:\sigma=0.25 \\
H_{1}:\sigma\neq 0.25
\end{array}
\right.
\]</span>
amb <span class="math inline">\(\alpha=0.05\)</span></p>
<p>Per poder aplicar el test <span class="math inline">\(\chi^2\)</span>, cal que <span class="math inline">\(X\)</span> sigui normal. Vegem el normal-plot:</p>
<div class="sourceCode" id="cb229"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb229-1" data-line-number="1"><span class="kw">qqPlot</span>(amnio, <span class="dt">distribution=</span><span class="st">&quot;norm&quot;</span>, <span class="dt">mean=</span><span class="kw">mean</span>(amnio), <span class="dt">sd=</span><span class="kw">sd</span>(amnio),</a>
<a class="sourceLine" id="cb229-2" data-line-number="2">        <span class="dt">ylab=</span><span class="st">&quot;Quantils de la mostra&quot;</span>, <span class="dt">xlab=</span><span class="st">&quot;Quantils de normal&quot;</span>, </a>
<a class="sourceLine" id="cb229-3" data-line-number="3">       <span class="dt">pch=</span><span class="dv">20</span>, <span class="dt">id=</span><span class="ot">FALSE</span>)</a></code></pre></div>
<p><img src="Bioestadistica-II_files/figure-html/unnamed-chunk-308-1.png" width="50%" style="display: block; margin: auto;" /></p>
<p>Acceptarem que <span class="math inline">\(X\)</span> és normal.</p>
<p><em>Estadístic de contrast</em>:
<span class="math display">\[
\chi^2=\frac{(n-1) \widetilde{S}_X^2}{\sigma_{0}^2}
\]</span>
que segueix una llei <span class="math inline">\(\chi^2_{n-1}\)</span> si <span class="math inline">\(H_0\)</span> és certa.</p>
<p><em>Valor de l’estadístic de contrast</em>, <span class="math inline">\(\chi^2_0\)</span>:</p>
<div class="sourceCode" id="cb230"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb230-1" data-line-number="1">n=<span class="kw">length</span>(amnio)</a>
<a class="sourceLine" id="cb230-2" data-line-number="2">n</a></code></pre></div>
<pre><code>## [1] 15</code></pre>
<div class="sourceCode" id="cb232"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb232-1" data-line-number="1"><span class="kw">var</span>(amnio)</a></code></pre></div>
<pre><code>## [1] 0.07624</code></pre>
<div class="sourceCode" id="cb234"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb234-1" data-line-number="1">khi0=(n<span class="dv">-1</span>)<span class="op">*</span><span class="kw">var</span>(amnio)<span class="op">/</span><span class="fl">0.25</span><span class="op">^</span><span class="dv">2</span></a>
<a class="sourceLine" id="cb234-2" data-line-number="2"><span class="kw">round</span>(khi0,<span class="dv">2</span>)</a></code></pre></div>
<pre><code>## [1] 17.08</code></pre>
<p><em>p-valor</em>:
<span class="math display">\[
\begin{array}{l}
2\min\big\{P(\chi_{n-1}^2\geqslant\chi^2_0), P(\chi_{n-1}^2\leqslant\chi^2_0)\big\}\\
\qquad=2\min\{\texttt{1-pchisq(17.08,14)},\texttt{pchisq(17.08,14)}\}\\
\qquad=2\min\{0.252,0.748\}=
0.504
\end{array}
\]</span></p>
<p>En aquest exemple, com que el contrast és bilateral, l’IC 95% seria el del tema anterior (amb <span class="math inline">\(q=1-\alpha=0.95\)</span>).</p>
<p>El de la variància seria
<span class="math display">\[
\left[ \frac{(n-1)\widetilde{S}_{X}^2}{\chi_{n-1,0.975}^2},
\frac{(n-1)\widetilde{S}_{X}^2}{\chi_{n-1,0.025}^2}
\right]
\]</span>
on <span class="math inline">\(\chi_{n-1,0.975}^2\)</span>=<code>qchisq(0.975,14)</code>=26.11895 i <span class="math inline">\(\chi_{n-1,0.025}^2\)</span>=<code>qchisq(0.025,14)</code>=26.11895. Dóna, per tant,
<span class="math display">\[
\left[ \frac{14\cdot 0.07624}{26.11895},
\frac{14\cdot 0.07624}{5.62873}\right]=[0.0409, 0.1896]
\]</span></p>
<p>L’interval de confiança del 95% per a la desviació típica serà aleshores
<span class="math display">\[
[\sqrt{0.0408}, \sqrt{0.1895}]=
[0.202,0.435]
\]</span>
i conté el valor 0.25 que contrastàvem.</p>
<p><em>Conclusió</em>: No hem obtingut evidència estadísticament significativa que la desviació típica (de la quantitat de proteïna total …) sigui diferent de 0.25 (test <span class="math inline">\(\chi^2\)</span>, p-valor 0.504, IC 95% de 0.202 a 0.435).</p>
<p>Aquest test <span class="math inline">\(\chi^2\)</span> d’una variància està implementat en la funció <code>sigma.test</code> del paquet <strong>TeachingDemos</strong>. La seva sintaxi és similar a la de <code>t.test</code> per a una mitjana, canviant la <code>mu</code> per <code>sigma</code> si contrastam la desviació típica o <code>sigmasq</code> si contrastam la variància. Per exemple, per realitzar aquest darrer contrast, simplement entraríem</p>
<div class="sourceCode" id="cb236"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb236-1" data-line-number="1"><span class="kw">library</span>(TeachingDemos)</a>
<a class="sourceLine" id="cb236-2" data-line-number="2"><span class="kw">sigma.test</span>(amnio,<span class="dt">sigma=</span><span class="fl">0.25</span>,<span class="dt">alternative=</span><span class="st">&quot;two.sided&quot;</span>)</a></code></pre></div>
<pre><code>## 
##  One sample Chi-squared test for variance
## 
## data:  amnio
## X-squared = 17.078, df = 14, p-value = 0.5041
## alternative hypothesis: true variance is not equal to 0.0625
## 95 percent confidence interval:
##  0.04086535 0.18962728
## sample estimates:
## var of amnio 
##      0.07624</code></pre>
<p>Ups, què ha passat amb l’interval de confiança? No res: fixau-vos que és el de la variància.</p>

<div class="rmdcaution">
L’interval de confiança que dóna la funció <code>sigma.test</code> és el de la variància, tant si contrastam la desviació típica (amb el paràmetre <code>sigma</code>) com si contrastam la variància (amb el paràmetre <code>sigmasq</code>).
</div>

</div>
<div id="test-f-per-a-dues-variàncies" class="section level3">
<h3><span class="header-section-number">5.2.2</span> Test F per a dues variàncies</h3>
<p>Siguin <span class="math inline">\(X_1,X_2\)</span> dues variables aleatòries normals de desviacions típiques <span class="math inline">\(\sigma_1\)</span> i <span class="math inline">\(\sigma_2\)</span>, respectivament.
En prenem dues mostres aleatòries simples independents de mides <span class="math inline">\(n_1\)</span> i <span class="math inline">\(n_2\)</span> i variàncies mostrals <span class="math inline">\(\widetilde{S}^2_1\)</span> i <span class="math inline">\(\widetilde{S}^2_2\)</span>.</p>
<p>Volem realitzar un contrast
<span class="math display">\[
\left\{\begin{array}{l}
H_{0}:\sigma_1^2=\sigma_2^2\\[1ex]
H_{1}:\sigma_1^2\neq \sigma_2^2\text{ o }\sigma_1^2&gt; \sigma_2^2\text{  o }\sigma_1^2&lt; \sigma_2^2
\end{array}
\right.
\]</span></p>
<p>L’interpretarem
<span class="math display">\[
\left\{\begin{array}{l}
H_{0}:\sigma_1^2/\sigma_2^2=1\\[1ex]
H_{1}:\sigma_1^2/\sigma_2^2\neq 1\text{  o }\sigma_1^2/\sigma_2^2&gt;1 \text{  o }\sigma_1^2/\sigma_2^2&lt; 1
\end{array}
\right.
\]</span></p>
<p>Per realitzar-lo, s’empra l’estadístic de contrast
<span class="math display">\[
F={\widetilde{S}_1^2}/{\widetilde{S}_2^2}
\]</span>
que, si les dues poblacions són normals i
<span class="math display">\[
H_0: \sigma_1=\sigma_2
\]</span>
és vertadera, té distribució coneguda: la <strong>F de Fisher-Snedecor</strong> <span class="math inline">\(F_{n_1-1,n_2-1}\)</span> amb <span class="math inline">\(n_1-1\)</span> i <span class="math inline">\(n_2-1\)</span> graus de llibertat.
Per aquest motiu a aquest contrast se li diu un <strong>test F</strong>.</p>
<p>De la distribució <span class="math inline">\(F_{n,m}\)</span>, on <span class="math inline">\(n,m\)</span> són els seus <strong>graus de llibertat</strong>, heu de saber que:</p>
<ul>
<li><p>Els graus de llibertat <span class="math inline">\(n,m\)</span> són els paràmetres dels quals depèn la funció de distribució, i l’ordre és important: si <span class="math inline">\(n\neq m\)</span>, la distribució <span class="math inline">\(F_{n,m}\)</span> i la distribució <span class="math inline">\(F_{m,n}\)</span> són diferents.</p></li>
<li><p>Amb R és <code>f</code></p></li>
<li><p>No és simètrica, té cua a la dreta i per tant, com explicam d’aquí a una estona, els p-valors dels contrastos bilaterals es calculen com al test <span class="math inline">\(\chi^2\)</span> d’una variància. El gràfic següent mostra les gràfiques de les densitats de les distribucions <span class="math inline">\(F_{n,m}\)</span> per a <span class="math inline">\(n=3,4\)</span> i <span class="math inline">\(m=3,4,5\)</span>. Es pot observar a cada una d’elles una cua a la dreta ben marcada, i també hi podeu observar que les distribucions <span class="math inline">\(F_{3,4}\)</span> i <span class="math inline">\(F_{4,3}\)</span> tenen densitats diferents.</p></li>
</ul>
<p><img src="Bioestadistica-II_files/figure-html/unnamed-chunk-312-1.png" width="50%" style="display: block; margin: auto;" /></p>
<p>Per tant, si diem <span class="math inline">\(F_0\)</span> al valor que pren l’estadístic <span class="math inline">\(F\)</span> sobre la nostra mostra</p>
<ul>
<li><p>Si <span class="math inline">\(H_{1}:\sigma_1^2&gt;\sigma_2^2\)</span>, el p-valor del contrast és <span class="math inline">\(P(F\geqslant F_0)\)</span></p></li>
<li><p>Si <span class="math inline">\(H_{1}:\sigma_1^2&lt;\sigma_2^2\)</span>, el p-valor del contrast és <span class="math inline">\(P(F\leqslant F_0)\)</span></p></li>
<li><p>Si <span class="math inline">\(H_{1}:\sigma_1^2\neq \sigma_2^2\)</span>, el p-valor es pren, <strong>per conveni</strong>, igual a <span class="math inline">\(2\text{min}\big\{P(F\geqslant F_0), P(F\leqslant F_0)\big\}\)</span></p></li>
</ul>
<p>El test F està implementat en la funció <code>var.test</code> de R: s’aplica a les dues mostres, amb sintaxi similar a la de <code>t.test</code>.</p>

<div class="example">
<p><span id="exm:unnamed-chunk-313" class="example"><strong>Exemple 5.10  </strong></span>Les variables <span class="math inline">\(X_d\)</span> i <span class="math inline">\(X_h\)</span> de l’Exemple <a href="contrastos-dhipòtesis-dun-i-dos-paràmetres.html#exm:temphomesdones">5.3</a>, tenen la mateixa variància?</p>
</div>

<p>Suposarem que totes dues són normals (les temperatures ho solen ser) i diguem <span class="math inline">\(\sigma_d^2\)</span> i <span class="math inline">\(\sigma_h^2\)</span> a les seves variàncies.</p>
<p><em>Contrast</em>:
<span class="math display">\[
\left\{\begin{array}{l}
H_{0}:\sigma_d^2=\sigma_h^2\\
H_{1}:\sigma_d^2\neq \sigma_h^2
\end{array}
\right.
\]</span></p>
<p><em>Estadístic de contrast</em>:
<span class="math display">\[
F=\widetilde{S}_d^2/\widetilde{S}_h^2
\]</span></p>
<ul>
<li><em>Valor de l’estadístic de contrast</em> a la nostra mostra, <span class="math inline">\(F_0\)</span>:</li>
</ul>
<div class="sourceCode" id="cb238"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb238-1" data-line-number="1">F0=<span class="kw">var</span>(X_d)<span class="op">/</span><span class="kw">var</span>(X_h)</a>
<a class="sourceLine" id="cb238-2" data-line-number="2"><span class="kw">round</span>(F0,<span class="dv">4</span>)</a></code></pre></div>
<pre><code>## [1] 0.8322</code></pre>
<p>Recordem que les mides de les nostres mostres eren <span class="math inline">\(n_d=116\)</span> i <span class="math inline">\(n_h=114\)</span></p>
<p><em>p-valor</em>:
<span class="math display">\[
\begin{array}{l}
2\min\big\{P(F_{n_d-1,n_h-1} \geqslant F_0), P(F_{n_d-1,n_h-1}\leqslant F_0)\big\}\\
\qquad =2\min\big\{P(F_{115,113} \geqslant 0.8322), P(F_{115,113} \leqslant 0.8322)\big\}\\
\qquad =2\min\{\texttt{1-pf(0.8322,115,113)},\texttt{pf(0.8322,115,113)}\} \\
\qquad =2\min\{0.836,0.164\}=
0.328
\end{array}
\]</span></p>
<p><em>Conclusió</em>: No hem trobat evidència estadísticament significativa que les variables <span class="math inline">\(X_h\)</span> i <span class="math inline">\(X_d\)</span> tenguin variància diferent (test F, p-valor 0.33). Acceptarem que tenen la mateixa variància.</p>
<p>Amb R entraríem:</p>
<div class="sourceCode" id="cb240"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb240-1" data-line-number="1"><span class="kw">var.test</span>(X_d, X_h)</a></code></pre></div>
<pre><code>## 
##  F test to compare two variances
## 
## data:  X_d and X_h
## F = 0.8322, num df = 115, denom df = 113, p-value = 0.3278
## alternative hypothesis: true ratio of variances is not equal to 1
## 95 percent confidence interval:
##  0.575234 1.203224
## sample estimates:
## ratio of variances 
##          0.8321984</code></pre>
<p>Obtenim el mateix p-valor que abans. L’interval de confiança que dóna aquesta funció és <em>per al quocient de les variàncies</em>. Aleshores, com que l’IC 95% conté l’1, no podem rebutjar amb un nivell de significació del 5% que <span class="math inline">\(\sigma_d^2/\sigma_h^2=1\)</span>, és a dir, que <span class="math inline">\(\sigma_d^2=\sigma_h^2\)</span>. Podem ampliar la conclusió:</p>
<p><em>Conclusió</em>: No hem trobat evidència estadísticament significativa que les variables <span class="math inline">\(X_h\)</span> i <span class="math inline">\(X_d\)</span> tenguin variància diferent (test F, p-valor 0.33, IC 95% per al quocient de les variàncies de 0.57 a 1.2). Acceptarem que tenen la mateixa variància.</p>
<p>Per tant, si els tests t amb <code>var.equal=TRUE</code> i <code>var.equal=FALSE</code> de l’Exemple <a href="contrastos-dhipòtesis-dun-i-dos-paràmetres.html#exm:temphomesdones">5.3</a> haguessin donat conclusions diferents, prendríem la corresponent a variàncies iguals.</p>
<p>Hem emprat un test F per comparar aquestes variàncies, i <strong>per que la conclusió sigui fiable, cal que les variables poblacionals siguin normals, no és suficient que les mostres siguin grans</strong>; de fet, la seva validesa no depèn per res de la mida de les mostres. Podem suposar que efectivament les variables <span class="math inline">\(X_d\)</span> i <span class="math inline">\(X_h\)</span> són normals?</p>
<p>Vegem els histogrames:</p>
<div class="sourceCode" id="cb242"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb242-1" data-line-number="1"><span class="kw">hist</span>(X_d,<span class="dt">freq=</span><span class="ot">FALSE</span>, <span class="dt">breaks=</span><span class="dv">4</span>,<span class="dt">col=</span><span class="st">&quot;light blue&quot;</span>,<span class="dt">xlab=</span><span class="st">&quot;Temperatures&quot;</span>,</a>
<a class="sourceLine" id="cb242-2" data-line-number="2">     <span class="dt">ylab=</span><span class="st">&quot;Densitat&quot;</span>,<span class="dt">main=</span><span class="st">&quot;Histograma de temperatures de dones&quot;</span>,<span class="dt">ylim=</span><span class="kw">c</span>(<span class="dv">0</span>,<span class="kw">max</span>(<span class="kw">density</span>(X_d)<span class="op">$</span>y)))</a>
<a class="sourceLine" id="cb242-3" data-line-number="3"><span class="kw">lines</span>(<span class="kw">density</span>(X_d),<span class="dt">lty=</span><span class="dv">2</span>,<span class="dt">lwd=</span><span class="dv">2</span>)</a>
<a class="sourceLine" id="cb242-4" data-line-number="4"><span class="kw">curve</span>(<span class="kw">dnorm</span>(x,<span class="kw">mean</span>(X_d),<span class="kw">sd</span>(X_d)),<span class="dt">col=</span><span class="st">&quot;red&quot;</span>,<span class="dt">lwd=</span><span class="dv">2</span>,<span class="dt">add=</span><span class="ot">TRUE</span>)</a>
<a class="sourceLine" id="cb242-5" data-line-number="5"><span class="kw">legend</span>(<span class="st">&quot;topright&quot;</span>,<span class="dt">legend=</span><span class="kw">c</span>(<span class="st">&quot;Densitat estimada&quot;</span>,<span class="st">&quot;Normal&quot;</span>),</a>
<a class="sourceLine" id="cb242-6" data-line-number="6">       <span class="dt">col=</span><span class="kw">c</span>(<span class="st">&quot;black&quot;</span>,<span class="st">&quot;red&quot;</span>),<span class="dt">lty=</span><span class="kw">c</span>(<span class="dv">2</span>,<span class="dv">1</span>),<span class="dt">cex=</span><span class="fl">0.5</span>)</a>
<a class="sourceLine" id="cb242-7" data-line-number="7"><span class="co">#</span></a>
<a class="sourceLine" id="cb242-8" data-line-number="8"><span class="kw">hist</span>(X_h,<span class="dt">freq=</span><span class="ot">FALSE</span>, <span class="dt">breaks=</span><span class="dv">4</span>,<span class="dt">col=</span><span class="st">&quot;light blue&quot;</span>,<span class="dt">xlab=</span><span class="st">&quot;Temperatures&quot;</span>,</a>
<a class="sourceLine" id="cb242-9" data-line-number="9">     <span class="dt">ylab=</span><span class="st">&quot;Densitat&quot;</span>,<span class="dt">main=</span><span class="st">&quot;Histograma de temperatures d&#39;homes&quot;</span>,<span class="dt">ylim=</span><span class="kw">c</span>(<span class="dv">0</span>,<span class="kw">dnorm</span>(<span class="kw">mean</span>(X_h),<span class="kw">mean</span>(X_h),<span class="kw">sd</span>(X_h))))</a>
<a class="sourceLine" id="cb242-10" data-line-number="10"><span class="kw">lines</span>(<span class="kw">density</span>(X_h),<span class="dt">lty=</span><span class="dv">2</span>,<span class="dt">lwd=</span><span class="dv">2</span>)</a>
<a class="sourceLine" id="cb242-11" data-line-number="11"><span class="kw">curve</span>(<span class="kw">dnorm</span>(x,<span class="kw">mean</span>(X_h),<span class="kw">sd</span>(X_h)),<span class="dt">col=</span><span class="st">&quot;red&quot;</span>,<span class="dt">lwd=</span><span class="dv">2</span>,<span class="dt">add=</span><span class="ot">TRUE</span>)</a>
<a class="sourceLine" id="cb242-12" data-line-number="12"><span class="kw">legend</span>(<span class="st">&quot;topright&quot;</span>,<span class="dt">legend=</span><span class="kw">c</span>(<span class="st">&quot;Densitat estimada&quot;</span>,<span class="st">&quot;Normal&quot;</span>),</a>
<a class="sourceLine" id="cb242-13" data-line-number="13">       <span class="dt">col=</span><span class="kw">c</span>(<span class="st">&quot;black&quot;</span>,<span class="st">&quot;red&quot;</span>),<span class="dt">lty=</span><span class="kw">c</span>(<span class="dv">2</span>,<span class="dv">1</span>),<span class="dt">cex=</span><span class="fl">0.5</span>)</a></code></pre></div>
<p><img src="Bioestadistica-II_files/figure-html/unnamed-chunk-318-1.png" width="90%" style="display: block; margin: auto;" /></p>
<p>i els normal-plot:</p>
<div class="sourceCode" id="cb243"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb243-1" data-line-number="1"><span class="kw">qqPlot</span>(X_d, <span class="dt">distribution=</span><span class="st">&quot;norm&quot;</span>, <span class="dt">mean=</span><span class="kw">mean</span>(X_d), <span class="dt">sd=</span><span class="kw">sd</span>(X_d),</a>
<a class="sourceLine" id="cb243-2" data-line-number="2">       <span class="dt">ylab=</span><span class="st">&quot;Quantils de la mostra de dones&quot;</span>, <span class="dt">xlab=</span><span class="st">&quot;Quantils de normal&quot;</span>, </a>
<a class="sourceLine" id="cb243-3" data-line-number="3">       <span class="dt">pch=</span><span class="dv">20</span>, <span class="dt">id=</span><span class="ot">FALSE</span>)</a>
<a class="sourceLine" id="cb243-4" data-line-number="4"><span class="kw">qqPlot</span>(X_h, <span class="dt">distribution=</span><span class="st">&quot;norm&quot;</span>, <span class="dt">mean=</span><span class="kw">mean</span>(X_h), <span class="dt">sd=</span><span class="kw">sd</span>(X_h),</a>
<a class="sourceLine" id="cb243-5" data-line-number="5">       <span class="dt">ylab=</span><span class="st">&quot;Quantils de la mostra d&#39;homes&quot;</span>, <span class="dt">xlab=</span><span class="st">&quot;Quantils de normal&quot;</span>, </a>
<a class="sourceLine" id="cb243-6" data-line-number="6">       <span class="dt">pch=</span><span class="dv">20</span>, <span class="dt">id=</span><span class="ot">FALSE</span>)</a></code></pre></div>
<p><img src="Bioestadistica-II_files/figure-html/unnamed-chunk-320-1.png" width="90%" style="display: block; margin: auto;" /></p>
<p>Seria millor haver emprat un test no paramètric, per més seguretat.</p>
</div>
<div id="tests-no-paramètrics-1" class="section level3">
<h3><span class="header-section-number">5.2.3</span> Tests no paramètrics</h3>
<p>Quan alguna de les variables poblacionals involucrades en un test de dues variàncies no és normal, no es pot fer servir el test F.</p>
<p>En aquest cas, us recomanam emprar el <strong>test de Fligner-Killeen</strong>, implementat en R en la funció <code>fligner.test</code>, que en la pràctica ha mostrat ser més exacte per a variables aleatòries molt diferents de normals.
<strong>Aquest test només serveix per a contrastos bilaterals</strong>, que en realitat són els únics interessants, i està implementat en la funció <code>fligner.test</code> de R. S’aplica a una <code>list</code> formada per les dues mostres o a una fórmula que separi una variable numèrica en dos grups.</p>
<p>Per exemple, per emprar-lo en el contrast bilateral de variàncies de l’exemple anterior, entraríem:</p>
<div class="sourceCode" id="cb244"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb244-1" data-line-number="1"><span class="kw">fligner.test</span>(<span class="kw">list</span>(X_h,X_d))</a></code></pre></div>
<pre><code>## 
##  Fligner-Killeen test of homogeneity of variances
## 
## data:  list(X_h, X_d)
## Fligner-Killeen:med chi-squared = 1.7736, df = 1, p-value = 0.1829</code></pre>
<p>Seguim acceptant que <span class="math inline">\(X_h\)</span> i <span class="math inline">\(X_d\)</span> tenen la mateixa variància.</p>
</div>
</div>
<div id="contrastos-per-a-proporcions" class="section level2">
<h2><span class="header-section-number">5.3</span> Contrastos per a proporcions</h2>
<div id="contrastos-per-a-una-proporció" class="section level3">
<h3><span class="header-section-number">5.3.1</span> Contrastos per a una proporció</h3>
<p>Suposem que la variable poblacional <span class="math inline">\(X\)</span> és Bernoulli de probabilitat d’èxit <span class="math inline">\(p\)</span> i que volem realitzar un contrast
<span class="math display">\[
\left\{\begin{array}{l}
H_{0}:p=p_{0}\\
H_{1}:p\neq p_{0}\text{ o }  p&gt;p_0 \text{ o } p&lt;p_0
\end{array}
\right.
\]</span></p>
<p>Tenim dues opcions:</p>
<ul>
<li>Realitzar un test binomial exacte, que és el que explicàvem a la Secció <a href="contrastos-dhipòtesis-generalitats.html#sec:moneda">4.2</a></li>
<li>Realitzar un test aproximat basat en l’aproximació d’una distribució binomial per una normal, i que per tant només podem emprar si la mostra és gran</li>
</ul>
<div id="test-binomial-exacte" class="section level4 unnumbered">
<h4>Test binomial exacte</h4>
<p>Suposem que prenem una mostra aleatòria simple de <span class="math inline">\(X\)</span> de mida <span class="math inline">\(n\)</span> qualsevol i que hi obtenim <span class="math inline">\(S_0\)</span> èxits, de manera que <span class="math inline">\(\widehat{p}_X=S_0/n\)</span>.</p>
<p>Si <span class="math inline">\(H_0\)</span> és vertadera, el nombre d’èxits <span class="math inline">\(S\)</span> en una mostra aleatòria simple segueix una distribució <span class="math inline">\(B(n,p_0)\)</span>. Ho podem usar per calcular p-valors de la manera usual:</p>
<ul>
<li><p>Si <span class="math inline">\(H_{1}:p&gt;p_{0}\)</span>, el p-valor és <span class="math inline">\(P(S\geqslant S_0)\)</span></p></li>
<li><p>Si <span class="math inline">\(H_{1}:p&lt;p_{0}\)</span>, el p-valor és <span class="math inline">\(P(S\leqslant S_0)\)</span></p></li>
<li><p>Si <span class="math inline">\(H_{1}:p\neq p_{0}\)</span>, el p-valor és la probabilitat que <span class="math inline">\(S\)</span> estigui tan o més allunyada que <span class="math inline">\(S_0\)</span> del nombre d’èxits que esperaríem si <span class="math inline">\(H_0\)</span> fos vertadera, que és <span class="math inline">\(p_0\cdot n\)</span>. Per tant, és
<span class="math display">\[
\text{p-valor}=P(|S-p_0\cdot n|\geqslant|S_0-p_0\cdot n|)
\]</span></p></li>
</ul>
<p>Aquesta probabilitat també es pot calcular com la probabilitat que <span class="math inline">\(S\)</span> prengui un valor de probabilitat més petita o igual que la de <span class="math inline">\(S_0\)</span>:
<span class="math display">\[
\text{p-valor}=\sum_{k\ \mathrm{tal\ que}\atop P(S=k)\leqslant P(S=S_0)} P(S=k)
\]</span></p>

<div class="rmdcaution">
Una distribució binomial <span class="math inline">\(B(n,p_0)\)</span> només és simètrica quan <span class="math inline">\(p_0= 0.5\)</span>.
</div>

<p>Aquest test binomial exacte està implementat en R en la funció <code>binom.test</code></p>
<div class="sourceCode" id="cb246"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb246-1" data-line-number="1"><span class="kw">binom.test</span>(S, n, <span class="dt">p=</span>..., <span class="dt">alternative=</span>..., <span class="dt">conf.level=</span>...)</a></code></pre></div>
<p>on <code>S</code> indica al nombre d’èxits a la mostra, <code>n</code> la mida de la mostra, <code>p</code> la probablitat que es contrasta, i els altres dos paràmetres signifiquen el mateix que a les altres funcions explicades fins ara. L’interval de confiança que dóna en els contrastos bilaterals és el de Clopper-Pearson.</p>

<div class="example">
<p><span id="exm:esqUIB1" class="example"><strong>Exemple 5.11  </strong></span>Ens demanam si la proporció d’estudiants esquerrans a la UIB, és diferent de la de l’estat espanyol, que és del 10%.</p>
</div>

<p>Prenem un mostra de 30 estudiants de la UIB més o menys a l’atzar i hi trobam 1 esquerrà.</p>
<p><em>Variable aleatòria d’interès</em>: <span class="math inline">\(X\)</span>: “Prenem un estudiant de la UIB i miram si és esquerrà”, de probabilitat d’èxit <span class="math inline">\(p\)</span></p>
<p><em>Contrast</em>:
<span class="math display">\[
\left\{\begin{array}{l}
H_{0}:p=0.1\\
H_{1}:p\neq 0.1
\end{array}
\right.
\]</span></p>
<p>Emprarem el test binomial exacte</p>
<p><em>Estadístic de contrast</em>: Nombre d’èxits <span class="math inline">\(S\)</span>, que si <span class="math inline">\(H_0\)</span> és vertadera, té distribució <span class="math inline">\(B(n,0.1)\)</span></p>
<p><em>Valor de l’estadístic de contrast</em>: 1</p>
<p><em>p-valor</em>: Si la hipòtesi nul·la <span class="math inline">\(p=0.1\)</span> fos vertadera, en una mostra aleatòria de 30 estudiants esperaríem 3 esquerrans, i n’hem trobat 1. Per tant el p-valor és la probabilitat la diferència en valor absolut entre <span class="math inline">\(S\)</span> i 1 sigui més gran o igual que 2, és a dir, que <span class="math inline">\(S\)</span> sigui més petit o igual que 1 o més gran o igual que 5:
<span class="math display">\[
\begin{array}{rl}
P(|S-3|\geqslant|S_0-3|) &amp; =P(|S-3|\geqslant 2)\\
&amp;= P(S\leqslant 1)+P(S\geqslant 5)\\
&amp; =\texttt{pbinom(1,30,0.1)+1-pbinom(4,30,0.1)}=0.359
\end{array}
\]</span></p>
<p><em>Conclusió</em>: No hem obtingut evidència estadísticament significativa que el percentatge d’esquerrans a la UIB sigui diferent del 10% (test binomial, p-valor 0.36).</p>

<div class="rmdnote">
Hem dit que el p-valor també es pot calcular com a
<span class="math display">\[
\text{p-valor}=\sum_{P(S=k)\leqslant P(S=S_0)} P(S=k)
\]</span>
Vegem-ho. Direm <code>PB</code> al vector que dóna els valors de la densitat de <span class="math inline">\(S\)</span> sobre <span class="math inline">\(k=0,\ldots,30\)</span>, que són tots els possibles valors de <span class="math inline">\(k\)</span>. Aleshores, els <span class="math inline">\(k\)</span> tals que <span class="math inline">\(P(S=k)\leqslant P(S=S_0)\)</span> són els que satisfan <code>PB&lt;=dbinom(1,30,0.1)</code> (o també <code>PB&lt;=PB[2]</code>, perquè <span class="math inline">\(P(S=1)\)</span> és la segona entrada del vector <code>PB</code>; la primera és <span class="math inline">\(P(S=0)\)</span>). Per tant, la suma de les seves probabilitats és:
</div>

<div class="sourceCode" id="cb247"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb247-1" data-line-number="1">PB=<span class="kw">dbinom</span>(<span class="dv">0</span><span class="op">:</span><span class="dv">30</span>,<span class="dv">30</span>,<span class="fl">0.1</span>)</a>
<a class="sourceLine" id="cb247-2" data-line-number="2"><span class="kw">sum</span>(PB[PB<span class="op">&lt;=</span><span class="kw">dbinom</span>(<span class="dv">1</span>,<span class="dv">30</span>,<span class="fl">0.1</span>)])</a></code></pre></div>
<pre><code>## [1] 0.3591899</code></pre>
<p>Amb R, entraríem:</p>
<div class="sourceCode" id="cb249"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb249-1" data-line-number="1"><span class="kw">binom.test</span>(<span class="dv">1</span>, <span class="dv">30</span>, <span class="dt">p=</span><span class="fl">0.1</span>, <span class="dt">alternative=</span><span class="st">&quot;two.sided&quot;</span>)</a></code></pre></div>
<pre><code>## 
##  Exact binomial test
## 
## data:  1 and 30
## number of successes = 1, number of trials = 30, p-value = 0.3592
## alternative hypothesis: true probability of success is not equal to 0.1
## 95 percent confidence interval:
##  0.0008435709 0.1721694556
## sample estimates:
## probability of success 
##             0.03333333</code></pre>
<p>i a més obtenim l’IC 95% de Clopper-Pearson per a <span class="math inline">\(p\)</span>, per tant podem refinar la nostra conclusió:</p>
<p><em>Conclusió</em>: No hem obtingut evidència estadísticament significativa que el percentatge d’esquerrans a la UIB sigui diferent del 10% (test binomial, p-valor 0.37, IC 95% de 0.001 a 0.172).</p>
</div>
<div id="test-aproximat" class="section level4 unnumbered">
<h4>Test aproximat</h4>
<p>Suposem que prenem una mostra aleatòria simple de <span class="math inline">\(X\)</span> de mida <span class="math inline">\(n\)</span> <em>gran</em>, posem de 40 subjectes o més, i que hi obtenim una proporció mostral d’èxits <span class="math inline">\(\widehat{p}_X\)</span>. En aquest cas, si <span class="math inline">\(H_{0}:p=p_{0}\)</span> és vertadera, pel Teorema Central del Límit, la distribució de
<span class="math display">\[
Z=\frac{\widehat{p}_X-p_0}{\sqrt{\frac{p_0(1-p_0)}{n}}}
\]</span>
és aproximadament la d’una variable <span class="math inline">\(N(0,1)\)</span>. Ho podem emprar per calcular p-valors i intervals de confiança com en el test t. En particular, si <span class="math inline">\(Z\)</span> pren el valor <span class="math inline">\(z_0\)</span> sobre la nostra mostra,</p>
<ul>
<li><p>Quan <span class="math inline">\(H_{1}:p&gt;p_{0}\)</span>, el p-valor és <span class="math inline">\(P(Z\geqslant z_0)\)</span></p></li>
<li><p>Quan <span class="math inline">\(H_{1}:p&lt;p_{0}\)</span>, el p-valor és <span class="math inline">\(P(Z\leqslant z_0)\)</span></p></li>
<li><p>Quan <span class="math inline">\(H_{1}:p\neq p_{0}\)</span>, el p-valor és <span class="math inline">\(2P(Z\geqslant|z_0|)\)</span> (recordau que <span class="math inline">\(Z\)</span> és simètrica)</p></li>
</ul>
<p>Amb R, està implementat en la funció</p>
<div class="sourceCode" id="cb251"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb251-1" data-line-number="1"><span class="kw">prop.test</span>(x, n, <span class="dt">p=</span>...,<span class="dt">alternative=</span>..., <span class="dt">conf.level=</span>..., </a>
<a class="sourceLine" id="cb251-2" data-line-number="2">          <span class="dt">correct=</span>...)</a></code></pre></div>
<p>on els paràmetres tenen el mateix significat que a <code>binom.test</code> excepte <code>correct</code>, que serveix per especificar si volem que s’apliqui una correcció de continuïtat com la que explicàvem al <a href="https://aprender-uib.github.io/MatesIIAD/repas-de-la-distribucio-normal.html">Tema de Repàs de la Distribució Normal</a> (que és recomanable quan s’aproxima una variable discreta per una contínua però que nosaltres no aplicarem en realitzar contrastos “a mà” per no complicar-los) que millora els resultats. El seu valor per defecte és <code>TRUE</code>, i és el que us recomanan que empreu; el que hem explicat aquí correspon a <code>correct=FALSE</code>. L’interval de confiança que dóna aquesta funció en un contrast bilateral és el de Wilson (amb o sense correcció de continuïtat, segons el que valgui <code>correct</code>).</p>

<div class="example">
<p><span id="exm:unnamed-chunk-328" class="example"><strong>Exemple 5.12  </strong></span>Continuant amb l’Exemple <a href="contrastos-dhipòtesis-dun-i-dos-paràmetres.html#exm:esqUIB1">5.11</a>, ara hi emprarem el test aproximat, tot i que no és lo seu.</p>
</div>

<p><em>Estadístic de contrast</em>:
<span class="math display">\[
Z=\frac{\widehat{p}_X-p_0}{\sqrt{\frac{p_0(1-p_0)}{n}}} 
\]</span>
que, si <span class="math inline">\(H_0\)</span> és vertadera, seguiria una distribució (aproximadament) normal estándard.</p>
<p><em>Valor sobre la nostra mostra</em>:
<span class="math display">\[
z_0=\frac{\frac{1}{30}-0.1}{\sqrt{\frac{0.1(1-0.1)}{30}}}=-1.22
\]</span></p>
<p><em>p-valor</em>: <span class="math inline">\(2P(Z\geqslant|-1.22|)=\texttt{2*(1-pnorm(1.22))}=0.222\)</span></p>
<p><em>Conclusió</em>: Un altre cop, no obtenim evidència estadísticament significativa que el percentatge d’esquerrans a la UIB sigui diferent del 10% (prop-test, p-valor 0.22).</p>
<p>Amb R, entraríem:</p>
<div class="sourceCode" id="cb252"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb252-1" data-line-number="1"><span class="kw">prop.test</span>(<span class="dv">1</span>, <span class="dv">30</span>, <span class="dt">p=</span><span class="fl">0.1</span>, <span class="dt">alternative=</span><span class="st">&quot;two.sided&quot;</span>)</a></code></pre></div>
<pre><code>## Warning in prop.test(1, 30, p = 0.1, alternative = &quot;two.sided&quot;): Chi-squared
## approximation may be incorrect</code></pre>
<pre><code>## 
##  1-sample proportions test with continuity correction
## 
## data:  1 out of 30, null probability 0.1
## X-squared = 0.83333, df = 1, p-value = 0.3613
## alternative hypothesis: true p is not equal to 0.1
## 95 percent confidence interval:
##  0.001742467 0.190530216
## sample estimates:
##          p 
## 0.03333333</code></pre>
<p>No dóna el mateix p-valor que abans, perquè, com hem explicat, el nostre test correspon a <code>correct=FALSE</code>:</p>
<div class="sourceCode" id="cb255"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb255-1" data-line-number="1"><span class="kw">prop.test</span>(<span class="dv">1</span>, <span class="dv">30</span>, <span class="dt">p=</span><span class="fl">0.1</span>, <span class="dt">alternative=</span><span class="st">&quot;two.sided&quot;</span>, <span class="dt">correct=</span><span class="ot">FALSE</span>)</a></code></pre></div>
<pre><code>## Warning in prop.test(1, 30, p = 0.1, alternative = &quot;two.sided&quot;, correct =
## FALSE): Chi-squared approximation may be incorrect</code></pre>
<pre><code>## 
##  1-sample proportions test without continuity correction
## 
## data:  1 out of 30, null probability 0.1
## X-squared = 1.4815, df = 1, p-value = 0.2235
## alternative hypothesis: true p is not equal to 0.1
## 95 percent confidence interval:
##  0.00590859 0.16670391
## sample estimates:
##          p 
## 0.03333333</code></pre>

<div class="rmdcorbes">
Si llegiu amb cura la sortida del <code>prop.test</code>, veureu que no empra un estadístic de contrast que té una distribució normal, sinó un que té distribució <span class="math inline">\(\chi^2\)</span> amb 1 grau de llibertat: <code>X-squared=..., df=1</code>. El que passa és que R no empra l’estadístic <span class="math inline">\(Z\)</span> que hem explicat, sinó el seu quadrat, <span class="math inline">\(Z^2\)</span>, que té distribució <span class="math inline">\(\chi_1^2\)</span> perquè <span class="math inline">\(Z\)</span> és normal estàndard.
</div>


<div class="rmdnote">
El missatge d’advertència que ens ha donat R en aquestes dues execucions de la funció <code>prop.test</code> ens diu que no se satisfan les condicions necessàries per que el resultat d’aquest contrast sigui vàlid.
</div>


<div class="example">
<p><span id="exm:unnamed-chunk-333" class="example"><strong>Exemple 5.13  </strong></span>Quina és la potència del contrast realitzat a l’exemple anterior?</p>
</div>

<p>Emprarem les funcions del paquet <strong>pwr</strong> per calcular-la; per més informació sobre les funcions d’aquest paquet, consultau la <a href="https://aprender-uib.github.io/AprendeR2/chap-contrastes.html#calculo-de-la-potencia-de-un-contraste">secció corresponent del manual de R</a>. Primer calculam la mida de l’efecte observat amb la funció <code>ES.h</code> aplicada a la proporció poblacional contrastada i a la proporció mostral:</p>
<div class="sourceCode" id="cb258"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb258-1" data-line-number="1"><span class="kw">library</span>(pwr)</a>
<a class="sourceLine" id="cb258-2" data-line-number="2"><span class="kw">ES.h</span>(<span class="fl">0.1</span>,<span class="fl">0.03</span>)</a></code></pre></div>
<pre><code>## [1] 0.2953351</code></pre>
<p>I ara aplicam la funció <code>pwr.p.test</code> a la mida de l’efecte observat, <code>h</code>, la mida de la mostra, <code>n</code>, el nivell de significació, <code>sig.level</code>, i el tipus de contrast, <code>alternative</code>, i ens donarà la potència:</p>
<div class="sourceCode" id="cb260"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb260-1" data-line-number="1"><span class="kw">pwr.p.test</span>(<span class="dt">h=</span><span class="fl">0.3</span>, <span class="dt">n=</span><span class="dv">30</span>, <span class="dt">sig.level=</span><span class="fl">0.05</span>, <span class="dt">alternative=</span><span class="st">&quot;two.sided&quot;</span>)</a></code></pre></div>
<pre><code>## 
##      proportion power calculation for binomial distribution (arcsine transformation) 
## 
##               h = 0.3
##               n = 30
##       sig.level = 0.05
##           power = 0.3758563
##     alternative = two.sided</code></pre>
<p>Què hagués passat si, en lloc d’1 esquerrà en una mostra de 30, haguéssim trobat 5 esquerrans en una mostra (aleatòria simple) de 150 estudiants, de manera que la proporció mostral fos la mateixa?</p>
<div class="sourceCode" id="cb262"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb262-1" data-line-number="1"><span class="kw">prop.test</span>(<span class="dv">5</span>, <span class="dv">150</span>, <span class="dt">p=</span><span class="fl">0.1</span>)</a></code></pre></div>
<pre><code>## 
##  1-sample proportions test with continuity correction
## 
## data:  5 out of 150, null probability 0.1
## X-squared = 6.6852, df = 1, p-value = 0.009722
## alternative hypothesis: true p is not equal to 0.1
## 95 percent confidence interval:
##  0.01233588 0.08010876
## sample estimates:
##          p 
## 0.03333333</code></pre>
<p>Ara podríem rebutjar amb un nivell de significació del 5% que la proporció d’esquerrans a la UIB és del 10%. Quina ha estat la potència d’aquest test?</p>
<div class="sourceCode" id="cb264"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb264-1" data-line-number="1"><span class="kw">pwr.p.test</span>(<span class="dt">h=</span><span class="fl">0.3</span>, <span class="dt">n=</span><span class="dv">150</span>, <span class="dt">sig.level=</span><span class="fl">0.05</span>, <span class="dt">alternative=</span><span class="st">&quot;two.sided&quot;</span>)</a></code></pre></div>
<pre><code>## 
##      proportion power calculation for binomial distribution (arcsine transformation) 
## 
##               h = 0.3
##               n = 150
##       sig.level = 0.05
##           power = 0.9567605
##     alternative = two.sided</code></pre>

<div class="rmdimportant">
Amb una mostra més gran, la potència és més gran, és més fàcil detectar que la hipòtesi alternativa sigui vertadera.
</div>


<div class="example">
<p><span id="exm:unnamed-chunk-339" class="example"><strong>Exemple 5.14  </strong></span>De quina mida hauríem d’haver pres la mostra per obtenir una potència del 90% amb <span class="math inline">\(\alpha=0.05\)</span> i esperant un efecte petit?</p>
</div>

<p>Per determinar el valor d’un “efecte petit” entram</p>
<div class="sourceCode" id="cb266"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb266-1" data-line-number="1"><span class="kw">cohen.ES</span>(<span class="dt">test=</span><span class="st">&quot;p&quot;</span>,<span class="dt">size=</span><span class="st">&quot;small&quot;</span>)</a></code></pre></div>
<pre><code>## 
##      Conventional effect size from Cohen (1982) 
## 
##            test = p
##            size = small
##     effect.size = 0.2</code></pre>
<p>i ara, a l’argument <code>pwr.p.test</code>, en lloc d’entrar-hi la mida de la mostra <code>n</code>, hi entram la potència desitjada i ens donarà la mida necessària per assolir-la:</p>
<div class="sourceCode" id="cb268"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb268-1" data-line-number="1"><span class="kw">pwr.p.test</span>(<span class="dt">h=</span><span class="fl">0.2</span>, <span class="dt">power=</span><span class="fl">0.9</span>, <span class="dt">sig.level=</span><span class="fl">0.05</span>, <span class="dt">alternative=</span><span class="st">&quot;two.sided&quot;</span>)</a></code></pre></div>
<pre><code>## 
##      proportion power calculation for binomial distribution (arcsine transformation) 
## 
##               h = 0.2
##               n = 262.6855
##       sig.level = 0.05
##           power = 0.9
##     alternative = two.sided</code></pre>
<p>Ens caldria una mostra aleatòria simple de 263 estudiants.</p>

<div class="rmdnote">
Com que en un contrast d’una proporció sempre hi podem emprar el test binomial exacte, no hi ha necessitat d’emprar-hi tests no paramètrics.
</div>

</div>
</div>
<div id="contrastos-per-a-2-proporcions-emprant-mostres-independents" class="section level3">
<h3><span class="header-section-number">5.3.2</span> Contrastos per a 2 proporcions emprant mostres independents</h3>
<p>Siguin <span class="math inline">\(X_1\)</span> i <span class="math inline">\(X_2\)</span> dues variables aleatòries Bernoulli de paràmetres poblacionals d’èxit <span class="math inline">\(p_1\)</span> i <span class="math inline">\(p_2\)</span>.</p>
<p>Volem realitzar un contrast
<span class="math display">\[
\left\{\begin{array}{l}
H_{0}:p_1=p_2\\ 
H_{1}:p_1\neq p_2\text{ o }p_1&gt; p_2\text{ o }p_1&lt; p_2
\end{array}
\right.
\]</span></p>
<p>Suposem que, per realitzar aquest contrast, prenem una mostra aleatòria simple de cada variable, independents una de l’altra.
Obtenim la taula de freqüències següent
<span class="math display">\[
\begin{array}{r|cc|c }
  &amp; X_1 &amp; X_2 &amp; \textrm{Total}  \\\hline
\textrm{Èxits} &amp; n_{11} &amp; n_{12} &amp; E  \\
\textrm{Fracassos} &amp; n_{21} &amp; n_{22} &amp; F   \\\hline 
\textrm{Total} &amp; n_{1} &amp; n_{2} 
\end{array}
\]</span></p>
<p>Aleshores tenim dues opcions:</p>
<ul>
<li>Realitzar un test <span class="math inline">\(\chi^2\)</span>, que es basa en una aproximació a una normal i requereix algunes condicions sobre les dues mostres</li>
<li>Realitzar un test de Fisher, que es pot emprar sempre però no dóna la informació exactament com la voldríem</li>
</ul>
<div id="test-chi2" class="section level4 unnumbered">
<h4>Test <span class="math inline">\(\chi^2\)</span></h4>
<p>Suposem que les dues mostres són <em>grans</em>, per fixar idees <span class="math inline">\(n_1,n_2\geqslant 50\)</span>, i que els nombres d’èxits i de fracasos a cada mostra <em>no són molt petits</em>, per fixar idees tots dos més grans o iguals que 5. Siguin <span class="math inline">\(\widehat{p}_1\)</span> i <span class="math inline">\(\widehat{p}_2\)</span> les proporcions mostrals d’èxits a les dues mostres.</p>
<p>En aquestes condicions, si la hipòtesi nul·la <span class="math inline">\(H_0: p_1=p_2\)</span> és vertadera, l’<em>estadístic de contrast</em>
<span class="math display">\[
Z=\frac{\widehat{p}_1 -\widehat{p}_2}{
\sqrt{\frac{E}{n_1
+n_2}\cdot \Big(1-\frac{E}{n_1
+n_2}\Big)\cdot \Big(\frac{1}{n_1}+\frac{1}{n_2}
\Big)}}
\]</span>
(on <span class="math inline">\(E=n_1 \widehat{p}_1 +n_2 \widehat{p}_2\)</span> és el nombre total d’èxits a les dues mostres) té distribució aproximadament normal estàndard, la qual cosa es pot emprar com sempre per calcular p-valors i intervals de confiança.</p>
<p>Aquest test està implementat en la funció de R</p>
<div class="sourceCode" id="cb270"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb270-1" data-line-number="1"><span class="kw">prop.test</span>(<span class="kw">c</span>(x1,x2), <span class="kw">c</span>(n1,n2), <span class="dt">alternative=</span>..., <span class="dt">correct=</span>...,</a>
<a class="sourceLine" id="cb270-2" data-line-number="2">          <span class="dt">conf.level=</span>...,)</a></code></pre></div>
<p>on <code>x1</code> i <code>x2</code> són els nombres d’èxits a les dues mostres i <code>n1</code>, <code>n2</code> les seves mides. Com al cas d’una proporció, la versió que hem explicat correspon a <code>correct=FALSE</code>, però és més recomanable emprar el valor per defecte de <code>correct</code>, que és TRUE i fa que s’hi apliqui una correcció de continuïtat.</p>

<div class="rmdnote">
Aquest test s’anomena <strong>prop-test</strong>, o també <strong>test</strong> <span class="math inline">\(\chi^2\)</span> perquè és un cas particular d’un test <span class="math inline">\(\chi^2\)</span> que veurem al proper tema. De fet, com en el cas d’una proporció, en la seva implementació en R no s’hi empra <span class="math inline">\(Z\)</span> sinó <span class="math inline">\(Z^2\)</span>, que té distribució aproximadament <span class="math inline">\(\chi^2_1\)</span>.
</div>


<div class="example">
<p><span id="exm:allel1" class="example"><strong>Exemple 5.15  </strong></span>En un estudi es volgué saber si un determinat al·lel d’un gen és present o no amb la mateixa proporció entre els mallorquins i els menorquins. Es prengueren una mostra d’ADN de 100 individus amb almenys tres generacions familiars a l’illa de Mallorca, i una altra de 50 individus amb almenys tres generacions familiars a l’illa de Menorca: les mostres es prengueren de manera independent. A la mostra mallorquina, 20 individus tengueren l’al·lel, i a la mostra menorquina, 12. La taula de freqüències és, doncs</p>
</div>

<p><span class="math display">\[
\begin{array}{r|cc }
  &amp; \textrm{Mallorca} &amp; \textrm{Menorca}  \\\hline
\textrm{Present} &amp; 20 &amp; 12 \\
\textrm{Absent} &amp; 80 &amp; 38   \\\hline 
\textrm{Total} &amp; 100 &amp; 50   
\end{array}
\]</span></p>

<div class="rmdexercici">
Com és aquesta mostra, per conglomerats o estratificada?
</div>

<p><em>Variables d’interés</em>:</p>
<ul>
<li><span class="math inline">\(X_1\)</span>: “Prenem un mallorquí amb 3 generacions familiars a l’illa i miram si té aquest al·lel”</li>
<li><span class="math inline">\(X_2\)</span>: “Prenem un menorquí amb 3 generacions familiars a l’illa i miram si té aquest al·lel”</li>
</ul>
<p>Totes dues són Bernoulli, amb proporcions poblacionals d’èxit <span class="math inline">\(p_1\)</span> i <span class="math inline">\(p_2\)</span>, respectivament.</p>
<p><em>Contrast</em>:
<span class="math display">\[
\left\{\begin{array}{l}
H_0:p_1=p_2\\
H_1:p_1\neq p_2
\end{array}\right.
\]</span></p>
<p>Estam les condicions de poder emprar el test <span class="math inline">\(\chi^2\)</span>, perquè les dues mostres i els seus nombres d’èxits (individus amb l’al·lel) i fracassos (individus sense l’al·lel) són prou grans.</p>
<p><em>Estadístic de contrast</em>:
<span class="math display">\[
Z=\frac{\widehat{p}_1 -\widehat{p}_2}{
\sqrt{\frac{E}{n_1+n_2}\cdot \Big(1-\frac{E}{n_1
+n_2}\Big)\cdot\Big(\frac{1}{n_1}+\frac{1}{n_2}
\Big)}}
\]</span>
que és aproximadament <span class="math inline">\(N(0,1)\)</span> si <span class="math inline">\(H_0\)</span> és vertadera.</p>
<p><em>Valor de l’estadístic</em>: Teim que <span class="math inline">\(\widehat{p}_1=0.2\)</span>, <span class="math inline">\(\widehat{p}_2=0.24\)</span>, <span class="math inline">\(n_1=100\)</span>, <span class="math inline">\(n_2=50\)</span>, <span class="math inline">\(E=20+12=32\)</span> i per tant
<span class="math display">\[
z_0=\frac{0.2 -0.24}{
\sqrt{\frac{32}{150}\Big(1-\frac{32}{150}\Big)\Big(\frac{1}{100}+\frac{1}{50}
\Big)}}
=-0.5637
\]</span></p>
<p><em>p-valor</em>: <span class="math inline">\(2\cdot P(Z\geqslant|-0.5637|)=0.573\)</span></p>
<p><em>Conclusió</em>: No hem trobat evidència estadísticament significativa que les proporcions de mallorquins i menorquins amb aquest al·lel siguin diferents (test <span class="math inline">\(\chi^2\)</span>, p-valor 0.57).</p>
<p>Amb R, entraríem</p>
<div class="sourceCode" id="cb271"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb271-1" data-line-number="1"><span class="kw">prop.test</span>(<span class="kw">c</span>(<span class="dv">20</span>,<span class="dv">12</span>), <span class="kw">c</span>(<span class="dv">100</span>,<span class="dv">50</span>), <span class="dt">alternative=</span><span class="st">&quot;two.sided&quot;</span>)</a></code></pre></div>
<pre><code>## 
##  2-sample test for equality of proportions with continuity correction
## 
## data:  c(20, 12) out of c(100, 50)
## X-squared = 0.12414, df = 1, p-value = 0.7246
## alternative hypothesis: two.sided
## 95 percent confidence interval:
##  -0.1969858  0.1169858
## sample estimates:
## prop 1 prop 2 
##   0.20   0.24</code></pre>
<p>Bé, no exactament: com hem explicat, nosaltres hem fet la versió <code>correct=FALSE</code>.</p>
<div class="sourceCode" id="cb273"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb273-1" data-line-number="1"><span class="kw">prop.test</span>(<span class="kw">c</span>(<span class="dv">20</span>,<span class="dv">12</span>), <span class="kw">c</span>(<span class="dv">100</span>,<span class="dv">50</span>), <span class="dt">alternative=</span><span class="st">&quot;two.sided&quot;</span>, <span class="dt">correct=</span><span class="ot">FALSE</span>)</a></code></pre></div>
<pre><code>## 
##  2-sample test for equality of proportions without continuity
##  correction
## 
## data:  c(20, 12) out of c(100, 50)
## X-squared = 0.3178, df = 1, p-value = 0.5729
## alternative hypothesis: two.sided
## 95 percent confidence interval:
##  -0.1819858  0.1019858
## sample estimates:
## prop 1 prop 2 
##   0.20   0.24</code></pre>
<p>L’interval de confiança que dóna la funció <code>prop.test</code> en un contrast de dues proporcions és per a la diferència de les proporcions, <span class="math inline">\(p_1-p_2\)</span>.</p>
</div>
<div id="test-exacte-de-fisher" class="section level4 unnumbered">
<h4>Test exacte de Fisher</h4>
<p>Si no se satisfan les condicions pel test <span class="math inline">\(\chi^2\)</span>, sempre es pot aplicar el <em>test exacte de Fisher</em>, que es basa en la idea següent.
Tenim la taula de freqüències
<span class="math display">\[
\begin{array}{r|cc|c }
  &amp; X_1 &amp; X_2 &amp; \textrm{Total}  \\\hline
\textrm{Èxits} &amp; n_{11} &amp; n_{12} &amp; E  \\
\textrm{Fracassos} &amp; n_{21} &amp; n_{22} &amp; F   \\\hline 
\textrm{Total} &amp; n_{1} &amp; n_{2} 
\end{array}
\]</span></p>
<p>Si <span class="math inline">\(p_1=p_2\)</span>, les dues variables <span class="math inline">\(X_1\)</span> i <span class="math inline">\(X_2\)</span> tenen la mateixa probabilitat d’èxit, i per tant les dues mostres podrien considerar-se com a dues mostres independents de la mateixa variable <span class="math inline">\(X_1\)</span>. Llavors, la probabilitat d’obtenir <span class="math inline">\(n_{11}\)</span> èxits dins la mostra de <span class="math inline">\(X_1\)</span> és la de:</p>
<blockquote>
<p>Si en una bossa hi tenim <span class="math inline">\(E\)</span> bolles “Èxit” i <span class="math inline">\(F\)</span> bolles “Fracàs”, la probabilitat d’obtenir <span class="math inline">\(n_{11}\)</span> bolles “Èxit” si en triam <span class="math inline">\(n_{1}\)</span> de cop.</p>
</blockquote>
<p>Per tant, la distribució de la variable <span class="math inline">\(N_{11}\)</span> que dóna el valor de <span class="math inline">\(n_{1,1}\)</span> (nombre d’èxits de <span class="math inline">\(X_1\)</span> en una mostra amb els valors de <span class="math inline">\(E,F,n_1\)</span> com la nostra) és hipergeomètrica <span class="math inline">\(H(E,F,n_{1})\)</span>. Podem emprar <span class="math inline">\(N_{11}\)</span> com a estadístic de contrast i la distribució hipergeomètrica per calcular p-valors com en el test binomial. En particular, si <span class="math inline">\(n_{1,1}\)</span> és el valor d’aquesta variable en la nostra mostra</p>
<ul>
<li><p>Si <span class="math inline">\(H_1:p_1&gt;p_2\)</span>, el p-valor és <span class="math inline">\(P(N_{1,1}\geqslant n_{1,1})\)</span>, on, recordem, <span class="math inline">\(N_{1,1}\sim H(E,F,n_{1})\)</span></p></li>
<li><p>Si <span class="math inline">\(H_1:p_1&lt;p_2\)</span>, el p-valor és <span class="math inline">\(P(N_{1,1}\leqslant n_{1,1})\)</span></p></li>
<li><p>Si <span class="math inline">\(H_1:p_1=p_2\)</span>, sigui <span class="math inline">\(n_0\)</span> el valor esperat de la variable <span class="math inline">\(N_{1,1}\sim H(E,F,n_{1})\)</span>, que és <span class="math inline">\(n_1\cdot E/(E+F)\)</span>. Aleshores el p-valor és la probabilitat que la variable <span class="math inline">\(N_{1,1}\)</span> prengui un valor tan o més diferent d’aquest <span class="math inline">\(n_0\)</span> que <span class="math inline">\(n_{1,1}\)</span>:
<span class="math display">\[
P(|N_{1,1}-n_0|\geqslant|n_{1,1}-n_0|)
\]</span>
També es pot calcular com la probabilitat que <span class="math inline">\(N_{1,1}\)</span> prengui un valor de probabilitat més petita o igual que la de <span class="math inline">\(n_{1,1}\)</span>:
<span class="math display">\[
\sum_{k\ \mathrm{tal\ que}\atop P(N_{1,1}=k)\leqslant P(N_{1,1}=n_{1,1})} P(N_{1,1}=k)
\]</span></p></li>
</ul>

<div class="example">
<p><span id="exm:SIDS1" class="example"><strong>Exemple 5.16  </strong></span>Per determinar si la Síndrome de Mort Sobtada del Nadó (SIDS) té component genètic, es consideren els casos de SIDS en parelles de bessons monozigòtics i dizigòtics. Diguem:</p>
</div>

<ul>
<li><p><span class="math inline">\(p_1\)</span>: proporció de parelles de bessons monozigòtics amb algun cas de SIDS on només un germà la sofrí</p></li>
<li><p><span class="math inline">\(p_2\)</span>: proporció de parelles de bessons dizigòtics amb algun cas de SIDS on només un germà la sofrí</p></li>
</ul>
<p>Si la SIDS té component genètic, hauria de passar que <span class="math inline">\(p_1&lt;p_2\)</span>. En efecte, si aquesta síndrome té component genètic i en una parella de bessons un d’ells mor per SIDS, és més probable que l’altre bessó també la sofreixi si els bessons són monozigòtics que si són dizigòtics, ja que els genomes dels monozigòtics són pràcticament idèntics i els dels dizigòtics no. És a dir, és més probable que l’altre bessó també mori per SIDS si els bessons són monozigòtics que si són dizigòtics, o el que és el mateix,
<em>és MENYS probable que l’altre bessó NO mori per SIDS si els bessons són monozigòtics que si són dizigòtics</em>.</p>
<p>Per tant les variables d’interès són:</p>
<ul>
<li><p><span class="math inline">\(X_1\)</span>: “Prenem una parella de bessons monozigòtics amb algun cas de SIDS, i miram si només un germà la sofrí”, que és Bernoulli amb probabilitat d’èxit <span class="math inline">\(p_1\)</span></p></li>
<li><p><span class="math inline">\(X_2\)</span>: “Prenem una parella de bessons dizigòtics amb algun cas de SIDS, i miram si només un germà la sofrí”, que és Bernoulli amb probabilitat d’èxit <span class="math inline">\(p_2\)</span></p></li>
</ul>
<p>i el contrast que volem realitzar és
<span class="math display">\[
\left\{\begin{array}{l}
H_0:p_1=p_2\\
H_1:p_1&lt; p_2
\end{array}\right.
\]</span></p>
<p>En un estudi s’obtingueren les dades següents:
<span class="math display">\[
\begin{array}{c}
\hphantom{Monozigotic} \textbf{Tipus de bessons} \\  
\begin{array}{lr|cc|c}
 &amp; &amp; \textrm{Monozigòtics} &amp; \textrm{Dizigòtics} &amp; \textrm{Total} \\ \hline
 \textbf{Casos} &amp; \textrm{Un}  &amp; 23 &amp; 35 &amp; 58\\
 \textbf{de SIDS} &amp; \textrm{Dos} &amp; 1 &amp; 2 &amp; 3\\\hline
 &amp; \textrm{Total}  &amp; 24 &amp; 37 &amp; 
\end{array}
\end{array}
\]</span></p>
<p>Emprarem el test de Fisher, ja que ni les mostres ni els nombres de “fracassos” no són prou grans per poder emprar el test <span class="math inline">\(\chi^2\)</span>.</p>
<p><em>p-valor</em>:
<span class="math display">\[
P(H(58,3,24)\leqslant 23) =\texttt{phyper(23,58,3,24)}=0.7841
\]</span></p>
<p><em>Conclusió</em>: No hem obtingut evidència estadísticament significativa que la SIDS tengui un component genètic (test de Fisher, p-valor 0.78).</p>
<p>Amb R el test de Fisher està implementat en la funció</p>
<div class="sourceCode" id="cb275"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb275-1" data-line-number="1"><span class="kw">fisher.test</span>(M,<span class="dt">alternative=</span>...,<span class="dt">conf.level=</span>...)</a></code></pre></div>
<p>on <code>M</code> és la matriu de freqüències de la mostra tal i com l’hem donada: fileres Èxits i Fracassos (en aquest ordre) i columnes <span class="math inline">\(X_1\)</span> i <span class="math inline">\(X_2\)</span>.</p>
<p>En el nostre exemple, entraríem</p>
<div class="sourceCode" id="cb276"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb276-1" data-line-number="1">M=<span class="kw">matrix</span>(<span class="kw">c</span>(<span class="dv">23</span>,<span class="dv">35</span>,<span class="dv">1</span>,<span class="dv">2</span>), <span class="dt">nrow=</span><span class="dv">2</span>, <span class="dt">byrow=</span><span class="ot">TRUE</span>)</a>
<a class="sourceLine" id="cb276-2" data-line-number="2"><span class="kw">fisher.test</span>(M,<span class="dt">alternative=</span><span class="st">&quot;less&quot;</span>)</a></code></pre></div>
<pre><code>## 
##  Fisher&#39;s Exact Test for Count Data
## 
## data:  M
## p-value = 0.7841
## alternative hypothesis: true odds ratio is less than 1
## 95 percent confidence interval:
##   0.00000 39.73954
## sample estimates:
## odds ratio 
##   1.308589</code></pre>
<p>Obtenim el mateix p-valor, i un interval de confiança del 95% que va de 0 a 39.7. Ja us podeu imaginar que aquest interval de confiança no pot ser per a <span class="math inline">\(p_1-p_2\)</span>.</p>

<div class="rmdcaution">
De fet, la funció <code>fisher.test</code> no compara <span class="math inline">\(p_1\)</span> i <span class="math inline">\(p_2\)</span>, sinó les seves <strong>odds</strong> (<strong>oportunitats</strong>; en castellà, també <em>momios</em>)
<span class="math display">\[
\frac{p_1}{1-p_1}\text{ i }\frac{p_2}{1-p_2}.
\]</span>
L’interval de confiança que dóna és per al quocient d’aquestes <em>odds</em>: la seva <strong>odds ratio</strong> (<strong>OR</strong>, <strong>raó d’oportunitats</strong>; en castellà, també <em>razón de momios</em>).
</div>

<p>Fem un incís sobre les <em>odds</em>. Les <strong>odds</strong> d’un esdeveniment <span class="math inline">\(A\)</span> són
<span class="math display">\[
\text{Odds}(A)=\frac{P(A)}{P(A^c)}=\frac{P(A)}{1-P(A)}
\]</span>
i indiquen <strong>quantes vegades és més probable <span class="math inline">\(A\)</span> que “no <span class="math inline">\(A\)</span>”</strong>.</p>
<p>Per exemple:</p>
<ul>
<li><p>Si <span class="math inline">\(P(A)=0.3\)</span>, <span class="math inline">\(\text{Odds}(A)=0.3/0.7=0.43\)</span></p></li>
<li><p>Si <span class="math inline">\(P(A)=0\)</span>, <span class="math inline">\(\text{Odds}(A)=0\)</span></p></li>
<li><p>Si <span class="math inline">\(P(A)=0.5\)</span>, <span class="math inline">\(\text{Odds}(A)=1\)</span></p></li>
<li><p>Si <span class="math inline">\(P(A)=1\)</span>, <span class="math inline">\(\text{Odds}(A)=\infty\)</span></p></li>
</ul>

<div class="rmdnote">
<p>Les <em>odds</em> d’<span class="math inline">\(A\)</span> se solen interpretar en termes d’apostes. Per desgràcia, si no estau acostumats a apostar, per exemple, a les carreres de trotons, aquesta interpretació no us aclarirà gaire. Però ho intentarem.</p>
<p>Suposem que <span class="math inline">\(\text{Odds}(A)=m\)</span>, és a dir, que <span class="math inline">\(P(A)=m\cdot P(A^c)\)</span>, i suposem que:</p>
<ul>
<li><p>Per cada euro que jugueu a <span class="math inline">\(A^c\)</span>, la casa d’apostes us en paga 1 si passa <span class="math inline">\(A^c\)</span> i 0 si passa <span class="math inline">\(A\)</span></p></li>
<li><p>Per cada euro que jugueu a <span class="math inline">\(A\)</span>, la casa d’apostes us en paga <span class="math inline">\(R\)</span> si passa <span class="math inline">\(A\)</span> i 0 si passa <span class="math inline">\(A^c\)</span></p></li>
</ul>
<p>Això se sol abreviar dient que <strong>les apostes a favor d’<span class="math inline">\(A\)</span> es paguen <span class="math inline">\(R\)</span> a 1</strong>: per cada euro que es paga si “guanya” <span class="math inline">\(A^c\)</span>, es paguen <span class="math inline">\(R\)</span> euros si “guanya” <span class="math inline">\(A\)</span>.</p>
<p>Què ha de valer <span class="math inline">\(R\)</span> per que si jugau 1 euro a <span class="math inline">\(A\)</span>, el que esperau guanyar sigui el mateix que si jugau 1 euro a <span class="math inline">\(A^c\)</span>? (Es diu en aquest cas que les apostes estan <strong>equilibrades</strong>.)</p>
<p>Vegem. Si jugau 1 euro a <span class="math inline">\(A\)</span>, esperau guanyar <span class="math inline">\(R\cdot P(A)=R\cdot m\cdot P(A^c)\)</span>, i si jugau 1 euro a <span class="math inline">\(A^c\)</span> esperau guanyar <span class="math inline">\(1\cdot P(A^c)\)</span>. Per tant, si aquests guanys esperats han de ser iguals, ha de passar <span class="math inline">\(R\cdot m=1\)</span>, és a dir <span class="math inline">\(R=1/m\)</span>.</p>
Així, per exemple, si <span class="math inline">\(\text{Odds}(A)=2\)</span> (la probabilitat que passi <span class="math inline">\(A\)</span> és 2 vegades la de que passi <span class="math inline">\(A^c\)</span>), per que les apostes estiguin equilibrades s’han de pagar 0.5 a 1 a favor d’<span class="math inline">\(A\)</span>: per cada euro que es paga si guanya <span class="math inline">\(A^c\)</span>, s’ha de pagar mig euro si guanya <span class="math inline">\(A\)</span>.
</div>

<p>Fixau-vos que si coneixeu <span class="math inline">\(\text{Odds}(A)\)</span>, podeu aïllar <span class="math inline">\(P(A)\)</span>. Per exemple si <span class="math inline">\(\text{Odds}(A)=0.6\)</span>
<span class="math display">\[
\begin{array}{l}
0.6=\dfrac{P(A)}{1-P(A)}\Rightarrow 0.6-0.6P(A)=P(A)\\
\qquad \Rightarrow 0.6=1.6P(A)\Rightarrow P(A)=\dfrac{0.6}{1.6}=0.375
\end{array}
\]</span>
En general
<span class="math display">\[
P(A)=\dfrac{\text{Odds}(A)}{1+\text{Odds}(A)}
\]</span></p>
<p>D’aquí podeu deduir fàcilment que
<span class="math display">\[
\begin{array}{c}
\text{Odds}(A)&lt;\text{Odds}(B)\Longleftrightarrow P(A)&lt;P(B)\\ 
\text{Odds}(A)&gt;\text{Odds}(B)\Longleftrightarrow P(A)&gt;P(B)\\ 
\text{Odds}(A)=\text{Odds}(B)\Longleftrightarrow P(A)=P(B)
\end{array}
\]</span>
i per tant comparant les probabilitats o les <em>odds</em> de dos esdeveniments obteniu la mateixa informació sobre quin és més probable.</p>
<p>La <em>odds ratio</em> de <span class="math inline">\(A\)</span> i <span class="math inline">\(B\)</span> és
<span class="math display">\[
  \text{OR}(A,B)=\frac{\text{Odds}(A)}{\text{Odds}(B)}
\]</span></p>
<p>Aquest quocient sol ser mal d’interpretar, i per això precisament sempre que poguem evitarem el test exacte de Fisher.</p>

<div class="rmdnote">
<p>En tot cas, fixau-vos que si <span class="math inline">\(\text{OR}(A,B)=r\)</span>, és a dir, <span class="math inline">\(\text{Odds}(A)=r\cdot \text{Odds}(B)\)</span>, i les apostes a favor de <span class="math inline">\(A\)</span> es paguen <span class="math inline">\(R_A\)</span> a 1 i les de <span class="math inline">\(B\)</span> es paguen <span class="math inline">\(R_B\)</span> a 1 i les dues estan equilibrades, aleshores
<span class="math display">\[
\frac{1}{R_A}=r\cdot \frac{1}{R_B}\Longrightarrow R_B=r\cdot R_A
\]</span></p>
Per tant, si <span class="math inline">\(\text{OR}(A,B)=r\)</span> i les apostes a favor de <span class="math inline">\(B\)</span> es paguen <span class="math inline">\(R_B\)</span> a 1, les apostes a favor d’<span class="math inline">\(A\)</span> s’han de pagar <span class="math inline">\(rR_B\)</span> a 1.
</div>


<div class="rmdimportant">
<p><span class="math inline">\(\text{OR}(A,B)=1\)</span> si, i només si, <span class="math inline">\(\text{Odds}(A)=\text{Odds}(B)\)</span> i per tant, pel que acabam de dir, si, i només si, <span class="math inline">\(P(A)=P(B)\)</span>.</p>
Per tant, si l’interval de confiança per a la <em>odds ratio</em> que dóna la funció <code>fisher.test</code> conté l’1, no podem rebutjar que les dues proporcions poblacionals d’èxit siguin iguals.
</div>


<div class="example">
<p><span id="exm:unnamed-chunk-354" class="example"><strong>Exemple 5.17  </strong></span>Si, per exemple, la <em>odds ratio</em> de <span class="math inline">\(A\)</span> i <span class="math inline">\(B\)</span> és
<span class="math display">\[
  \text{OR}(A,B)=\frac{\text{Odds}(A)}{\text{Odds}(B)}=1.5
\]</span>
i per tant <span class="math inline">\(\text{Odds}(A)=1.5\cdot \text{Odds}(B)\)</span>:</p>
</div>

<ul>
<li><p>Com que en particular <span class="math inline">\(\text{Odds}(A)&gt; \text{Odds}(B)\)</span>, podeu concloure que <span class="math inline">\(P(A)&gt;P(B)\)</span></p></li>
<li><p>Però el fet que <span class="math inline">\(\text{Odds}(A)=1.5\cdot \text{Odds}(B)\)</span> <strong>no implica</strong> que <span class="math inline">\(P(A)=1.5P(B)\)</span>. De fet, d’aquest valor de <span class="math inline">\(OR(A,B)\)</span> no podeu deduir el valor de <span class="math inline">\(P(A)/P(B)\)</span>. Intentau-ho si no ens creieu.</p></li>
</ul>

<div class="example">
<p><span id="exm:unnamed-chunk-355" class="example"><strong>Exemple 5.18  </strong></span>Si realitzam el contrast de l’Exemple <a href="contrastos-dhipòtesis-dun-i-dos-paràmetres.html#exm:allel1">5.15</a> amb el test <span class="math inline">\(\chi^2\)</span>, obtenim</p>
</div>

<div class="sourceCode" id="cb278"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb278-1" data-line-number="1"><span class="kw">prop.test</span>(<span class="kw">c</span>(<span class="dv">20</span>,<span class="dv">12</span>),<span class="kw">c</span>(<span class="dv">100</span>,<span class="dv">50</span>),<span class="dt">alternative=</span><span class="st">&quot;two.sided&quot;</span>,<span class="dt">correct=</span><span class="ot">FALSE</span>)</a></code></pre></div>
<pre><code>## 
##  2-sample test for equality of proportions without continuity
##  correction
## 
## data:  c(20, 12) out of c(100, 50)
## X-squared = 0.3178, df = 1, p-value = 0.5729
## alternative hypothesis: two.sided
## 95 percent confidence interval:
##  -0.1819858  0.1019858
## sample estimates:
## prop 1 prop 2 
##   0.20   0.24</code></pre>
<ul>
<li><p>El p-valor 0.5729 no ens permet rebutjar que les proporcions de mallorquins i menorquins amb l’al·lel objecte d’estudi siguin iguals</p></li>
<li><p>L’IC 95% per a la diferència de proporcions va de -0.18 a 0.1: com que conté el 0, no podem rebutjar amb aquest nivell de confiança que les proporcions siguin iguals</p></li>
<li><p>La diferència de proporcions mostrals <span class="math inline">\(p_1-p_2\)</span> ha estat <span class="math inline">\(0.2-0.24=-0.04\)</span>: la proporció de menorquins amb l’al·lel a la nostra mostra ha estat 4 punts percentuals més gran que la dels mallorquins</p></li>
</ul>
<p>Si ara l’efectuam amb el test de Fisher:</p>
<div class="sourceCode" id="cb280"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb280-1" data-line-number="1">M.A=<span class="kw">matrix</span>(<span class="kw">c</span>(<span class="dv">20</span>,<span class="dv">12</span>,<span class="dv">80</span>,<span class="dv">38</span>), <span class="dt">nrow=</span><span class="dv">2</span>, <span class="dt">byrow=</span><span class="ot">TRUE</span>)</a>
<a class="sourceLine" id="cb280-2" data-line-number="2"><span class="kw">fisher.test</span>(M.A,<span class="dt">alternative=</span><span class="st">&quot;two.sided&quot;</span>)</a></code></pre></div>
<pre><code>## 
##  Fisher&#39;s Exact Test for Count Data
## 
## data:  M.A
## p-value = 0.673
## alternative hypothesis: true odds ratio is not equal to 1
## 95 percent confidence interval:
##  0.3287521 1.9742955
## sample estimates:
## odds ratio 
##  0.7929466</code></pre>
<ul>
<li>El p-valor 0.673 no ens permet rebutjar que les <strong>odds</strong> de tenir aquest al·lel entre els mallorquins i els menorquins siguin iguals; com que igualtat d’<em>odds</em> és equivalent a igualtat de probabilitats, no podem rebutjar que els mallorquins i menorquins tenguin la mateixa probabilitat de tenir l’al·lel objecte d’estudi</li>
</ul>

<div class="rmdnote">
<p>Vegem que coincideix amb el p-valor del contrast bilateral de Fisher que hem explicat. Recordem la taula de dades:
<span class="math display">\[
\begin{array}{r|cc }
  &amp; \textrm{Mallorca} &amp; \textrm{Menorca}  \\\hline
\textrm{Present} &amp; 20 &amp; 12 \\
\textrm{Absent} &amp; 80 &amp; 38   \\\hline 
\textrm{Total} &amp; 100 &amp; 50   
\end{array}
\]</span></p>
Si la hipòtesi nul·la és vertadera, el nombre <span class="math inline">\(N_{1,1}\)</span> de mallorquins amb l’al·lel en una mostra com la nostra té distribució hipergeomètrica <span class="math inline">\(H(32,118,100)\)</span> i per tant valor esperat <span class="math inline">\(100\cdot 32/150=21.333\)</span>. Com que a la nostra mostra <span class="math inline">\(n_{1,1}=20\)</span>, el p-valor és
<span class="math display">\[
\begin{array}{l}
P(|N_{1,1}-21.333|\geqslant 1.333)=P(N_{1,1}\leqslant 20\text{ o }N_{1,1}\geqslant 22.666)\\
\qquad= P(N_{1,1}\leqslant 20\text{ o }N_{1,1}\geqslant 23)\qquad \text{(perquè $N_{1,1}\in \mathbb{N}$)}\\
\qquad= P(N_{1,1}\leqslant 20)+P(N_{1,1}\geqslant 23)\\
\qquad= \texttt{phyper(20,32,118,100)+(1-phyper(22,32,118,100))}\\
\qquad=0.6729552
\end{array}
\]</span>
i
</div>

<div class="sourceCode" id="cb282"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb282-1" data-line-number="1"><span class="kw">fisher.test</span>(M.A,<span class="dt">alternative=</span><span class="st">&quot;two.sided&quot;</span>)<span class="op">$</span>p.value</a></code></pre></div>
<pre><code>## [1] 0.6729552</code></pre>
<ul>
<li><p>L’IC 95% per a la <strong>odds ratio</strong> (per al quocient de les <em>odds</em>) va de 0.33 a 1.97: com que conté l’1, no podem rebutjar amb aquest nivell de confiança que la <em>odds ratio</em> sigui 1; és a dir, no podem rebutjar que les <em>odds</em> siguin iguals; és a dir, no podem rebutjar que les proporcions siguin iguals</p></li>
<li><p>El <em>quocient d’odds mostrals</em> (la <strong>odds ratio mostral</strong>) ha estat 0.79: a la nostra mostra, les <em>odds</em> que un mallorquí tengués l’al·lel han estat 0.79 vegades (un 21% més petites que) les d’un menorquí; però això no ens dóna cap relació numèrica entre les proporcions mostrals de mallorquins i menorquins amb l’al·lel.</p></li>
</ul>
</div>
</div>
<div id="contrastos-per-a-2-proporcions-emprant-mostres-aparellades" class="section level3">
<h3><span class="header-section-number">5.3.3</span> Contrastos per a 2 proporcions emprant mostres aparellades</h3>
<p>Siguin una altra vegada <span class="math inline">\(X_1\)</span> i <span class="math inline">\(X_2\)</span> dues variables aleatòries Bernoulli de paràmetres poblacionals <span class="math inline">\(p_1\)</span> i <span class="math inline">\(p_2\)</span>.
Seguim volent realitzar un contrast
<span class="math display">\[
\left\{\begin{array}{l}
H_{0}:p_1=p_2\\ 
H_{1}:p_1\neq p_2\text{ o }p_1&gt; p_2\text{ o }p_1&lt; p_2
\end{array}
\right.
\]</span>
però ara les mesuram sobre els subjectes d’una mateixa mostra, o sobre els subjectes de dues mostres aparellades, de mida <span class="math inline">\(n\)</span>.
Suposem que tenim els resultats en una taula</p>
<p><span class="math display">\[
\begin{array}{c}
\hphantom{Variablesssss}  \text{Variable $X_2$}\\
\begin{array}{r|cc}
\text{Variable $X_1$} &amp;\text{Èxit} &amp; \text{Fracàs} \\  \hline
\text{Èxit} &amp; a &amp; b \\
\text{Fracàs} &amp; c &amp; d\\ 
\end{array}
\end{array}
\]</span>
on cada entrada representa el nombre de subjectes (o parelles) que satisfan les condicions de la filera i la columna.</p>
<p>En aquest cas tenim dues opcions:</p>
<ul>
<li>Realitzar un test de McNemar, que només serveix per a contrastos bilaterals i a més requereix algunes condicions sobre les dues mostres</li>
<li>Realitzar un test binomial, que es pot emprar sempre però no dóna la informació exactament com la voldríem</li>
</ul>
<div id="test-de-mcnemar" class="section level4 unnumbered">
<h4>Test de McNemar</h4>
<p>Quan el test és <strong>bilateral</strong>, si el nombre de <strong>casos discordants</strong> (<span class="math inline">\(b+c\)</span> en la taula anterior) és prou gran (posem, més gran o igual que 25), es pot emprar el <strong>test de McNemar</strong>, que empra l’estadístic de contrast
<span class="math display">\[
Z^2=\frac{(b-c)^2}{b+c}
\]</span>
el qual, si se satisfan les condicions esmentades, segueix aproximadament una distribució <span class="math inline">\(\chi^2_1\)</span> si <span class="math inline">\(H_0\)</span> és vertadera.</p>
<p>En aquest test se rebutja la hipòtesi nul·la si <span class="math inline">\(b\)</span> i <span class="math inline">\(c\)</span> són prou diferents i per tant, malgrat ser un contrast bilateral, es pren com a p-valor <span class="math inline">\(P(Z^2\geqslant Z_0^2)\)</span>, on <span class="math inline">\(Z_0^2\)</span> és el valor de l’estadístic a la nostra mostra i <span class="math inline">\(Z^2\)</span> té distribució <span class="math inline">\(\chi_1^2\)</span>.</p>
<p>Aquest test està implementat en R en la funció <code>mcnemar.test</code>, que s’aplica a la taula de freqüències absolutes de la mostra tal i com l’hem donada.</p>

<div class="example">
<p><span id="exm:migranya" class="example"><strong>Exemple 5.19  </strong></span>En un assaig clínic es volgué comparar l’efectivitat d’un fàrmac nou contra la migranya amb la d’un placebo.
Es prengué una mostra de 500 persones afectades per migranya. A cada una, a l’atzar, se li administrà el fàrmac o el placebo. Se’ls demanà si havien notat alleujament en el dolor. Al cap d’un temps, als mateixos individus se’ls subministrà l’altre tractament (fàrmac als que havien rebut placebo, placebo als que havien rebut fàrmac) i se’ls tornà a demanar si havien notat o no millora.</p>
</div>

<p>Els resultats varen ser:
<span class="math display">\[
\begin{array}{c}
\hphantom{Variables}  \text{Placebo}\\
\begin{array}{r|cc}
\text{Fàrmac} &amp;\text{Sí} &amp; \text{No} \\  \hline
\text{Sí} &amp; 150 &amp; 41  \\
\text{No} &amp; 19 &amp; 285\\ 
\end{array}
\end{array}
\]</span>
on “Sí” indica que el malalt va dir que sí que havia notat alleujament en el dolor.</p>
<p><em>Variables d’interès</em>:</p>
<ul>
<li><p><span class="math inline">\(X_1\)</span>: “Prenem un malalt, li administram el fàrmac i li demanam si nota millora del dolor”. És Bernoulli amb proporció poblacional d’èxit <span class="math inline">\(p_1\)</span></p></li>
<li><p><span class="math inline">\(X_2\)</span>: “Prenem un malalt, li administram el placebo i li demanam si nota millora del dolor”. És Bernoulli amb proporció poblacional d’èxit <span class="math inline">\(p_2\)</span></p></li>
</ul>
<p><em>Contrast</em>: Com que la mostra i el nombre de casos discordants són prou grans, podem emprar el test de McNemar, però aleshores el contrast ha de ser bilateral
<span class="math display">\[
\left\{\begin{array}{l}
H_0:p_1=p_2\\
H_1:p_1\neq  p_2
\end{array}\right.
\]</span></p>
<p><em>Estadístic de contrast</em>:
<span class="math display">\[
Z^2=\frac{(b-c)^2}{b+c}
\]</span>
que segueix una distribució aproximadament <span class="math inline">\(\chi_1^2\)</span> si <span class="math inline">\(p_1=p_2\)</span>.</p>
<p><em>Valor sobre la nostra mostra</em>: <span class="math inline">\(Z_0^2=(41-19)^2/(41+19)=8.067\)</span></p>
<p><em>p-valor</em>: <span class="math inline">\(P(Z^2\geqslant 8.067)=\texttt{1-pchisq(8.067,1)}=0.0045\)</span></p>
<p><em>Conclusió</em>: Hem obtingut evidència estadísticament significativa que la taxa d’efectivitat del placebo i del fàrmac són diferents (test de McNemar, p-valor 0.0045).</p>
<p>I ara, com que la taxa d’efectivitat del fàrmac ha estat superior a la del placebo (191/500 contra 169/500), faríem la petita trampa de concloure que la diferència entre aquestes taxes d’efectivitat és perquè el fàrmac es més efectiu.</p>
<p>Amb R, entraríem</p>
<div class="sourceCode" id="cb284"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb284-1" data-line-number="1">Dades.M=<span class="kw">matrix</span>(<span class="kw">c</span>(<span class="dv">150</span>,<span class="dv">41</span>,<span class="dv">19</span>,<span class="dv">285</span>), <span class="dt">nrow=</span><span class="dv">2</span>, <span class="dt">byrow=</span><span class="ot">TRUE</span>)</a>
<a class="sourceLine" id="cb284-2" data-line-number="2"><span class="kw">mcnemar.test</span>(Dades.M)</a></code></pre></div>
<pre><code>## 
##  McNemar&#39;s Chi-squared test with continuity correction
## 
## data:  Dades.M
## McNemar&#39;s chi-squared = 7.35, df = 1, p-value = 0.006706</code></pre>
<p>Ups! No ha donat el mateix estadístic ni el mateix p-valor. Això passa perquè R també aplica per defecte una correcció de continuïtat al test de McNemar. El que nosaltres hem explicat correspon a</p>
<div class="sourceCode" id="cb286"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb286-1" data-line-number="1"><span class="kw">mcnemar.test</span>(Dades.M,<span class="dt">correct=</span><span class="ot">FALSE</span>)</a></code></pre></div>
<pre><code>## 
##  McNemar&#39;s Chi-squared test
## 
## data:  Dades.M
## McNemar&#39;s chi-squared = 8.0667, df = 1, p-value = 0.004509</code></pre>
</div>
<div id="test-binomial-exacte-1" class="section level4 unnumbered">
<h4>Test binomial exacte</h4>
<p>Si no podeu emprar el test de McNemar, sempre podeu emprar el <strong>test binomial exacte</strong> següent.</p>
<p>Considerau la taula de probabilitats poblacionals</p>
<p><span class="math display">\[
\begin{array}{c}
\hphantom{Variablesssss}  \text{Variable $X_2$}\\
\begin{array}{r|cc}
\text{Variable $X_1$} &amp;\text{Èxit} &amp; \text{Fracàs} \\  \hline
\text{Èxit} &amp; p_{11} &amp; p_{10} \\
\text{Fracàs} &amp; p_{01} &amp; p_{00}
\end{array}
\end{array}
\]</span></p>
<p>Llavors
<span class="math display">\[
p_1=p_{11}+p_{10},\ p_2=p_{11}+p_{01}
\]</span>
i per tant
<span class="math display">\[
\begin{array}{l}
\displaystyle p_1=p_2\Longleftrightarrow   p_{10}=p_{01}\Longleftrightarrow \frac{p_{10}}{p_{10}+p_{01}}=0.5\\[1ex]
\displaystyle p_1\neq p_2\Longleftrightarrow   p_{10}\neq p_{01}\Longleftrightarrow \frac{p_{10}}{p_{10}+p_{01}}\neq 0.5\\[1ex]
\displaystyle p_1&lt; p_2\Longleftrightarrow   p_{10}&lt; p_{01}\Longleftrightarrow \frac{p_{10}}{p_{10}+p_{01}}&lt;0.5\\[1ex]
\displaystyle p_1&gt; p_2\Longleftrightarrow   p_{10}&gt; p_{01}\Longleftrightarrow \frac{p_{10}}{p_{10}+p_{01}}&gt;0.5\\[1ex]
\end{array}
\]</span></p>
<p>Això permet traduir un contrast sobre <span class="math inline">\(p_1\)</span> i <span class="math inline">\(p_2\)</span> pbinom{27,71,0.5)</p>

<div class="example">
<p><span id="exm:unnamed-chunk-362" class="example"><strong>Exemple 5.20  </strong></span>Tornem a la situació de l’Exemple <a href="contrastos-dhipòtesis-dun-i-dos-paràmetres.html#exm:migranya">5.19</a>. Ara volem fer el contrast que realment ens interessa, que és si la taxa d’efectivitat del fàrmac és més gran que la del placebo:</p>
</div>

<p><span class="math display">\[
\left\{\begin{array}{l}
H_0:p_1=p_2\\
H_1:p_1&gt;p_2
\end{array}\right.
\]</span></p>
<p>Dient <span class="math inline">\(p=p_{10}/(p_{10}+p_{01})\)</span>, el traduïm en
<span class="math display">\[
\left\{\begin{array}{l}
H_0:p=0.5\\
H_1:p&gt; 0.5
\end{array}\right.
\]</span></p>
<p>Les dades eren
<span class="math display">\[
\begin{array}{c}
\hphantom{Variables}  \text{Placebo}\\
\begin{array}{r|cc}
\text{Fàrmac} &amp;\text{Sí} &amp; \text{No} \\  \hline
\text{Sí} &amp; 150 &amp; 41  \\
\text{No} &amp; 19 &amp; 285
\end{array}
\end{array}
\]</span></p>
<p>I per tant al contrast sobre <span class="math inline">\(p\)</span> emprarem la mostra de 60 casos discordants on 41 són Èxits. Ho fen directament amb R:</p>
<div class="sourceCode" id="cb288"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb288-1" data-line-number="1"><span class="kw">binom.test</span>(<span class="dv">41</span>, <span class="dv">60</span>, <span class="dt">p=</span><span class="fl">0.5</span>, <span class="dt">alternative=</span><span class="st">&quot;greater&quot;</span>)</a></code></pre></div>
<pre><code>## 
##  Exact binomial test
## 
## data:  41 and 60
## number of successes = 41, number of trials = 60, p-value = 0.003109
## alternative hypothesis: true probability of success is greater than 0.5
## 95 percent confidence interval:
##  0.5708296 1.0000000
## sample estimates:
## probability of success 
##              0.6833333</code></pre>
<p><em>Conclusió</em>: Hem obtingut evidència estadísticament significativa que el fàrmac té una taxa d’efectivitat més gran que el placebo (test binomial, p-valor 0.003).</p>

</div>
</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="contrastos-dhipòtesis-generalitats.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="contrastos-de-bondat-dajust.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "subsection",
"download": ["pdf", "epub"]
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
