<!DOCTYPE html>
<html >

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Tema 8 Introducció a l’estadística multidimensional | Matemàtiques II</title>
  <meta name="description" content="Apunts Matemàtiques II bookdown::gitbook.">
  <meta name="generator" content="bookdown  and GitBook 2.6.7">

  <meta property="og:title" content="Tema 8 Introducció a l’estadística multidimensional | Matemàtiques II" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Apunts Matemàtiques II bookdown::gitbook." />
  <meta name="github-repo" content="cescrossello/MatesII" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Tema 8 Introducció a l’estadística multidimensional | Matemàtiques II" />
  
  <meta name="twitter:description" content="Apunts Matemàtiques II bookdown::gitbook." />
  



<meta name="date" content="2020-04-15">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  
  
<link rel="prev" href="contrastos-dindependencia-i-homogeneitat.html">
<link rel="next" href="anova.html">
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />









<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(data-line-number);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Bioestadística II</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Presentació</a></li>
<li class="part"><span><b>Part II: Estadística inferencial</b></span></li>
<li class="chapter" data-level="1" data-path="repas-de-la-distribucio-normal.html"><a href="repas-de-la-distribucio-normal.html"><i class="fa fa-check"></i><b>1</b> Repàs de la distribució normal</a><ul>
<li class="chapter" data-level="1.1" data-path="repas-de-la-distribucio-normal.html"><a href="repas-de-la-distribucio-normal.html#propietats-de-la-distribucio-normal"><i class="fa fa-check"></i><b>1.1</b> Propietats de la distribució normal</a></li>
<li class="chapter" data-level="1.2" data-path="repas-de-la-distribucio-normal.html"><a href="repas-de-la-distribucio-normal.html#amb-r"><i class="fa fa-check"></i><b>1.2</b> Amb R</a></li>
<li class="chapter" data-level="1.3" data-path="repas-de-la-distribucio-normal.html"><a href="repas-de-la-distribucio-normal.html#combinacions-lineals"><i class="fa fa-check"></i><b>1.3</b> Combinacions lineals</a></li>
<li class="chapter" data-level="1.4" data-path="repas-de-la-distribucio-normal.html"><a href="repas-de-la-distribucio-normal.html#intervals-de-referencia"><i class="fa fa-check"></i><b>1.4</b> Intervals de referència</a></li>
<li class="chapter" data-level="1.5" data-path="repas-de-la-distribucio-normal.html"><a href="repas-de-la-distribucio-normal.html#el-z-score"><i class="fa fa-check"></i><b>1.5</b> El z-score</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="estimacio-puntual.html"><a href="estimacio-puntual.html"><i class="fa fa-check"></i><b>2</b> Estimació puntual</a><ul>
<li class="chapter" data-level="2.1" data-path="estimacio-puntual.html"><a href="estimacio-puntual.html#definicions-basiques"><i class="fa fa-check"></i><b>2.1</b> Definicions bàsiques</a></li>
<li class="chapter" data-level="2.2" data-path="estimacio-puntual.html"><a href="estimacio-puntual.html#mitjana-mostral"><i class="fa fa-check"></i><b>2.2</b> Mitjana mostral</a></li>
<li class="chapter" data-level="2.3" data-path="estimacio-puntual.html"><a href="estimacio-puntual.html#proporcio-mostral"><i class="fa fa-check"></i><b>2.3</b> Proporció mostral</a></li>
<li class="chapter" data-level="2.4" data-path="estimacio-puntual.html"><a href="estimacio-puntual.html#variancia-mostral"><i class="fa fa-check"></i><b>2.4</b> Variància mostral</a></li>
<li class="chapter" data-level="2.5" data-path="estimacio-puntual.html"><a href="estimacio-puntual.html#la-t-de-student"><i class="fa fa-check"></i><b>2.5</b> La t de Student</a></li>
<li class="chapter" data-level="2.6" data-path="estimacio-puntual.html"><a href="estimacio-puntual.html#bons-estimadors"><i class="fa fa-check"></i><b>2.6</b> “Bons” estimadors</a><ul>
<li class="chapter" data-level="2.6.1" data-path="estimacio-puntual.html"><a href="estimacio-puntual.html#estimadors-no-esbiaixats"><i class="fa fa-check"></i><b>2.6.1</b> Estimadors no esbiaixats</a></li>
<li class="chapter" data-level="2.6.2" data-path="estimacio-puntual.html"><a href="estimacio-puntual.html#estimadors-eficients"><i class="fa fa-check"></i><b>2.6.2</b> Estimadors eficients</a></li>
<li class="chapter" data-level="2.6.3" data-path="estimacio-puntual.html"><a href="estimacio-puntual.html#estimadors-maxim-versemblants"><i class="fa fa-check"></i><b>2.6.3</b> Estimadors màxim versemblants</a></li>
</ul></li>
<li class="chapter" data-level="2.7" data-path="estimacio-puntual.html"><a href="estimacio-puntual.html#sec:pobl"><i class="fa fa-check"></i><b>2.7</b> Estimació de poblacions</a><ul>
<li class="chapter" data-level="2.7.1" data-path="estimacio-puntual.html"><a href="estimacio-puntual.html#estimacio-de-poblacions-numerades"><i class="fa fa-check"></i><b>2.7.1</b> Estimació de poblacions numerades</a></li>
<li class="chapter" data-level="2.7.2" data-path="estimacio-puntual.html"><a href="estimacio-puntual.html#marca-recaptura"><i class="fa fa-check"></i><b>2.7.2</b> Marca-recaptura</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="intervals-de-confianca.html"><a href="intervals-de-confianca.html"><i class="fa fa-check"></i><b>3</b> Intervals de confiança</a><ul>
<li class="chapter" data-level="3.1" data-path="intervals-de-confianca.html"><a href="intervals-de-confianca.html#definicions-basiques-1"><i class="fa fa-check"></i><b>3.1</b> Definicions bàsiques</a></li>
<li class="chapter" data-level="3.2" data-path="intervals-de-confianca.html"><a href="intervals-de-confianca.html#exemple-interval-de-confianca-del-95-per-a-la-mitjana-duna-variable-aleatoria-normal"><i class="fa fa-check"></i><b>3.2</b> Exemple: Interval de confiança del 95% per a la mitjana d’una variable aleatòria normal</a></li>
<li class="chapter" data-level="3.3" data-path="intervals-de-confianca.html"><a href="intervals-de-confianca.html#interval-de-confianca-per-a-la-mitjana-basat-en-la-t-de-student"><i class="fa fa-check"></i><b>3.3</b> Interval de confiança per a la mitjana basat en la t de Student</a><ul>
<li class="chapter" data-level="" data-path="intervals-de-confianca.html"><a href="intervals-de-confianca.html#la-formula"><i class="fa fa-check"></i>La fórmula</a></li>
<li class="chapter" data-level="" data-path="intervals-de-confianca.html"><a href="intervals-de-confianca.html#algunes-consideracions"><i class="fa fa-check"></i>Algunes consideracions</a></li>
<li class="chapter" data-level="" data-path="intervals-de-confianca.html"><a href="intervals-de-confianca.html#amb-r-1"><i class="fa fa-check"></i>Amb R</a></li>
<li class="chapter" data-level="" data-path="intervals-de-confianca.html"><a href="intervals-de-confianca.html#calcul-de-la-mida-de-la-mostra-per-fixar-lerror"><i class="fa fa-check"></i>Càlcul de la mida de la mostra per fixar l’error</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="intervals-de-confianca.html"><a href="intervals-de-confianca.html#intervals-de-confianca-per-a-proporcions"><i class="fa fa-check"></i><b>3.4</b> Intervals de confiança per a proporcions</a><ul>
<li class="chapter" data-level="" data-path="intervals-de-confianca.html"><a href="intervals-de-confianca.html#metode-exacte-de-clopper-pearson"><i class="fa fa-check"></i>Mètode “exacte” de Clopper-Pearson</a></li>
<li class="chapter" data-level="" data-path="intervals-de-confianca.html"><a href="intervals-de-confianca.html#metode-de-wilson"><i class="fa fa-check"></i>Mètode de Wilson</a></li>
<li class="chapter" data-level="" data-path="intervals-de-confianca.html"><a href="intervals-de-confianca.html#metode-de-laplace"><i class="fa fa-check"></i>Mètode de Laplace</a></li>
<li class="chapter" data-level="" data-path="intervals-de-confianca.html"><a href="intervals-de-confianca.html#mes-exemples"><i class="fa fa-check"></i>Més exemples</a></li>
<li class="chapter" data-level="" data-path="intervals-de-confianca.html"><a href="intervals-de-confianca.html#calcul-de-la-mida-de-la-mostra-per-a-fixar-lerror"><i class="fa fa-check"></i>Càlcul de la mida de la mostra per a fixar l’error</a></li>
</ul></li>
<li class="chapter" data-level="3.5" data-path="intervals-de-confianca.html"><a href="intervals-de-confianca.html#intervals-de-confianca-per-a-la-variancia-duna-variable-normal"><i class="fa fa-check"></i><b>3.5</b> Intervals de confiança per a la variància d’una variable normal</a></li>
<li class="chapter" data-level="3.6" data-path="intervals-de-confianca.html"><a href="intervals-de-confianca.html#poblacions-finites"><i class="fa fa-check"></i><b>3.6</b> “Poblacions finites”</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="contrastos-dhipotesis-generalitats.html"><a href="contrastos-dhipotesis-generalitats.html"><i class="fa fa-check"></i><b>4</b> Contrastos d’hipòtesis: Generalitats</a><ul>
<li class="chapter" data-level="4.1" data-path="contrastos-dhipotesis-generalitats.html"><a href="contrastos-dhipotesis-generalitats.html#hipotesis-nulla-i-alternativa"><i class="fa fa-check"></i><b>4.1</b> Hipòtesis nul·la i alternativa</a></li>
<li class="chapter" data-level="4.2" data-path="contrastos-dhipotesis-generalitats.html"><a href="contrastos-dhipotesis-generalitats.html#sec:moneda"><i class="fa fa-check"></i><b>4.2</b> Un exemple</a></li>
<li class="chapter" data-level="4.3" data-path="contrastos-dhipotesis-generalitats.html"><a href="contrastos-dhipotesis-generalitats.html#sec:pval"><i class="fa fa-check"></i><b>4.3</b> El p-valor</a></li>
<li class="chapter" data-level="4.4" data-path="contrastos-dhipotesis-generalitats.html"><a href="contrastos-dhipotesis-generalitats.html#tipus-derrors"><i class="fa fa-check"></i><b>4.4</b> Tipus d’errors</a></li>
<li class="chapter" data-level="4.5" data-path="contrastos-dhipotesis-generalitats.html"><a href="contrastos-dhipotesis-generalitats.html#sec:exttest"><i class="fa fa-check"></i><b>4.5</b> Exemple: El test t</a></li>
<li class="chapter" data-level="4.6" data-path="contrastos-dhipotesis-generalitats.html"><a href="contrastos-dhipotesis-generalitats.html#recapitulacio"><i class="fa fa-check"></i><b>4.6</b> Recapitulació</a><ul>
<li class="chapter" data-level="" data-path="contrastos-dhipotesis-generalitats.html"><a href="contrastos-dhipotesis-generalitats.html#interval-de-confianca-dun-contrast"><i class="fa fa-check"></i>Interval de confiança d’un contrast</a></li>
<li class="chapter" data-level="" data-path="contrastos-dhipotesis-generalitats.html"><a href="contrastos-dhipotesis-generalitats.html#la-potencia"><i class="fa fa-check"></i>La potència</a></li>
<li class="chapter" data-level="" data-path="contrastos-dhipotesis-generalitats.html"><a href="contrastos-dhipotesis-generalitats.html#el-risc-de-positiu-fals-opcional"><i class="fa fa-check"></i>El risc de positiu fals (Opcional)</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="contrastos-dhipotesis-dun-i-dos-parametres.html"><a href="contrastos-dhipotesis-dun-i-dos-parametres.html"><i class="fa fa-check"></i><b>5</b> Contrastos d’hipòtesis d’un i dos paràmetres</a><ul>
<li class="chapter" data-level="5.1" data-path="contrastos-dhipotesis-dun-i-dos-parametres.html"><a href="contrastos-dhipotesis-dun-i-dos-parametres.html#contrastos-de-mitjanes"><i class="fa fa-check"></i><b>5.1</b> Contrastos de mitjanes</a><ul>
<li class="chapter" data-level="5.1.1" data-path="contrastos-dhipotesis-dun-i-dos-parametres.html"><a href="contrastos-dhipotesis-dun-i-dos-parametres.html#test-t-per-a-una-mitjana"><i class="fa fa-check"></i><b>5.1.1</b> Test t per a una mitjana</a></li>
<li class="chapter" data-level="5.1.2" data-path="contrastos-dhipotesis-dun-i-dos-parametres.html"><a href="contrastos-dhipotesis-dun-i-dos-parametres.html#test-t-per-a-dues-mitjanes"><i class="fa fa-check"></i><b>5.1.2</b> Test t per a dues mitjanes</a></li>
<li class="chapter" data-level="5.1.3" data-path="contrastos-dhipotesis-dun-i-dos-parametres.html"><a href="contrastos-dhipotesis-dun-i-dos-parametres.html#tests-t-amb-r"><i class="fa fa-check"></i><b>5.1.3</b> Tests t amb R</a></li>
<li class="chapter" data-level="5.1.4" data-path="contrastos-dhipotesis-dun-i-dos-parametres.html"><a href="contrastos-dhipotesis-dun-i-dos-parametres.html#exemples"><i class="fa fa-check"></i><b>5.1.4</b> Exemples</a></li>
<li class="chapter" data-level="5.1.5" data-path="contrastos-dhipotesis-dun-i-dos-parametres.html"><a href="contrastos-dhipotesis-dun-i-dos-parametres.html#tests-no-parametrics"><i class="fa fa-check"></i><b>5.1.5</b> Tests no paramètrics</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="contrastos-dhipotesis-dun-i-dos-parametres.html"><a href="contrastos-dhipotesis-dun-i-dos-parametres.html#sec:contrvar"><i class="fa fa-check"></i><b>5.2</b> Contrastos de variàncies</a><ul>
<li class="chapter" data-level="5.2.1" data-path="contrastos-dhipotesis-dun-i-dos-parametres.html"><a href="contrastos-dhipotesis-dun-i-dos-parametres.html#test-chi2-duna-variancia"><i class="fa fa-check"></i><b>5.2.1</b> Test <span class="math inline">\(\chi^2\)</span> d’una variància</a></li>
<li class="chapter" data-level="5.2.2" data-path="contrastos-dhipotesis-dun-i-dos-parametres.html"><a href="contrastos-dhipotesis-dun-i-dos-parametres.html#test-f-per-a-dues-variancies"><i class="fa fa-check"></i><b>5.2.2</b> Test F per a dues variàncies</a></li>
<li class="chapter" data-level="5.2.3" data-path="contrastos-dhipotesis-dun-i-dos-parametres.html"><a href="contrastos-dhipotesis-dun-i-dos-parametres.html#tests-no-parametrics-1"><i class="fa fa-check"></i><b>5.2.3</b> Tests no paramètrics</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="contrastos-dhipotesis-dun-i-dos-parametres.html"><a href="contrastos-dhipotesis-dun-i-dos-parametres.html#contrastos-per-a-proporcions"><i class="fa fa-check"></i><b>5.3</b> Contrastos per a proporcions</a><ul>
<li class="chapter" data-level="5.3.1" data-path="contrastos-dhipotesis-dun-i-dos-parametres.html"><a href="contrastos-dhipotesis-dun-i-dos-parametres.html#contrastos-per-a-una-proporcio"><i class="fa fa-check"></i><b>5.3.1</b> Contrastos per a una proporció</a></li>
<li class="chapter" data-level="5.3.2" data-path="contrastos-dhipotesis-dun-i-dos-parametres.html"><a href="contrastos-dhipotesis-dun-i-dos-parametres.html#contrastos-per-a-2-proporcions-emprant-mostres-independents"><i class="fa fa-check"></i><b>5.3.2</b> Contrastos per a 2 proporcions emprant mostres independents</a></li>
<li class="chapter" data-level="5.3.3" data-path="contrastos-dhipotesis-dun-i-dos-parametres.html"><a href="contrastos-dhipotesis-dun-i-dos-parametres.html#contrastos-per-a-2-proporcions-emprant-mostres-aparellades"><i class="fa fa-check"></i><b>5.3.3</b> Contrastos per a 2 proporcions emprant mostres aparellades</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="contrastos-de-bondat-dajust.html"><a href="contrastos-de-bondat-dajust.html"><i class="fa fa-check"></i><b>6</b> Contrastos de bondat d’ajust</a><ul>
<li class="chapter" data-level="6.1" data-path="contrastos-de-bondat-dajust.html"><a href="contrastos-de-bondat-dajust.html#bondat-dajust"><i class="fa fa-check"></i><b>6.1</b> Bondat d’ajust</a></li>
<li class="chapter" data-level="6.2" data-path="contrastos-de-bondat-dajust.html"><a href="contrastos-de-bondat-dajust.html#test-chi2-de-pearson"><i class="fa fa-check"></i><b>6.2</b> Test <span class="math inline">\(\chi^2\)</span> de Pearson</a><ul>
<li class="chapter" data-level="6.2.1" data-path="contrastos-de-bondat-dajust.html"><a href="contrastos-de-bondat-dajust.html#el-test-basic"><i class="fa fa-check"></i><b>6.2.1</b> El test bàsic</a></li>
<li class="chapter" data-level="6.2.2" data-path="contrastos-de-bondat-dajust.html"><a href="contrastos-de-bondat-dajust.html#metode-de-montecarlo"><i class="fa fa-check"></i><b>6.2.2</b> Mètode de Montecarlo</a></li>
<li class="chapter" data-level="6.2.3" data-path="contrastos-de-bondat-dajust.html"><a href="contrastos-de-bondat-dajust.html#test-chi2-amb-parametres-poblacionals-desconeguts"><i class="fa fa-check"></i><b>6.2.3</b> Test <span class="math inline">\(\chi^2\)</span> amb paràmetres poblacionals desconeguts</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="contrastos-de-bondat-dajust.html"><a href="contrastos-de-bondat-dajust.html#test-de-kolmogorov-smirnov"><i class="fa fa-check"></i><b>6.3</b> Test de Kolmogorov-Smirnov</a></li>
<li class="chapter" data-level="6.4" data-path="contrastos-de-bondat-dajust.html"><a href="contrastos-de-bondat-dajust.html#test-de-kolmogorov-smirnov-lilliefors"><i class="fa fa-check"></i><b>6.4</b> Test de Kolmogorov-Smirnov-Lilliefors</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="contrastos-dindependencia-i-homogeneitat.html"><a href="contrastos-dindependencia-i-homogeneitat.html"><i class="fa fa-check"></i><b>7</b> Contrastos d’independència i homogeneïtat</a><ul>
<li class="chapter" data-level="7.1" data-path="contrastos-dindependencia-i-homogeneitat.html"><a href="contrastos-dindependencia-i-homogeneitat.html#test-chi2-dindependencia"><i class="fa fa-check"></i><b>7.1</b> Test <span class="math inline">\(\chi^2\)</span> d’independència</a></li>
<li class="chapter" data-level="7.2" data-path="contrastos-dindependencia-i-homogeneitat.html"><a href="contrastos-dindependencia-i-homogeneitat.html#test-chi2-dhomogeneitat"><i class="fa fa-check"></i><b>7.2</b> Test <span class="math inline">\(\chi^2\)</span> d’homogeneïtat</a></li>
<li class="chapter" data-level="7.3" data-path="contrastos-dindependencia-i-homogeneitat.html"><a href="contrastos-dindependencia-i-homogeneitat.html#test-chi2-de-tendencia-opcional"><i class="fa fa-check"></i><b>7.3</b> Test <span class="math inline">\(\chi^2\)</span> de tendència (Opcional)</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="introduccio-a-lestadistica-multidimensional.html"><a href="introduccio-a-lestadistica-multidimensional.html"><i class="fa fa-check"></i><b>8</b> Introducció a l’estadística multidimensional</a><ul>
<li class="chapter" data-level="8.1" data-path="introduccio-a-lestadistica-multidimensional.html"><a href="introduccio-a-lestadistica-multidimensional.html#poblacions-vectors-aleatoris"><i class="fa fa-check"></i><b>8.1</b> Poblacions: vectors aleatoris</a><ul>
<li class="chapter" data-level="8.1.1" data-path="introduccio-a-lestadistica-multidimensional.html"><a href="introduccio-a-lestadistica-multidimensional.html#covariancia"><i class="fa fa-check"></i><b>8.1.1</b> Covariància</a></li>
<li class="chapter" data-level="8.1.2" data-path="introduccio-a-lestadistica-multidimensional.html"><a href="introduccio-a-lestadistica-multidimensional.html#correlacio"><i class="fa fa-check"></i><b>8.1.2</b> Correlació</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="introduccio-a-lestadistica-multidimensional.html"><a href="introduccio-a-lestadistica-multidimensional.html#estadistica-descriptiva-mostres"><i class="fa fa-check"></i><b>8.2</b> Estadística descriptiva: Mostres</a><ul>
<li class="chapter" data-level="8.2.1" data-path="introduccio-a-lestadistica-multidimensional.html"><a href="introduccio-a-lestadistica-multidimensional.html#covariancies"><i class="fa fa-check"></i><b>8.2.1</b> Covariàncies</a></li>
<li class="chapter" data-level="8.2.2" data-path="introduccio-a-lestadistica-multidimensional.html"><a href="introduccio-a-lestadistica-multidimensional.html#correlacio-de-pearson"><i class="fa fa-check"></i><b>8.2.2</b> Correlació de Pearson</a></li>
<li class="chapter" data-level="8.2.3" data-path="introduccio-a-lestadistica-multidimensional.html"><a href="introduccio-a-lestadistica-multidimensional.html#correlacio-de-spearman"><i class="fa fa-check"></i><b>8.2.3</b> Correlació de Spearman</a></li>
<li class="chapter" data-level="8.2.4" data-path="introduccio-a-lestadistica-multidimensional.html"><a href="introduccio-a-lestadistica-multidimensional.html#contrastos-de-correlacio"><i class="fa fa-check"></i><b>8.2.4</b> Contrastos de correlació</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="anova.html"><a href="anova.html"><i class="fa fa-check"></i><b>9</b> ANOVA</a><ul>
<li class="chapter" data-level="9.1" data-path="anova.html"><a href="anova.html#nocions-basiques"><i class="fa fa-check"></i><b>9.1</b> Nocions bàsiques</a></li>
<li class="chapter" data-level="9.2" data-path="anova.html"><a href="anova.html#anova-d1-via"><i class="fa fa-check"></i><b>9.2</b> ANOVA d’1 via</a><ul>
<li class="chapter" data-level="9.2.1" data-path="anova.html"><a href="anova.html#contrast-basic"><i class="fa fa-check"></i><b>9.2.1</b> Contrast bàsic</a></li>
<li class="chapter" data-level="9.2.2" data-path="anova.html"><a href="anova.html#amb-r-2"><i class="fa fa-check"></i><b>9.2.2</b> Amb R</a></li>
<li class="chapter" data-level="9.2.3" data-path="anova.html"><a href="anova.html#comparacions-posteriors-per-parelles"><i class="fa fa-check"></i><b>9.2.3</b> Comparacions posteriors per parelles</a></li>
<li class="chapter" data-level="9.2.4" data-path="anova.html"><a href="anova.html#verificacio-de-les-condicions"><i class="fa fa-check"></i><b>9.2.4</b> Verificació de les condicions</a></li>
<li class="chapter" data-level="9.2.5" data-path="anova.html"><a href="anova.html#test-no-parametric"><i class="fa fa-check"></i><b>9.2.5</b> Test no paramètric</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="anova.html"><a href="anova.html#anova-de-blocs"><i class="fa fa-check"></i><b>9.3</b> ANOVA de blocs</a><ul>
<li class="chapter" data-level="9.3.1" data-path="anova.html"><a href="anova.html#contrast-basic-1"><i class="fa fa-check"></i><b>9.3.1</b> Contrast bàsic</a></li>
<li class="chapter" data-level="9.3.2" data-path="anova.html"><a href="anova.html#amb-r-3"><i class="fa fa-check"></i><b>9.3.2</b> Amb R</a></li>
<li class="chapter" data-level="9.3.3" data-path="anova.html"><a href="anova.html#comparacions-posteriors-per-parelles-1"><i class="fa fa-check"></i><b>9.3.3</b> Comparacions posteriors per parelles</a></li>
<li class="chapter" data-level="9.3.4" data-path="anova.html"><a href="anova.html#contrast-no-parametric"><i class="fa fa-check"></i><b>9.3.4</b> Contrast no paramètric</a></li>
</ul></li>
<li class="chapter" data-level="9.4" data-path="anova.html"><a href="anova.html#anova-de-2-vies"><i class="fa fa-check"></i><b>9.4</b> ANOVA de 2 vies</a><ul>
<li class="chapter" data-level="9.4.1" data-path="anova.html"><a href="anova.html#contrast-basic-2"><i class="fa fa-check"></i><b>9.4.1</b> Contrast bàsic</a></li>
<li class="chapter" data-level="9.4.2" data-path="anova.html"><a href="anova.html#amb-r-4"><i class="fa fa-check"></i><b>9.4.2</b> Amb R</a></li>
</ul></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Matemàtiques II</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="introduccio-a-lestadistica-multidimensional" class="section level1">
<h1><span class="header-section-number">Tema 8</span> Introducció a l’estadística multidimensional</h1>
<p>En general, les dades que es recullen en experiments són multidimensionals: mesuram diverses variables aleatòries sobre una mateixa mostra d’individus i organitzam aquesta informació en taules de dades on les fileres representen els individus observats i cada columna correspon a una variable diferent. És a dir, el que fem és avaluar un vector de variables aleatòries (en direm un <strong>vector aleatori</strong>) sobre els individus d’una població. En aquesta lliçó introduïm alguns conceptes nous sobre vectors de variables aleatòries i taules multidimensionals de dades quantitatives.</p>
<div id="poblacions-vectors-aleatoris" class="section level2">
<h2><span class="header-section-number">8.1</span> Poblacions: vectors aleatoris</h2>
<p>Un <strong>vector aleatori de dimensió <span class="math inline">\(p\)</span></strong> és un vector format per <span class="math inline">\(p\)</span> variables aleatòries
<span class="math display">\[
\underline{X}=(X_1,X_2,\ldots,X_p).
\]</span>
Una <strong>realització</strong> de <span class="math inline">\(\underline{X}\)</span> és un vector <span class="math inline">\((x_1,\ldots,x_p)\)</span> format pels valors de <span class="math inline">\(X_1,\ldots,X_p\)</span> sobre un individu. Una <strong>mostra</strong> de <span class="math inline">\(\underline{X}\)</span> és un conjunt de realitzacions. Usualment, organitzam una mostra de <span class="math inline">\(\underline{X}\)</span> per mitjà d’una taula de dades amb les columnes definides per les variables <span class="math inline">\(X_1,\ldots,X_p\)</span> i on cada filera és una realització d’aquestes variables, és a dir, un vector format pels valors de <span class="math inline">\(X_1,\ldots,X_p\)</span> sobre un individu de la mostra.</p>

<div class="example">
<span id="exm:unnamed-chunk-422" class="example"><strong>Exemple 8.1  </strong></span>Si diem <span class="math inline">\(\textit{BMI}\)</span> a la variable aleatòria que dóna l’Índex de Massa Corporal (BMI) d’una persona, <span class="math inline">\(C\)</span> a la variable aleatòria que dóna el nivell de colesterol en mg/dl d’una persona i <span class="math inline">\(E\)</span> a la variable aleatòria que dóna l’edat d’una persona en anys, llavors
<span class="math display">\[
\underline{X}=(\textit{BMI},C,E)
\]</span>
és un <strong>vector aleatori</strong> de dimensió 3. Cada cop que prenem una persona i n’anotam el BMI, el nivell de colesterol i l’edat i organitzam aquestes mesures en aquest ordre en un vector, obtenim una <strong>realització</strong> d’aquest vector aleatori <span class="math inline">\(\underline{X}\)</span>. Llavors,una <strong>mostra</strong> de <span class="math inline">\(\underline{X}\)</span> serà un conjunt de vectors amb el BMI, el nivell de colesterol i l’edat d’un grup de persones de la població. Per exemple
</div>

<table>
<thead>
<tr class="header">
<th align="right">BMI</th>
<th align="right">C</th>
<th align="right">E</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">18.3</td>
<td align="right">170</td>
<td align="right">49</td>
</tr>
<tr class="even">
<td align="right">24.4</td>
<td align="right">202</td>
<td align="right">39</td>
</tr>
<tr class="odd">
<td align="right">24.6</td>
<td align="right">215</td>
<td align="right">50</td>
</tr>
<tr class="even">
<td align="right">24.4</td>
<td align="right">218</td>
<td align="right">44</td>
</tr>
<tr class="odd">
<td align="right">22.2</td>
<td align="right">210</td>
<td align="right">40</td>
</tr>
<tr class="even">
<td align="right">19.5</td>
<td align="right">210</td>
<td align="right">36</td>
</tr>
</tbody>
</table>

<div class="rmdcaution">
<p>No confongueu vector aleatori amb mostra aleatòria. Tot i que tots dos es representen formalment per mitjà de vectors de variables aleatòries,</p>
<ul>
<li><p>En un vector aleatori, en principi totes les variables són diferents i les avaluam sobre el mateix individu, obtenint un vector de mesures d’aquest individu</p></li>
<li><p>En una mostra aleatòria, totes les variables són còpies de la mateixa variable <span class="math inline">\(X\)</span> i les avaluam cada una sobre un individu diferent, obtenint una mostra de valors de <span class="math inline">\(X\)</span></p></li>
</ul>
</div>

<p>Siguin <span class="math inline">\(\underline{X}=(X_1,X_2,\ldots,X_p)\)</span> un vector aleatori i <span class="math inline">\(\mu_i\)</span> i <span class="math inline">\(\sigma_i\)</span> la mitjana i la desviació típica, respectivament, de cada <span class="math inline">\(X_i\)</span>.</p>
<ul>
<li><p>El <strong>valor esperat</strong>, o <strong>vector de mitjanes</strong>, de <span class="math inline">\(\underline{X}\)</span> és el vector format pels valors esperats, o mitjanes, de les seves components:
<span class="math display">\[
E(\underline{X})=(\mu_1,\ldots,\mu_p).
\]</span>
Per abreviar, de vegades indicarem aquest vector simplement amb <span class="math inline">\(\boldsymbol\mu\)</span>.</p></li>
<li><p>El <strong>vector de variàncies</strong> de <span class="math inline">\(\underline{X}\)</span> és el vector format per les variàncies de les seves components:
<span class="math display">\[
\sigma^2(\underline{X})=(\sigma_1^2,\ldots,\sigma_p^2).
\]</span></p></li>
<li><p>El <strong>vector de desviacions típiques</strong> de <span class="math inline">\(\underline{X}\)</span> és el vector format per les desviacions típiques de les seves components:
<span class="math display">\[
\sigma(\underline{X})=(\sigma_1,\ldots,\sigma_p).
\]</span></p></li>
</ul>
<div id="covariancia" class="section level3">
<h3><span class="header-section-number">8.1.1</span> Covariància</h3>
<p>La <strong>covariància</strong> de dues variables <span class="math inline">\(X\)</span> i <span class="math inline">\(Y\)</span> és una mesura del seu comportament conjunt.
Formalment, donades dues variables aleatòries <span class="math inline">\(X,Y\)</span> de mitjanes <span class="math inline">\(\mu_X\)</span> i <span class="math inline">\(\mu_Y\)</span>, respectivament, la seva <strong>covariància</strong> és
<span class="math display">\[
\sigma_{X,Y}=E((X-\mu_X)\cdot ( Y-\mu_Y)).
\]</span>
És fàcil comprovar que
<span class="math display">\[
\sigma_{X,Y}=E(X\cdot Y) -\mu_X\cdot \mu_Y.
\]</span></p>

<div class="rmdcorbes">
En efecte,
<span class="math display">\[
\begin{array}{rl}
\sigma_{X,Y} &amp; =E((X-\mu_X) ( Y-\mu_Y))=
E(XY-\mu_XY-\mu_YX+\mu_X\mu_Y)\\ &amp;
=E(XY)-\mu_XE(Y)-\mu_YE(X)+\mu_X\mu_Y\\ &amp;=
E(XY)-\mu_X\mu_Y-\mu_Y\mu_X+\mu_X\mu_Y
=E(XY)-\mu_X\mu_Y
\end{array}
\]</span>
</div>

<p>La covariància de <span class="math inline">\(X\)</span> i <span class="math inline">\(Y\)</span> pot prendre qualsevol valor real (no com la variància, que sempre és positiva), i mesura el grau de variació conjunta de les variables en el sentit següent. Si quan <span class="math inline">\(X\)</span> pren un valor gran sobre un individu, <span class="math inline">\(Y\)</span> tendeix a també prendre’l gran, i quan <span class="math inline">\(X\)</span> pren un valor petit sobre un individu, <span class="math inline">\(Y\)</span> tendeix a també prendre’l petit, la seva covariància és positiva. Si, en canvi, quan <span class="math inline">\(X\)</span> pren un valor gran sobre un individu, <span class="math inline">\(Y\)</span> tendeix a prendre’l petit i vice versa, la seva covariància és negativa.</p>

<div class="rmdimportant">
<p>El signe de la covariància reflecteix la tendència de la relació entre les variables:</p>
<ul>
<li>Covariància positiva: Si <span class="math inline">\(X\)</span> creix, <span class="math inline">\(Y\)</span> tendeix a créixer, i si <span class="math inline">\(X\)</span> decreix, <span class="math inline">\(Y\)</span> tendeix a decréixer</li>
<li>Covariància negativa: Si <span class="math inline">\(X\)</span> creix, <span class="math inline">\(Y\)</span> tendeix a decréixer, i si <span class="math inline">\(X\)</span> decreix, <span class="math inline">\(Y\)</span> tendeix a créixer</li>
</ul>
</div>

<p><strong>Si <span class="math inline">\(X\)</span> i <span class="math inline">\(Y\)</span> són variables independents, la seva covariància es 0</strong>, perquè en aquest cas <span class="math inline">\(E(X\cdot Y) =\mu_X\mu_Y\)</span> i per tant
<span class="math display">\[
\sigma_{X,Y}=E(X\cdot Y) -\mu_X\cdot \mu_Y=\mu_X\cdot \mu_Y-\mu_X\cdot \mu_Y=0.
\]</span>
El recíproc és fals: <strong>dues variables aleatòries poden tenir covariància 0 i no ser independents</strong>. Vegem un exemple d’aquest darrer fet:</p>

<div class="example">
<p><span id="exm:nocorr" class="example"><strong>Exemple 8.2  </strong></span>Suposem que tenim un dau tetraèdric no trucat amb les cares marcades amb els valors -2, -1, 1 i 2. Siguin <span class="math inline">\(X\)</span> la variable aleatòria que consisteix a llançar el dau i anotar el resultat, i <span class="math inline">\(Y\)</span> la variable aleatòria que consisteix a llançar el dau i anotar el <em>quadrat</em> del resultat obtingut. Com que les quatre cares del dau són equiprobables,
<span class="math display">\[
\begin{array}{l}
\displaystyle P(X=-2)=P(X=-1)=P(X=1)=P(X=2)=\frac{1}{4}\\
\displaystyle P(Y=1)=P(Y=4)=\frac{1}{2}
\end{array}
\]</span></p>
</div>

<p>Com que <span class="math inline">\(Y\)</span> és funció de <span class="math inline">\(X\)</span>, ja que <span class="math inline">\(Y=X^2\)</span>, <span class="math inline">\(X\)</span> i <span class="math inline">\(Y\)</span> no poden ser mai independents. Vegem que, en efecte, no ho són. Observau que els únics possibles valors per al vector <span class="math inline">\((X,Y)\)</span> en una tirada del dau són (-2,4), (-1,1), (1,1) i (2,4), cadascun amb probabilitat 1/4. Llavors, per exemple, la probabilitat d’obtenir en una tirada <span class="math inline">\(X=-1\)</span> i <span class="math inline">\(Y=4\)</span> és 0, perquè és impossible, mentre que
<span class="math display">\[
P(X=-1)\cdot P(Y=4)=\frac{1}{4}\cdot\frac{1}{2}=\frac{1}{8}\neq 0.
\]</span></p>
<p>Vegem ara que la covariància de <span class="math inline">\(X\)</span> i <span class="math inline">\(Y\)</span> es 0. Per calcular-la, primer necessitam calcular els valors esperats de les variables:
<span class="math display">\[
\begin{array}{l}
\displaystyle \mu_X=(-2)\cdot \frac{1}{4}+(-1)\cdot \frac{1}{4}+1\cdot \frac{1}{4}+2\cdot \frac{1}{4}=0\\
\displaystyle \mu_Y=1\cdot \frac{1}{2}+4\cdot \frac{1}{2}=2.5
\end{array}
\]</span>
Per tant
<span class="math display">\[
\begin{array}{l}
\sigma_{X,Y}=E\big(X\cdot Y\big)-\mu_X\cdot \mu_Y=E\big(X\cdot Y\big)-0\cdot 2.5=E\big(X\cdot Y\big)\\
\qquad =P\big(X=-2,Y=4\big)\cdot (-2\cdot 4)+P\big(X=-1,Y=1\big)\cdot (-1\cdot 1)\\
\qquad\qquad\qquad +P\big(X=1,Y=1\big)\cdot (1\cdot 1)+P\big(X=2,Y=4\big)\cdot (2\cdot 4)\\
\qquad =\displaystyle \frac{1}{4}\cdot (-8)+\frac{1}{4}\cdot (-1)+\frac{1}{4}\cdot 1+\frac{1}{4}\cdot 8=0.
\end{array}
\]</span>
Així doncs, <span class="math inline">\(X\)</span> i <span class="math inline">\(Y\)</span> són variables dependents, però la seva covariància és 0.</p>

<div class="rmdimportant">
<p>Dues propietats importants més de la covariància:</p>
<ul>
<li><p>La covariància és simètrica:
<span class="math display">\[
\sigma_{X,Y}=E((X-\mu_X)\cdot ( Y-\mu_Y))=E(( Y-\mu_Y)\cdot (X-\mu_X))=\sigma_{Y,X}
\]</span></p></li>
<li><p>La covariància d’una variable aleatòria amb ella mateixa és la seva variància:
<span class="math display">\[
\sigma_{X,X}=E((X-\mu_X)^2)=\sigma^2(X)
\]</span></p></li>
</ul>
</div>

<p>La <em>matriu de covariàncies</em> d’un vector aleatori <span class="math inline">\(\underline{X}=(X_1,\ldots,X_p)\)</span> és la matriu formada per les covariàncies dels parells de variables que la formen:
<span class="math display">\[
\sigma_{\underline{X},\underline{X}}=\begin{pmatrix} \sigma_{X_1,X_1} &amp; \sigma_{X_1,X_2} &amp; \ldots &amp; \sigma_{X_1,X_p}\\
\sigma_{X_2,X_1} &amp; \sigma_{X_2,X_2} &amp; \ldots &amp; \sigma_{X_2,X_p}\\
\vdots &amp; \vdots &amp;\ddots  &amp; \vdots\\
\sigma_{X_p,X_1} &amp; \sigma_{X_p,X_2} &amp; \ldots &amp; \sigma_{X_p,X_p}\\
 \end{pmatrix}
\]</span></p>
<p>Aquesta matriu és simètrica i les entrades de la diagonal són les variàncies de les variables del vector, perquè <span class="math inline">\(\sigma_{X_i,X_i}=\sigma^2_{X_i}\)</span>.</p>
</div>
<div id="correlacio" class="section level3">
<h3><span class="header-section-number">8.1.2</span> Correlació</h3>
<p>Com hem dit, el signe de la covariància té una interpretació senzilla, ja que reflecteix la tendència de la relació entre les variables.
Emperò, la seva magnitud no té una interpretació senzilla. Aleshores, per mesurar la relació lineal entre dues variables aleatòries contínues s’usa l’anomenat <strong>coeficient de correlació lineal de Pearson</strong> (o <strong>correlació</strong> a seques), que ve a ser una versió normalitzada de la covariància. En concret, la <strong>correlació</strong> de les variables <span class="math inline">\(X\)</span> i <span class="math inline">\(Y\)</span> es defineix com el quocient de la seva covariància pel producte de les seves desviacions típiques:
<span class="math display">\[
\rho_{X,Y}=\frac{\sigma_{X,Y}}{\sigma_{X} \sigma_{Y}},
\]</span></p>
<p>La correlació té les propietats importants següents:</p>
<ol style="list-style-type: decimal">
<li><p>No té unitats (perquè les unitats de <span class="math inline">\(\sigma_X\)</span> són les de <span class="math inline">\(X\)</span>, les unitats de <span class="math inline">\(\sigma_Y\)</span> són les de <span class="math inline">\(Y\)</span>, i les unitats de <span class="math inline">\(\sigma_{X,Y}\)</span> són les de <span class="math inline">\(X\)</span> per les de <span class="math inline">\(Y\)</span>)</p></li>
<li><p>Pren valors entre -1 i 1: <span class="math inline">\(-1\leqslant\rho_{X,Y}\leqslant 1\)</span></p></li>
<li><p>És simètrica, <span class="math inline">\(\rho_{X,Y}= \rho_{Y,X}\)</span></p></li>
<li><p>La correlació d’una variable amb ella mateixa és 1: <span class="math inline">\(\rho_{X,X}=1\)</span></p></li>
<li><p>Si <span class="math inline">\(\rho_{X,Y}=\pm 1\)</span>, les variables <span class="math inline">\(X,Y\)</span> tenen una <strong>relació lineal perfecta</strong>, és a dir, existeixen <span class="math inline">\(a,b\in \mathbb{R}\)</span> tals que <span class="math inline">\(Y=a X+b\)</span>. La pendent <span class="math inline">\(a\)</span> d’aquesta recta té el mateix signe que <span class="math inline">\(\rho_{X,Y}\)</span>.</p></li>
<li><p>Si <span class="math inline">\(\rho_{X,Y}=0\)</span>, diem que les variables <span class="math inline">\(X\)</span> i <span class="math inline">\(Y\)</span> són <strong>incorrelades</strong>. Notem que la correlació és 0 si, i només si, la covariància és 0. Per tant, <strong>si <span class="math inline">\(X\)</span> i <span class="math inline">\(Y\)</span> són independents, també són incorrelades. El recíproc en general és fals</strong>, com mostra l’Exemple <a href="introduccio-a-lestadistica-multidimensional.html#exm:nocorr">8.2</a>.</p></li>
</ol>
<p>La <em>matriu de correlacions</em> d’un vector aleatori <span class="math inline">\(\underline{X}=(X_1,\ldots,X_p)\)</span> és la matriu formada per les correlacions de parells de les seves variables:
<span class="math display">\[
\rho(\underline{X})
=\begin{pmatrix} 1 &amp; \rho_{X_1,X_2} &amp; \ldots &amp; \rho_{X_1,X_p}\\
\rho_{X_2,X_1} &amp; 1 &amp; \ldots &amp; \rho_{X_2,X_p}\\
\vdots &amp; \vdots &amp; \ddots &amp; \vdots\\
\rho_{X_p,X_1} &amp; \rho_{X_p,X_2} &amp; \ldots &amp; 1\\
 \end{pmatrix}.
\]</span>
Aquesta matriu és simètrica per la simetria de la correlació.</p>
</div>
</div>
<div id="estadistica-descriptiva-mostres" class="section level2">
<h2><span class="header-section-number">8.2</span> Estadística descriptiva: Mostres</h2>
<div id="covariancies" class="section level3">
<h3><span class="header-section-number">8.2.1</span> Covariàncies</h3>
<p>Siguin <span class="math inline">\(x=(x_1,\ldots,x_n)\)</span> i <span class="math inline">\(y=(y_1,\ldots,y_n)\)</span> dos vectors obtinguts mesurant dues variables aleatòries <span class="math inline">\(X\)</span> i <span class="math inline">\(Y\)</span> sobre una mateixa mostra ordenada d’individus de mida <span class="math inline">\(n\)</span> d’una població. Siguin <span class="math inline">\(\overline{x}\)</span> i <span class="math inline">\(\overline{y}\)</span> les seves mitjanes mostrals. Aleshores la seva <strong>covariància mostral</strong> és
<span class="math display">\[
\widetilde{s}_{x,y} =\frac{1}{n-1} \sum_{i =1}^n\big((x_{i}-\overline{{x}})(y_i-\overline{y})\big)
\]</span>
i la seva <strong>covariància</strong> (<strong>a seques</strong>) és
<span class="math display">\[
{s}_{x,y} =\frac{1}{n} \sum_{i =1}^n\big((x_{i}-\overline{{x}})(y_i-\overline{y})\big)=\frac{n-1}{n}\widetilde{s}_{XY}.
\]</span>
És a dir, com sempre, la diferència entre la versió “mostral” i la versió “a seques” rau en el denominador, <span class="math inline">\(n-1\)</span> i <span class="math inline">\(n\)</span> respectivament.</p>

<div class="rmdimportant">
La covariància de dos vectors només té sentit quan aquests vectors representen els valors de dues variables quantitatives sobre els mateixos individus i en el mateix ordre. En particular, els dos vectors han de tenir la mateixa longitud.
</div>

<p>Com en el cas poblacional, la <strong>covariància</strong> entre dos vectors mesura la tendència que tenen les seves dades a variar conjuntament. Quan la covariància és positiva, si una <span class="math inline">\(x_i\)</span> és gran o petita, la corresponent <span class="math inline">\(y_i\)</span> tendeix a tenir el mateix comportament. Quan la covariància és negativa, aquesta tendència s’inverteix: si una <span class="math inline">\(x_i\)</span> és gran, la corresponent <span class="math inline">\(y_i\)</span> tendeix a ser petita, i viceversa.</p>
<p>És fàcil comprovar que:</p>
<ul>
<li>Les dues covariàncies són simètriques
<span class="math display">\[
\widetilde{s}_{x,y}=\widetilde{s}_{y,x},\ {s}_{x,y}={s}_{y,x}
\]</span></li>
<li>La variància d’un vector és la seva covariància amb ell mateix
<span class="math display">\[
\widetilde{s}_{x,x}=\widetilde{s}^2_{x},\ {s}_{x,x}={s}^2_{x}.
\]</span></li>
</ul>
<p>Les covariàncies de dos vectors estimen la covariància poblacional de les variables que han produït els vectors:</p>
<ul>
<li><p>La covariància mostral <span class="math inline">\(\widetilde{s}_{x,y}\)</span> sempre és un estimador no esbiaixat de la covariància poblacional <span class="math inline">\(\sigma_{X,Y}\)</span></p></li>
<li><p>La covariància a seques <span class="math inline">\(s_{x,y}\)</span> és l’estimador màxim versemblant de <span class="math inline">\(\sigma_{X,Y}\)</span> quan la distribució conjunta de les variables <span class="math inline">\(X,Y\)</span> és el que s’anomena <a href="http://es.wikipedia.org/wiki/Distribución_normal_multivariante%7D">normal bivariant</a>.</p></li>
</ul>

<div class="example">
<p><span id="exm:multex1" class="example"><strong>Exemple 8.3  </strong></span>Hem mesurat l’índex de massa corporal, BMI, i el nivell de colesterol en 5 individus sans. Guardam els resultats en un <em>data frame</em> i en calculam les mitjanes:</p>
</div>

<pre class="sourceCode r"><code class="sourceCode r">BMI=<span class="st"> </span><span class="kw">c</span>(<span class="fl">18.3</span>,<span class="fl">24.4</span>,<span class="fl">24.6</span>,<span class="fl">24.4</span>,<span class="fl">22.2</span>,<span class="fl">19.5</span>)
Chol=<span class="kw">c</span>(<span class="dv">170</span>,<span class="dv">202</span>,<span class="dv">215</span>,<span class="dv">218</span>,<span class="dv">210</span>,<span class="dv">210</span>)
DF=<span class="kw">data.frame</span>(BMI,Chol)
<span class="kw">mean</span>(BMI)</code></pre>
<pre><code>## [1] 22.23333</code></pre>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">mean</span>(Chol)</code></pre>
<pre><code>## [1] 204.1667</code></pre>
<p>Aleshores la covariància mostral d’aquests dos vectors és
<span class="math display">\[
\begin{array}{l}
\dfrac{1}{5}\Big((18.3-22.23)(170-204.17)+(24.4-22.23)(202-204.17)\\
\qquad +(24.6-22.23)(215-204.17)+(24.4-22.23)(218-204.17)\\
\qquad +(22.2-22.23)(210-204.17)+(19.5-22.23)(210-204.17)\Big)=33.8333
\end{array}
\]</span></p>
<p>i la seva covariància a seques és
<span class="math display">\[
\begin{array}{l}
\dfrac{1}{6}\Big((18.3-22.23)(170-204.17)+(24.4-22.23)(202-204.17)\\
\qquad +(24.6-22.23)(215-204.17) +(24.4-22.23)(218-204.17)\\
\qquad +(22.2-22.23)(210-204.17)+(19.5-22.23)(210-204.17)\Big)=27.0667
\end{array}
\]</span></p>
<p>La covariància <em>mostral</em> de dos vectors numèrics de la mateixa longitud <span class="math inline">\(n\)</span> es calcula amb R amb la funció <code>cov</code>.
Per obtenir la seva covariància <em>a seques</em>, cal multiplicar el resultat de <code>cov</code> per <span class="math inline">\((n-1)/n\)</span>.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">cov</span>(BMI,Chol)</code></pre>
<pre><code>## [1] 33.83333</code></pre>
<p>Considerem una taula de dades de la forma
<span class="math display">\[
\begin{array}{cccc}
X_1 &amp; X_2 &amp; \ldots &amp; X_p\\ \hline
x_{1 1} &amp; x_{1 2} &amp;\ldots &amp; x_{1 p}\\
x_{2 1} &amp; x_{2 2} &amp;\ldots &amp; x_{2 p}\\
\vdots &amp; \vdots   &amp;   \ddots    &amp;\vdots\\ 
x_{n 1} &amp; x_{n 2} &amp;\ldots &amp; x_{n p}
\end{array}
\]</span>
on cada columna representa els valors d’una certa variable <span class="math inline">\(X_i\)</span> i cada filera un individu d’una mostra de la població, de manera que l’entrada <span class="math inline">\(x_{ij}\)</span> d’aquesta taula és el valor de <span class="math inline">\(X_j\)</span> sobre l’individu <span class="math inline">\(i\)</span>-èssim de la mostra.</p>
<p>La <strong>matriu de covariàncies mostrals</strong> d’aquesta taula és la matriu
<span class="math display">\[
\widetilde{{S}}=
\begin{pmatrix}  
 \widetilde{s}^2_{X_1} &amp; \widetilde{s}_{X_1,X_2} &amp; \ldots &amp; \widetilde{s}_{X_1,X_p}\\
 \widetilde{s}_{X_2,X_1} &amp;  \widetilde{s}^2_{X_2} &amp; \ldots &amp; \widetilde{s}_{X_2,X_p}\\
  \vdots &amp; \vdots  &amp;  \ddots      &amp; \vdots\\
\widetilde{s}_{X_p,X_1} &amp; \widetilde{s}_{X_p,X_2} &amp; \ldots &amp;  \widetilde{s}^2_{X_p}
\end{pmatrix}
\]</span>
i la <strong>matriu de covaiàncies</strong> (<strong>a seques</strong>) es defineix de manera similar, però amb les covariàncies a seques:
<span class="math display">\[
{S}=
\begin{pmatrix}  
 s^2_{X_1} &amp; s_{X_1,X_2} &amp; \ldots &amp; s_{X_1,X_p}\\
 s_{X_2,X_1} &amp; s^2_{X_2} &amp; \ldots &amp; s_{X_2,X_p}\\
  \vdots &amp; \vdots  &amp;  \ddots      &amp; \vdots\\
s_{X_p,X_1} &amp; s_{X_p,X_2} &amp; \ldots &amp; s^2_{X_p}
\end{pmatrix}
\]</span>
Totes dues són simètriques.</p>
<p>La matriu de covariàncies mostrals es calcula amb la funció <code>cov</code> aplicada a la matriu o el <em>data frame</em> de variables numèriques que emmagatzema la taula de dades. Per calcular la matriu de covariàncies a seques, es multiplica el resultat de <code>cov</code> per <span class="math inline">\((n-1)/n\)</span>, on <span class="math inline">\(n\)</span> és el nombre de fileres de la taula.</p>

<div class="example">
<p><span id="exm:multex2" class="example"><strong>Exemple 8.4  </strong></span>Afegirem a la taula de dades de l’Exemple <a href="introduccio-a-lestadistica-multidimensional.html#exm:multex1">8.3</a> una tercera variable amb les edats dels 6 individus representats en ella.</p>
</div>

<pre class="sourceCode r"><code class="sourceCode r">DF<span class="op">$</span>Edats=<span class="kw">c</span>(<span class="dv">49</span>,<span class="dv">39</span>,<span class="dv">50</span>,<span class="dv">44</span>,<span class="dv">40</span>,<span class="dv">36</span>)
DF</code></pre>
<pre><code>##    BMI Chol Edats
## 1 18.3  170    49
## 2 24.4  202    39
## 3 24.6  215    50
## 4 24.4  218    44
## 5 22.2  210    40
## 6 19.5  210    36</code></pre>
<p>La matriu de covariàncies mostrals d’aquesta taula és</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">cov</span>(DF)</code></pre>
<pre><code>##             BMI      Chol  Edats
## BMI    7.586667  33.83333   1.14
## Chol  33.833333 309.76667 -33.00
## Edats  1.140000 -33.00000  32.00</code></pre>
<p>Podreu observar que és simètrica, que a la diagonal hi obtenim les variàncies mostrals de les variables de la taula:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">apply</span>(DF,<span class="dt">MARGIN=</span><span class="dv">2</span>,<span class="dt">FUN=</span>var)</code></pre>
<pre><code>##        BMI       Chol      Edats 
##   7.586667 309.766667  32.000000</code></pre>
<p>i que l’entrada (2,1) coincideix amb la covariància de <code>BMI</code> i <code>Chol</code> que hem calculat abans.</p>
</div>
<div id="correlacio-de-pearson" class="section level3">
<h3><span class="header-section-number">8.2.2</span> Correlació de Pearson</h3>
<p>Siguin <span class="math inline">\(x=(x_1,\ldots,x_n)\)</span> i <span class="math inline">\(y=(y_1,\ldots,y_n)\)</span> dos vectors obtinguts mesurant dues variables aleatòries <span class="math inline">\(X\)</span> i <span class="math inline">\(Y\)</span> sobre una mateixa mostra d’individus de mida <span class="math inline">\(n\)</span> d’una població.</p>
<p>La <strong>correlació de Pearson</strong> de <span class="math inline">\(x\)</span> i <span class="math inline">\(y\)</span> és la seva covariància mostral dividida pel producte de les seves desviacions típiques mostrals:
<span class="math display">\[
r_{x,y}=\frac{\widetilde{s}_{x,y}}{\widetilde{s}_x\cdot \widetilde{s}_y}.
\]</span></p>
<p>També és igual a la seva covariància dividida pel producte de les seves desviacions típiques, perquè els canvis de denominador se cancel·len:
<span class="math display">\[
r_{x,y}=\frac{\widetilde{s}_{x,y}}{\widetilde{s}_x\cdot \widetilde{s}_y}=
\frac{\frac{n}{n-1}\cdot {s}_{x,y}}{\sqrt{\frac{n}{n-1}}\cdot {s}_x \cdot\sqrt{\frac{n}{n-1}}\cdot{s}_y}=
\frac{s_{x,y}}{s_x \cdot s_y}=r_{x,y}.
\]</span></p>

<div class="example">
<p><span id="exm:multex1rev" class="example"><strong>Exemple 8.5  </strong></span>Tornem a la situació de l’Exemple <a href="introduccio-a-lestadistica-multidimensional.html#exm:multex1">8.3</a>. La covariància mostral i les desviacions típiques mostrals dels vectors <code>BMI</code> i <code>Chol</code> són</p>
</div>

<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sd</span>(BMI)</code></pre>
<pre><code>## [1] 2.75439</code></pre>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sd</span>(Chol)</code></pre>
<pre><code>## [1] 17.60019</code></pre>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">cov</span>(BMI,Chol)</code></pre>
<pre><code>## [1] 33.83333</code></pre>
<p>i per tant la seva correlació de Pearson és
<span class="math display">\[
r_{BMI,Chol}=\frac{33.833}{2.754\cdot 17.6}= 0.698
\]</span></p>
<p>La correlació de Pearson de dos vectors estima la correlació de les variables poblacionals que han produït els vectors. En concret</p>
<ul>
<li><span class="math inline">\(r_{x,y}\)</span> és un estimador màxim versemblant de <span class="math inline">\(\rho_{X,Y}\)</span> quan la seva distribució conjunta és normal bivariant. N’és un estimador esbiaxiat, però el seu biaix tendeix a 0.</li>
</ul>
<p>Altres propietats importants de la correlació de Pearson:</p>
<ul>
<li><p>La correlació de Pearson és simètrica: <span class="math inline">\(r_{x,y}=r_{y,x}\)</span></p></li>
<li><p>La correlació de Pearson pren valors només entre -1 i 1: <span class="math inline">\(-1\leqslant r_{x,y}\leqslant 1\)</span></p></li>
<li><p>La correlació de Pearson d’un vector amb ell mateix és 1: <span class="math inline">\(r_{x,x}=1\)</span></p></li>
<li><p><span class="math inline">\(r_{x,y}\)</span> té el mateix signe que <span class="math inline">\(s_{x,y}\)</span></p></li>
<li><p><span class="math inline">\(r_{x,y}=\pm 1\)</span> si, i només si, existeixen <span class="math inline">\(a, b\in \mathbb{R}\)</span> tals que <span class="math inline">\(y=ax+b\)</span>, és a dir, <span class="math inline">\(y_i=ax_i+b\)</span> per a cada <span class="math inline">\(i=1,\ldots,n\)</span>. La pendent <span class="math inline">\(a\)</span> d’aquesta relación lineal té el mateix signe que <span class="math inline">\(r_{x,y}\)</span>.</p></li>
<li><p>El coeficient de determinació <span class="math inline">\(R^2\)</span> de la regressió lineal per mínims quadrats de <span class="math inline">\(y\)</span> respecte de <span class="math inline">\(x\)</span> és igual al quadrat de la seva correlació de Pearson:
<span class="math display">\[
R^2=r_{x,y}^2
\]</span></p></li>
</ul>

<div class="rmdimportant">
Per tant, com més s’acosta <span class="math inline">\(|r_{x,y}|\)</span> a 1, més s’acosten els vectors <span class="math inline">\(x,y\)</span> a dependre linealment l’un de l’altre. El signe de <span class="math inline">\(r_{x,y}\)</span> indica si dependència és creixent (<span class="math inline">\(r_{x,y}&gt;0\)</span>) o decreixent (<span class="math inline">\(r_{x,y}&lt;0\)</span>).
</div>

<p>Amb R, la correlació de Pearson de dos vectors es pot calcular amb la funció <code>cor</code>. Per exemple, la correlació del Pearson dels vectors <code>BMI</code> i <code>Chol</code> s’obté amb</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">cor</span>(BMI,Chol)</code></pre>
<pre><code>## [1] 0.6979141</code></pre>
<p>Vegem que el seu quadrat és igual al <span class="math inline">\(R^2\)</span> de la regressió lineal de <code>Chol</code> en funció de <code>BMI</code>:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">cor</span>(BMI,Chol)<span class="op">^</span><span class="dv">2</span></code></pre>
<pre><code>## [1] 0.487084</code></pre>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summary</span>(<span class="kw">lm</span>(Chol<span class="op">~</span>BMI))<span class="op">$</span>r.squared</code></pre>
<pre><code>## [1] 0.487084</code></pre>
<p>Per fer-nos una idea de què representa aquest valor de la correlació, vegem el gràfic dels punts (BMI,Chol) amb la seva recta de regressió lineal:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">plot</span>(BMI,Chol,<span class="dt">pch=</span><span class="dv">20</span>)
<span class="kw">abline</span>(<span class="kw">lm</span>(Chol<span class="op">~</span>BMI),<span class="dt">col=</span><span class="st">&quot;red&quot;</span>,<span class="dt">lwd=</span><span class="fl">1.5</span>)</code></pre>
<p><img src="Bioestadistica-II_files/figure-html/unnamed-chunk-438-1.png" width="50%" style="display: block; margin: auto;" /></p>
<p>Hi podem observar com <code>Chol</code> tendeix a créixer quan <code>BMI</code> creix.</p>

<div class="rmdnote">
<p>Les funcions del paquet <strong>datasaurus</strong> us permeten crear conjunts de punts de “formes” diferents i mateixos estadístics, i en particular la mateixa correlació. Per exemple, tots els conjunts de punts del gràfic següent tenen la mateixa correlació.</p>
</div>

<p><img src="Bioestadistica-II_files/figure-html/datasaurus.png" width="90%" style="display: block; margin: auto;" /></p>
<p>Suposem que tenim una taula de dades de la forma
<span class="math display">\[
\begin{array}{cccc}
X_1 &amp; X_2 &amp; \ldots &amp; X_p\\ \hline
x_{1 1} &amp; x_{1 2} &amp;\ldots &amp; x_{1 p}\\
x_{2 1} &amp; x_{2 2} &amp;\ldots &amp; x_{2 p}\\
\vdots &amp; \vdots   &amp;   \ddots    &amp;\vdots\\ 
x_{n 1} &amp; x_{n 2} &amp;\ldots &amp; x_{n p}
\end{array}
\]</span>
on cada columna representa els valors d’una certa variable <span class="math inline">\(X_i\)</span> i cada filera un individu d’una mostra de la població, de manera que l’entrada <span class="math inline">\(x_{ij}\)</span> d’aquesta taula és el valor de <span class="math inline">\(X_j\)</span> sobre l’individu <span class="math inline">\(i\)</span>-èssim de la mostra.</p>
<p>La seva <strong>matriu de correlacions de Pearson</strong> és la matriu simètrica
<span class="math display">\[
\begin{pmatrix}  
 1 &amp; r_{X_1,X_2} &amp; \ldots &amp; r_{X_1,X_p}\\
 r_{X_2,X_1} &amp; 1 &amp; \ldots &amp; r_{X_2,X_p}\\
  \vdots &amp; \vdots  &amp;  \ddots      &amp; \vdots\\
r_{X_p,X_1} &amp; r_{X_p,X_2} &amp; \ldots &amp; 1
\end{pmatrix}
\]</span></p>
<p>Aquesta matriu de correlacions es calcula amb la funció <code>cor</code> aplicada a la matriu o el <em>data frame</em> de variables numèriques que emmagatzema la taula de dades. Per exemple, la matriu de correlacions de Pearson de la taula de dades <code>DF</code> de l’Exemple <a href="introduccio-a-lestadistica-multidimensional.html#exm:multex2">8.4</a> és</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">cor</span>(DF)</code></pre>
<pre><code>##              BMI       Chol       Edats
## BMI   1.00000000  0.6979141  0.07316517
## Chol  0.69791406  1.0000000 -0.33145274
## Edats 0.07316517 -0.3314527  1.00000000</code></pre>
</div>
<div id="correlacio-de-spearman" class="section level3">
<h3><span class="header-section-number">8.2.3</span> Correlació de Spearman</h3>
<p>La correlació de Pearson mesura específicament la tendència de dues variables contínues a dependre linealment l’una de l’altra. En circumstàncies en les quals no esperem aquesta dependència lineal, o en les quals les nostres variables siguin quantitatives discretes o simplement ordinals, emprar la correlació de Pearson per a analitzar la relació entre dues variables no és el més adequat. Entre les propostes alternatives, la més popular és la <strong>correlació de Spearman</strong>.</p>
<p>La correlació de Spearman de dos vectors <span class="math inline">\(x\)</span> i <span class="math inline">\(y\)</span> és la correlació de Pearson dels vectors de <strong>rangs</strong> de <span class="math inline">\(x\)</span> i <span class="math inline">\(y\)</span>. El vector de rangs d’un vector <span class="math inline">\(x\)</span> s’obté substituïnt cada valor de <span class="math inline">\(x\)</span> per la seva posició en el vector ordenat de menor a major, i en cas d’empats assigna la mitjana de les posicions que ocuparien tots els empats (aquests rangs ja han sortit, al <a href="https://aprender-uib.github.io/MatesII/contrastos-de-bondat-dajust.html#test-de-kolmogorov-smirnov">test de bondat d’ajust de Kolmogorov-Smirnov</a>). Per exemple, el vector de rangs de
<span class="math display">\[
x=(4,5,1,5,1,3,4,4)
\]</span>
és
<span class="math display">\[
(5,7.5,1.5,7.5,1.5,3,5,5)
\]</span>
Com hem calculat aquest vector?</p>
<ul>
<li>Als dos elements 1 de <span class="math inline">\(x\)</span> els tocarien les posicions 1, 2 del vector ordenat, i per tant el seu rang és la mitjana d’aquestes dues posicions: 1.5.</li>
<li>A l’element 3 li tocaria la posició 3 del vector ordenat, i com que només n’hi ha un, aquest és el seu rang.</li>
<li>Als tres elements 4 els tocarien les posicions 4, 5 i 6 del vector ordenat, i per tant el seu rang és la mitjana d’aquestes tres posicions: 5.</li>
<li>Finalment, als dos elements 5 els tocarien les posicions 7, 8 del vector ordenat, i per tant el seu rang és la mitjana d’aquestes dues posicions: 7.5.</li>
</ul>

<div class="rmdnote">
Per cert, amb R els rangs es calculen amb la funció <code>rank</code>:
</div>

<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">rank</span>(<span class="kw">c</span>(<span class="dv">4</span>,<span class="dv">5</span>,<span class="dv">1</span>,<span class="dv">5</span>,<span class="dv">1</span>,<span class="dv">3</span>,<span class="dv">4</span>,<span class="dv">4</span>))</code></pre>
<pre><code>## [1] 5.0 7.5 1.5 7.5 1.5 3.0 5.0 5.0</code></pre>
<p>Amb R, la correlació de Spearman es calcula directament amb la funció <code>cor</code> entrant-li el paràmetre <code>method=&quot;spearman&quot;</code>. (El valor per defecte del paràmetre <code>method</code> és <code>&quot;pearson&quot;</code> i per això no l’indicam quan calculam la correlació de Pearson.)</p>

<div class="example">
<p><span id="exm:unnamed-chunk-444" class="example"><strong>Exemple 8.6  </strong></span>Calculem a mà la correlació de Spearman dels vectors <code>BMI</code> i <code>Chol</code>. El primer que farem serà calcular els rangs dels valors</p>
</div>

<p><span class="math display">\[
\begin{array}{|c|c||c|c|}
\hline
\mathit{BMI} &amp; \mathit{Rang} &amp; \mathit{Chol}&amp;  \mathit{Rang}
\\\hline\hline
18.3&amp; 1 &amp; 170&amp; 1 \\
24.4&amp;4.5 &amp; 202 &amp; 2\\
24.6&amp;6 &amp; 215&amp; 5 \\
24.4&amp;4.5 &amp; 218&amp;  6\\ 
22.2&amp;3 &amp; 210&amp;  3.5\\
19.5&amp;2 &amp; 210&amp;  3.5\\\hline
\end{array}
\]</span></p>
<p>Per tant, la correlación de Spearman de
<span class="math display">\[
\mathit{BMI}=(18.3, 24.4, 24.6, 24.4, 22.2, 19.5)\mbox{ i }\mathit{Chol}=(170, 202, 215, 218, 210, 210)
\]</span>
és la correlació de Pearson de
<span class="math display">\[
(1, 4.5, 6, 4.5, 3, 2)\mbox{ i }(1, 2, 5, 6, 3.5, 3.5)
\]</span></p>
<p>Comprovem-ho:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">cor</span>(BMI,Chol,<span class="dt">method=</span><span class="st">&quot;spearman&quot;</span>)</code></pre>
<pre><code>## [1] 0.6470588</code></pre>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">cor</span>(<span class="kw">c</span>(<span class="dv">1</span>,<span class="fl">4.5</span>,<span class="dv">6</span>,<span class="fl">4.5</span>,<span class="dv">3</span>,<span class="dv">2</span>),<span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">5</span>,<span class="dv">6</span>,<span class="fl">3.5</span>,<span class="fl">3.5</span>))</code></pre>
<pre><code>## [1] 0.6470588</code></pre>
</div>
<div id="contrastos-de-correlacio" class="section level3">
<h3><span class="header-section-number">8.2.4</span> Contrastos de correlació</h3>
<p>En un <strong>contrast de correlació</strong> de dues variables poblacionals <span class="math inline">\(X\)</span> i <span class="math inline">\(Y\)</span>, la hipòtesi nul·la és que no hi ha correlació entre les dues variables, la qual cosa s’entén que tradueix que no hi ha cap relació entre elles.
<span class="math display">\[
\left\{
\begin{array}{ll}
H_0: &amp; \rho_{XY}=0\\
H_1: &amp; \rho_{XY}&gt; 0\text{ o }\rho_{XY}&lt; 0\text{ o }\rho_{XY}\neq 0
\end{array}\right.
\]</span></p>

<div class="rmdimportant">
Si en un contrast de correlació rebutjam la hipòtesi nul·la, en particular concloem que les variables <span class="math inline">\(X\)</span> i <span class="math inline">\(Y\)</span> són dependents (perquè si fossin independents, la seva correlació seria 0).
</div>

<p>No explicarem com es fa a mà aquest contrast ni quines hipòtesis han de satisfer les variables poblacionals per que el resultat sigui fiable. Simplement heu de saber que s’efectua amb la funció <code>cor.test</code>. Si estau interessats en el detall, podeu consultar la <a href="https://en.wikipedia.org/wiki/Pearson_correlation_coefficient#Testing_using_Student&#39;s_t-distribution">corresponent entrada de la Wikipedia</a>.</p>

<div class="example">
<p><span id="exm:unnamed-chunk-447" class="example"><strong>Exemple 8.7  </strong></span>Volem contrastar si hi ha correlació positiva entre el BMI i el nivell de colesterol d’un adult sa, amb un nivell de significació del 5%.</p>
</div>

<p><em>Variables poblacionals d’interès</em>:</p>
<ul>
<li><span class="math inline">\(\mathit{BMI}\)</span>: “Prenem un adult sa i mesuram el seu BMI”</li>
<li><span class="math inline">\(\mathit{Chol}\)</span>: “Prenem un adult sa i mesuram el nivell de colesterol en mg/dl”</li>
</ul>
<p><em>Contrast</em>:
<span class="math display">\[
\left\{
\begin{array}{ll}
H_0: &amp; \rho_{\textit{BMI,Chol}}=0\\
H_1: &amp; \rho_{\textit{BMI,Chol}}&gt;0
\end{array}\right.
\]</span></p>
<p>Emprarem les mostres <code>BMI</code> i <code>Chol</code> de l’Exemple<a href="introduccio-a-lestadistica-multidimensional.html#exm:multex1">8.3</a>.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">cor.test</span>(BMI,Chol,<span class="dt">alternative=</span><span class="st">&quot;greater&quot;</span>)</code></pre>
<pre><code>## 
##  Pearson&#39;s product-moment correlation
## 
## data:  BMI and Chol
## t = 1.949, df = 4, p-value = 0.06155
## alternative hypothesis: true correlation is greater than 0
## 95 percent confidence interval:
##  -0.08621998  1.00000000
## sample estimates:
##       cor 
## 0.6979141</code></pre>
<p><em>Conclusió</em>: No hem obtingut evidència estadísticament significativa que el BMI i el nivell de colesterol d’un adult sa tenguin correlació positiva (test de correlació, p-valor 0.06, IC 95% per a la correlació de <span class="math inline">\(-0.086\)</span> a 1).</p>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="contrastos-dindependencia-i-homogeneitat.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="anova.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "subsection",
"download": ["pdf", "epub"]
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:" && /^https?:/.test(src))
      src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
