<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Tema 1 Repàs de la distribució normal | Matemàtiques II</title>
  <meta name="description" content="Apunts Matemàtiques II bookdown::gitbook." />
  <meta name="generator" content="bookdown 0.18 and GitBook 2.6.7" />

  <meta property="og:title" content="Tema 1 Repàs de la distribució normal | Matemàtiques II" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Apunts Matemàtiques II bookdown::gitbook." />
  <meta name="github-repo" content="cescrossello/MatesII" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Tema 1 Repàs de la distribució normal | Matemàtiques II" />
  
  <meta name="twitter:description" content="Apunts Matemàtiques II bookdown::gitbook." />
  



<meta name="date" content="2020-05-04" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="index.html"/>
<link rel="next" href="estimació-puntual.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />











<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(data-line-number);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Bioestadística II</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Presentació</a></li>
<li class="part"><span><b>Part II: Estadística inferencial</b></span></li>
<li class="chapter" data-level="1" data-path="repàs-de-la-distribució-normal.html"><a href="repàs-de-la-distribució-normal.html"><i class="fa fa-check"></i><b>1</b> Repàs de la distribució normal</a><ul>
<li class="chapter" data-level="1.1" data-path="repàs-de-la-distribució-normal.html"><a href="repàs-de-la-distribució-normal.html#propietats-de-la-distribució-normal"><i class="fa fa-check"></i><b>1.1</b> Propietats de la distribució normal</a></li>
<li class="chapter" data-level="1.2" data-path="repàs-de-la-distribució-normal.html"><a href="repàs-de-la-distribució-normal.html#amb-r"><i class="fa fa-check"></i><b>1.2</b> Amb R</a></li>
<li class="chapter" data-level="1.3" data-path="repàs-de-la-distribució-normal.html"><a href="repàs-de-la-distribució-normal.html#combinacions-lineals"><i class="fa fa-check"></i><b>1.3</b> Combinacions lineals</a></li>
<li class="chapter" data-level="1.4" data-path="repàs-de-la-distribució-normal.html"><a href="repàs-de-la-distribució-normal.html#intervals-de-referència"><i class="fa fa-check"></i><b>1.4</b> Intervals de referència</a></li>
<li class="chapter" data-level="1.5" data-path="repàs-de-la-distribució-normal.html"><a href="repàs-de-la-distribució-normal.html#el-z-score"><i class="fa fa-check"></i><b>1.5</b> El z-score</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="estimació-puntual.html"><a href="estimació-puntual.html"><i class="fa fa-check"></i><b>2</b> Estimació puntual</a><ul>
<li class="chapter" data-level="2.1" data-path="estimació-puntual.html"><a href="estimació-puntual.html#definicions-bàsiques"><i class="fa fa-check"></i><b>2.1</b> Definicions bàsiques</a></li>
<li class="chapter" data-level="2.2" data-path="estimació-puntual.html"><a href="estimació-puntual.html#mitjana-mostral"><i class="fa fa-check"></i><b>2.2</b> Mitjana mostral</a></li>
<li class="chapter" data-level="2.3" data-path="estimació-puntual.html"><a href="estimació-puntual.html#proporció-mostral"><i class="fa fa-check"></i><b>2.3</b> Proporció mostral</a></li>
<li class="chapter" data-level="2.4" data-path="estimació-puntual.html"><a href="estimació-puntual.html#variància-mostral"><i class="fa fa-check"></i><b>2.4</b> Variància mostral</a></li>
<li class="chapter" data-level="2.5" data-path="estimació-puntual.html"><a href="estimació-puntual.html#la-t-de-student"><i class="fa fa-check"></i><b>2.5</b> La t de Student</a></li>
<li class="chapter" data-level="2.6" data-path="estimació-puntual.html"><a href="estimació-puntual.html#bons-estimadors"><i class="fa fa-check"></i><b>2.6</b> “Bons” estimadors</a><ul>
<li class="chapter" data-level="2.6.1" data-path="estimació-puntual.html"><a href="estimació-puntual.html#estimadors-no-esbiaixats"><i class="fa fa-check"></i><b>2.6.1</b> Estimadors no esbiaixats</a></li>
<li class="chapter" data-level="2.6.2" data-path="estimació-puntual.html"><a href="estimació-puntual.html#estimadors-eficients"><i class="fa fa-check"></i><b>2.6.2</b> Estimadors eficients</a></li>
<li class="chapter" data-level="2.6.3" data-path="estimació-puntual.html"><a href="estimació-puntual.html#estimadors-màxim-versemblants"><i class="fa fa-check"></i><b>2.6.3</b> Estimadors màxim versemblants</a></li>
</ul></li>
<li class="chapter" data-level="2.7" data-path="estimació-puntual.html"><a href="estimació-puntual.html#sec:pobl"><i class="fa fa-check"></i><b>2.7</b> Estimació de poblacions</a><ul>
<li class="chapter" data-level="2.7.1" data-path="estimació-puntual.html"><a href="estimació-puntual.html#estimació-de-poblacions-numerades"><i class="fa fa-check"></i><b>2.7.1</b> Estimació de poblacions numerades</a></li>
<li class="chapter" data-level="2.7.2" data-path="estimació-puntual.html"><a href="estimació-puntual.html#marca-recaptura"><i class="fa fa-check"></i><b>2.7.2</b> Marca-recaptura</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="intervals-de-confiança.html"><a href="intervals-de-confiança.html"><i class="fa fa-check"></i><b>3</b> Intervals de confiança</a><ul>
<li class="chapter" data-level="3.1" data-path="intervals-de-confiança.html"><a href="intervals-de-confiança.html#definicions-bàsiques-1"><i class="fa fa-check"></i><b>3.1</b> Definicions bàsiques</a></li>
<li class="chapter" data-level="3.2" data-path="intervals-de-confiança.html"><a href="intervals-de-confiança.html#exemple-interval-de-confiança-del-95-per-a-la-mitjana-duna-variable-aleatòria-normal"><i class="fa fa-check"></i><b>3.2</b> Exemple: Interval de confiança del 95% per a la mitjana d’una variable aleatòria normal</a></li>
<li class="chapter" data-level="3.3" data-path="intervals-de-confiança.html"><a href="intervals-de-confiança.html#interval-de-confiança-per-a-la-mitjana-basat-en-la-t-de-student"><i class="fa fa-check"></i><b>3.3</b> Interval de confiança per a la mitjana basat en la t de Student</a><ul>
<li class="chapter" data-level="" data-path="intervals-de-confiança.html"><a href="intervals-de-confiança.html#la-fórmula"><i class="fa fa-check"></i>La fórmula</a></li>
<li class="chapter" data-level="" data-path="intervals-de-confiança.html"><a href="intervals-de-confiança.html#algunes-consideracions"><i class="fa fa-check"></i>Algunes consideracions</a></li>
<li class="chapter" data-level="" data-path="intervals-de-confiança.html"><a href="intervals-de-confiança.html#amb-r-1"><i class="fa fa-check"></i>Amb R</a></li>
<li class="chapter" data-level="" data-path="intervals-de-confiança.html"><a href="intervals-de-confiança.html#càlcul-de-la-mida-de-la-mostra-per-fixar-lerror"><i class="fa fa-check"></i>Càlcul de la mida de la mostra per fixar l’error</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="intervals-de-confiança.html"><a href="intervals-de-confiança.html#intervals-de-confiança-per-a-proporcions"><i class="fa fa-check"></i><b>3.4</b> Intervals de confiança per a proporcions</a><ul>
<li class="chapter" data-level="" data-path="intervals-de-confiança.html"><a href="intervals-de-confiança.html#mètode-exacte-de-clopper-pearson"><i class="fa fa-check"></i>Mètode “exacte” de Clopper-Pearson</a></li>
<li class="chapter" data-level="" data-path="intervals-de-confiança.html"><a href="intervals-de-confiança.html#mètode-de-wilson"><i class="fa fa-check"></i>Mètode de Wilson</a></li>
<li class="chapter" data-level="" data-path="intervals-de-confiança.html"><a href="intervals-de-confiança.html#mètode-de-laplace"><i class="fa fa-check"></i>Mètode de Laplace</a></li>
<li class="chapter" data-level="" data-path="intervals-de-confiança.html"><a href="intervals-de-confiança.html#més-exemples"><i class="fa fa-check"></i>Més exemples</a></li>
<li class="chapter" data-level="" data-path="intervals-de-confiança.html"><a href="intervals-de-confiança.html#càlcul-de-la-mida-de-la-mostra-per-a-fixar-lerror"><i class="fa fa-check"></i>Càlcul de la mida de la mostra per a fixar l’error</a></li>
</ul></li>
<li class="chapter" data-level="3.5" data-path="intervals-de-confiança.html"><a href="intervals-de-confiança.html#intervals-de-confiança-per-a-la-variància-duna-variable-normal"><i class="fa fa-check"></i><b>3.5</b> Intervals de confiança per a la variància d’una variable normal</a></li>
<li class="chapter" data-level="3.6" data-path="intervals-de-confiança.html"><a href="intervals-de-confiança.html#poblacions-finites"><i class="fa fa-check"></i><b>3.6</b> “Poblacions finites”</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="contrastos-dhipòtesis-generalitats.html"><a href="contrastos-dhipòtesis-generalitats.html"><i class="fa fa-check"></i><b>4</b> Contrastos d’hipòtesis: Generalitats</a><ul>
<li class="chapter" data-level="4.1" data-path="contrastos-dhipòtesis-generalitats.html"><a href="contrastos-dhipòtesis-generalitats.html#hipòtesis-nulla-i-alternativa"><i class="fa fa-check"></i><b>4.1</b> Hipòtesis nul·la i alternativa</a></li>
<li class="chapter" data-level="4.2" data-path="contrastos-dhipòtesis-generalitats.html"><a href="contrastos-dhipòtesis-generalitats.html#sec:moneda"><i class="fa fa-check"></i><b>4.2</b> Un exemple</a></li>
<li class="chapter" data-level="4.3" data-path="contrastos-dhipòtesis-generalitats.html"><a href="contrastos-dhipòtesis-generalitats.html#sec:pval"><i class="fa fa-check"></i><b>4.3</b> El p-valor</a></li>
<li class="chapter" data-level="4.4" data-path="contrastos-dhipòtesis-generalitats.html"><a href="contrastos-dhipòtesis-generalitats.html#tipus-derrors"><i class="fa fa-check"></i><b>4.4</b> Tipus d’errors</a></li>
<li class="chapter" data-level="4.5" data-path="contrastos-dhipòtesis-generalitats.html"><a href="contrastos-dhipòtesis-generalitats.html#sec:exttest"><i class="fa fa-check"></i><b>4.5</b> Exemple: El test t</a></li>
<li class="chapter" data-level="4.6" data-path="contrastos-dhipòtesis-generalitats.html"><a href="contrastos-dhipòtesis-generalitats.html#recapitulació"><i class="fa fa-check"></i><b>4.6</b> Recapitulació</a><ul>
<li class="chapter" data-level="" data-path="contrastos-dhipòtesis-generalitats.html"><a href="contrastos-dhipòtesis-generalitats.html#interval-de-confiança-dun-contrast"><i class="fa fa-check"></i>Interval de confiança d’un contrast</a></li>
<li class="chapter" data-level="" data-path="contrastos-dhipòtesis-generalitats.html"><a href="contrastos-dhipòtesis-generalitats.html#la-potència"><i class="fa fa-check"></i>La potència</a></li>
<li class="chapter" data-level="" data-path="contrastos-dhipòtesis-generalitats.html"><a href="contrastos-dhipòtesis-generalitats.html#el-risc-de-positiu-fals-opcional"><i class="fa fa-check"></i>El risc de positiu fals (Opcional)</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="contrastos-dhipòtesis-dun-i-dos-paràmetres.html"><a href="contrastos-dhipòtesis-dun-i-dos-paràmetres.html"><i class="fa fa-check"></i><b>5</b> Contrastos d’hipòtesis d’un i dos paràmetres</a><ul>
<li class="chapter" data-level="5.1" data-path="contrastos-dhipòtesis-dun-i-dos-paràmetres.html"><a href="contrastos-dhipòtesis-dun-i-dos-paràmetres.html#contrastos-de-mitjanes"><i class="fa fa-check"></i><b>5.1</b> Contrastos de mitjanes</a><ul>
<li class="chapter" data-level="5.1.1" data-path="contrastos-dhipòtesis-dun-i-dos-paràmetres.html"><a href="contrastos-dhipòtesis-dun-i-dos-paràmetres.html#test-t-per-a-una-mitjana"><i class="fa fa-check"></i><b>5.1.1</b> Test t per a una mitjana</a></li>
<li class="chapter" data-level="5.1.2" data-path="contrastos-dhipòtesis-dun-i-dos-paràmetres.html"><a href="contrastos-dhipòtesis-dun-i-dos-paràmetres.html#test-t-per-a-dues-mitjanes"><i class="fa fa-check"></i><b>5.1.2</b> Test t per a dues mitjanes</a></li>
<li class="chapter" data-level="5.1.3" data-path="contrastos-dhipòtesis-dun-i-dos-paràmetres.html"><a href="contrastos-dhipòtesis-dun-i-dos-paràmetres.html#tests-t-amb-r"><i class="fa fa-check"></i><b>5.1.3</b> Tests t amb R</a></li>
<li class="chapter" data-level="5.1.4" data-path="contrastos-dhipòtesis-dun-i-dos-paràmetres.html"><a href="contrastos-dhipòtesis-dun-i-dos-paràmetres.html#exemples"><i class="fa fa-check"></i><b>5.1.4</b> Exemples</a></li>
<li class="chapter" data-level="5.1.5" data-path="contrastos-dhipòtesis-dun-i-dos-paràmetres.html"><a href="contrastos-dhipòtesis-dun-i-dos-paràmetres.html#tests-no-paramètrics"><i class="fa fa-check"></i><b>5.1.5</b> Tests no paramètrics</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="contrastos-dhipòtesis-dun-i-dos-paràmetres.html"><a href="contrastos-dhipòtesis-dun-i-dos-paràmetres.html#sec:contrvar"><i class="fa fa-check"></i><b>5.2</b> Contrastos de variàncies</a><ul>
<li class="chapter" data-level="5.2.1" data-path="contrastos-dhipòtesis-dun-i-dos-paràmetres.html"><a href="contrastos-dhipòtesis-dun-i-dos-paràmetres.html#test-chi2-duna-variància"><i class="fa fa-check"></i><b>5.2.1</b> Test <span class="math inline">\(\chi^2\)</span> d’una variància</a></li>
<li class="chapter" data-level="5.2.2" data-path="contrastos-dhipòtesis-dun-i-dos-paràmetres.html"><a href="contrastos-dhipòtesis-dun-i-dos-paràmetres.html#test-f-per-a-dues-variàncies"><i class="fa fa-check"></i><b>5.2.2</b> Test F per a dues variàncies</a></li>
<li class="chapter" data-level="5.2.3" data-path="contrastos-dhipòtesis-dun-i-dos-paràmetres.html"><a href="contrastos-dhipòtesis-dun-i-dos-paràmetres.html#tests-no-paramètrics-1"><i class="fa fa-check"></i><b>5.2.3</b> Tests no paramètrics</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="contrastos-dhipòtesis-dun-i-dos-paràmetres.html"><a href="contrastos-dhipòtesis-dun-i-dos-paràmetres.html#contrastos-per-a-proporcions"><i class="fa fa-check"></i><b>5.3</b> Contrastos per a proporcions</a><ul>
<li class="chapter" data-level="5.3.1" data-path="contrastos-dhipòtesis-dun-i-dos-paràmetres.html"><a href="contrastos-dhipòtesis-dun-i-dos-paràmetres.html#contrastos-per-a-una-proporció"><i class="fa fa-check"></i><b>5.3.1</b> Contrastos per a una proporció</a></li>
<li class="chapter" data-level="5.3.2" data-path="contrastos-dhipòtesis-dun-i-dos-paràmetres.html"><a href="contrastos-dhipòtesis-dun-i-dos-paràmetres.html#contrastos-per-a-2-proporcions-emprant-mostres-independents"><i class="fa fa-check"></i><b>5.3.2</b> Contrastos per a 2 proporcions emprant mostres independents</a></li>
<li class="chapter" data-level="5.3.3" data-path="contrastos-dhipòtesis-dun-i-dos-paràmetres.html"><a href="contrastos-dhipòtesis-dun-i-dos-paràmetres.html#contrastos-per-a-2-proporcions-emprant-mostres-aparellades"><i class="fa fa-check"></i><b>5.3.3</b> Contrastos per a 2 proporcions emprant mostres aparellades</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="contrastos-de-bondat-dajust.html"><a href="contrastos-de-bondat-dajust.html"><i class="fa fa-check"></i><b>6</b> Contrastos de bondat d’ajust</a><ul>
<li class="chapter" data-level="6.1" data-path="contrastos-de-bondat-dajust.html"><a href="contrastos-de-bondat-dajust.html#bondat-dajust"><i class="fa fa-check"></i><b>6.1</b> Bondat d’ajust</a></li>
<li class="chapter" data-level="6.2" data-path="contrastos-de-bondat-dajust.html"><a href="contrastos-de-bondat-dajust.html#test-chi2-de-pearson"><i class="fa fa-check"></i><b>6.2</b> Test <span class="math inline">\(\chi^2\)</span> de Pearson</a><ul>
<li class="chapter" data-level="6.2.1" data-path="contrastos-de-bondat-dajust.html"><a href="contrastos-de-bondat-dajust.html#el-test-bàsic"><i class="fa fa-check"></i><b>6.2.1</b> El test bàsic</a></li>
<li class="chapter" data-level="6.2.2" data-path="contrastos-de-bondat-dajust.html"><a href="contrastos-de-bondat-dajust.html#mètode-de-montecarlo"><i class="fa fa-check"></i><b>6.2.2</b> Mètode de Montecarlo</a></li>
<li class="chapter" data-level="6.2.3" data-path="contrastos-de-bondat-dajust.html"><a href="contrastos-de-bondat-dajust.html#test-chi2-amb-paràmetres-poblacionals-desconeguts"><i class="fa fa-check"></i><b>6.2.3</b> Test <span class="math inline">\(\chi^2\)</span> amb paràmetres poblacionals desconeguts</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="contrastos-de-bondat-dajust.html"><a href="contrastos-de-bondat-dajust.html#test-de-kolmogorov-smirnov"><i class="fa fa-check"></i><b>6.3</b> Test de Kolmogorov-Smirnov</a></li>
<li class="chapter" data-level="6.4" data-path="contrastos-de-bondat-dajust.html"><a href="contrastos-de-bondat-dajust.html#test-de-kolmogorov-smirnov-lilliefors"><i class="fa fa-check"></i><b>6.4</b> Test de Kolmogorov-Smirnov-Lilliefors</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="contrastos-dindependència-i-homogeneïtat.html"><a href="contrastos-dindependència-i-homogeneïtat.html"><i class="fa fa-check"></i><b>7</b> Contrastos d’independència i homogeneïtat</a><ul>
<li class="chapter" data-level="7.1" data-path="contrastos-dindependència-i-homogeneïtat.html"><a href="contrastos-dindependència-i-homogeneïtat.html#test-chi2-dindependència"><i class="fa fa-check"></i><b>7.1</b> Test <span class="math inline">\(\chi^2\)</span> d’independència</a></li>
<li class="chapter" data-level="7.2" data-path="contrastos-dindependència-i-homogeneïtat.html"><a href="contrastos-dindependència-i-homogeneïtat.html#test-chi2-dhomogeneïtat"><i class="fa fa-check"></i><b>7.2</b> Test <span class="math inline">\(\chi^2\)</span> d’homogeneïtat</a></li>
<li class="chapter" data-level="7.3" data-path="contrastos-dindependència-i-homogeneïtat.html"><a href="contrastos-dindependència-i-homogeneïtat.html#test-chi2-de-tendència-opcional"><i class="fa fa-check"></i><b>7.3</b> Test <span class="math inline">\(\chi^2\)</span> de tendència (Opcional)</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="introducció-a-lestadística-multidimensional.html"><a href="introducció-a-lestadística-multidimensional.html"><i class="fa fa-check"></i><b>8</b> Introducció a l’estadística multidimensional</a><ul>
<li class="chapter" data-level="8.1" data-path="introducció-a-lestadística-multidimensional.html"><a href="introducció-a-lestadística-multidimensional.html#poblacions-vectors-aleatoris"><i class="fa fa-check"></i><b>8.1</b> Poblacions: vectors aleatoris</a><ul>
<li class="chapter" data-level="8.1.1" data-path="introducció-a-lestadística-multidimensional.html"><a href="introducció-a-lestadística-multidimensional.html#covariància"><i class="fa fa-check"></i><b>8.1.1</b> Covariància</a></li>
<li class="chapter" data-level="8.1.2" data-path="introducció-a-lestadística-multidimensional.html"><a href="introducció-a-lestadística-multidimensional.html#correlació"><i class="fa fa-check"></i><b>8.1.2</b> Correlació</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="introducció-a-lestadística-multidimensional.html"><a href="introducció-a-lestadística-multidimensional.html#estadística-descriptiva-mostres"><i class="fa fa-check"></i><b>8.2</b> Estadística descriptiva: Mostres</a><ul>
<li class="chapter" data-level="8.2.1" data-path="introducció-a-lestadística-multidimensional.html"><a href="introducció-a-lestadística-multidimensional.html#covariàncies"><i class="fa fa-check"></i><b>8.2.1</b> Covariàncies</a></li>
<li class="chapter" data-level="8.2.2" data-path="introducció-a-lestadística-multidimensional.html"><a href="introducció-a-lestadística-multidimensional.html#correlació-de-pearson"><i class="fa fa-check"></i><b>8.2.2</b> Correlació de Pearson</a></li>
<li class="chapter" data-level="8.2.3" data-path="introducció-a-lestadística-multidimensional.html"><a href="introducció-a-lestadística-multidimensional.html#correlació-de-spearman"><i class="fa fa-check"></i><b>8.2.3</b> Correlació de Spearman</a></li>
<li class="chapter" data-level="8.2.4" data-path="introducció-a-lestadística-multidimensional.html"><a href="introducció-a-lestadística-multidimensional.html#contrastos-de-correlació"><i class="fa fa-check"></i><b>8.2.4</b> Contrastos de correlació</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="anova.html"><a href="anova.html"><i class="fa fa-check"></i><b>9</b> ANOVA</a><ul>
<li class="chapter" data-level="9.1" data-path="anova.html"><a href="anova.html#nocions-bàsiques"><i class="fa fa-check"></i><b>9.1</b> Nocions bàsiques</a></li>
<li class="chapter" data-level="9.2" data-path="anova.html"><a href="anova.html#anova-d1-via"><i class="fa fa-check"></i><b>9.2</b> ANOVA d’1 via</a><ul>
<li class="chapter" data-level="9.2.1" data-path="anova.html"><a href="anova.html#contrast-bàsic"><i class="fa fa-check"></i><b>9.2.1</b> Contrast bàsic</a></li>
<li class="chapter" data-level="9.2.2" data-path="anova.html"><a href="anova.html#amb-r-2"><i class="fa fa-check"></i><b>9.2.2</b> Amb R</a></li>
<li class="chapter" data-level="9.2.3" data-path="anova.html"><a href="anova.html#comparacions-posteriors-per-parelles"><i class="fa fa-check"></i><b>9.2.3</b> Comparacions posteriors per parelles</a></li>
<li class="chapter" data-level="9.2.4" data-path="anova.html"><a href="anova.html#verificació-de-les-condicions"><i class="fa fa-check"></i><b>9.2.4</b> Verificació de les condicions</a></li>
<li class="chapter" data-level="9.2.5" data-path="anova.html"><a href="anova.html#test-no-paramètric"><i class="fa fa-check"></i><b>9.2.5</b> Test no paramètric</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="anova.html"><a href="anova.html#anova-de-blocs"><i class="fa fa-check"></i><b>9.3</b> ANOVA de blocs</a><ul>
<li class="chapter" data-level="9.3.1" data-path="anova.html"><a href="anova.html#contrast-bàsic-1"><i class="fa fa-check"></i><b>9.3.1</b> Contrast bàsic</a></li>
<li class="chapter" data-level="9.3.2" data-path="anova.html"><a href="anova.html#amb-r-3"><i class="fa fa-check"></i><b>9.3.2</b> Amb R</a></li>
<li class="chapter" data-level="9.3.3" data-path="anova.html"><a href="anova.html#comparacions-posteriors-per-parelles-1"><i class="fa fa-check"></i><b>9.3.3</b> Comparacions posteriors per parelles</a></li>
<li class="chapter" data-level="9.3.4" data-path="anova.html"><a href="anova.html#contrast-no-paramètric"><i class="fa fa-check"></i><b>9.3.4</b> Contrast no paramètric</a></li>
</ul></li>
<li class="chapter" data-level="9.4" data-path="anova.html"><a href="anova.html#anova-de-2-vies"><i class="fa fa-check"></i><b>9.4</b> ANOVA de 2 vies</a><ul>
<li class="chapter" data-level="9.4.1" data-path="anova.html"><a href="anova.html#contrast-bàsic-2"><i class="fa fa-check"></i><b>9.4.1</b> Contrast bàsic</a></li>
<li class="chapter" data-level="9.4.2" data-path="anova.html"><a href="anova.html#amb-r-4"><i class="fa fa-check"></i><b>9.4.2</b> Amb R</a></li>
</ul></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Matemàtiques II</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="repàs-de-la-distribució-normal" class="section level1">
<h1><span class="header-section-number">Tema 1</span> Repàs de la distribució normal</h1>
<div id="propietats-de-la-distribució-normal" class="section level2">
<h2><span class="header-section-number">1.1</span> Propietats de la distribució normal</h2>
<p>Una variable aleatòria contínua <span class="math inline">\(X\)</span> és <strong>normal</strong> de paràmetres <span class="math inline">\(\mu\)</span> i <span class="math inline">\(\sigma\)</span>, i ho indicarem escrivint <span class="math inline">\(X\sim N(\mu,\sigma)\)</span>, quan la seva funció de densitat és</p>
<p><img src="Bioestadistica-II_files/figure-html/censored.png" width="35%" style="display: block; margin: auto;" /></p>
<p>Naturalment, no cal saber aquesta fórmula. El que cal saber és que:</p>
<ul>
<li><p>Una variable aleatòria normal <span class="math inline">\(X\)</span> és contínua, i per tant <span class="math inline">\(P(X=x)=0\)</span>, <span class="math inline">\(P(X\leqslant x)=P(X&lt;x)\)</span> etc.</p></li>
<li><p>Si <span class="math inline">\(X\sim N(\mu,\sigma)\)</span>, aleshores el seu valor esperat és <span class="math inline">\(E(X)=\mu\)</span> i la seva desviació típica és <span class="math inline">\(\sigma_X=\sigma\)</span></p></li>
</ul>
<p>Una variable aleatòria normal és <strong>típica</strong> (o <strong>estàndard</strong>) quan <span class="math inline">\(\mu=0\)</span> i <span class="math inline">\(\sigma=1\)</span>; la indicarem usualment amb <span class="math inline">\(Z\)</span>. Per tant, si <span class="math inline">\(Z\sim N(0,1)\)</span>, <span class="math inline">\(E(Z)=0\)</span> i <span class="math inline">\(\sigma_Z=1\)</span>.</p>
<p>La gràfica de la densitat d’una variable aleatòria normal és la famosa <strong>campana de Gauss</strong>:</p>
<p><img src="Bioestadistica-II_files/figure-html/unnamed-chunk-11-1.png" width="50%" style="display: block; margin: auto;" /></p>
<p>La gràfica de la densitat d’una variable aleatòria normal és també la menys famosa <strong>gràfica del capell del gendarme</strong>:</p>
<p><img src="Bioestadistica-II_files/figure-html/gendarme.png" width="40%" style="display: block; margin: auto;" /></p>
<p>La distribució normal és una distribució teòrica, no la trobareu exacta en la pràctica. I malgrat el seu nom, no és més “normal” que les altres distribucions que estudiarem.</p>
<p><img src="Bioestadistica-II_files/figure-html/paranormal.png" width="40%" style="display: block; margin: auto;" /></p>
<p>La distribució normal és important perquè aproxima bé moltes distribucions reals, perquè:</p>
<blockquote>
<p>Moltes variables aleatòries que consisteixen a prendre <span class="math inline">\(n\)</span> observacions independents d’una o diverses variables aleatòries i sumar-les, tenen distribució aproximadament normal quan <span class="math inline">\(n\)</span> és gran, encara que les variables aleatòries de partida no ho siguin.</p>
</blockquote>
<p>Per exemple:</p>
<ul>
<li>Si <span class="math inline">\(X\)</span> és una variable aleatòria binomial <em>B(n,p)</em>, amb <span class="math inline">\(n\)</span> gran, alehores <span class="math inline">\(X\)</span> és aproximadament <span class="math inline">\(N(np,\sqrt{np(1-p)})\)</span>, en el sentit que les dues funcions de densitat (salvant la diferència pel fet que la binomial és discreta i la normal contínua) són semblants:</li>
</ul>
<p><img src="Bioestadistica-II_files/figure-html/unnamed-chunk-14-1.png" width="50%" style="display: block; margin: auto;" /></p>
<ul>
<li>Si <span class="math inline">\(X\)</span> és una variable aleatòria de Poisson <span class="math inline">\(Po(\lambda)\)</span> i <span class="math inline">\(\lambda\)</span> és gran, aleshores <span class="math inline">\(X\)</span> és aproximadament <span class="math inline">\(N(\lambda,\sqrt{\lambda})\)</span></li>
</ul>
<p><img src="Bioestadistica-II_files/figure-html/unnamed-chunk-15-1.png" width="50%" style="display: block; margin: auto;" /></p>

<div class="rmdcaution">
<p>Quan s’aproxima una variable binomial o Poisson <span class="math inline">\(X\)</span> per mitjà d’una variable normal <span class="math inline">\(Y\)</span>, és convenient aplicar l’anomenada <strong>correcció de continuïtat</strong>: per a cada <span class="math inline">\(n\in \mathbb{N}\)</span>, interpretar <span class="math inline">\(P(X\leqslant n)\)</span> com <span class="math inline">\(P(X&lt; n+1/2)\)</span> i aleshores aproximar:</p>
<ul>
<li><p><span class="math inline">\(P(X\leqslant n)\)</span> per mitjà de <span class="math inline">\(P(Y&lt; n+1/2)\)</span></p></li>
<li><p><span class="math inline">\(P(X=n)\)</span> per mitjà de <span class="math inline">\(P(n-1/2&lt; Y&lt; n+1/2)\)</span></p></li>
</ul>
Vegeu l’Exemple <a href="repàs-de-la-distribució-normal.html#exm:corrcont1">1.1</a> a la propera secció.
</div>

<p>Una de les propietats clau de la distribució normal és la seva simetria:</p>

<div class="rmdimportant">
Si <span class="math inline">\(X\sim N(\mu,\sigma)\)</span>, la seva densitat <span class="math inline">\(f_X\)</span> és simètrica respecte de <span class="math inline">\(x=\mu\)</span>, és a dir,
<span class="math display">\[
f_{X}(\mu-x)=f_{X}(\mu+x),
\]</span>
i té el màxim en <span class="math inline">\(x=\mu\)</span>.
</div>

<p><img src="Bioestadistica-II_files/figure-html/unnamed-chunk-18-1.png" width="80%" style="display: block; margin: auto;" /></p>
<p>Diem aleshores que <span class="math inline">\(\mu\)</span> és la <strong>moda</strong> de <span class="math inline">\(X\)</span>.</p>

<div class="rmdnote">
Recordem que no té sentit definir la moda d’una variable contínua <span class="math inline">\(X\)</span> com el valor <span class="math inline">\(x_0\)</span> tal que <span class="math inline">\(P(X=x_0)\)</span> sigui màxim, perquè <span class="math inline">\(P(X=x)=0\)</span> per a tot <span class="math inline">\(x\in \mathbb{R}\)</span>. Es defineix llavors la <strong>moda</strong> d’una variable contínua <span class="math inline">\(X\)</span> com el valor (o els valors) <span class="math inline">\(x_0\)</span> tal(s) que <span class="math inline">\(f_X(x_0)\)</span> és màxim.
</div>

<p>En particular, si <span class="math inline">\(Z\sim N(0,1)\)</span>, llavors <span class="math inline">\(f_{Z}\)</span> és simètrica al voltant de <span class="math inline">\(x=0\)</span>, és a dir, <span class="math inline">\(f_{Z}(-x)=f_{Z}(x)\)</span>, i la moda de <span class="math inline">\(Z\)</span> és 0.</p>
<p>Si la <span class="math inline">\(\mu\)</span> creix, el màxim es desplaça a la dreta, i amb ell tota la corba de manera rígida.</p>
<p><img src="Bioestadistica-II_files/figure-html/unnamed-chunk-20-1.png" width="80%" style="display: block; margin: auto;" /></p>
<p>Si la <span class="math inline">\(\sigma\)</span> creix, la corba s’aplata: en augmentar la desviació típica, els valors s’allunyen més del valor mitjà.</p>
<p><img src="Bioestadistica-II_files/figure-html/unnamed-chunk-21-1.png" width="80%" style="display: block; margin: auto;" /></p>
<p>Vegem l’efecte combinat:</p>
<p><img src="Bioestadistica-II_files/figure-html/unnamed-chunk-22-1.png" width="80%" style="display: block; margin: auto;" /></p>
<p>Recordem que la funció de distribució d’una variable aleatòria contínua <span class="math inline">\(X\)</span>
<span class="math display">\[
F_X(x)=P(X\leqslant x)
\]</span>
és l’àrea compresa entre la corba definida per la densitat <span class="math inline">\(y=f_X(x)\)</span> i l’eix d’abscisses a l’esquerra de <span class="math inline">\(x\)</span>.</p>
<p><img src="Bioestadistica-II_files/figure-html/unnamed-chunk-23-1.png" width="80%" style="display: block; margin: auto;" /></p>
<p>La simetria de <span class="math inline">\(f_X\)</span> fa que les àrees a l’esquerra de <span class="math inline">\(\mu-x\)</span> i a la dreta de <span class="math inline">\(\mu+x\)</span> siguin iguals.</p>
<p><img src="Bioestadistica-II_files/figure-html/unnamed-chunk-24-1.png" width="80%" style="display: block; margin: auto;" /></p>
<p>És a dir,
<span class="math display">\[
P(X\leqslant\mu-x) = P(X\geqslant\mu+x)=1-P(X\leqslant\mu+x)
\]</span>
En particular (prenent <span class="math inline">\(x=0\)</span>)
<span class="math display">\[
P(X\leqslant\mu)=1-P(X\leqslant\mu)\Rightarrow P(X\leqslant\mu)=0.5,
\]</span>
i per tant <span class="math inline">\(\mu\)</span> és també la <em>mediana</em> de <span class="math inline">\(X\)</span>.</p>

<div class="rmdimportant">
Si <span class="math inline">\(X\sim N(\mu,\sigma)\)</span>, <span class="math inline">\(\mu\)</span> és la moda, la mitjana, o esperança, i la mediana de <span class="math inline">\(X\)</span>.
</div>

<p>En particular, si <span class="math inline">\(Z\sim N(0,1)\)</span>, les àrees a l’esquerra de <span class="math inline">\(-z\)</span> i a la dreta de <span class="math inline">\(z\)</span> són iguals,
<span class="math display">\[
P(Z\leqslant-z)=P(Z\geqslant z)=1-P(Z\leqslant z),
\]</span>
i la mediana de <span class="math inline">\(Z\)</span> és 0.</p>
<p>Indicarem amb <span class="math inline">\(z_q\)</span> el <span class="math inline">\(q\)</span><strong>-quantil</strong> d’una variable normal estàndard <span class="math inline">\(Z\)</span>. És a dir, <span class="math inline">\(z_q\)</span> és el valor tal que <span class="math inline">\(P(Z\leqslant z_q)=q\)</span>.</p>
<p>A banda del fet que <span class="math inline">\(z_{0.5}=0\)</span> (la mediana de <span class="math inline">\(Z\)</span> és 0), hi ha dos quantils més de la normal estándard que heu de saber “de memòria”:</p>
<ul>
<li><p><span class="math inline">\(z_{0.95}=1.64\)</span>; és a dir, <span class="math inline">\(P(Z\leqslant 1.64)=0.95\)</span> i per tant <span class="math inline">\(P(Z\leqslant-1.64)=P(Z\geqslant 1.64)=0.05\)</span>.</p></li>
<li><p><span class="math inline">\(z_{0.975}=1.96\)</span>; és a dir, <span class="math inline">\(P(Z\leqslant 1.96)=0.975\)</span> i per tant <span class="math inline">\(P(Z\leqslant-1.96)=P(Z\leqslant 1.96)=0.025\)</span></p></li>
</ul>

<div class="rmdmercifulgod">
Molt sovint el valor 1.96 de <span class="math inline">\(z_{0.975}\)</span> s’aproxima per 2. Teniu permís per fer-ho quan no disposeu de mitjans (R, aplis de mòbil) per calcular quantils.
</div>

</div>
<div id="amb-r" class="section level2">
<h2><span class="header-section-number">1.2</span> Amb R</h2>
<p>Per calcular probabilitats d’una variable normal emprant R, heu de recordar que la normal és <code>norm</code>.
Per tant, si <span class="math inline">\(X\sim N(\mu,\sigma)\)</span>:</p>
<ul>
<li><p><code>dnorm(x,mu,sigma)</code> dóna el valor de la densitat <span class="math inline">\(f_X(x)\)</span></p></li>
<li><p><code>pnorm(x,mu,sigma)</code> dóna el valor de la distribució <span class="math inline">\(F_X(x)=P(X\leqslant x)\)</span>; afegint-hi el paràmetre <code>lower.tail=FALSE</code> dóna el valor de <span class="math inline">\(P(X&gt;x)\)</span></p></li>
<li><p><code>qnorm(q,mu,sigma)</code> dóna el <span class="math inline">\(q\)</span>-quantil de <span class="math inline">\(X\)</span></p></li>
<li><p><code>rnorm(N,mu,sigma)</code> dóna un vector de <span class="math inline">\(n\)</span> nombres aleatoris generats amb aquesta distribució</p></li>
</ul>
<p>A la normal estàndard no és necessari entrar-hi <span class="math inline">\(\mu=0\)</span> i <span class="math inline">\(\sigma=1\)</span>, són els valors per defecte d’aquests paràmetres.</p>
<p>Vegem-ne alguns exemples:</p>
<ul>
<li>Si <span class="math inline">\(X\sim N(3,0.5)\)</span>, què val <span class="math inline">\(P(X\leqslant 2)\)</span>?</li>
</ul>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb1-1" data-line-number="1"><span class="kw">pnorm</span>(<span class="dv">2</span>,<span class="dv">3</span>,<span class="fl">0.5</span>)</a></code></pre></div>
<pre><code>## [1] 0.02275013</code></pre>
<ul>
<li>Si <span class="math inline">\(X\sim N(-2,0.3)\)</span>, què val <span class="math inline">\(P(X\geqslant-1.8)\)</span>?</li>
</ul>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb3-1" data-line-number="1"><span class="dv">1</span><span class="op">-</span><span class="kw">pnorm</span>(<span class="op">-</span><span class="fl">1.8</span>,<span class="op">-</span><span class="dv">2</span>,<span class="fl">0.3</span>)</a></code></pre></div>
<pre><code>## [1] 0.2524925</code></pre>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb5-1" data-line-number="1"><span class="kw">pnorm</span>(<span class="op">-</span><span class="fl">1.8</span>,<span class="op">-</span><span class="dv">2</span>,<span class="fl">0.3</span>,<span class="dt">lower.tail=</span><span class="ot">FALSE</span>)  </a></code></pre></div>
<pre><code>## [1] 0.2524925</code></pre>
<ul>
<li><p>Si <span class="math inline">\(X\sim N(0,1)\)</span>, què val <span class="math inline">\(P(-1\leqslant X\leqslant 1)\)</span>?</p>
<p>Com que <span class="math inline">\(P(-1\leqslant X\leqslant 1)=P(X\leqslant 1)-P(X\leqslant-1)\)</span>,</p></li>
</ul>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb7-1" data-line-number="1"><span class="kw">pnorm</span>(<span class="dv">1</span>)<span class="op">-</span><span class="kw">pnorm</span>(<span class="op">-</span><span class="dv">1</span>)</a></code></pre></div>
<pre><code>## [1] 0.6826895</code></pre>
<ul>
<li>Què val el primer quartil d’una variable <span class="math inline">\(N(3,0.5)\)</span>?</li>
</ul>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb9-1" data-line-number="1"><span class="kw">qnorm</span>(<span class="fl">0.25</span>,<span class="dv">3</span>,<span class="fl">0.5</span>)</a></code></pre></div>
<pre><code>## [1] 2.662755</code></pre>

<div class="rmdexercici">
Comprovau els valors de <span class="math inline">\(z_{0.95}\)</span> i <span class="math inline">\(z_{0.975}\)</span> donats al final de la secció anterior.
</div>


<div class="example">
<p><span id="exm:corrcont1" class="example"><strong>Exemple 1.1  </strong></span>A la secció anterior, us hem dit que una variable binomial <span class="math inline">\(B(n,p)\)</span> amb <span class="math inline">\(n\)</span> gran s’aproxima per mitjà d’una variable normal <span class="math inline">\(N(np,\sqrt{np(1-p)})\)</span>. Així, per exemple, una variable <span class="math inline">\(X\sim B(400,0.2)\)</span> s’aproxima per mitjà d’una variable <span class="math inline">\(Y\sim N(400\cdot 0.2,\sqrt{400\cdot 0.2\cdot 0.8})=N(80,8)\)</span>. Vegem amb alguns exemples que aquesta aproximació és millor aplicant-hi la correcció de continuïtat:</p>
</div>

<ul>
<li><span class="math inline">\(P(X\leqslant 70)\)</span>:</li>
</ul>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb11-1" data-line-number="1"><span class="kw">pbinom</span>(<span class="dv">70</span>,<span class="dv">400</span>,<span class="fl">0.2</span>)</a></code></pre></div>
<pre><code>## [1] 0.1163917</code></pre>
<ul>
<li><span class="math inline">\(P(Y&lt; 70+1/2)\)</span>:</li>
</ul>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb13-1" data-line-number="1"><span class="kw">pnorm</span>(<span class="fl">70.5</span>,<span class="dv">80</span>,<span class="dv">8</span>)</a></code></pre></div>
<pre><code>## [1] 0.1175152</code></pre>
<ul>
<li><span class="math inline">\(P(Y\leqslant 70)\)</span>:</li>
</ul>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb15-1" data-line-number="1"><span class="kw">pnorm</span>(<span class="dv">70</span>,<span class="dv">80</span>,<span class="dv">8</span>)</a></code></pre></div>
<pre><code>## [1] 0.1056498</code></pre>
<ul>
<li><span class="math inline">\(P(X=70)\)</span>:</li>
</ul>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb17-1" data-line-number="1"><span class="kw">dbinom</span>(<span class="dv">70</span>,<span class="dv">400</span>,<span class="fl">0.2</span>) </a></code></pre></div>
<pre><code>## [1] 0.02338443</code></pre>
<ul>
<li><span class="math inline">\(P(70-1/2&lt; Y&lt; 70+1/2)\)</span>:</li>
</ul>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb19-1" data-line-number="1"><span class="kw">pnorm</span>(<span class="fl">70.5</span>,<span class="dv">80</span>,<span class="dv">8</span>)<span class="op">-</span><span class="kw">pnorm</span>(<span class="fl">69.5</span>,<span class="dv">80</span>,<span class="dv">8</span>) </a></code></pre></div>
<pre><code>## [1] 0.02283949</code></pre>
<ul>
<li><span class="math inline">\(P(Y=70)\)</span>:</li>
</ul>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb21-1" data-line-number="1"><span class="kw">dnorm</span>(<span class="dv">70</span>,<span class="dv">80</span>,<span class="dv">8</span>) </a></code></pre></div>
<pre><code>## [1] 0.02283114</code></pre>

<div class="rmderror">
<strong>NO!</strong> <code>dnorm(70,80,8)</code> és la funció de densitat de <span class="math inline">\(Y\)</span> (la fórmula que hem censurat al començament d’aquest tema) aplicada a 70, i no és igual a la probabilitat que <span class="math inline">\(Y\)</span> valgui 70. Recordau que <span class="math inline">\(P(Y=70)=0\)</span> perquè <span class="math inline">\(Y\)</span> és contínua.
</div>

</div>
<div id="combinacions-lineals" class="section level2">
<h2><span class="header-section-number">1.3</span> Combinacions lineals</h2>
<p>El resultat següent descriu el comportament de la mitjana i la variància d’una combinació lineal de variables aleatòries:</p>

<div class="theorem">
<p><span id="thm:combvar" class="theorem"><strong>Teorema 1.1  </strong></span>Siguin <span class="math inline">\(Y_1,\ldots,Y_n\)</span> variables aleatòries, cada <span class="math inline">\(Y_i\)</span> de mitjana <span class="math inline">\(\mu_i\)</span> i variància <span class="math inline">\(\sigma_i^2\)</span>, i siguin
<span class="math inline">\(a_1,\ldots,a_n,b\in \mathbb{R}\)</span>. Sigui <span class="math inline">\(Y\)</span> la variable aleatòria
<span class="math display">\[
Y=a_1Y_1+\cdots+a_nY_n+b.
\]</span>
Aleshores</p>
<ol style="list-style-type: decimal">
<li><p>La mitjana de <span class="math inline">\(Y\)</span> és
<span class="math display">\[
  \mu_Y=a_1\mu_1+\cdots+a_n\mu_n+b.
\]</span></p></li>
<li><p>Si <span class="math inline">\(Y_1,\ldots,Y_n\)</span> són <strong>independents</strong>, aleshores la variància de <span class="math inline">\(Y\)</span> és
<span class="math display">\[
  \sigma_Y^2=a_1^2\sigma_1^2+\cdots+a_n^2\sigma_n^2
\]</span>
i per tant la seva desviació típica és
<span class="math display">\[
  \sigma_Y=\sqrt{a_1^2\sigma_1^2+\cdots+a_n^2\sigma_n^2}.
\]</span></p></li>
</ol>
</div>

<p>Una altra propietat destacada de la distribució normal és que tota combinació lineal de variables aleatòries normals independents torna a ser normal:</p>

<div class="theorem">
<p><span id="thm:combnormal" class="theorem"><strong>Teorema 1.2  </strong></span>Si <span class="math inline">\(Y_1,\ldots,Y_n\)</span> son variables aleatòries normals independents, cada <span class="math inline">\(Y_i\sim N(\mu_i,\sigma_i)\)</span>, i <span class="math inline">\(a_1,\ldots,a_n,b\in \mathbb{R}\)</span>, aleshores
<span class="math display">\[
Y=a_1Y_1+\cdots+a_nY_n+b
\]</span>
és una variable aleatòria <span class="math inline">\(N(\mu,\sigma)\)</span> amb <span class="math inline">\(\mu\)</span> i <span class="math inline">\(\sigma\)</span> els que toquin pel teorema anterior:</p>
<ul>
<li><p><span class="math inline">\(\mu=a_1\mu_1+\cdots+a_n\mu_n+b\)</span></p></li>
<li><p><span class="math inline">\(\sigma=\sqrt{a_1^2\sigma_1^2+\cdots+a_n^2\sigma_n^2}\)</span></p></li>
</ul>
</div>

<p>Com a cas particular, obtenim que una transformació afí d’una variable aleatòria normal torna a ser normal:</p>

<div class="theorem">
<p><span id="thm:tipi" class="theorem"><strong>Teorema 1.3  </strong></span>Si <span class="math inline">\(X\sim N(\mu,\sigma)\)</span> i <span class="math inline">\(a,b\in \mathbb{R}\)</span>, llavors <span class="math inline">\(aX+b\)</span> també és normal, i en concret és <span class="math inline">\(N(a\mu+b,|a|\cdot\sigma)\)</span>.</p>
<p>En particular, si <span class="math inline">\(X\sim N(\mu,\sigma)\)</span>, llavors la seva <strong>tipificada</strong>
<span class="math display">\[
Z=\dfrac{X-\mu}{\sigma}
\]</span>
és <span class="math inline">\(N(0,1)\)</span>.</p>
</div>

<p>Les probabilitats de la normal tipificada determinen les de la normal original, perquè si <span class="math inline">\(X\sim N(\mu,\sigma)\)</span>,
<span class="math display">\[
\begin{array}{rl}
P(a\leqslant X\leqslant b) &amp; \displaystyle  =P\Big( \frac{a-\mu}{\sigma}\leqslant\frac{X-\mu}{\sigma}\leqslant\frac{b-\mu}{\sigma}\Big)\\ &amp; \displaystyle =P\Big(\frac{a-\mu}{\sigma}\leqslant Z\leqslant\frac{b-\mu}{\sigma}\Big)
\end{array}
\]</span></p>

<div class="rmdnote">
Que tota combinació lineal de variables normals torni a ser del mateix tipus, és a dir, normal, és una propietat molt útil de les variables normals que pocs altres tipus de variables aleatòries tenen. Per exemple, si <span class="math inline">\(X\)</span> és una variable binomial <span class="math inline">\(B(n,p)\)</span> amb <span class="math inline">\(p\neq 0\)</span>, <span class="math inline">\(2X\)</span> no és cap variable binomial, perquè només pren valors parells i una variable binomial <span class="math inline">\(B(m,q)\)</span> pot prendre tots els valors entre 0 i <span class="math inline">\(m\)</span>.
</div>

</div>
<div id="intervals-de-referència" class="section level2">
<h2><span class="header-section-number">1.4</span> Intervals de referència</h2>
<p>Un <strong>interval de referència del <span class="math inline">\(100q\%\)</span></strong> per a una variable aleatòria <span class="math inline">\(X\)</span> és un interval <span class="math inline">\([a,b]\)</span> tal que
<span class="math display">\[
P(a\leqslant X\leqslant b)=q.
\]</span>
És a dir, un interval de referència del <span class="math inline">\(100q\%\)</span> per a <span class="math inline">\(X\)</span> és un interval que conté els valors de <span class="math inline">\(X\)</span> del <span class="math inline">\(100q\%\)</span> de subjectes de la població on està definida.</p>
<p>Els més comuns són els intervals de referència del 95% (<span class="math inline">\(q=0.95\)</span>), que satisfan que
<span class="math display">\[
P(a\leqslant X\leqslant b)=0.95
\]</span>
i són els, que per exemple, us donen com a valors de referència a les analítiques:</p>
<p><img src="Bioestadistica-II_files/figure-html/analit.png" width="80%" style="display: block; margin: auto;" /></p>

<div class="rmdnote">
Quan es parla d’un <strong>interval de referència</strong> sense donar-ne la probabilitat, se sobreentén sempre que és l’interval de referència del 95%.
</div>

<p>Quan <span class="math inline">\(X\sim N(\mu,\sigma)\)</span>, aquests intervals de referència es prenen <em>sempre centrats en la mitjana</em> <span class="math inline">\(\mu\)</span>, és a dir, de la forma <span class="math inline">\([\mu-x,\mu+x]\)</span>. Per calcular-los fàcilment, podem emprar el resultat següent:</p>

<div class="theorem">
<p><span id="thm:unnamed-chunk-43" class="theorem"><strong>Teorema 1.4  </strong></span>Si <span class="math inline">\(X\sim N(\mu,\sigma)\)</span>, un interval de referència del <span class="math inline">\(100q\%\)</span> és
<span class="math display">\[
[\mu- z_{(1+q)/2}\cdot \sigma, \mu+ z_{(1+q)/2}\cdot \sigma]
\]</span>
on <span class="math inline">\(z_{(1+q)/2}\)</span> indica el <span class="math inline">\((1+q)/2\)</span>-quantil de <span class="math inline">\(Z\sim N(0,1)\)</span>. L’escriurem
<span class="math display">\[
\mu\pm z_{(1+q)/2}\cdot \sigma.
\]</span></p>
</div>


<div class="rmdcorbes">
<p>En efecte:
<span class="math display">\[
\begin{array}{l}
P(\mu-x\leqslant X\leqslant\mu+x)=q\\
\qquad \Longleftrightarrow \displaystyle P\Big(\frac{\mu-x-\mu}{\sigma}\leqslant\frac{X-\mu}{\sigma}\leqslant\frac{\mu+x-\mu}{\sigma}\Big)=q\\
\qquad \Longleftrightarrow \displaystyle P(-x/{\sigma}\leqslant Z\leqslant{x}/{\sigma})=q\\
\qquad \Longleftrightarrow \displaystyle P(Z\leqslant{x}/{\sigma})-P(Z\leqslant-{x}/{\sigma})=q\\
\qquad \Longleftrightarrow \displaystyle P(Z\leqslant{x}/{\sigma})-(1-P(Z\leqslant{x}/{\sigma}))=q\\
\qquad \mbox{(per la simetria de $f_Z$ al voltant de 0)}\\
\qquad \Longleftrightarrow \displaystyle 2P(Z\leqslant{x}/{\sigma})=q+1\\
\qquad \Longleftrightarrow P(Z\leqslant{x}/{\sigma})=(1+q)/2\\
\qquad \Longleftrightarrow x/\sigma=
z_{(1+q)/2}\\
\qquad \Longleftrightarrow x=z_{(1+q)/2}\cdot \sigma
\end{array}
\]</span></p>
</div>

<p>En particular, com que si <span class="math inline">\(q=0.95\)</span>, aleshores <span class="math inline">\((1+q)/2=0.975\)</span> i llavors <span class="math inline">\(z_{0.975}=1.96\)</span>, i això sovint s’aproxima per 2, l’interval de referència del 95% per a <span class="math inline">\(X\sim N(\mu,\sigma)\)</span> és
<span class="math display">\[
\mu\pm 1.96\sigma
\]</span>
o simplement, per simplificar,
<span class="math display">\[
\mu\pm 2\sigma.
\]</span>
Això diu, bàsicament, que</p>
<blockquote>
<p>si una població segueix una distribució normal <span class="math inline">\(N(\mu,\sigma)\)</span>, un 95% dels seus individus tenen el seu valor de <span class="math inline">\(X\)</span> a distància como a màxim <span class="math inline">\(2\sigma\)</span> (“a dues sigmes”) de <span class="math inline">\(\mu\)</span>.</p>
</blockquote>

<div class="example">
<p><span id="exm:unnamed-chunk-45" class="example"><strong>Exemple 1.2  </strong></span>Segons l’OMS, les alçades de les dones europees de 18 anys segueixen una llei <span class="math inline">\(N(163.1,18.53)\)</span>. Vull trobar un interval d’alçades centrat en la mitjana que contengui les de la meitat de les europees de 18 anys. És, a dir, vull trobar l’interval de referència del 50% per a la variable aleatòria <span class="math inline">\(X\)</span> definida per les alçades de les dones europees de 18 anys.</p>
<p>Com que <span class="math inline">\(X\sim N(163.1,18.53)\)</span> i si <span class="math inline">\(q=0.5\)</span>, aleshores <span class="math inline">\((1+q)/2=0.75\)</span>, aquest interval és</p>
</div>

<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb23-1" data-line-number="1"><span class="fl">163.1</span><span class="op">+</span><span class="kw">qnorm</span>(<span class="fl">0.75</span>)<span class="op">*</span><span class="fl">18.53</span><span class="op">*</span><span class="kw">c</span>(<span class="op">-</span><span class="dv">1</span>,<span class="dv">1</span>)</a></code></pre></div>
<pre><code>## [1] 150.6017 175.5983</code></pre>
<p>Arrodonint a cm, és l’interval [151, 176]. Per tant, la meitat de les dones europees de 18 anys fan entre
1.51 m i 1.76 m d’alçada.</p>

<div class="example">
<p><span id="exm:unnamed-chunk-47" class="example"><strong>Exemple 1.3  </strong></span>Quin és l’interval de referència per a les alçades de les dones europees de 18 anys?</p>
</div>

<p>Com que sobreentenem que es tracta de l’interval de referència del 95%, és
<span class="math display">\[
163.1\pm 1.96\times 18.53\Longrightarrow [127, 199]
\]</span></p>
</div>
<div id="el-z-score" class="section level2">
<h2><span class="header-section-number">1.5</span> El z-score</h2>
<p>El <strong>z-score</strong> (o <strong>valor z</strong>, <strong>puntuació z</strong>) d’un valor <span class="math inline">\(x_0\)</span> respecte d’una distribució <span class="math inline">\(N(\mu,\sigma)\)</span> és
<span class="math display">\[
\frac{x_0-\mu}{\sigma}.
\]</span>
És a dir, el z-score de <span class="math inline">\(x_0\)</span> és el resultat de “tipificar” <span class="math inline">\(x_0\)</span> en el sentit del Teorema <a href="repàs-de-la-distribució-normal.html#thm:tipi">1.3</a>.</p>
<p>Si la variable poblacional és normal, com més gran és el valor absolut del z-score de <span class="math inline">\(x_0\)</span>, més “rar” és <span class="math inline">\(x_0\)</span>; el signe ens diu si és més gran o més petit que el valor esperat <span class="math inline">\(\mu\)</span>.</p>

<div class="example">
<span id="exm:unnamed-chunk-48" class="example"><strong>Exemple 1.4  </strong></span>Recordau que, segons l’OMS, les altures de les dones europees de 18 anys segueixen una llei <span class="math inline">\(N(163.1,18.53)\)</span>. Quin és el z-score d’una jugadora de bàsket de 18 anys que faci 191 cm?
</div>

<p>Serà:
<span class="math display">\[ 
\frac{191-163.1}{18.53}=1.5
\]</span>
Això normalment es llegeix dient que aquesta alçada “està a 1.5 sigmes de l’alçada mitjana.”</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="index.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="estimació-puntual.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "subsection",
"download": ["pdf", "epub"]
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
